### ISSUE TITLE
Linux release with adapters CI fails with "Failed to download metadata for repo 'appstream'"

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#10016]
### Problem description

https://github.com/facebookincubator/velox/actions/runs/9349519365/job/25731004184?pr=10015

```
+ yum install -y cuda-nvcc-11-8 cuda-cudart-devel-11-8
CentOS Stream 8 - AppStream                     429  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
Error: Process completed with exit code 1.
```

CC: @majetideepak @assignUser @kgpai 

### System information

n/a

**Comment by assignUser** [comment]
Ah, this is due to: #9879 I wasn't aware they would turn off the repos immediately.  There is a PR open to upgrade our images but in the mean time it should be possible to disable that cuda step as there should be a cuda version available in the adapters image.

**Comment by mbasmanova** [comment]
CC: @Yuhta

**Comment by majetideepak** [comment]
I don't think we install any CUDA library by default. I don't see any thing at `ls /usr/local/cuda*`.
Disabling CUDA/GPU build is a temporary workaround. https://github.com/facebookincubator/velox/pull/10025

**Comment by Yuhta** [comment]
CC: @luhenry

**Comment by luhenry** [comment]
Couldn't we simply use the Centos 9 repositories for nvidia packages? https://developer.nvidia.com/cuda-downloads?target_os=Linux&target_arch=x86_64&Distribution=RHEL&target_version=9&target_type=rpm_network

**Comment by majetideepak** [comment]
> Couldn't we simply use the Centos 9 repositories for nvidia packages?

We are migrating the CI images to use Centos 9 here https://github.com/facebookincubator/velox/pull/9903
