### ISSUE TITLE
Having issue with Velox Slack

### ISSUE THREAD

**Issue by xumingming** [facebookincubator/velox#1006]
Hello, when I try to register Velox Slack, I was redirected to the following page:

![image](https://user-images.githubusercontent.com/379733/152927331-a32ebc77-a127-4b65-990d-092bcb88281b.png)

It seems that only person from Meta can use the Velox Slack, is it true?

**Comment by LantaoJin** [comment]
It still can login via "I have a guest account"

**Comment by xumingming** [comment]
@LantaoJin I don't have a "guest account" yet.

**Comment by LantaoJin** [comment]
> @LantaoJin I don't have a "guest account" yet.

Have you logged in Slack before? You can use that email (account) and click `reset the password`.

**Comment by xumingming** [comment]
I used Slack before in other open source projects(Alluxio, Presto), but not for Velox. By doing what you suggested, I got the following email:

![image](https://user-images.githubusercontent.com/379733/152974057-e71651e3-a993-4edb-8898-aa5debb8ffdb.png)

**Comment by LantaoJin** [comment]
Could you leave your account here, I have a try to invite you to the channel. @xumingming

**Comment by xumingming** [comment]
@LantaoJin xumingmingv at gmail.com 

thanks!

**Comment by LantaoJin** [comment]
> @LantaoJin xumingmingv at gmail.com
> 
> thanks!

Seems only a person who is already in the org can be invited to the channel now.

**Comment by xumingming** [comment]
@LantaoJin by "org" you mean "Meta" or the companies(e.g. Intel, Ahana) that is also participating in the project developing?

So the Velox Slack is closed for the outside world?

**Comment by LantaoJin** [comment]
> @LantaoJin by "org" you mean "Meta" or the companies(e.g. Intel, Ahana) that is also participating in the project developing?
> 
> So the Velox Slack is closed for the outside world?

I don't know. I have a guest account of Meta Slack. Slack channels themselves are grouped by enterprises. I guess it may close the registration if you could not find the register page.

**Comment by kgpai** [comment]
Hi @jijufb , Can you help them out ?

**Comment by jijufb** [comment]
I can invite external folks to our Slack channel. Please share email address to send invitation.

**Comment by jijufb** [comment]
I believe the email address is - xumingmingv@gmail.com.
I have send slack invitation to this email account. Please check and confirm.

Let me know if any issues accessing slack workspace.

**Comment by xumingming** [comment]
Thanks @jijufb , closing it.
