### ISSUE TITLE
format_datetime fails with +00:00 not found in timezone database

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#10101]
### Bug description

```
TEST_F(DateTimeFunctionsTest, xxx) {
  auto r = evaluateOnce<std::string>(
      "format_datetime(from_unixtime(0.0, 'UTC'), 'yyyy-MM-dd HH:mm:ss')",
      std::optional(123));

  ASSERT_TRUE(r.has_value());
  LOG(ERROR) << r.value();
}

[ RUN      ] DateTimeFunctionsTest.xxx

terminate called after throwing an instance of 'facebook::velox::VeloxUserError'
  what():  Exception: VeloxUserError
Error Source: USER
Error Code: INVALID_ARGUMENT
Reason: +00:00 not found in timezone database
Retriable: False
Context: Top-level Expression: format_datetime(0:TIMESTAMP WITH TIME ZONE, yyyy-MM-dd HH:mm:ss:VARCHAR)
```

Similar errors:

- Etc/GMT+7:  -07:00 not found in timezone database
- Etc/GMT+8: +08:00 not found in timezone database

They come from date::locate_zone("+00:00").

CC: @pedroerp @amitkdutta 

### System information

n/a

**Comment by PHILO-HE** [comment]
FYI. Quote:
_"date::locate_zone() only recognizes IANA time zone names. Here is a list of the IANA time zone names: 
https://en.wikipedia.org/wiki/List_of_tz_database_time_zones"_

Source https://github.com/HowardHinnant/date/issues/823#issuecomment-2059351689.

**Comment by mbasmanova** [comment]
@pedroerp Pedro, any update on this?

**Comment by pedroerp** [comment]
> @pedroerp Pedro, any update on this?

I haven't had the time to start on this yet. Unless anyone has bandwidth to take this first, my plan is to start early next week.

**Comment by pedroerp** [comment]
This is the last one to address this Issue:

https://github.com/facebookincubator/velox/pull/10606/
