### ISSUE TITLE
clang-format:75:1: error: unknown key 'InsertNewlineAtEOF'

### ISSUE THREAD

**Issue by zhli1142015** [facebookincubator/velox#10236]
### Problem description

```
/home/runner/work/velox/velox/.clang-format:75:1: error: unknown key 'InsertNewlineAtEOF'
InsertNewlineAtEOF: true
^~~~~~~~~~~~~~~~~~
Error reading /home/runner/work/velox/velox/.clang-format: Invalid argument
```

### System information

https://github.com/facebookincubator/velox/actions/runs/9556237249/job/26341092762?pr=10218

### CMake log

```bash
https://github.com/facebookincubator/velox/actions/runs/9556237249/job/26341092762?pr=10218
```

**Comment by zhli1142015** [comment]
cc @kevinwilfong and @pedroerp , thanks.

**Comment by liujiayi771** [comment]
This may need Clang 19 https://clang.llvm.org/docs/ClangFormatStyleOptions.html

**Comment by zhli1142015** [comment]
Looks this is fixed by https://github.com/facebookincubator/velox/commit/b37ceb4569019e9b9b5b764c0882e627a0b4b640 

https://github.com/facebookincubator/velox/actions/runs/9557979924/job/26345937476?pr=10218

**Comment by kevinwilfong** [comment]
This was fixed in https://github.com/facebookincubator/velox/pull/10234 I'm going to add the check back
