### ISSUE TITLE
Dead lock when adding child memory pool with already existing name

### ISSUE THREAD

**Issue by zhztheplayer** [facebookincubator/velox#10342]
This causes the intended error `Child memory pool {} already exists in {}` never get raised.

Code that acquired lock:

https://github.com/facebookincubator/velox/blob/cc6ac918c3b30ad47eb459effcf5065b3a3dbd20/velox/common/memory/MemoryPool.cpp#L349-L355

Code that awaits for lock:

https://github.com/facebookincubator/velox/blob/cc6ac918c3b30ad47eb459effcf5065b3a3dbd20/velox/common/memory/MemoryPool.cpp#L276-L288

Call stack:

```
syscall 0x00007f09e70f073d
folly::detail::nativeFutexWaitImpl Futex.cpp:126
folly::detail::futexWaitImpl Futex.cpp:254
folly::detail::futexWait<…> Futex-inl.h:94
folly::SharedMutexImpl::WaitForever::doWait SharedMutex.h:738
folly::SharedMutexImpl::futexWaitForZeroBits<…> SharedMutex.h:1191
folly::SharedMutexImpl::yieldWaitForZeroBits<…> SharedMutex.h:1158
folly::SharedMutexImpl::waitForZeroBits<…> SharedMutex.h:1122
folly::SharedMutexImpl::waitForZeroBits<…> SharedMutex.h:1111
folly::SharedMutexImpl::lockSharedImpl<…> SharedMutex.h:1486
folly::SharedMutexImpl::lockSharedImpl<…> SharedMutex.h:1359
folly::SharedMutexImpl::lock_shared SharedMutex.h:491
std::shared_lock::lock SharedMutex.h:1684
std::shared_lock::shared_lock SharedMutex.h:1634
facebook::velox::memory::MemoryPool::visitChildren(const std::function<…> &) const MemoryPool.cpp:280
facebook::velox::memory::MemoryPoolImpl::usedBytes MemoryPool.cpp:699
facebook::velox::memory::MemoryPoolImpl::toStringLocked[abi:cxx11]() const MemoryPool.h:944
facebook::velox::memory::MemoryPoolImpl::toString[abi:cxx11]() const MemoryPool.h:670
facebook::velox::memory::MemoryPool::addAggregateChild MemoryPool.cpp:350
```

**Comment by zhztheplayer** [comment]
cc @xiaoxmeng

**Comment by lingbin** [comment]
@zhztheplayer   The call stack you gave is very helpful, and I feel like I already know the cause of the problem, I can write a cause analysis of this problem soon.

I can give a quick fix if you are not working on this bug.    

In addition, I am curious: in what scenario would you try to add a child node with a duplicate name? Can you share a little bit?

**Comment by lingbin** [comment]
@zhztheplayer  Created #10400 to fix this bug.
