### ISSUE TITLE
CI Linux release with adapters is broken

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#10352]
### Problem description

Example job: https://github.com/facebookincubator/velox/actions/runs/9720416362/job/26831774050
This is likely due to changes from https://github.com/facebookincubator/velox/pull/9992

``
/usr/bin/ccache /opt/rh/gcc-toolset-12/root/bin/g++ -DFOLLY_HAVE_INT128_T=1 -DVELOX_ENABLE_ABFS -DVELOX_ENABLE_GCS -DVELOX_ENABLE_HDFS3 -DVELOX_ENABLE_PARQUET -DVELOX_ENABLE_S3 -I/usr/local/cuda-12.4/targets/x86_64-linux/include -I/__w/velox/velox/_build/release/_deps/protobuf-src/src -I/__w/velox/velox/. -I/__w/velox/velox/velox/external/xxhash -isystem /__w/velox/velox/velox -isystem /__w/velox/velox/velox/external -mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17 -mbmi2 -D USE_VELOX_COMMON_BASE -D HAS_UNCAUGHT_EXCEPTIONS -Wall -Wextra -Wno-unused        -Wno-unused-parameter        -Wno-sign-compare        -Wno-ignored-qualifiers        -Wnon-virtual-dtor        -Wno-implicit-fallthrough          -Wno-class-memaccess          -Wno-comment          -Wno-int-in-bool-context          -Wno-redundant-move          -Wno-array-bounds          -Wno-maybe-uninitialized          -Wno-unused-result          -Wno-format-overflow          -Wno-strict-aliasing -Werror -O3 -DNDEBUG -std=gnu++17 -fPIC -fdiagnostics-color=always -MD -MT velox/dwio/parquet/thrift/CMakeFiles/velox_dwio_parquet_thrift.dir/ParquetThriftTypes.cpp.o -MF velox/dwio/parquet/thrift/CMakeFiles/velox_dwio_parquet_thrift.dir/ParquetThriftTypes.cpp.o.d -o velox/dwio/parquet/thrift/CMakeFiles/velox_dwio_parquet_thrift.dir/ParquetThriftTypes.cpp.o -c /__w/velox/velox/velox/dwio/parquet/thrift/ParquetThriftTypes.cpp
In file included from /__w/velox/velox/velox/dwio/parquet/thrift/ParquetThriftTypes.cpp:23:
/__w/velox/velox/velox/dwio/parquet/thrift/ParquetThriftTypes.h:25:10: fatal error: thrift/TApplicationException.h: No such file or directory
   25 | #include <thrift/TApplicationException.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
``

### System information

CircleCI

**Comment by PHILO-HE** [comment]
Just created a pr to fix this issue: https://github.com/facebookincubator/velox/pull/10355.

**Comment by majetideepak** [comment]
Let's merge https://github.com/facebookincubator/velox/pull/10360 as a fix for CI while @PHILO-HE is working on fixing the thrift dependency when using the system arrow.
