### ISSUE TITLE
`setup-adapters.sh` script doesn't work on ARM Linux machines

### ISSUE THREAD

**Issue by ashkrisk** [facebookincubator/velox#10386]
### Bug description

The `setup-adapters.sh` script installs non-core dependencies for Velox. Running this script on an `aarch64` Linux machine results in the following error:
```
+ yum list installed minio
+ rpm -i minio-20220526054841.0.0.x86_64.rpm
        package minio-0:20220526054841.0.0-1.x86_64 is intended for a different architecture
```

This is because the `setup-adapters.sh` script assumes that the architecture is `x86_64` whenever the OS type is Linux.

### System information

Velox System Info v0.0.2
Commit: 63ccecaa2812c70aa7b2cda7a3a4b43abe0af223
CMake Version: 3.26.5
System: Linux-6.5.0-42-generic
Arch: aarch64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.4.1
C Compiler: /usr/bin/cc
C Compiler Version: 11.4.1
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by majetideepak** [comment]
This PR fixes this and simplifies the Minio install https://github.com/facebookincubator/velox/pull/10373
