### ISSUE TITLE
Velox doesn't support to read binary as string in Parquet

### ISSUE THREAD

**Issue by kevincmchen** [facebookincubator/velox#10398]
### Problem description

we'll use spark ,that has the native engine(velox) by gluten, and impala  to read same parquet files in our data warehouse.
the bug is that spark threw the following error while reading parquet file that is generated by impala. 

<img width="710" alt="parquet_bug" src="https://github.com/facebookincubator/velox/assets/68981916/db1dd602-5789-4480-bf12-4b3b8def356c">

Here are my steps of operation:
1. create parquet table test by spark
`CREATE  TABLE test (
`did` INT, 
`data_day` STRING
)
USING parquet`

2. insert values by impala
`insert into test values(1, '20240703')`

3. select by spark
`select * from test limit 10`

After my careful investigation, it is due to Impala writing string-type data as binary into Parquet files, and Velox's ParquetReader does not support binaryAsString.
  

### System information

Velox System Info v0.0.2
Commit: e0300dc15e1e939d23611f65c581bdb36ffa699c
CMake Version: 3.28.3
System: Linux-5.4.203-1-tlinux4-0011
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr/local/lib/python3.8/dist-packages/cmake/data;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by yingsu00** [comment]
@kevincmchen Will you please attach the Parquet file here?

**Comment by yingsu00** [comment]
@kevincmchen Is the DATA_DAY column of VARBINARY type in Velox?

**Comment by kevincmchen** [comment]
@yingsu00  the DATA_DAY in parquet is byte_array， the default type in velox is VARBINARY

**Comment by kevincmchen** [comment]
> @kevincmchen Will you please attach the Parquet file here?

sorry, the file is in our online hadoop cluster, we can't download the file.

**Comment by kevincmchen** [comment]
> @kevincmchen Will you please attach the Parquet file here?

[bb4fc17563709e2c-39e8c8be00000000_2087878052_data.0.parq.zip](https://github.com/user-attachments/files/16177042/bb4fc17563709e2c-39e8c8be00000000_2087878052_data.0.parq.zip)

@yingsu00  this is the Parquet file.

**Comment by yingsu00** [comment]
PR: https://github.com/facebookincubator/velox/pull/10399

**Comment by majetideepak** [comment]
Resolved by https://github.com/facebookincubator/velox/pull/10399
