### ISSUE TITLE
Questions about the unsupported PlanNodes in CodeGen

### ISSUE THREAD

**Issue by markjin1990** [facebookincubator/velox#1040]
Hi! I am trying to run presto + velox with CodeGen turned on, and found that most SQL execution will get stuck. This might be caused by the fact that codegen analysis/compilation for some of the plan node types (e.g., LimitNode) are not yet supported ([CodegenASTAnalysis.h](https://github.com/facebookincubator/velox/blob/main/velox/experimental/codegen/CodegenASTAnalysis.h#L58), [CompiledExpressionAnalysis.h](https://github.com/facebookincubator/velox/blob/main/velox/experimental/codegen/CompiledExpressionAnalysis.h#L79), [CodegenCompiledExpressionTransform.h](https://github.com/facebookincubator/velox/blob/main/velox/experimental/codegen/CodegenCompiledExpressionTransform.h#L101)) and exceptions "Unknown node type" will be thrown when velox tries code generation on plans with such nodes. Correct me if I am wrong.

If my observation is expected and my analysis is correct, may I ask if there is immediate plan that the support for the rest of plan nodes will be added in velox or this is something low-priority?

**Comment by mbasmanova** [comment]
@markjin1990 At this moment we are not actively developing codegen functionality. I'm curious about the motivation for using codegen. Have you have tried non-codegen path already and are you seeing inefficiencies you are hoping to "fix" using codegen?

CC: @laithsakka

**Comment by markjin1990** [comment]
> @markjin1990 At this moment we are not actively developing codegen functionality. I'm curious about the motivation for using codegen. Have you have tried non-codegen path already and are you seeing inefficiencies you are hoping to "fix" using codegen?
> 
> CC: @laithsakka

Thank you Marsh for answering the question! At this moment, I p. My long-term plan is to explore opportunities

**Comment by markjin1990** [comment]
Thank you @mbasmanova for answering the question. I am simply playing with the existing codegen in velox and found out that the code compilation time could take >5s in tests like [CodegenBenchmarks.cpp](https://github.com/facebookincubator/velox/blob/main/velox/experimental/codegen/benchmark/CodegenBenchmarks.cpp). That's why I was trying to run prestocpp+velox with codegen turned on to see if the long compilation time also occurs when handling real SQLs. I was hoping to figure out whether the long runtime compilation time is expected and whether there is an opportunity to reduce that.

**Comment by laithsakka** [comment]
Hi @markjin1990,
The work at codegen is suspended for now and hence its not tracked that its still working
with all the changes that are happening in VELOX. since its not being updated nor tracked.

Back to your questions, the codegen for velox was build and meant for Large queries that runs for minutes, 
and hours.  In that case the 5s overhead during query compilation wont matter. 
It was not meat for interactive queries.
