### ISSUE TITLE
Incorrect results when query has filters on info/metadata columns

### ISSUE THREAD

**Issue by nmahadevuni** [facebookincubator/velox#10423]
### Bug description

Following is the sample table with info column "$file_size" also selected in the query. Run multiple inserts on the table to have at least two different files created for the table.

presto:tpch> select regionkey,name,"$file_size" from region2 order by "$file_size";

 regionkey |    name     | $file_size
-----------+-------------+------------
         0 | AFRICA      |        701
         0 | AFRICA      |        820
         3 | EUROPE      |        820
         4 | MIDDLE EAST |        820
         1 | AMERICA     |        881
         2 | ASIA        |        881
         1 | AMERICA     |        882
         2 | ASIA        |        882
         3 | EUROPE      |        896
         4 | MIDDLE EAST |        896
(10 rows)

If we have a filter `"$file_size"=701` in the query, we expect it to return only the first row from above. But it returns all the rows with file_size set to 701, the incorrect result is below.

presto:tpch> select regionkey,name,"$file_size" from region2 where "$file_size"=701;

 regionkey |    name     | $file_size
-----------+-------------+------------
         1 | AMERICA     |        701
         2 | ASIA        |        701
         1 | AMERICA     |        701
         2 | ASIA        |        701
         0 | AFRICA      |        701
         3 | EUROPE      |        701
         4 | MIDDLE EAST |        701
         0 | AFRICA      |        701
         3 | EUROPE      |        701
         4 | MIDDLE EAST |        701
(10 rows)

### System information

Velox System Info v0.0.2
Commit: 6caa7d5351ef4a83acfaebaab7b4389ae3231421
CMake Version: 3.29.3
System: Darwin-23.5.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 15.0.0.15000309
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 15.0.0.15000309
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.29.3;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by Yuhta** [comment]
Velox is not responsible to filter on split property like `$file_size`.  You should filter it in prestp_cpp worker and send only the qualified splits to Velox.

**Comment by yingsu00** [comment]
From @nmahadevuni  Naveen:  Found that we are already filtering splits in InternalHiveSplitFactory when "$path" is there in the filter, will need to extend this to include other info columns and also need to do this for IcebergSplits too.
