### ISSUE TITLE
Aggregation fuzzer is failing in nightly runs

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#10442]
### Description

There is an aggregation fuzzer failure on the main branch in nightly runs: https://github.com/facebookincubator/velox/actions/runs/9867509773/job/27248394740.

**Comment by kagamiori** [comment]
I've checked the recent aggregation fuzzer test failures on set_agg(). It's a false alarm. It was due to a recent change in Presto that makes set_agg() not respect order-by on the inputs. A most recent change (https://github.com/prestodb/presto/commit/6d2e8cb53bedb9e7e245971c8668441ab75c493f) makes set_agg() respect order-by on the inputs again. So our fuzzer test will be fine once we compare results with Presto 0.289. Before that, we can add set_agg to the skip function list to avoid the noise.

**Comment by kgpai** [comment]
@kagamiori Should be safe to close ?
