### ISSUE TITLE
bugs in Conbench performance report

### ISSUE THREAD

**Issue by kevincmchen** [facebookincubator/velox#10473]
### Bug description

i just remove a comment and commit the pr.  the Conbench performance report failed.

<img width="1314" alt="image" src="https://github.com/user-attachments/assets/9f55822d-dc50-49bb-89ed-fb1f031b5dd7">

related pr: [#10465](url)

### System information

Velox System Info v0.0.2
Commit: ad70c9fc6875da8bf7a057e7daa75a981d5e41b9
CMake Version: 3.28.3
System: Linux-5.4.0-181-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr/local/lib/python3.8/dist-packages/cmake/data;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by pedroerp** [comment]
Cc: @assignUser @kgpai

**Comment by assignUser** [comment]
The Fuzzer job you circled in the screenshot is expected to fail for reasons unrelated to the PR some times, though this failure looks like it found an actual issue maybe @pedroerp  https://github.com/facebookincubator/velox/actions/runs/9942173218/job/27464421554?pr=10465#step:6:54

The performance report _shouldn't_ fail on reasons unrelated to the PR but sadly it sometimes does due benchmarking being difficult ^^ In this case it's a pretty clear outlier/false positive https://velox-conbench.voltrondata.run/compare/benchmark-results/06683349688c788b80003ec3bf313991...06694cbdf2b875c58000ac8dd9cc4078/

**Comment by kevincmchen** [comment]
@assignUser  then what should i do, if i want to commit this pr successfully ? recommit it ?

**Comment by assignUser** [comment]
I am not sure what the meta internal rules are but afaik red Fuzzer jobs and performance reports are only prevent a merge when they are related to changes you made (which these are not)

**Comment by kevincmchen** [comment]
I also think so, could you please look into this issue deeply?  @pedroerp @assignUser
