### ISSUE TITLE
How to expose statistics like "branch misses" in CodeGen?

### ISSUE THREAD

**Issue by markjin1990** [facebookincubator/velox#1053]
[CodegenPerf.cpp](https://github.com/facebookincubator/velox/blob/main/velox/experimental/codegen/benchmark/CodegenPerf.cpp#L34) has shown some critical codegen statistics like `branch misses` and `branch instructions`. However, I have not seen any such statistics exposed during running CodegenPerf or any other benchmark tests for Velox. May I ask how can I enable exposing such statistics in velox?

**Comment by pedroerp** [comment]
@laithsakka has more context on that codebase; could you help @markjin1990 here?

**Comment by kkeita** [comment]
@markjin1990  Hello. We do not have a consistent way to export the statistics you are mentioning on the codegen. The example you are seeing was an adoc measurement we did for experimentation. 
We do have an API however to produce the desired statistics (codegen/vector_function/Perf.h), but you would need to insert explicit calls to collect the counter values around the code you are interrested in. 
Hope it helps.

**Comment by pedroerp** [comment]
Closing this one for now. Please re-open if there are any further questions.
