### ISSUE TITLE
Mismatch of chi_squared_cdf() result from Presto Java (within epsilon)

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#10537]
### Description

Expression fuzzer found a mismatch between chi_squared_cdf results in Velox and in Presto-0.289. The mismatch is within epsilon though.

Query: select chi_squared_cdf(c0, c1) from (values (0.0518702557310462, 0.3271371030714363)) t(c0, c1);
Java result: 0.9641484735361332
Velox result: 0.964148473536133

**Comment by Yuhta** [comment]
Why are we marking this as mismatch the first place?

**Comment by mbasmanova** [comment]
CC: @Krishna-Prasad-P-V

**Comment by kagamiori** [comment]
> Why are we marking this as mismatch in the first place? Floating point numbers are compared with delta within epsilon, no?

@Yuhta Our result comparison methods in QueryAssertions.cpp didn't compare this result with epsilon because the rest non-floating-point columns doesn't form unique keys. This is a limitation of our QueryAssertions, so it would be good to extend it.

**Comment by kagamiori** [comment]
Here is where the condition for epsilon comparison was not satisfied in QueryAssertions: https://github.com/facebookincubator/velox/blob/781967c481409b25a7243635ce507a21549a9db0/velox/exec/tests/utils/QueryAssertions.cpp#L1140-L1143

QueryAssertions requires every row to have distinct combination of values at non-floating-point columns so that it can find the corresponding rows between the expected and actual result vectors. This condition was not satisfied in the fuzzer iteration of chi_squared_cdf(), so epsilon comparison was not used. One solution would be to add an additional "row_number" bigint column to the input vector and project this column to the result as well. Then this column would be able to distinctly identify the corresponding rows between the expected and actual result vectors and hence enable the epsilon comparison.

**Comment by kagamiori** [comment]
Closing this issue since QueryAssertions has been extended to apply epsilon comparison on floating-point columns in side complex types: https://github.com/facebookincubator/velox/pull/10927.
