### ISSUE TITLE
json_array_length: Velox throws while Presto returns NULL

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#10541]
### Description

Query: select json_array_length(c0) from (values '(Af*>1+rije-x0}') t(c0);
Presto-0.289 result: NULL
Velox: Throws an exception "TAPE_ERROR: The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc."

**Comment by kagamiori** [comment]
The same behavior difference applies to json_array_contains.

Query: select json_array_contains(c0, c0) from (values '(Af*>1+rije-x0}') t(c0);
Presto-0.289 result: NULL
Velox: Throws an exception "TAPE_ERROR: The JSON document has an improper structure: missing or superfluous commas, braces, missing keys, etc."

**Comment by kagamiori** [comment]
cc @kgpai

**Comment by kevinwilfong** [comment]
Fixed in https://github.com/facebookincubator/velox/pull/10630
