### ISSUE TITLE
array_min: Presto throws while Velox returns non-NULL

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#10543]
### Description

Query: select array_min(c0) from (values array[array[array[0.001], null]]) t(c0);
Presto-0.289: Throws an exception "ARRAY comparison not supported for arrays with null elements".
Velox result: [[0.001], null] 

Another query: select array_min(c0) from (values array[array[1, null]]) t(c0);
Presto-0.289: Throws an exception "ARRAY comparison not supported for arrays with null elements"
Velox result: [1, null]

**Comment by kevinwilfong** [comment]
I think this might be a bug in Presto Java, it compares the element at position 0 with itself, which means that if there is ever a null in the first element it will throw (everything in the first element has to be compared to verify it's equal to itself)

For other elements, the comparison may exit early as soon as it determines it's greater/less than the current candidate so it may not throw even if it has nulls

This seems like inconsistent behavior

**Comment by kevinwilfong** [comment]
https://github.com/prestodb/presto/pull/23323

**Comment by kagamiori** [comment]
array_max has the similar issue.

Query: select array_max(c0) from (values (array[row(1, null)])) t(c0);
Presto-0.289: Throws an exception "null value at position 1"
Velox: Returns a result {field0=1, field1=null}.

**Comment by kevinwilfong** [comment]
The Presto change addresses both functions
