### ISSUE TITLE
poisson_cdf supports more signatures in Velox than in Presto

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#10542]
### Description

Presto only supports poisson_cdf(double, integer): https://github.com/prestodb/presto/blob/9a364cd8d7938535b095b853e29cd3f6ff047bae/presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java#L971-L973.

Velox additionally supports poisson_cdf(double, bigint). 

This doesn't affect Prestissimo because Presto coordinator rejects poisson_cdf(double, bigint) upfront.

**Comment by kagamiori** [comment]
> Does not look like a bug to me?

@Yuhta It doesn't affect Prestissimo indeed. We probably should better just exclude the additional signature in fuzzer.

**Comment by mbasmanova** [comment]
@Yuhta @kagamiori It seems seems a bug that Velox signatures do not match Presto's. Let's fix this.

**Comment by amitkdutta** [comment]
Fixed.
