### ISSUE TITLE
CI Code Format checking failed

### ISSUE THREAD

**Issue by lingbin** [facebookincubator/velox#10550]
### Problem description

In many new PRs, the `Run Checks / Code Format (pull_request)` CI job fails due to formatting checks on `CMakeLists.txt` files.

In #9948, a new `.cmake-format.yaml` file was added to define the format of the `CMakeLists.txt` file, instead of using the default format of the `cmake-format` tool.

For a PR, currently only the modified files will be checked formatting, so for those PRs that modify the `CMakeLists.txt` file, this problem will occur.

Therefore, in order to solve this problem, all `CMakeLists.txt` files should be formatted uniformly once.

### System information

N/A

### CMake log

```bash
N/A
```

**Comment by czentgr** [comment]
I've run into the same problem. Now that I rebased again, the `make format-fix` on MacOS required the additional installation of `pyyaml`. But it is not part of the current setup scripts. So I believe if we use this new format the setup scripts also need to install pyyaml.

**Comment by lingbin** [comment]
@czentgr Tested in #10551, after formatting the CMakeLists.txt file, it can pass CI.

**Comment by czentgr** [comment]
@lingbin Yes, CI will be fine but users running the command locally on their own will not be unless they manually install the pyyaml module, like I did, unless it is already installed for some other reason.

**Comment by assignUser** [comment]
@czentgr sorry I missed that the setup scripts also install the formatting deps. 

I have an issue open to format the entire code base I'll link it here when I'm back.

**Comment by czentgr** [comment]
@assignUser No problem. For MacOS it is here: https://github.com/facebookincubator/velox/blob/40122c6a98de87b4fec33a1c688d1fb9caf251ab/scripts/setup-macos.sh#L73. And it is a simple fix :)

**Comment by majetideepak** [comment]
I opened a PR here to fix the scripts https://github.com/facebookincubator/velox/pull/10553

**Comment by assignUser** [comment]
https://github.com/facebookincubator/velox/issues/10240
