### ISSUE TITLE
find_first: Presto function has default null behavior while Velox function doesn't

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#10564]
### Description

Presto: Returns NULL for the query `select find_first(if(boolean 'true', repeat(smallint '1233', integer '895435987'), c0), cast(null as bigint), (x) -> try_cast(x as BOOLEAN)) from (values (array[1, 2])) t(c0);`

Velox: Throws an exception "(895435987 vs. 10000) Count argument of repeat function must be less than or equal to 10000" in the following unit test.
```
TEST_F(ExprTest, aaa) {
  auto data = makeRowVector({
      makeArrayVectorFromJson<int16_t>({"[1, 2]"}),
  });
  auto actual = evaluate(
      "find_first(if(true::boolean, repeat(1233::smallint, 895435987::integer), c0), null::bigint, (x) -> try_cast(x as BOOLEAN))",
      data);
  auto expected = makeNullConstant(TypeKind::SMALLINT, 1);
  assertEqualVectors(expected, actual);
}
```

**Comment by kevinwilfong** [comment]
It sounds like find_first is using default null behavior at least for the second argument in Presto Java, while in Velox it doesn't have default null behavior.
