### ISSUE TITLE
concat: Presto throws while Velox returns non-NULL

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#10562]
### Description

Query: select concat(c0) from (values '123') t(c0);
Presto-0.289: Throws an exception "There must be two or more concatenation arguments".
Velox: Returns a result '123'.

**Comment by kgpai** [comment]
Shouldnt this be rejected at the co-ordinator level ? Is there concat with one argument ? How does it even get to velox ?

**Comment by kagamiori** [comment]
> Shouldnt this be rejected at the co-ordinator level ? Is there concat with one argument ? How does it even get to velox ?

@kgpai No, this query is not rejected by the Java coordinator. My guess is that the check is inside the concat function in Java, not the expr compiler.

**Comment by kevinwilfong** [comment]
https://github.com/facebookincubator/velox/pull/10625 will address this
