### ISSUE TITLE
Should we disable Simdjson's UTF-8 validation?

### ISSUE THREAD

**Issue by PHILO-HE** [facebookincubator/velox#10639]
### Description

Simdjson has a build option called `SIMDJSON_SKIPUTF8VALIDATION` to control whether to check UTF-8 encoding validity for JSON input. It is OFF by default to not allow illegal UTF-8 encoding. But we recently found Spark disregards illegal UTF-8 encoding in JSON string. If Presto behaves same as Spark on this, we can set `SIMDJSON_SKIPUTF8VALIDATION=ON` at build time, then Simdjson will skip this check at runtime.

@mbasmanova

**Comment by mbasmanova** [comment]
> Spark disregards illegal UTF-8 encoding in JSON string.

@PHILO-HE Would you clarify what that means exactly? Does Spark allow invalid UTF-8 encoding? Do you have an example? We can try the same example in Presto.

**Comment by PHILO-HE** [comment]
> > Spark disregards illegal UTF-8 encoding in json string.
> 
> @PHILO-HE Would you clarify what that means exactly? Does Spark allow invalid UTF-8 encoding? Do you have an example? We can try the same example in Presto.

@mbasmanova, yes, Spark allows invalid UTF-8 encoding. If input contains invalid utf-8 encoded data, NULL is returned when Gluten + Velox is used. Only if I set `SIMDJSON_SKIPUTF8VALIDATION=ON` for simdjson build, the result is consistent with Spark. 

I tried testing Presto with the same parquet file containing invalid utf-8 encoding. Looks presto also allows invalid utf-8 encoding in json parsing, like Spark.

```sql
select json_extract(c1, '$.c') from tbl;
```

Could you help verify the result of Presto + Velox? You can use the parquet file unpacked from [test.tar.gz](https://github.com/user-attachments/files/16467622/test.tar.gz). Thanks!

**Comment by mbasmanova** [comment]
@PHILO-HE In general, I believe there are no guarantees in either Spark or Presto on behavior when input is invalid UTF-8. Hence, I doesn't think we need (or should) try to match such behavior. It might be better to simply say that input is expected to be valid UTF-8 and if not, there will an error or undefined behavior.

See https://prestodb.io/docs/current/functions/string.html#string-functions

CC: @FelixYBW @rui-mo

**Comment by PHILO-HE** [comment]
@mbasmanova, thanks for your comment! I got your point. Now that we know there is no guaranteed behavior for invalid utf-8 input, should we just let Simdjson skip the check? See code [link](https://github.com/simdjson/simdjson/blob/ccf8694510bcf3d7d53fd58cd574d5b78bcc28aa/src/generic/stage1/json_structural_indexer.h#L242). I think JSON parser's performance can be improved if we do that.

**Comment by mbasmanova** [comment]
> JSON parser's performance can be improved if we do that.

I feel it is safer to keep the validation and fail loudly if it fails as opposed to returning some "strange" result and have the user guess what's going on. How much of a perf boost do you observe for valid use cases?

**Comment by PHILO-HE** [comment]
> How much of a perf boost do you observe for valid use cases?
@mbasmanova, I just tested. But no evident perf. gain in my test cases after the validation is disabled. Maybe, only some certain cases (e.g., long json input) can be benefited. We have made some change in Gluten. Let's close this issue. Thanks!

**Comment by mbasmanova** [comment]
> We have made some change in Gluten.

@PHILO-HE Curious, what is this change.

**Comment by PHILO-HE** [comment]
> > We have made some change in Gluten.
> 
> @PHILO-HE Curious, what is this change.

@mbasmanova, we have some users require the output of Gluten + Velox is consistent with Spark. So we just set SIMDJSON_SKIPUTF8VALIDATION=ON to build simdjson lib and then install it.

**Comment by marin-ma** [comment]
Previously, we addressed this issue by adding a patch when building Velox in Gluten: https://github.com/apache/incubator-gluten/pull/6661/files#diff-b41402fae332ead78c4646843c9bcf66a2813203cdc82521c9c9f130b48146db But now we need to move away from this temporary workaround, as it's never a good idea to add patches to Velox in Gluten.

We need to support the SIMDJSON_SKIPUTF8VALIDATION flag in Velox, because the result consistency of Gluten + Velox vs Spark is very important to our customer and to Gluten project, and the customers would never expect inconsistent behaviour during the migration from Spark to Gluten + Velox.

As @mbasmanova said, it's safer to keep the utf8 validation. It can be resolved by adding a CMake option in Velox to enable UTF-8 validation by default, and allowing downstream projects like Gluten to decide whether to disable this flag.

cc: @PHILO-HE
