### ISSUE TITLE
Unnest operator honor kPreferredOutputBatchRows strictly

### ISSUE THREAD

**Issue by jinchengchenghh** [facebookincubator/velox#10655]
### Description

This PR honor kPreferredOutputBatchRows config.
https://github.com/facebookincubator/velox/pull/7051

Now there is the constraint that single row output should be into single batch.
But for this case, an input row has a very large nested array+struct, the output batch size is also large.
So we need to respect kPreferredOutputBatchRows strictly.
There is several strategies:
1. Split the row only if one row output batch size is more than maxOutputBatchSize.
2. Always split the last row to match the output batch size .

I would prefer the second way, it can lead to accurate batch size.
We could add a benchmark to test the performance if we always split the end row.

https://github.com/facebookincubator/velox/pull/7051#issuecomment-2264790839

**Comment by jinchengchenghh** [comment]
CC @mbasmanova @FelixYBW

**Comment by mbasmanova** [comment]
CC: @bikramSingh91 @pedroerp

**Comment by mbasmanova** [comment]
I don't have a strong preference between 1 or 2. 

It would be nice to figure out how to produce batches of a specified "size in bytes", rather than "number of rows". This doesn't have happen right away, but something to keep in mind.
