### ISSUE TITLE
macos-13 and macos-14 CI are failing to build

### ISSUE THREAD

**Issue by kevinwilfong** [facebookincubator/velox#10721]
### Problem description

The macos-13 and macos-14 CI are failing to build with

ld: library 'gtest' not found

It may be due to https://github.com/facebookincubator/velox/pull/10422

### System information

CI

**Comment by kevinwilfong** [comment]
Example

 https://github.com/facebookincubator/velox/actions/runs/10357705644/job/28670309341?fbclid=IwZXh0bgNhZW0CMTEAAR2GshOg-i_nYt9ylHAgJgSy09GU7u7Aijq94bIsJWDfJaZ9Q9MR4ERGIaU_aem_aHcbqh7vfm4kZ2Vp1mat5g

**Comment by assignUser** [comment]
Kind of, it because #10694 added a target linking against `gtest` but #10422 correctly requires the namespaced targets. This happened due to the long delay between the CI run and merging the PR (10422). I'll open a fix
