### ISSUE TITLE
Collect and use columns' mayHaveNulls info for RowContainer

### ISSUE THREAD

**Issue by zhli1142015** [facebookincubator/velox#10776]
### Description

Collect and use columns' mayHaveNulls info for RowContainer.
Problem
We found non nulls columns' `mayHaveNulls` information would be changed from false to true after they are handling by inner join, aggregation and sort. This is because dependent columns of join, key columns of aggregation and all key / dependent columns of sort are considered as containing null values ​​by default in the row container. If the related column doesn't contain null value, this assumption would cause `extractValuesWithNulls` is used for data extraction, which triggers unnecessary null buffers allocations and null bits checking.

Proposed solution
1. Collecting `mayHaveNulls` Information from Input Vectors: If the parameter `trackColumnsMayHaveNulls` is set to true, we initialize the column's `mayHaveNulls` value as false. We then update the column's `mayHaveNulls` with each input vector: column's `mayHaveNulls` |= vector's  `mayHaveNulls`.
2. If a column's `mayHaveNulls` is false, the `extractValuesNoNulls` method will be used to extract values from the row container.

We observed several queries in our TPCDS runs benefited from this. For example:
Query14b
Before
![image](https://github.com/user-attachments/assets/57828ece-6281-47ce-9853-798468af85db)
After
![image](https://github.com/user-attachments/assets/ea3d7445-9654-4f33-a516-938453fe4671)

Query47
Before
![image](https://github.com/user-attachments/assets/4fcf2140-09e4-4e8c-897e-9b1be3da414f)
After
![image](https://github.com/user-attachments/assets/3e07ef35-3cfc-4fe1-ae82-4e51a56d433e)

Query65
Before
![image](https://github.com/user-attachments/assets/4d4d2c1c-2afa-47be-b6cc-b808d69989cc)
After
![image](https://github.com/user-attachments/assets/85082d30-1c1d-47f3-b24a-5784b1546cef)

Query72
Before
![image](https://github.com/user-attachments/assets/1c3ce5bf-1301-4f96-b39e-c991ea28ad59)
After
![image](https://github.com/user-attachments/assets/c08739ad-5fa9-4236-be7f-d52556a7eb63)

Query95
Before
![image](https://github.com/user-attachments/assets/464161b2-6334-4cc3-949a-d4f34495b4a6)
After
![image](https://github.com/user-attachments/assets/8da2e0a3-6cfc-4b9b-bf86-2a1df8f052cc)

**Comment by zhli1142015** [comment]
Hello @mbasmanova  and @Yuhta,
Could you please help to check, https://github.com/facebookincubator/velox/pull/10775?
Thanks.

**Comment by mbasmanova** [comment]
@zhli1142015 Thank you for sharing these findings.

> We observed several queries in our TPCDS runs benefited from this. For example:

I see multiple screenshots, but I find it hard to get the big picture of the improvement. Would you update PR description to summarize the performance gains you observed?

**Comment by zhli1142015** [comment]
Updated, thanks.
