### ISSUE TITLE
Support reading fields with non-ASCII names

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#10796]
### Description

Currently the tokenizer only considers ASCII characters, and to read fields with non-ASCII names results in an exception with the message 'Invalid subfield path'.

A reproducible unit test is available at https://github.com/rui-mo/velox/commit/8dc1ea41d378e42d38502d29caf13eac0614a2c2. To make this test work, a temporary change was made to the 'isUnquotedSubscriptCharacter' function by removing 'isalnum'.

To fix this issue, shall we support UTF-8 characters in the Tokenizer, for example, by replacing 'isalnum' with 'u_isalnum' in the ICU library?

**Comment by Yuhta** [comment]
Gluten should parse the field names into `Subfield` directly without using the `Tokenizer` (which we will rename into `PrestoTokenizer`).

**Comment by rui-mo** [comment]
@Yuhta Thanks for your feedback. I will take a look.

**Comment by rui-mo** [comment]
This issue can be solved with the solution recommended above. Thanks.
