### ISSUE TITLE
`StringEncodingMode` not defined in velox/functions/lib/string/StringCore.h

### ISSUE THREAD

**Issue by markjin1990** [facebookincubator/velox#1082]
The CodeGen generated code may contain `functions::stringImpl::upper<functions::stringCore::StringEncodingMode::MOSTLY_ASCII>` and when the compiler compiles the generated code during codegen, it may complain "error: no member named 'StringEncodingMode' in namespace 'facebook::velox::functions::stringCore'".

My guess is that `functions::stringCore::StringEncodingMode::MOSTLY_ASCII` stores whether the input strings in runtime are ascii or unicode.

May I ask if `StringEncodingMode::MOSTLY_ASCII` is missed by accident in the current open source version of velox or it is no longer used?

**Comment by kgpai** [comment]
Hi @markjin1990 , StringEncodingMode is no longer used and we just default to ascii or not ascii. The new simple function api allows you to write udfs which can call either ascii only or unicode code paths based on the input. I can point you to some examples if you are interested.

**Comment by mbasmanova** [comment]
@markjin1990 Is this resolved now?

**Comment by markjin1990** [comment]
Yes, appreciate it! @kgpai @mbasmanova
