### ISSUE TITLE
Saprk Fuzzer Test is blocking

### ISSUE THREAD

**Issue by kevincmchen** [facebookincubator/velox#10851]
### Description

https://github.com/facebookincubator/velox/actions/runs/10569348755/job/29283216551?pr=10799

![image](https://github.com/user-attachments/assets/28fb5e37-e9b0-400c-bcf9-a510c8529358)

@assignUser  could you please take a look ?

**Comment by assignUser** [comment]
Duplicate of #10789

**Comment by assignUser** [comment]
It seems to be an intermittent issue that is not/hard to repro locally so there is not much we can do for now, please check the tagged issue.
