### ISSUE TITLE
Build failure of macos-14

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#10901]
### Problem description

The macos-14 build is failing on the main branch, e.g., https://github.com/facebookincubator/velox/actions/runs/10636402809/job/29488130396. 

The failure happens when building targets under velox/functions/sparksql/tests, but I don't see specific error message about why they fails.

### System information

N/A

**Comment by kagamiori** [comment]
cc @assignUser @kgpai

**Comment by kgpai** [comment]
cc: @rui-mo

**Comment by assignUser** [comment]
It seems like there was an update to the runner image, nothing in that dir was changed otherwise. I'll investigate.

**Comment by assignUser** [comment]
It's actually a disk space issue, PR is up
