### ISSUE TITLE
Broken macos 13 and 14 build

### ISSUE THREAD

**Issue by bikramSingh91** [facebookincubator/velox#10936]
### Bug description

both MacOS 13 and 14 builds are breaking intermittently. The ones failing seem to be using pre-release image.

### System information

Eg: 
OS 13: 
passed: https://github.com/facebookincubator/velox/actions/runs/10724693510/job/29740898530 (this uses an relatively older image: https://github.com/actions/runner-images/releases/tag/macos-13%2F20240825.1)
failed: https://github.com/facebookincubator/velox/actions/runs/10709032825/job/29692726504 (this uses a pre-release image: https://github.com/actions/runner-images/releases/tag/macos-13%2F20240901.3)

OS 14:
passed: https://github.com/facebookincubator/velox/actions/runs/10724693510/job/29740899057 ( relatively older image: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240827.4)
failed: https://github.com/facebookincubator/velox/actions/runs/10724607009/job/29740627074 (prerelease image: https://github.com/actions/runner-images/releases/tag/macos-14-arm64%2F20240903.5)

**Comment by majetideepak** [comment]
https://github.com/facebookincubator/velox/pull/10933
