### ISSUE TITLE
`hour(from_unixtime())`: Presto and Velox return different results

### ISSUE THREAD

**Issue by pramodsatya** [facebookincubator/velox#10945]
### Bug description

Tested with expression: `hour(from_unixtime(9.98489045321E8))`

[Expected behavior]
In Presto:
```
presto> select hour(from_unixtime(9.98489045321E8));
 _col0
-------
     7
(1 row)
```

[actual behavior]
In Presto native:
```
presto> select hour(from_unixtime(9.98489045321E8));
 _col0
-------
    14
(1 row)
```

Issue can be reproduced in velox with unit test:
```
TEST_F(DateTimeFunctionsTest, test) {
  const auto evalExpr = [&](std::optional<double> t) {
    return evaluateOnce<int64_t>("hour(from_unixtime(c0))", t);
  };

  EXPECT_EQ(evalExpr(9.98489045321E8), 7);
}
```
Output:
```
Expected equality of these values:
  evalExpr(9.98489045321E8)
    Which is: (14)
  7
```

### System information

Velox System Info v0.0.2
Commit: 81a283fed3c926eee2fe2604f57a8cadd1c55666
CMake Version: 3.30.2
System: Darwin-23.6.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 15.0.0.15000309
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 15.0.0.15000309
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.30.2;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local
  

cc: @tdcmeehan @aditi-pandit @czentgr

**Comment by kevinwilfong** [comment]
Looks related to timezones, I tried this test in Velox and it passes

TEST_F(DateTimeFunctionsTest, test) {
  const auto evalExpr = [&](std::optional<double> t) {
    return evaluateOnce<int64_t>("hour(from_unixtime(c0))", t);
  };

  setQueryTimeZone("America/Los_Angeles");

  EXPECT_EQ(evalExpr(9.98489045321E8), 7);
}

**Comment by pramodsatya** [comment]
Thanks for the fix @kevinwilfong.
