### ISSUE TITLE
Ubuntu 20.04 install gcc11 instead of gcc9

### ISSUE THREAD

**Issue by czentgr** [facebookincubator/velox#10953]
### Description

When Velox starts building with C++20 standard the compiler toolchain needs to be updated and gcc11 will be the minimum supported version. Because Ubuntu 20.04 LTS is still around the setup script needs to change and install gcc11 (instead of keep installing gcc9).

Eventually, the CMake will enforce the supported compiler version.

**Comment by PHILO-HE** [comment]
I note the recently folly is upgrade. Seems it requires gcc version >10. https://github.com/facebookincubator/velox/commit/3fabdf5cf7827c1308736b2b78a6a8dc4c64ef40

**Comment by czentgr** [comment]
@PHILO-HE Ok, looks like we have to move up gcc for Ubuntu 20.04 faster than expected. Recommended is using gcc11. We haven't run the recent upgraded folly with gcc9 so missed any potential issue.

**Comment by czentgr** [comment]
@PHILO-HE In fact, Ubuntu 20.04 has a few problems right now independent of gcc11.

1. setup script is not installing CMake PkgConfig used by a few modules (RE2).
2. https://github.com/facebookincubator/velox/pull/9374 added Gtest features only available in gtest 1.11 while system default in Ubuntu 20.04 is 1.10.

This begs the question if we can discontinue supporting Ubuntu 20.04 as a build environment?

**Comment by PHILO-HE** [comment]
> @PHILO-HE In fact, Ubuntu 20.04 has a few problems right now independent of gcc11.
> 
> 1. setup script is not installing CMake PkgConfig used by a few modules (RE2).
> 2. [Improve duplicated key error message #9374](https://github.com/facebookincubator/velox/pull/9374) added Gtest features (`Throws`) only available in Gtest 1.11 while system default in Ubuntu 20.04 is 1.10. So we'd need to move to a build&install for Gtest.
> 
> This begs the question if we can discontinue supporting Ubuntu 20.04 as a build environment?

@czentgr, thanks for your check! cc @majetideepak, @assignUser, @kgpai

**Comment by majetideepak** [comment]
> This begs the question if we can discontinue supporting Ubuntu 20.04 as a build environment?

The first issue can be fixed by installing the missing package. I will fix the second issue by using `VELOX_EXPECT_THROW`
The Ubuntu 20.04 end of standard support in April 2025. We should support it until then.

**Comment by majetideepak** [comment]
https://github.com/facebookincubator/velox/pull/11270

**Comment by PHILO-HE** [comment]
@majetideepak, I agree to keep supporting ubuntu 20.04. @czentgr, could you help upgrade gcc for this os?

**Comment by czentgr** [comment]
@PHILO-HE Sure. I am working on a PR for that (where I found the additional issues).
