### ISSUE TITLE
`array_normalize` does not support `int128_t` due to lack of `std::abs(int128_t)` on macOS

### ISSUE THREAD

**Issue by zuyu** [facebookincubator/velox#11178]
### Bug description
#11173 introduces several int types for `array_normalize`, but only tested for the `int` type.

Moreover, the underlying implementation uses `std::abs`, which lacks of the `int128_t` version, and thus causes build errors on macOS.

https://github.com/facebookincubator/velox/blob/4f1140247e2f5059abd8f71b2ae54e3d1dcf1be2/velox/functions/prestosql/ArrayFunctions.h#L613

As a workaround for the build issue, comment out the problematic line.

https://github.com/facebookincubator/velox/blob/4f1140247e2f5059abd8f71b2ae54e3d1dcf1be2/velox/functions/prestosql/registration/ArrayFunctionsRegistration.cpp#L315

### System information

Velox System Info v0.0.2
Commit: 4f1140247e2f5059abd8f71b2ae54e3d1dcf1be2
CMake Version: 3.30.4
System: Darwin-24.1.0
Arch: arm64
C++ Compiler: /opt/homebrew/opt/ccache/libexec/c++
C++ Compiler Version: 16.0.0.16000026
C Compiler: /opt/homebrew/opt/ccache/libexec/cc
C Compiler Version: 16.0.0.16000026
CMake Prefix Path: /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX15.1.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.30.4;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local
 

### Relevant logs
https://github.com/facebookincubator/velox/actions/runs/11203696506/job/31141255371
https://github.com/facebookincubator/velox/actions/runs/11203696506/job/31141255572

**Comment by czentgr** [comment]
Fix got merged. Closing.
