### ISSUE TITLE
The conversion from velox MapVector to Arrow MapVector doesn't satisfy the constraint of Arrow in Java

### ISSUE THREAD

**Issue by whutjs** [facebookincubator/velox#11204]
### Bug description

When velox convert the MapVector to Arrow MapVector, velox will set the flag of MapVector to nullable: https://github.com/facebookincubator/velox/blob/acd57170b6d98206def1ef02b74c467e3ba18061/velox/vector/arrow/Bridge.cpp#L1388
However, in the implementation of arrow-java, MapVector is not allowed to be nullable, otherwise an exception is throwed:  
https://github.com/apache/arrow/blob/d4516c5386f84619dfdf2a9f72fed6d7df89704c/java/vector/src/main/java/org/apache/arrow/vector/complex/MapVector.java#L98

### System information

NONE

**Comment by whutjs** [comment]
@pedroerp Would you please take a look at it?

**Comment by pedroerp** [comment]
@whutjs thanks for reporting; this looks wrong indeed. I'll try to take a stab at it tomorrow.

**Comment by whutjs** [comment]
@pedroerp I have fixed this issue in this PR: https://github.com/facebookincubator/velox/pull/11214

**Comment by pedroerp** [comment]
Awesome! I made a small comments to the PR. After that I can get it merged.

**Comment by pedroerp** [comment]
Closing as #11214 has merged. 

Thank you @whutjs !
