### ISSUE TITLE
Hash probe performance regression with https://github.com/facebookincubator/velox/pull/10652

### ISSUE THREAD

**Issue by JunhyungSong** [facebookincubator/velox#11438]
### Bug description

I found that TPC-DS hash probe performance is regressed by ~10% with the PR, https://github.com/facebookincubator/velox/pull/10652. 

### System information

Spark 3.5 & Gluten 1.2.0

**Comment by Yuhta** [comment]
@tanjialiang Some good candidates to address during code freeze

**Comment by FelixYBW** [comment]
@JunhyungSong would you like to fix the regression?

**Comment by JunhyungSong** [comment]
I have no time now. Will try in December if no one takes this until then.

**Comment by Yuhta** [comment]
Fixed by #11438
