### ISSUE TITLE
Add ABFS support for Azure service principal auth

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#11568]
### Description

Current ADLS connections are supported through an account-key-based authentication mechanism.
Per the Azure doc, the secured/preferred way of accessing ADLS is using the service principle authentication.
https://learn.microsoft.com/en-us/azure/databricks/connect/storage/azure-storage#azureserviceprincipal

**Comment by majetideepak** [comment]
@zhli1142015 Do you have any thoughts on this?

**Comment by zhli1142015** [comment]
We have Oauth and sas key support internally, if they are needed, we can contribute related code to the community.

**Comment by zhli1142015** [comment]
Sure.
