### ISSUE TITLE
Speed up sparksql target compilation times

### ISSUE THREAD

**Issue by Yohahaha** [facebookincubator/velox#11564]
### Description

Now, all sparksql functions registered in one cpp file, lead to slow compilation time when debug tests or add a new function in each modify-then-compile loop.

I propose to split sparksql registration code into different cpp files to improve compilation parallelism, thus compilation times can be faster.

I will start by splitting the registration code and then extract different types of functions.

@PHILO-HE @rui-mo @mbasmanova

**Comment by PHILO-HE** [comment]
@Yohahaha, do you mean it will be refactored like presto's `RegistrationFunctions.cpp`? If so, it makes sense to me.

**Comment by Yohahaha** [comment]
> @Yohahaha, do you mean it will be refactored like presto's `RegistrationFunctions.cpp`? If so, it makes sense to me.

yes

**Comment by Yohahaha** [comment]
I have two choices:
1. split registration code in one PR, it might be a large PR.
2. split registration code in serval PRs, eg, string, array, bitwise etc.

which one do you prefer?

**Comment by FelixYBW** [comment]
> which one do you prefer?

You may try 1 PR since it's just refactor of function registration.
