### ISSUE TITLE
Compile error when Create MapType instance use Type::create

### ISSUE THREAD

**Issue by zwykmm** [facebookincubator/velox#1170]
https://github.com/facebookincubator/velox/blob/5176ce40f4612998d792990229b74bdc6cbf11af/velox/type/Type.h#L452

the follow code compile fail:
```cpp
std::shared_ptr<const MapType> MAP(
    std::shared_ptr<const Type> keyType,
    std::shared_ptr<const Type> valType) {
  return Type::create<TypeKind::MAP>(std::move(keyType), std::move(valType));
};
```
Error message:
no matching function for call to 'forward'
Development environment:
clang 13.0.0 c++11

suggest:
```cpp
  template <TypeKind KIND, typename... CHILDREN>
  static std::shared_ptr<const typename TypeTraits<KIND>::ImplType> create(
      CHILDREN... children) {
    return TypeFactory<KIND>::create(std::forward<CHILDREN>(children)...);
  }
```

**Comment by majetideepak** [comment]
C++17 is the standard used by Velox. How are you building the code? Are you using any editor?

**Comment by mbasmanova** [comment]
@zwykmm Have you tried upgrading to C++ 17 ? Do you still experience build failures?

**Comment by mbasmanova** [comment]
@zwykmm Are you still blocked? Have you been able to resolve the issue by upgrading to C++ 17?

**Comment by mbasmanova** [comment]
@zwykmm I haven't heard from you for some time now. I assume you are no longer blocked. I'm going to close this issue, but feel free to reopen if you need further help.
