### ISSUE TITLE
RowContainer's columns' HasNulls info

### ISSUE THREAD

**Issue by zsmj2017** [facebookincubator/velox#11741]
### Description

https://github.com/facebookincubator/velox/pull/11558
and
https://github.com/facebookincubator/velox/pull/10775

Both of these PRs add column-based statistics to RowContainer (the former includes column length information and nullcnt, while the latter only includes nullcnt).

Can we consider merging these two statistics? 
From the current perspective, the changes in PR 10775 can be fully covered by PR 11558 (But PR 10775 is always enabled, while PR 11558 provides an option to decide whether to enable it).

I simply think that the statistical information should come from the same data source as much as possible. Dispersed data sources may lead to certain changes missing part of the logic, which could result in APIs that are supposed to have consistent semantics failing to return the same results.

**Comment by xiaoxmeng** [comment]
@zsmj2017 good point. We can consider to support this. cc @tanjialiang  @zation99

**Comment by zation99** [comment]
@xiaoxmeng @tanjialiang one decision we need to make is, after we merge these two places to add the stats, do we want to enable it by default as what https://github.com/facebookincubator/velox/pull/10775 does, or make it disabled by default as what https://github.com/facebookincubator/velox/pull/11558 does? 
Another choice is that we only make this stats `nullcnt` enabled by default but others disabled by default. Not sure if the effort worths it though.
What do you think?

**Comment by zation99** [comment]
nvm @tanjialiang pointed me to the recent PR that enabled col stats by default: #11731
