### ISSUE TITLE
macos-14 CI fails to download Arrow

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#11871]
### Problem description

https://github.com/facebookincubator/velox/actions/runs/12351544283/job/34466738471?pr=11859

```
          --- LOG END ---
          error: downloading 'https://archive.apache.org/dist/arrow/arrow-15.0.0/apache-arrow-15.0.0.tar.gz' failed
          status_code: 28
          status_string: "Timeout was reached"
          log:
          --- LOG BEGIN ---
          Host archive.apache.org:443 was resolved.
```

### System information

https://github.com/facebookincubator/velox/actions/runs/12351544283/job/34466738471?pr=11859

**Comment by majetideepak** [comment]
@assignUser: I have seen this failure often too. Would you have any thoughts on how to workaround this?

**Comment by kgpai** [comment]
Hmm, the URL does work , re trying to see if its some transient issue : https://github.com/facebookincubator/velox/actions/runs/12351544283?pr=11859

**Comment by kgpai** [comment]
Seems to have passed now . Possibly a transient issue. I will create an issue to bake arrow into our docker image.

**Comment by assignUser** [comment]
The archive servers seem to be overloaded in recent times. We can switch to fetch arrow from the git tag. Long term (2025H2+) archive.a.o will be moved to a CDN in the future that should fix this.

**Comment by majetideepak** [comment]
> We can switch to fetch arrow from the git tag
