### ISSUE TITLE
Abi header being conflict with Arrow's

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#1257]
We found below header would be confict with Arrow's abi.h when including both:
https://github.com/facebookincubator/velox/blob/main/velox/vector/arrow/Abi.h.
Found one way to solve this issue without changing names, that is to move Velox's Abi.h to the same path as Arrow's, and add velox/vector into include path. In this way, compiler will just use the first found one.

**Comment by rui-mo** [comment]
@zhejiangxiaomai Do you know whether we still need this change?

**Comment by zhejiangxiaomai** [comment]
> @zhejiangxiaomai Do you know whether we still need this change?

exactly, we need this now.
