### ISSUE TITLE
implicit conversion from 'std::numeric_limits<long long>::type' (aka 'long long') to 'double' changes value from 9223372036854775807 to 9223372036854775808

### ISSUE THREAD

**Issue by xumingming** [facebookincubator/velox#1280]
FAILED: velox/functions/sparksql/CMakeFiles/velox_functions_spark.dir/RegisterArithmetic.cpp.o
ccache /usr/local/opt/llvm/bin/clang++ -DBOOST_ALL_NO_LIB -DBOOST_CONTEXT_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DCODEGEN_ENABLED=1 -DFMT_LOCALE -DGFLAGS_IS_A_DLL=0 -I/usr/local/opt/icu4c/include -I/Users/abei/Code/velox/. -isystem /usr/local/include -isystem /Users/abei/Code/velox/velox -isystem /Users/abei/Code/velox/velox/external -isystem /Users/abei/Code/velox/velox/external/duckdb -isystem /usr/local/opt/openssl@1.1/include -mavx2 -mfma -mavx -mf16c -mbmi2 -march=native -D USE_VELOX_COMMON_BASE -D HAS_UNCAUGHT_EXCEPTIONS -Werror -Wall -Wextra -Wno-unused        -Wno-unused-parameter        -Wno-sign-compare        -Wno-ignored-qualifiers        -Wno-range-loop-analysis -Wno-mismatched-tags -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -std=gnu++17 -MD -MT velox/functions/sparksql/CMakeFiles/velox_functions_spark.dir/RegisterArithmetic.cpp.o -MF velox/functions/sparksql/CMakeFiles/velox_functions_spark.dir/RegisterArithmetic.cpp.o.d -o velox/functions/sparksql/CMakeFiles/velox_functions_spark.dir/RegisterArithmetic.cpp.o -c /Users/abei/Code/velox/velox/functions/sparksql/RegisterArithmetic.cpp
In file included from /Users/abei/Code/velox/velox/functions/sparksql/RegisterArithmetic.cpp:20:
/Users/abei/Code/velox/./velox/functions/sparksql/Arithmetic.h:99:13: error: implicit conversion from 'std::numeric_limits<long long>::type' (aka 'long long') to 'double' changes value from 9223372036854775807 to 9223372036854775808 [-Werror,-Wimplicit-const-int-float-conversion]
  if (arg > std::numeric_limits<int64_t>::max()) {
          ~ ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[305/830] Building CXX object velox/functions/prestosql/aggregates/CMakeFiles/velox_aggregates.dir/MinMaxByAggregates.cpp.o
ninja: build stopped: subcommand failed.
make[1]: *** [build] Error 1
make: *** [release] Error 2

**Comment by xumingming** [comment]
similar to https://github.com/facebookincubator/velox/issues/1089

**Comment by xumingming** [comment]
@majetideepak

**Comment by majetideepak** [comment]
@xumingming This should be fixed as part of https://github.com/facebookincubator/velox/pull/1240 that got merged yesterday. Can you pull this change and verify?

**Comment by xumingming** [comment]
@majetideepak similar issue, but in different file: functions/sparksql/Arithmetic.h
