### ISSUE TITLE
A little bit hard to understand the arguments peeling in expression evaluation.

### ISSUE THREAD

**Issue by dingqiaoyi** [facebookincubator/velox#1374]
I'm reading the codes of the expression evaluation recently.

I found the vectorized expression evaluation framework is very impressive, especially some features of common subexpression sharing, lazy loading, separating the NULL value handle which is quiet friendly to the intra-core parallelism, as well as the vector reusing strategy.

But I found there is a little bit hard to understand the arguments peeling part. Is there any detailed document explained that or the whole part of expression evaluation design?

Thanks. @oerling @mbasmanova

**Comment by mbasmanova** [comment]
@dingqiaoyi There are a few resources to read about expression evaluation:

- https://facebookincubator.github.io/velox/develop/expression-evaluation.html
- 2.4 Expression Calculation section in https://homepages.cwi.nl/~boncz/snb-challenge/chokepoints-tpctc.pdf

**Comment by mbasmanova** [comment]
@dingqiaoyi Did you find these documents helpful? Do you have any follow-up questions?

**Comment by mbasmanova** [comment]
> Right now I'm trying to add a regex matching function using intel hyperscan.

FYI, we now recommend that all functions are added using Simple Function APIs described in https://facebookincubator.github.io/velox/develop/scalar-functions.html#simple-functions

**Comment by mbasmanova** [comment]
I'm not sure I understand the question.

> I still thought the logics of handling nulls and peeling of encodings in Expr::evalEncodings/Expr::evalWithNulls could be covered by the logics in Expr::evalAll. 

The following diagram shows the differences in these methods: https://facebookincubator.github.io/velox/develop/expression-evaluation.html#evaluation-algorithm

When writing a function, you can assume that if function declares default null behavior it won't be called on null inputs. You can also assume that the engine will do its best to not call function repeatedly on duplicate input values.

**Comment by dingqiaoyi** [comment]
@mbasmanova  My question is about the implementation of that two features.

Take the peeling of encodings as  an example. Similar code snippets can be found both in Expr::evalEcodings （peelEncodings）and Expr::eval （applyFunctionWithPeeling）, but I cannot tell the differences between them.
According to the document,  Expr::evalEncodings are working with the input references of the whole expression ,while  Expr::eval is working with the current expr node's input while traversing the expression tree. 
My question is whether the former case is just a special form of the latter one ? So can we treat the codes in the Expr::evalEcodings as a fast path ？

I believe the same question exists when we talked about the null handling case. (Expr::evalWithNulls vs. Expr::eval)

**Comment by mbasmanova** [comment]
@dingqiaoyi Thank you for clarifying. I think I might know what you are asking about. Expression evaluation is traversing the expression tree depth first. On the way down, peelEncodings is peeling encodings off of the inputs. On the way up, applyFunctionWithPeeling is peeling encodings off of the intermediate results (just computed). In other words, on the way down we are looking at the raw inputs and peeling off shared encodings from these. On the way up, we are looking at intermediate results and peeling off shared encodings from these. Same for nulls. The logic is the same, but the specific details of the implementation are slightly different.

PR #1425 introduced a helper function printExprWithStats which can be used to print expression tree annotated with runtime statistics after evaluation. Among other things, it will show number of rows processed by each node. This could provide a view into whether deduplication (peeling of dictionary / constant encoding) happened or not and where in the tree it occurred.

Hope this helps, but feel free to ask follow-up questions if my answer is not sufficient.

**Comment by mbasmanova** [comment]
@dingqiaoyi Are you still blocked? Anything else we can help with?

**Comment by mbasmanova** [comment]
@dingqiaoyi  We haven't heard from you in awhile. I assume you are no longer blocked and will close this issue. Feel free to reopen if you have any further questions.
