### ISSUE TITLE
Add decimal types

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#1376]
Decimal types have two parameters: precision and scale. Short decimal type supports max precision of 18. Long decimal type supports max precision of 38. Short decimals can be represented using int64_t. Long decimals can be represented using int128_t.

Scalar operations for decimal types:
 - add
 - subtract
 - multiply
 - divide
 - modulus
 - negation

Aggregate functions:
- sum
- avg
- min
- max
- etc.

Presto's implementation:
* presto-common/src/main/java/com/facebook/presto/common/type/DecimalType.java
* presto-main/src/main/java/com/facebook/presto/type/DecimalOperators.java
* presto-main/src/main/java/com/facebook/presto/type/DecimalCasts.java

Design doc: https://docs.google.com/document/d/1YAifFTY6GBVUk4t2LyMRYtgomdSFp-A5dBXdK8jAqNs/edit#heading=h.y4nqvaggm1ci

CC: @aditi-pandit @zzhao0 @laithsakka @kevinwilfong

**Comment by mbasmanova** [comment]
WIP PR from @karteekmurthys : #1402

**Comment by karteekmurthys** [comment]
@mbasmanova thanks for adding the background details and the WIP PR.
Here is a WIP PR for Signature support for Decimal type https://github.com/facebookincubator/velox/pull/1406/
