### ISSUE TITLE
Exception cannot be caught

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#1377]
Found below exception cannot be caught in below code. Instead, the code will stop and print some error messages. If throwing std::runtime_error, it can be caught.
Anything missing here? Thanks for your reply!
 
```
    try {
      std::cout << "will throw exception" << std::endl;
      VELOX_NYI("Child Rel is expected in ProjectRel.");
    } catch (const VeloxException& err) {
      std::cout << "caught" << std::endl; 
    } catch (const std::exception& err) {
      std::cout << "caught std exception" << std::endl;
    }

```

Looks like VELOX_NYI will throw VeloxRuntimeError which extends std::exception.

```
#define VELOX_NYI(...)                                              \
  _VELOX_THROW(                                                     \
      ::facebook::velox::VeloxRuntimeError,                         \
      ::facebook::velox::error_source::kErrorSourceRuntime.c_str(), \
      ::facebook::velox::error_code::kNotImplemented.c_str(),       \
      /* isRetriable */ false,                                      \
      ##__VA_ARGS__)
```

**Comment by mbasmanova** [comment]
@rui-mo Rui, I'm not sure what the question is about, but I'm seeing that VeloxRuntimeError extends VeloxException which extends std::exception. Are you seeing something different?

```
class VeloxRuntimeError final : public VeloxException {

class VeloxException : public std::exception {
```

**Comment by rui-mo** [comment]
@mbasmanova Thanks for your reply.
Yes, it extends them. But the issue I met is I cannot catch any exception with above catch clauses after throwing exception with VELOX_NYI. I can only got below error message, and the program stopped. If I throw std::runtime_error instead, the catch clauses wored well.

```
E20220406 20:27:29.127830 66201 Exceptions.h:68] Line: ../../velox/substrait/SubstraitToVeloxPlan.cpp:270, Function:toVeloxPlan, Expression: Child Rel is expected in ProjectRel., Source: RUNTIME, ErrorCode: NOT_IMPLEMENTED
```

**Comment by mbasmanova** [comment]
@rui-mo I tried your code and it seems to work. I'm running on Mac. What OS do you run on? Which compiler do you use?

```
TEST(A, a) {
  try {
    std::cout << "will throw exception" << std::endl;
    VELOX_NYI("Child Rel is expected in ProjectRel.");
  } catch (const VeloxException& err) {
    std::cout << "caught" << std::endl;
  } catch (const std::exception& err) {
    std::cout << "caught std exception" << std::endl;
  }
}

will throw exception
caught
```

**Comment by mbasmanova** [comment]
@rui-mo Rui, is this resolved now or would like some help?

**Comment by rui-mo** [comment]
@mbasmanova Thanks for your time.
I found the exception was not caught due to missing the dependent library in our project, so the exception thrown did not work well actually. I'm working on fixing the libraries linking issues referring to below code.
```
target_link_libraries(
  velox_exception
  velox_flag_definitions
  velox_process
  glog::glog
  ${FOLLY_WITH_DEPENDENCIES}
  ${FMT}
  ${GFLAGS_LIBRARIES})
```
Closed this issue, and thanks for your attention on it!

**Comment by mbasmanova** [comment]
@rui-mo Thank you for clarifying.
