### ISSUE TITLE
Unsupported filter in parquet reader: BigintValuesUsingHashTable

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#1381]
ParquetTpchTest.Q18 is failing on main:

https://circleci.com/api/v1.1/project/github/facebookincubator/velox/36554/output/110/0?file=true&allocation-id=625024fbab5841206bde4e42-0-build%2F7F7AA1C8

```
110: [ RUN      ] ParquetTpchTest.Q18
110: E0408 12:17:05.578356 10177 Exceptions.h:68] Line: ../../velox/dwio/parquet/reader/ParquetReader.cpp:155, Function:toDuckDbFilter, Expression: Unsupported filter in parquet reader: BigintValuesUsingHashTable: [6882, 29158] no nulls, Source: USER, ErrorCode: UNSUPPORTED
110: E0408 12:17:05.578382 10170 Exceptions.h:68] Line: ../../velox/dwio/parquet/reader/ParquetReader.cpp:155, Function:toDuckDbFilter, Expression: Unsupported filter in parquet reader: BigintValuesUsingHashTable: [6882, 29158] no nulls, Source: USER, ErrorCode: UNSUPPORTED
110: E0408 12:17:05.578362 10173 Exceptions.h:68] Line: ../../velox/dwio/parquet/reader/ParquetReader.cpp:155, Function:toDuckDbFilter, Expression: Unsupported filter in parquet reader: BigintValuesUsingHashTable: [6882, 29158] no nulls, Source: USER, ErrorCode: UNSUPPORTED
110: E0408 12:17:05.578361 10169 Exceptions.h:68] Line: ../../velox/dwio/parquet/reader/ParquetReader.cpp:155, Function:toDuckDbFilter, Expression: Unsupported filter in parquet reader: BigintValuesUsingHashTable: [6882, 29158] no nulls, Source: USER, ErrorCode: UNSUPPORTED
110: unknown file: Failure
110: C++ exception with description "Exception: VeloxUserError
110: Error Source: USER
110: Error Code: UNSUPPORTED
110: Reason: Unsupported filter in parquet reader: BigintValuesUsingHashTable: [6882, 29158] no nulls
110: Retriable: False
110: Function: toDuckDbFilter
110: File: ../../velox/dwio/parquet/reader/ParquetReader.cpp
110: Line: 155
110: Stack trace:
110: # 0  _ZN8facebook5velox7process10StackTraceC1Ei
110: # 1  _ZN8facebook5velox14VeloxExceptionC2EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bS7_
110: # 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_14VeloxUserErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_
110: # 3  _ZN8facebook5velox7parquet16ParquetRowReaderC2ESt10shared_ptrIN6duckdb13ParquetReaderEERKNS0_4dwio6common16RowReaderOptionsERNS0_6memory10MemoryPoolE
110: # 4  _ZNK8facebook5velox7parquet13ParquetReader15createRowReaderERKNS0_4dwio6common16RowReaderOptionsE
110: # 5  _ZN8facebook5velox9connector4hive14HiveDataSource8addSplitESt10shared_ptrINS1_14ConnectorSplitEE
110: # 6  _ZN8facebook5velox4exec9TableScan9getOutputEv
110: # 7  _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_EPS3_INS1_13BlockingStateEE
110: # 8  _ZN8facebook5velox4exec6Driver3runESt10shared_ptrIS2_E
110: # 9  _ZN5folly6detail8function14FunctionTraitsIFvvEE9callSmallIZN8facebook5velox4exec6Driver7enqueueESt10shared_ptrIS9_EEUlvE_EEvRNS1_4DataE
110: # 10 _ZN5folly18ThreadPoolExecutor7runTaskERKSt10shared_ptrINS0_6ThreadEEONS0_4TaskE
110: # 11 _ZN5folly21CPUThreadPoolExecutor9threadRunESt10shared_ptrINS_18ThreadPoolExecutor6ThreadEE
110: # 12 _ZN5folly6detail8function14FunctionTraitsIFvvEE9callSmallISt5_BindIFMNS_18ThreadPoolExecutorEFvSt10shared_ptrINS7_6ThreadEEEPS7_SA_EEEEvRNS1_4DataE
110: # 13 0x0000000000000000
110: # 14 start_thread
110: # 15 clone
110: " thrown in the test body.
110: [  FAILED  ] ParquetTpchTest.Q18 (15 ms)
```

CC: @gggrace14 @majetideepak

**Comment by mbasmanova** [comment]
I wonder if this is due to #1314 - Push down dynamic filters by default

**Comment by majetideepak** [comment]
@mbasmanova the test started failing after https://github.com/facebookincubator/velox/pull/1314. Let's disable the test for now. I want to see if this is a positive or negative improvement of always pushing dynamic filters down.

**Comment by gggrace14** [comment]
Fix proposed is to add support for the following IN-list filters to Parquet reader and toDuckDbFilter(). From a quick lookup, [DuckDb should support IN list](https://github.com/facebookincubator/velox/blob/main/velox/external/duckdb/duckdb.hpp#L5577-L5578).

kBigintValuesUsingHashTable
kBigintValuesUsingBitmask

Will look at details, as well as how we support kBytesValues. Will come back and update.

@majetideepak

**Comment by majetideepak** [comment]
@gggrace14, @mbasmanova  Thanks for looking into this. I also agree that supporting these filter types is best.

**Comment by majetideepak** [comment]
I reopened this to track adding support for BigintValuesUsingHashTable filter in the ParquetReader.

**Comment by majetideepak** [comment]
I did some investigation into this as well. Looks like the issue existed prior to the changes in https://github.com/facebookincubator/velox/pull/1314 but did not show up since we use SF 0.01 for the ParquetTpchTest and the filter never got pushed down as we used to push only after 10'000 rows. However, it would fail for SF 10. Let me know if I can help with the filter implementation in any way.

**Comment by gggrace14** [comment]
> I did some investigation into this as well. Looks like the issue existed prior to the changes in #1314 but did not show up since we use SF 0.01 for the ParquetTpchTest and the filter never got pushed down as we used to push only after 10'000 rows. However, it would fail for SF 10. Let me know if I can help with the filter implementation in any way.

Yeah, that makes a lot of sense. I was thinking why the issues didn't happen before and guess about the 10'000 condition. Thank you, @majetideepak , for helping investigate!

I will be implementing the new filter support. Will ask your help if I have questions :)

**Comment by gggrace14** [comment]
#1423  added support for Velox filter BigintValuesUsingHashTable, which converts to conjunction or of DuckDB filters. DuckDB doesn't have a complete support for IN-list filter, due to lack of comparison operation struct for IN-list, as in https://github.com/facebookincubator/velox/blob/main/velox/external/duckdb/duckdb.hpp#L6475-L6480.
