### ISSUE TITLE
Build fail on ubuntu 20.04

### ISSUE THREAD

**Issue by giulio98** [facebookincubator/velox#1383]
I'm trying to build velox on Ubuntu 20.04 using the provided script setup-ubuntu.sh
These are my steps:
```bash
git clone --recursive https://github.com/facebookincubator/velox.git
cd velox
git submodule sync --recursive
git submodule update --init --recursive
cd scripts/
sudo ./setup-ubuntu.sh
```

Unfortunately, the build fails with the following here due to folly
![image](https://user-images.githubusercontent.com/79860892/162485843-130002b4-e040-4066-8dc1-828a611b303b.png)

I tried using different releases of folly, to no avail.
I don't know how to fix this problem, can anyone please help me ? =)

**Comment by jiangzhx** [comment]
i got same issues on wsl2.

**Comment by dingqiaoyi** [comment]
@giulio98 @jiangzhx 
Removing "--masm=intel" from  the COMPILER_FLAGS could solve this problem.
@mbasmanova Is this flag necessary to build velox, generating the assembly code in Intel syntax?
There seems to be a PR working on removing this flag in the setup-macos.sh
https://github.com/facebookincubator/velox/pull/1336

**Comment by mbasmanova** [comment]
> Removing "--masm=intel" from the COMPILER_FLAGS could solve this problem.
> Is this flag necessary to build velox, generating the assembly code in Intel syntax?

I haven't tried this. Maybe try to see what happens.

@kgpai @mshang816 @Yuhta Krishna, Michael, Jimmy, would you know how to unblock compilation on ubuntu 20.04?

**Comment by Yuhta** [comment]
What I did: https://github.com/facebookincubator/velox/pull/1505/commits/136ef7f97f9cc6a466eef9a98238fc6a8d688a60#diff-c388f86bda09fbfc530dba49b80d1c22912c27c22a8b412d51b405304ccb8810L509-R509

**Comment by mbasmanova** [comment]
@Yuhta Thank you for sharing a workaround. Just to clarify, the change is to replace  __builtin_ia32_tzcnt_u64 call with __builtin_ctzll. Is that right?

**Comment by mbasmanova** [comment]
CC: @fbalicchia Would you like to try the suggestion above from @Yuhta ?

**Comment by Yuhta** [comment]
> @Yuhta Thank you for sharing a workaround. Just to clarify, the change is to replace __builtin_ia32_tzcnt_u64 call with __builtin_ctzll. Is that right?

Yes exactly

**Comment by fbalicchia** [comment]
@mbasmanova sorry I read only now.. Yes I'll try
