### ISSUE TITLE
fix RowSet in LazyVector ensureLoadedRows in constant wrapper branch

### ISSUE THREAD

**Issue by Dream-hu** [facebookincubator/velox#1471]
rowSet should be assigned in isConstantMapping branch:
![image](https://user-images.githubusercontent.com/67504811/165069525-ab3a8ac9-a4b4-4430-a5d8-1fc80f7f3821.png)

**Comment by mbasmanova** [comment]
@kgpai @oerling Is this the crash we are seeing?

**Comment by mbasmanova** [comment]
@Dream-hu You are correct that there is a bug here, but I wonder how did you reproduce this? It seems like this code path may not be possible to hit.

**Comment by mbasmanova** [comment]
@Dream-hu I was able to reproduce this bug and here is a fix: #1477. Thank you for reporting.

**Comment by Dream-hu** [comment]
get,  thx!  btw,  I found this when I was reading the lazy loading related codes, I haven't tested
