### ISSUE TITLE
Build failure on Ubuntu 20.04

### ISSUE THREAD

**Issue by fbalicchia** [facebookincubator/velox#1516]
Hi,
first of all thanks for your work, I found it very interesting.
With revision b160102130d5c I've some trouble compiling on Ubuntu 20.04. I retrieve this error
```
In member function 'void facebook::velox::memory::MmapAllocator::SizeClass::allocateAny(int32_t, facebook::velox::memory::ClassPageCount&, facebook::velox::memory::MachinePageCount&, facebook::velox::memory::MappedMemory::Allocation&)':
../../velox/common/memory/MmapAllocator.cpp:509:15: error: '__builtin_ia32_tzcnt_u64' was not declared in this scope; did you mean '__builtin_ia32_sbb_u64'?
  509 |     int bit = __builtin_ia32_tzcnt_u64(freeBits);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~
```

Here an example on how to reproduce the problem

```
FROM ubuntu:20.04
RUN apt update
WORKDIR /home/root
RUN apt install -y \
	git \ 
	sudo
RUN git clone https://github.com/facebookincubator/velox.git
RUN cd velox; git submodule sync --recursive; git submodule update --init --recursive
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Rome
RUN /home/root/velox/scripts/setup-ubuntu.sh
RUN cd /home/root/velox;make
```

Do I need to make some other step or change g++ version? if so which one thank you for help

**Comment by mbasmanova** [comment]
This might be the same problem as discussed in #1426

CC: @kgpai @Yuhta Krishna, Jimmy, any suggestions about how to fix / workaround?

**Comment by fbalicchia** [comment]
Hi @mbasmanova did you try this https://github.com/facebookincubator/velox/issues/1383#issuecomment-1099028295 ? 
If no tell me that I'll try to address on my side

**Comment by mbasmanova** [comment]
@fbalicchia I haven't tried this. If you try it, let us know how it works.

**Comment by Yuhta** [comment]
This will be fixed in #1505

**Comment by kgpai** [comment]
Hi @fbalicchia , 
Can you paste the contents of /proc/cpuinfo here. It will help us determine if this is Velox not supporting your cpu or something else. As @Yuhta pointed out, with #1505 we should be able to support older intel cpus but we currently dont.

**Comment by fbalicchia** [comment]
```
model name	: Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz
vendor_id	: GenuineIntel
```

**Comment by fbalicchia** [comment]
Tell me please if you need other info. Today I think to try #https://github.com/facebookincubator/velox/pull/1505

**Comment by kgpai** [comment]
Hi @fbalicchia , cat /proc/cpuinfo should give instruction set supported etc, for e.g this is what I see : 

```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 158
model name	: Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
stepping	: 13
cpu MHz		: 2400.000
cache size	: 16384 KB
physical id	: 0
siblings	: 1
core id		: 0
cpu cores	: 1
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 22
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht pbe syscall nx pdpe1gb lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid pni pclmulqdq dtes64 ds_cpl ssse3 sdbg fma cx16 xtpr pcid sse4_1 sse4_2 movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch fsgsbase bmi1 avx2 bmi2 erms xsaveopt arat
bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips	: 4800.00
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
```
Can you post something similar ?

**Comment by fbalicchia** [comment]
Ok, @mbasmanova thanks for the explanation. I'll close the issue thanks

**Comment by fbalicchia** [comment]
Hi, @mbasmanova @Yuhta the fix works for me thanks !.  I saw that some internal tests on cicd fail but I' haven't permission to see details but from my side, on my console, it works. Yes I have other hardware Apple M1 but I haven't tested it yet
