### ISSUE TITLE
Generalize the reader and input interfaces

### ISSUE THREAD

**Issue by yingsu00** [facebookincubator/velox#1533]
Velox will support multiple file formats like Parquet, ORC, Alpha in the future. These readers, like the DWRF reader, shall use some common components like the InputStream's, decoding and decompression utility functions, etc. Further more, they may directly inherit the ColumnReader's that were originally made for DWRF. To prep for the upcoming native Parquet reader, we propose to do the following refactoring: 

# 1. Move SeekableInputStream, BufferredInput, (de)compressor related classes to velox::dwio::common::io
 - #1617
 - #1618

# 2. Move some DWRF utility headers to dwio::common #1619

# 3. Compatibility support with DuckDB parquet reader
 - #1621
 - #1622
 - 
# 4. Generalize the ColumnReader and SelectiveColumnReader classes #1620

# 5. Tests
The tests for the classes that moved to dwio::common will also be moved to that namespace/folders
 - Move velox/dwio/dwrf/test/utils/DataFiles.h&cpp to velox/dwio/common/tests/DataFiles.h&cpp
 - https://github.com/facebookincubator/velox/issues/2032

**Comment by mbasmanova** [comment]
CC: @majetideepak @tanjialiang @oerling @hannes

**Comment by frankobe** [comment]
cc @liushengxuan

**Comment by yingsu00** [comment]
cc @majetideepak @aditi-pandit

**Comment by yingsu00** [comment]
- PR1: https://github.com/facebookincubator/velox/pull/1526
