### ISSUE TITLE
Implement Filter::mergeWith for MultiRange

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#154]
Similar to #153 this task is to implement Filter::mergeWith() for MultiRange filters which represent an OR of two of more filters.

CC: @pedroerp @kgpai @aditi-pandit @majetideepak

**Comment by amaliujia** [comment]
@mbasmanova 

I am a person who is interested in contributing to open source. Looks like this issue is a good one for a starter. May I work on this issue?

**Comment by mbasmanova** [comment]
Welcome, @amaliujia . Sure, feel free to pick this up. CC: @atanu1991 who is working on a related issue #153

**Comment by amaliujia** [comment]
@mbasmanova 

I want to discuss a bit on high level before start to implement.

MultiRange is a class that contains a list of Filter, with nan_allowed and null_allowed. So my current idea of the implementation is:
1. Two MultiRange can merge only if they have the same nan_allowed and null_allowed.
2. Two MultiRange can merge only if they have the same data type on all the Filters.
3. If 1 and 2 are true, then simply have a nested loop to do
```
 for f1 in MultiRangeA.getFilters():
      for f2 in MultiRangeB.getFilters():
           f1.mergeWith(f2);
```

Can you give me some suggestions?

**Comment by mbasmanova** [comment]
Rui,

MultiRange represents and OR of multiple filters. NaN values pass only if MultiRange::nanAllowed is true. Null values pass only if nullAllowed is true.

Merging two filters is combining the filters with an AND. A value passes the new filter only if it passes both the original filters.

Here is how I would represent a merge of two MultiRange filters (with just 2 filters in each for simplicity:

(a OR b) AND (c OR d) = (a AND c) OR (a AND d) OR (b AND c) OR (b AND d)

Therefore, what you have proposed is very close.

1. Calculate nullAllowed for the combined filter: `bool bothNullAllowed = nullAllowed_ && other->testNull();`
1. Calculate nanAllowed for the combined filter: <same as above>
1. Loop over all combinations of filters from left and right side and merge these.
1. Construct a new filter using flags and list of filters from previous steps.

In step (3), make sure to check if a merge of two filter is kAlwaysFalse, kIsNull, kIsNotNull. In this case, the filter can be dropped from the result (null and NaN flags in the nested filters do not count for MultiRange filter; only top-level flags take effect).

Step (3) may result in an empty list of filters or a list of one. If the list is empty, return kAlwaysFalse, kIsNull, or kIsNotNull as appropriate (see nullOrFalse(bothNullAllowed) in Filter.cpp). If the list contains just one filter, return that filter after incorporating the null flag, e.g. if bothNullAllowed && !filter->testNull() return filter.mergeWith(IsNull) else return filter.

That should be it. 

(Check out https://github.com/facebookincubator/velox/pull/233 that implements merge logic for BytesValues and BytesRanges.)

**Comment by amaliujia** [comment]
Thanks @mbasmanova! 

I prepared a WIP impl based on your suggestions: #299.

Can you comment on the PR to see if I am on the right track? 

Sorry to occupy too much of your time. I am a beginner so probably need more guidance at this moment (for example on how to deal with nullness in Volex)? Maybe later I could help to contribute a doc about nullness, nan, always true, always false, is null, is not null with Filter.

**Comment by kgpai** [comment]
Looks like this issue was resolved with https://github.com/facebookincubator/velox/pull/299 . Closing.
