### ISSUE TITLE
check the availableInRun() of the next PageRun in current allocation_ whether satisfied with the preferredSize in AllocationPool::newRun

### ISSUE THREAD

**Issue by Dream-hu** [facebookincubator/velox#1546]
![image](https://user-images.githubusercontent.com/67504811/166889326-4ef89b31-6679-44c5-98a3-56db58d92234.png)

**Comment by mbasmanova** [comment]
@Dream-hu It is hard to read a screenshot. Would you provide a text-based explanation of the problem and proposed solution? Would you like to send a PR?

CC: @oerling
