### ISSUE TITLE
Slack OSS Workspace Invite

### ISSUE THREAD

**Issue by cjgdev** [facebookincubator/velox#1580]
Hi, my apologies for posting this on the issue tracker (it’s not a code issue), but I’m trying to follow the instructions in the README for joining the Velox Slack OSS workspace. I’ve tried sending an email to velox@fb.com, but I’ve not received an acknowledgement in a couple of days. If it’s just a matter of waiting then I will wait, but if there’s anything that can be done to expedite the process then I would appreciate it.

**Comment by mbasmanova** [comment]
CC: @jijufb

**Comment by jijufb** [comment]
Hi Christopher, sorry for the delay. We did not receive email for your request. Checking with IT on the actual reason.

Can you share your email address to send slack invitation?

**Comment by jijufb** [comment]
I have give access. Please check.

**Comment by cjgdev** [comment]
I can confirm I have access, thank you.
