### ISSUE TITLE
Two cases of HashJoin with incorrect result

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#1722]
Hi,
We found incorrect result when using Anti and Semi join with a filter on the payload.

This issue can be reproduced with the unit tests in below commit:
https://github.com/rui-mo/velox/commit/b96ceaa1c1fa4fb0b403475e953b07f732f9e373.

The tested queries are:
for Anti join:
```
SELECT t.c0, t.c1 FROM t WHERE NOT EXISTS (SELECT c0, c1 FROM u WHERE t.c0 = u.c0 AND t.c1 <> u.c1)
```
for Semi join:
```
SELECT t.c0, t.c1 FROM t WHERE EXISTS (SELECT c0, c1 FROM u WHERE t.c0 = u.c0 AND t.c1 <> u.c1)
```

**Comment by mbasmanova** [comment]
@rui-mo Thank you for reporting. Have you had a chance to debug to see what's wrong? We'll take a look as well.

**Comment by mbasmanova** [comment]
CC: @gggrace14 @spershin

**Comment by rui-mo** [comment]
Thanks, just found this issue when testing TPC-H q21. Looks like if no filter, the result is correct.

**Comment by mbasmanova** [comment]
Got it. Interestingly, we have all TPC-H queries tested for correctness against Presto and didn't see any failures. Will take a look. CC: @aditi-pandit

**Comment by rui-mo** [comment]
Got that. Thank you, if there is something wrong with our usage, like the unit tests show, please kindly point out.

**Comment by mbasmanova** [comment]
Thank you for including a repro. It is super helpful. Will post here what I find.

**Comment by mbasmanova** [comment]
@rui-mo Rui, here is a fix for anti join: https://github.com/facebookincubator/velox/pull/1728

**Comment by rui-mo** [comment]
Thanks for your great work! Verified locally with the two commits, works well for us.

**Comment by mbasmanova** [comment]
@rui-mo Glad to hear the issue is resolved now. Thank you for the confirmation.
