### ISSUE TITLE
Pre-projection for aggregation and join

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#1724]
We noted the aggregation function can only accept field and literal as args, and if there is computing like sum(col_a * col_b), a project node needs to added before aggregation.
Similar case for join. Only fields can be accepted as join keys.
Will Velox support args of expressions in aggregation or join?
Thanks.

Reference:
https://github.com/facebookincubator/velox/blob/main/velox/exec/HashAggregation.cpp#L76
https://github.com/facebookincubator/velox/blob/main/velox/core/PlanNode.h#L910-L920

**Comment by mbasmanova** [comment]
@rui-mo As you noted the application needs to add a projection node before aggregation of join. This is by design.

**Comment by rui-mo** [comment]
OK, in Spark, the args of aggregation and join can be expressions, so we are wondering will Velox do the same thing in the future.

**Comment by mbasmanova** [comment]
We do not plan to support this. Velox doesn't include an optimizer and expects the application to optimize the plan before passing it to Velox.
