### ISSUE TITLE
Double type support for In filter

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#1725]
For the filter of In expression, we noted there are only BytesValues and BigintValues implemented. Will double type be supported in the future? Thanks.

Reference:
https://github.com/facebookincubator/velox/blob/main/velox/type/Filter.h#L40-L45

**Comment by mbasmanova** [comment]
Thank you for clarifying. You can represent this using a MultiRange filter with DoubleRange/FloatRange used as individual filters (a = 1 or a = 3). That said, equality filters for doubles are tricky.

```
/// Represents a combination of two of more filters with
/// OR semantics. The filter passes if at least one of the contained filters
/// passes.
class MultiRange final : public Filter {
```

**Comment by rui-mo** [comment]
Got that. Thank you. Does Velox plan to support DoubleValues as well in the long term? Or the IN expression for double is tricky and no need to support.

**Comment by mbasmanova** [comment]
IN list for floating point numbers has the same challenges as equality filter, hence, in general is discouraged. (Results are unreliable.)

**Comment by Yuhta** [comment]
You probably should use `array_min` instead of `IN`:

```sql
array_min(ARRAY[abs(x - 1.0), abs(x - 3.0), abs(x - 5.0)]) < 0.001
```

**Comment by rui-mo** [comment]
Thanks for your quick answering.
