### ISSUE TITLE
Re-enable Decimal FlatVector changes.

### ISSUE THREAD

**Issue by karteekmurthys** [facebookincubator/velox#1753]
Creating this issue to track re-enabling of reverted PR: https://github.com/facebookincubator/velox/pull/1742.

**Comment by karteekmurthys** [comment]
cc: @majetideepak @aditi-pandit

**Comment by majetideepak** [comment]
@kgpai any update on when this will land? Thanks.
CC: @pedroerp @mbasmanova

**Comment by Yuhta** [comment]
There is some regression on Prestissimo and other internal AI systems.  We are waiting for them to provide repro test cases so we can diagnose the issue.

**Comment by kgpai** [comment]
@majetideepak @karteekmurthys @Yuhta 
I hope to get this checked in by next week. I will keep you folks in loop.

**Comment by kgpai** [comment]
#1781 is the PR that reintroduces @karteekmurthys changes.

**Comment by kgpai** [comment]
Closing issue.
