### ISSUE TITLE
DuckDB Amalgamation causing wrong operator overloading

### ISSUE THREAD

**Issue by karteekmurthys** [facebookincubator/velox#1771]
Querying DuckDB HUGEINT_T(129 bit) decimal literals involves converting the string literal into HUGEINT_T structures.
Just like any other string to integer conversion, this involves shifting the hugeint_t result to left by 1 position (multiply by 10) and adding the newly extracted digit from the string to the final result. This is the method invoked as one of the steps:
```
1444 struct DecimalCastOperation {
1445         template <class T, bool NEGATIVE>
1446         static bool HandleDigit(T &state, uint8_t digit) {
1447                 if (state.result == 0 && digit == 0) {
1448                         // leading zero's don't count towards the digit count
1449                         return true;
1450                 }
1451                 if (state.digit_count == state.width - state.scale) {
1452                         // width of decimal type is exceeded!
1453                         return false;
1454                 }
1455                 state.digit_count++;
1456                 if (NEGATIVE) {
1457                         state.result = state.result * 10 - digit;
1458                 } else {
1459                         state.result = state.result * 10 + digit;
1460                 }
1461                 return true;
1462         }
```
The multiply operation in lines 1457 and 1459 in the above code invoke `operator*` overloaded method:
https://github.com/duckdb/duckdb/blob/master/src/common/types/hugeint.cpp#L616
```
hugeint_t hugeint_t::operator*(const hugeint_t &rhs) const {
	return Hugeint::Multiply(*this, rhs);
}

```

But on VELOX, the operator* invoked for this case is:
https://github.com/duckdb/duckdb/blob/master/src/function/aggregate/holistic/quantile.cpp#L17
```
// Hugeint arithmetic
hugeint_t operator*(const hugeint_t &h, const double &d) {
	D_ASSERT(d >= 0 && d <= 1);
	return Hugeint::Convert(Hugeint::Cast<double>(h) * d);
}
```
In VELOX, the hugeint multiplication trims down the precision as the value is cast to double leading to incorrect results.
Commenting the above method in the amalgamated file leads to picking the expected operator* in VELOX.

**Source**
HandleDigit function:
https://github.com/duckdb/duckdb/blob/master/src/common/operator/cast_operators.cpp#L1509

Actual method invoked in VELOX:
https://github.com/duckdb/duckdb/blob/master/src/function/aggregate/holistic/quantile.cpp#L17

Expected method:
https://github.com/duckdb/duckdb/blob/master/src/common/types/hugeint.cpp#L616

**Comment by majetideepak** [comment]
@mbasmanova Is there a reason for amalgamating DuckDb instead of treating it as a submodule?

**Comment by mbasmanova** [comment]
This was easier to add to internal build system. @Yuhta Jimmy, do you think we could add DuckDB via tp2?
