### ISSUE TITLE
How to use a single thread for plan execution?

### ISSUE THREAD

**Issue by zhztheplayer** [facebookincubator/velox#1803]
(edit: previously titled as "How to support a pull model in plan execution?")

It seems to me that these basic components, `Driver` / `Task` are all designed for a push-based execution model (Data is produced from Velox and send to subsequent endpoints). 

So is there a easy way to make Velox properly work with a pull-based system? Which means, I don't want to adopt a new thread or coroutine to connect these two types of systems. I see operator's API already provides method `getOutput` which can be useful for the purpose but operator and plan nodes seem to be already tied to the push-based execution engine.

**Comment by mbasmanova** [comment]
@zhztheplayer Hongze, thank you for the question. I'm wondering which system are you trying to integrate with and what would be the overall flow you are looking for.

CC: @laithsakka @oerling

**Comment by zhztheplayer** [comment]
It's Spark SQL. We'd like to conform to Spark's tasking model that a single instance of Spark task will play the role of a "driver" for plan execution. This driver drives a single thread and should actively pull data from Velox to its definition, e.g. a shuffle writer or a file writer, etc.

I also see Velox supports InlineLikeExecutor. Is using it a recommended way in cases like mine?

**Comment by rui-mo** [comment]
Hi @mbasmanova, Hongze is my colleague and is working on Gluten. As he said, we are currently using below TaskCursor and creates a thread in Velox for each thread in Spark. 

https://github.com/facebookincubator/velox/blob/main/velox/exec/tests/utils/Cursor.cpp#L145-L151

**Comment by mbasmanova** [comment]
@rui-mo Rui, thank you for clarifying. Welcome, Hongze. I'd like to understand the question better.

Do you use core::QueryCtx::createForTest() or pass in your own QueryCtx? QueryCtx allows to specify a folly::Executor for Velox to use for execution. 

Spark is written in Java / Scala. Velox is written in C++. Are you looking to run Velox on the thread created and managed by the JVM?

Velox operators need a way to yield a thread while blocked, e.g. HashProbe may be blocked waiting for the hash table. What's the API you'd like to use for driving the operators? Is it synchronous or asynchronous? 

Would you share a code pointer to the code you are currently using to run Velox tasks?

**Comment by zhztheplayer** [comment]
> Spark is written in Java / Scala. Velox is written in C++. Are you looking to run Velox on the thread created and managed by the JVM?

Yes. It should be ideal to let Spark manage all the threads in a Spark application. Spark has some thread local task contexts that would not be visible from non-task threads.

> Velox operators need a way to yield a thread while blocked, e.g. HashProbe may be blocked waiting for the hash table. What's 
the API you'd like to use for driving the operators? Is it synchronous or asynchronous?

The API is synchronous with regard to the single thread principle.
Actually we want to iterate over Velox's results by an Arrow [RecordBatchIterator](https://github.com/apache/arrow/blob/2c405dacc7be37e13368039fd96f3f32c1905dba/cpp/src/arrow/type_fwd.h#L88)
Here is the definition of `Iterator`: [link](https://github.com/apache/arrow/blob/2c405dacc7be37e13368039fd96f3f32c1905dba/cpp/src/arrow/util/iterator.h#L86-L210)

> Do you use core::QueryCtx::createForTest() or pass in your own QueryCtx? 

I have tried using QueryCtx within `InlineExecutor` and also `QueuedImediateExecutor`. But that didn't seem to work as expected since if I hit `Task::start`, all the results should be cached before being pulled to read. In `TaskCursor` it always results in blocking because of the cache size limit.

> Would you share a code pointer to the code you are currently using to run Velox tasks?

Our typical usage of Velox is to create a `TaskCursor`:
https://github.com/oap-project/gluten/blob/9a9d920f3570441229ba5f443f8e34f21e0cba72/cpp/velox/compute/VeloxPlanConverter.cc#L372

And then to get results from it:
https://github.com/oap-project/gluten/blob/9a9d920f3570441229ba5f443f8e34f21e0cba72/cpp/velox/compute/VeloxPlanConverter.cc#L271-L312

**Comment by miaoever** [comment]
@zhztheplayer could you share an example of how do you use the `InlineLikeExecutor `? At Meta, we're exactly using the ` InlineLikeExecutor` to match the Spark thread/task model in our Velox-Spark integration.

**Comment by zhztheplayer** [comment]
I tried something like this, then the program had hanged by the time TaskCursor's queue was full:

```c++
std::shared_ptr<Config> config = std::make_shared<core::MemConfig>();
std::shared_ptr<folly::Executor> executor =
std::shared_ptr<folly::QueuedImmediateExecutor>(&folly::QueuedImmediateExecutor::instance(), [](void *) {});
params_.queryCtx = std::make_shared<core::QueryCtx>(std::move(executor), std::move(config));
cursor_ = std::make_unique<test::TaskCursor>(params_);
```
Other codes was same as https://github.com/oap-project/gluten/blob/9a9d920f3570441229ba5f443f8e34f21e0cba72/cpp/velox/compute/VeloxPlanConverter.cc

**Comment by zhztheplayer** [comment]
E.g. there is `TaskContext` that is only visible for task threads.

https://github.com/apache/spark/blob/2fa98a6a0971cafeb98a2148a962cf8d79381842/core/src/main/scala/org/apache/spark/TaskContext.scala#L52

Currently we have a workaround to get the correct instance of `TaskContext` from Velox's executor threads. But that will seem like a suboptimal solution so we still want to get some suggestions from you guys to see if "single thread per task" can be achieved here.

**Comment by mbasmanova** [comment]
@zhztheplayer Thank you for clarifying further. It is not clear to me now to run Velox plan single-threaded in a general case. Maybe if pipeline is restricted to certain types of operators, e.g. TableScan, Aggregation, FilterProject, we can write a new single-threaded driver. Do you have an idea how that might look like? Would you like to prototype something?

**Comment by mbasmanova** [comment]
@zhztheplayer Let's try to put together something for a simple TableScan -> FilterProject -> Aggregation plan. We can add a new method Task::next() that would be used instead of Task::start().

`RowVectorPtr Task::next(bool* isBlocked, ContinueFuture* future);`

We would then require that the caller calls Task::addSplit() and Task::noMoreSplits() first, then calls Task::next() in a loop until it returns a nullptr or indicates being blocked.

On first Task::next() call, the task translates query plan into a set of pipelines, checks that there is only on pipeline, checks that noMoreSplits flag is already set, then makes a single Driver for that pipeline and calls a version of Driver::runInternal.

Driver::runInternal runs the pipeline on the caller's thread until it gets a batch of results or one of the operators blocks. In our case there will be no blocking operator since the only one that can block is TableScan, but it won't be blocked because 
 noMoreSplits flag is set.

I can help put this together if you find it useful. Let me know.

**Comment by zhztheplayer** [comment]
@mbasmanova Just to update, we've adopt these 2 PRs and they seem to work good as expected until now. Thank you very much for all the help :)

And I guess this can be closed now?

**Comment by mbasmanova** [comment]
@zhztheplayer Hongze, thank you for the update. I'm glad the new Task::next API is working for your use case. I'll close this issue now.
