### ISSUE TITLE
why separate store tag and row in hashtable

### ISSUE THREAD

**Issue by yetingsky** [facebookincubator/velox#1806]
In velox's use case, hashtable will not have equal key row (equal key row will be chained, and not inserted into hashtable), store meta and data together (just like folly f14table does) will improve performance？

**Comment by pedroerp** [comment]
from @oerling:

"We expect to miss in joins using the bit fields alone most of the time. So no pointer access needed and more coverage of table in cache.

For group by having tags in the same line as the pointers would likely be better. The layout for this case would be 16 * 8 bits for tags and 48 * 16 bits for pointers. This would fit in 2 lines. We have considered this. There are setters and getters that would make this change fairly convenient. This could be tried when next looking at hash tables."

**Comment by yetingsky** [comment]
Thanks.
