### ISSUE TITLE
Cannot access memory at address in StringDictionaryEncoder::addKey

### ISSUE THREAD

**Issue by JkSelf** [facebookincubator/velox#1814]
We encounter the following exceptions when using the Writer API to write DWRF file with large num rows.

`
  0x00007f0f39221859 in __GI_abort () at abort.c:79
#2  0x00007f0f385a9f1f in ?? () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#3  0x00007f0f38eeb143 in ?? () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#4  0x00007f0f38d3cd30 in JVM_handle_linux_signal ()
   from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#5  0x00007f0f38d3002c in ?? () from /usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64/server/libjvm.so
#6  <signal handler called>
#7  folly::detail::crc32_detail::align_to_8 (next=<optimized out>, crc0=<optimized out>, align=7)
    at ../folly/hash/detail/Crc32cDetail.cpp:171
#8  folly::detail::crc32c_hw (
    buf=0x32312d37302d3739 <error: Cannot access memory at address 0x32312d37302d3739>, len=758591533, crc=0)
    at ../folly/hash/detail/Crc32cDetail.cpp:251
#9  0x00007f0e1f8f6b90 in folly::crc32c (
    data=0x32312d37302d3739 <error: Cannot access memory at address 0x32312d37302d3739>, nbytes=758591533,
    startingChecksum=0) at ../folly/hash/Checksum.cpp:133
#10 0x00007f0e1f2aa65b in facebook::velox::dwrf::StringDictionaryEncoder::addKey(folly::Range<char const*>, unsigned int, unsigned int) () from /tmp/spark_columnar_plugin_9017457352165741288/libvelox.so
#11 0x00007f0e1f28be1e in facebook::velox::dwrf::(anonymous namespace)::StringColumnWriter::write(std::shared_ptr<facebook::velox::BaseVector> const&, facebook::velox::dwrf::Ranges const&) ()
   from /tmp/spark_columnar_plugin_9017457352165741288/libvelox.so
#12 0x00007f0e1f285151 in facebook::velox::dwrf::(anonymous namespace)::StructColumnWriter::writeChildrenAndStats(facebook::velox::RowVector const*, facebook::velox::dwrf::Ranges const&, unsigned long) ()
   from /tmp/spark_columnar_plugin_9017457352165741288/libvelox.so
#13 0x00007f0e1f28961b in facebook::velox::dwrf::(anonymous namespace)::StructColumnWriter::write(std::shared_ptr<facebook::velox::BaseVector> const&, facebook::velox::dwrf::Ranges const&) ()
   from /tmp/spark_columnar_plugin_9017457352165741288/libvelox.so
#14 0x00007f0e1f2dddd7 in facebook::velox::dwrf::Writer::write(std::shared_ptr<facebook::velox::BaseVector> const&) () from /tmp/spark_columnar_plugin_9017457352165741288/libvelox.so
`
@mbasmanova Do you have any comments?

**Comment by JkSelf** [comment]
Here is the code for test.

` // Batches has only one RowVector here.
    uint64_t nullCount = 0;
    std::vector<RowVectorPtr> batches{std::make_shared<RowVector>(
        pool_.get(), type, nullptr, num_rows_, vecs_, nullCount)};

    auto sink = std::make_unique<facebook::velox::dwio::common::FileSink>(absoluate_path);
    auto config = std::make_shared<facebook::velox::dwrf::Config>();
    const int64_t writerMemoryCap = std::numeric_limits<int64_t>::max();

    facebook::velox::dwrf::WriterOptions options;
    options.config = config;
    options.schema = type;
    options.memoryBudget = writerMemoryCap;
    options.flushPolicyFactory = nullptr;
    options.layoutPlannerFactory = nullptr;
    auto writer = std::make_unique<facebook::velox::dwrf::Writer>(
        options, std::move(sink),
        facebook::velox::memory::getProcessDefaultMemoryManager().getRoot());
    for (size_t i = 0; i < batches.size(); ++i) {
      writer->write(batches[i]);
    }
    writer->close();`

**Comment by mbasmanova** [comment]
@JkSelf Do you happen to have a repro I could run?

**Comment by mbasmanova** [comment]
@JkSelf The stack trace is a bit difficult to parse. Any chance you could attach it as a gist with proper formatting, e.g. one line per frame?

**Comment by mbasmanova** [comment]
@JkSelf 

> with large row count

How large is the row count in this case? Are you creating a single vector with very large number of rows and trying to write it to a file?

**Comment by JkSelf** [comment]
![image](https://user-images.githubusercontent.com/11972570/173734994-2c1a2343-5a68-4e1f-b7d4-1eb07f450397.png)

Here is the stack error.

**Comment by JkSelf** [comment]
Yes, I create a single vector with about 1174096 num rows to write a file.

**Comment by mbasmanova** [comment]
@JkSelf Does the image above come from a gdb? Any chance you could reproduce this in a unit test that I can run?

**Comment by mbasmanova** [comment]
My guess is that you are creating a vector of strings using StringViews which point to freed or uninitialized memory.

**Comment by JkSelf** [comment]
It maybe hard to run in a unit test. Here is my code to add the dwrf write in Gluten. And It can pass in small datasets.

**Comment by JkSelf** [comment]
https://github.com/oap-project/gluten/pull/205/files

**Comment by JkSelf** [comment]
> My guess is that you are creating a vector of strings using StringViews which point to freed or uninitialized memory.

If so, Why the small dataset can pass?

**Comment by mbasmanova** [comment]
> If so, Why the small dataset can pass?

Could be because the memory doesn't actually get freed / reallocated in this case.

**Comment by JkSelf** [comment]
Is it reasonable to create a single vector with very large number of rows and write it to a file?

**Comment by mbasmanova** [comment]
It is fine. You need to check the total size in bytes of the data in the vector. If you have very large strings you may end up using a lot of memory. Still, this should work. Try the same with inline strings (length < 12).

**Comment by JkSelf** [comment]
@mbasmanova  This issue is caused by the wrong vector construction in my side. Thanks for your help! And I will close this issue.

**Comment by mbasmanova** [comment]
@JkSelf Thank you for the update. Glad to hear the issue is resolved.
