### ISSUE TITLE
Is there any documentation on performance testing?

### ISSUE THREAD

**Issue by limbolism** [facebookincubator/velox#1842]
I would like to know the performance difference between using velox and not using velox, is there any documentation on this?

**Comment by pedroerp** [comment]
@limbolism can you elaborate on your question? You mean the difference between using Velox to interpret an expression, vs. having it hard-coded in, say, a cpp program? Or the question in related to a particular compute engine, like Presto or Spark?

**Comment by limbolism** [comment]
yes, I would like to know the performance reports related to the compute engine like presto

**Comment by mbasmanova** [comment]
@majetideepak @aditi-pandit @frankobe Folks from Ahana and ByteDance have been running some performance testing. Deepak, Frank, anything you can share here?
