### ISSUE TITLE
vectorized processing  for take

### ISSUE THREAD

**Issue by chakpongchung** [facebookincubator/velox#1859]
https://stackoverflow.com/questions/72735678/how-to-vectorize-arrowcomputetake

Is there a similar feature in Velox?

**Comment by pedroerp** [comment]
Hi @chakpongchung, it depends on what you intend to do with the results. In Velox you could do this zero-copy by wrapping input_array and take_array and creating a DictionaryVector, for instance. Could you explain a bit more about the use case?

**Comment by kgpai** [comment]
Hi chakpongchung , Can you add more details here. What feature are you exactly looking for ?

**Comment by chakpongchung** [comment]
Use Case: I am taking a subset of a really large input_array. It is used in places where OpenMP-like and MPI-like parallelism are used. So vectorization seems to be the next low-hanging fruit.

Context and use cases also added to the original StackOverflow post.

**Comment by pedroerp** [comment]
> Is there an arrow-equivalent operation for this?

Arrow also supports dictionary encoded data:

> https://arrow.apache.org/docs/format/Columnar.html#dictionary-encoded-layout

**Comment by pedroerp** [comment]
Closing it. Please re-open if you have additional questions.
