### ISSUE TITLE
Linux build failures due to folly::ssl::openssl dependency in velox

### ISSUE THREAD

**Issue by karteekmurthys** [facebookincubator/velox#1882]
PrestoCPP linux CircleCI build failing because of folly::ssl dependency:

```
In file included from ../../velox/velox/functions/prestosql/StringFunctions.cpp:23:
../../velox/velox/functions/lib/string/StringImpl.h: In function 'void facebook::velox::functions::stringImpl::sha512(TOutString&, const TInString&)':
../../velox/velox/functions/lib/string/StringImpl.h:293:28: error: 'sha512' is not a member of 'folly::ssl::OpenSSLHash'
  293 |   folly::ssl::OpenSSLHash::sha512(
      |                            ^~~~~~
[256/477] Building CXX object velox/velox/functions/prestosql/CMakeFiles/velox_functions_prestosql_impl.dir/Subscript.cpp.o
ninja: build stopped: subcommand failed.

Exited with code exit status 1

```
Circle CI:
https://app.circleci.com/pipelines/github/facebookexternal/presto_cpp/5466/workflows/21fe2321-0705-4488-b27f-9a2f9eb97b36/jobs/21074

@aditi-pandit @pramodsatya

**Comment by mbasmanova** [comment]
CC: @kgpai @mshang816

**Comment by aditi-pandit** [comment]
> > CC: @kgpai @mshang816
> 
> Working on a fix. It looks like the version of folly is too old in our docker image.

Thanks @mshang816.

**Comment by mshang816** [comment]
This issue is fix after this PR (https://github.com/facebookexternal/presto_cpp/pull/788) is merged into presto_cpp main branch. Closing this issue.
