### ISSUE TITLE
Performance regression with row construct

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#1890]
Hi,
We are tesing the performance of TPC-H q17 integrated with Spark. Becuase spark has two columns of output, sum and count, for partial avg, we need to use row_construct to combine them to a RowType vector for the computing of final agg in Velox. But we found some performance issue may be related to the [RowFunction](https://github.com/facebookincubator/velox/blob/main/velox/functions/prestosql/RowFunction.cpp#L38-L43).

```
    if (*result) {
      BaseVector::ensureWritable(rows, outputType, context->pool(), result);
      (*result)->copy(row.get(), rows, nullptr);
    } else {
      *result = std::move(row);
    }
```

For one thing, if we remove the `(*result)->copy` code path and only keep `*result = std::move(row)`, the performance can be improved from 136s to 74s. But we guess it is not propriate to do this for all cases.

For another, if changing the query from avg(l_quantity) to sum(l_quantity) / count(l_quantity), the performance can also be improved from 136s to 74s. In this case, the row construct and final avg is not used.

Therefore, one way for us to workaround this issue would be to generate a new Substrait plan. In this plan, we can use sum and count for final avg, and add a projection after aggragation to conduct the sum/count.

Glad to here your opinion on this issue, thanks!

**Comment by rui-mo** [comment]
Raised an issue here @marin-ma @FelixYBW.

**Comment by kagamiori** [comment]
Hi Rui, Thank you for bringing this up. Could you also provide the query plans in Spark before and after the query rewritings?  
CC: @mbasmanova

**Comment by rui-mo** [comment]
@mbasmanova One thing we found is that this issue seems to be already fixed on the latest Velox main branch. Below is some test results we got:

| Time(s) | Old Velox main | Latest Velox main |
|---------|------------------|---------------------|
| Q17 avg	| 197.66 | 117.25 |
| Q17 sum/count | 125.21 | 119.35 |

About changing to use `context->moveOrCopyResult(row, rows, result);`, below are some findings.

```
    if (result && !isFinalSelection() && *finalSelection() != rows) {
      BaseVector::ensureWritable(rows, result->type(), result->pool(), &result);
      result->copy(localResult.get(), rows, nullptr);
    } else {
      result = localResult;
    }
```

We previously found the performance was similar after this change actually because we were not using the latest Velox. 

> *finalSelection() != rows

The above check is not in the Velox we used, so only the first call from row function went to a no-copy code path, others still went to result->copy. Tried to add this check, and found all calls from row function went to a no-copy path.

**Comment by rui-mo** [comment]
Found latest Velox is still using below implementation in RowFuntion, but the performance regression has been fixed based on our test. Does it still need to be changed?

```
    if (*result) {
      BaseVector::ensureWritable(rows, outputType, context->pool(), result);
      (*result)->copy(row.get(), rows, nullptr);
    } else {
      *result = std::move(row);
    }
```

**Comment by mbasmanova** [comment]
@rui-mo Rui, glad to hear you are getter better performance using latest Velox. The problem you pointed out is still valid, but may need surface in the workloads are you testing right now. I'm working on fixing this in #1921

**Comment by rui-mo** [comment]
Thanks for your great work! Closing this issue.
