### ISSUE TITLE
Unify include ordering

### ISSUE THREAD

**Issue by yingsu00** [facebookincubator/velox#1918]
Right now there're some discrepancies in the #include ordering. Some files put the system includes before the velox ones, while some the opposite. Furthermore, the .h file for the corresponding cpp is usually not separated by the rest includes.

Examples:
RLEv2.cpp 
```
#include "velox/dwio/dwrf/common/RLEv2.h"
#include "velox/dwio/common/SeekableInputStream.h"
#include "velox/dwio/dwrf/common/Common.h"
```
PagedInputStream.cpp
```
#include "velox/dwio/dwrf/common/PagedInputStream.h"
#include "velox/dwio/common/SeekableInputStream.h"
#include "velox/dwio/common/exception/Exception.h"
```
compression.cpp
```
#include "velox/dwio/dwrf/common/Compression.h"

#include "velox/dwio/common/Common.h"
#include "velox/dwio/common/compression/LzoDecompressor.h"
#include "velox/dwio/common/exception/Exception.h"
#include "velox/dwio/dwrf/common/PagedInputStream.h"
#include "velox/dwio/dwrf/common/PagedOutputStream.h"

#include <folly/logging/xlog.h>
#include <lz4.h>
#include <snappy.h>
#include <zlib.h>
#include <zstd.h>
#include <zstd_errors.h>
```
ColumnSelector.cpp
```
#include "velox/dwio/common/ColumnSelector.h"

#include <iterator>

#include "folly/Conv.h"
#include "velox/dwio/common/TypeUtils.h"
```
BufferedInput.cpp
```
#include <fmt/format.h>

#include "velox/dwio/common/BufferedInput.h"
```
It will be nice to unify the include orderings. The proposal here is to order the includes this way

1. The prototype/interface header for this implementation (ie, the .h file that corresponds to this .cpp file).
2. Other headers in Velox.
3. Headers from other libraries (e.g. fmt, folly) and standard C++ headers ( e.g. iostream).

Groups shall be separated with an empty line, and lines in each group shall be ordered in alphabetic order. Group 1 and 2 uses `""` while group 3 uses `<>`

References:

https://blog.knatten.org/2010/07/01/the-order-of-include-directives-matter/
https://stackoverflow.com/questions/2762568/c-c-include-header-file-order
http://www.cplusplus.com/forum/articles/10627/

If the above proposal is agreed, the `make format-fix` and `make format-check` will need to be updated accordingly.

**Comment by kagamiori** [comment]
Hi @yingsu00, Thank you for bringing this up. Just to add relevant information: we internally follow a coding style as follows (and yes, there are files not following this style unfortunately).

> a. If you're in a cpp file, foo.cpp (or fooTest.cpp if foo.cpp doesn't exist), the first #include must be foo.h (if it exists).
> b. All C standard library and UNIX includes: #include <sys/time.h>
> c. All C++ standard lib includes: #include <iostream>
> d. All third-party open sourced includes: #include <boost/utility.hpp>
> e. All Meta's open sourced includes: #include <folly/dynamic.h>, #include <thrift/lib/cpp/Thrift.h>
> f. All of our local includes: #include "velox/dwio/common/BufferedInput.h"
> g. All includes within one group should be ordered in alphabetical order
> h. All using and using namespace declarations.

CC: @pedroerp @mbasmanova

**Comment by yingsu00** [comment]
Reason to use local -> global order 

Imagine you are writing a library that depends on some other library, like the STL (hardly any library doesn’t). Imagine you are a good boy (or girl) and write the test first. You might do something like this:

```
#include <vector> //STL
#include <gtest/gtest.h> //ThirdParty 
#include "geometry.hpp" //In-house
 
#define PI 3.2 //As pr. Indiana Bill #246, 1897
 
TEST(TestGeometry, rotatingOrigoGivesOrigo) {
    std::vector<double> v(2,0);
    rotate(v, PI);
    EXPECT_EQ(0, v[0]) << "X got moved!";
    EXPECT_EQ(0, v[1]) << "Y got moved!";
}
```
and your geometry.hpp looks like this:

```
void rotate(std::vector<double>& v, double angle);
```
This all works out nicely until someone else wants to include geometry.hpp without including <vector> first, and get something like geometry.hpp:1: error: ‘vector’ is not a member of ‘std’. **You have now forced all the users of your geometry library to include <vector> before including geometry.hpp**.

**Comment by pedroerp** [comment]
Not sure I followed the idea, but if your `geometry.hpp` library uses std::vector, it should absolutely include an explicit `#include <vector>` in the library itself, and not rely on clients of the library to figure what the library might need internally.
