### ISSUE TITLE
Optimized CXX_FLAGS for new Intel platform

### ISSUE THREAD

**Issue by zhouyuan** [facebookincubator/velox#1975]
Hi Velox developers,

The` CXX_FLAGS` were configured to pick only a small set of CPU features, is this an intended configuration to work with Meta local building env? 
https://github.com/facebookincubator/velox/blob/main/scripts/setup-helper-functions.sh#L103

These flags prevents GCC to do more optimizations when compiling, and the library compiled with these flags are missing some important optimizations on recent intel platform like `-mbmi -mbmi2` which can bring ~10% speed up in our tests. 

I'd suggest to create more profiles when parsing CPU types and apply more GCC optimizations if available 
https://github.com/facebookincubator/velox/blob/main/scripts/setup-helper-functions.sh#L102-L108
e.g.,  new profile on `avx2` or `avx512` then pick more optimizations flags there, how do you think about this?

CC: @mbasmanova 

Thanks, -yuan

**Comment by mbasmanova** [comment]
CC: @Yuhta @kgpai

**Comment by kgpai** [comment]
Hi zhouyuan, 

To an extent yes, velox is built with these flags so we can target the largest set of users. For e.g certain bmi/avx instructions are not present on Google collab. Adding more finer grained profiles increases testing burden as we need to ensure we have appropriate CI jobs to ensure things don't break. 
Hope this helps. 

-Krishna.

**Comment by kgpai** [comment]
Also to clarify we take the conservative approach only for binaries that are to distributed externally, we do try and apply the maximum optimizations to internal builds. One nice change/ feature to add would be to override these flags if CXX_FLAGS is set .

**Comment by zhejiangxiaomai** [comment]
Change CXX_FLAGS  to -march=native -mno-avx512f, we can compile successfully. But it does not contain any avx512 Instruction. we will make new PR to fix  avx512 compile problem, when we need delete  -mno-avx512f in the future.
