### ISSUE TITLE
can not run CPU_TARGET="arm64" ./scripts/setup-macos.sh on mac m1

### ISSUE THREAD

**Issue by zzpzbl6685** [facebookincubator/velox#2016]
env mac m1

CPU_TARGET="arm64" ./scripts/setup-macos.sh:
-- Build files have been written to: /Users/lengpi/Desktop/work/velox/range-v3/_build
+ ninja -C _build install
ninja: Entering directory `_build'
[0/1] Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:53 (file):
  file cannot create directory: /usr/local/lib/cmake/range-v3.  Maybe need
  administrative privileges.

FAILED: CMakeFiles/install.util

i also try sudo but:
+ brew install --formula ninja
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
+ brew upgrade --formula ninja
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

**Comment by zuyu** [comment]
Fixed by adding `INSTALL_PREFIX` env, as mentioned in https://github.com/facebookincubator/velox/issues/1446#issuecomment-1543363264
