### ISSUE TITLE
[Refactoring] Move dwrf::E2EFilterTestBase to dwio::common

### ISSUE THREAD

**Issue by yingsu00** [facebookincubator/velox#2032]
This is a sub issue of https://github.com/facebookincubator/velox/issues/1533

Both Parquet and Dwrf e2e filter tests will inherit this class. To remove the dependency of Parquet tests on dwrf::E2EFilterTestBase, we need to remove Dwrf specific contents from it and move to dwio::common.

This is part of the native parquet refactoring task.

**Comment by yingsu00** [comment]
cc @zzhao0 @oerling @HuamengJiang @weizheng10

**Comment by pedroerp** [comment]
Let me look at this one. I've been meaning to learn more about this part of the codebase anyway.

**Comment by pedroerp** [comment]
First moving the dwrf/test/utils files: #2093 2093

**Comment by yingsu00** [comment]
Thank you very much @pedroerp !

**Comment by pedroerp** [comment]
No problem! This is finished, closing it.
