### ISSUE TITLE
Status missing with toPlanStats on certain pattern

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#2048]
Hi,

We are using below function to get the map of plan node status with `toPlanStats(task_->taskStats())`. Link: [toPlanStats](https://github.com/facebookincubator/velox/blob/main/velox/exec/PlanNodeStats.cpp#L102-L121).
> std::unordered_map<core::PlanNodeId, PlanNodeStats> toPlanStats(
    const TaskStats& taskStats)

But found there is one missing status on below pattern. We suppose to get a map with size 5 but actually only get 4.

```
-- Project[expressions: (n4_0:DOUBLE, ROW["n2_0"]), (n4_1:DOUBLE, ROW["n2_1"])] -> n4_0:DOUBLE, n4_1:DOUBLE
  -- Filter[expression: and(not(is_null(ROW["n2_2"])),gt(ROW["n2_2"],12295372397.752893))] -> n2_0:DOUBLE, n2_1:DOUBLE, n2_2:DOUBLE
     -- Project[expressions: (n2_0:DOUBLE, ROW["n0_0"]), (n2_1:DOUBLE, ROW["n1_1"]), (n2_2:DOUBLE, ROW["n1_1"])] -> n2_0:DOUBLE, n2_1:DOUBLE, n2_2:DOUBLE
       -- Aggregation[FINAL [n0_0] n1_1 := sum(ROW["n0_1"])] -> n0_0:DOUBLE, n1_1:DOUBLE
          -- ArrowStream[] -> n0_0:DOUBLE, n0_1:DOUBLE
```

We printed the plan node id and found id 3 was missing. Based on the plan, the respective plan node for id 3 is Filter.

```
4
0
2
1
```

Do you have any suggestion from us on this issue? Thanks in advance.

**Comment by mbasmanova** [comment]
@rui-mo This is because Filter over Project nodes are mapped to a single operator FilterProject. Runtime statistics are collected at a per-operator basis and then mapped back to the plan node. FilterProject operator is mapped to the Project node. No operator is mapped to Filter node in this case, hence, Filter node doesn't have stats.

**Comment by rui-mo** [comment]
> @rui-mo This is because Filter over Project nodes are mapped to a single operator FilterProject. Runtime statistics are collected at a per-operator basis and then mapped back to the plan node. FilterProject operator is mapped to the Project node. No operator is mapped to Filter node in this case, hence, Filter node doesn't have stats.

Thanks for your clarify. We will make the change accordingly.
