### ISSUE TITLE
sum(float) aggregation function gives wrong results

### ISSUE THREAD

**Issue by bikramSingh91** [facebookincubator/velox#2079]
The sum aggregation function for result-type float currently uses double as an intermediate. During execution the accumulator ends up writing intermediate values as double which then get read directly as floats (by using a reinterpret_cast). Due to the difference in memory layouts that double and floats use, the output float value turn out to be wrongly read.
Possible solution:
The simple solution here would be to store the accumulator type as float whenever the result type is float too.
If however it is essential to keep the accumulator type as double, then we will have to explicitly cast the double value to a float during the call to extractValues().

Follow up:
Also check on the Avg() aggregate function since it has similar implementation

To reproduce run the following as a gtest: 

```
  void testAddOverflowOfNumbers() {
    std::vector<RowVectorPtr> data;
    data.push_back(makeRowVector(
        {makeFlatVector<float>({2.00, 1.00})}));
    auto plan = PlanBuilder()
                    .values(data)
                    .singleAggregation({}, {"sum(c0)"})
                    .planNode();
    createDuckDbTable({data});
    assertQuery(plan, "SELECT sum(c0) FROM tmp");
    
  }
```

**Comment by majetideepak** [comment]
This problem arises for ShortDecimal -> LongDecimal as well. I have a fix. Assigning this issue to me.

**Comment by majetideepak** [comment]
Resolved with https://github.com/facebookincubator/velox/pull/2150
