### ISSUE TITLE
Add support for LIKE operator

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#208]
Presto's documentation about LIKE operator: https://prestodb.io/docs/current/functions/comparison.html#like 

LIKE operator can be implemented by translating the pattern to a regular expression and using regexp_like function to evaluate it.

regexp_like already exists. See velox/functions/prestosql/VectorFunctions.cpp

Presto's conversion from like pattern to regex pattern can be found at https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/type/LikeFunctions.java#L174

We can add vector function "like" that takes two parameters, likePattern and escapeChar (optional), translates likePattern and escapeChar into a regular expression and invokes regexp_like. To avoid re-compiling regular expressions multiple times, the new function can be implemented as stateful and compile regular expression from the constant inputs in the constructor. See makeRe2Search in velox/functions/lib/Re2Functions.h

In Presto query plan, `c LIKE '<pattern>'` appears as `like(c, cast('<pattern>' as LikePattern))` and `c LIKE '<pattern>' ESCAPE '<escape-char>'` appears as `like(c, like_pattern('<pattern>', '<escape-char>'))`. We'll need to translate these expressions to `like(c, `<pattern>`)` and `like(c, '<pattern>', '<escape-char>')` respectively. See tryConvertCast in presto_cpp/main/types/PrestoToVeloxExpr.cpp for a similar logic applied to regular expressions.

To quickly try LIKE operator, edit e2e test to add a query like this:

```
assertQuery("SELECT * FROM lineitem WHERE comment LIKE '%afa%'");
assertQuery("SELECT * FROM lineitem WHERE comment LIKE '%afa#%' ESCAPE '#'");
```

CC: @spershin @pedroerp @aditi-pandit @majetideepak @kgpai

**Comment by mbasmanova** [comment]
DuckDB has a custom LIKE implementation not using regular expressions: https://github.com/duckdb/duckdb/blob/master/src/function/scalar/string/like.cpp

DuckDB folks considered switching to RE2, but found that RE2 is 2-4x slower: https://github.com/duckdb/duckdb/issues/157

Same for OmniSciDB: https://github.com/omnisci/omniscidb/blob/master/Utils/StringLike.cpp#L94

CC: @biswapesh @spershin @amitkdutta

**Comment by aditi-pandit** [comment]
More changes are needed in presto_cpp for the e2e TPC-H query.

**Comment by yingsu00** [comment]
Seems this is already done. Shall we close the issue? @aditi-pandit

**Comment by aditi-pandit** [comment]
@yingsu00 : I have not spent much time benchmarking the like operator. But I will open a separate issue for it and close this one.
