### ISSUE TITLE
Question about output batch size of join and aggregation

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#2086]
Hi,

We noticed there was a config controlling the output batch size of join and aggregation at below two places:

[Aggregation](https://github.com/facebookincubator/velox/blob/main/velox/exec/HashAggregation.cpp#L35)
[HashProbe](https://github.com/facebookincubator/velox/blob/main/velox/exec/HashProbe.cpp#L63)

We are wondering why the default value is 1024. Would that be too small？We previously noted bigger batch size could benefit the performance of shuffle after join.

[QueryConfig](https://github.com/facebookincubator/velox/blob/main/velox/core/QueryConfig.h#L119-L121)

We tried to increase the batch size to be 32k, but found if the join was with a filter, the batch size of the result become small again. From code we found the output rows after filter seems to be not controlled ([evalFilter](https://github.com/facebookincubator/velox/blob/main/velox/exec/HashProbe.cpp#L473)).

Will Velox add logic to coalesce the outputs of operators to certain batch size in the future? Or is there any implementation for coalesce in Velox code now?

Thanks in advance.

**Comment by rui-mo** [comment]
hi @zhouyuan, raised an issue here.

**Comment by Yuhta** [comment]
@mbasmanova Can you help answering this when you have time?  Thanks.

**Comment by mbasmanova** [comment]
@rui-mo Rui, we haven't had a chance to fine tune this parameter. I can imagine that 1024 could be small in certain cases, but wonder if you could describe a specific query shape where this becomes a problem and also share how big the problem is, e.g. what is the performance difference between different batch sizes. It would be helpful to put together a benchmark that we could use to illustrate the problem and iterate on a solution.

**Comment by rui-mo** [comment]
Hi @FelixYBW @marin-ma, about the batch size issue, can you help put the test data here if you still keep it?

**Comment by marin-ma** [comment]
@rui-mo Thanks for reporting the issue. @mbasmanova In our case, we were testing the performance of TPC-H Q21 with Gluten + Velox on spark. In gluten, we are using columnar ShuffleExchange operator to replace Spark's row-based shuffle. Columnar shuffle is sensitive to the input batch size, which means its performance gets worse with small input batch size (the output data from hash join is the input data for shuffle operator). 

We've compared the performance of TPC-H Q21 by changing the default output batch size from 1k to 32k, and found the execution time of Q21 reduced from 4.2min to 3.7min, and the execution time of the most time-consuming stage (2 consecutive hash join followed by 1 large shuffle) reduced from to 2.8min to 2.4min, meanwhile the CPU utilization of columnar shuffle task thread reduced from ~30% to ~4%. 

Therefore, the output batch size may have no impact to Velox's performance, but do affects the execution time of the entire query. It would be better if the value could be configurable in our practice.

**Comment by mbasmanova** [comment]
> Currently, to test the performance with different output batch size, we need to change the default value in the source code.

@rui-mo Rui, it should not be necessary to change the value in the code. You can simply specify a different value in the QueryConfig. See an example in velox/exec/tests/HashJoinTest.cpp

```
  AssertQueryBuilder(plan, duckDbQueryRunner_)
      .config(core::QueryConfig::kPreferredOutputBatchSize, std::to_string(10))
      .assertResults("SELECT c0, u_c1 FROM t, u WHERE c0 = u_c0 AND c1 < u_c1");
```

**Comment by mbasmanova** [comment]
> In gluten, we are using columnar ShuffleExchange operator to replace Spark's row-based shuffle.

I'm curious what's the motivation for using columnar shuffle. Do you see improved performance? CC: @beroyfb @miaoever @spershin @xiaoxmeng

**Comment by mbasmanova** [comment]
> the output batch size may have no impact to Velox's performance, but do affects the execution time of the entire query.

This makes sense. I'm curious which operator do you use for shuffle. Would it make sense for that operator to buffer enough rows before sending these to shuffle? Such buffering logic exists in velox/exec/PartitionedOutput.cpp, but I'm not sure if you are using this operator or some other custom operator.

**Comment by rui-mo** [comment]
Hi @mbasmanova, yes, we implemented a PR to set this config through query context. The value is acquired from Spark config, and its default value is 32k. But we found join with filter still had small batch size with this config. So we raised this issue to ask about it. Thanks!

**Comment by mbasmanova** [comment]
> we found join with filter still had small batch size with this config

I see. The problem is that join with filter does not respect the kPreferredOutputBatchSize configuration property. The questions would be whether to modify HashProbe operator to always respect kPreferredOutputBatchSize configuration property or introduce a separate operator to merge small bathes into larger ones.

CC: @oerling @xiaoxmeng

**Comment by rui-mo** [comment]
> I'm curious which operator do you use for shuffle. Would it make sense for that operator to buffer enough rows before sending these to shuffle? Such buffering logic exists in velox/exec/PartitionedOutput.cpp, but I'm not sure if you are using this operator or some other custom operator.

Hi Masha, we are using a custom operator for columnar shuffle. But I think you are right, we can add some operator before shuffle to buffer enough rows. Currently we have a custom implementation for that, and it combines the shuffle outputs to certain batch size. I think we can also use that operator to combine the inputs for shuffle.

**Comment by FelixYBW** [comment]
It make sense to add an coalesce operator after each filter, either it's from filter operator or hash join. Rapids-plugin does in this way. Photon either didn't buffer enough rows after filter, they didn't add coalesce operator.

Thank you, Masha. We may close this issue.

**Comment by mbasmanova** [comment]
Closing per @FelixYBW comment. Feel free to reopen if needed.

**Comment by rui-mo** [comment]
Thanks for your answering! Closing this issue.
