### ISSUE TITLE
How to generate the TPC-H data?

### ISSUE THREAD

**Issue by UranusSeven** [facebookincubator/velox#2162]
Hi guys, I want to run the TPC-H benchmark. Is there a convenient way to generate the required data?

**Comment by majetideepak** [comment]
@UranusSeven Presto has a TPC-H connector that can be used to generate Parquet and DWRF format data.
Velox recently added a TPC-H connector, Parquet writer. It already has a DWRF writer. But I think there is no ready-to-use tool to connect the TPC-H connector to these writes.

CC: @pedroerp

**Comment by majetideepak** [comment]
Yes, I used the Presto TPC-H connector to test.

**Comment by UranusSeven** [comment]
Cool. Thanks for your help : )

**Comment by pedroerp** [comment]
The TPC-H Connector unit test suite has some examples of how you can use it in Velox:

> https://github.com/facebookincubator/velox/blob/main/velox/connectors/tpch/tests/TpchConnectorTest.cpp
