### ISSUE TITLE
Add this table to velox aggregate developer page

### ISSUE THREAD

**Issue by shiyu-bytedance** [facebookincubator/velox#2175]
<img width="913" alt="Screen Shot 2022-08-01 at 6 22 42 PM" src="https://user-images.githubusercontent.com/105019964/182271708-1370d47a-850b-46e5-b59f-c61041f10f48.png">

This table can be added to the velox developer 's aggregate page to make understanding aggregates easier.

**Comment by mbasmanova** [comment]
CC: @xiaoxmeng 

There are additional usage pattern when spilling is enabled or when an aggregate function is used in a streaming application.

For spilling, extractAccumulator and addSingleGroupIntermediateResults are used in single and partial aggregation.

Streaming applications use the same instance of an Aggregate class to add raw and intermediate results. In this case, a single instance receives both addRawInput and addIntermediateResults calls as well as extractAccumulators and extractValues.

**Comment by mbasmanova** [comment]
@shiyu-bytedance PR #2250 updates the documentation to clarify usage of Aggregate class methods in different aggregation workflows.
