### ISSUE TITLE
SumTest.sumDouble failing often in CI

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#2198]
[ RUN      ] SumTest.sumDouble
../../velox/exec/tests/utils/QueryAssertions.cpp:597: Failure
Value of: false
  Actual: false
Expected: true
Expected 1, got 1
1 extra rows, 1 missing rows
1 of extra rows:
	-4.7537139293722525E29 | 4463.235924376847

1 of missing rows:
	4617.17236328125 | 4463.235924376847

**Comment by pedroerp** [comment]
Masha already assigned it, but @xiaoxmeng is working on it.

**Comment by xiaoxmeng** [comment]
https://github.com/facebookincubator/velox/pull/2183 has fixed this issue. Thanks!
