### ISSUE TITLE
Fix PrestoException in TPC-H query 21

### ISSUE THREAD

**Issue by aditi-pandit** [facebookincubator/velox#223]
TPC-H benchmark query 21 failed on PrestoCPP with the following Exception:
"PrestoException com.facebook.presto.sql.planner.plan.AssignUniqueId no abstract type PlanNode".

Steps to reproduce :  Run unit tests testTpchQ21 in
java/presto-native-tests/src/test/java/com/facebook/presto/nativeworker/TestHiveTpchQueries.java

**Comment by frankobe** [comment]
This is caused by `AssignUniqueId` plan node is not supported in presto_cpp & velox. I am adding the support
