### ISSUE TITLE
Build failure when native Parquet Reader is enabled

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#2263]
I hit the following build error when I enable the native Parquet Reader in the TPCHBenchmark

```
make[3]: *** No rule to make target `third_party/arrow_ep/src/arrow_ep-build/thrift_ep-install/lib/libthrift.a', needed by `velox/benchmarks/tpch/velox_tpch_benchmark'.  Stop.
```

**Comment by majetideepak** [comment]
@pedroerp I am unable to set the Assignees or Labels. I used to be able to before. Did anything change? Thanks.

**Comment by Yuhta** [comment]
I cannot reproduce the issue with `make debug EXTRA_CMAKE_FLAGS="-DVELOX_ENABLE_PARQUET=ON"` on my laptop.  Can you share the command and the full output?

**Comment by majetideepak** [comment]
This issue can be reproduced if you already have a local thrift library installed. In my case
```
/usr/local/Cellar/thrift/0.16.0/lib/libthrift.a
/usr/local/Cellar/thrift/0.16.0/include
```
This is on macOS. The change I made is to `parquet::registerParquetReaderFactory(parquet::ParquetReaderType::NATIVE)` to the below file
https://github.com/facebookincubator/velox/blob/c1175118d362d42b0a7a692994aa3b86cb5a63f0/velox/benchmarks/tpch/TpchBenchmark.cpp#L101

**Comment by pedroerp** [comment]
> @pedroerp I am unable to set the Assignees or Labels. I used to be able to before. Did anything change? Thanks.

I think your permission must have expired or something; I just added it back. Could you git it another try? 

(it also shows now as "invited" so you might need to check if you got an email or something)

**Comment by majetideepak** [comment]
@pedroerp thank you!  The permission issue is fixed.

**Comment by Yuhta** [comment]
@majetideepak Can you add a check in the cmake to see if thrift is already installed, then use that path, instead of using the one in arrow?

**Comment by majetideepak** [comment]
@Yuhta unfortunately, the CMake module `FindThrift.cmake` is not present in the standard path. Arrow has it own here `arrow_ep/src/arrow_ep/cpp/cmake_modules/FindThrift.cmake`. Since `ExternalProject_Add` does not download the project during cmake time, we cannot find thrift.
Should we have our own `velox/third_party/cmake_modules`?

**Comment by majetideepak** [comment]
Thanks. I will add a PR for this since I already have the environment.
