### ISSUE TITLE
Add support for EXTRACT Year from Date. This is used in 3 TPC-H queries.

### ISSUE THREAD

**Issue by aditi-pandit** [facebookincubator/velox#228]
TPC-H queries 7, 8, 9 group by a column that is obtained using EXTRACT Year from Date. Add support for this functionality in PrestoCPP.

Steps to reproduce : Run unit tests testTpchQ7(8)(9) in
java/presto-native-tests/src/test/java/com/facebook/presto/nativeworker/TestHiveTpchQueries.java

(The test also fails as DATE type is not supported for the EXTRACT functionality)

**Comment by mbasmanova** [comment]
Year function was added in https://github.com/facebookincubator/velox/commit/7ac665ad5ed6b973dcf5daef98045adc72a768d8

**Comment by aditi-pandit** [comment]
EXTRACT YEAR is required from DATE type also for this work.

**Comment by aditi-pandit** [comment]
https://github.com/facebookincubator/velox/pull/627 extends Masha's PR for Date.

**Comment by aditi-pandit** [comment]
https://github.com/facebookexternal/presto_cpp/pull/578 enables the queries using extract(year from date) in the TPC-H tests.
