### ISSUE TITLE
Improve ParquetRowReader::filterRowGroups() 

### ISSUE THREAD

**Issue by yingsu00** [facebookincubator/velox#2329]
Issue 1
It'll be better to match the split range before match each ColumnChunk's Statistics.

Issue 2
It'll be clearer and more efficient to move columnReader_->filterRowGroups() in the for loop and only calls it when the current RowGroup passes split match. This would save the cost of std::find() over all excluded RowGroups

**Comment by yingsu00** [comment]
Working on a fix... Assigning to myself.

**Comment by majetideepak** [comment]
> Suppose [52,269,596, 26,134,798] is the split range.
The lower bound > upper bound. Is this a valid split range? 
The split ranges will span the entire file size. Looking at only column 0's offset should work.

> It'll be better to match the split range before match each ColumnChunk's Statistics.
This makes sense since stat computation is relatively expensive.

**Comment by yingsu00** [comment]
> The lower bound > upper bound. Is this a valid split range?
It was a typo. The second should be 52,269,596 + 26,134,798. It falls into RowGroup 0. I have a fix for this.

**Comment by majetideepak** [comment]
> RowGroup 1 has columns[0].file_offset = 133,677,309

This is not in the range of  [52,269,596, 52,269,596 + 26,134,798]. So it will be eliminated right?

**Comment by yingsu00** [comment]
Actually this is a severe bug. It fails to add rowgroups that should be read and read a lot less data than it should. In the attached example, the split range is [26134798, 52269596]. There are 2 row groups in the table. row group 0 is in range [4, 133677309], row group 1 in [133677309, 261347983]. filterRowGroups() should add RG0 to rowGroupIds, and skip RG1. But it fails to add any of the RGs and rowGroupIds.size() remains 0.  This means no data is read! See pic
<img width="2597" alt="Screen Shot 2022-08-20 at 3 10 36 AM" src="https://user-images.githubusercontent.com/33299678/185741285-3be27cab-c198-4b9e-873a-f5a387fc8f61.png">

**Comment by majetideepak** [comment]
Isn't this expected? Split range [0, 26134798] will read RG0 and split range  [130673990, 156808788] will read RG1.

**Comment by yingsu00** [comment]
> Isn't this expected? Split range [0, 26134798] will read RG0 and split range [130673990, 156808788] will read RG1.

Split ranges [0, 26134798] were not handled by this reader instance. A reader never processes more than 1 split. In the above example, this reader instance needs to read split range [26134798, 52269596], which falls in RG0 and shall read RG0 only. But it didn't recognize any  RGs and put zero RG into the rowGroupIds to be read. This results in no data being read at all.

**Comment by majetideepak** [comment]
I don't believe every reader instance should process at least one Row Group. I also think a Parquet RowGroup is indivisible. It cannot be processed across two reader instances.
This is how I believe the processing works. A Parquet file is set up to be processed across multiple consecutive split ranges.
Example: Say there is a foo.parquet file of size 1000 bytes with two RowGroups with file_offsets 4, 504. We can set it up to be processed as 10 splits, [0, 99], [100, 199], ... [999, 1000]. However, only two split ranges [0, 99], [500, 599] will process the two RowGroups. Other split ranges and their readers will process nothing even if they overlap a Row Group.
Did I miss anything?

**Comment by yingsu00** [comment]
Sorry for the confusion. I did make a mistake in how Velox handles the RowGroup elimination. There was no functional error here. I'll close this issue now.
