### ISSUE TITLE
ParquetTpchTest does not test multiple rowgroups

### ISSUE THREAD

**Issue by yingsu00** [facebookincubator/velox#2345]
We need to manually create small row groups and include multiple rowgroups in the test.

**Comment by yingsu00** [comment]
cc @oerling @majetideepak @jwyles-ahana

**Comment by majetideepak** [comment]
The current ParquetTpchTest already does this.
See https://github.com/facebookincubator/velox/blob/main/velox/dwio/parquet/tests/reader/ParquetTpchTest.cpp#L65
