### ISSUE TITLE
Is DateDiffFunction  need timezone?

### ISSUE THREAD

**Issue by LastSmiling** [facebookincubator/velox#2363]
in function
```
template <typename T>
struct DateDiffFunction {
  VELOX_DEFINE_FUNCTION_TYPES(T);

  FOLLY_ALWAYS_INLINE void initialize(
      const core::QueryConfig& config,
      const arg_type<Varchar>* unitString,
      const arg_type<Timestamp>* /*timestamp1*/,
      const arg_type<Timestamp>* /*timestamp2*/) {
    if (unitString != nullptr) {
      unit_ = fromDateTimeUnitString(*unitString, false /*throwIfInvalid*/);
    }

    sessionTimeZone_ = getTimeZoneFromConfig(config);
  }
...
  FOLLY_ALWAYS_INLINE bool call(
      int64_t& result,
      const arg_type<Varchar>& unitString,
      const arg_type<Timestamp>& timestamp1,
      const arg_type<Timestamp>& timestamp2) {

  }

```

when use TimeStamp type, it will use timezone, but,  timestamp1 and timestamp2 use the same tz,  so whether the absolute difference between  the two timestamp values is the same whatever the tz is.

on the other side,  the below function is confusing

```
inline int64_t deltaWithTimezone(const date::time_zone& zone, int64_t seconds) {
  auto tp = std::chrono::time_point<std::chrono::system_clock>(
      std::chrono::seconds(seconds));
  auto epoch = zone.to_local(tp).time_since_epoch();
  int64_t delta =
      seconds - std::chrono::duration_cast<std::chrono::seconds>(epoch).count();
  return delta;
}

void Timestamp::toTimezone(const date::time_zone& zone) {
  seconds_ -= deltaWithTimezone(zone, seconds_);
}
```
it can just be simplified to ?
```
auto tp = std::chrono::time_point<std::chrono::system_clock>(
      std::chrono::seconds(seconds));
seconds_ = zone.to_local(tp).time_since_epoch().count()
```

**Comment by kagamiori** [comment]
Hi @LastSmiling, Thank you for reaching out! These are good questions. At first sight, it looks like both the `call()` that takes `Timestamp` arguments and `Timestamp::toTimezone()` can indeed be simplified. CC @mbasmanova for opinions.

**Comment by mbasmanova** [comment]
@LastSmiling You are welcome to submit a PR to simplify this code.

**Comment by LastSmiling** [comment]
@mbasmanova  my pleasure to do this   :)

**Comment by LastSmiling** [comment]
sorry, I miss understanding the DateDiffFunction before.  Cause the daylight saving,  the timezone parameter in DateDiffFunction is  necessary.

so i will give a pr only to simplify the Timestamp::toTimezone function

**Comment by mbasmanova** [comment]
@LastSmiling Thank you for the update.
