### ISSUE TITLE
Different rules for nulls handling in anti join

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#2438]
We found Velox's rules for null handling in anti join seemed to be **matched** with `not in` semantics in Duckdb or Spark.

```
Not in rules:
  (1) If hash table is empty, return stream side;
  (2) Else if existing key in hash table being null, no row will be joined;
  (3) Else if the key from stream side is null, this row will not be joined;
  (4) Else if the key from stream side cannot be found in build side, this row will be
joined.
```

But **not matched** with `not exists` semantics in Duckdb or Spark. 

```
Not exists rules:
(1) If key from stream side contains null, this row will be joined;
(2) Else if the key from stream side cannot be found in build side, this row will be
joined;
(3) Else the key from stream side does not statisfy the condition, this row
will be joined.
```

In Spark BHJ, there is a parameter naming `isNullAwareAntiJoin` controlling the behavior of anti join. If true, it behave as `not in` rules, else as `not exists` rules. This parameter is true only for `not in` with single join key and without filter.

We are wondering how to integrate Spark with Velox when the operator semantics are different, and maybe you could provide us with some advice.

There are two unit tests for Velox anti join on null handling if you want to take a look: https://github.com/rui-mo/velox/commit/5344e580fd950316e4d9aa87619c2fd980c7c5cb.

Thanks!

**Comment by rui-mo** [comment]
cc @FelixYBW

**Comment by mbasmanova** [comment]
@rui-mo Rui, thank you for brining this up. I took a look and here is what I'm seeing.

I looked into 2 similar queries: one using NOT EXISTS and another using NOT IN.

```
> WITH t as (SELECT * FROM UNNEST(ARRAY[1, 2, 3, null]) as _t(id)),
u as (SELECT * FROM UNNEST(ARRAY[1, null, 3]) as _t(id))
SELECT * FROM t 
WHERE NOT EXISTS(SELECT * from u WHERE u.id = t.id)

> WITH t as (SELECT * FROM UNNEST(ARRAY[1, 2, 3, null]) as _t(id)),
u as (SELECT * FROM UNNEST(ARRAY[1, null, 3]) as _t(id))
SELECT * FROM t 
WHERE t.id NOT IN (SELECT id from u)
```

In Presto, NOT EXISTS query is planned as LEFT JOIN + FILTER:

```
         - FilterProject[filterPredicate = not(COALESCE(subquerytrue, BOOLEAN'false')), projectLocality = LOCAL] => [field:integer]
             - LeftJoin[("field" = "field_6")] => [field:integer, subquerytrue:boolean]
                     Distribution: PARTITIONED
                 - RemoteStreamingExchange[REPARTITION] => [field:integer]
                     - Unnest[replicate=, unnest=expr:array(integer)] => [field:integer]
                         ...
                 - LocalExchange[HASH] (field_6) => [subquerytrue:boolean, field_6:integer]
                     - RemoteStreamingExchange[REPARTITION] => [subquerytrue:boolean, field_6:integer]
                         - Project[projectLocality = LOCAL] => [subquerytrue:boolean, field_6:integer]
                                 subquerytrue := BOOLEAN'true'
                             - Aggregate(FINAL)[field_6] => [field_6:integer]
                                 - LocalExchange[HASH] (field_6) => [field_6:integer]
                                     - Aggregate(PARTIAL)[field_6] => [field_6:integer]
                                         - Unnest[replicate=, unnest=expr_7:array(integer)] => [field_6:integer]
                                             ...
```

while NOT IN query is planned as SEMI JOIN + FILTER using REPLICATE NULLS AND ANY option for the build-side exchange:

```
         - FilterProject[filterPredicate = not(expr_19), projectLocality = LOCAL] => [field:integer]
             - SemiJoin[field = field_7] => [field:integer, expr_19:boolean]
                     Distribution: PARTITIONED
                 - RemoteStreamingExchange[REPARTITION] => [field:integer]
                     - Unnest[replicate=, unnest=expr:array(integer)] => [field:integer]
                         ...
                 - LocalExchange[SINGLE] () => [field_7:integer]
                     - RemoteStreamingExchange[REPARTITION - REPLICATE NULLS AND ANY] => [field_7:integer]
                         - Unnest[replicate=, unnest=expr_8:array(integer)] => [field_7:integer]
                                 Estimates: {rows: 1 (5B), cpu: ?, memory: ?, network: ?}
                             ...
```

Prestissimo, converts SEMI JOIN + FILTER into Velox ANTI JOIN: https://github.com/prestodb/presto/blob/master/presto-native-execution/presto_cpp/main/types/PrestoToVeloxQueryPlan.cpp#L1027 Using ANTI JOIN is more efficient as we don't need to emit rows that will be filtered out by subsequent FILTER operator. 

As you pointing out, currently ANTI JOIN cannot be used for NOT EXISTS queries. As a workaround, you can plan these using LEFT JOIN + FILTER. A long term solution could be to extend ANTI JOIN to support NOT EXISTS semantic.

Let me know if you could use the workaround to unblock.

**Comment by mbasmanova** [comment]
CC: @bikramSingh91

**Comment by rui-mo** [comment]
> As a workaround, you can plan these using LEFT JOIN + FILTER.

@mbasmanova Masha, thanks for your detailed and helpful guiding. I have a question on this workaround. Looks like Presto has an extra boolean column to indicate whether a row is selected.
> SemiJoin operator returns all probe rows plus an extra boolean column which indicates whether there is a match for a given row. Then a filter on the boolean column is used to select a subset of probe rows that match (semi join) or don't match (anti join).

Can Velox's left join have an extra boolean column to represent whether the stream keys can be found in the build side? If not, should I use a filter for null to check whether a row should be selected? Thanks again.
cc @FelixYBW

**Comment by mbasmanova** [comment]
@rui-mo Rui,

> Looks like Presto has an extra boolean column to indicate whether a row is selected.

To get that boolean, add a Project node to the join build side to add a boolean column with constant value "true":

                         - Project[projectLocality = LOCAL] => [subquerytrue:boolean, field_6:integer]
                                 subquerytrue := BOOLEAN'true'

Then, make sure to include this boolean in the output of the left join. Rows that had a match will have this boolean set to true. Rows that didn't match will have it set to null.

**Comment by rui-mo** [comment]
> To get that boolean, add a Project node to the join build side to add a boolean column with constant value "true".

Thanks Masha, understood. Do you think this part of logic should be added during Substrait-to-Velox conversion, or before that, in the Substrait plan generation process (in Gluten)?

**Comment by mbasmanova** [comment]
> Do you think this part of logic should be added during Substrait-to-Velox conversion, or before that, in the Substrait plan generation process (in Gluten)?

I suggest to put that into plan generation (Gluten).

**Comment by mbasmanova** [comment]
@rui-mo On a related topic, Substrait doesn't seem to clearly define semantics for the anti join:

https://substrait.io/relations/logical_relations/#join-types

> Anti | Return records from the left input. These are returned only if the records do not have a join partner on the right side.

I wonder if this is an omission or by design. The wording suggests NOT EXISTS semantics, but I'm not sure. What do you think?

**Comment by mbasmanova** [comment]
@rui-mo For the workaround using left join, it is also necessary to add distinct aggregation to the build-side to ensure there are no duplicate join keys on the build side.

**Comment by mbasmanova** [comment]
Here is nice description of the differences between NOT IN and NOT EXISTS from Databricks.

https://databricks-prod-cloudfront.cloud.databricks.com/public/4027ec902e239c93eaaa8714f173bcfc/2728434780191932/1483312212640900/6987336228780374/latest.html

```
A NOT IN subquery is the opposite of an IN subquery. This is different from a NOT EXISTS because NOT IN treats NULL values differently. A NOT IN can be rewritten as a conjunction of not equals predicates. For example x NOT IN (subquery y) with subquery y having 1 to n values, translates into: x <> y1 AND x <> y2 … AND x <> yn. When one of the tuples returned by the subquery contains a NULL the entire NOT IN clause will evaluate to NULL, this causes the outer row to be filtered out.

We use a Null Aware Anti Join to plan NOT IN subqueries. Note that this is a very expensive operator in practice because it will almost always be executed using a Broadcast Nested Loop join.
```

In Velox, kAnti join matches Databrick's Null Aware Anti Join semantics. One option is to rename kAnti to kNullAwareAnti and add a new kAnti that would implement NOT EXISTS semantics.

**Comment by rui-mo** [comment]
@mbasmanova Masha, thank you for your great help.
> Anti | Return records from the left input. These are returned only if the records do not have a join partner on the right side.

This definition from Substrait seems to be correct for both `not in` and `not exists` in a common case.

> Note that this is a very expensive operator in practice because it will almost always be executed using a Broadcast Nested Loop join.

In Spark, if the anti join is single-key and without filter, `not in` is planned as BroadcastHashJoin with `isNullAwareAntiJoin` enabled. In this case, matched result can be got from currenct Velox's anti join.

> One option is to rename kAnti to kNullAwareAnti and add a new kAnti that would implement NOT EXISTS semantics.

We already supported to send the `isNullAwareAntiJoin` flag from Spark to Velox through Substrait plan, so it is feasible for us to integrate Spark with different anti join semantics. And we're working on the workaround for now.

**Comment by mbasmanova** [comment]
> This definition from Substrait seems to be correct for both not in and not exists in a common case.

I'm not sure that one type of join can cover both NOT IN and NOT EXISTS semantics. Opened an issue to ask for clarification:

https://github.com/substrait-io/substrait/issues/325

**Comment by mbasmanova** [comment]
@rui-mo Rui, the semantics of anti joins are super tricky. Hence, before adding support for NOT EXISTS anti join, I decided to document the semantics to make sure I get it right. It would be great if you could review: https://github.com/facebookincubator/velox/pull/2527

**Comment by Yuhta** [comment]
@rui-mo I am going to work on this.

**Comment by rui-mo** [comment]
@mbasmanova @Yuhta Thank you very much for your time. We just implemented the workaround to replace anti join with left outer join with aggregation, project and filter. Initial tests showed the incorrect result issue for `not exists` we met could be resolved.

**Comment by Yuhta** [comment]
Hi @rui-mo , with #2906 both regular and null-aware anti join will be supported in Velox.  Feel free to download the PR and try it even before it merges.
