### ISSUE TITLE
Unused variable VELOX_BUILD_BENCHMARKS_LARGE in CMakeLists.txt

### ISSUE THREAD

**Issue by leoluan2009** [facebookincubator/velox#2448]
VELOX_BUILD_BENCHMARKS_LARGE is not used in project, can we remove it for code clean?
https://github.com/facebookincubator/velox/blob/main/CMakeLists.txt#L96

cc @mbasmanova @majetideepak

**Comment by majetideepak** [comment]
@leoluan2009 we will be adding a nightly test for this target. So let's keep it.

**Comment by leoluan2009** [comment]
Ok, make sense, I will close this issue.

**Comment by majetideepak** [comment]
@leoluan2009 I was wrong. We only use `VELOX_ENABLE_BENCHMARKS` and `VELOX_ENABLE_BENCHMARKS_BASIC`.
Let's remove this.

**Comment by leoluan2009** [comment]
@majetideepak  ok, I will submit a pr, thank you!

**Comment by leoluan2009** [comment]
fixed in https://github.com/facebookincubator/velox/pull/2454
