### ISSUE TITLE
TestHiveQueriesUsingJSON.testDecimalLiterals fails

### ISSUE THREAD

**Issue by spershin** [facebookincubator/velox#2478]
The test fails on the latest Presto Native + the latest Velox.

https://github.com/prestodb/presto/runs/8241037975?check_suite_focus=true

Error:    TestHiveQueriesUsingJSON.testDecimalLiterals:16->TestHiveQueries.testDecimalLiterals:349->AbstractTestQueryFramework.assertQuery:149 For query: 
 SELECT * from (values decimal'123.12', decimal'-0.0004', NULL,CAST('922337203685477580' as DECIMAL(18,0)), decimal'1123', NULL)
not equal
Actual rows (up to 100 of 1 extra rows shown, 6 rows in total):
    [-17014118346046923173168730371588410.5724]
Expected rows (up to 100 of 1 missing rows shown, 6 rows in total):
    [-0.0004]

**Comment by karteekmurthys** [comment]
Taking a look at this issue. This could be related what we noticed while testing decimal arithmetic e2e. The prestodb uses signed-bit representation while velox uses 2s complement representation of integers. However, it was an issue with 128-bit numbers. Here the value is quite small.

**Comment by majetideepak** [comment]
@karteekmurthys I am working on a PR for this.

**Comment by majetideepak** [comment]
I opened an issue on the Presto side. The deserializer code there needs the fix. Closing this.
https://github.com/prestodb/presto/issues/18312
