### ISSUE TITLE
Is Window function sum supported?

### ISSUE THREAD

**Issue by JkSelf** [facebookincubator/velox#2552]
Does velox only support the `row_number` window function now? Are `sum ` aggregate function supported in window function?

**Comment by mbasmanova** [comment]
At the moment only row_number is supported. We are working on adding more functions including adding support for aggregate functions. CC: @aditi-pandit

**Comment by JkSelf** [comment]
Got it. Thanks for the quickly response.

**Comment by mbasmanova** [comment]
You are welcome. I'll close the issue. Feel free to reopen if you have any follow-up questions.

**Comment by aditi-pandit** [comment]
Thanks @JkSelf. Will prioritize adding this sooner.

**Comment by JkSelf** [comment]
@aditi-pandit
 Currently does the Window Operator only support the default window frame not specified frame in [here](https://github.com/facebookincubator/velox/blob/71df8f40d55fd8608a8d714d3fd2bc0271ab3845/velox/exec/Window.cpp#L44)?

**Comment by aditi-pandit** [comment]
Current window support is only for default frame. We have some PRs in flight for the other frames. Do you have a priority of which frames you want sooner ?

**Comment by JkSelf** [comment]
Thank you very much for your prompt reply. The specficed WindowType in Spark `RowNumber` function is `ROWS` not `RANGE`. So I need the following frame for my test.
```
type = core::WindowNode::WindowType::kROW,
startType = core::WindowNode::BoundType::kUnboundedPreceding,
startValue = nullptr,
endType = core::WindowNode::BoundType::kCurrentRow,
endValue = nullptr
```

**Comment by aditi-pandit** [comment]
Thanks. There is a PR around for that. I'll prioritize check-in.
