### ISSUE TITLE
[Bug] docker-compose build failure

### ISSUE THREAD

**Issue by randosrandom** [facebookincubator/velox#2556]
Hi there,

I am new to velox and I was hoping to contribute in my small. To start, I was building velox through docker-compose, but I encountered an error, namely:

```
163.9 + Finished running install_folly
163.9 + run_and_time install_protobuf
163.9 + install_protobuf
163.9 + wget https://github.com/protocolbuffers/protobuf/releases/download/v21.4/protobuf-all-21.4.tar.gz
163.9 /velox/scripts/setup-ubuntu.sh: line 86: wget: command not found
163.9
163.9 real   0m0.001s
163.9 user   0m0.001s
163.9 sys    0m0.000s
------
executor failed running [/bin/bash -o pipefail -c /velox/scripts/setup-ubuntu.sh]: exit code: 127
ERROR: Service 'ubuntu-cpp' failed to build : Build failed
``` 
Apparently the problem was trivial, caused by the fact that the image `amd64/ubuntu:22.04` does not come with `wget` already installed. I managed to solve it by just adding the installation of `wget` in the file `scripts/setup-ubuntu.sh`. I am not sure whether this issue is of common interest or it was just a problem of mine, so please let me know. Anyway, if you want, I can also submit a PR, but since (apparently) the change is trivial, a Contributor may want to commit it directly.

Thank you for your time and looking forward to contributing to velox!

**Comment by kgpai** [comment]
Hi @randosrandom , Please feel free to submit a PR with fix .
