### ISSUE TITLE
CastIntByTruncate affects string to date casting

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#2567]
Hi,
We set below config to true to cast from float/double to integer by truncating. But found this setting also affects the behavior of casting from string to date, which causes failure in our test.

```
static constexpr const char* kCastIntByTruncate = "driver.cast.int_by_truncate";
```

We believe this config is meant to take effect for casting from double/float to integer. Should some special handling being added in [CastExpr](https://github.com/facebookincubator/velox/blob/main/velox/expression/CastExpr.cpp#L133-L139) to make this config effective only for that case?
This issue could be reproduced with below test in [CastExprTest](https://github.com/rui-mo/velox/blob/cast_test/velox/expression/tests/CastExprTest.cpp#L371-L393).

```
TEST_F(CastExprTest, stringToDate) {
  setCastIntByTruncate(true);
  testCast<std::string, Date>(
    "date",
    {
        "1970-01-01",
        "2020-01-01",
        "2135-11-09",
        "1969-12-27",
        "1812-04-15",
        "1920-01-02",
        std::nullopt,
    },
    {
        Date(0),
        Date(18262),
        Date(60577),
        Date(-5),
        Date(-57604),
        Date(-18262),
        std::nullopt,
    });
}
```

The error we noticed was:
```
Reason: Failed to cast from VARCHAR to DATE: 1970-01-01. 
Retriable: False
Context: cast((c0) as DATE)
Top-Level Context: Same as context.
Function: operator()
File: ../../velox/expression/CastExpr.cpp
```

Thanks!

**Comment by rui-mo** [comment]
cc @FelixYBW

**Comment by kagamiori** [comment]
Sorry for being late reply. I can reproduce this error. I'll take a look.

**Comment by rui-mo** [comment]
@kagamiori Thanks a lot for your fix!
