### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by eedalong** [facebookincubator/velox#2569]
I try to build this project, but ran into this problem

![image](https://user-images.githubusercontent.com/39682259/190605210-bfa63378-f75b-4728-8b77-0e82f8904c4a.png)

**Comment by kgpai** [comment]
Hi @eedalong can you paste the whole stack trace here ?

**Comment by eedalong** [comment]
Seems this is cause by mismatch of libzstd version.

**Comment by kgpai** [comment]
Seems like it, One problem could be you have mutliple zstd libraries installed and we are picking up wrong one. Again full stack trace might help.

**Comment by eedalong** [comment]
Yes, thx @kgpai. I've updated my libzstd into 1.4.0 version, and it works!
