### ISSUE TITLE
[Possible build issue] "docker compose run" uses too much RAM

### ISSUE THREAD

**Issue by randosrandom** [facebookincubator/velox#2571]
Hi there,

I was creating the velox services through `docker compose` (in this context it should be the same using the old `docker-compose`), but during compilation of the source files, the used RAM reached peaks of 10/11GB, hitting my Docker limit. After a while, the operating system killed the whole process:

```
FAILED: velox/functions/sparksql/CMakeFiles/velox_functions_spark.dir/RegisterCompare.cpp.o
ccache /usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_ATOMIC_DYN_LINK -DBOOST_CONTEXT_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DFMT_LOCALE -DGFLAGS_IS_A_DLL=0 -I/velox/. -I/velox/velox/external/xxhash -I/velox/third_party/xsimd/include -isystem /velox/velox -isystem /velox/velox/external -isystem /velox/velox/external/duckdb -isystem /velox/velox/external/duckdb/tpch/dbgen/include -isystem /velox/third_party/googletest/googletest/include -isystem /velox/third_party/googletest/googletest -mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17 -mbmi2 -D USE_VELOX_COMMON_BASE -D HAS_UNCAUGHT_EXCEPTIONS -Werror -Wall -Wextra -Wno-unused        -Wno-unused-parameter        -Wno-sign-compare        -Wno-ignored-qualifiers        -Wno-implicit-fallthrough          -Wno-empty-body          -Wno-class-memaccess          -Wno-comment          -Wno-int-in-bool-context          -Wno-redundant-move          -Wno-array-bounds          -Wno-maybe-uninitialized          -Wno-unused-result
-Wno-format-overflow          -Wno-strict-aliasing          -Wno-type-limits -O3 -DNDEBUG -std=gnu++17 -MD -MT velox/functions/sparksql/CMakeFiles/velox_functions_spark.dir/RegisterCompare.cpp.o -MF velox/functions/sparksql/CMakeFiles/velox_functions_spark.dir/RegisterCompare.cpp.o.d -o velox/functions/sparksql/CMakeFiles/velox_functions_spark.dir/RegisterCompare.cpp.o -c /velox/velox/functions/sparksql/RegisterCompare.cpp
c++: fatal error: Killed signal terminated program cc1plus
compilation terminated.
```
Interrogating the kernel through `dmesg`:

```
[ 2225.927013] Out of memory: Killed process 31667 (cc1plus) total-vm:2270576kB, anon-rss:269120kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:4448kB oom_score_adj:0
```
The problem is attributable to the number of threads deployed during compilation which is chosen to be the maximum available on the system (I have 16 threads). Therefore, I modified the `docker-compose.yml` limiting the number of threads to 4, so that the compilation happens with  `cmake --build _build/release -j 4`. Of course, in this way compilation will be slower, but at least it is guaranteed to succeed (actually, even using 4 threads, RAM can go to 7/8 GB in my case: I also have some additional overheads since I am using Windows Subsystem for Linux, but still the RAM consumption is remarkable). 

There are other possible workarounds: for instance one can override the container entrypoint command provided in the `docker-compose.yml` if the compilation fails. However, I think that it is worth limiting the number of processors to a smaller number, but giving the possibility to set it through an environmental variable read by the `docker-compose.yml,` for instance.

What do you think about it?

Thank you for your time!

**Comment by kgpai** [comment]
cc @raulcd

**Comment by raulcd** [comment]
Thanks for the report @randosrandom ! I did notice the compilation using a lot of resources too. The current docker-compose mimics the local build where Makefile find the available processors and uses all of them:
`NUM_THREADS ?= $(shell getconf _NPROCESSORS_CONF 2>/dev/null || echo 1)`
I do think that limiting it or allowing users to configure the amount of threads to use would be a helpful addition.
How did you modify the docker-compose to achieve the limiting, did you add some limits to the container or modified the command? Could you share your changes?

I agree we could add an environment variable and override the `NUM_THREADS` used on the `Makefile` if that environment variable is set.

I am happy to take a look if you want to provide a PR or I'll work on it as I think is a nice feature to be added.

**Comment by randosrandom** [comment]
Hi @raulcd,

In the `docker-compose.yml` I simply modified the entrypoint command as below:
```
command: &cpp-command >
/bin/bash -c "
make NUM_THREADS=4 &&
cd _build/release &&
ctest -j16 -VV --output-on-failure"
```
so I simply overridden the NUM_THREADS variable in the Makefile, passing it as an argument of make. 

To generalize it, in the `docker-compose.yml` we can do something like:

```
command: &cpp-command >
/bin/bash -c "
make NUM_THREADS=${NUM_THREADS:-} &&
cd _build/release &&
ctest -j16 -VV --output-on-failure"
```
so that, if `NUM_THREADS` exists in the environment, we override the number of the threads to use in the Makefile, otherwise it is set by  `NUM_THREADS ?= $(shell getconf _NPROCESSORS_CONF 2>/dev/null || echo 1)`.

Anyway, I am very happy to provide a PR with the feature above if it makes sense to you.

Thank you!

**Comment by raulcd** [comment]
Yes, that makes sense to me. This is what I was thinking! Thanks!

**Comment by randosrandom** [comment]
Hi @raulcd @kgpai,

I provided the PR, which is linked above, please let me know if it is ok.

Just one question that may sound naive, but I am new to velox (and open-source in general): 
I also have another pull request open (#2568), but the latest PR contains also the previous commit. Should I remove the old PR? What is the best thing to do in such cases?

Thank you!

**Comment by kgpai** [comment]
FYI, 
In the command listed above , lets make sure that `ctest -j16 -VV --output-on-failure` also uses NUM_THREADS instead of hard coding the test runs to 16 . 

@randosrandom ; No you do not have to remove it , you will probably have to merge from main/update if the dependent PR undergoes changes.

**Comment by randosrandom** [comment]
Ok @kgpai,

I did not used NUM_THREADS in test, since they are lightweight (for what I experienced) so we can safely allow the maximum number of threads. But if you think it's cleaner to use the same number of threads, I can add this modification.

Thanks!
