### ISSUE TITLE
RightSemiJoin/LeftSemiJoin shall only output build side/probe side columns

### ISSUE THREAD

**Issue by xiaoxmeng** [facebookincubator/velox#2609]
Currently, a right semi join could return the probe side columns as noticed in HashJoinTest.dynamicFilters test when the build side could be replaced by a dynamic filter. It can be used to filter out probe rows and returns the probe input directly in case of identical projections. Has offline discussion with @mbasmanova, we need to add check in plan node as well as operator to disallow output columns from probe side for right semi join type. The same for the left semi join.

**Comment by mbasmanova** [comment]
CC: @majetideepak

**Comment by xiaoxmeng** [comment]
https://github.com/facebookincubator/velox/pull/3068 should have fixed this.
