### ISSUE TITLE
Tpch connector scaleFactor type must be double instead of size_t

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#2612]
The `scaleFactor` is used to determine the output size of each Tpch Table. Currently, the type used for scaleFactor is 
`size_t` https://github.com/facebookincubator/velox/blob/main/velox/connectors/tpch/TpchConnector.h#L65.
However, for testing, smaller data size is desired. We must use a double instead, so that Velox can support tiny Tpch dataset where the scaleFactor say is `0.01`.
scaleFactor type is double as well in Presto Java.

**Comment by mbasmanova** [comment]
@majetideepak Deepak, would you add some more details?
