### ISSUE TITLE
Conbench integration with linux-benchmarks-basic in CircleCI

### ISSUE THREAD

**Issue by pramodsatya** [facebookincubator/velox#2622]
The linux-benchmark-basics build in CircleCI appears to be integrated with Conbench to check for benchmark regressions, which is great. The error message when builds fail due to benchmark regressions, however, is not detailed enough to identify which benchmark actually regressed (for instance: https://app.circleci.com/pipelines/github/facebookincubator/velox/13778/workflows/7ccab4fa-b7e1-49bf-a04a-2c907b395459/jobs/83156). Could this please be updated to reflect where the regression happened?
Also, I am curious if this check is accurate in catching benchmark regressions yet? I noticed that #2025 was flagged as having regressed the benchmarks by this check, although it ideally shouldn't have caused any regressions.

**Comment by pedroerp** [comment]
Hi @pramodsatya, this was a false alarm. I'm discussing it with @austin3dickey and @jonkeane , but looks like it's a bug or aconfiguration issue with our conbench integration. 

@austin3dickey is actively working on this. Will assign this Issue to you.

**Comment by pedroerp** [comment]
@austin3dickey said he'll have a fix by today!

**Comment by pramodsatya** [comment]
Thanks for the update!

**Comment by pedroerp** [comment]
Fix has been merged https://github.com/facebookincubator/velox/pull/2624
