### ISSUE TITLE
Build side cannot be reverted

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#2632]
Hi,
We found for hash join in some cases the build side had much larger size than the stream side, which would limit the join performance. For example, a left outer join is with right build side but the right side has larger datasize than the left side. In this case, if we can build the left side, the performance could be improved. But the issue is not all engines support both left and right build side for left outer join. Looks like a different logic is needed to support left outer join with left build side to have the correct output.

For now, if we just change left outer join to be right outer join (which builds left), correct result cannot be got unless we revert the left and right tables at the same time. But in this case, the build side would still be larger than the stream side and the performance issue cannot be resolved.

We also found in Velox if we reverted the build side for left outer join, the result was not correct. But for full outer join, correct result can be got with build side reverted. This is the Velox test I'm testing on if you want to take a look: [Velox test](https://github.com/rui-mo/velox/commit/e976271ad70f6c531590f6d96d087b61ff4a5117).

@oerling @mbasmanova Glad to hear your opinoin on this issue, thanks!

**Comment by rui-mo** [comment]
cc @FelixYBW

**Comment by FelixYBW** [comment]
The wrong seq we noted from Gluten, in all cases below, right table is targe table. We can modify spark to get the correct build table, question is how Velox can support this.

Q4, stage 67     LeftSemi, BuildRight
Q13, stage 362   LeftOuter, BuildRight
Q21, stage 522   LeftSemi, BuildRight
Q22, stage 553  LeftAnti, BuildRight

**Comment by mbasmanova** [comment]
@rui-mo Rui, thank you for reaching out. I expect a LEFT OUTER JOIN b to be equivalent to b RIGHT OUTER JOIN a. Hence, if b is smaller, the optimizer can plan the left join. Otherwise, the right join. Maybe there is a bug in the right join implementation in Velox. I'll take a look at the tests you linked.

**Comment by mbasmanova** [comment]
@rui-mo A quick look at the leftJoinBuildSideRevert test suggests that the test is comparing a LEFT b with b LEFT a. These are not expected to be the same. Let's change the test to compare a LEFT b with b RIGHT a.

**Comment by rui-mo** [comment]
> a LEFT OUTER JOIN b to be equivalent to b RIGHT OUTER JOIN a

Hi Masha, maybe I did not decribe the issue accurately. We agree above sentence but the build and probe tables should be reverted, right? For example, `left outer with a as build table and b as probe table` **equals to** `right outer with b as build table and a as probe table`. I think this case works well in Velox.
But our issue is about `left outer with b as build table and a as probe table`. You can see the build side is reverted but the join type is still the same. In this case, if we still want the correct result, the join logic is different.

**Comment by mbasmanova** [comment]
@rui-mo In Velox, right side of the join is always the build side. Hence, a LEFT b creates hash table from b, while b RIGHT a creates hash table from a. Since there are equivalent, the optimizer can pick which one to plan based on the sizes of a and b. If b is small, then a LEFT b. Otherwise, b RIGHT a.

**Comment by rui-mo** [comment]
> @rui-mo A quick look at the leftJoinBuildSideRevert test suggests that the test is comparing a LEFT b with b LEFT a. These are not expected to be the same. Let's change the test to compare a LEFT b with b RIGHT a.

I guess that is because build right is default behavior. Ideally, there may be build side options. For left outer join, build left or right can have the same output.

**Comment by mbasmanova** [comment]
> For left outer join, build left or right can have the same output.

True, but since a LEFT b == b RIGHT a, there is no need to provide an option of the left join with "left side being the build side".

**Comment by mbasmanova** [comment]
@rui-mo I modified the leftJoinBuildSideRevert test to change the join type for the second query to kRight and the test passed.

**Comment by rui-mo** [comment]
> The optimizer can pick which one to plan based on the sizes of a and b. If b is small, then a LEFT b. Otherwise, b RIGHT a.

Actually the issue we met was that the optimizer planned an `a LEFT b` logic, but b is larger. So we want to change the build side to a, if we change it to be `b Right a`, then because right outer builds left, b is still the build side. Therefore, with this change the build side is still the larger side.

**Comment by mbasmanova** [comment]
> because right outer builds left, b is still the build side

Why do you say this? In Velox, b RIGHT a uses table a to build the hash table.

**Comment by rui-mo** [comment]
> In Velox, right side of the join is always the build side. Hence, a LEFT b creates hash table from b, while b RIGHT a creates hash table from a. 

Thank you Masha! I think this is the key point I was missing. Based on this, it would be feasible to change the build table by justing switching the tables and the join type. I think we could close this issue now, how do you think so? @FelixYBW

**Comment by mbasmanova** [comment]
@rui-mo Happy to hear the issue is resolved. I'm going to close, but feel free to reopen if there are any follow-up questions.

**Comment by FelixYBW** [comment]
Can leftsemi and leftanti work as well?

**Comment by mbasmanova** [comment]
Semi and anti joins are tricker. Velox has LEFT and RIGHT SEMI joins, but only one NULL AWARE ANTI JOIN. @Yuhta is working on adding regular ANTI JOIN. We may need to look into adding support for both LEFT and RIGHT anti joins.

**Comment by FelixYBW** [comment]
Do you mean one null aware semi join?

**Comment by mbasmanova** [comment]
@FelixYBW 

There is only one kind of SEMI join. Having both kLeftSemi and kRightSemi allows us to choose which table to load into a hash table.

However, there are 2 different ANTI joins: NULL AWARE (NOT IN) and regular (NOT EXISTS). This is explained in more details in https://facebookincubator.github.io/velox/develop/anti-join.html

Currently we only support NULL AWARE ANTI join with subquery being loaded into a hash table. We are working on adding support for regular anti join with subquery being loaded into a hash table. On top of that, there might be a need to implement both joins in a way that allow for the outer query to be loaded into a hash table. That work hasn't been planned yet.

**Comment by FelixYBW** [comment]
Thank you, Masha. Then we can fix Q4, Q13 and Q21. 

Anti join isn't urgent now. Anti join in Q22 is a very small one.
