### ISSUE TITLE
Integrate Fuzzer with VectorSaver to save input data and expressions on failures

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#2669]
Right now, fuzzer test failures can only be reproduced with seeds. This approach is not convenient because developers must use the seed on the same commit where the failure happened (or the pool of all supported UDFs may be different which cause fuzzer to generate a different expression).

A new tool has been introduced recently (https://github.com/facebookincubator/velox/pull/2591) that allows saving the failed expression and input data to local files that can be used to easily reproduce the error later. So we would like to integrate fuzzer with this tool to enable saving of expressions and input data on fuzzer test failures too.

**Comment by mbasmanova** [comment]
CC: @tanjialiang

**Comment by tanjialiang** [comment]
> CC: @tanjialiang

Will be working on this item.

**Comment by tanjialiang** [comment]
The feature has been added.
