### ISSUE TITLE
Memory allocator issue on Mac M1

### ISSUE THREAD

**Issue by uhyonc** [facebookincubator/velox#2676]
Hi,

I was trying out Velox on the M1 Mac (via Presto-native) and I was getting
`MMAPL: Inconsistent mapped free lookup class` from
https://github.com/facebookincubator/velox/blob/f60a0821dc04482719e7d816e4c1519e98e1ae85/velox/common/memory/MmapAllocator.cpp#L513

I did a bit of debugging and it looks like this is happening because there are a few places where we assume a 256bit SIMD register width, which works for Intel AVX, but not Arm Neon which has a 128bit register width.
* https://github.com/facebookincubator/velox/blob/f60a0821dc04482719e7d816e4c1519e98e1ae85/velox/common/memory/MmapAllocator.cpp#L525
* https://github.com/facebookincubator/velox/blob/f60a0821dc04482719e7d816e4c1519e98e1ae85/velox/common/memory/MmapAllocator.cpp#L489
* https://github.com/facebookincubator/velox/blob/f60a0821dc04482719e7d816e4c1519e98e1ae85/velox/common/memory/MmapAllocator.h#L192

I think if we used
`xsimd::simd_type<uint64_t>::size` instead of the hardcoded values above, it will fix this issue.

What do you think?

Thanks.

**Comment by mbasmanova** [comment]
CC: @Yuhta @kgpai @xiaoxmeng @oerling

**Comment by Yuhta** [comment]
@uhyonc I think your are right, can you contribute a fix for it?  If you don't have time I can take a look later.

**Comment by uhyonc** [comment]
Yep, I can do it. I will create a PR and update the Issue with it.
