### ISSUE TITLE
ExpressionFuzzer: Add support for functions with parametrized types

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#2725]
Allow expression fuzzer to test functions whose arguments or return types are parametrized types, e.g., array_position(array(T), bigint) -> T.

**Comment by laithsakka** [comment]
@kagamiori this is done right?

**Comment by laithsakka** [comment]
@kagamiori  this is done right?

**Comment by kagamiori** [comment]
> @kagamiori this is done right?

Yes, this is done. I'm closing it. Thanks for the reminder!
