### ISSUE TITLE
Is http://velox-oss.slack.com an workspace that is invitation based only?

### ISSUE THREAD

**Issue by amaliujia** [facebookincubator/velox#273]
Hi Velox community,

I am wondering if http://velox-oss.slack.com is  invitation based only? I tried to use `amaliujia@apache.org` to signin which didn't work. Also tried a gmail address which seemed not working either.

Thanks,
Rui

**Comment by pedroerp** [comment]
@amaliujia sorry, I'm trying to figure out a way to let the Slack workspace open without requiring an invite, but couldn't find a way. I sent you an invite for now.

**Comment by amaliujia** [comment]
Thanks @pedroerp! I received the invitation and joined now without a problem.

**Comment by baiwfg2** [comment]
@pedroerp Hi, I've sent an email to you, would you please send me an invitation ?

**Comment by pedroerp** [comment]
@baiwfg2 sorry about that. I'm trying to make it open but I can't find out how. Any chance any of you guys would know?

In the meantime, you can use this invitation link:

> https://join.slack.com/t/velox-oss/shared_invite/zt-vn9xxoms-Z8N1c70WLKqqG2Ru8wAQjw

**Comment by baiwfg2** [comment]
@pedroerp I happen to see this. https://groups.google.com/g/janusgraph-dev/c/5Fp2tQNn_Po/m/0g8CiFknBQAJ
It turns out that a bot is needed.

**Comment by pedroerp** [comment]
> > @baiwfg2 sorry about that. I'm trying to make it open but I can't find out how. Any chance any of you guys would know?
> > In the meantime, you can use this invitation link:
> > > https://join.slack.com/t/velox-oss/shared_invite/zt-vn9xxoms-Z8N1c70WLKqqG2Ru8wAQjw
> 
> @pedroerp Hi, could you please send me an invitation? I do not have account in the list. Thanks!

Sure, you can use this link:

> https://join.slack.com/t/velox-oss/shared_invite/zt-xibt6okg-gmugBP1W9bZB3qJ6HAhSrw

**Comment by waitinfuture** [comment]
> > > @baiwfg2 sorry about that. I'm trying to make it open but I can't find out how. Any chance any of you guys would know?
> > > In the meantime, you can use this invitation link:
> > > > https://join.slack.com/t/velox-oss/shared_invite/zt-vn9xxoms-Z8N1c70WLKqqG2Ru8wAQjw
> > 
> > 
> > @pedroerp Hi, could you please send me an invitation? I do not have account in the list. Thanks!
> 
> Sure, you can use this link:
> 
> > https://join.slack.com/t/velox-oss/shared_invite/zt-xibt6okg-gmugBP1W9bZB3qJ6HAhSrw

Thanks!
