### ISSUE TITLE
SelectiveColumnReader compilation warnings in 10/13 build

### ISSUE THREAD

**Issue by aditi-pandit** [facebookincubator/velox#2838]
The build after sync today shows many warnings in SelectiveColumnReader in the log. Please fix.

/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:53:13: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  const void* values{nullptr};
            ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:53:13: note: insert '_Nullable' if the pointer may be null
  const void* values{nullptr};
            ^
              _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:53:13: note: insert '_Nonnull' if the pointer should never be null
  const void* values{nullptr};
            ^
              _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:447:64: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  prepareRead(vector_size_t offset, RowSet rows, const uint64_t* incomingNulls);
                                                               ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:447:64: note: insert '_Nullable' if the pointer may be null
  prepareRead(vector_size_t offset, RowSet rows, const uint64_t* incomingNulls);
                                                               ^
                                                                 _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:447:64: note: insert '_Nonnull' if the pointer should never be null
  prepareRead(vector_size_t offset, RowSet rows, const uint64_t* incomingNulls);
                                                               ^
                                                                 _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:459:44: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  void getIntValues(RowSet rows, const Type* requestedType, VectorPtr* result);
                                           ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:459:44: note: insert '_Nullable' if the pointer may be null
  void getIntValues(RowSet rows, const Type* requestedType, VectorPtr* result);
                                           ^
                                             _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:459:44: note: insert '_Nonnull' if the pointer should never be null
  void getIntValues(RowSet rows, const Type* requestedType, VectorPtr* result);
                                           ^
                                             _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:459:70: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  void getIntValues(RowSet rows, const Type* requestedType, VectorPtr* result);
                                                                     ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:459:70: note: insert '_Nullable' if the pointer may be null
  void getIntValues(RowSet rows, const Type* requestedType, VectorPtr* result);
                                                                     ^
                                                                       _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:459:70: note: insert '_Nonnull' if the pointer should never be null
  void getIntValues(RowSet rows, const Type* requestedType, VectorPtr* result);
                                                                     ^
                                                                       _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:468:16: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
      VectorPtr* result,
               ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:468:16: note: insert '_Nullable' if the pointer may be null
      VectorPtr* result,
               ^
                 _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:468:16: note: insert '_Nonnull' if the pointer should never be null
      VectorPtr* result,
               ^
                 _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:494:7: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  char* copyStringValue(folly::StringPiece value);
      ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:494:7: note: insert '_Nullable' if the pointer may be null
  char* copyStringValue(folly::StringPiece value);
      ^
        _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:494:7: note: insert '_Nonnull' if the pointer should never be null
  char* copyStringValue(folly::StringPiece value);
      ^
        _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:506:26: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  velox::common::ScanSpec* const scanSpec_;
                         ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:506:26: note: insert '_Nullable' if the pointer may be null
  velox::common::ScanSpec* const scanSpec_;
                         ^
                           _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:506:26: note: insert '_Nonnull' if the pointer should never be null
  velox::common::ScanSpec* const scanSpec_;
                         ^
                           _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:540:11: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  uint64_t* rawResultNulls_ = nullptr;
          ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:540:11: note: insert '_Nullable' if the pointer may be null
  uint64_t* rawResultNulls_ = nullptr;
          ^
            _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:540:11: note: insert '_Nonnull' if the pointer should never be null
  uint64_t* rawResultNulls_ = nullptr;
          ^
            _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:544:7: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  void* rawValues_ = nullptr;
      ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:544:7: note: insert '_Nullable' if the pointer may be null
  void* rawValues_ = nullptr;
      ^
        _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:544:7: note: insert '_Nonnull' if the pointer should never be null
  void* rawValues_ = nullptr;
      ^
        _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:570:7: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  char* rawStringBuffer_ = nullptr;
      ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:570:7: note: insert '_Nullable' if the pointer may be null
  char* rawStringBuffer_ = nullptr;
      ^
        _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:570:7: note: insert '_Nonnull' if the pointer should never be null
  char* rawStringBuffer_ = nullptr;
      ^
        _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:618:50: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  void addValue(vector_size_t /*row*/, const void* /*value*/) override {}
                                                 ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:618:50: note: insert '_Nullable' if the pointer may be null
  void addValue(vector_size_t /*row*/, const void* /*value*/) override {}
                                                 ^
                                                   _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:618:50: note: insert '_Nonnull' if the pointer should never be null
  void addValue(vector_size_t /*row*/, const void* /*value*/) override {}
                                                 ^
                                                   _Nonnull

**Comment by kagamiori** [comment]
Thanks for reporting this issue! Let me try to reproduce it on my laptop.

**Comment by mbasmanova** [comment]
CC: @yingsu00 @majetideepak @oerling @Yuhta

**Comment by kagamiori** [comment]
These warnings indeed appear. Hi @aditi-pandit, would you like to help fix this issue?

**Comment by aditi-pandit** [comment]
Yes, I'll take a stab at it.

**Comment by majetideepak** [comment]
I see them as well.

**Comment by aditi-pandit** [comment]
There were more after a first round of fixes. Just logging here for history

In file included from /Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/ColumnVisitors.h:22:
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:64:17: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  const uint64_t* __restrict inDictionary{nullptr};
                ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:64:17: note: insert '_Nullable' if the pointer may be null
  const uint64_t* __restrict inDictionary{nullptr};
                ^
                  _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:64:17: note: insert '_Nonnull' if the pointer should never be null
  const uint64_t* __restrict inDictionary{nullptr};
                ^
                  _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:65:10: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  uint8_t* __restrict filterCache;
         ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:65:10: note: insert '_Nullable' if the pointer may be null
  uint8_t* __restrict filterCache;
         ^
           _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:65:10: note: insert '_Nonnull' if the pointer should never be null
  uint8_t* __restrict filterCache;
         ^
           _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:143:21: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
      const uint64_t* /*incomingNulls*/ = nullptr) {
                    ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:143:21: note: insert '_Nullable' if the pointer may be null
      const uint64_t* /*incomingNulls*/ = nullptr) {
                    ^
                      _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:143:21: note: insert '_Nonnull' if the pointer should never be null
      const uint64_t* /*incomingNulls*/ = nullptr) {
                    ^
                      _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:158:57: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  read(vector_size_t offset, RowSet rows, const uint64_t* incomingNulls) = 0;
                                                        ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:158:57: note: insert '_Nullable' if the pointer may be null
  read(vector_size_t offset, RowSet rows, const uint64_t* incomingNulls) = 0;
                                                        ^
                                                          _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:158:57: note: insert '_Nonnull' if the pointer should never be null
  read(vector_size_t offset, RowSet rows, const uint64_t* incomingNulls) = 0;
                                                        ^
                                                          _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:167:48: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  virtual void getValues(RowSet rows, VectorPtr* result) = 0;
                                               ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:167:48: note: insert '_Nullable' if the pointer may be null
  virtual void getValues(RowSet rows, VectorPtr* result) = 0;
                                               ^
                                                 _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:167:48: note: insert '_Nonnull' if the pointer should never be null
  virtual void getValues(RowSet rows, VectorPtr* result) = 0;
                                               ^
                                                 _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:202:16: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  vector_size_t* mutableOutputRows(int32_t size) {
               ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:202:16: note: insert '_Nullable' if the pointer may be null
  vector_size_t* mutableOutputRows(int32_t size) {
               ^
                 _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:202:16: note: insert '_Nonnull' if the pointer should never be null
  vector_size_t* mutableOutputRows(int32_t size) {
               ^
                 _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:209:4: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  T* mutableValues(int32_t size) {
   ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:209:4: note: insert '_Nullable' if the pointer may be null
  T* mutableValues(int32_t size) {
   ^
     _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:209:4: note: insert '_Nonnull' if the pointer should never be null
  T* mutableValues(int32_t size) {
   ^
     _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:218:11: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  uint64_t* mutableNulls(int32_t size) {
          ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:218:11: note: insert '_Nullable' if the pointer may be null
  uint64_t* mutableNulls(int32_t size) {
          ^
            _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:218:11: note: insert '_Nonnull' if the pointer should never be null
  uint64_t* mutableNulls(int32_t size) {
          ^
            _Nonnull
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:319:26: warning: pointer is missing a nullability type specifier (_Nonnull, _Nullable, or _Null_unspecified) [-Wnullability-completeness]
  velox::common::ScanSpec* scanSpec() const {
                         ^
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:319:26: note: insert '_Nullable' if the pointer may be null
  velox::common::ScanSpec* scanSpec() const {
                         ^
                           _Nullable
/Users/aditipandit/ahana_dev/velox/velox/./velox/dwio/common/SelectiveColumnReader.h:319:26: note: insert '_Nonnull' if the pointer should never be null
  velox::common::ScanSpec* scanSpec() const {
                         ^
                           _Nonnull

**Comment by mbasmanova** [comment]
@aditi-pandit Thanks. Consider using Gist for long pastes. https://gist.github.com/
