### ISSUE TITLE
Parquet native reader fails to read an empty Parquet file

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#2871]
Reading an empty Parquet file throws the following error
```
VeloxRuntimeError: footerLength + 12 < fileLength_ (465 vs. 465)
```

The fix is to modify the check in `velox/dwio/parquet/reader/ParquetReader.cpp:68` to `VELOX_CHECK_LE(footerLength + 12, fileLength_);`

**Comment by kagamiori** [comment]
CC: @Yuhta @kgpai

**Comment by Yuhta** [comment]
Thanks @majetideepak , can you change it while you are working on it?

**Comment by majetideepak** [comment]
@Yuhta will do!

**Comment by yingsu00** [comment]
Fixed and closing
