### ISSUE TITLE
Unsupported Filter over SemiJoin

### ISSUE THREAD

**Issue by aditi-pandit** [facebookincubator/velox#2877]
Semi-joins with additional filters are not yet supported in Prestissimo / Velox:

```
SELECT * FROM lineitem 
WHERE orderkey < 10 OR orderkey IN (SELECT orderkey FROM orders WHERE (orderkey + custkey) % 2 = 0);

VeloxUserError:  Unsupported Filter over SemiJoin: ...
```

From @XuPingyong 

TPC-DS q45 fails with: Unsupported Filter over SemiJoin

```
--TPC-DS Q45
select  ca_zip, ca_city, sum(ws_sales_price)
 from web_sales, customer, customer_address, date_dim, item
 where ws_bill_customer_sk = c_customer_sk
 	and c_current_addr_sk = ca_address_sk
 	and ws_item_sk = i_item_sk
 	and ( substr(ca_zip,1,5) in ('85669', '86197','88274','83405','86475', '85392', '85460', '80348', '81792')
 	      or
 	      i_item_id in (select i_item_id
                             from item
                             where i_item_sk in (2, 3, 5, 7, 11, 13, 17, 19, 23, 29)
                             )
 	    )
 	and ws_sold_date_sk = d_date_sk
 	and d_qoy = 2 and d_year = 2002
 group by ca_zip, ca_city
 order by ca_zip, ca_city
 limit 100;
```

_Originally posted by @XuPingyong in https://github.com/facebookincubator/velox/issues/2820#issuecomment-1276917192_

**Comment by mbasmanova** [comment]
CC: @rui-mo Rui, I'm curious how Gluten plans with query (TPC-DS q45). Does it use Spark's Java operators for the semi join?

**Comment by rui-mo** [comment]
> CC: @rui-mo Rui, I'm curious how Gluten plans with query (TPC-DS q45). Does it use Spark's Java operators for the semi join?

Masha, I checked both q45 and above query, and found they were similar. In Spark, it is planned as a ShuffledHashJoin with existence join type and a filter as below.

```
(122) ShuffledHashJoin
Left keys [1]: [i_item_id#363]
Right keys [1]: [i_item_id#852]
Join condition: None

(123) Filter
Input [5]: [ws_sales_price#751, ca_city#244, ca_zip#247, i_item_id#363, exists#913]
Condition : (substr(ca_zip#247, 1, 5) IN (85669,86197,88274,83405,86475,85392,85460,80348,81792) OR exists#913)
```

ExistenceJoin in Spark appends a column of boolean type after the left table to illustrate whether one row is joined or not. This join type is not supported in Gluten for now, so in TPC-DS q45, this join is executed by vanilla Spark and this filter is executed by Velox. But we are working on enabling more operators and functions to offload more computing into Velox.

**Comment by mbasmanova** [comment]
@rui-mo Rui, thank you for the clarifying. This is very helpful. ExistingJoin in Spark appears to work similar to SemiJoin in Presto. Both act as a projection by emitting all rows from the left side with an additional boolean column set to true if there is a match, false if there is no match and null if "unknown" (left key is null and build side is not empty or there is no match and build side has a null).

In Velox, SemiJoin acts as a filter by emitting a subset of rows from the left side for which there is a match on the right side. There is a left semi join and right semi join to allow for using the smaller side as the build side. Both semi joins support filter pushdown from build to probe side.

As @XuPingyong pointed out, the existing implementation of SemiJoin in Velox doesn’t support queries like TPC-DS q45.
 
Presto’s and Spark's semantics for the semi join do not allow for dynamic filter pushdown. Hence, we may want to keep Velox’s implementation, but extend it to allow the queries above. One option is to extend the plan node to allow for specifying whether semi join should act as a filter, i.e. produce a subset of the left side rows, or as a project, i.e. emit all the left side rows with an extra boolean column.

CC: @oerling

**Comment by mbasmanova** [comment]
@XuPingyong I added support for semi join project in #3068. Would you try it out and let us know how it goes?

**Comment by XuPingyong** [comment]
> 

Thanks very much. LGTM.
But the error "Unsupported Filter over SemiJoin" still exists in prestodb/presto native-engine.

**Comment by mbasmanova** [comment]
@XuPingyong That's right. I didn't update the plan translation in Prestissimo yet to use the kSemiJoinProject join type. Let me send out a PR with these changes.

**Comment by mbasmanova** [comment]
@XuPingyong Here is a PR to update plan translation in Prestissimo to use kLeftSemiProject join:

https://github.com/prestodb/presto/pull/18616

**Comment by mbasmanova** [comment]
@storm-dance Thank you for confirming that these changes are sufficient to fix the original issue.
