### ISSUE TITLE
Add support for LEFT, RIGHT and FULL OUTER joins with no equi-clauses

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#2886]
Extends CrossJoinNode plan node and CrossJoinProbe operator to support LEFT, RIGHT and FULL OUTER joins without equi-clauses.

```
SELECT * FROM t LEFT JOIN u ON t.a < u.b;
SELECT * FROM t RIGHT JOIN u ON t.a < u.b;
SELECT * FROM t FULL OUTER JOIN u ON t.a < u.b;
```

Currently, these queries are not supported. Running these from Prestissimo gives errors like

```
VeloxRuntimeError: !leftKeys_.empty() JoinNode requires at least one join key
```

CC: @rui-mo @aditi-pandit @majetideepak @xiaoxmeng @Yuhta

**Comment by usurai** [comment]
Hi @mbasmanova, is anyone working on this issue? If not, I'd like to take a stub at it.

**Comment by mbasmanova** [comment]
@usurai I do not believe anything is working on this. You are welcome to pick this up.

**Comment by Yuhta** [comment]
Probably just add a filter to cross join?

**Comment by mbasmanova** [comment]
@usurai At a high level this makes sense. I think we'll need to take a closer look at how to implement 6. Check out HashProbe implementation. I suggest to go ahead and put together a prototype.

**Comment by usurai** [comment]
> @usurai At a high level this makes sense. I think we'll need to take a closer look at how to implement 6. Check out HashProbe implementation. I suggest to go ahead and put together a prototype.

Sure, have been referencing HashProbe and will put out a PR.

**Comment by mbasmanova** [comment]
@usurai @xiaoxmeng Folks, is there anything left to do here? If not, let's close.

CC: @shiyu-bytedance

**Comment by usurai** [comment]
> @usurai @xiaoxmeng Folks, is there anything left to do here? If not, let's close.
> 
> CC: @shiyu-bytedance

I think this can be closed, thanks.
