### ISSUE TITLE
Add truncate(x,n) presto function

### ISSUE THREAD

**Issue by gosharz** [facebookincubator/velox#2887]
**Context**: of https://github.com/facebookincubator/velox/issues/2262

Presto supports two versions of truncate: **truncate(x)** and **truncate(x,n)**. The former one has been added per https://github.com/facebookincubator/velox/pull/2862. This issue add adding implementation for the second overload.

Here is the java reference implementation which must be mimicked:
https://github.com/prestodb/presto/blob/ff412ef4b745eb31549cc0abe25e885a63875f58/presto-main/src/main/java/com/facebook/presto/operator/scalar/MathFunctions.java#L365

BigDecimal **setScale** - https://github.com/openjdk-mirror/jdk7u-jdk/blob/f4d80957e89a19a29bb9f9807d2a28351ed7f7df/src/share/classes/java/math/BigDecimal.java#L2378

**Comment by pedroerp** [comment]
@gosharz are you going to be working on this Issue as well?

**Comment by gosharz** [comment]
From https://en.wikipedia.org/wiki/Floating-point_arithmetic:

Type | Sign | Exponent | Significand field | Total bits |   | Exponent bias | Bits precision | Number of decimal digits
-- | -- | -- | -- | -- | -- | -- | -- | --
Half (IEEE 754-2008) | 1 | 5 | 10 | 16 |   | 15 | 11 | ~3.3
Single | 1 | 8 | 23 | 32 |   | 127 | 24 | ~7.2
Double | 1 | 11 | 52 | 64 |   | 1023 | 53 | ~15.9
x86 extended precision | 1 | 15 | 64 | 80 |   | 16383 | 64 | ~19.2
Quad | 1 | 15 | 112 | 128 |   | 16383 | 113 | ~34.0

<br class="Apple-interchange-newline">Type	Sign	Exponent	Significand field	Total bits		Exponent bias	Bits precision	Number of decimal digits
[Half](https://en.wikipedia.org/wiki/Half_precision) ([IEEE 754-2008](https://en.wikipedia.org/wiki/IEEE_floating_point))	1	5	10	16		15	11	~3.3
[Single](https://en.wikipedia.org/wiki/Single_precision)	1	8	23	32		127	24	~7.2
[Double](https://en.wikipedia.org/wiki/Double_precision)	1	11	52	64		1023	53	~15.9
[x86 extended precision](https://en.wikipedia.org/wiki/Extended_precision#x86_extended_precision_format)	1	15	64	80		16383	64	~19.2
[Quad](https://en.wikipedia.org/wiki/Quad_precision)	1	15	112	128		16383	113	~34.0

**Comment by gosharz** [comment]
Per https://github.com/facebookincubator/velox/pull/2892
