### ISSUE TITLE
Add context to std::exceptions thrown from the UDFs

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#2888]
When a UDF throws VeloxException using one of the VELOX_XXX macros, the error message includes a lot of useful information including the location of the error (file path and line number), stack trace, and expression being evaluated. For example,

```
Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Velox check failed.
Retriable: False
Context: x(c0)
Top-Level Context: plus(x(c0), 100:BIGINT)
Function: apply
File: /Users/mbasmanova/cpp/velox-1/velox/expression/tests/ExprTest.cpp
Line: 2808
Stack trace: ...
```

When UDF throws an std::exception, the error message is missing the context.

```
An std::invalid_argument occurred.
```

The information provided in the "Context:" and "Top-Level Context:" is particularly useful as it helps identify a specific UDF that generated an exception. We'd like to figure out how to add this information to std::exceptions as well.

CC: @kagamiori @laithsakka @aditi-pandit @majetideepak

**Comment by mbasmanova** [comment]
One way to add context to std::exceptions would be to modify the logic in EvalCtx::setError.

Current:

```
void EvalCtx::setError(
    vector_size_t index,
    const std::exception_ptr& exceptionPtr) {
  if (throwOnError_) {
     std::rethrow_exception(exceptionPtr);
  }
  addError(index, exceptionPtr, errors_);
}
```

New logic:
```
void EvalCtx::setError(
    vector_size_t index,
    const std::exception_ptr& exceptionPtr) {
  if (throwOnError_) {
    try {
      std::rethrow_exception(exceptionPtr);
    } catch (const VeloxException& e) {
      std::rethrow_exception(exceptionPtr);
    } catch (const std::exception& e) {
     VELOX_FAIL("{}", e.what());
    }
  }
  addError(index, exceptionPtr, errors_);
}
```

If we want to also ensure that suppressed errors (TRY) also include context, we may need to change the logic a bit more:

```
void EvalCtx::setError(
    vector_size_t index,
    const std::exception_ptr& exceptionPtr) {
  try {
    std::rethrow_exception(exceptionPtr);
  } catch (const VeloxException& e) {
    if (throwOnError_) {
      std::rethrow_exception(exceptionPtr); 
    } else {
      addError(index, exceptionPtr, errors_);
    }
  } catch (const std::exception& e) {
    if (throwOnError_) {
      VELOX_FAIL("{}", e.what()); 
    } else {
      try {
        VELOX_FAIL("{}", e.what());
      } catch (...) {
        addError(index, std::current_exception(), errors_);
      }
    }
  }
}
```

**Comment by mbasmanova** [comment]
@laithsakka Laith pointed out that we may also want to modify EvalCtx::applyToSelectedNoThrow to handle VeloxException and std::exception differently to reduce the amount of re-throwing needed.

**Comment by kagamiori** [comment]
@laithsakka also pointed out that if we re-throw std::exception as VeloxException, the file and line number in the error message would be of EvalCtx::setError() instead of the original location that throws in the UDF.

**Comment by mbasmanova** [comment]
> @laithsakka also pointed out that if we re-throw std::exception as VeloxException, the file and line number in the error message would be of EvalCtx::setError() instead of the original location that throws in the UDF.

That's indeed the case. Today, we don't get file name and line number at all. Getting file name and line number from the EvalCtx::setError() is not useful, but doesn't hurt either. The actual win is in getting the additional Context: and Top-Level Context: information.

**Comment by kagamiori** [comment]
> > @laithsakka also pointed out that if we re-throw std::exception as VeloxException, the file and line number in the error message would be of EvalCtx::setError() instead of the original location that throws in the UDF.
> 
> That's indeed the case. Today, we don't get file name and line number at all. Getting file name and line number from the EvalCtx::setError() is not useful, but doesn't hurt either. The actual win is in getting the additional Context: and Top-Level Context: information.

Yes, I agree. Just wanted to bring this up and maybe we'd like to document this somewhere to avoid potential confusion of users.
