### ISSUE TITLE
Add support for timeouts in S3FileSystem

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#2941]
We need to add an option to configure the `requestTimeoutMs` and `connectionTimeoutMs` 
in AWS C++ SDK client. The current SDK defaults are too small (3 sec, 1 sec) to handle AWS S3 storage.

Presto defaults these to 5 seconds. See `hive.s3.connect-timeout` and `hive.s3.socket-timeout`
https://github.com/prestodb/presto/blob/5adc7c00aec765ecba85a4923cbfa1d791195db9/presto-hive/src/main/java/com/facebook/presto/hive/s3/HiveS3Config.java#L54

https://github.com/aws/aws-sdk-cpp/blob/34fcd4beaa77bf394806631eae9270ad28ece77e/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h#L96
https://github.com/aws/aws-sdk-cpp/blob/main/src/aws-cpp-sdk-core/source/client/ClientConfiguration.cpp#L55

**Comment by majetideepak** [comment]
@jayadeep-jayaraman that is correct. The code comments explain the timeouts better https://github.com/aws/aws-sdk-cpp/blob/34fcd4beaa77bf394806631eae9270ad28ece77e/aws-cpp-sdk-core/include/aws/core/client/ClientConfiguration.h#L96

**Comment by chrisxu333** [comment]
Hi @majetideepak, I‘m fairly new to Velox but since it's labeled "good first issue", can I take this issue as my first contribution to Velox, if nobody is working on it?

**Comment by majetideepak** [comment]
@chrisxu333 Nobody is working on this.

**Comment by chrisxu333** [comment]
> @chrisxu333 Nobody is working on this.

Sounds good, I'll work on this then.

**Comment by kevinmingtarja** [comment]
Hi, is this still being worked on? I'd like to contribute to this if not!

**Comment by qqibrow** [comment]
@majetideepak could you chime in?  We also need this feature. and can we add user agent support as well? user agent setting is very important to track s3 usage in production: https://github.com/prestodb/presto/blob/5adc7c00aec765ecba85a4923cbfa1d791195db9/presto-hive/src/main/java/com/facebook/presto/hive/s3/HiveS3Config.java#L415 .
