### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by natashaxin** [facebookincubator/velox#2948]
CMake Error in velox/common/encode/CMakeLists.txt:
  Imported target "Folly::folly" includes non-existent path

    "/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.

**Comment by zuochunwei** [comment]
the directory of `/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk` does not exist, there is a directory of `/Library/Developer/CommandLineTools/SDKs/MacOSX11.1.sdk`.

why `Folly::folly` includes `/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include`, or how upgrade the MacOSX11.1.sdk to the new version of MacOSX12.sdk

**Comment by mbasmanova** [comment]
CC: @kgpai @raulcd @Yuhta @pedroerp

**Comment by kgpai** [comment]
Hi @natashaxin , Can you post the full cmake output so we can better debug ? Thanks.

**Comment by assignUser** [comment]
Duplicate of #2924
