### ISSUE TITLE
TPCH performance regression possibly caused by the hash join disk spilling feature

### ISSUE THREAD

**Issue by markjin1990** [facebookincubator/velox#2987]
@xiaoxmeng @mbasmanova We noticed in our ByteDance production environment that this PR https://github.com/facebookincubator/velox/pull/2573 might have caused significant performance regression on TPCH (SF1000) performance benchmarks while spilling is certainly disabled on our deployment. With this commit, Q8 takes >3mins, but if we revert this commit, Q8 takes around 1.5mins. Similar performance regression also happens to queries like Q3, Q9, Q21 with this commit. The performance regression is mostly caused by a slower HashJoin, which is quite confusing given that ideally this commit should not make an impact on hash join performance if spilling is disabled. 
The same issue cannot be reproduced when running tpch benchmark test on a local machine. 
So far, we have not identified the actual root cause for issue we observed in this commit. No sure if you have encountered a similar performance issue at Meta?

PS: 
One thing we noticed might be a mistake in this commit. However, this is not the root cause of the performance regression we observed. 
![image](https://user-images.githubusercontent.com/1387708/198234279-97f004db-987e-40f1-a1f0-8a56425eea24.png)

In tpch Q8, the hashjoin joining part and lineitem is the bottleneck 
![image](https://user-images.githubusercontent.com/1387708/198396928-7e7966e7-15e4-43ef-8b2a-217e2f44eb8d.png)

After diving into stage 9, here is the difference
Before reverting #2573
![image](https://user-images.githubusercontent.com/1387708/198397515-194db56e-07a6-4eb7-963b-eb8873113dae.png)

After reverting #2573 
![image](https://user-images.githubusercontent.com/1387708/198397641-a831e704-fd4e-4a4e-b6db-da2e869f75ec.png)

**Comment by xiaoxmeng** [comment]
@markjin1990: can you try https://github.com/facebookincubator/velox/pull/2996 to see if the regression is caused by this. The parallel build is accidentally reverted. Also, I think the change pointed above is actually a good one? Thanks!

**Comment by markjin1990** [comment]
It works. Thanks! Also this this intended or it is also a mistake?
![image](https://user-images.githubusercontent.com/1387708/198699609-e0d4985c-0bec-4635-86a3-f12c2d9784a4.png)

**Comment by xiaoxmeng** [comment]
I think that change is good. Thanks for the quick verification @markjin1990
