### ISSUE TITLE
Compiler error: writing 1 byte into a region of size 0

### ISSUE THREAD

**Issue by save-buffer** [facebookincubator/velox#2994]
Hi, I'm trying to compile Velox now on Linux with GCC 10.2.1 and I'm getting a ton of the following error:

```
In static member function 'static PHYSICAL_TYPE duckdb::ParquetDecimalUtils::ReadDecimalValue(duckdb::const_data_ptr_t, duckdb::idx_t) [with PHYSICAL_TYPE = short int]',
    inlined from 'static DUCKDB_PHYSICAL_TYPE duckdb::DecimalParquetValueConversion<DUCKDB_PHYSICAL_TYPE, FIXED_LENGTH>::PlainRead(duckdb::ByteBuffer&, duckdb::ColumnReader&) [with DUCKDB_PHYSICAL_TYPE = short int; bool FIXED_LENGTH = false]' at /home/sasha/velox/velox/external/duckdb/parquet-amalgamation.cpp:30074:66,
    inlined from 'void duckdb::TemplatedColumnReader<VALUE_TYPE, VALUE_CONVERSION>::Plain(std::shared_ptr<duckdb::ByteBuffer>, uint8_t*, uint64_t, duckdb::parquet_filter_t&, duckdb::idx_t, duckdb::Vector&) [with VALUE_TYPE = short int; VALUE_CONVERSION = duckdb::DecimalParquetValueConversion<short int, false>]' at /home/sasha/velox/velox/external/duckdb/parquet-amalgamation.cpp:27412:49:
/home/sasha/velox/velox/external/duckdb/parquet-amalgamation.cpp:27602:15: error: writing 1 byte into a region of size 0 [-Werror=stringop-overflow=]
27602 |    res_ptr[i] = positive ? byte : byte ^ 0xFF;
      |    ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/sasha/velox/velox/external/duckdb/parquet-amalgamation.cpp: In member function 'void duckdb::TemplatedColumnReader<VALUE_TYPE, VALUE_CONVERSION>::Plain(std::shared_ptr<duckdb::ByteBuffer>, uint8_t*, uint64_t, duckdb::parquet_filter_t&, duckdb::idx_t, duckdb::Vector&) [with VALUE_TYPE = short int; VALUE_CONVERSION = duckdb::DecimalParquetValueConversion<short int, false>]':
/home/sasha/velox/velox/external/duckdb/parquet-amalgamation.cpp:27594:17: note: at offset 0 to object 'res' with size 2 declared here
27594 |   PHYSICAL_TYPE res = 0;
      |                 ^~~
```

Has anyone seen anything like this? Is this some static analysis with a new GCC maybe?

Thanks!

**Comment by mbasmanova** [comment]
CC: @raulcd @majetideepak @kgpai @Yuhta @laithsakka

**Comment by mbasmanova** [comment]
CC: @yingsu00

**Comment by majetideepak** [comment]
@save-buffer This error seems to be coming directly from DuckDB code. Are you able to build DuckDB using GCC 10.2.1 https://github.com/duckdb/duckdb?

**Comment by save-buffer** [comment]
Hi @majetideepak I was able to compile duckdb itself with GCC 10.2.1. I did make sure to enable the Parquet extension like so:

```
cmake ../../ -G Ninja -DBUILD_PARQUET_EXTENSION=TRUE -DCMAKE_BUILD_TYPE=Release
```
I guess it's some sort of issue with the amalgamation then. The relevant line of code seems to be in duckdb's `extension/parquet/include/parquet_decimal_utils.hpp`.

**Comment by majetideepak** [comment]
@save-buffer Likely an issue with the amalgamation. You should be able to add `-Wno-stringop-overflow` to the `CMAKE_CXX_FLAGS` for now.

**Comment by save-buffer** [comment]
@majetideepak That seems to have fixed it. Googling around it seems like this error is frequently a false positive (as here: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99578), and I've seen a few other projects disable it. Would it be useful to make a PR to disable the flag in `velox/external/duckdb/CMakeLists.txt` if using GCC?

**Comment by majetideepak** [comment]
@save-buffer Do open a PR to disable the warning with a note briefly describing the false positive nature of this flag.

**Comment by kgpai** [comment]
Closing issue due to fix.
