### ISSUE TITLE
Velox HDFS connector dependencies not statically linked

### ISSUE THREAD

**Issue by zhouyuan** [facebookincubator/velox#3047]
Hi Velox developers, 

Trying to enable the HDFS connectors in Gluten, I followed the scripts in setup_adapters.sh and installed libhdfs3 manually. 
https://github.com/facebookincubator/velox/blob/main/scripts/setup-adapters.sh#L34-L47
and then enable HDFS with `-DVELOX_ENABLE_HDFS`

The compile is fine but there are still several missing symbols in hdfs connector lib

```
nm _build/release/velox/connectors/hive/storage_adapters/hdfs/libvelox_hdfs.a | grep hdfs
                 U hdfsBuilderConnect
                 U hdfsBuilderSetNameNode
                 U hdfsBuilderSetNameNodePort
                 U hdfsDisconnect
                 U hdfsGetLastError
                 U hdfsNewBuilder
```
Thus Gluten will still require to link with libhdfs3, which is a bit trivial to as we need to deploy the libhdfs3 and its dependencies on many worker nodes. 

Is there any methods to optimize the build and use static link in HDFS connector?

Thanks, -yuan 

CC: @mbasmanova

**Comment by mbasmanova** [comment]
CC: @majetideepak

**Comment by mbasmanova** [comment]
CC: @kgpai

**Comment by kgpai** [comment]
@zhouyuan I havent used libhdfs3 - is it very hard to modify our hawq/hdfs build to create an archive file (.a) and then just statically link against it ? 
We would welcome any  help to contribute a fix for this and allow for static linking.

**Comment by majetideepak** [comment]
CC: @artem.malyshev, @frankobe

**Comment by zhouyuan** [comment]
@kgpai
Thanks for the hints, currently libhdfs3 depends on these packages mainly in my testing env:
```
Libgsasl  Libkrb5 Libuuid libxml2
```
on ubuntu system these packages do provide some static libs, however these libs are not compiled with "-fPIC" thus it's not working for Velox use case.
I have tried to rebuild those packages locally with -fPIC but ran into more similar issues with the the packages' dependencies :sweat: 
so want to check with community if there's any building method for this issue first

**Comment by majetideepak** [comment]
@zhouyuan Why do you need to install static libraries on the various worker nodes? You only need the dynamic libraries right?

**Comment by majetideepak** [comment]
Can't you disable the dynamic libraries for libhdfs3 and force a static linkage?

**Comment by zhouyuan** [comment]
> Can't you disable the dynamic libraries for libhdfs3 and force a static linkage?

Yes, I did tried to force static link, but the dependencies of libhdfs3 are not compiled with -fPIC
 
see comments here: 
https://github.com/facebookincubator/velox/issues/3047#issuecomment-1302849015

-yuan
