### ISSUE TITLE
Hive predicate pushdown disabled is not supported

### ISSUE THREAD

**Issue by yyang52** [facebookincubator/velox#3065]
Some cloud object storages (such as Ali OSS) may not support predicate pushdown mechanism, while there is no flag to toggle this option on and off in velox, which will cause the query fail due to `Table scan with filter pushdown disabled is not supported`.

Here are the error message and related code for your reference:

![image2022-10-31_11-14-44](https://user-images.githubusercontent.com/82208254/199410581-6e17d23e-9bc8-477f-96bd-67e0aba4888f.png)
![image2022-10-31_11-15-49](https://user-images.githubusercontent.com/82208254/199410622-2013acec-3cfc-4fbc-a5ee-9c01fb601b37.png)

**Comment by mbasmanova** [comment]
@yyang52 Hi, thank you for reporting an issue. It is more convenient to work with text, than images. Any chance you could replace images with text?

> Ali OSS

Curious, what is "Ali OSS"? The pushdown logic is implemented inside HiveConnector. Are you using some other connector?

**Comment by george-gu-2021** [comment]
@mbasmanova , Ali OSS is Alibaba Object Storage Service, and here is the service link: https://www.alibabacloud.com/product/object-storage-service

**Comment by mbasmanova** [comment]
@george-gu-2021 Then, you should be able to enable filter pushdown. Can you try that?

**Comment by pedroerp** [comment]
My understanding is that the pushdown enabled flag you refer to means that predicates will be pushed to the Table Scan node, not to the remote storage system (we don't really support that yet AFAIK). So in your case it should be ok to keep that flag enabled - even if your remote object store doesn't support predicate pushdown.

**Comment by george-gu-2021** [comment]
@pedroerp , you are right. We successfully enabled Velox over Alibaba OSS after upgrading the Velox code base and all TPC-H 22 queries got passed. The reason it failed before may be the previous version code was modified by mistake. Thanks for your insights!
