### ISSUE TITLE
Unclear --help on "velox_s3read_benchmark"; need help running benchmark on S3 connector

### ISSUE THREAD

**Issue by paul-amonson** [facebookincubator/velox#3088]
After building with:

make -E "EXTRA_CMAKE_FLAGS := -DVELOX_ENABLE_S3=ON" release

A executable called "velox_s3read_benchmark" is created in the _build/release/velox/connectors/hive/storage_adapters/s3fs/benchmark

I would like to use this to do some S3 file read benchmarks but the --help only leads to the following output with no real text on usage. Short term I need to know how to use this tool long term the --help should be fixed.

--------------------- OUTPUT -------------------------
velox_s3read_benchmark: Warning: SetUsageMessage() never called

  Flags from ./src/logging.cc:
    -alsologtoemail (log messages go to these email addresses in addition to
      logfiles) type: string default: ""
    -alsologtostderr (log messages go to stderr in addition to logfiles)
      type: bool default: false
    -colorlogtostderr (color messages logged to stderr (if supported by
      terminal)) type: bool default: false
    -drop_log_memory (Drop in-memory buffers of log contents. Logs can grow
      very quickly and they are rarely read before they need to be evicted from
      memory. Instead, drop them from memory as soon as they are flushed to
      disk.) type: bool default: true
    -log_backtrace_at (Emit a backtrace when logging at file:linenum.)
      type: string default: ""
    -log_dir (If specified, logfiles are written into this directory instead of
      the default logging directory.) type: string default: ""
    -log_link (Put additional links to the log files in this directory)
      type: string default: ""
    -log_prefix (Prepend the log prefix to the start of each log line)
      type: bool default: true
    -logbuflevel (Buffer log messages logged at this level or lower (-1 means
      don't buffer; 0 means buffer INFO only; ...)) type: int32 default: 0
    -logbufsecs (Buffer log messages for at most this many seconds) type: int32
      default: 30
    -logemaillevel (Email log messages logged at this level or higher (0 means
      email all; 3 means email FATAL only; ...)) type: int32 default: 999
    -logfile_mode (Log file mode/permissions.) type: int32 default: 436
    -logmailer (Mailer used to send logging email) type: string
      default: "/bin/mail"
    -logtostderr (log messages go to stderr instead of logfiles) type: bool
      default: false
    -max_log_size (approx. maximum log file size (in MB). A value of 0 will be
      silently overridden to 1.) type: int32 default: 1800
    -minloglevel (Messages logged at a lower level than this don't actually get
      logged anywhere) type: int32 default: 0
    -stderrthreshold (log messages at or above this level are copied to stderr
      in addition to logfiles.  This flag obsoletes --alsologtostderr.)
      type: int32 default: 2
    -stop_logging_if_full_disk (Stop attempting to log to disk if the disk is
      full.) type: bool default: false

  Flags from ./src/utilities.cc:
    -symbolize_stacktrace (Symbolize the stack trace in the tombstone)
      type: bool default: true

  Flags from ./src/vlog_is_on.cc:
    -v (Show all VLOG(m) messages for m <= this. Overridable by --vmodule.)
      type: int32 default: 0
    -vmodule (per-module verbose level. Argument is a comma-separated list of
      <module name>=<log level>. <module name> is a glob pattern, matched
      against the filename base (that is, name ignoring .cc/.h./-inl.h). <log
      level> overrides any value given by --v.) type: string default: ""

  Flags from /build/gflags-WDCpEz/gflags-2.2.2/src/gflags.cc:
    -flagfile (load flags from file) type: string default: ""
    -fromenv (set flags from the environment [use 'export FLAGS_flag1=value'])
      type: string default: ""
    -tryfromenv (set flags from the environment if present) type: string
      default: ""
    -undefok (comma-separated list of flag names that it is okay to specify on
      the command line even if the program does not define a flag with that
      name.  IMPORTANT: flags in this list that have arguments MUST use the
      flag=value format) type: string default: ""

  Flags from /build/gflags-WDCpEz/gflags-2.2.2/src/gflags_completions.cc:
    -tab_completion_columns (Number of columns to use in output for tab
      completion) type: int32 default: 80
    -tab_completion_word (If non-empty, HandleCommandLineCompletions() will
      hijack the process and attempt to do bash-style command line flag
      completion on this value.) type: string default: ""

  Flags from /build/gflags-WDCpEz/gflags-2.2.2/src/gflags_reporting.cc:
    -help (show help on all flags [tip: all flags can have two dashes])
      type: bool default: false currently: true
    -helpfull (show help on all flags -- same as -help) type: bool
      default: false
    -helpmatch (show help on modules whose name contains the specified substr)
      type: string default: ""
    -helpon (show help on the modules named by this flag value) type: string
      default: ""
    -helppackage (show help on all modules in the main package) type: bool
      default: false
    -helpshort (show help on only the main module for this program) type: bool
      default: false
    -helpxml (produce an xml version of help) type: bool default: false
    -version (show version and build info and exit) type: bool default: false

  Flags from /home/localuser/workspace/_build/release/_deps/folly-src/folly/detail/MemoryIdler.cpp:
    -folly_memory_idler_purge_arenas (if enabled, folly memory-idler purges
      jemalloc arenas on thread idle) type: bool default: true

  Flags from /home/localuser/workspace/_build/release/_deps/folly-src/folly/executors/CPUThreadPoolExecutor.cpp:
    -dynamic_cputhreadpoolexecutor (CPUThreadPoolExecutor will dynamically
      create and destroy threads) type: bool default: true

  Flags from /home/localuser/workspace/_build/release/_deps/folly-src/folly/executors/IOThreadPoolExecutor.cpp:
    -dynamic_iothreadpoolexecutor (IOThreadPoolExecutor will dynamically create
      threads) type: bool default: true

  Flags from /home/localuser/workspace/_build/release/_deps/folly-src/folly/executors/ThreadPoolExecutor.cpp:
    -threadtimeout_ms (Idle time before ThreadPoolExecutor threads are joined)
      type: int64 default: 60000

  Flags from /home/localuser/workspace/_build/release/_deps/folly-src/folly/init/Init.cpp:
    -logging (Logging configuration) type: string default: ""

  Flags from /home/localuser/workspace/_build/release/_deps/folly-src/folly/synchronization/Hazptr.cpp:
    -folly_hazptr_use_executor (Use an executor for hazptr asynchronous
      reclamation) type: bool default: true

  Flags from /home/localuser/workspace/velox/common/file/benchmark/ReadBenchmark.cpp:
    -bytes (If 0, runs through a set of predefined read patterns. If non-0,
      this is the size of a single read. The reads are made in --num_in_run
      consecutive batchhes with --gap bytes between each read) type: int32
      default: 0
    -file_size_gb (Limits the test to the first --file_size_gb of --path. 0
      means use the whole file) type: int64 default: 0
    -gap (Gap between consecutive reads if --bytes is non-0) type: int32
      default: 0
    -measurement_size (Total reads per thread when throughput for a
      --bytes/--gap/--/gap/--num_in_run combination) type: int32
      default: 104857600
    -num_in_run (Number of consecutive reads of --bytes separated by --gap
      bytes) type: int32 default: 10
    -num_threads (Test paralelism) type: int32 default: 16
    -odirect (Use O_DIRECT) type: bool default: false
    -path (Path of test file) type: string default: ""
    -seed (Random seed, 0 means no seed) type: int32 default: 0

  Flags from /home/localuser/workspace/velox/connectors/hive/storage_adapters/s3fs/benchmark/S3ReadBenchmark.cpp:
    -s3_config (Path of S3 config file) type: string default: ""

  Flags from /home/localuser/workspace/velox/flag_definitions/flags.cpp:
    -avx2 (Enables use of AVX2 when available) type: bool default: true
    -bmi2 (Enables use of BMI2 when available) type: bool default: true
    -max_block_value_set_length (Max entries per column that the block
      meta-record stores for pre-flight filtering optimization) type: int32
      default: 5
    -memory_usage_aggregation_interval_millis (Interval to compute aggregate
      memory usage for all nodes) type: int32 default: 2
    -velox_exception_system_stacktrace_enabled (Enable the stacktrace for
      system type of VeloxException) type: bool default: true
    -velox_exception_system_stacktrace_rate_limit_ms (Min time interval in
      milliseconds between stack traces captured in system type of
      VeloxException; off when set to 0 (the default)) type: int32 default: 0
    -velox_exception_user_stacktrace_enabled (Enable the stacktrace for user
      type of VeloxException) type: bool default: false
    -velox_exception_user_stacktrace_rate_limit_ms (Min time interval in
      milliseconds between stack traces captured in user type of
      VeloxException; off when set to 0 (the default)) type: int32 default: 0
    -velox_memory_pool_mb (Size of file cache/operator working memory in MB)
      type: int32 default: 4096
    -velox_save_input_on_expression_any_failure_path (Enable saving input
      vector and expression SQL on any failure during expression evaluation.
      Specifies the directory to use for storing the vectors and expression SQL
      strings.) type: string default: ""
    -velox_save_input_on_expression_system_failure_path (Enable saving input
      vector and expression SQL on system failure during expression evaluation.
      Specifies the directory to use for storing the vectors and expression SQL
      strings. This flag is ignored if
      velox_save_input_on_expression_any_failure_path is set.) type: string
      default: ""
    -velox_time_allocations (Record time and volume for large allocation/free)
      type: bool default: true
    -velox_use_malloc (Use malloc for file cache and large operator
      allocations) type: bool default: true
------------------------------------------------------------

**Comment by mbasmanova** [comment]
CC: @majetideepak

**Comment by mbasmanova** [comment]
@paul-amonson Try --helpmatch (see Special Flags section in https://gflags.github.io/gflags/)

```
--helpmatch S3ReadBenchmark
```

**Comment by paul-amonson** [comment]
So this only filtered the pasted list above to:

Flags from /home/localuser/workspace/velox/connectors/hive/storage_adapters/s3fs/benchmark/S3ReadBenchmark.cpp:
-s3_config (Path of S3 config file) type: string default: ""

Unfortunately, I still don't have a syntax for the command line to execute the "velox_s3read_benchmark" executable. Also, I can't find documentation for the referred to "S3 config file".

**Comment by majetideepak** [comment]
@paul-amonson The PR description has some details on how to run this https://github.com/facebookincubator/velox/pull/1033.

I am currently working on the documentation for this as part of https://github.com/facebookincubator/velox/issues/2861

**Comment by majetideepak** [comment]
Paul is now one of the experts on S3ReadBenchmark and TpchBenchmark.

**Comment by majetideepak** [comment]
S3 Config is now available here: https://facebookincubator.github.io/velox/configs.html#amazon-s3-configuration
