### ISSUE TITLE
Crash in approx_most_frequent

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#3101]
Reproduce by running single aggregation `approx_most_frequent(c0, c1, c2)` over attached vector.

[approx_most_fr.tar.gz](https://github.com/facebookincubator/velox/files/9940420/approx_most_fr.tar.gz)

**Comment by Yuhta** [comment]
It's crashing because `buckets` is too large.  We will need #3159 to limit the range of the argument in fuzzer.

**Comment by mbasmanova** [comment]
@Yuhta Can we add a check and throw an exception instead of crashing? Otherwise, a client may inadvertently send a "bad" query and crash the cluster.

**Comment by Yuhta** [comment]
@mbasmanova It's hard to draw the line here, something working fine on one machine might be OOM on another, and we don't want to put the value too small here to make it too limiting for the user.

**Comment by mbasmanova** [comment]
> buckets is too large

How large is this? Would it be reasonable to limit 'buckets' to 100 (or 1000) entries?

**Comment by Yuhta** [comment]
@mbasmanova That would be too restricting.  Java Presto has a limit of 2^30, but on some machines this can still be OOM.

**Comment by mbasmanova** [comment]
> @mbasmanova That would be too restricting. Java Presto has a limit of 2^31, but on some machines this can still be OOM.

Having buckets value that large doesn't seem to make sense? What's the use case? Does Java Presto OOM as well? We have seen cases in the past where Presto Java lacks checks for inputs and allows a bad query to bring down the cluster. We should not "match" that behavior.

**Comment by Yuhta** [comment]
@mbasmanova I would suggest we hook this into the memory arbitrageur and turn the input with too large values into something like a `VeloxException` based on the runtime configuration.
