### ISSUE TITLE
Repro not correctly restore type of field reference

### ISSUE THREAD

**Issue by pzhzqt** [facebookincubator/velox#3135]
velox/expression/tests/velox_expression_fuzzer_test --velox_fuzzer_enable_complex_types --repro_persist_path ~/fuzzer_repro --seed 987157638 (Could be any other thing, this is just an example)

This should fail, however, the repro successfully ran the query(even after #2972 is fixed temporarily locally). After looking into it, it seems the FieldReference exprs aren't correctly rebuilt from sql: not the same as original type

toString() from TypedExpr:
original:
in(array_join("c0","c1") .... (omitted)
vs repro
in(array_join(ROW["c0"],ROW["c1"]) .... (omitted)

**Comment by mbasmanova** [comment]
It is not clear what's wrong here. Would you explain a bit more?

**Comment by pzhzqt** [comment]
> It is not clear what's wrong here. Would you explain a bit more?
I'm still trying to understand more myself. Now all I know is that the example test fails and persists repro files, however, expression runner successfully ran the query from the repro files, and the only difference I found right now from `toString()` from the typedExpr is that in fuzzer it's `array_join("c0","c1")`, and when reproduced from the exact same sql it somehow become `array_join(ROW["c0"],ROW["c1"])`

**Comment by pzhzqt** [comment]
> I think this is expected. That's just the difference in output between toString() and toSql(). The problem must be somewhere else.

Actually, they are both result from `toString()`

**Comment by pzhzqt** [comment]
Sorry, false alarm. It seems I just didn't run the reproducer correctly, just add --mode verify will successfully reproduce

**Comment by mbasmanova** [comment]
@pzhzqt Happy to hear the issue is resolved.
