### ISSUE TITLE
Type "any" should not appear in the return type signature.

### ISSUE THREAD

**Issue by laithsakka** [facebookincubator/velox#3168]
ex: this signature should fail to build, it's meaningless. 
  auto signature = exec::FunctionSignatureBuilder()
                       .returnType("array(any)")
                       .argumentType("varchar")
                       .argumentType("bigint")
                       .build();

**Comment by kgpai** [comment]
@laithsakka Can you explain why ? for example I can create a udf like array(int) genRandomArray(std::string typeName, uint32 length) .

**Comment by laithsakka** [comment]
our expressions are type checked, if the output type is any its imposssible to infer the functions output type.
