### ISSUE TITLE
SemiProjection join result error when there are null keys in build table

### ISSUE THREAD

**Issue by storm-dance** [facebookincubator/velox#3169]
SemiProjection join should only output true/null when there are null keys in build table, while only true/false now.

The following UT can produce the error [ run in HashJoinTest] :

```
  auto probeVectors = makeBatches(3, [&](int32_t /*unused*/) {
    return makeRowVector({
        makeFlatVector<int64_t>({1, 2, 2, 3, 3, 3, 4, 5, 5, 6, 7}),
        makeFlatVector<int64_t>({10, 20, 21, 30, 31, 32, 40, 50, 51, 60, 70}),
    });
  });

  // Some keys are nullable
  auto buildVectors = makeBatches(3, [&](int32_t /*unused*/) {
    return makeRowVector({
        makeFlatVector<int64_t>(8, [](auto row) { return row; }, nullEvery(7)),
        makeFlatVector<int64_t>({100, 101, 300, 400, 500, 501, 700, 800}),
    });
  });

  createDuckDbTable("t", probeVectors);
  createDuckDbTable("u", buildVectors);

  auto planNodeIdGenerator = std::make_shared<core::PlanNodeIdGenerator>();
  auto plan = PlanBuilder(planNodeIdGenerator)
                  .values(probeVectors)
                  .project({"c0 AS t0", "c1 AS t1"})
                  .hashJoin(
                      {"t0"},
                      {"u0"},
                      PlanBuilder(planNodeIdGenerator)
                          .values(buildVectors)
                          .project({"c0 AS u0", "c1 AS u1"})
                          .planNode(),
                      "",
                      {"t0", "t1", "match"},
                      core::JoinType::kLeftSemiProject)
                  .planNode();

  HashJoinBuilder(*pool_, duckDbQueryRunner_)
      .planNode(plan)
      .referenceQuery("SELECT t.c0, t.c1, t.c0 in (SELECT u.c0 FROM u) FROM t")
      .run();
```

UT results:

Expected 33, got 33
3 extra rows, 3 missing rows
3 of extra rows:
	7 | 70 | false
	7 | 70 | false
	7 | 70 | false

3 of missing rows:
	7 | 70 | null
	7 | 70 | null
	7 | 70 | null

**Comment by mbasmanova** [comment]
@storm-dance Thank you for reporting.

- Left-side rows with nulls in the join key should report NULL regardless of whether build side has nulls or not.
- Left-side rows with non-null keys and no match in the build side should report FALSE if build side has no nulls and NULL if build side has nulls.

HashBuild needs to report whether there are null keys for kLeftSemiProject as well as for kNullAwareAntiJoin.

kRightSemiProject is tricky as we don't know whether probe side has any nulls (globally). Perhaps, Velox can rely on the query planner to ensure that probe-side nulls are replicated for kRightSemiProject similarly how nulls are replicated for kLeftSemiProject and kNullAwareAntiJoin.

CC: @xiaoxmeng @Yuhta
