### ISSUE TITLE
Hash join performance issue

### ISSUE THREAD

**Issue by marin-ma** [facebookincubator/velox#3173]
We are testing the performance over TPCH 2T dataset in Gluten with Velox. The total number of cores on the target machine is 56. 
We set up two workloads with the following configuration, and both handle 2T dataset.
1. Use all 56 cores
    Input file partitions = 56 * 4 = 224
    Shuffle partitions = 56 * 8 = 448
    Number of executors * Number of tasks per executor = 32 * 7 = 224
3.  Use 48 cores out of 56 cores
    Input file partitions = 48 * 4 = 192
    Shuffle partitions = 48 * 8 = 384
    Number of executors * Number of tasks per executor = 24 * 8 = 192

By comparing the running time of queries, some queries have worse performance under 56c. For example, Q4 takes 19s in 48c workload and takes 45s in 56c workload. After analyzing the hotspot and some printed data in one partition, we found the reason is the hash table size is too small and cause lots of hash collision.

|  | 56c | 48c |
|--|--|--|
| num hash keys | 256,518 | 299,237|
| hash table size | 262,144 | 524,288|

```
+   97.00%    97.00%  generic_benchma  libvelox.so               [.] facebook::velox::exec::HashTable<true>::joinNormalizedKeyProbe
+   86.33%     0.00%  generic_benchma  libvelox.so               [.] facebook::velox::exec::Driver::runInternal
+   85.37%     0.05%  generic_benchma  libvelox.so               [.] facebook::velox::exec::HashProbe::addInput
+   85.08%     0.00%  generic_benchma  libvelox.so               [.] facebook::velox::exec::HashTable<true>::joinProbe
+   11.07%     0.00%  generic_benchma  [unknown]                 [.] 0x00000000002798e2
+    0.93%     0.00%  generic_benchma  [unknown]                 [k] 0xffffffffba000d82
+    0.88%     0.00%  generic_benchma  [unknown]                 [.] 0xffffffffb9e8a32e
+    0.87%     0.00%  generic_benchma  [unknown]                 [.] 0xffffffffb9271461
+    0.82%     0.00%  generic_benchma  [unknown]                 [.] 0xffffffffb93536c1
+    0.74%     0.00%  generic_benchma  [unknown]                 [.] 0xffffffffb9352c69
+    0.73%     0.00%  generic_benchma  libvelox.so               [.] facebook::velox::exec::HashProbe::getOutput
+    0.71%     0.00%  generic_benchma  [unknown]                 [.] 0xffffffffb9365678
+    0.68%     0.00%  generic_benchma  [unknown]                 [.] 0xffffffffb93650e9
+    0.52%     0.00%  generic_benchma  libvelox.so               [.] facebook::velox::exec::HashProbe::fillOutput
     0.50%     0.00%  generic_benchma  libvelox.so               [.] facebook::velox::exec::(anonymous namespace)::extractColumns
```

In above workload, the size of hash table is computed only once, and never grow. The chunk below is the first time computing and setting the hash table size. The arg numNew is 0, so the size is computed only based on numDistinct_. It should also add the load factor to numDistinct_ to get a proper hash table size.
https://github.com/facebookincubator/velox/blob/5df0bc59ce491ec5766a4a0e4ae389f31e9899ed/velox/exec/HashTable.cpp#L617-L627

**Comment by mbasmanova** [comment]
CC: @Yuhta @xiaoxmeng @oerling

**Comment by marin-ma** [comment]
CC: @FelixYBW
