### ISSUE TITLE
Is there release for Velox ?

### ISSUE THREAD

**Issue by vimalKeshu** [facebookincubator/velox#3183]
Is it safe to use Velox in production environment as there is no release provided yet ?

**Comment by assignUser** [comment]
Velox does not have a release cycle yet as the API is not stable enough for any compatibility guarantees. Once the API is stable enough there will be official releases. If you want to use velox you should pin a certain commit hash for consistency until there are releases.

You have to decide yourself *if* you want to use velox in production: For some the unstable, changing nature of the current API would be an absolute no-go, for some the power velox provides is such an improvement that it's worth using, even without releases. :shrug:
