### ISSUE TITLE
How to export Constant Vector to Arrow

### ISSUE THREAD

**Issue by eedalong** [facebookincubator/velox#3184]
Great project guys！Can somebody help to answer how to export Constant vector to arrow?

**Comment by eedalong** [comment]
Create a arrow T vector of length N, each value is constant_vec[0] right?

**Comment by mbasmanova** [comment]
CC: @Yuhta

**Comment by Yuhta** [comment]
Currently it's not supported yet, but you can use `BaseVector::flattenVector` to convert it to flat first.  Once Arrow has support for constant encoding, we will be able to add this support.

**Comment by pedroerp** [comment]
We are also working with the Arrow community to extend the Arrow standard and add support for RLE and Constant encoding (the latter maybe as a base case for RLE). We should see these new encodings being added to Arrow in the next few months, and once they are added we'll add the proper conversions to our Arrow bridge. 

For now the only way is by flattening the vector like @Yuhta mentioned. @Yuhta should we add this logic to the Arrow bridge in the meantime, for completeness?

**Comment by Yuhta** [comment]
@pedroerp I would keep it this way until we can do a direct conversion, to show that the cost of this operation including memory allocation.  But if we see more people requesting this (and if Arrow is late on their schedule) we can add it as a temporary solution.

**Comment by eedalong** [comment]
Thx guys. I see that import data from arrow to velox is mostly zero-copy except for `string` column right, but export a velox vector to arrow always needs memory allocationa and copy. Do we have plan for supporting zero-copy velox data export?

**Comment by Yuhta** [comment]
@eedalong The conversion from arrow to velox is also zero-copy wherever we can.

**Comment by eedalong** [comment]
@Yuhta  Yeah, I know this, I mean velox to arrow conversion

**Comment by eedalong** [comment]
> @eedalong Sorry that was a typo, I meant velox to arrow is also zero-copy. In line 369 we reuse the underlying buffer without copy.

I see, great, thx!
