### ISSUE TITLE
Implement partial aggregation passthrough

### ISSUE THREAD

**Issue by shiyu-bytedance** [facebookincubator/velox#3194]
From benchmarking TPCH Q15, it was discovered that velox is about 10x slower than running the equivalent Q15 SQL using DuckDB, against the same parquet input.

The majority of time is spent in partial aggregation's hashtable.clear(), as shown in the below profile, caused by high cardinality on the group by columns:
![image](https://user-images.githubusercontent.com/105019964/201224786-cd273a70-3f05-4b0f-8451-3b9feb2facd9.png)

To alleviate this problem, and borrowing from previous discussions, we decide to implement an optimization that adaptively detect input groupby key cardinality and in the case of high cardinality, simply passthrough partial aggregation node, tagging the output as "Raw" and sending it directly downstream to final aggregation node.

**Comment by shiyu-bytedance** [comment]
cc @frankobe @mbasmanova

**Comment by mbasmanova** [comment]
@shiyu-bytedance Curious, how does Velox performance compares to DuckDB if you disable partial aggregation or increase the memory limit?

**Comment by mbasmanova** [comment]
This enhancement requires changes in the query planner as well. It would be nice to put together a design document and a list of tasks / milestones.

**Comment by shiyu-bytedance** [comment]
@mbasmanova 

> Curious, how does Velox performance compares to DuckDB if you disable partial aggregation or increase the memory limit?

Disabling partial aggregation or increasing memory limit brings Velox to 1.5 - 2x of DuckDB.

> This enhancement requires changes in the query planner as well. It would be nice to put together a design document and a list of tasks / milestones.

Sounds good. Internally, we just implemented a "simpler" version where we skip the "hashing" (groupless) in partial aggregation(i.e 1 input row = 1 intermediate output) and observed very good performance(roughly on par with duckdb).

**Comment by mbasmanova** [comment]
@shiyu-bytedance When comparing with DuckDB, perhaps, it is better to use kSingle aggregation type. DuckDB doesn't support distributed execution, hence, doesn't implement partial + final aggregation. When running on single node, there is no benefit to that splitting, hence, using kSingle is more appropriate.

**Comment by FelixYBW** [comment]
@shiyu-bytedance  Is the pass through feature implemented?

We noted the similar issue in Gluten. TPCDS Q67's aggregation has very bad performance, Q67's aggreation has low cardinality. The reason is partial aggregation output current rows and flushed hash table once exceeding kMaxPartialAggregationMemory. We need to increase the kMaxPartialAggregationMemory to void the hash table rebuild. But once we increase the value, TPCH Q17 and 18 has big regression because its partial aggregation has high cardinality, building a large table is a waste . 

@rui-mo is going to implement a feature to check the cardinality firstly on default kMaxPartialAggregationMemory, if it's low then we increase the hash table size, otherwise we output and flash. We can get better performance if we check the cardinality here then pass through the following rows on high cardinality.

**Comment by FelixYBW** [comment]
@rui-mo has implemented an simple one to check the cardinality every 16 vectors to decide the hash table flush or keep. We didn't implement pass through. @shiyu-bytedance have you implement it and will submit a PR?

**Comment by yingsu00** [comment]
@shiyu-bytedance We are also looking forward to this feature. Are you going to send a PR for this?

**Comment by mbasmanova** [comment]
CC: @aditi-pandit

**Comment by mbasmanova** [comment]
Orri and I discussed this a bit more and we would like to propose an implementation that doesn't require planner changes. 

The idea is very similar to what @shiyu-bytedance has implemented, i.e. if partial aggregation is not productive (doesn't reduce cardinality sufficiently) we turn it off and convert each input row into single-value intermediate result. This allows us to save CPU cycles on hashing and comparing the group-by keys. 

It is possible convert raw inputs into single-value intermediate results using existing Aggregate function APIs, but it would be more efficient to provide a separate vector API. Some functions (min, max, sum) could implement it trivially by returning the input vector unmodified. Other functions would need to convert the data, but can do this more efficiently than calling initialize - addRawInput - extractAccumulators in sequence. 

One caveat to mention is that aggregate functions need to design the intermediate results to be space efficient for single or small number of values. This is helpful in general, but would be particularly useful for the cases where we convert raw inputs into single-value intermediate results in bulk. 

(This functionality can be extended in the future disable partial aggregation for a subset of group-by keys, i.e. in case when some keys reduce well, while others do not reduce at all or very little. In this case we can continue accumulating partial results for keys that reduce well and pass through data for other keys.)

CC: @oerling @kagamiori @Yuhta

**Comment by shiyu-bytedance** [comment]
@mbasmanova @yingsu00 @FelixYBW 
PR is here: https://github.com/facebookincubator/velox/pull/4157

**Comment by shiyu-bytedance** [comment]
Corresponding Prestissimo PR: https://github.com/prestodb/presto/pull/19129

**Comment by mbasmanova** [comment]
PR #4588 implements this design.
