### ISSUE TITLE
Question on AWS C++ SDK version

### ISSUE THREAD

**Issue by zhouyuan** [facebookincubator/velox#3198]
Hi Velox developers,

The example in unit tests is using 1.9.96 aws sdk. By default this version is not able to compile on ubuntu 22.04 see discussion on Gluten(https://github.com/oap-project/gluten/pull/491#issuecomment-1306018449).
Bumping to 1.10.x seems to compile there. 

the SDK release is very frequent and there are many new tags, do you have some AWS SDK version recommended to use?  

CC: @majetideepak @estoianovici  

thanks, -yuan

**Comment by mbasmanova** [comment]
CC: @majetideepak

**Comment by mbasmanova** [comment]
CC: @raulcd @kgpai

**Comment by kgpai** [comment]
Hi @zhouyuan feel free to contribute by creating  a PR bumping up the aws sdk version. We are always looking for contributions and it would be great if you can help out.

**Comment by majetideepak** [comment]
@zhouyuan I don't see any harm in updating the AWS C++ SDK version. But you don't necessarily have to make this change in Velox. You could always install the version you need in your application. If you want to use the Velox setup script, we can add can improve AWS_SDK_VERSION in `scripts/setup-adapters.sh` to be set in the environment. That way, Velox users can choose their preferred AWS SDK version.

**Comment by zhouyuan** [comment]
Hi @majetideepak, 
Thanks, I actually don't have much experience on the AWS SDK so I was trying to align with the version used in Velox community - trying to seek some advices on recommended version first

-yuan
