### ISSUE TITLE
TypePtr to arrow schema transformation support

### ISSUE THREAD

**Issue by eedalong** [facebookincubator/velox#3232]
For now, we have importFromArrow which transform a arrow schema to velox typeptr, but we lack velox typeptr->arrow schema transformation support. We can only do this by exportToArrow(vectPtr) but sometimes we may have a filter op and all data are filtered out and the result vectorptr is a nullptr, then we should expect to export a empty arrow table but with schema information. But in current implementation we will just get a empty arrow table with no schema information either.

![image](https://user-images.githubusercontent.com/39682259/201824781-ca5a8bda-8bd5-4752-8643-aca8962daa41.png)

**Comment by Yuhta** [comment]
We designed it this way because arrow schema containing both type and encoding information, and `TypePtr` is not enough.  You can create an empty vector from the type using `BaseVector::create` then arrow will consider it flat encoding.

**Comment by eedalong** [comment]
This is great, many thx!
