### ISSUE TITLE
Add "-g" to  CMAKE_CXX_FLAGS

### ISSUE THREAD

**Issue by zhejiangxiaomai** [facebookincubator/velox#3233]
User can not get code stack, when using perf or gdb to get velox code stack for analysing. 
Do we need add  "-g" to  CMAKE_CXX_FLAGS as a default Flag?

**Comment by majetideepak** [comment]
Can you use the `RelWithDebInfo` CMAKE_BUILD_TYPE?

**Comment by zhejiangxiaomai** [comment]
Ok, I will try it.

**Comment by zhejiangxiaomai** [comment]
It works.
