### ISSUE TITLE
Intermittent CI failure: velox_hdfs_file_test (Timeout)

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#3237]
Example: https://app.circleci.com/pipelines/github/facebookincubator/velox/16445/workflows/8b486d70-1022-4533-9972-1a27a82bf332/jobs/101874

```
[ RUN      ] HdfsFileSystemTest.writeDataFailures

99% tests passed, 1 tests failed out of 153

Total Test time (real) = 1504.26 sec

The following tests FAILED:
	146 - velox_hdfs_file_test (Timeout)
```

CC: @KevinyhZou @majetideepak @frankobe

**Comment by KevinyhZou** [comment]
I think I have reproduce the issue locally,  it cause an 'segmentation fault' when i run the velox_hdfs_file_test just now. and I think the reason for this issue may be below:
![image](https://user-images.githubusercontent.com/37431499/201935826-0c9e3f03-9f88-4d1a-a08a-039dd57fffc2.png)

when call writeFile->close(), the writeFile is deleted in libhdfs3/hdfs.cpp #hdfsCloseFile(...) function
![image](https://user-images.githubusercontent.com/37431499/201936190-c2da1dc8-2b77-4188-acd0-589bac26384f.png)

when call wirteFile->append(...), the file write handle may be a Nullptr, so the error happend.
@mbasmanova

**Comment by kgpai** [comment]
@mbasmanova @KevinyhZou You should be able to rerun CI jobs now - I have added you to contributor list, let me know if it doesnt work.

**Comment by KevinyhZou** [comment]
> @mbasmanova @KevinyhZou You should be able to rerun CI jobs now - I have added you to contributor list, let me know if it doesnt work.

OK
