### ISSUE TITLE
Add CI jobs to run fuzzer on SparkSQL functions

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#3257]
CC: @kagamiori @pedroerp @bikramSingh91 

We have CI jobs to run fuzzer on PrestoSQL functions: both on each PR and nightly. We need to add similar jobs for SparkSQL functions.

**Comment by mbasmanova** [comment]
@kgpai Krishna, is this done now?

**Comment by kgpai** [comment]
Yes this is done https://github.com/facebookincubator/velox/pull/3374
