### ISSUE TITLE
build/make error

### ISSUE THREAD

**Issue by darrenfu** [facebookincubator/velox#3297]
Hello there,

When I resync my forked repo, and "rebuild the project" in CLion, I got the following [cmake error](https://gist.github.com/darrenfu/c58aaffa042536d246b134ddaead2afd), I also got the following [make error](https://gist.github.com/darrenfu/f5c4d78f04fef65a01610364b5cf36d5) via the command line.

Any ideas?

**Comment by mbasmanova** [comment]
Try https://github.com/facebookincubator/velox/pull/3295

**Comment by darrenfu** [comment]
Thanks, @mbasmanova ! The `BaseRuntimeStatWriter` error is gone, here is a new make [error](https://gist.github.com/darrenfu/5ae2429e0f8d96e71a54475154ca7766), which seems to be related to class `SelectiveColumnReaderInternal.h`

**Comment by mbasmanova** [comment]
@darrenfu Try adding FOLLY_NULLABLE to raw pointers the compiler complains about.

**Comment by darrenfu** [comment]
Thanks @mbasmanova.

If you look at the failure error stacks, they mostly occurred at lines when include a header, such as `<optional>`, `<algorithm>`, `<memory>`, `<folly/Range.h>`. This is different from fixes like [#2026](https://github.com/facebookincubator/velox/pull/2026). Since it reports at nullptr in its dep libraries, I have less confidence adding FOLLY_NULLABLE to velox code will help, any other thoughts?

e.g.
```
In file included from /Users/dofu/git/velox/velox/common/base/RandomUtil.cpp:19:
In file included from /opt/homebrew/opt/llvm/bin/../include/c++/v1/optional:163:
In file included from /opt/homebrew/opt/llvm/bin/../include/c++/v1/__concepts/invocable.h:13:
In file included from /opt/homebrew/opt/llvm/bin/../include/c++/v1/__functional/invoke.h:15:
In file included from /opt/homebrew/opt/llvm/bin/../include/c++/v1/__type_traits/apply_cv.h:16:
In file included from /opt/homebrew/opt/llvm/bin/../include/c++/v1/__type_traits/remove_reference.h:13:
/opt/homebrew/opt/llvm/bin/../include/c++/v1/cstddef:50:9: error: no member named 'nullptr_t' in the global namespace
using ::nullptr_t;
```

**[Update]** I tried to resync the forked repo, reinstall most dependency libraries (and upgrade llvm to 15), clean the build folder and rerun "make debug", it doesn't help. Looks like it requires some code fixes for M1 build?   
Btw, I'm using Mac M1, macOS v12.6.1, CLion 2022.2.4.

**Comment by darrenfu** [comment]
@kgpai and I paired and located the issue, it relates to the incompatible versions of my Mac's CommandLineTools and XCode. Once I manually removed the `-isystem /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr/include` in the cmake command, the cmake command will pass. I will look into it further for an ultimate fix.

**Comment by kgpai** [comment]
@darrenfu Can we close this issue if your problem is resolved ?
