### ISSUE TITLE
Is there any roadmap for velox onboarding on CentOs version?

### ISSUE THREAD

**Issue by qingyuan18** [facebookincubator/velox#3308]
FYI,  as our prod env all runs on CentOS7.x version, which can't use velox so far

**Comment by mbasmanova** [comment]
CC: @kgpai @raulcd

**Comment by kgpai** [comment]
Hi @qingyuan18 I have verified that atleast velox minimal builds fine on centos 7 - though havent tested if parquet etc build. Can you add more details on what problems you are seeing from your end ?

**Comment by raulcd** [comment]
Hi @qingyuan18 ,
Velox should work on centos but you have to install the dependencies manually at the moment. There is currently a work in progress PR that adds a `setup-centos8.sh` script. I have reviewed and tested locally and will probably be merged soon:
https://github.com/facebookincubator/velox/pull/3023
Maybe this PR can help you, let us know if you test it and if you want to take a look on the PR.
As a follow up from this PR we plan to add a CI job to build velox and run tests on a centos 8 docker build on a nightly basis.

**Comment by qingyuan18** [comment]
hello @raulcd
Thanks for the information, I have tried the setup-centos8.sh  it uses dnf rather than yum, which is not applicable for  our CentOS7 env: 
dnf_install epel-release dnf-plugins-core # For ccache, ninja
dnf config-manager --set-enabled powertools
dnf_install ninja-build ccache gcc-toolset-9 git wget which libevent-devel \
  openssl-devel re2-devel libzstd-devel lz4-devel double-conversion-devel \
  libdwarf-devel curl-devel

dnf remove -y gflags
do you have the dependency list which I can install using yum in CentOS7 myself?  or I need to modified the setup script to adapt into CentOS7's yum ?

Regards

**Comment by assignUser** [comment]
Closing in favour of new issue as we do have setup scripts and ci for centos now.
