### ISSUE TITLE
Add Presto window functions to function coverage maps

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#3331]
### Bug description

It would be helpful to add window functions to the lists of all PrestoSQL functions and to PrestoSQL function coverage map:

- https://facebookincubator.github.io/velox/functions.html
- https://facebookincubator.github.io/velox/functions/coverage.html

### System information

n/a

**Comment by aditi-pandit** [comment]
https://github.com/facebookincubator/velox/pull/4454

**Comment by aditi-pandit** [comment]
This is completed now.
