### ISSUE TITLE
Parquet writer always uncompressed?

### ISSUE THREAD

**Issue by wjones127** [facebookincubator/velox#3335]
### Bug description

I was looking around the codebase, and noticed you are using the Apache Arrow C++ Parquet writer. Cool!

I also noticed you seem to only use the default `::parquet::WriterProperties`:

https://github.com/facebookincubator/velox/blob/9ae4bf9e1efe419d9b20b9a8630628fa2dc313b3/velox/dwio/parquet/writer/Writer.h#L81-L82

Unfortunately, this means you are always writing out Parquet files with no compression (the default value). You might want to change this so default to some compression, so that you are writing smaller files.

### System information

NA

**Comment by yzhang1991** [comment]
@majetideepak can you verify if this is fixed?

**Comment by majetideepak** [comment]
This is now fixed on the main branch.
