### ISSUE TITLE
Incorrect result when semi/anti join with extra filter

### ISSUE THREAD

**Issue by storm-dance** [facebookincubator/velox#3343]
### Bug description

1.  Semi Join:
Same as #2583 
- When build side is empty, rows with null join keys should report match = false
==>  Probe null join keys report match = false when no build side rows can pass join filter.

- Left-side rows with non-null keys and no match in the build side should report  FALSE if build side has no nulls.
==> Report FALSE when all build side null key rows can pass join filter.

2. How to know no build side rows can pass join filter (Semi/Anti join with join filter)
As mentioned in #3271 , 'replicateNullsAndAny' is not enough to know whether all build side rows(of all tasks) can pass join filter, so gather exchange is needed?

@mbasmanova @Yuhta 

### System information

no

**Comment by Yuhta** [comment]
@storm-dance Thanks I will take a look while Masha is on vacation.

**Comment by Yuhta** [comment]
I see, the null semantics are not handled properly in semi project joins.

@mbasmanova Shall we separate the case for null-aware (`IN`) and regular (`EXISTS`) semi project?  In the null-aware case for null probe keys, we need to do cross join to check if any rows passing the filter; if yes the result is null and false otherwise.

Also the `JoinType` enum will become quite messy if we keep adding like this.  I suggest we change it to a struct:
```c++
struct JoinType {
  enum { kInner, kLeft, kRight, kFull, kAnti} side;
  bool nullAware;
  bool project;
};
```

**Comment by mbasmanova** [comment]
@Yuhta Jimmy, thank you for looking into this. It makes sense to support both null-aware and regular semi joins. It would be nice to extend the Anti Joins documentation to include semi joins as well: https://facebookincubator.github.io/velox/develop/anti-join.html 

> Also the JoinType enum will become quite messy if we keep adding like this.

I agree.

> I suggest we change it to a struct:

Sounds good.

@storm-dance Thank you for reporting this issue. Curious how did you run into this? Are using using Presto or Spark front end? How do you translate a query plan to Velox?

**Comment by Yuhta** [comment]
Hi @storm-dance, we are planning to fix this behavior, and will probably have a look at the implementation in 2023 Q2.  If you need this earlier, feel free to contribute an implementation yourself.  Ideally the fix should contain
1. Backward compatible migration from old `JoinType` enum to new `JoinType` struct.
2. Reuse the existing Null-Aware Anti-Join code to implement the Null-Aware Semi Project.
