### ISSUE TITLE
Confirm aggregation percentage value type

### ISSUE THREAD

**Issue by shiyu-bytedance** [facebookincubator/velox#3371]
### Bug description

We should double check what [aggregationPct](https://github.com/facebookincubator/velox/blob/main/velox/exec/HashAggregation.cpp#L224-L225) is supposed to be.

Specifically, when its value is 2, does it mean 200% or 2%. 

This value is used to compare to with driverCtx->queryConfig().partialAggregationGoodPct(), which defaults to 0.5(50%), but if so, then we should not multiple by 100 on [this line](https://github.com/facebookincubator/velox/blob/main/velox/exec/HashAggregation.cpp#L224-L225).

### System information

n/a

**Comment by xiaoxmeng** [comment]
@shiyu-bytedance pct 2 means 2% and the default good reduction pct is set to 0.5%. We could tune this in practice which is the best value
