### ISSUE TITLE
Improve how the fuzzer selects expressions

### ISSUE THREAD

**Issue by bikramSingh91** [facebookincubator/velox#3388]
### Description

Proposed design:

- Pick functions based on function name and not their signatures
    - Currently, functions with more signatures are more favorable to be picked because they have more entries
    - there is a 50-50 chance of picking templated vs concrete functions, this makes one type more favorable depending on the number of each type available
    - When picking functions from templated functions, the signatureTemplateMap_ has separate entries for returnType "T" and other concrete types like bigint, however, functions with return type "T" can also be bound to concrete types like bigint, so those can be neglected. Instead, functions like these should always be considered for any return type.
    - The initial return type for the top level expression is by picking a random signature from all the concrete type signatures and then picking its return type. This means a complex type is never chosen as the starting signature. Need to improve this as well.
- Add mechanism to define function names and a factor that would increase their favorability. eg a startup flag that takes in a comma separated list of func_name=tickets where each function is by default assigned one ticket and increasing that number would increase its favorability.
- Finally add stats at the end of a fuzzer run that shows a the distribution of functions being chosen, so that we can tune these variables in case we notice some are neglected or some should be picked more often

**Comment by kagamiori** [comment]
cc @mbasmanova @pedroerp

**Comment by bikramSingh91** [comment]
Some Ideas of how to make progress on this:

I tried prototyping some of these and Step 3 is the biggest change and quite a bit tricky due the complex types and templated types and I have tried to capture some of those challenges here.

```
=============================
Step 1
=============================
Adding Stats
* At the end of a complete fuzzer run, output a list of function names selected and their frequency, percentage compared to total number of selection in decreasing order
Cons:
* The accounting is coarse grained as it only looks at the functions name selected and not which of its signatures was selected.


=============================
Step 2
=============================
Picking A top level ReturnType:
* Enhance ArgumentTypeFuzzer to support generating complex types
   * randomType() should take in a level param that it used to decide whether to pick a scalar or complex type
* This will also help selecting complex types as arguments for templated functions.
Cons:
* There can be some types that do not map to any function’s return type
* Some functions that have nested complex types will never be selected as top level.
* It will only support one level of nesting as a starting point.


=============================
Step 3
=============================
Function Selection:
Input:
* Map<Function, Signature>
* Signature can have return types that are:
   * Scalar Concrete
   * Complex<Scalar Concrete>
   * Complex<Template>
   * Template
* The following are converted into “CallableSignature” directly
   * Concrete
   * Complex<Concrete>
* The following are converted into “SignatureTemplate” directly
   * Complex<Template>
   * Template


Process:
1. Parse:  Map<Function, Signature> into a map from
FunctionName -> ReturnType -> List<CallableSignature/SignatureTemplate>
2. From this create a Map:
ReturnType -> List<FunctionName>

Here ReturnType is a baseType

3. Every function will have one entry for each base type that it supports


Cons:
   * Functions that have both concrete and templated/Complex returns types can be included twice.
   * A function can be selected solely based on its top level complex type and it might not bind to the concrete templated types resulting in the generateExpression() creating a Constant instead.
   * This happens because for complex types we have 3 variations of return type:
   * Complex<Scalar Concrete>
   * Complex<Template>
   * Template
   * So we need to go through the list of all functions and check which functions can be used. Eg. Array<timestamp> can pick “spilt” which has a concrete return type of Array<varchar>. Therefore, before we pick, we will have to go through all functions with base type as Array and only pick those that are either Array<timestamp> or Array<T> or T
=============================
Step 4
=============================
Probability Modifier:
Prerequisites: Function Selection Change


   * Startup flag that takes a comma separated list of functionName=<NumTickets>
   * Each function by default gets 1 ticket.
   * This means each function will have one entry in the map<ReturnType, List<FunctionName>>
   * A user can specify whether a function name should be more favorable by specifying more tickets for it.


Cons:
   * Functions that have both concrete and templated/Complex returns types can be included twice and have more tickets than specified.
```

**Comment by bikramSingh91** [comment]
I implemented step 1 mentioned above and tried running the fuzzer with the following flags

> --duration_sec 10 --enable_variadic_signatures --velox_fuzzer_enable_complex_types --lazy_vector_generation_ratio=0.5 --special_forms=and,or,if

 and saw this distribution of which functions are picked in decreasing order of frequency.

```
map_concat : 1750(10.5772%)
subscript : 1746(10.553%)
map : 1707(10.3173%)
if : 1166(7.04745%)
array_distinct : 981(5.92928%)
array_except : 932(5.63312%)
array_position : 836(5.05289%)
reverse : 448(2.70777%)
array_sort : 417(2.5204%)
slice : 399(2.4116%)
array_constructor : 389(2.35116%)
map_keys : 370(2.23633%)
map_values : 368(2.22424%)
eq : 236(1.42641%)
array_max : 218(1.31762%)
array_join : 205(1.23905%)
array_min : 193(1.16652%)
contains : 192(1.16047%)
is_null : 188(1.13629%)
round : 184(1.11212%)
minus : 124(0.749471%)
negate : 124(0.749471%)
ceiling : 113(0.682986%)
multiply : 110(0.664853%)
divide : 107(0.646721%)
greatest : 105(0.634633%)
mod : 105(0.634633%)
floor : 104(0.628589%)
least : 101(0.610456%)
sign : 98(0.592324%)
plus : 92(0.556059%)
ceil : 88(0.531883%)
date_add : 88(0.531883%)
abs : 84(0.507706%)
clamp : 83(0.501662%)
date_trunc : 70(0.423089%)
lte : 69(0.417044%)
regexp_extract_all : 66(0.398912%)
array_duplicates : 61(0.368691%)
split : 59(0.356603%)
array_sum : 53(0.320338%)
lt : 48(0.290118%)
distinct_from : 46(0.27803%)
neq : 46(0.27803%)
gte : 45(0.271985%)
arrays_overlap : 42(0.253853%)
bitwise_not : 41(0.247809%)
between : 40(0.241765%)
gt : 38(0.229677%)
substr : 38(0.229677%)
bitwise_left_shift : 36(0.217588%)
bitwise_or : 36(0.217588%)
bitwise_and : 36(0.217588%)
date_parse : 35(0.211544%)
bit_count : 34(0.2055%)
bitwise_arithmetic_shift_right : 32(0.193412%)
bitwise_right_shift_arithmetic : 32(0.193412%)
codepoint : 30(0.181324%)
bitwise_right_shift : 29(0.17528%)
regexp_extract : 27(0.163191%)
bitwise_xor : 27(0.163191%)
from_unixtime : 26(0.157147%)
strpos : 25(0.151103%)
combinations : 23(0.139015%)
hour : 23(0.139015%)
year_of_week : 22(0.132971%)
array_has_duplicates : 21(0.126927%)
year : 21(0.126927%)
truncate : 20(0.120882%)
quarter : 18(0.108794%)
millisecond : 18(0.108794%)
dow : 18(0.108794%)
empty_approx_set : 17(0.10275%)
from_base : 16(0.096706%)
second : 16(0.096706%)
day : 16(0.096706%)
url_extract_host : 16(0.096706%)
strrpos : 16(0.096706%)
replace : 16(0.096706%)
date_diff : 15(0.0906618%)
minute : 15(0.0906618%)
day_of_year : 14(0.0846177%)
regexp_replace : 14(0.0846177%)
tanh : 14(0.0846177%)
pow : 14(0.0846177%)
to_hex : 13(0.0785736%)
format_datetime : 13(0.0785736%)
yow : 13(0.0785736%)
doy : 12(0.0725295%)
lower : 12(0.0725295%)
e : 12(0.0725295%)
power : 12(0.0725295%)
rtrim : 11(0.0664853%)
concat : 11(0.0664853%)
month : 11(0.0664853%)
json_extract_scalar : 11(0.0664853%)
url_extract_port : 11(0.0664853%)
json_array_contains : 11(0.0664853%)
day_of_month : 11(0.0664853%)
crc32 : 10(0.0604412%)
url_extract_protocol : 10(0.0604412%)
url_extract_query : 10(0.0604412%)
atan : 10(0.0604412%)
day_of_week : 10(0.0604412%)
sha256 : 9(0.0543971%)
url_decode : 9(0.0543971%)
url_extract_fragment : 9(0.0543971%)
sha512 : 9(0.0543971%)
log2 : 9(0.0543971%)
split_part : 9(0.0543971%)
bitwise_logical_shift_right : 9(0.0543971%)
like : 9(0.0543971%)
xxhash64 : 8(0.048353%)
cos : 8(0.048353%)
infinity : 8(0.048353%)
date_format : 8(0.048353%)
chr : 8(0.048353%)
upper : 8(0.048353%)
and : 7(0.0423089%)
rpad : 7(0.0423089%)
to_base64 : 7(0.0423089%)
to_base : 7(0.0423089%)
tan : 7(0.0423089%)
json_array_length : 7(0.0423089%)
md5 : 7(0.0423089%)
log10 : 7(0.0423089%)
exp : 7(0.0423089%)
url_extract_parameter : 7(0.0423089%)
nan : 7(0.0423089%)
ltrim : 7(0.0423089%)
lpad : 7(0.0423089%)
sqrt : 7(0.0423089%)
length : 6(0.0362647%)
ln : 6(0.0362647%)
cbrt : 6(0.0362647%)
from_hex : 6(0.0362647%)
url_encode : 6(0.0362647%)
cosh : 5(0.0302206%)
pi : 5(0.0302206%)
from_base64 : 5(0.0302206%)
acos : 5(0.0302206%)
bitwise_shift_left : 5(0.0302206%)
not : 5(0.0302206%)
asin : 5(0.0302206%)
radians : 4(0.0241765%)
is_json_scalar : 4(0.0241765%)
is_finite : 4(0.0241765%)
to_unixtime : 4(0.0241765%)
or : 4(0.0241765%)
url_extract_path : 4(0.0241765%)
is_infinite : 4(0.0241765%)
sin : 4(0.0241765%)
atan2 : 3(0.0181324%)
regexp_like : 3(0.0181324%)
to_utf8 : 3(0.0181324%)
is_nan : 2(0.0120882%)
trim : 2(0.0120882%)
degrees : 2(0.0120882%)
zip : 0(0%)
map_entries : 0(0%)
```

**Comment by mbasmanova** [comment]
@bikramSingh91 Bikram,

>    * randomType() should take in a level param that it used to decide whether to pick a scalar or complex type

There is a similar method VectorFuzzer::randType. It would be nice to consolidate these two. 

```
  // Generates a random type, including maps, vectors, and arrays. maxDepth
  // limits the maximum level of nesting for complex types. maxDepth <= 1 means
  // no complex types are allowed.
  //
  // There are no options to control type generation yet; these may be added in
  // the future.
  TypePtr randType(int maxDepth = 5);
  RowTypePtr randRowType(int maxDepth = 5);
```

**Comment by mbasmanova** [comment]
> I implemented step 1 mentioned above and tried running the fuzzer with the following flags

Would you run this with longer duration, e.g. 10min vs. 10sec? It might be more convenient to analyze the results if these are added to the Google Sheet.

**Comment by bikramSingh91** [comment]
> 
> > * There can be some types that do not map to any function’s return type
> > * Some functions that have nested complex types will never be selected as top level.
> 
> Would you provide some examples?

Good Callout. Please disregard these points, I unfortunately did not revise this part of my notes while trying to make sense of the current implementation.



> > * At the end of a complete fuzzer run, output a list of function names selected and their frequency, percentage compared to total number of selection in decreasing order
> 
> It might be useful to separate statistics for testing of the same function name with different number of arguments. E.g. track testing of foo(a) and foo(a, b) separately.

We can add stats for this but I was worried that adding stats on dimensions that we cannot tune might confuse us.

Context:
I was currently only looking at stats per function name because that is the dimension where I was aiming to distribute favorability equally.

There are other dimension that are interesting and a potential candidate, for eg.
- number of arguments (as you mentioned)
- type of arguments
- certain inputs that trigger optimizations (like non-null fast-path, ascii only, etc)

This brings up the question of which dimensions do we consider while thinking about fairness. This decision would shape our final implementation, that is, how we build our choosing mechanism(step 2), tunable knobs (step 4), and observability metrics(Step1).
 In my current proposal, I am only considering the function name, and once a function is selected, all its signatures would get equal preference. My motivation was to keep the mechanism simple and still allow the ability to favor certain functions.

Having said that, we can definitely add metrics for these dimensions as a first step to help us make this decision. I would love to get more input from you and everyone else on this.

> > I implemented step 1 mentioned above and tried running the fuzzer with the following flags
> 
> Would you run this with longer duration, e.g. 10min vs. 10sec? It might be more convenient to analyze the results if these are added to the Google Sheet.

Will do

**Comment by bikramSingh91** [comment]
@mbasmanova Uploaded a spreadsheet with the stats.

Sheet 1: fuzzer run for 10 mins on current master
Sheet 2: fuzzer run for 20sec(see notes in sheet for why a small time was chosen) on a prototype with all the steps I described in my comment here: https://github.com/facebookincubator/velox/issues/3388#issuecomment-1340252132

https://docs.google.com/spreadsheets/d/11eG0ayO6hsSt1wV95nKfAGg_bZRHbOV0NDjEw-AMKJA/edit?usp=sharing

**Comment by mbasmanova** [comment]
@bikramSingh91 Thank you, Bikram.

I wonder why zip and map_entries do not get tested at all? Both should up with 0s.

**Comment by bikramSingh91** [comment]
> zip

Thats because both of them have a 2 level deep complex return type ARRAY(ROW(<>)). In the current state, return types are only picked from non-templated types so a 2 level complex type never gets used as a top level return type. Moreover, none of the current functions have an input type of the same structure so it never gets selected as an input expression too (even though return templated types can theoretically take this as an input, I suspect the logic that binds random types to ARRAY(T) types does not generate another level of complex input)
Also, the reason it does not get selected in my prototype even though I am using a randomized way of selecting top level return type is because I am only generating complex types with nesting level 1. Switching that to 2 should help solve this.

**Comment by kagamiori** [comment]
> even though return templated types can theoretically take this as an input, I suspect the logic that binds random types to ARRAY(T) types does not generate another level of complex input

You're right. I think we don't generate complex type for T when instantiating ARRAY(T). It would be great if we can remove this limitation.

https://github.com/facebookincubator/velox/blob/e8041f46dfefbafcdf71b6f38694009bad81bd65/velox/expression/tests/ArgumentTypeFuzzer.cpp#L30-L49

**Comment by kagamiori** [comment]
Some UDFs were not tested and indeed had bugs (e.g., #3542), while we didn't even know this case existed. Should we prioritize at least the first step to print out the number of times each UDF is tested at the end of each fuzzer run, so that we are aware of such gaps? @mbasmanova @bikramSingh91

**Comment by mbasmanova** [comment]
It might be useful to highlight functions that are not tested at all and functions that always fail. We could use ExprListener to identify a list of function used in the expression along with number of rows each function was evaluated on. This would allow us to identify functions that were evaluated on zero rows (e.g. maybe function was participating in a expression, but never got evaluated due to failures in other expression or nulls or something else).
