### ISSUE TITLE
How to sync changes from duckdb code base

### ISSUE THREAD

**Issue by darrenfu** [facebookincubator/velox#3411]
### Description

I have a fix [duckdb #5545](https://github.com/duckdb/duckdb/pull/5545) to resolve a known 'sprintf' build error with MacOS 13.0 sdk.  
We need to sync the directory: `velox/external/duckdb/` from [duckdb repo](https://github.com/duckdb/duckdb) (at least do an adhoc sync).

cc @pedroerp

**Comment by pedroerp** [comment]
Hi @darrenfu , there are instruction on how to update it here:

https://github.com/facebookincubator/velox/tree/main/velox/duckdb
