### ISSUE TITLE
Result mismatch between common and simplified path

### ISSUE THREAD

**Issue by bikramSingh91** [facebookincubator/velox#3471]
### Description

I was running fuzzer with switch and came across this issue, however I am not sure if the Switch expression and any role to play here. Attaching file to repro issue using ExpressionRunner.

### Error Reproduction

[velox_expressionVerifier_mzNXdx.zip](https://github.com/facebookincubator/velox/files/10198780/velox_expressionVerifier_mzNXdx.zip)

### Relevant logs

```bash
/Users/bikramjeet/dev/velox/cmake-build-debug/velox/expression/tests/velox_expression_runner_test --fuzzer_repro_path /Users/bikramjeet/dev/_velox_errors/velox_expressionVerifier_mzNXdx --mode verify
E20221209 15:52:30.207585 7936509 Exceptions.h:68] Line: /Users/bikramjeet/dev/velox/velox/expression/tests/ExpressionVerifier.cpp:67, Function:compareVectors, Expression: left->equalValueAt(right.get(), i, i) Different results at idx '20': '0.32423801231198013' vs. '0.6763309531379491', Source: RUNTIME, ErrorCode: INVALID_STATE
libc++abi: terminating with uncaught exception of type facebook::velox::VeloxRuntimeError: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Different results at idx '20': '0.32423801231198013' vs. '0.6763309531379491'
Retriable: False
Expression: left->equalValueAt(right.get(), i, i)
Function: compareVectors
File: /Users/bikramjeet/dev/velox/velox/expression/tests/ExpressionVerifier.cpp
Line: 67
Stack trace:
# 0  
# 1  
# 2  
# 3  
# 4  
# 5  
# 6  
# 7  
# 8  
# 9  
# 10 
# 11
```

**Comment by kagamiori** [comment]
Hi Bikram, could you also share the evaluated expression and input data in the log?

**Comment by bikramSingh91** [comment]
> Hi Bikram, could you also share the evaluated expression and input data in the log?

 you should be able to access all that info in the repro zipfile i attached under "Error Reproduction". Its decently large and the data includes complex types so i did not include it in the logs

**Comment by bikramSingh91** [comment]
Another result mis-match, this time its the expression is smaller and operates on date datatype.

SQL (Note: the swtich here was originally "if" but got converted to "switch" when the expression was serialized as a valid sql: 

"switch"("gt"("c0", "c1"), "switch"("gt"("c2", "round"("c3")), NULL::DATE), "greatest"("switch"("lt"("c4", '1457323771'::INTEGER), "c5", "c6"), "switch"(NULL::BOOLEAN, '4859599-12-03'::DATE, "c7"), '4715946-11-10'::DATE))
```
/Users/bikramjeet/dev/velox/cmake-build-debug/velox/expression/tests/velox_expression_runner_test --fuzzer_repro_path /Users/bikramjeet/dev/_velox_errors/velox_expressionVerifier_lGPlxd --mode verify
E20221212 15:16:07.074040 8729068 Exceptions.h:68] Line: /Users/bikramjeet/dev/velox/velox/expression/tests/ExpressionVerifier.cpp:67, Function:compareVectors, Expression: left->equalValueAt(right.get(), i, i) Different results at idx '0': '-4332802-04-26' vs. '1647034-08-06', Source: RUNTIME, ErrorCode: INVALID_STATE
libc++abi: terminating with uncaught exception of type facebook::velox::VeloxRuntimeError: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Different results at idx '0': '-4332802-04-26' vs. '1647034-08-06'
Retriable: False
Expression: left->equalValueAt(right.get(), i, i)
Function: compareVectors
File: /Users/bikramjeet/dev/velox/velox/expression/tests/ExpressionVerifier.cpp
Line: 67
Stack trace:
# 0  
# 1  
# 2  
# 3  
# 4  
# 5  
# 6  
# 7  
# 8  
# 9  
# 10 
# 11 
```
[mismatchDateResult.zip](https://github.com/facebookincubator/velox/files/10212887/mismatchDateResult.zip)
