### ISSUE TITLE
[Mac] Replace custom built dependencies with homebrewed libraries

### ISSUE THREAD

**Issue by darrenfu** [facebookincubator/velox#3474]
### Description

In `scripts/setup-macos.sh`, there are a few custom built dependencies (built from source code). Why not replace them with the official homebrewed version?
- range-v3 
- double-conversion 
- re2
- fmt
*NOTE*: `fmt` is tricky because its brew version is 9.1.0 which is incompatible with Meta's internal version: 8.1.0.  
Upgrade to homebrewed version will break the build. See the [9.1.0 build error](https://gist.github.com/darrenfu/ff42788e732cb04aa9c98acc37118fcd) and the past 8.x upgrade commit: https://github.com/facebookincubator/velox/commit/bc7b6fad728fdbfa3abde01664d106f30c320bbc.

With homebrewed libraries, we can enjoy the benefits such like:
1. Keep the dep version up-to-date without manually bumping up the versions.
2. Make all the dep source consistent and setup script simple to maintain.

Thoughts?

**Comment by darrenfu** [comment]
> @darrenfu We are actually moving away from having brew take care of dependencies to moving them all to cmake / resolve_dependencies. Theres already a pr out for fmt (#3100) . If you can move any of these above dependencies to also use resolve_dependencies, that would be great.

Thanks for the context, @kgpai. I will trim my PR for some minor changes other than the four brew deps. 
Regarding adding CMake deps, I'm not super familiar with that. I will park them for now.

**Comment by assignUser** [comment]
I think this issue can be closed but @darrenfu you might be interested in https://github.com/facebookincubator/velox/discussions/4992
