### ISSUE TITLE
Clarify the semantics of input.mayHaveNulls() in simple function

### ISSUE THREAD

**Issue by darrenfu** [facebookincubator/velox#3511]
### Expected behavior
fuzzer should pass. See the following command to run the fuzzer:
> velox_expression_fuzzer_test --enable_variadic_signatures --velox_fuzzer_enable_complex_types --lazy_vector_generation_ratio 0.2 --velox_fuzzer_enable_column_reuse --velox_fuzzer_enable_expression_reuse --seed 3175657226 --logtostderr=1

### Actual behavior
Fuzzer will fail because simplifyEval path will remove initial nulls (see #156), which creates a discrepancy between eval path and simplifyEval path. See CI failure log below.

### Relevant Info
The failure is gone once I switch from:
```cpp
FOLLY_ALWAYS_INLINE void call(out_type<Map<K, V>>& out, const arg_type<Array<Row<K, V>>>& inputArray) {
    VELOX_USER_CHECK(!inputArray.mayHaveNulls(), "map entry cannot be null");
}
```
to:
```cpp
FOLLY_ALWAYS_INLINE void call(out_type<Map<K, V>>& out, const arg_type<Array<Row<K, V>>>& inputArray) {
    for (const auto& tuple : inputArray) {
        VELOX_USER_CHECK(tuple.has_value(), "map entry cannot be null");
    }
}
```
I guess there is some underlying vector behavior mismatch between `mayHaveNulls()` and `item.has_value()`.  

To wrap it up, it's not recommended to use `mayHaveNulls()` in udf `call()` method, which will cause unexpected behavior in simplifyEval path.

### System information

Velox System Info v0.0.2
Commit: aea5e85e05570ca056e2db16060599af5137350f
CMake Version: 3.25.1
System: Darwin-21.6.0
Arch: arm64
C++ Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
C++ Compiler Version: 14.0.0.14000029
C Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
C Compiler Version: 14.0.0.14000029
CMake Prefix Path: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.0.sdk/usr;/Users/dofu/homebrew;/usr/local;/usr;/;/Users/dofu/homebrew/Cellar/cmake/3.25.1;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

### Relevant logs

```bash
I1212 19:12:22.016161 113105 ExpressionVerifier.cpp:80] Executing expression: greatest(subscript(map_from_entries("c0"),"c1"),2011-04-28T07:16:09.157640963,from_unixtime("c2"))
I1212 19:12:22.016181 113105 ExpressionVerifier.cpp:32] 3 vectors as input:
I1212 19:12:22.016202 113105 ExpressionVerifier.cpp:34] 	[CONSTANT ARRAY<ROW<"":TINYINT,"":TIMESTAMP>>: 100 elements, 10 elements starting at 40 {[40->154] {106, null}, [41->122] {119, null}, [42->38] {16, null}, [43->16] {79, null}, [44->149] {31, null}, ...}], [ARRAY ARRAY<ROW<"":TINYINT,"":TIMESTAMP>>: 17 elements, no nulls]
I1212 19:12:22.016237 113105 ExpressionVerifier.cpp:34] 	[CONSTANT TINYINT: 100 elements, 64]
I1212 19:12:22.016243 113105 ExpressionVerifier.cpp:34] 	[FLAT DOUBLE: 100 elements, 10 nulls]
E1212 19:12:22.017853 113105 Exceptions.h:68] Line: ../.././velox/functions/prestosql/MapFunctions.h:40, Function:call, Expression: !inputArray.mayHaveNulls() map entry cannot be null, Source: USER, ErrorCode: INVALID_ARGUMENT
E1212 19:12:22.020548 113105 FuzzerToolkit.cpp:131] Only one path threw exception:
I1212 19:12:22.021528 113105 ExpressionVerifier.cpp:295] Persisted input: --fuzzer_repro_path /tmp/fuzzer_repro/velox_expressionVerifier_lmKcgi --input_path /tmp/fuzzer_repro/velox_expressionVerifier_lmKcgi/input_vector --result_path /tmp/fuzzer_repro/velox_expressionVerifier_lmKcgi/result_vector --sql_path /tmp/fuzzer_repro/velox_expressionVerifier_lmKcgi/sql
terminate called after throwing an instance of 'facebook::velox::VeloxUserError'
  what():  Exception: VeloxUserError
Error Source: USER
Error Code: INVALID_ARGUMENT
Reason: map entry cannot be null
Retriable: False
Expression: !inputArray.mayHaveNulls()
Context: map_from_entries(c0)
Top-Level Context: greatest(subscript(map_from_entries(c0), c1), 2011-04-28T07:16:09.157640963:TIMESTAMP, from_unixtime(c2))
Function: call
File: ../.././velox/functions/prestosql/MapFunctions.h
Line: 40
Stack trace:
Stack trace has been disabled.Use --velox_exception_user_stacktrace=true to enable it.

*** Aborted at 1670872342 (Unix time, try 'date -d @1670872342') ***
*** Signal 6 (SIGABRT) (0x1b9d1) received by PID 113105 (pthread TID 0x7ff9132de300) (linux TID 113105) (maybe from PID 113105, UID 0) (code: -6), stack trace: ***
(error retrieving stack trace)
/bin/bash: line 13: 113105 Aborted                 (core dumped) _build/debug/velox/expression/tests/velox_expression_fuzzer_test --seed 123456 --enable_variadic_signatures --velox_fuzzer_enable_complex_types --lazy_vector_generation_ratio 0.2 --velox_fuzzer_enable_column_reuse --velox_fuzzer_enable_expression_reuse --duration_sec 60 --logtostderr=1 --minloglevel=0 --repro_persist_path=/tmp/fuzzer_repro

Exited with code exit status 134
CircleCI received exit code 134
```

**Comment by mbasmanova** [comment]
@darrenfu Darren, the semantics of mayHaveNulls are the following: (1) if returns false, it is guaranteed that there are no nulls; (2) if returns 'true', there may or may not be nulls. Hence, one should never assert that mayHaveNulls is false.

**Comment by mbasmanova** [comment]
CC: @laithsakka

**Comment by darrenfu** [comment]
> Hence, one should never assert that mayHaveNulls is false.

Thanks @mbasmanova for the elaboration! That makes sense to my case then. Let me close this issue.
