### ISSUE TITLE
How to control the compilation thread number exactly?

### ISSUE THREAD

**Issue by zuochunwei** [facebookincubator/velox#3532]
### Problem description

I changed the `NUM_THREADS` to 4 in the Makefile, but it does not work.

sometimes, there are only 4 compilation tasks, while sometimes there are more than ten tasks, which makes me confused.

Because I compiled in the container, too many tasks will lead to crash for OOM, I want to control the compilation task number exactly. how to do this?

### System information

compile

**Comment by assignUser** [comment]
To change the number of threads when using docker compose you have to set the envvar: `NUM_THREADS=4` or provide the var directly via the `-e` param as explained in the [README](https://github.com/facebookincubator/velox#building-velox-with-docker-compose)
