### ISSUE TITLE
ExprSet destructor throws exception when an ExprSetListener is set and one of the expressions in the set cannot be converted to SQL

### ISSUE THREAD

**Issue by bikramSingh91** [facebookincubator/velox#3578]
### Bug description

As the title suggests, the destructor throws and error which ends up being unhandled and causes the process to terminate.

https://github.com/facebookincubator/velox/blob/af6864a61b2b86f6a70cfd60bbc2d6beb380c6bb/velox/expression/Expr.cpp#L1616

Possible solution: handle the error here and append a generic error message to the list of sqls. This would allow the destructor to successful execute the callback that handles expression stats.

### System information

N/A

**Comment by mbasmanova** [comment]
@bikramSingh91 Curious what was the expression that failed to be converted to SQL.

**Comment by bikramSingh91** [comment]
> @bikramSingh91 Curious what was the expression that failed to be converted to SQL.

It was trying to convert a literal of VARBINARY type to SQL and throwing at:
https://github.com/facebookincubator/velox/blob/35a9f5190e6d1647dcae54954436fe6b360932b9/velox/expression/ConstantExpr.cpp#L216
