### ISSUE TITLE
Add nullability check to "make format-check"

### ISSUE THREAD

**Issue by yingsu00** [facebookincubator/velox#3586]
### Description

Often times there're a lot of the "insert _NonNull" or "insert _Nullable" warnings in CLion, and this makes the CLion buffer to be exhausted and useful information was harder to be seen. These annotations do make the code easier to understand, because people can derive the fact that a pointer can be nullable or not. Instead of manually fixing them by people who were affected, or completely disabling them, shall we make "make format-check" and CI format check to identify this issue? 
![Screen Shot 2022-12-21 at 8 23 48 PM](https://user-images.githubusercontent.com/33299678/209055428-293ff0e6-c4ed-4481-a4c3-9ec1c127ae3b.png)

**Comment by yingsu00** [comment]
cc @kgpai @Yuhta @pedroerp

**Comment by Yuhta** [comment]
There was a discussion among @mbasmanova @pedroerp and me that we decided to remove the nullability check.  The immediate cause is that we could not make the compiler happy with something like `U<T*>` where `U` is conditionally a no-op in some cases.  The root cause is that we discovered it did not help us prevent more bugs than the trouble it causes.

**Comment by drin** [comment]
I am building on macosx and came across these excessive notes/warnings as well. Just wanted to note here, for anyone else, that `-DENABLE_ALL_WARNINGS=1` should be added as a cmake option.

Found an example in the [workflow for macos][build-macos]. After figuring out what to search for from the root [CMakeLists.txt][build-cmake] cmake definition.


[build-macos]: https://github.com/facebookincubator/velox/blob/main/.github/workflows/macos.yml#L87
[build-cmake]: https://github.com/facebookincubator/velox/blob/main/CMakeLists.txt#L335-L340

**Comment by mbasmanova** [comment]
CC: @assignUser @kgpai @majetideepak Jacob, Deepak, can one of you help look into this?

**Comment by majetideepak** [comment]
@mbasmanova, There is an issue tracking improving warnings here https://github.com/facebookincubator/velox/issues/7389

**Comment by mbasmanova** [comment]
@drin Let's continue the discussion in https://github.com/facebookincubator/velox/issues/7389
