### ISSUE TITLE
Fail to build with with compilation error on Folly

### ISSUE THREAD

**Issue by viirya** [facebookincubator/velox#360]
I tried to build this on Mac OS, but saw the error as follows:

```
/usr/local/include/folly/Conv.h:744:41: error: no matching function for call to 'estimateSpaceNeeded'
  return estimateSpaceToReserve(sofar + estimateSpaceNeeded(v), vs...);                                                                                                                        
                                        ^~~~~~~~~~~~~~~~~~~
```

I looked at `Conv.h` quickly, there are some candidate templates. But based on the message of compiler, seems these templates are not suitable for `unsigned __int128` so the compiler cannot find a matching function of `estimateSpaceNeeded`.

**Comment by viirya** [comment]
This can be fixed by https://github.com/Homebrew/homebrew-core/pull/86451

**Comment by pedroerp** [comment]
I remember seeing this problem in Ubuntu as well, so I had to add this flag:

> https://github.com/facebookincubator/velox/blob/main/scripts/setup-ubuntu.sh#L73

does this help in your case as well (adding the flag to setup-macos.sh)?

**Comment by viirya** [comment]
Yes, I added the flag to homebrew folly Formula to fix it.
