### ISSUE TITLE
Parquet and S3 support

### ISSUE THREAD

**Issue by sunchao** [facebookincubator/velox#362]
The project README mentions that Parquet and S3 are supported, but I couldn't find any reference in the repo. Can someone provide more information on this?

**Comment by majetideepak** [comment]
@sunchao The README is slightly ahead of time :). S3 and Parquet support should land soon. See https://github.com/facebookincubator/velox/issues/211 for S3 support updates.

**Comment by sunchao** [comment]
@majetideepak thanks! looking forward to these features!

**Comment by majetideepak** [comment]
@sunchao, S3, and Parquet support are now available.
