### ISSUE TITLE
INVALID_ARGUMENT thrown by subscript during simplified path execution mode

### ISSUE THREAD

**Issue by bikramSingh91** [facebookincubator/velox#3625]
### Description

INVALID_ARGUMENT thrown by subscript during simplified path execution mode.

### Error Reproduction

[velox_expressionVerifier_kt4TFY.zip](https://github.com/facebookincubator/velox/files/10339958/velox_expressionVerifier_kt4TFY.zip)

### Relevant logs

```bash
I0103 20:02:23.647855 152733 ExpressionFuzzer.cpp:798] ==============================> Started iteration 2615 (seed: 1094499939)
I0103 20:02:23.653506 152733 ExpressionVerifier.cpp:80] Executing expression: array_position(10 elements starting at 0 {2009-12-12T09:31:54.894841300, 1995-06-02T13:30:43.913646693, 1987-11-24T15:15:05.236538757, null, 1971-01-11T15:43:18.577269835, ...},"c0",bitwise_left_shift(divide("c1",subscript(slice(array_constructor(abs(subscript(null,subscript("c2",1178731994)))),"c3",8565660703275138108),bitwise_right_shift_arithmetic("c4",105514524058872182))),mod(array_min(slice(array_constructor(round(94),subscript(map_values(1 elements starting at 100 {1204953800 => 124}),bitwise_not(subscript(map_concat(null,"c5",10 elements starting at 20 {6383568212542281926 => [20->37] [37->28] null, 4011788701907749929 => [21->144] [144->111] 61, 7159472352823304865 => [22->35] [35->103] 64, 2748324217157614835 => [23->97] [97->7] 50, 8916038657026389917 => [24->48] [48->111] 61, ...},10 elements starting at 640 {3652459724368932121 => 29, 5378650609570921515 => 29, 2939101558656983556 => 29, 3765034347288938825 => 29, 8009557573431640803 => 29, ...},"c6","c7",10 elements starting at 500 {6100305555218967284 => [500->778] [778->268] [268->617] 47, 7695999056154443245 => [501->733] [733->519] [519->180] 47, 1265726444055991992 => [502->363] [363->476] [476->628] 47, 674635885269288971 => [503->407] [407->280] null, 4506588249774667931 => [504->163] [163->34] [34->589] 47, ...}),3297020222291298957))),array_max(array_distinct("c8"))),bitwise_xor(mod(subscript(array_except("c8",slice("c8",147037367031698285,1543488174578509901)),array_position(10 elements starting at 120 {[120->102] 6839039105762476639, [121->114] 3828167836485361845, [122->94] 8227698100252441841, [123->40] 3903097607573319806, [124->88] 3128394680040015408, ...},833651070002152173,array_position(10 elements starting at 70 {[70->156] [156->89] 3055566645710933014, [71->94] [94->105] 7841272746418322431, [72->94] [94->105] 7841272746418322431, null, [74->157] null, ...},4418456305701289008,"c3"))),abs(round(round(108,"c9"),ceiling("c9")))),round(108,"c9")),2792615629279082903)),round(108,"c9"))))
I0103 20:02:23.653666 152733 ExpressionVerifier.cpp:32] 10 vectors as input:
I0103 20:02:23.653676 152733 ExpressionVerifier.cpp:34] 	[CONSTANT TIMESTAMP: 100 elements, 2008-04-23T07:34:35.357243854]
I0103 20:02:23.653687 152733 ExpressionVerifier.cpp:34] 	[DICTIONARY TINYINT: 100 elements, 9 nulls], [CONSTANT TINYINT: 100 elements, 115]
I0103 20:02:23.653697 152733 ExpressionVerifier.cpp:34] 	[DICTIONARY ARRAY<INTEGER>: 100 elements, 9 nulls], [ARRAY ARRAY<INTEGER>: 100 elements, no nulls]
I0103 20:02:23.653705 152733 ExpressionVerifier.cpp:34] 	[DICTIONARY BIGINT: 100 elements, 11 nulls], [DICTIONARY BIGINT: 100 elements, 7 nulls], [CONSTANT BIGINT: 100 elements, 4553690030360127345]
I0103 20:02:23.653717 152733 ExpressionVerifier.cpp:34] 	[DICTIONARY BIGINT: 100 elements, 8 nulls], [FLAT BIGINT: 100 elements, 12 nulls]
I0103 20:02:23.653724 152733 ExpressionVerifier.cpp:34] 	[MAP MAP<BIGINT,TINYINT>: 100 elements, no nulls]
I0103 20:02:23.653731 152733 ExpressionVerifier.cpp:34] 	[CONSTANT MAP<BIGINT,TINYINT>: 100 elements, 10 elements starting at 10 {7058905778023661630 => null, 6750504155567541940 => [11->10] null, 1512267420787841446 => [12->0] null, 2041682673931326294 => [13->4] 125, 5676628656268200636 => [14->15] 40, ...}], [MAP MAP<BIGINT,TINYINT>: 2 elements, no nulls]
I0103 20:02:23.653753 152733 ExpressionVerifier.cpp:34] 	[DICTIONARY MAP<BIGINT,TINYINT>: 100 elements, 13 nulls], [MAP MAP<BIGINT,TINYINT>: 100 elements, no nulls]
I0103 20:02:23.653760 152733 ExpressionVerifier.cpp:34] 	[DICTIONARY ARRAY<TINYINT>: 100 elements, 15 nulls], [ARRAY ARRAY<TINYINT>: 100 elements, no nulls]
I0103 20:02:23.653769 152733 ExpressionVerifier.cpp:34] 	[DICTIONARY INTEGER: 100 elements, 8 nulls], [DICTIONARY INTEGER: 100 elements, 12 nulls], [DICTIONARY INTEGER: 100 elements, 9 nulls], [CONSTANT INTEGER: 100 elements, 1293189257]
I0103 20:02:23.658988 152733 ExpressionVerifier.cpp:133] Modified inputs for common eval path: 
I0103 20:02:23.659003 152733 ExpressionVerifier.cpp:32] 10 vectors as input:
I0103 20:02:23.659006 152733 ExpressionVerifier.cpp:34] 	[LAZY TIMESTAMP: 100 elements, no nulls]
I0103 20:02:23.659015 152733 ExpressionVerifier.cpp:34] 	[DICTIONARY TINYINT: 100 elements, 9 nulls], [CONSTANT TINYINT: 100 elements, 115]
I0103 20:02:23.659026 152733 ExpressionVerifier.cpp:34] 	[DICTIONARY ARRAY<INTEGER>: 100 elements, 9 nulls], [ARRAY ARRAY<INTEGER>: 100 elements, no nulls]
I0103 20:02:23.659035 152733 ExpressionVerifier.cpp:34] 	[DICTIONARY BIGINT: 100 elements, 11 nulls], [DICTIONARY BIGINT: 100 elements, 7 nulls], [CONSTANT BIGINT: 100 elements, 4553690030360127345]
I0103 20:02:23.659047 152733 ExpressionVerifier.cpp:34] 	[DICTIONARY BIGINT: 100 elements, 8 nulls], [FLAT BIGINT: 100 elements, 12 nulls]
I0103 20:02:23.659055 152733 ExpressionVerifier.cpp:34] 	[MAP MAP<BIGINT,TINYINT>: 100 elements, no nulls]
I0103 20:02:23.659062 152733 ExpressionVerifier.cpp:34] 	[CONSTANT MAP<BIGINT,TINYINT>: 100 elements, 10 elements starting at 10 {7058905778023661630 => null, 6750504155567541940 => [11->10] null, 1512267420787841446 => [12->0] null, 2041682673931326294 => [13->4] 125, 5676628656268200636 => [14->15] 40, ...}], [MAP MAP<BIGINT,TINYINT>: 2 elements, no nulls]
I0103 20:02:23.659087 152733 ExpressionVerifier.cpp:34] 	[DICTIONARY MAP<BIGINT,TINYINT>: 100 elements, 13 nulls], [MAP MAP<BIGINT,TINYINT>: 100 elements, no nulls]
I0103 20:02:23.659096 152733 ExpressionVerifier.cpp:34] 	[DICTIONARY ARRAY<TINYINT>: 100 elements, 15 nulls], [ARRAY ARRAY<TINYINT>: 100 elements, no nulls]
I0103 20:02:23.659104 152733 ExpressionVerifier.cpp:34] 	[DICTIONARY INTEGER: 100 elements, 8 nulls], [DICTIONARY INTEGER: 100 elements, 12 nulls], [DICTIONARY INTEGER: 100 elements, 9 nulls], [CONSTANT INTEGER: 100 elements, 1293189257]
E0103 20:02:23.662540 152733 Exceptions.h:68] Line: ../.././velox/functions/lib/SubscriptUtil.h:227, Function:adjustIndex, Expression:  SQL array indices start at 1, Source: USER, ErrorCode: INVALID_ARGUMENT
E0103 20:02:23.662698 152733 FuzzerToolkit.cpp:131] Only simplified path threw exception:
I0103 20:02:23.663442 152733 ExpressionVerifier.cpp:295] Persisted input: --fuzzer_repro_path /tmp/fuzzer_repro/velox_expressionVerifier_kt4TFY --input_path /tmp/fuzzer_repro/velox_expressionVerifier_kt4TFY/input_vector --result_path /tmp/fuzzer_repro/velox_expressionVerifier_kt4TFY/result_vector --sql_path /tmp/fuzzer_repro/velox_expressionVerifier_kt4TFY/sql --lazy_column_list_path /tmp/fuzzer_repro/velox_expressionVerifier_kt4TFY/indices_of_lazy_columns --complex_constant_path /tmp/fuzzer_repro/velox_expressionVerifier_kt4TFY/complex_constants
terminate called after throwing an instance of 'facebook::velox::VeloxUserError'
  what():  Exception: VeloxUserError
Error Source: USER
Error Code: INVALID_ARGUMENT
Reason: SQL array indices start at 1
Retriable: False
Function: adjustIndex
File: ../.././velox/functions/lib/SubscriptUtil.h
Line: 227
Stack trace:
Stack trace has been disabled.Use --velox_exception_user_stacktrace=true to enable it.
```

**Comment by mbasmanova** [comment]
I wonder if this is due to simplified path not doing constant folding. In this case that would be a bug in the Fuzzer itself, not a problem in subscript function.

**Comment by bikramSingh91** [comment]
Root cause: The issue here is that #3284 added a behavior change to subscript operator that if an array is empty then any subscript access (regardless of value) returns NULL. This happens because the code returns a null vector as soon as it confirms that the underlying values vector is of size zero which skips the checks for valid index values. However, it does not check the individual sizes of each array in the array vector. Therefore, if the underlying values vector is not a zero size vector but each individual array size is zero it would continue and encounter the part that checks for valid index values and eventually throw.

This is what happened in this issue, that the simplified path returned an arrayVector with non-empty values vector whereas the common path returned one with an empty values vector.

I then tried out this behavior in Presto and noticed that an error is always returned if the index is invalid, even if the input array is empty. So ideally, this should be the expected behavior and the fix here should be to ensure both common and simplified paths throw these user errors.

However, I noticed that another change #3509 further fortified the behavior (contrary to Presto's behavior) introduced in #3284 . Therefore, before I went ahead and made the change to conform with Presto, I wanted to confirm with others in the community.

cc @mbasmanova @kagamiori @kevinwilfong

**Comment by mbasmanova** [comment]
@bikramSingh91 Bikram, thank you for investigating. We need to make sure the behavior matches Presto.

**Comment by kagamiori** [comment]
> Root cause: The issue here is that #3284 added a behavior change to subscript operator that if an array is empty then any subscript access (regardless of value) returns NULL. This happens because the code returns a null vector as soon as it confirms that the underlying values vector is of size zero which skips the checks for valid index values. However, it does not check the individual sizes of each array in the array vector. Therefore, if the underlying values vector is not a zero size vector but each individual array size is zero it would continue and encounter the part that checks for valid index values and eventually throw.
> 
> This is what happened in this issue, that the simplified path returned an arrayVector with non-empty values vector whereas the common path returned one with an empty values vector.
> 
> I then tried out this behavior in Presto and noticed that an error is always returned if the index is invalid, even if the input array is empty. So ideally, this should be the expected behavior and the fix here should be to ensure both common and simplified paths throw these user errors.
> 
> However, I noticed that another change #3509 further fortified the behavior (contrary to Presto's behavior) introduced in #3284 . Therefore, before I went ahead and made the change to conform with Presto, I wanted to confirm with others in the community.
> 
> cc @mbasmanova @kagamiori @kevinwilfong

Hi @bikramSingh91, Thank you for looking into this issue. I'm trying to understand which part of #3284 is different from Presto. I did checked the query "select element_at(array[], 1)" in Presto and it returns NULL. So if the underlying element vector is empty, then we should return a NULL vector. Did I miss anything?

**Comment by mbasmanova** [comment]
@kagamiori Wei, it could be the difference between element_at and [] operator:

```
presto> select array[][5];
Query 20230105_010832_05294_ae7g6 failed: Array subscript out of bounds

presto> select element_at(array[], 5);
 _col0
-------
 NULL
(1 row)
```

**Comment by bikramSingh91** [comment]
looks like out of bounds and invalid index (value of 0) gets handled a bit differently in element_at and subscript.

Both throw error for an invalid index of 0:

select element_at(myarray,0) from (SELECT ARRAY[] as myarray) a;
select myarray[0] from (SELECT ARRAY[] as myarray) a;

error:
(INVALID_FUNCTION_ARGUMENT) SQL array indices start at 1

Whereas for an index > 0 but out of bounds, element_at returns null but the subscript returns an error

**Comment by kagamiori** [comment]
> > @kagamiori Wei, it could be the difference between element_at and [] operator:
> > ```
> > presto> select array[][5];
> > Query 20230105_010832_05294_ae7g6 failed: Array subscript out of bounds
> > 
> > presto> select element_at(array[], 5);
> >  _col0
> > -------
> >  NULL
> > (1 row)
> > ```
> 
> Is this "[]" operator the "subscript" function in Velox? We implement both subscript and element_at using the same class template "SubscriptImpl". If they behave differently, then we need to add a parameter to control that.

OK, I think it's the "allowOutOfBound" parameter of SubscriptImpl that should control this behavior.

**Comment by bikramSingh91** [comment]
@kagamiori Just confirmed via a quick unit test that after my fix for this issue, for an out of bounds index, the element_at returns null but subscript throws error. So it will conform with Presto in that regard and we should be good.

**Comment by kagamiori** [comment]
> @kagamiori Just confirmed via a quick unit test that after my fix for this issue, for an out of bounds index, the element_at returns null but subscript throws error. So it will conform with Presto in that regard and we should be good.

Are you going to send the fix? I can help review it then.

**Comment by bikramSingh91** [comment]
> > @kagamiori Just confirmed via a quick unit test that after my fix for this issue, for an out of bounds index, the element_at returns null but subscript throws error. So it will conform with Presto in that regard and we should be good.
> 
> Are you going to send the fix? I can help review it then.

Yes, just wrapping up writing unit tests, should push a PR soon. Thanks for volunteering to review!

**Comment by kagamiori** [comment]
Looks like there is no E2E test for this corner case of subscript() in Prestissimo. We should add it after we fix this divergence. 
https://github.com/prestodb/presto/blob/a1a9299e054173ed380e1e6704310ff9c9b8e0a0/presto-native-execution/src/test/java/com/facebook/presto/nativeworker/TestHiveQueries.java#L528-L533
