### ISSUE TITLE
Code cleanup for existing UDF functions

### ISSUE THREAD

**Issue by darrenfu** [facebookincubator/velox#3639]
List a few code cleanup items among the existing UDF functions:

## Remove redundant udf argument validations

There are a few existing UDFs redundantly validating the arguments, which are already validated inside the `apply()` function. We should do some code cleaning.
E.g.
https://github.com/facebookincubator/velox/blob/e0b12a1989385fd1b4c1c9db42a651e2f1e01a78/velox/functions/prestosql/ArraySort.cpp#L253
https://github.com/facebookincubator/velox/blob/e0b12a1989385fd1b4c1c9db42a651e2f1e01a78/velox/functions/prestosql/ArrayDistinct.cpp#L172
https://github.com/facebookincubator/velox/blob/e0b12a1989385fd1b4c1c9db42a651e2f1e01a78/velox/functions/prestosql/ArrayDuplicates.cpp#L186

See @mbasmanova 's comment: https://github.com/facebookincubator/velox/pull/3404#discussion_r1061094323

## Do not pass nullCount when construct an ArrayVector

This `nullCount` property is not maintained properly and should not be used. We should not pass nullCount to the constructor.

**Suggested fix**: do not pass any value. Use the ctor default value, `std::nullopt`.

Example:
https://github.com/facebookincubator/velox/blob/e0b12a1989385fd1b4c1c9db42a651e2f1e01a78/velox/functions/prestosql/ArraySort.cpp#L225-L225

**Comment by vj-codes** [comment]
@darrenfu hey can you assign this to me please? Thanks!
