### ISSUE TITLE
Master Issue: Enable try support in Fuzzer

### ISSUE THREAD

**Issue by kgpai** [facebookincubator/velox#3645]
### Description

Running fuzzer with -retry_with_try brings up a bunch of new fuzzer bugs. This issue will detail all of these bugs.

**Comment by kgpai** [comment]
### 2. Regexp functions do not handle Try correctly. 

Functions : "regexp_replace",
      "re2_extract_all",
      "re2_extract",
      "re2_search",
      "re2_match",
      "like" 
do not handle Try correctly and thus fail Try fuzzer.

**Comment by kgpai** [comment]
### 3. Common and Simple eval dont match when executing expression `distinct_from(276619011,clamp(codepoint("c0"),round(null),floor(807223209)))` 

Input: [DICTIONARY VARCHAR: 100 elements, 9 nulls], [CONSTANT VARCHAR: 100 elements, {sKT-dKablwem]q.wWEn4$W)Rh?h&lWxNA<fW"q_'c@;_\S4]V;=-f|>3/m)(i}v0n]

Stack Trace: 
```
 E20230104 15:09:01.423604 8106041 Exceptions.h:68] Line: /Users/kpai/src/Velox/velox/expression/tests/ExpressionVerifier.cpp:67, Function:compareVectors, Expression: left->equalValueAt(right.get(), i, i) Different results at idx '17': 'null' vs. '1', Source: RUNTIME, ErrorCode: INVALID_STATE
libc++abi: terminating with uncaught exception of type facebook::velox::VeloxRuntimeError: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Different results at idx '17': 'null' vs. '1'
Retriable: False
Expression: left->equalValueAt(right.get(), i, i)
Function: compareVectors
File: /Users/kpai/src/Velox/velox/expression/tests/ExpressionVerifier.cpp
Line: 67
Stack trace:
# 0  .. 
``` 

I will have PR for this soon.

**Comment by kgpai** [comment]
### 4. Infinite loop in date_parse . 

With skipFunctions: "regexp_replace",
      "re2_extract_all",
      "re2_extract",
      "re2_search",
      "re2_match",
      "like",
      "regexp_extract",

And running fuzzer as : `--seed 3279418538 --duration_sec 3600 --logtostderr=1 --minloglevel=0 --retry_with_try`

**Comment by mbasmanova** [comment]
@kgpai Krishna, do we have separate fuzzer-found issues for regex and date_parse functions? If not, let's create these.

**Comment by kgpai** [comment]
Try support has been added and has been stable in fuzzer for somewhile so closing this issue.
