### ISSUE TITLE
use simdjson to enhance the performance of json parsing

### ISSUE THREAD

**Issue by wanweiqiangintel** [facebookincubator/velox#3658]
### Description

simdjson is a very popular json processing library that uses SIMD instructions. In our initial test, using simdjson to implement the jsonExtract function in (velox/functions/prestosql/json/JsonExtractor.cpp) can get about 50X+ speedup while using twitter.json. So can we try to integrate simdjson into Velox to enhance the json processing performance?

**Comment by mbasmanova** [comment]
CC: @kagamiori @Yuhta @oerling 

@wanweiqiangintel Would you like to send out a PR?

**Comment by wanweiqiangintel** [comment]
> 
Sure, I will wrap up the code and submit the PR as soon as possible.

**Comment by mbasmanova** [comment]
@wanweiqiangintel Looking forward to faster json parsing. Please, check out https://github.com/facebookincubator/velox/blob/main/CONTRIBUTING.md and https://github.com/facebookincubator/velox/blob/main/CODING_STYLE.md to familiarize yourself with the coding style and contributing guidelines.

**Comment by mbasmanova** [comment]
This is done now. 

@wanweiqiangintel We found some gaps in simdjson wrt to parsing invalid JSON. Would you take a look at https://github.com/facebookincubator/velox/discussions/6597
