### ISSUE TITLE
Run S3FileSystemTest on mac m1 but report the error "Failed to get metadata for S3 object due to: 'Resource not found'. Path:'s3://data/test.txt'"

### ISSUE THREAD

**Issue by Dream-hu** [facebookincubator/velox#3733]
### Bug description

I brew install the minio and run the S3FileSystemTest on my laptop（mac m1）such as  its writeAndRead UT

[Expected behavior]
 tests all pass

[actual behavior]
S3fs write data successfully, but report an error when initialized the S3ReadFile before reading.
 

### System information

Velox System Info v0.0.2
Commit: a2d28762b7ccd9a5aea7051c2ae28c2c824bb124
CMake Version: 3.24.2
System: Darwin-21.4.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 13.1.6.13160021
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 13.1.6.13160021
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.24.2;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local
  

### Relevant logs

```bash
E20230117 19:58:18.428419 7179733 Exceptions.h:68] Line: presto/presto-native-execution/velox/velox/connectors/hive/storage_adapters/s3fs/S3FileSystem.cpp:83, Function:initialize, Expression:  Failed to get metadata for S3 object due to: 'Resource not found'. Path:'s3://data/test.txt', SDK Error Type:16, HTTP Status Code:404, S3 Service:'MinIO', Message:'No response body.', Source: RUNTIME, ErrorCode: INVALID_STATE
```

**Comment by majetideepak** [comment]
@Dream-hu The tests write via the local file system. There is no S3 write support yet.
The circle CI tests S3 Read using Minio and there are no CI failures. Since your server is Minio as well, the issue must be local to your system.
Can you verify the path?
