### ISSUE TITLE
MemoryPoolImpl::getCurrentBytes() returns incorrect value

### ISSUE THREAD

**Issue by waitinfuture** [facebookincubator/velox#3750]
### Bug description

getCurrentBytes() is supposed to return the aggregated sum of the whole tree, but in fact it merely adds up localMemoryUsage_.getCurrentBytes() with subtreeMemoryUsage_.getCurrentBytes(), because accessSubtreeMemoryUsage just visits subtreeMemoryUsage_.

For example, when I run the following test, it fails
```
TEST_F(BufferTest, testNonPODMemoryUsage) {
  using T = std::shared_ptr<void>;
  auto child = pool_->addChild("child");
  auto buffer = AlignedBuffer::allocate<T>(8, child.get());
  EXPECT_GT(pool_->getCurrentBytes(), 0);
}
```

```
Running main() from /Users/yichui/workspace/emr/velox/third_party/googletest/googletest/src/gtest_main.cc
/Users/yichui/workspace/emr/velox/velox/buffer/tests/BufferTest.cpp:336: Failure
Expected: (pool_->getCurrentBytes()) > (0), actual: 0 vs 0
```

### System information

Velox System Info v0.0.2
Commit: 66ff2ac4a6505adef59ea90a43a6a71cf9e3b564
CMake Version: 3.24.1
System: Darwin-20.6.0
Arch: x86_64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 13.0.0.13000029
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 13.0.0.13000029
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/usr;/usr/local;/usr;/;/usr/local/Cellar/cmake/3.24.1;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local
  

### Relevant logs
Running main() from /Users/yichui/workspace/emr/velox/third_party/googletest/googletest/src/gtest_main.cc
/Users/yichui/workspace/emr/velox/velox/buffer/tests/BufferTest.cpp:336: Failure
Expected: (pool_->getCurrentBytes()) > (0), actual: 0 vs 0

_No response_

**Comment by waitinfuture** [comment]
Hi @mbasmanova @xiaoxmeng , please verify if this is a bug. If so, I'd like to try to fix, thanks!

**Comment by xiaoxmeng** [comment]
@waitinfuture we will deprecate the memory usage counting in memory pool soon and replace with the ones in memory tracker. But it seems to be wrong in the current logic to calculate the aggregated memory usage and visitor should aggregate the memory usage from its child pools instead of subtree usage. cc @HuamengJiang is deprecating this logic.

**Comment by waitinfuture** [comment]
> 

OK, I'm closing this issue.
