### ISSUE TITLE
Another issue with Folly: Cannot found folly library from rpath

### ISSUE THREAD

**Issue by viirya** [facebookincubator/velox#376]
After fixing #360 by adding `FOLLY_HAVE_INT128_T` (I used homebrew, not the `setup-macos.sh`), I had another Folly issue as follows.

```
ld: file not found: @rpath/libfolly.0.58.0-dev.dylib for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [velox/common/base/benchmarks/velox_common_base_benchmarks] Error 1
make[3]: *** [velox/common/base/benchmarks/CMakeFiles/velox_common_base_benchmarks.dir/all] Error 2
make[3]: *** Waiting for unfinished jobs....
```

It looks weird because ` /usr/local/lib/libfollybenchmark.dylib` and `libfolly_test_util.dylib` both load libfolly.0.58.0-dev.dylib from `@rpath/libfolly.0.58.0-dev.dylib`, but they don't specify RPATH?

Anyway, it is a bit hacky, but I manually added rpath by doing:

```
sudo install_name_tool -add_rpath /usr/local/lib  /usr/local/lib/libfollybenchmark.dylib
```

After that, I can successfully build Velox locally on Mac OS. Maybe this can be resolved from Folly side? I'm not sure. Hopefully this can be useful for others encountering the same issue.

**Comment by mbasmanova** [comment]
CC: @funrollloops @syotfs @pedroerp
