### ISSUE TITLE
findMappedFreeGroup should use step-length of kWidth instead of one

### ISSUE THREAD

**Issue by waitinfuture** [facebookincubator/velox#3888]
### Description

The loop in MmapAllocator::SizeClass::findMappedFreeGroup loads and checks kWidth elements of mappedFreeLookup_ each iteration, and since lookupSize equals size of mappedFreeLookup_ plus kSimdTail, we should increment counter by kWidth instead of one each iteration.

cc @mbasmanova @oerling

**Comment by mbasmanova** [comment]
CC: @xiaoxmeng
