### ISSUE TITLE
Nightly doc-gen job is failing: SyntaxError: future feature annotations is not defined

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#3928]
### Bug description

CC: @zhejiangxiaomai 

https://app.circleci.com/pipelines/github/facebookincubator/velox/19730/workflows/7fffc2df-0393-4543-9788-e6abec45ff2b/jobs/124340

```
Exception occurred:
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/root/project/velox/docs/ext/spark.py", line 17
    from __future__ import annotations
                                     ^
SyntaxError: future feature annotations is not defined
```

### System information

n/a

**Comment by mbasmanova** [comment]
CC: @majetideepak @kgpai

**Comment by zhejiangxiaomai** [comment]
I'm fixing it.

**Comment by zhejiangxiaomai** [comment]
I can not reproduce this issue on my server because my python version is 3.9.12.
And I found solutions is that it require python>=3.7 version.
https://github.com/csuhan/ReDet/issues/14#issuecomment-814827012

**Comment by kgpai** [comment]
Hi @zhejiangxiaomai , The docs are generated on ghcr.io/facebookincubator/velox-dev:circleci-avx image which you can pull for yourself and see what version of python is supported etc (I think it should have python 3 above). You can probably fix the makefile to ensure right version of python is invoked for sphinx.

**Comment by mbasmanova** [comment]
@kgpai Krishna, thank you for the suggestions on how to fix this.

@zhejiangxiaomai Can you try this?

**Comment by zhejiangxiaomai** [comment]
- Can you try this?
Yes, I've taken down the centos8(ghcr.io/facebookincubator/velox-dev:circleci-avx) image, try to reproduce it.
