### ISSUE TITLE
Enable or delete SumTest::DISABLED_decimalAggregateOverflow

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#3931]
### Bug description

SumTest::decimalAggregateOverflow is disabled. Let's fix it or remove if it is not needed.

```
TEST_F(SumTest, DISABLED_decimalAggregateOverflow) {
```

CC: @majetideepak @karteekmurthys @aditi-pandit @pramodsatya 

### System information

n/a

**Comment by majetideepak** [comment]
@mbasmanova I will resolve this. Thanks!
