### ISSUE TITLE
Improvements to the Velox S3 connector. 

### ISSUE THREAD

**Issue by akashsha1** [facebookincubator/velox#3938]
### Description

Problem: The performance of S3 on Velox is reliant on the S3 connector, which is single threaded. Threading in velox is handled at a higher layer (i.e. table scan layer).

Current Design:
The current design of Velox implements threading at the Table Scan operator layer. This is a layer that is executed by multiple drivers (threads). Each scan operator/thread handles a file split i.e., read a portion of a file. A Rowreader instance, which is part of the connector starts processing a file split. The row reader can prefetch data, coalesce reads where it helps and leverage the in-memory/SSD cache of Velox. 

S3 file system, and HDFS (Hadoop Distributed File System) are two storage adapters which implement the Hive connector. 
S3 read is implemented in preadv* method and uses GetObjectRequest API from the AWS C++ SDK. In addition, there is also the use of buffers which contain Ranges with some gaps in between. The GetObject does not support multi-range reads. The idea is to use a single read, which spans all the ranges and populate the individual ranges and use a pre-allocated buffer to support this.
 
Proposal: 
The proposal is to modify:
1.	Replace the GetObject API call used by the AWS S3 SDK and use TransferManager semantics in its place. This change would be contained within the S3 portion mainly. The transfer manager provides built-in multi-threading with thread interleaving, and uses async calls with callbacks to track progress of transfers. This can be used to populate read ranges to pre-allocated buffers more efficiently. 
2.	Introducing the TransferManager, which is a more advanced API offered by AWS C++ SDK, will add several capabilities such as:
-	Calling “DownloadFile” asynchronously and using a TransferHandle to manage the status of the request. 
-	Use callback capabilities to track transfer progress.
In addition, expose AWS client object’s ‘maxConnections’ to the user or an ability to automatically calculate it via core counts on the instance. This will allow more HTTP connections to an AWS endpoint (S3). Default is 25.
3.	With the modifications to the TransferManager, we can tune the coalesce and row group configurations properties defined in CachedBufferedInput.cpp and ParquetReader.cpp.
While the additional parallelism provided by the TransferManager is nice, it is important to tune coalescing accordingly for optimal configuration. 

The intent is to provide better performance, and testing this using tpc-h queries would validate the design. 

Based on experiments done using AWS C++ SDK, a benchmark app written based on the Velox S3 connector and S3 object store, we have observed the following speeds:
-	AWS C++ SDK (multi-threaded with 25threads): 3 Gbps (it’s possible to go even higher)
-	AWS C++/Python SDK (single threaded): 1 Gbps 
-	AWS CLI: 46 Mb/s
-	Benchmark tool using the current velox S3 connector: 25 Mb/s

Benchmarking tool: 
The benchmarking tool is in a fork of the Velox GitHub repo7 and was designed as a single threaded tool to test throughput of the S3 connector at its interface level. It is very simple and produces a small CSV output for each run.
https://github.com/paul-amonson/velox/tree/benchmarking/velox/connectors/hive/storage_adapters/s3fs/benchmark2

**Comment by Yohahaha** [comment]
> With the modifications to the TransferManager, we can tune the coalesce and row group configurations properties defined in CachedBufferedInput.cpp and ParquetReader.cpp.
While the additional parallelism provided by the TransferManager is nice, it is important to tune coalescing accordingly for optimal configuration.

Hi, I'm confused how do you tune the coalesce and row group configurations properties. In `ParquetReader.cpp`, each thread splits needed RowGroup into `BufferedInput`s, then enqueue ColumnChunk region and load synchronous.
So, how do you improve parallelism?

**Comment by majetideepak** [comment]
The benchmark app reads a whole file in one call and does not reflect the practical read pattern.
The other S3ReadBenchmark `s3fs/benchmark` has a practical read pattern with `gap`, `num_threads` parameters that can be tuned to control the coalescing, and parallelism. 
Please benchmark using this to see if TransferManager improves the performance.
My hunch is that you will see reduced benefits since the reads are usually small (at most 1MB chunk size) and the Transfer Manager might induce more overhead.
The performance will also depend on how much is being enqueued, and coalesced.

**Comment by akashsha1** [comment]
> 



> ch is that you will see reduced benefits since the reads in practice are usually small (at most 1MB chunk size) and the Transfer Manager might induce more overhead.
> The performance will also depend on how much is being enqueued, and coalesced.

The suggestion here is to enqueue more Parquet row groups to be scheduled to start. So there will be more reads starting at the same time. 
For coalescing, there were 2 possiblities to tune: maxCoalesceDistance which can help coalesce reads that are not more than so far apart, and max size of a coalesced chunk which can be varied to coalesce fewer times.

**Comment by akashsha1** [comment]
> > With the modifications to the TransferManager, we can tune the coalesce and row group configurations properties defined in CachedBufferedInput.cpp and ParquetReader.cpp.
> > While the additional parallelism provided by the TransferManager is nice, it is important to tune coalescing accordingly for optimal configuration.
> 
> Hi, I'm confused how do you tune the coalesce and row group configurations properties. In `ParquetReader.cpp`, each thread splits needed RowGroup into `BufferedInput`s, then enqueue ColumnChunk region and load synchronous. So, how do you improve parallelism?

The suggestion here is to enqueue more Parquet row groups to be scheduled to start. So there will be more reads starting at the same time.
For coalescing, there were 2 possiblities to tune: maxCoalesceDistance which can help coalesce reads that are not more than so far apart, and max size of a coalesced chunk which can be varied to coalesce fewer times.

**Comment by akashsha1** [comment]
closing the issue - transfer manager did not provide optimal outcome in multiple scenarios, so we ended up documenting IO tuning recommendations with current implementation : https://facebookincubator.github.io/velox/develop/TpchBenchmark.html
