### ISSUE TITLE
[Spark functions] least and greatest only support scalar types but are also run with complex types

### ISSUE THREAD

**Issue by bikramSingh91** [facebookincubator/velox#3991]
### Description

least and greatest only support scalar types but the function signatures are registered with a templated type "T". Therefore, the fuzzer also generates complex types inputs for them. This is wasteful and caused noise in the logs where the thrown error is printed out repeatedly.

We should update the signature to be more strict and constrictive or add a mechanism in fuzzer to identify these kinds of functions and avoid generation of wrong types of inputs

### Error Reproduction

run the spark expression fuzzer with --velox_fuzzer_enable_complex_types --only="least,greatest"

### Relevant logs

```bash
Error Source: RUNTIME
Error Code: NOT_IMPLEMENTED
Reason: greatest does not support arguments of type MAP
Retriable: False
Function: makeImpl
File: /Users/bikramjeet/dev/velox/velox/functions/sparksql/LeastGreatest.cpp
Line: 127
```

**Comment by kgpai** [comment]
Currently this PR : https://github.com/facebookincubator/velox/pull/4013 breaks the spark fuzzer due to the above issue since , these are runtime and system errors and not user errors.
