### ISSUE TITLE
When make install after build, only Type.h is installed in centos

### ISSUE THREAD

**Issue by hsshsssh** [facebookincubator/velox#3999]
### Problem description

When make install after build, only Type.h is installed in centos.
I want to include and use the velox-built library in another project.  However, when installing after make, only Type.h is installed.
Root CmakeLists.Lists are below.
```
# TODO: Include all other installation files. For now just making sure this
# generates an installable makefile.
install(FILES velox/type/Type.h DESTINATION "include/velox")
```
Do I need to add anything to use the built velox library?

### System information

Velox System Info v0.0.2
Commit: 66ff2ac4a6505adef59ea90a43a6a71cf9e3b564
CMake Version: 3.22.1
System: Linux-3.10.0-862.el7.x86_64
Arch: x86_64
C++ Compiler: /opt/rh/devtoolset-11/root/usr/bin/c++
C++ Compiler Version: 11.2.1
C Compiler: /opt/rh/devtoolset-11/root/usr/bin/cc
C Compiler Version: 11.2.1
CMake Prefix Path: /usr/local;/usr;/;/home/root/cmake-3.22.1;/usr/local;/usr/X11R6;/usr/pkg;/op

### CMake log

```bash
.
```

**Comment by lingbin** [comment]
What I see is that currently, Velox is generally used as a git submodule, that is, it is compiled with your project instead of pre-compiled and installed.  Probably because Velox is still iterating rapidly, it is slightly more convenient for git submodules to keep in sync.
For specific usage example, you can refer to: https://github.com/prestodb/presto/tree/master/presto-native-execution

**Comment by assignUser** [comment]
Thanks for the report. It is as @lingbin says, this is currently known and intended behavior. But we are aware that it is not ideal for downstream users and an overhaul of the cmake and introduction of proper install and config capabilities is on (my) to-do list, it may take a bit until that is resolved though. I have created #4027 to track this.

**Comment by hsshsssh** [comment]
thank you It was helpful.
