### ISSUE TITLE
Spark case-sensitive option mode

### ISSUE THREAD

**Issue by jinchengchenghh** [facebookincubator/velox#4000]
### Description

Presto only supports case-sensitive mode, but spark has configuration `spark.sql.caseSensitive` with default value `false` which describes as `Whether the query analyzer should be case sensitive or not. Default to case insensitive. It is highly discouraged to turn on case sensitive mode.`

Can we support case-insensitive mode in velox?

As spark implementation, it will convert parquet read column name to lowercase and convert operator column name to lowercase.

Velox can add a new config named `case_sensitive` in `HiveConfig`, and set it in QueryContext, The default value will be true matches velox original logical. If set it to false, we will convert the column name to lowercase when converting parquet schema to velox schema `RowType`.
If user uses case-insensitive mode, user should use lower case column name to create` PlanNode`, or we can add a function to convert original `PlanNode` to case-insensitive `PlanNode`.

What do you think? @mbasmanova 

Kindly look forward to your reply!

**Comment by mbasmanova** [comment]
> As spark implementation, it will convert parquet read column name to lowercase and convert operator column name to lowercase.

Columns name in the plan are controlled outside of Velox, hence, no change in Velox is needed I think.

Re: Parquet reader - Can you clarify a bit more about the desired behavior? Do we need the reader to read column FOO as foo or something else?

**Comment by jinchengchenghh** [comment]
Yes, we need the reader to read column FOO or fOO as foo.

**Comment by mbasmanova** [comment]
@Yuhta Jimmy, do you know if Parquet reader can handle column names in a case insensitive ways already? If not, how hard would it be to change it?

**Comment by Yuhta** [comment]
It should be doable, this is not specific to parquet though.

1. We generate output type and filters using all lower case names in connector (if the planner can ensure this, we do not need to do this in Velox)
2. For the readers we add an option to return all column names as lower case
3. If 1 is needed in Velox, we change the column names in the result vector back to its original names in plan

**Comment by jinchengchenghh** [comment]
For the 2, I have one draft PR https://github.com/oap-project/velox/pull/126, now it is just for parquet reader, we can expand it to other readers.

**Comment by Yuhta** [comment]
@jinchengchenghh The idea looks good.  Some suggestions:
1. The option at reader level should be `readAsLowerCase` as that is the actual behavior.
2. We also need to convert all field names in subfield filters to lower case

**Comment by jinchengchenghh** [comment]
Thanks for your suggestion. I will create a PR to do as you say.
