### ISSUE TITLE
Improve TableScan read IO related metrics.

### ISSUE THREAD

**Issue by Yohahaha** [facebookincubator/velox#4018]
### Description

In TableScan operator, time consuming for read IO is important, it can reflect real read time consuming, including network latency and different implementation of `ReadFile`'s performance.

Velox could read data from HDFS\S3 by implementation of `ReadFile`, but lack of `rawReadTime` similar to `rawBytesRead_` in `IoStatistics.h`.  

In my case, I want figure out read consuming of HDFS, S3, OSS. Current implementation for this is too general, I found `dataSourceWallNanos` in `TableScan.cpp`
https://github.com/facebookincubator/velox/blob/fb33fbfec589547c1eda6ac1b9aa5dcb18f9c66f/velox/exec/TableScan.cpp#L153-L157 but its include reading and filtering, and I also found `latencyInMs` in `IoStatistics.h` and `incOperationCounters` method, however, these variable and method are not invoked, please correct me if I am wrong.

I would appreciate it if anyone could tell me the correct usage to measure this metric. If this metrics has not implemented, I would like take this and implemented with `IoStatistics` and `ReadFileInputStream`.

**Comment by Yohahaha** [comment]
cc @Yuhta @oerling @mbasmanova

**Comment by mbasmanova** [comment]
@Yuhta Jimmy, would you help take a look?

CC: @majetideepak

**Comment by majetideepak** [comment]
+1 on this.  I see `std::unordered_map<std::string, OperationCounters> operationStats_;` and wonder what the intention for a Map is here
@oerling @Yuhta can you clarify?

**Comment by Yuhta** [comment]
@Yohahaha `IoStatistics:: incOperationCounters` is the function you are looking for; however it's expensive and should not be call in a generic `ReadFileInputStream::read`.  As a workaround, you can create a subclass of `ReadFileInputStream` and increase the counters there; There is a plan on our side to move the stats and log into `ReadFile` and remove the whole `InputStream` class tree though, so it is just a workaround, and will be broken later.

@majetideepak The map is for categorize the stats by different operations, e.g. "open", "write", etcs.

**Comment by Yuhta** [comment]
Actually, let me see if we can add stats and log in `ReadFile` early, so that you can add the metrics in a subclass of `ReadFile` instead.  That will be the long term solution.

**Comment by Yohahaha** [comment]
Thanks for reply!

I agree with your ideas of do not call `incOperationCounters` in a generic methods. However, I am not sure the workaround you mentioned is most suitable.

> There is a plan on our side to move the stats and log into ReadFile and remove the whole InputStream class tree though

LGTM.

Would you mind if I move the stats into `ReadFile` first or you have already started? @Yuhta

**Comment by Yohahaha** [comment]
To make minimal refactor, I introduced a new variable `totalScanTime_` in `IoStatistics.h`, and measure it with `rawBytesRead_` cause they have correlation.

This is enough for this issue currently I think, looking forward to receiving more suggestions on this.
