### ISSUE TITLE
MapVector::sortedKeys_ is not maintained properly

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#4116]
### Bug description

I found that MapVector::sortedKeys_ flag is not maintained properly when I investigated the error in https://github.com/facebookincubator/velox/issues/4114.

MapVector::sortedKeys_ indicates whether all rows in the map vector has their keys sorted in ascending order. This flag is used in MapZipWithFunction to skip sorting of keys. However, it doesn't always reflect the truth.
1. When a map vector is created, sortedKeys_ is set to false unless explicitly specified by the constructor caller. Callers that do not specify this flat include CastExpr, MapFilterFunction, MapValues, MapVector::slice().
2. CoalesceExpr and SwitchExpr compose a result vector with contents from multiple arguments. They do not update the sortedKeys_ flag, so the final result's sortedKeys_ flag would remain the same as the flag of the first argument or branch.

For (1), since MapVector constructor conservatively set sortedKeys_ to be false, it doesn't cause correctness issue. But (2) can possibly cause correctness issue when evaluating `map_zip_with(coalesce(sorted_key_map, non_sorted_key_map), ...)`.

One possible solution is to set the result vector's sortedKeys_ to true only if all arguments of CoalesceExpr or all branches of SwitchExpr have sortedKeys_ being true (or simply set the result sortedKeys_ to false for these two special forms). This would require a special handling of MapVector in these two special forms. 

### System information

Unit test to reproduce the issue:
```
TEST_F(ExprTest, mapIsSortedKeys) {
  auto map1 = makeNullableMapVector<int64_t, int64_t>(
      {{{{0, 0}, {1, 10}}}, {{{2, 20}, {3, 30}}}, std::nullopt});
  EXPECT_TRUE(map1->hasSortedKeys());

  auto map2 = makeNullableMapVector<int64_t, int64_t>(
      {std::nullopt, std::nullopt, {{{5, 50}, {4, 40}}}});
  auto keys =
      makeNullableArrayVector<int64_t>({{{0, 1}}, {{2, 3}}, std::nullopt});
  auto values =
      makeNullableArrayVector<int64_t>({{{0, 10}}, {{20, 30}}, std::nullopt});

  auto result = evaluate(
      "coalesce(map(c0, c1), c2)", makeRowVector({keys, values, map2}));
  auto resultMap = result->as<MapVector>();
  EXPECT_FALSE(resultMap->hasSortedKeys());
}
```

**Comment by Yuhta** [comment]
> Set the result vector's sortedKeys_ to true only if all arguments of CoalesceExpr or all branches of SwitchExpr have sortedKeys_ being true

I think this is a good way to go.

**Comment by kagamiori** [comment]
> > Set the result vector's sortedKeys_ to true only if all arguments of CoalesceExpr or all branches of SwitchExpr have sortedKeys_ being true
> 
> I think this is a good way to go.

Hi Jimmy, Thank you for sharing your idea! Looking into this problem deeper, Masha and I found that it doesn't limit to sortedKeys_ and CoalesceExpr only. I extend the discussion about this problem in https://github.com/facebookincubator/velox/discussions/4148.

**Comment by kagamiori** [comment]
Closing this issue since it has been fixed.
