### ISSUE TITLE
"getrandom" error when running TPC-H benchmark and TpchConnectorTest

### ISSUE THREAD

**Issue by EthanFu1996** [facebookincubator/velox#4128]
### Bug description

When I run the tpch benchmark, or run the TpchConnectorTest, it always fails due to a "getrandom" exception. I just can't figure it out. Could you help to glance on this? Thanks a lot!

[Expected behavior] Pass the tests or give the benchmark result without exception.

[Actual behavior] Here is the verbose log when running TpchConnectorTest:

171: Test command: /velox/_build/debug/velox/connectors/tpch/tests/velox_tpch_connector_test
171: Test timeout computed to be: 1500
171: [==========] Running 9 tests from 1 test suite.
171: [----------] Global test environment set-up.
171: [----------] 9 tests from TpchConnectorTest
171: [ RUN      ] TpchConnectorTest.simple
171: unknown file: Failure
171: C++ exception with description "getrandom" thrown in the test body.
171: [  FAILED  ] TpchConnectorTest.simple (24 ms)
171: [ RUN      ] TpchConnectorTest.singleColumn
171: unknown file: Failure
171: C++ exception with description "getrandom" thrown in the test body.
171: [  FAILED  ] TpchConnectorTest.singleColumn (19 ms)
171: [ RUN      ] TpchConnectorTest.singleColumnWithAlias
171: unknown file: Failure
171: C++ exception with description "getrandom" thrown in the test body.
171: [  FAILED  ] TpchConnectorTest.singleColumnWithAlias (44 ms)
171: [ RUN      ] TpchConnectorTest.simpleAggregation
171: E0224 16:38:11.751578 25487 Exceptions.h:68] Line: ../.././velox/connectors/tpch/TpchConnector.h:50, Function:TpchTableHandle, Expression: scaleFactor >= 0 (-1 vs. 0) Tpch scale factor must be non-negative, Source: RUNTIME, ErrorCode: INVALID_STATE
171: unknown file: Failure
171: C++ exception with description "getrandom" thrown in the test body.
171: [  FAILED  ] TpchConnectorTest.simpleAggregation (44 ms)
171: [ RUN      ] TpchConnectorTest.lineitemTinyRowCount
171: unknown file: Failure
171: C++ exception with description "getrandom" thrown in the test body.
171: [  FAILED  ] TpchConnectorTest.lineitemTinyRowCount (43 ms)
171: [ RUN      ] TpchConnectorTest.unknownColumn
171: E0224 16:38:11.839913 25487 Exceptions.h:68] Line: ../../velox/type/Type.cpp:355, Function:findChild, Expression:  Field not found: does_not_exist. Available fields are: n_nationkey, n_name, n_regionkey, n_comment., Source: USER, ErrorCode: INVALID_ARGUMENT
171: [       OK ] TpchConnectorTest.unknownColumn (42 ms)
171: [ RUN      ] TpchConnectorTest.multipleSplits
171: unknown file: Failure
171: C++ exception with description "getrandom" thrown in the test body.
171: [  FAILED  ] TpchConnectorTest.multipleSplits (42 ms)
171: [ RUN      ] TpchConnectorTest.join
171: unknown file: Failure
171: C++ exception with description "getrandom" thrown in the test body.
171: [  FAILED  ] TpchConnectorTest.join (42 ms)
171: [ RUN      ] TpchConnectorTest.orderDateCount
171: unknown file: Failure
171: C++ exception with description "getrandom" thrown in the test body.
171: [  FAILED  ] TpchConnectorTest.orderDateCount (33 ms)
171: [----------] 9 tests from TpchConnectorTest (338 ms total)
171:
171: [----------] Global test environment tear-down
171: [==========] 9 tests from 1 test suite ran. (360 ms total)
171: [  PASSED  ] 1 test.
171: [  FAILED  ] 8 tests, listed below:
171: [  FAILED  ] TpchConnectorTest.simple
171: [  FAILED  ] TpchConnectorTest.singleColumn
171: [  FAILED  ] TpchConnectorTest.singleColumnWithAlias
171: [  FAILED  ] TpchConnectorTest.simpleAggregation
171: [  FAILED  ] TpchConnectorTest.lineitemTinyRowCount
171: [  FAILED  ] TpchConnectorTest.multipleSplits
171: [  FAILED  ] TpchConnectorTest.join
171: [  FAILED  ] TpchConnectorTest.orderDateCount
171:
171:  8 FAILED TESTS
1/1 Test #171: velox_tpch_connector_test ........***Failed    0.39 sec

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.40 sec

The following tests FAILED:
	171 - velox_tpch_connector_test (Failed)
Errors while running CTest

### System information

Velox System Info v0.0.2
Commit: 9ff617d49afc8a50e2e8fd0d8eb6b4f1ec502b6f
CMake Version: 3.16.3
System: Linux-3.10.0-327.ali2010.alios7.x86_64
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by majetideepak** [comment]
@EthanFu1996 The Linux kernel version (3.10) does not support `getrandom`.
It was introduced in 3.17. See the documentation below.
https://man7.org/linux/man-pages/man2/getrandom.2.html
