### ISSUE TITLE
How to remove the error log?

### ISSUE THREAD

**Issue by jiangjiguang** [facebookincubator/velox#4161]
### Bug description

Hi, I am running prestissimo TPC-H, presto version 0.279 the prestissimo always print the error log, but the query result is correct.

I know the root cause is that "Unsupported call expression" in velox code.

But I am confused why presto 0.278 does not have the error log. How to I can do to remove the error log.

![image](https://user-images.githubusercontent.com/12368495/222039151-bf5dae28-07b0-4859-88ae-6c5917a52333.png)

### System information

ubuntu22

**Comment by mbasmanova** [comment]
@jiangjiguang Since the log messages comes from Prestissimo codebase, the fix would go there. I suggest you close this issue and open a new one in https://github.com/prestodb/presto/issues

BTW, make sure to include log messages as plain text and not as images. It is hard to work with images.

**Comment by mbasmanova** [comment]
CC: @amitkdutta @gggrace14 @spershin @zacw7

**Comment by mbasmanova** [comment]
CC: @majetideepak @aditi-pandit @pramodsatya

**Comment by jiangjiguang** [comment]
> @jiangjiguang Since the log messages comes from Prestissimo codebase, the fix would go there. I suggest you close this issue and open a new one in https://github.com/prestodb/presto/issues
> 
> BTW, make sure to include log messages as plain text and not as images. It is hard to work with images.

@mbasmanova Got it, thanks
