### ISSUE TITLE
SsdFile does not support larger entry which size over 8MB and throw exception

### ISSUE THREAD

**Issue by Yohahaha** [facebookincubator/velox#4164]
### How to reproduce:
When modify `SsdFileTest::writeAndRead` pins' size greater than 8MB, will hit `SsdRun`'s VELOX_CHECK and throw exception
![image](https://user-images.githubusercontent.com/34979747/222095414-5391247d-66a7-4ef6-a413-4b31d0936aea.png)

### Expected:
`SsdRun` is constructed from `AsyncDataCacheEntry` which `size()` return a int32_t variable, but `SsdRun` only support 23 bits size (8MB).
`AsyncDataCacheEntry` is related to `kDefaultLoadQuantum`, and it can be set explicitly by `ReaderOptions::setLoadQuantum` with over 8MB size.
We should support 32 bits `SsdRun` size.

### System information

Velox System Info v0.0.2
Commit: Not in a git repo.
CMake Version: 3.20.2
System: Linux-5.10.134-13.al8.x86_64
Arch: x86_64
C++ Compiler: /usr/lib64/ccache/c++
C++ Compiler Version: 10.2.1
C Compiler: /usr/lib64/ccache/cc
C Compiler Version: 10.2.1
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

### Relevant logs

```bash
WARNING: Logging before InitGoogleLogging() is written to STDERR
E0301 16:50:08.254395 1165613 Exceptions.h:68] Line: .././velox/common/caching/SsdFile.h:42, Function:SsdRun, Expression: size - 1 < 1 << kSizeBits (16777215 vs. 8388608), Source: RUNTIME, ErrorCode: INVALID_STATE

            unknown file: Failure
C++ exception with description "Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: (16777215 vs. 8388608)
Retriable: False
Expression: size - 1 < 1 << kSizeBits
Function: SsdRun
File: .././velox/common/caching/SsdFile.h
Line: 42
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxException5State4makeIZNS1_C4EPKcmS5_St17basic_string_viewIcSt11char_traitsIcEES9_S9_S9_bNS1_4TypeES9_EUlRT_E_EESt10shared_ptrIKS2_ESA_SB_
# 2  _ZN8facebook5velox14VeloxExceptionC2EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 3  _ZN8facebook5velox17VeloxRuntimeErrorC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bS7_
# 4  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_
# 5  _ZN8facebook5velox5cache6SsdRunC2Emj
# 6  _ZN8facebook5velox5cache7SsdFile5writeERSt6vectorINS1_8CachePinESaIS4_EE
# 7  _ZN29SsdFileTest_writeAndRead_Test8TestBodyEv
# 8  _ZN7testing8internal38HandleSehExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc
# 9  _ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS_4TestEvEET0_PT_MS4_FS3_vEPKc
# 10 _ZN7testing4Test3RunEv
# 11 _ZN7testing8TestInfo3RunEv
# 12 _ZN7testing9TestSuite3RunEv
# 13 _ZN7testing8internal12UnitTestImpl11RunAllTestsEv
# 14 _ZN7testing8internal38HandleSehExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc
# 15 _ZN7testing8internal35HandleExceptionsInMethodIfSupportedINS0_12UnitTestImplEbEET0_PT_MS4_FS3_vEPKc
# 16 _ZN7testing8UnitTest3RunEv
# 17 _Z13RUN_ALL_TESTSv
# 18 main
# 19 __libc_start_main
# 20 _start
" thrown in the test body.
```

**Comment by Yohahaha** [comment]
cc @mbasmanova @oerling

**Comment by mbasmanova** [comment]
@Yohahaha Curious, what's the motivation for this code change? Would you replace image of the code with plain text snippet. It is hard to work with images.

**Comment by Yohahaha** [comment]
```
  for (auto startOffset = 0; startOffset <= kSsdSize - SsdFile::kRegionSize;
       startOffset += SsdFile::kRegionSize) {
    auto pins =
        makePins(fileName_.id(), startOffset, 2 * kMB, 16 * kMB, 62 * kMB);
    ssdFile_->write(pins);
    for (auto& pin : pins) {
      EXPECT_EQ(ssdFile_.get(), pin.entry()->ssdFile());
      allEntries.emplace_back(
          pin.entry()->key(), pin.entry()->ssdOffset(), pin.entry()->size());
    };
  }
```

**Comment by Yohahaha** [comment]
@mbasmanova Thanks reply!
I was trying to enable local data cache in Gluten, and find this limit.

**Comment by mbasmanova** [comment]
CC: @Yuhta @xiaoxmeng

**Comment by oerling** [comment]
A single entry being latrger than 8MB does not net necessarily make sense. A single transfer size for a column chunk that is > 8MB will still be made even if it fills more than one cache entry. This is subject to getting the right prefetch. You would get this for a densely read column with >8MB column chunks.  Adding bits to the length on the other hand is straightforward enough. You could make the change. Or add a range check earlier in the control flow. What is the motivation? Note that eviction is tracked entry by entry. IO is multi-entry.  If entries were, say, max 16MB, then there would be for each 64MB region in SSD cache up to 16MB - 1 unused space at the end. In any case a SSD cache entry could not be > the region size. You could crank up the region size as well but again the benefit is not obvious. All the sizes (max quantum, ssd region etc.) could be global configs. The effect of these would be hard to explain and ard to configure and caches created with one setting might not be compatible with different settings. All kinds of possible misconfiguration and corner cases.    could arise.

**Comment by Yohahaha** [comment]
> A single entry being latrger than 8MB does not net necessarily make sense

Agree.
