### ISSUE TITLE
Add DATE type

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#418]
Add DATE type backed by 32-bit integer (int32_t).

CC: @funrollloops @pedroerp @aditi-pandit

**Comment by aditi-pandit** [comment]
Overlaps with https://github.com/facebookincubator/velox/issues/229 for TPC-H queries.

**Comment by aditi-pandit** [comment]
https://github.com/facebookincubator/velox/pull/475

**Comment by aditi-pandit** [comment]
https://github.com/facebookincubator/velox/pull/552

**Comment by aditi-pandit** [comment]
https://github.com/facebookincubator/velox/pull/627

**Comment by aditi-pandit** [comment]
Leaving this open since there are few functions left to be implemented for date type for completeness

viz current_date, from_iso8601_date and to_iso8601.

Will work on them after completing the interval related functionality.

**Comment by mbasmanova** [comment]
We also need to add support for DATE type to

- VectorHasher (will enable array-based aggregation for grouping keys of type DATE - https://facebookincubator.github.io/velox/develop/aggregations.html#array-mode )
- min/max aggregate functions
- registerUnaryScalar helper functions in velox/functions/lib/RegistrationHelpers.h

**Comment by majetideepak** [comment]
@yingsu00 this is probably a good starter for James.

**Comment by zhanglistar** [comment]
What's the status now? Thanks.

**Comment by aditi-pandit** [comment]
DATE support has been added in Velox. current_date, from_iso8601_date and to_iso8601 functions are not yet supported though.

I'm closing this issue as most work on this has completed. We will add separate issues for the missing work items.
