### ISSUE TITLE
Does Gluten use driver.cast.int_by_truncate configuration setting? 

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#4186]
### Bug description

"driver.cast.int_by_truncate" configuration setting is used to change the behavior of Cast. It is 'false' by default. Does Gluten (Spark on Velox) use this setting?

```
  // This flags forces the cast from float/double to integer to be performed by
  // truncating the decimal part instead of rounding.
  static constexpr const char* kCastIntByTruncate =
      "driver.cast.int_by_truncate";
```

CC: @rui-mo @FelixYBW @kagamiori 

### System information

n/a

**Comment by rui-mo** [comment]
@mbasmanova Indeed, we set this setting to true in Gluten as below to align with Spark.

```c++
configs[velox::core::QueryConfig::kCastIntByTruncate] = std::to_string(true);
```

**Comment by mbasmanova** [comment]
@rui-mo Rui, thank you for confirming that Gluten uses this setting.
