### ISSUE TITLE
Link Native Parquet writer in Velox

### ISSUE THREAD

**Issue by karteekmurthys** [facebookincubator/velox#4213]
### Description

The parquet writer is not currently linked in velox builds.
Include velox_dwio_parquet_writer in below CMakeLists.

**velox/velox/dwio/parquet/CMakeLists.txt**
```
add_subdirectory(duckdb_reader)
add_subdirectory(thrift)
add_subdirectory(reader)
add_subdirectory(writer)

if(${VELOX_BUILD_TESTING})
  add_subdirectory(tests)
endif()

add_library(velox_dwio_parquet_reader RegisterParquetReader.cpp)
target_link_libraries(
  velox_dwio_parquet_reader velox_dwio_duckdb_parquet_reader
  velox_dwio_native_parquet_reader xsimd)
```

**Comment by karteekmurthys** [comment]
cc: @majetideepak @yingsu00

**Comment by karteekmurthys** [comment]
Also, HiveDataSink currently uses only DWRF writer. It must optionally include Parquet writer as well:

```
 auto sink = dwio::common::DataSink::create(writePath);
  writers_.push_back(std::make_unique<Writer>( <--- ------------  this is velox::dwrf::writer
      options, std::move(sink), *connectorQueryCtx_->memoryPool()));
  writerInfo_.push_back(std::make_shared<HiveWriterInfo>(*writerParameters));
```

**Comment by yingsu00** [comment]
@karteekmurthys The Parquet readers and writer will be compiled when you set VELOX_BUILD_TESTING ON in the main CMakeLists.txt. It was set to OFF by intention.

**Comment by yzhang1991** [comment]
https://github.com/facebookincubator/velox/blob/main/CMakeLists.txt#L69
https://github.com/facebookincubator/velox/blob/main/velox/dwio/parquet/RegisterParquetReader.cpp

**Comment by yingsu00** [comment]
@karteekmurthys Please refer to the way how HiveDataSource create the reader_. It's calling getReaderFactory in HiveDataSource::addSplit
```
  reader_ = dwio::common::getReaderFactory(readerOpts_.getFileFormat())
                ->createReader(std::move(input), readerOpts_);
```
getReaderFactory() is defined in  velox/dwio/common/ReaderFactory.cpp:
```
std::shared_ptr<ReaderFactory> getReaderFactory(FileFormat format) {
  auto it = readerFactories().find(format);
  VELOX_CHECK(
      it != readerFactories().end(),
      "ReaderFactory is not registered for format {}",
      toString(format));
  return it->second;
}
```
Similarly we can create the writers in HiveDataSink by calling a new function `getWriterFactory` in a new file velox/dwio/common/WriterFactory.cpp

**Comment by majetideepak** [comment]
The PR here https://github.com/facebookincubator/velox/pull/4091 explored writing Parquet and identified some issues with the Arrow integration. We need to resolve those first.

**Comment by majetideepak** [comment]
Resolved with https://github.com/facebookincubator/velox/pull/5055
