### ISSUE TITLE
VeloxUserError: index < childrenSize_ in DWRF reader

### ISSUE THREAD

**Issue by kaikalur** [facebookincubator/velox#4220]
### Bug description

Query crashes

20230307_234810_03651_9dcgh

```
VeloxUserError: index < childrenSize_ (8 vs. 3) Split [file ws://ws.dw.pnb3dw1/namespace/measurementsystems/warehouse/cc66ee1106634f8c99aea538685bb5da/b5741db40dd141a2b309fb13008e5e38/ds=2023-03-04/ts=2023-03-05+06%3A00%3A99/action_type=create/part-00264 0 - 67108864] Task 20230307_234810_03651_9dcgh.2.0.182
```

### System information

prod

**Comment by mbasmanova** [comment]
@kaikalur Sreeni, do you happen to have a simple, TPC-H-based repro?

CC: @Yuhta @oerling

**Comment by kaikalur** [comment]
> @kaikalur Sreeni, do you happen to have a simple, TPC-H-based repro?
> 
> CC: @Yuhta @oerling

Sorry no. This is in one of our prod queries

**Comment by Yuhta** [comment]
#4255 fixes the crashes.  There still could be memory issue if we try to materialize the giant struct over exchange boundary, that will be addressed once we have subfields pruning fully integrated with presto_cpp.
