### ISSUE TITLE
Variance aggregation functions such as "stddev" and "variance" could produce incorrect result due to floating-point precision errors

### ISSUE THREAD

**Issue by isadikov** [facebookincubator/velox#4225]
### Bug description

I found that "stddev", "variance", and other Variance aggregation functions could produce incorrect results due to errors creeping in when calculating `newMean` in `VarianceAccumulator`.

If you have a table like this: 
```c++
auto inputRowVector = makeRowVector(
    {"c0", "c1"},
    {
        makeNullableFlatVector<int64_t>({-7, 8, -6, std::nullopt, -5}),
        makeNullableFlatVector<int64_t>(
            {-5, -8, -3, 2, -3833098290310622212}),
    });

auto vectors = {
    inputRowVector, 
    inputRowVector, 
    inputRowVector, 
    inputRowVector
};
```

then running a query `SELECT c0, stddev(c1) FROM table GROUP BY 1` would fail with the following:
```
Expected 5, got 5
1 extra rows, 1 missing rows
1 of extra rows:
	-5 | 256

1 of missing rows:
	-5 | "0"
```

The same query produces correct "0" result for row -5 in DuckDB and Spark. Actually, they all should be 0.

I opened a PR to fix this issue: https://github.com/facebookincubator/velox/pull/4156. When dealing with large int64_t, a small precision error might show up since all intermediate values are stored using `double` which can only hold 15 decimal digits. So any errors that come after that are untracked, however, with the current way of computing mean they cascade into large differences. 

The solution is to rewrite mean calculation to leverage difference (delta) instead of sum + multiplication:
```
mean = (countOther * meanOther + count * mean) / newCount
```

ends up being:
```
mean = (count * mean + countOther * meanOther) / newCount = 
       (count * mean) / newCount + (countOther * meanOther - countOther * mean + countOther * mean) / newCount = 
       (count + countOther) * mean / newCount + (meanOther - mean) * countOther / newCount = 
       mean + (meanOther - mean) * countOther / newCount = 
       mean + delta * countOther / newCount
```

This reduces the error and makes the above test pass.

Relates to https://github.com/facebookincubator/velox/issues/4083.

======

I also noticed that if I use post-aggregation projection in `VarianceAggregationTest::varianceWithGlobalAggregation` test, the small errors that are below EPSILON are removed, e.g. without projection you can get the error like this: 
```
at 0: expected 0.07500675872696637, 
       but got 0.07500675872696638
...
at 0: expected 0.0754257908986254, 
       but got 0.07542579089862542
```
but those errors disappear once the projection is used (I verified that the output matches in that case).

### System information

Velox System Info v0.0.2
Commit: 6eca9dfe12d215094e7a047aa66cf6fb78c9afbe
CMake Version: 3.25.2
System: Darwin-21.6.0
Arch: arm64
C++ Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
C++ Compiler Version: 14.0.0.14000029
C Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
C Compiler Version: 14.0.0.14000029
CMake Prefix Path: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk/usr;/Users/ivansadikov/homebrew;/usr/local;/usr;/;/Users/ivansadikov/homebrew/Cellar/cmake/3.25.2;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by aditi-pandit** [comment]
@laithsakka @Yuhta : We are interested to know your thoughts on this issue and PR. wdyt ?

**Comment by kagamiori** [comment]
Hi @isadikov, CircleCI nightly job caught another failure of the var_pop() function due to precision issue: https://app.circleci.com/pipelines/github/facebookincubator/velox/22264/workflows/f09ec64c-27f9-4e2a-b0cb-6467fb44c5ca/jobs/140580. Could you help take a look because you worked on this similar issue recently?

> I also noticed that if I use post-aggregation projection in VarianceAggregationTest::varianceWithGlobalAggregation test, the small errors that are below EPSILON are removed...

By the way, this problem is due to a limitation of the results verification utility code in assertResults(): https://github.com/facebookincubator/velox/issues/4481.

**Comment by isadikov** [comment]
Yes, sure. I will take a look.
