### ISSUE TITLE
[Spark] [Fuzzer] Common eval throws after retry success. 

### ISSUE THREAD

**Issue by kgpai** [facebookincubator/velox#4247]
### Description

Currently when  an expression fails in expression fuzzer we run it with try enabled and verify that both common eval and simplified eval show similar results. If this succeeds we again verify against the non - errored rows and expect no errors to be thrown in common or simple eval. 

In the expression below we see that we are seeing an error when verifying after retry. 

### Error Reproduction

Flags: 
```
--retry_with_try
--repro_persist_path=/Users/kpai/src/Velox/_velox_errors
--enable_variadic_signatures
--velox_fuzzer_enable_complex_types
--velox_fuzzer_enable_column_reuse
--velox_fuzzer_enable_expression_reuse
--lazy_vector_generation_ratio
0.2
```

Seed : 1431057359

Unfortunately in this particular case I cant attach a repro as fuzzer creates constant varbinaries in sql which currently cant be sql'ized (#4243 )

**Comment by laithsakka** [comment]
this is not happening over and over an is old plus we do not have artifact to reproduce there is nothing we can do here.
