### ISSUE TITLE
Unknown plan node type com.facebook.presto.sql.planner.plan.TableWriterMergeNode when running CREATE AS SELECT

### ISSUE THREAD

**Issue by isadikov** [facebookincubator/velox#4253]
### Bug description

I found that simple query such as 
```sql
create table ivan_test3 as select 1 as a, 2 as b;
```
fails in Prestissimo with 
```
VeloxUserError:  Unknown plan node type com.facebook.presto.sql.planner.plan.TableWriterMergeNode
```

I could reproduce it in Presto + Velox setup as well as in a unit test (works fine with Presto Java). It seems we always need to set `table_writer_merge_operator_enabled` to `false` to make this work (practically all Prestissimo tests set this flag).

Do you know if Velox inherently cannot support `TableWriterMergeNode` or has it not simply been added yet? Also, what is the difference between TableWriterMergeNode and TableWriteNode and why does Presto choose the former when running CTAS? I could not find much information on TableWriterMergeNode purpose so I would greatly appreciate more context on this operator. Thanks!

### System information

Reproducible on the latest master and seems to be a known issue. I am just trying to collect information on this and see if it is support is simply missing.

**Comment by xiaoxmeng** [comment]
> @majetideepak @aditi-pandit Do you know where I can find more context on the difference between TableWriterMergeNode and TableWriteNode? Should we support this operator in Velox? Thank you!

@isadikov  TableWriterMergeNode is to merge the meta outputs from multiple table writer. We are going to add this support soon. Thanks!
