### ISSUE TITLE
Use executor implement vread to boost ReadFileInputStream

### ISSUE THREAD

**Issue by Yohahaha** [facebookincubator/velox#4275]
### Description

For reading parquet file, column chunk requests were enqueued into `BufferedInput` as regions, and load these regions one by one sequentially. However, it could hurt performance when IO latency is heavy, such as cloud storage. So, submit these regions parallel to leverage network bandwidth is important.

We can implement a subclass of `BufferedInput` to override `enqueue` and `load` to archive parallel read, or use current `vread` interface, and I choose second way.

In out workloads, this feature can gain huge performance when read data from cloud storage.

**Comment by mbasmanova** [comment]
CC: @oerling @majetideepak @Yuhta
