### ISSUE TITLE
only velox/Type.h got installed after execute ./scripts/setup_ubuntu.sh & make

### ISSUE THREAD

**Issue by fq-zhaang** [facebookincubator/velox#4382]
### Problem description

I executed `./scripts/setup_ubuntu.sh` and `make` in the root directory. Only `velox/Type.sh` was put in the `/usr/local/include directory`. There was no error during the execution process.
```bash
./scripts/setup_ubuntu.sh
make
```

### System information

Velox System Info v0.0.2
Commit: e152ec65ff26ba17d3d4a58dc128e89ee967d8ca
CMake Version: 3.26.0
System: Linux-5.4.0-144-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr/local;/usr/local;/usr/X11R6;/usr/pkg;/opt
  
\nThe results will be copied to your clipboard if xclip is installed.

**Comment by kagamiori** [comment]
cc @kgpai

**Comment by assignUser** [comment]
This is the expected behavior at the moment, work is planned to properly install velox in #4027
