### ISSUE TITLE
NestLoopJoin Support

### ISSUE THREAD

**Issue by eedalong** [facebookincubator/velox#4452]
### Description

Hi guys, I wonder how to handle NestLoopJoin(Equal Condition) in Velox， Thx！

![image](https://user-images.githubusercontent.com/39682259/228549139-821643c4-72dd-4af5-ac02-2cbc4f2b0794.png)

**Comment by mbasmanova** [comment]
@eedalong Can you use CrossJoinNode?

**Comment by eedalong** [comment]
Thx.
