### ISSUE TITLE
MaterializedRowEpsilonComparator doesn't work with complex types with floating-point child types

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#4481]
### Bug description

MaterializedRowEpsilonComparator is expected to compare the expected and actual results with epsilon if floating-point column(s) exists in the result and conditions are satisfied. (See https://github.com/facebookincubator/velox/issues/3493 for the design.) When there is no floating-point column or conditions are not satisfied, regular comparison without epsilon is used. However, the results may have no floating-point column, but complex-typed columns with floating-point children, e.g., columns of row(double, bigint). In this situation, we should compare results with epsilon, but we currently do not. 

This problem can cause result verification failures in some unit tests. E.g., 
```
TEST_F(VarianceAggregationTest, varianceWithGlobalAggregation) {
  auto vectors = makeVectors(rowType_, 10, 20);
  createDuckDbTable(vectors);
  auto sql = genAggrQuery(
        "SELECT var_pop(c1), var_pop(c2), var_pop(c4), var_pop(c5) FROM tmp", aggrName);
    testAggregations(
        vectors,
        {},
        {GEN_AGG("c1"), GEN_AGG("c2"), GEN_AGG("c4"), GEN_AGG("c5")},
        // {"a0", "a1", "a2", "a3"},
        {},
        sql);
}
```

### System information

N/A

### Relevant logs

```bash
N/A
```

**Comment by liujiayi771** [comment]
@kagamiori Hi, I am working on kurtosis Presto function, and I find that validateStreamingInTestAggregations in testAggregations not use EpsilonComparator to check results. The func I implemented will fail due to the floating precision issue during the UT test. 
```
../../velox/vector/tests/utils/VectorTestBase.cpp:123: Failure
Value of: expected->equalValueAt(actual.get(), i, i)
  Actual: false
Expected: true
at 0: expected -1.2000000000000002, but got -1.2000000000000006
Google Test trace:
../../velox/functions/lib/aggregates/tests/AggregationTestBase.cpp:490: kurtosis
../../velox/functions/lib/aggregates/tests/AggregationTestBase.cpp:722: Streaming
../../velox/functions/lib/aggregates/tests/AggregationTestBase.cpp:76: SELECT kurtosis(c1) FROM tmp
../../velox/functions/lib/aggregates/tests/AggregationTestBase.cpp:58: SELECT kurtosis(c1) FROM tmp
```
Can you help to add the EpsilonComparator check for the streaming test?

**Comment by kagamiori** [comment]
Hi @liujiayi771, this is because validateStreamingInTestAggregations uses velox::test::assertEqualVectors() that compares values directly without epsilon. Could you try replacing velox::test::assertEqualVectors() with assertEqualResults() in QueryAssertions.h? This function supports comparison with epsilon.

https://github.com/facebookincubator/velox/blob/99ee69f6d8decf3b8ba3021bfea22e3661721e4e/velox/exec/tests/utils/QueryAssertions.h#L199

**Comment by liujiayi771** [comment]
> 

ok, i'll try it, thanks a lot.

**Comment by liujiayi771** [comment]
> Hi @liujiayi771, this is because validateStreamingInTestAggregations uses velox::test::assertEqualVectors() that compares values directly without epsilon. Could you try replacing velox::test::assertEqualVectors() with assertEqualResults() in QueryAssertions.h? This function supports comparison with epsilon.
> 
> https://github.com/facebookincubator/velox/blob/99ee69f6d8decf3b8ba3021bfea22e3661721e4e/velox/exec/tests/utils/QueryAssertions.h#L180-L201

ok, i'll try it, thanks a lot.

**Comment by kagamiori** [comment]
Closing this issue since QueryAssertions has been extended to apply epsilon comparison on floating-point columns in side complex types: https://github.com/facebookincubator/velox/pull/10927.
