### ISSUE TITLE
Reason: (830 vs. 100) Dictionary index must be less than base vector's size. Index: 25.

### ISSUE THREAD

**Issue by laithsakka** [facebookincubator/velox#4490]
### Description

https://app.circleci.com/pipelines/github/facebookincubator/velox/22488/workflows/bafb3c3d-d91d-4515-b258-1ee2ddc4e016/jobs/142099/artifacts

Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: (830 vs. 100) Dictionary index must be less than base vector's size. Index: 25.
Retriable: False
Expression: rawIndices_[i] < dictionaryValues_->size()
Context: from_utf8(c3, reverse(lower(c1)))
Top-Level Context: is_null(date_trunc(replace(concat(c0, lower(c1), c2, reverse(lower(c1)), ?T[>*M9"QcTeI9#;FSP8jA++2%4Z^B$\p!oE;(1vi=5.j`8:VARCHAR, c2), to_hex(from_base64(from_utf8(c3, reverse(lower(c1)))))), null:TIMESTAMP))
Function: setInternalState
File: ../.././velox/vector/DictionaryVector-inl.h

**Comment by laithsakka** [comment]
same :
https://app.circleci.com/pipelines/github/facebookincubator/velox/22467/workflows/50c00eeb-492f-4761-823e-6c8e6bd33759/jobs/141956/timing

**Comment by laithsakka** [comment]
same
https://app.circleci.com/pipelines/github/facebookincubator/velox/22468/workflows/a186c0f1-e5f6-4498-b3f7-8d056ab5dbdc/jobs/141962/artifacts

**Comment by mbasmanova** [comment]
Duplicate of #4496
