### ISSUE TITLE
Window::callApplyForPartitionRows only compute once between peerStartRow_ and peerEndRow_ cause problem

### ISSUE THREAD

**Issue by Yohahaha** [facebookincubator/velox#4502]
### Bug description

When I running fuzzer test with #4467 , I got an assert error in verifyWindow.

### Related Info
Rows
```
[ROW ROW<c0:INTEGER,p0:BOOLEAN,s0:VARBINARY,s1:DATE,s2:TINYINT,s3:INTEGER,s4:VARCHAR,row_number:BIGINT,w0:INTEGER>: 1000 elements, no nulls]
```

DuckSQL
```
SELECT c0, p0, s0, s1, s2, s3, s4, row_number, bit_xor(c0) OVER (partition by p0 order by s0, s1, s2, s3, s4) FROM tmp
```

Velox Plan
```
-- Window[partition by [p0] order by [s0 ASC NULLS LAST, s1 ASC NULLS LAST, s2 ASC NULLS LAST, s3 ASC NULLS LAST, s4 ASC NULLS LAST] w0 := bit_xor(ROW["c0"]) RANGE between UNBOUNDED PRECEDING and CURRENT ROW] -> c0:INTEGER, p0:BOOLEAN, s0:VARBINARY, s1:DATE, s2:TINYINT, s3:INTEGER, s4:VARCHAR, row_number:BIGINT, w0:INTEGER
  -- Values[1000 rows in 10 vectors] -> c0:INTEGER, p0:BOOLEAN, s0:VARBINARY, s1:DATE, s2:TINYINT, s3:INTEGER, s4:VARCHAR, row_number:BIGINT
```

### Reason
Velox current Window implementation only compute once if input rows has same value between peerStartRow_ and peerEndRow_, same value is defined by `peerCompare` with `sortKeyInfo_`. That means rows has same orderBy compare results in single partition will be compute only once.
https://github.com/facebookincubator/velox/blob/62edd076fba41ccbbcd654dd1d46ecc1f3dc9d86/velox/exec/Window.cpp#L462-L482

But for `bit_xor` aggregate function, same value should also be computed, other aggregate functions may have similar problems, examples below:
assume we have following rows and sql:
```
int, varchar, int
1, "a", 3
2, "b", 3
1, "a", 3
2, "b", 4

select sum(c2) over (partition by c0 order by c1);
```

### System information

Velox System Info v0.0.2
Commit: Not in a git repo.
CMake Version: 3.20.2
System: Linux-5.10.134-13.al8.x86_64
Arch: x86_64
C++ Compiler: /usr/lib64/ccache/c++
C++ Compiler Version: 10.2.1
C Compiler: /usr/lib64/ccache/cc
C Compiler Version: 10.2.1
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by Yohahaha** [comment]
cc @mbasmanova @aditi-pandit

**Comment by aditi-pandit** [comment]
Hi @Yohahaha : The logic you have quoted is computing the peer row values to put in the peerBuffer for the Window::callApplyForPartitionRows(...). The callApplyForPartitionRows(...) isn't called for each row individually. It is invoked for an output buffer of rows with buffers for peerStart(End), frameStart(End). So if all rows between peerStart and peerEnd fall in the same output buffer, the expected behavior is to callApplyForPartitionRows(...) once.

Please can you give me the command line for the fuzzer you invoked. I will try to debug the failure.

**Comment by Yohahaha** [comment]
Hi @aditi-pandit 

> So if all rows between peerStart and peerEnd fall in the same output buffer, the expected behavior is to callApplyForPartitionRows(...) once.

Sorry for opening a wrong issue, you're right.
