### ISSUE TITLE
Convert DATE type to logical type

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#4513]
### Description

See #4406 and #4069

**Comment by mbasmanova** [comment]
@aditi-pandit Aditi kindly offered to help with this change. 

CC: @duanmeng

**Comment by aditi-pandit** [comment]
@pramodsatya : Please can you try this refactoring.

**Comment by mbasmanova** [comment]
@aditi-pandit Any update?

**Comment by aditi-pandit** [comment]
I have started working on this. Should have something out by Monday.

**Comment by mbasmanova** [comment]
@aditi-pandit Aditi, thank you for the update. Is there a PR available for review now?

**Comment by aditi-pandit** [comment]
https://github.com/facebookincubator/velox/pull/5015
