### ISSUE TITLE
Implement timezone_minute Presto Function

### ISSUE THREAD

**Issue by gopukrishnasIBM** [facebookincubator/velox#4521]
### Description

Add missing function to handle timezone_minute prestosql function.

**Comment by gopukrishnasIBM** [comment]
@aditi-pandit Can you assign it to @Ann-Rose

**Comment by aditi-pandit** [comment]
> @aditi-pandit Can you assign it to @Ann-Rose

@gopukrishnasIBM : I don't find @Ann-Rose in the dropdown. Please can you confirm the github ID.

**Comment by Ann-Rose** [comment]
I confirm, this is my id @Ann-Rose
