### ISSUE TITLE
DuckDB has different result for Window in fuzzer test

### ISSUE THREAD

**Issue by Yohahaha** [facebookincubator/velox#4532]
### Description

AggregationFuzzer use DuckDB to verify result correctness, I have found a wrong result for DuckDB in Velox with PR https://github.com/facebookincubator/velox/pull/4467#issuecomment-1497233828.

To verify that is not an occasional case, I modify the Window coinToss from 0.1 to 0.9, re-run a 1 hour `velox_aggregation_fuzzer_test`, similar wrong results got again.

This command can reproduce in my machine:
```
./velox/exec/tests/velox_aggregation_fuzzer_test --seed 2556655631 --duration_sec 10 --logtostderr=1 --minloglevel=0 --repro_persist_path=/tmp/aggregate_fuzzer_repro --only="avg"
```

Related DuckDB SQL:
```
SELECT c0, p0, s0, s1, s2, s3, row_number, avg(c0) OVER (partition by p0 order by s0, s1, s2, s3) FROM tmp
```

DuckDB default window frame is RANGE, same as Presto.

### Error Reproduction

Modify Window coinToss from 0.1 to 0.9
https://github.com/facebookincubator/velox/blob/9eaaa683c1e8e2082899a8720327f8e4d6ea7570/velox/exec/tests/AggregationFuzzer.cpp#L558-L559

./velox/exec/tests/velox_aggregation_fuzzer_test --seed 123 --duration_sec 3600 --logtostderr=1 --minloglevel=0 --repro_persist_path=/tmp/aggregate_fuzzer_repro

./velox/exec/tests/velox_aggregation_fuzzer_test --seed 2556655631 --duration_sec 10 --logtostderr=1 --minloglevel=0 --repro_persist_path=/tmp/aggregate_fuzzer_repro --only="avg"

### Relevant logs

```bash
I0405 22:38:20.932768 4013141 AggregationFuzzer.cpp:532] ==============================> Started iteration 786 (seed: 2556655631)
I0405 22:38:20.935362 4013141 AggregationFuzzer.cpp:624] Executing query plan:
-- Window[partition by [p0] order by [s0 ASC NULLS LAST, s1 ASC NULLS LAST, s2 ASC NULLS LAST, s3 ASC NULLS LAST] w0 := avg(ROW["c0"]) RANGE between UNBOUNDED PRECEDING and CURRENT ROW] -> c0:SMALLINT, p0:BOOLEA$
, s0:DATE, s1:SMALLINT, s2:TINYINT, s3:TINYINT, row_number:BIGINT, w0:DOUBLE
  -- Values[1000 rows in 10 vectors] -> c0:SMALLINT, p0:BOOLEAN, s0:DATE, s1:SMALLINT, s2:TINYINT, s3:TINYINT, row_number:BIGINT
I0405 22:38:20.941809 4020465 Task.cpp:825] All drivers (1) finished for task test_cursor 2959 after running for 6 ms.
I0405 22:38:20.941823 4020465 Task.cpp:1474] Terminating task test_cursor 2959 with state Finished after running for 6 ms.
I0405 22:38:20.942467 4013141 AggregationFuzzer.cpp:639] [ROW ROW<c0:SMALLINT,p0:BOOLEAN,s0:DATE,s1:SMALLINT,s2:TINYINT,s3:TINYINT,row_number:BIGINT,w0:DOUBLE>: 1000 elements, no nulls]
../velox/exec/tests/utils/QueryAssertions.cpp:1062: Failure
Failed
Expected 1000, got 1000
1 extra rows, 1 missing rows
1 of extra rows:
        23511 | null | null | 21006 | 41 | 45 | 61 | 15876.634615384615

1 of missing rows:
        23511 | null | null | 21006 | 41 | 45 | 61 | 15815.733333333334

Unexpected results
E0405 22:38:21.185443 4013141 Exceptions.h:68] Line: ../velox/exec/tests/AggregationFuzzer.cpp:960, Function:verifyWindow, Expression: assertEqualResults(expectedResult.value(), {resultOrError.result}) Velox and
DuckDB results don't match, Source: RUNTIME, ErrorCode: INVALID_STATE
I0405 22:38:21.186599 4013141 AggregationFuzzer.cpp:452] Persisted input: /tmp/aggregate_fuzzer_repro/velox_vector_jfqwe7 and plan: /tmp/aggregate_fuzzer_repro/velox_plan_Zx3AY6
terminate called after throwing an instance of 'facebook::velox::VeloxRuntimeError'
  what():  Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Velox and DuckDB results don't match
Retriable: False
Expression: assertEqualResults(expectedResult.value(), {resultOrError.result})
Function: verifyWindow
File: ../velox/exec/tests/AggregationFuzzer.cpp
Line: 960
```
```

**Comment by Yohahaha** [comment]
CC @mbasmanova

**Comment by mbasmanova** [comment]
@Yohahaha I assume DuckDB results are incorrect. If so, would you file an issue at https://github.com/duckdb/duckdb ?

**Comment by mbasmanova** [comment]
CC: @aditi-pandit

**Comment by Yohahaha** [comment]
> @Yohahaha I assume DuckDB results are incorrect. If so, would you file an issue at https://github.com/duckdb/duckdb ?

Hi @mbasmanova, I guess the problem is related with old DuckDB version but not verified, Velox use v0.4.1-dev344 currently, I will try to upgrade DuckDB version soon.

**Comment by mbasmanova** [comment]
@Yohahaha 

> the problem is related with old DuckDB 

Got it. Please, try upgrading to see if the issue goes away. Thank you for working on this.

**Comment by aditi-pandit** [comment]
> @Yohahaha
> 
> > the problem is related with old DuckDB
> 
> Got it. Please, try upgrading to see if the issue goes away. Thank you for working on this.

@Yohahaha : We have found DuckDB avg implementation problematic in other situations also. See https://github.com/duckdb/duckdb/issues/6829. Though we discovered the problems through DECIMAL type and not double.

Could you share the input data values for us to understand more if possible ? I wonder if some overflow situation is being encountered here.

**Comment by Yohahaha** [comment]
Hi @aditi-pandit 

> Could you share the input data values for us to understand more if possible ? I wonder if some overflow situation is being encountered here.

Can I attach the saved `velox_vector_xxx` file in this issue? does this helpful to you? You could also modify the window cointoss to get the results.

**Comment by sanumandla** [comment]
Hi @aditi-pandit, can you please help with this issue? Thank you!

**Comment by mbasmanova** [comment]
@aditi-pandit Any update?

**Comment by isadikov** [comment]
I am following up on this.

**Comment by isadikov** [comment]
I have started working on this, apologies for the delay.

**Comment by isadikov** [comment]
@Yohahaha I am struggling to reproduce this issue on the latest main branch. Would you be able to attach the files necessary to trigger the problem, e.g. velox_vector... so I can run on my laptop? Thanks.

**Comment by isadikov** [comment]
Actually, I managed to reproduce this: 
```
/tmp/velox/cmake-build-debug/velox/exec/tests/velox_aggregation_fuzzer_test --seed 2556655631 --duration_sec 60 --only avg --logtostderr=1 --minloglevel=0 --gtest_filter=* --gtest_color=no
Testing started at 7:31 AM ...
W20230523 07:31:46.518414 3291783 AggregationFuzzer.cpp:336] Skipping generic function signature: a_scale(DECIMAL(a_precision,a_scale)) -> varbinary -> DECIMAL(a_precision,a_scale)
I20230523 07:31:46.519193 3291783 AggregationFuzzer.cpp:260] Total functions: 1 (6 signatures)
I20230523 07:31:46.519207 3291783 AggregationFuzzer.cpp:262] Functions with at least one supported signature: 1 (100.00%)
I20230523 07:31:46.519223 3291783 AggregationFuzzer.cpp:266] Functions with no supported signature: 0 (0.00%)
I20230523 07:31:46.519230 3291783 AggregationFuzzer.cpp:268] Supported function signatures: 5 (83.33%)
I20230523 07:31:46.519237 3291783 AggregationFuzzer.cpp:272] Unsupported function signatures: 1 (16.67%)
I20230523 07:31:46.519266 3291783 AggregationFuzzer.cpp:554] ==============================> Started iteration 0 (seed: 2556655631)
I20230523 07:31:46.521207 3291783 AggregationFuzzer.cpp:652] Executing query plan: 
-- Window[partition by [p0] order by [s0 ASC NULLS LAST, s1 ASC NULLS LAST, s2 ASC NULLS LAST, s3 ASC NULLS LAST] w0 := avg(ROW["c0"]) RANGE between UNBOUNDED PRECEDING and CURRENT ROW] -> c0:DOUBLE, p0:BOOLEAN, s0:DATE, s1:SMALLINT, s2:TINYINT, s3:TINYINT, row_number:BIGINT, w0:DOUBLE
  -- Values[1000 rows in 10 vectors] -> c0:DOUBLE, p0:BOOLEAN, s0:DATE, s1:SMALLINT, s2:TINYINT, s3:TINYINT, row_number:BIGINT
I20230523 07:31:46.525825 3291808 Task.cpp:875] All drivers (1) finished for task test_cursor 1 after running for 3 ms.
I20230523 07:31:46.525857 3291808 Task.cpp:1553] Terminating task test_cursor 1 with state Finished after running for 3 ms.
I20230523 07:31:46.526258 3291783 AggregationFuzzer.cpp:667] [ROW ROW<c0:DOUBLE,p0:BOOLEAN,s0:DATE,s1:SMALLINT,s2:TINYINT,s3:TINYINT,row_number:BIGINT,w0:DOUBLE>: 1000 elements, no nulls]
E20230523 07:31:46.668896 3291783 Exceptions.h:68] Line: /tmp/velox/velox/exec/tests/AggregationFuzzer.cpp:990, Function:verifyWindow, Expression: assertEqualResults(expectedResult.value(), {resultOrError.result}) Velox and DuckDB results don't match, Source: RUNTIME, ErrorCode: INVALID_STATE
libc++abi: terminating with uncaught exception of type facebook::velox::VeloxRuntimeError: Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Velox and DuckDB results don't match
Retriable: False
Expression: assertEqualResults(expectedResult.value(), {resultOrError.result})
Function: verifyWindow
File: /tmp/velox/velox/exec/tests/AggregationFuzzer.cpp
Line: 990
Stack trace:
/tmp/velox/velox/exec/tests/utils/QueryAssertions.cpp:1017: Failure
Failed
Expected 1000, got 1000
1 extra rows, 1 missing rows
1 of extra rows:
	0.7175111607648432 | null | null | 21006 | 41 | 45 | 61 | 0.48453118572181736

1 of missing rows:
	0.7175111607648432 | null | null | 21006 | 41 | 45 | 61 | 0.4826726330244648

Unexpected results

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

I will follow up on the fix.

**Comment by isadikov** [comment]
I wrote a unit test that reproduces this issue with a sample data and debugged this further. It is actually a bug in DuckDB that we bundle with Velox, not a bug in Velox. 

My dataset contains 129 records of the following schema:
```sql
create table tmp (c0 double, s1 int, s2 int, s3 int);
```

I run the following query: 
```sql
select *, avg(c0) over (order by s1 ASC NULLS LAST, s2 ASC NULLS LAST, s3 ASC NULLS LAST) as avg_c0 from tmp
```
NULLS LAST part depends on the database, I had to replace it with an alternative in MySQL.

Results for the query engines I tested with:

Velox (latest master):
`0.7175111607648432 | null | 82 | 41 | 0.48453118572181736`

Spark 3.4.0:
`|  0.7175111607648432| null|  82|  41|0.48453118572181736|`

Postgres 15.3:
`0.7175111607648432 |       |  82 |  41 | 0.48453118572181736`

MySQL 8.0.33:
`|   0.7175111607648432 |  NULL |   82 |   41 | 0.48453118572181736 |`

DuckDB 0.8.0
`│  0.7175111607648432 │       │    82 │    41 │ 0.48453118572181736 │`

DuckDB (bundled with Velox)
`0.7175111607648432 | null | 82 | 41 | 0.4826726330244648`
`0.7175111607648432	NULL	82	41	0.4826726330244648`

For some reason, DuckDB shipped with Velox that we use for query assertions produces an incorrect result. I can confirm it with a script without even running the test.

There appears to be no correctness issues in Velox with regard to this problem but we may need to consider upgrading DuckDB version in Velox.

cc @mbasmanova @majetideepak @aditi-pandit

**Comment by isadikov** [comment]
I will open a PR to update the DuckDB version to fix this issue.

**Comment by Yuhta** [comment]
Do we have a fix for this one?  Seems still happening: https://app.circleci.com/pipelines/github/facebookincubator/velox/28332/workflows/149c3f61-7f3a-4f8f-890d-90535f4b6d9d/jobs/178622

**Comment by mbasmanova** [comment]
I believe @isadikov has left the project. We need find someone to pick up DuckDB upgrade. CC: @aditi-pandit

**Comment by laithsakka** [comment]
this is same as https://github.com/facebookincubator/velox/issues/4350
