### ISSUE TITLE
Add ValueStreamNode

### ISSUE THREAD

**Issue by jinchengchenghh** [facebookincubator/velox#4649]
### Description

Gluten will use Velox RowVector-based shuffleto replace current Arrow-based shuffle. To connect it with subsequent Velox computing, we wrap the RowVector iterator as a RowVectorStream, and use this operator to fetch data from it.
 So the node changes from `ArrowStreamNode` to `ValueStreamNode`.

Now velox has Node `ValuesNode` whose input argument is `std::vector<RowVectorPtr> values`, which will load all the data from shuffle..
```
  ValuesNode(
      const PlanNodeId& id,
      std::vector<RowVectorPtr> values,
      bool parallelizable = false,
      size_t repeatTimes = 1)
```
Add
```
  ValueStreamNode(
      const PlanNodeId& id,
     std::shared_ptr<RowVectorStream> valueStream)
```

Relevant PR: 
https://github.com/facebookincubator/velox/pull/3917
https://github.com/oap-project/gluten/pull/1397

**Comment by mbasmanova** [comment]
Curious why wouldn't you use ExchangeNode and Exchange operator with a custom ExchangeSource?

**Comment by jinchengchenghh** [comment]
Because our source data origins from java size Iterator ColumnarBatch, https://github.com/oap-project/gluten/blob/main/cpp/core/jni/JniWrapper.cc#L173  https://github.com/oap-project/gluten/blob/main/gluten-data/src/main/scala/io/glutenproject/vectorized/CloseableColumnBatchIterator.scala#L32, to adaptive Spark framework, we need to iterator ColumnarBatch from shuffle reader which exists in only one worker.

It is a supplement of `ValuesNode`.

Maybe in the further future, we can totally use Velox plan node to shuffle.

**Comment by mbasmanova** [comment]
> we need to iterator ColumnarBatch from shuffle reader which exists in only one worker.

I'm not sure why this prevents you from using Exchange operator. Would you explain a bit more?

**Comment by jinchengchenghh** [comment]
@FelixYBW Can you help explain a bit more?

**Comment by FelixYBW** [comment]
@mbasmanova currently the data transfer is still fully reused Vanilla spark's. Chengcheng's latest PR removes the arrow intermediate format, instead we  transfer serialized velox rowvector directly. From Spark shuffle, we can get an iterator of rowvector as reducer pipeline's input. Now we needn't to touch the mapper's address and shuffle block's position, etc. we either needn't to care about the async data fetch of spark shuffle. This part isn't computation intensive and highly optimized by Spark. 

If we fully use Velox's exchange framework, we need to rewrite spark's shuffle logic on mapper and reducer, and communicate though spark driver directly to get the mapper block information etc. The work is not simple. We did plan to abstract velox's shuffle logic more to fit into Gluten's pipeline in future.

If we only reuse Velox's exchange client part, we need to use the rowvector iterator to mimic a buffer_ queue and pass to customized exchange source, which added much complexity than current ValueStreamNode solution but no performance benefit.

**Comment by mbasmanova** [comment]
@FelixYBW I'm not sure understanding, but is there any particular reason not to add ValueStreamNode to Gluten codebase and use Operator::registerOperator API? This node and operator seem very specific to Gluten.

**Comment by jinchengchenghh** [comment]
Moved to gluten internal.
