### ISSUE TITLE
Timestamp reader support for Parquet file format

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#4681]
### Description

Hi,
We would like to add the support for timestamp in Velox Parquet reader. It was noticed there were two kinds of timestamp types used in Parquet files, the INT96 type and the INT64 type (for TIMESTAMP_MILLIS or TIMESTAMP_MICROS). Which one is Velox's plan on timestamp reader for Parquet?

Although INT96 is deprecated in Parquet (see [PARQUET-323](https://issues.apache.org/jira/browse/PARQUET-323)), Spark uses it by default for timestamp during Parquet writing. Therefore, we firstly drafted this PR(https://github.com/facebookincubator/velox/pull/4680) to support a timestamp reader to read from INT96-typed timestamps, and would like to hear your opinions and suggestions. Thanks!

**Comment by rui-mo** [comment]
@mbasmanova @majetideepak Would you like to take a look on this issue?

**Comment by mbasmanova** [comment]
CC: @oerling @Yuhta @yingsu00

**Comment by majetideepak** [comment]
@rui-mo we definitely need to support INT96 timestamp type for legacy Parquet writers and Parquet files. I will review the PR. Thanks for raising this issue.

**Comment by rui-mo** [comment]
@majetideepak Thanks for the feedback!
