### ISSUE TITLE
Add missing function to handle normal_cdf function.

### ISSUE THREAD

**Issue by poojabhandari** [facebookincubator/velox#4717]
### Description

add missing function to handle normal_cdf prestosql function.

**Comment by poojabhandari** [comment]
@aditi-pandit please assign it to @poojabhandari  thanks!

**Comment by ashokku2022** [comment]
@majetideepak @mbasmanova if you could assigned this issue to @poojabhandari that would be great as she is working on getting the PR out, thanks!
