### ISSUE TITLE
Wrongly skip a row group in metadata filter

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#4749]
### Bug description

Hi,
We found this issue when running Spark unit test.

For a remaining filter combined with `not equal` and `or`, row group is wrongly skipped.

The Velox plan is as below.

-- TableScan[table: hive_table, remaining filter: (or(not(eq(ROW["a"],cast 2 as INTEGER)),not(eq(ROW["b"],cast 1 as VARCHAR))))] -> a:INTEGER, b:VARCHAR

If `not(eq(x))` is converted to `neq(x)`, the result is right, but `not(eq(x))` can be a possible way of computing.

We find NotNode negates the bits, which can cause incorrect result because its input only decides a range to exclude. But the others are not decided to be excluded or included. Through negating, those not determined are wrongly decided. Do we consider removing NotNode from Metadata filter for simplicity?

https://github.com/facebookincubator/velox/blob/main/velox/dwio/common/MetadataFilter.cpp#L102-L113

This issue can be reproduced with https://github.com/facebookincubator/velox/pull/4748.

### System information

Velox System Info v0.0.2
Commit: 438b62e5e98952d7bbd678f6581d8fe01c577570
CMake Version: 3.16.3
System: Linux-5.4.0-146-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by rui-mo** [comment]
Hi @Yuhta, would you like to take a look on this issue? Thanks.

**Comment by Yuhta** [comment]
@rui-mo Nice catch, I think the right solution is to push NOT down to leaf nodes.  I will have a fix soon.

**Comment by rui-mo** [comment]
@Yuhta Thank you for the quick fix!
