### ISSUE TITLE
Decimal function signature binder constraint cannot work in complex computation

### ISSUE THREAD

**Issue by jinchengchenghh** [facebookincubator/velox#4773]
### Description

Currently, the function signature is a simple computation to generate result type.
```
.integerVariable("r_precision", "min(38, a_precision + b_precision)")


  void apply(
      const SelectivityVector& rows,
      std::vector<VectorPtr>& args,
      const TypePtr& resultType, // This result type is same with constraint 
      exec::EvalCtx& context,
      VectorPtr& result) const override {

// The result type is computed in 
  auto calculation = buildCalculation(variable, constraints);
  expression::calculation::evaluate(calculation, integerVariablesBindings);
```

![image](https://user-images.githubusercontent.com/79615558/235032139-20c58624-0156-4dea-834d-00c704ac00a7.png)

But for spark decimal arithmetic result computation, it is:
```
adjustPrecisionScale(aPrecision + bPrecision + 1, aScale + bScale);

inline static std::pair<uint8_t, uint8_t> adjustPrecisionScale(
    const uint8_t rPrecision,
    const uint8_t rScale) {
  if (rPrecision <= 38) {
    return {rPrecision, rScale};
  } else if (rScale < 0) {
    return {38, rScale};
  } else {
    int32_t minScale = std::min(static_cast<int32_t>(rScale), 6);
    int32_t delta = rPrecision - 38;
    return {38, std::max(rScale - delta, minScale)};
  }
}

```
How to compute it under signature binder? Can we use a function as an argument of function `integerVariable()`?

Relevant PR: 
https://github.com/facebookincubator/velox/pull/4613
https://github.com/facebookincubator/velox/pull/4638

Do you have any suggestions for that? @mbasmanova @majetideepak

**Comment by majetideepak** [comment]
@jinchengchenghh You could improve the TypeCalculation grammar to support the ternary conditional operator.
`velox/expression/type_calculation/TypeCalculation.yy` `velox/expression/type_calculation/TypeCalculation.ll`
You can build the above expression as 
`r_recision = ((aPrecision + bPrecision + 1) <= 38) ? (aPrecision + bPrecision + 1) : 38)`
`r_scale = ((aPrecision + bPrecision + 1) <= 38) ? (aScale + bScale) : (((aScale + bScale) < 0) ? aScale + bScale : (max(rScale - delta, minScale))))`

**Comment by jinchengchenghh** [comment]
Should I improve the TypeCalculation grammar in a new PR or existing PR https://github.com/facebookincubator/velox/pull/4613

**Comment by majetideepak** [comment]
@jinchengchenghh You can add it to the existing PR since that would have tests as well.
