### ISSUE TITLE
Some aggregate function behavior is controlled by config

### ISSUE THREAD

**Issue by jinchengchenghh** [facebookincubator/velox#4774]
### Description

Some spark functions such as `bloom_filter_agg` allow user to change the function argument default value and max value.

Now we cannot get configuration when we implement aggregate functions, because we cannot get queryContext config there.

If we need this feature, we should reserve config in `GroupingSet` when we initialize it in `HashAggregation.cpp`.
Now just Spiller::Config exists in `GroupingSet`.

And we need to add a new argument `config` or `context` to functions such as `addRawInput`, it will change all the aggregate function input arguments.
Or we can reserve the config in `Aggregate`, it changes the code less but `Aggregate` is created from FunctionRegistry factory, we cannot use constructor to create it with config.

What's the best way to implement it?

Welcome to participate the topic.

Relevant PR: https://github.com/facebookincubator/velox/pull/4028#discussion_r1179255310

**Comment by zhli1142015** [comment]
How about add an `virtaul void initialize(const core::QueryConfig& config)` method to class `Aggregate`, this would be similar to what we does for scala fucntions.

**Comment by Yohahaha** [comment]
It looks similar with first/last spark aggregate function discussed in https://github.com/facebookincubator/velox/discussions/4611, first/last can use different function name as workaround, but bloom_filter_agg need a config indeed.

Pass a config class to aggregate function's constructor or initialize method could fix these cases.

**Comment by jinchengchenghh** [comment]
Do you have some suggestions? @mbasmanova Do you think @zhli1142015 's suggestions is reasonable?

**Comment by mbasmanova** [comment]
> How about add an virtaul void initialize(const core::QueryConfig& config) {} method to class Aggregate, this would be similar to what we does for scala fucntions.

Sounds reasonable to me. CC: @kagamiori @laithsakka @Yuhta

**Comment by jinchengchenghh** [comment]
Can you help implement this feature? Thanks! @zhli1142015
