### ISSUE TITLE
Aggregate possible have memory leak in global aggregation and non-global aggregation

### ISSUE THREAD

**Issue by Yohahaha** [facebookincubator/velox#4894]
### Bug description

According to https://facebookincubator.github.io/velox/develop/aggregate-functions.html#accumulator
> Memory allocated from the HashStringAllocator needs to be released in the destroy() method.

AggregateWindow will invoke Aggregate::destroy in its destructor.
https://github.com/facebookincubator/velox/blob/acaeb1f8705cf92cb5eddc3299b7ee24d32ab95e/velox/exec/AggregateWindow.cpp#L94-L101

But GroupingSet only invoke Aggregate::destroy when isGlobal_= true and Aggregate::accumulatorUsesExternalMemory return true. 
https://github.com/facebookincubator/velox/blob/acaeb1f8705cf92cb5eddc3299b7ee24d32ab95e/velox/exec/GroupingSet.cpp#L93-L97
https://github.com/facebookincubator/velox/blob/acaeb1f8705cf92cb5eddc3299b7ee24d32ab95e/velox/exec/GroupingSet.cpp#L379-L381

For most Aggregates, their accumulatorUsesExternalMemory default return false, thus will not be invoked destroy in global aggregation. For non-global aggregation, seems no one will invoke destroy method to release memory.

Why we use these conditions to decide whether invoke destroy? Is anywhere will shared aggregates with grouping set?

CC @mbasmanova @xiaoxmeng 

### System information

Velox System Info v0.0.2
Commit: Not in a git repo.
CMake Version: 3.20.2
System: Linux-5.10.134-13.1.al8.x86_64
Arch: x86_64
C++ Compiler: /usr/lib64/ccache/c++
C++ Compiler Version: 10.2.1
C Compiler: /usr/lib64/ccache/cc
C Compiler Version: 10.2.1
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by Yuhta** [comment]
For grouped aggregation, the aggregates are destroyed in hash table -> row container: https://github.com/facebookincubator/velox/blob/acaeb1f8705cf92cb5eddc3299b7ee24d32ab95e/velox/exec/RowContainer.cpp#L298

**Comment by Yohahaha** [comment]
Thanks for reply @Yuhta .

I add log and debug MinMaxTest.maxVarchar, both global aggregation and grouped aggregation's destroy were not invoked.

RowContainer::freeAggregates only invoked in spilling aggregation when running testAggregates.

**Comment by Yuhta** [comment]
min/max is not using external memory so destroy is not called.  Can you check some other aggregate that has `accumulatorUsesExternalMemory()` return `true`?

**Comment by Yohahaha** [comment]
> min/max is not using external memory so destroy is not called. Can you check some other aggregate that has `accumulatorUsesExternalMemory()` return `true`?

Only `SumNonPODAggregate`'s accumulatorUsesExternalMemory return true.

Most aggregate use `SingleValueAccumulator`, did you mean `SingleValueAccumulator` will auto release memory without explicitly invoke SingleValueAccumulator::destroy?
@Yuhta

**Comment by Yuhta** [comment]
Yes memory allocated from `HashStringAllocator` is not considered "external memory" and does not need to released in the aggregate itself.

**Comment by Yohahaha** [comment]
Thanks for the explanation!
