### ISSUE TITLE
VectorTest.findDuplicateValue fails in CircleCI

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#4897]
### Bug description

https://app.circleci.com/pipelines/github/facebookincubator/velox/24798/workflows/5015a9f8-2014-4a70-8f50-03d51c196b5a/jobs/157242/tests

### System information

CircleCI

### Relevant logs

```bash
../../velox/vector/tests/VectorTest.cpp:2325
Failed
Expected an exception
```

**Comment by kagamiori** [comment]
cc @mbasmanova

**Comment by mbasmanova** [comment]
The check that is supposed to throw is a debug-only check. Hence, it doesn't throw in release builds. I'm going to remove this test.
