### ISSUE TITLE
Wrong result of Date::toString() in multithreading

### ISSUE THREAD

**Issue by xiaodouchen** [facebookincubator/velox#5028]
### Bug description

When I was running an end-to-end test on velox, I encountered an error.

Query
```
SELECT cast(cast(c0 as varchar) as date) FROM test
```
`c0` is date type and the data of `c0` is randomly generated. 

Error
```
Failed to cast from VARCHAR to DATE: 2014-02-30. Date out of range: 2014-2-30". 
```
I analyzed the code and found that `Date::toString()` was called when casting date to varchar, and `std::gmtime()` was used in`Date::toString()`. `std::gmtime()` is not threadsafe and will cause wrong results. I try to replace it with `std::gmtime_r()`, and the error is no longer reported.

In addition, I notice that `std::gmtime()` is also used in `Timestamp::toString()`, but I don't quite understand the comment that `std::gmtime_r()` is not used here. @mbasmanova Can you help me with my problem here?

### System information

Velox System Info v0.0.2
Commit: 590d56f5caf744e7adbf9e0051181fa17a3498e8
CMake Version: 3.25.1
System: Darwin-21.4.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 13.1.6.13160021
C Compiler: 
C Compiler Version: 13.1.6.13160021
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.25.1;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by laithsakka** [comment]
is gmtime_r thread safe? if so do you want to put  a PR for the change? sounds like a bug

**Comment by laithsakka** [comment]
you can ping me to review it

**Comment by laithsakka** [comment]
linking the pr i found it https://github.com/facebookincubator/velox/pull/5029
