### ISSUE TITLE
support array_concat

### ISSUE THREAD

**Issue by hn5092** [facebookincubator/velox#5085]
### Description

当前不支持 array_concat

**Comment by whutjs** [comment]
You could use [zip_with](https://facebookincubator.github.io/velox/functions/presto/array.html#zip_with) for the purpose of `array_concat`.

**Comment by hn5092** [comment]
> You could use [zip_with](https://facebookincubator.github.io/velox/functions/presto/array.html#zip_with) for the purpose of `array_concat`.

A little different
<img width="1087" alt="image" src="https://github.com/facebookincubator/velox/assets/10030046/b416ecd8-36be-4359-98fa-e3a83ed48df5">
<img width="1291" alt="image" src="https://github.com/facebookincubator/velox/assets/10030046/00d954f4-f757-4dca-95b0-7c616b059ae5">
