### ISSUE TITLE
Remove Parquet implementation based on DuckDB

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#5108]
### Description

Now that we have the native implementation for Parquet, we can remove the implementation based on DuckDB.
We must port existing DuckDB tests to Native and verify parity.

**Comment by aditi-pandit** [comment]
This will also help us to move to DuckDB 0.8.0. That has some fixes for empty frames for window functions.

**Comment by majetideepak** [comment]
This is complete.
