### ISSUE TITLE
Join fuzzer fails with no such file or directory at end of job

### ISSUE THREAD

**Issue by kgpai** [facebookincubator/velox#5150]
### Description

Shouldnt fail with no such file or directory (possible race condition ?). 

### Error Reproduction

eval " _build/debug/velox/exec/tests/velox_join_fuzzer_test  --seed ${RANDOM} --duration_sec 3600 --logtostderr=1 --minloglevel=0 "

### Relevant logs

```bash
I0605 03:45:48.770680 93950 Task.cpp:1550] Terminating task test_cursor 14021 with state Finished after running for 11 ms.
I0605 03:45:48.770833  6661 JoinFuzzer.cpp:270] Results: [ROW ROW<bp1:ARRAY<INTEGER>,u0:VARBINARY>: 500 elements, no nulls]
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::directory_iterator::construct: No such file or directory: "/tmp/velox_test_hypwZy/test_cursor 14021"
*** Aborted at 1685936748 (Unix time, try 'date -d @1685936748') ***
*** Signal 6 (SIGABRT) (0x1a05) received by PID 6661 (pthread TID 0x7fea4d3c5240) (linux TID 6661) (maybe from PID 6661, UID 0) (code: -6), stack trace: ***
(error retrieving stack trace)
```

**Comment by kagamiori** [comment]
There is a new instance: https://app.circleci.com/pipelines/github/facebookincubator/velox/28080/workflows/543a45db-915e-4309-ba82-2a8ac2b30987/jobs/177116.

**Comment by laithsakka** [comment]
another one https://app.circleci.com/jobs/github/facebookincubator/velox/187374

**Comment by laithsakka** [comment]
closing the issue until it happen again there is no action that we can do.
