### ISSUE TITLE
nextGroup is not loaded in scheduleRowGroups

### ISSUE THREAD

**Issue by zhli1142015** [facebookincubator/velox#5172]
### Bug description

Hello,
From my understand below logic should be `if (inputs_.count(nextGroup) == 0) {`, @oerling , @Yuhta , could you please help clarify?
https://github.com/facebookincubator/velox/blob/main/velox/dwio/parquet/reader/ParquetReader.cpp#L470
Thanks.

### System information

Velox System Info v0.0.2
Commit: 480e0a91be50ead06eb41423b3c563b33f5e4b2f
CMake Version: 3.16.3
System: Linux-5.10.102.1-microsoft-standard-WSL2
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by Yuhta** [comment]
Yes it looks like a bug.  Would you fix it?

**Comment by yingsu00** [comment]
@zhli1142015 I think this is fixed already, can you please confirm it? If yes can we close this issue?

**Comment by zhli1142015** [comment]
Yes, this is fixed.
