### ISSUE TITLE
Max value of Timestamp will throw when invoke toString

### ISSUE THREAD

**Issue by Yohahaha** [facebookincubator/velox#5199]
### Bug description

I see lots of usage like this https://github.com/facebookincubator/velox/blob/90b26a83c3a9234bae59c733fd9202cd948a2645/velox/functions/prestosql/aggregates/MinMaxAggregates.cpp#L31-L44

But invoke Timestamp::toString() for max value will throw
```
"Can't convert Seconds to time: 9223372036854775807"
```

### Reproduce
```
TEST(TimestampTest, test) {
  auto ts = Timestamp(
      std::numeric_limits<int64_t>::max(),
      std::numeric_limits<uint64_t>::max());
  ts.toString();
}
```

### Question
1, How do we represent max value of Timestamp?
2, Could we implement a common MaxMinTrait for every type supported?

### System information

Velox System Info v0.0.2
Commit: Not in a git repo.
CMake Version: 3.20.2
System: Linux-5.10.134-13.1.al8.x86_64
Arch: x86_64
C++ Compiler: /usr/lib64/ccache/c++
C++ Compiler Version: 10.2.1
C Compiler: /usr/lib64/ccache/cc
C Compiler Version: 10.2.1
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by Yohahaha** [comment]
CC @mbasmanova @majetideepak

**Comment by mbasmanova** [comment]
Related PR: #5083
