### ISSUE TITLE
Remove default CPU_TARGET avx from cmake_install function in setup-helper-functions.sh

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#5204]
### Description

The default CPU_TARGET avx does not work on Mac M1 machines. 
We can remove the default since get_cxx_flags automatically infers the target if not specified.

https://github.com/facebookincubator/velox/blob/main/scripts/setup-helper-functions.sh#L130

**Comment by Nimausfi** [comment]
Hi Deepak, can I remove the default CPU_TARGET and open a PR? Thank you!

**Comment by majetideepak** [comment]
@Nimausfi sure. Someone reached out to me offline as well to work on this but there is no PR yet.
I guess who ever opens a working PR first :).
