### ISSUE TITLE
Fuzzer failure in trim_array

### ISSUE THREAD

**Issue by aditi-pandit** [facebookincubator/velox#5277]
### Description

Found fuzzer failure in build with trivial documentation change https://app.circleci.com/pipelines/github/facebookincubator/velox/26939/workflows/f140c78a-d6aa-415f-98ee-5f18bffdcfe0/jobs/170199

### Error Reproduction

I20230615 01:09:42.647145 219765 ExpressionFuzzer.cpp:1357] ==============================> Done with iteration 1655
I20230615 01:09:42.647207 219765 ExpressionFuzzer.cpp:1312] ==============================> Started iteration 1656 (seed: 3635887565)
I20230615 01:09:42.649145 219765 ExpressionVerifier.cpp:79] Executing expression 0 : reverse(coalesce("c0",trim_array(10 elements starting at 105 {null, null, null, null, null, ...},bitwise_right_shift_arithmetic(ceiling(32075),ceiling(32075))),trim_array(10 elements starting at 105 {null, null, null, null, null, ...},bitwise_right_shift_arithmetic(ceiling(32075),ceiling(32075))),trim_array(10 elements starting at 105 {null, null, null, null, null, ...},bitwise_right_shift_arithmetic(ceiling(32075),ceiling(32075))),12 elements starting at 115 {10 elements starting at 1105 {[1105->538] 0.11914267460815609, [1106->1157] null, null, [1108->2966] 0.24127194099128246, [1109->1162] 0.962568299844861, ...}, 19 elements starting at 1115 {[1115->3680] 0.3153136223554611, [1116->2804] null, null, null, null, ...}, 13 elements starting at 1134 {[1134->3354] 0.9721274494659156, [1135->1826] 0.5976221957243979, [1136->563] null, [1137->2693] 0.8075743892695755, [1138->2028] 0.2634472807403654, ...}, 9 elements starting at 1147 {[1147->3543] 0.36391805531457067, [1148->2697] 0.6406117244623601, [1149->381] 0.012656669365242124, [1150->703] 0.37948697386309505, [1151->3856] 0.06157567794434726, ...}, 6 elements starting at 1156 {null, [1157->798] 0.45338503434322774, [1158->851] 0.8015984941739589, [1159->4079] null, [1160->1841] 0.972444819053635, ...}, ...}))
I20230615 01:09:42.649309 219765 ExpressionVerifier.cpp:30] 1 vectors as input:
I20230615 01:09:42.649327 219765 ExpressionVerifier.cpp:32] 	[DICTIONARY ARRAY<ARRAY<DOUBLE>>: 100 elements, 13 nulls], [DICTIONARY ARRAY<ARRAY<DOUBLE>>: 100 elements, 15 nulls], [ARRAY ARRAY<ARRAY<DOUBLE>>: 100 elements, no nulls]
E20230615 01:09:42.653121 219765 Exceptions.h:68] Line: ../../velox/expression/tests/ExpressionVerifier.cpp:60, Function:compareVectors, Expression: left->equalValueAt(right.get(), i, i) Different results at idx '0': '15 elements starting at 0 {[0->14] 7 elements starting at 113 {0.09924193867482245, 0.09924193867482245, 0.09924193867482245, 0.09924193867482245, 0.09924193867482245, ...}, [1->13] null, [2->12] 14 elements starting at 99 {0.09924193867482245, 0.09924193867482245, 0.09924193867482245, 0.09924193867482245, 0.09924193867482245, ...}, [3->11] 2 elements starting at 97 {0.09924193867482245, 0.09924193867482245}, [4->10] 11 elements starting at 86 {0.09924193867482245, 0.09924193867482245, 0.09924193867482245, 0.09924193867482245, 0.09924193867482245, ...}, ...}' vs. '15 elements starting at 0 {null, null, null, null, null, ...}', Source: RUNTIME, ErrorCode: INVALID_STATE
I20230615 01:09:42.654541 219765 ExpressionVerifier.cpp:325] Persisted input: --fuzzer_repro_path /tmp/fuzzer_repro/velox_expressionVerifier_8vWFwY --input_path /tmp/fuzzer_repro/velox_expressionVerifier_8vWFwY/input_vector --result_path /tmp/fuzzer_repro/velox_expressionVerifier_8vWFwY/result_vector --sql_path /tmp/fuzzer_repro/velox_expressionVerifier_8vWFwY/sql --complex_constant_path /tmp/fuzzer_repro/velox_expressionVerifier_8vWFwY/complex_constants
terminate called after throwing an instance of 'facebook::velox::VeloxRuntimeError'
  what():  Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Different results at idx '0': '15 elements starting at 0 {[0->14] 7 elements starting at 113 {0.09924193867482245, 0.09924193867482245, 0.09924193867482245, 0.09924193867482245, 0.09924193867482245, ...}, [1->13] null, [2->12] 14 elements starting at 99 {0.09924193867482245, 0.09924193867482245, 0.09924193867482245, 0.09924193867482245, 0.09924193867482245, ...}, [3->11] 2 elements starting at 97 {0.09924193867482245, 0.09924193867482245}, [4->10] 11 elements starting at 86 {0.09924193867482245, 0.09924193867482245, 0.09924193867482245, 0.09924193867482245, 0.09924193867482245, ...}, ...}' vs. '15 elements starting at 0 {null, null, null, null, null, ...}'
Retriable: False
Expression: left->equalValueAt(right.get(), i, i)
Function: compareVectors
File: ../../velox/expression/tests/ExpressionVerifier.cpp
Line: 60

Stack trace:
 0  _ZN8facebook5velox7process10StackTraceC1Ei
 1  _ZN8facebook5velox14VeloxException5State4makeIZNS1_C4EPKcmS5_St17basic_string_viewIcSt11char_traitsIcEES9_S9_S9_bNS1_4TypeES9_EUlRT_E_EESt10shared_ptrIKS2_ESA_SB_
 2  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
 3  _ZN8facebook5velox17VeloxRuntimeErrorC2EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bS7_
 4  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_
 5  _ZN8facebook5velox4test12_GLOBAL__N_114compareVectorsERKSt10shared_ptrINS0_10BaseVectorEES7_
 6  _ZN8facebook5velox4test18ExpressionVerifier6verifyERKSt6vectorISt10shared_ptrIKNS0_4core10ITypedExprEESaIS8_EERKS4_INS0_9RowVectorEEOS4_INS0_10BaseVectorEEbS3_IiSaIiEE
 7  _ZN8facebook5velox4test16ExpressionFuzzer2goEv
 8  _ZN8facebook5velox4test16expressionFuzzerESt13unordered_mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt6vectorIPKNS0_4exec17FunctionSignatureESaISD_EESt4hashIS8_ESt8equal_toIS8_ESaISt4pairIKS8_SF_EEEm
 9  _ZN12FuzzerRunner3runERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEmRKSt13unordered_setIS5_St4hashIS5_ESt8equal_toIS5_ESaIS5_EES7_
 10 main
 11 __libc_start_main
 12 _start

**Comment by aditi-pandit** [comment]
https://github.com/facebookincubator/velox/pull/5221

**Comment by laithsakka** [comment]
was able to simplify the repo to 
"coalesce"("c0" , "trim_array"(__complex_constant(c1), "bitwise_right_shift_arithmetic"('32075'::SMALLINT, '32075'::SMALLINT)))

looks like a problem in coalesce so far

**Comment by laithsakka** [comment]
actually looks like the problem is in the GenericWriter.

**Comment by laithsakka** [comment]
ensureSize() is downsizing the vector it should not. fix in progerss
