### ISSUE TITLE
Implement inverse_cauchy_cdf prestosql function

### ISSUE THREAD

**Issue by jobbine-joseph** [facebookincubator/velox#5301]
### Description

Add missing function to handle inverse_cauchy_cdf prestosql function.

**Comment by jobbine-joseph** [comment]
@aditi-pandit please assign this issue to me .

**Comment by jobbine-joseph** [comment]
I have raised tenative pr to https://github.com/facebookincubator/velox/pull/5341 covering below test cases for inverse cauchy cdf 

Test Case | Inputs | Expected Output
-- | -- | --
Test Case 1 | 0.0, 1.0, 0.5 | 0.0
Test Case 2 | 0.0, 1.0, 0.75 | 1.0
Test Case 3 | 5.0, 2.0, 1.0 | kInf (Infinity)
Test Case 4 | 5.0, kInf, 0.5 | 5.0
Test Case 5 | 5.0, 2.0, 1.0 | kInf (Infinity)
Test Case 6 | 5.0, kDoubleMax, 0.5 | 5.0
Test Case 7 | 2.5, 1.0, 0.64758361765043326 | 3.0
Test Case 8 | 5.0, 1.0, 0.14758361765043326 | 3.0
Test Case 9 | kNan, 1.0, 0.5 | IsNan() (NaN)
Test Case 10 | 1.0, 1.0, kNan | IsNan() (NaN)
Test Case 11 | kInf, 1.0, kNan | IsNan() (NaN)
Test Case 12 (Exception) | 1.0, kNan, 0.5 | "scale must be greater than 0" (Exception is thrown)
Test Case 13 (Exception) | 0, -1, 0.5 | "scale must be greater than 0" (Exception is thrown)

cc: @skairali@in.ibm.com @Sandhya.Srikumar@ibm.com @ashokku@us.ibm.com

**Comment by jobbine-joseph** [comment]
./velox_expression_fuzzer_test --seed 123456 --duration_sec 60 --logtostderr=1 --minloglevel=0  --only inverse_cauchy_cdf  --v=1 2>&1 | tee fuzzertest.out
I0625 22:11:30.785084 533090 ExpressionVerifier.cpp:53] At 99: [null vs null]
I0625 22:11:30.785089 533090 ExpressionVerifier.cpp:56] ===================
I0625 22:11:30.785109 533090 ExpressionVerifier.cpp:67] All results match.
I0625 22:11:30.785154 533090 ExpressionFuzzer.cpp:1357] ==============================> Done with iteration 13
I0625 22:11:30.785521 533090 ExpressionFuzzer.cpp:1092] ==============================> Top 1 by number of rows processed
I0625 22:11:30.785527 533090 ExpressionFuzzer.cpp:1094] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I0625 22:11:30.785533 533090 ExpressionFuzzer.cpp:1098] inverse_cauchy_cdf 1612 100.00% 56
I0625 22:11:30.785571 533090 ExpressionFuzzer.cpp:1104] ==============================> Bottom 1 by number of rows processed
I0625 22:11:30.785575 533090 ExpressionFuzzer.cpp:1106] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I0625 22:11:30.785578 533090 ExpressionFuzzer.cpp:1111] inverse_cauchy_cdf 1612 100.00% 56
I0625 22:11:30.785583 533090 ExpressionFuzzer.cpp:1124] ==============================> All stats sorted by number of times the function was chosen
I0625 22:11:30.785588 533090 ExpressionFuzzer.cpp:1126] Format: functionName numTimesSelected proportionOfTimesSelected numProcessedRows
I0625 22:11:30.785590 533090 ExpressionFuzzer.cpp:1130] inverse_cauchy_cdf 1612 100.00% 56
[==========] Running 0 tests from 0 test suites.
[==========] 0 tests from 0 test suites ran. (0 ms total)
[  PASSED  ] 0 tests.

**Comment by jobbine-joseph** [comment]
raised pr for this issue https://github.com/facebookincubator/velox/pull/5543

**Comment by yzhang1991** [comment]
> 

Hi @jobbine-joseph, the PR you linked here seems to be for `inverse_laplace_cdf`, not `inverse_cauchy_cdf `

**Comment by jobbine-joseph** [comment]
@yzhang1991 updated it , Thanks for pointing out
