### ISSUE TITLE
Spill and VectorSerializer supports compression

### ISSUE THREAD

**Issue by jinchengchenghh** [facebookincubator/velox#5313]
### Description

Spark would compress data in shuffle serializer and spill, but now `PrestoVectorSerde` and `UnsafeRowVectorSerde` does not support compression.

I find it exists some compression strategy in velox code https://github.com/facebookincubator/velox/blob/main/velox/dwio/dwrf/common/Compression.cpp

And more compression codec support in folly
https://github.com/facebook/folly/blob/main/folly/compression/Compression.h

Does Velox have plan to support this? I can help implement it as you need.

We can compress when `flush` data to `OutputStream`, compress the `ByteStream` data in `PrestoVectorSerializer` and compress the `BufferPtr` in `UnsafeRowVectorSerializer`.

Spark config for compression:
```
  private[spark] val IO_COMPRESSION_CODEC =
    ConfigBuilder("spark.io.compression.codec")
      .doc("The codec used to compress internal data such as RDD partitions, event log, " +
        "broadcast variables and shuffle outputs. By default, Spark provides four codecs: " +
        "lz4, lzf, snappy, and zstd. You can also use fully qualified class names to specify " +
        "the codec")
      .version("0.8.0")
      .stringConf
      .createWithDefaultString("lz4")
```

Wish to your reply! @mbasmanova 
Thanks!

**Comment by FelixYBW** [comment]
How does presto compress the data during shuffle and spill?

**Comment by jinchengchenghh** [comment]
Presto support compression in spill, https://prestodb.io/docs/current/admin/spill.html#spill-compression
Not find compression in shuffle.

**Comment by mbasmanova** [comment]
@jinchengchenghh I do not believe Presto uses compression for shuffle data. Presto-on-Spark does compress shuffle data, but we are seeing that compressing (ZSTD) is 30% of the CPU profile, hence, looking into whether it is worth it. What are your experience with Gluten? How much CPU do you spend on compression / decompression and what are the storage / IO savings you are getting from it? How are you thinking about the balance between using more CPU and less storage? What is the rate of compression are you seeing?

**Comment by FelixYBW** [comment]
@mbasmanova  the issue now is not CPU% but the disk space. Spark may spill TB level data and if customer use local NVME SSDs the space is easily to used. That's why Spark's spill also support compress. We need to do the same in Gluten.

**Comment by FelixYBW** [comment]
To TPCH workload, zstd compression ratio is about 2.6x or 38% of original size.

**Comment by mbasmanova** [comment]
@FelixYBW Thank you for clarifying. Is it accurate to say that you want to apply compression to spill data, not necessarily shuffle data? That makes sense. Feel free to propose a solution. CC: @xiaoxmeng

**Comment by FelixYBW** [comment]
Currently Gluten still uses its own shuffle including the hashing, serializer. The data is compressed by Arrow IPC library eventually. But spill logic totally reuse Velox's. If compress is not planned, @jinchengchenghh may propose one.

**Comment by jinchengchenghh** [comment]
Could you help propose and implement this? Thanks! @zuochunwei

**Comment by jinchengchenghh** [comment]
Currently, the serialized vector binary can be interpreted as Presto `SerializedPage`.
Presto spill only supports lz4 compression with io.airlift.aircompressor algorithm, if support compression in Velox, does Velox needs to support serialized binary same as Presto? In another words, do we need to support serialize in Velox and deserialize in Presto?

I suppose different compressor algorithm hash different implementation, it is hard to be same with java Presto.

If not, I think we can use folly to compress and decompress ByteStream, and add PrestoOptions `compressCodec`.

**Comment by mbasmanova** [comment]
> do we need to support serialize in Velox and deserialize in Presto?

Not for spilling use case.
