### ISSUE TITLE
Round-robin local exchange is slow

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#5324]
### Bug description

Presto queries use lots of round-robin local exchanges:

```
Fragment 5 [SOURCE]
    - LocalExchange[ROUND_ROBIN] ()
        - Aggregate(PARTIAL)[a, c] 
```

These exchanges tend to use significant portion of a fragment's CPU time. In Velox, these exchanges assign individual rows to random partitions, but in Presto Java they assign whole batches / pages. It seems like Velox should also assign whole batches.

CC: @oerling @xiaoxmeng @vermapratyush @miaoever 

### System information

n/a

**Comment by amitkdutta** [comment]
CC: @pranjalssh
