### ISSUE TITLE
Several failed cases on Parquet scan of complex type

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#5454]
### Bug description

We made some tests on the Parquet scan of complex type, and https://github.com/facebookincubator/velox/pull/5451 provides several failed cases. Three of them can be fixed with the change in that PR, and four of them still have incorrect result.

Two kinds of failure were noticed:

- Segment fault in `preloadRepDefs()` due to `wideDefineDecoder_` is used without creation.
- The mismatched `maxDefine_` at [ParquetTypeWithId.cpp#L79](https://github.com/facebookincubator/velox/blob/main/velox/dwio/parquet/reader/ParquetTypeWithId.cpp#L79) causes data missing or extra null value. But a simple adjustment to it cannot adapt to all cases, so we would like to seek your opinions on that.

There are several other failed cases not included, including:

- the key type of map type was struct type
- the value type of map type was array type
- the element type of array type is struct type or array type

### System information

Velox System Info v0.0.2
Commit: 97324ef8965aae279ea4e2f672d93ce6aa58e0b3
CMake Version: 3.16.3
System: Linux-5.4.0-146-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0

**Comment by rui-mo** [comment]
@mbasmanova @Yuhta Would you like to take look on this issue? Thank you.

**Comment by jaystarshot** [comment]
These test cases are being fixed in https://github.com/facebookincubator/velox/pull/9187

**Comment by rui-mo** [comment]
@jaystarshot Thanks!
