### ISSUE TITLE
Support for common super type

### ISSUE THREAD

**Issue by vermapratyush** [facebookincubator/velox#5471]
### Description

NULLIF support for velox only exists when [both arguments have same type](https://github.com/prestodb/presto/blob/189afe0a571d7ee128f242fd803a6098d967861b/presto-native-execution/presto_cpp/main/types/PrestoToVeloxExpr.cpp#L620).

Presto provide utility functions to get the [lowest common super type](https://github.com/prestodb/presto/blob/189afe0a571d7ee128f242fd803a6098d967861b/presto-analyzer/src/main/java/com/facebook/presto/sql/analyzer/FunctionAndTypeResolver.java#L47) (best possible super type) for 2 distinct types. This is used in a number of places within the presto codebase, and also for [nullif](https://github.com/prestodb/presto/blob/189afe0a571d7ee128f242fd803a6098d967861b/presto-main/src/main/java/com/facebook/presto/sql/gen/NullIfCodeGenerator.java#L75). Thus presto is able to support NULLIF even for distinct types.
Presto implements this as a specialForm as it also includes optimisation when the [first argument is null](
https://github.com/prestodb/presto/blob/189afe0a571d7ee128f242fd803a6098d967861b/presto-main/src/main/java/com/facebook/presto/sql/gen/NullIfCodeGenerator.java#L84).

Due to NULLIF being specialForm and lack of common super type in velox, we had to branch within presto codebase  and provide an alternate code path in SqlToRowExpressionTranslator for native queries. Follow up issue: https://github.com/prestodb/presto/issues/20008

Providing support for common super type will help bridge the gap and remove the unnecessary branching in presto codebase.

**Comment by vermapratyush** [comment]
cc @mbasmanova

**Comment by mbasmanova** [comment]
@vermapratyush Just to clarify, are you suggesting to add support for NULLIF special form to Velox? It feels like you are asking for a specific solution (common super type), but it would be better to describe a problem and then look for best solution.

**Comment by vermapratyush** [comment]
@mbasmanova Updated the description with the problem and the impact of the current workaround.

**Comment by mbasmanova** [comment]
For reference, type coercion rules in Presto: com.facebook.presto.type.TypeCoercer#coerceTypeBase

At a high-level, I'm not sure if it makes sense for Velox to implement type coercion and do that in Presto-compatible way. Velox expects the application to resolve types and provide fully resolved and optimized query plans and expressions. It is not also not clear to me that the optimization for first arg of nullif being null is particularly useful.

That said, Prestissimo can implement type coercion compatible with Presto and that would allow to avoid branching the Java code you mentioned.

**Comment by vermapratyush** [comment]
That makes sense. I will close this issue and continue the discussion in presto https://github.com/prestodb/presto/issues/20008

**Comment by mbasmanova** [comment]
FYI, expression evaluation in Velox already has optimization for nulls, which would apply to the expression that NULLIF is being translated to: https://facebookincubator.github.io/velox/develop/expression-evaluation.html#handling-nulls
