### ISSUE TITLE
Migrate more Presto functions to new framework

### ISSUE THREAD

**Issue by leoluan2009** [facebookincubator/velox#549]
Hi team, do we need to migrate more Presto functions such as arithmetic and comparison functions to new framework just like [487](https://github.com/facebookincubator/velox/pull/487) for String functions? If yes, I'll happy to take the task.

**Comment by mbasmanova** [comment]
@leoluan2009 You are welcome to help. CC: @pedroerp

**Comment by pedroerp** [comment]
Yes, help on that would be great :)

**Comment by jijufb** [comment]
@leoluan2009 You are welcome and excited to see the impact you and team are planning with this collaboration.

**Comment by pedroerp** [comment]
Functions have all been migrated. Closing it.
