### ISSUE TITLE
Static assert in HashStringAllocator::freeListIndex

### ISSUE THREAD

**Issue by karteekmurthys** [facebookincubator/velox#5514]
### Bug description

Hitting this issue in [velox/common/memory/HashStringAllocator.cpp](https://github.com/facebookincubator/velox/blob/main/velox/common/memory/HashStringAllocator.cpp#L278):
```
Static assertion failed due to requirement 'sizeof (freeListSizes_) == sizeof(xsimd::batch<int, xsimd::neon64>)'
```

### System information

M1 Mac.

**Comment by karteekmurthys** [comment]
cc: @mbasmanova

**Comment by ankitsultana** [comment]
Seeing the same issue. Looks like this is coming from a [commit yesterday](https://github.com/facebookincubator/velox/commit/722380ee521c46a8b2ca4bea132ab0e3cf898f57).

`sizeof(xsimd::batch<int32_t>)` is 16 whereas `sizeof (freeListSizes_)` is 32.

**Comment by mbasmanova** [comment]
CC: @oerling
