### ISSUE TITLE
TEXTFILE Reader Support

### ISSUE THREAD

**Issue by Yuhta** [facebookincubator/velox#5523]
### Description

In order to read TEXTFILE, we need the following
1. TEXTFILE Reader (merged, no OSS version this half)
2. Table Schema passed from coordinator (https://github.com/prestodb/presto/pull/19924)
3. Make sure Hive connector can handle tables that does not support filter pushdown (#5310)
4. Fix `HiveTypeParser` to handle `VARCHAR` length, which is used in data column types in the query plan (#5360)
5. Fix validation when filter pushdown is disabled (#5614)
6. #5726

**Comment by mbasmanova** [comment]
CC: @vermapratyush

**Comment by zacw7** [comment]
All planned items have been landed.
