### ISSUE TITLE
Window frame offset of zero unsupported in prestissimo

### ISSUE THREAD

**Issue by pramodsatya** [facebookincubator/velox#5529]
### Bug description

Window frames of type k PRECEDING and k FOLLOWING are expected to have a non negative value for k in Presto. Velox expects k to be greater than 1 for such window frames.
Bug detected while running the query from testWindowFrames (presto-tests/src/main/java/com/facebook/presto/tests/AbstractTestWindowQueries.java) with presto-native workers.

### System information

Velox System Info v0.0.2
Commit: 3cc8d681e776756f936e4decc7d8302290762cc8
CMake Version: 3.26.4
System: Darwin-22.5.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 14.0.3.14030022
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 14.0.3.14030022
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.26.4;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

### Relevant logs

java.lang.reflect.InvocationTargetException
 Caused by: java.lang.RuntimeException: offsets[i] >= 1 (0 vs. 1) k in frame bounds must be at least 1
 ... 32 more
 Caused by: VeloxUserError: offsets[i] >= 1 (0 vs. 1) k in frame bounds must be at least 1

**Comment by mbasmanova** [comment]
CC: @aditi-pandit @zacw7

**Comment by mbasmanova** [comment]
CC: @vermapratyush
