### ISSUE TITLE
Error in transform function: Unexpected element type: BIGINT. Expected: VARCHAR

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#5536]
### Bug description

```
assertQuery("SELECT transform(zip(array[orderkey], array[comment]), x -> x[2]) FROM orders");

transform := transform(zip(ARRAY(orderkey), ARRAY(comment)), (expr) -> DEREFERENCE(expr, INTEGER'1')) (1:73)

Caused by: VeloxRuntimeError: elements_->type()->kindEquals(type->childAt(0)) Unexpected element type: BIGINT. Expected: VARCHAR presto.default.transform(presto.default.zip(presto.default.array_constructor(orderkey), presto.default.array_constructor(comment)), (expr) -> (expr)). Input data: /tmp/velox_vector_irhypc. SQL expression: /tmp/velox_sql_BmtWgP. All SQL expressions: /tmp/velox_allExprSql_kbZdSO.
```

CC: @vermapratyush @zacw7 

### System information

n/a

**Comment by mbasmanova** [comment]
'transform' function is applied to a array(row(bigint, varchar)) with a dereference lambda x[2]:

```
{
  "@type": "special",
  "arguments": [
    {
      "@type": "variable",
      "name": "expr",
      "type": "row(bigint,varchar(79))"
    },
    {
      "@type": "constant",
      "type": "integer",
      "valueBlock": "CQAAAElOVF9BUlJBWQEAAAAAAQAAAA==" <--- This is constant 1. Zero-based index of the field in a struct.
    }
  ],
  "form": "DEREFERENCE",
  "returnType": "varchar(79)",
}
```

> "type": "row(bigint,varchar(79))"

This struct doesn't have field names, they are all empty strings. Expression converter in Prestissimo converts field index (1) into field name (empty string) and ends up creating FieldAccessTypedExpr with field name that's ambitious. At runtime, FieldReference expressions picks "first" field with matching name. This happens to be the first field, whose type is BIGINT. Hence, we end up creating a vector of BIGINT instead of VARCHAR and run into a type check later.

```
TypedExprPtr convertDereferenceExpr(
    const velox::TypePtr& returnType,
    const std::vector<TypedExprPtr>& args) {
  VELOX_USER_CHECK_EQ(args.size(), 2);

  const auto& input = args[0];
  VELOX_USER_CHECK_EQ(input->type()->kind(), TypeKind::ROW);
  const auto& inputType = input->type()->asRow();

  // First argument is a struct. Second argument is a constant integer
  // zero-based index of the subfield in the struct.

  auto childIndexExpr = dynamic_cast<const ConstantTypedExpr*>(args[1].get());
  VELOX_USER_CHECK_NOT_NULL(
      childIndexExpr,
      "Second argument for dereference special form must be a constant integer");

  auto childIndex = childIndexExpr->value().value<int32_t>();

  VELOX_USER_CHECK_LT(childIndex, inputType.size());
  auto childName = inputType.names()[childIndex];

  return std::make_shared<FieldAccessTypedExpr>(returnType, input, childName);
}

  int32_t index(const EvalCtx& context) {
    if (index_ != -1) {
      return index_;
    }
    auto* rowType = dynamic_cast<const RowType*>(context.row()->type().get());
    VELOX_CHECK(rowType, "The context has no row");
    index_ = rowType->getChildIdx(field_);
    return index_;
  }
```

**Comment by mbasmanova** [comment]
It seems that we need to change FieldAccessTypedExpr to specify field by index, not by name.

```
/// Represents one of two things:
///     - a leaf in an expression tree specifying input column by name;
///     - a dereference expression which selects a subfield in a struct by name.
class FieldAccessTypedExpr : public ITypedExpr {
 public:
  /// Used as a leaf in an expression tree specifying input column by name.
  FieldAccessTypedExpr(TypePtr type, std::string name)
      : ITypedExpr{std::move(type)},
        name_(std::move(name)),
        isInputColumn_(true) {}

  /// Used as a dereference expression which selects a subfield in a struct by
  /// name.
  FieldAccessTypedExpr(TypePtr type, TypedExprPtr input, std::string name)
      : ITypedExpr{std::move(type), {std::move(input)}},
        name_(std::move(name)),
        isInputColumn_(dynamic_cast<const InputTypedExpr*>(inputs()[0].get())) {
  }
```

**Comment by mbasmanova** [comment]
CC: @bikramSingh91 @laithsakka @kagamiori

**Comment by mbasmanova** [comment]
This bug can cause incorrect results as well:

```
 SELECT transform(array[row(orderkey, orderkey * 10)], x -> x[2]) FROM orders WHERE orderkey < 10

not equal
Actual rows (up to 100 of 7 extra rows shown, 7 rows in total):
    [[1]]
    [[2]]
    [[3]]
    [[4]]
    [[5]]
    [[6]]
    [[7]]
Expected rows (up to 100 of 7 missing rows shown, 7 rows in total):
    [[10]]
    [[20]]
    [[30]]
    [[40]]
    [[50]]
    [[60]]
    [[70]]


SELECT transform(array[row(orderkey, comment)], x -> x[2]) FROM orders

Caused by: VeloxRuntimeError: elements_->type()->kindEquals(type->childAt(0)) Unexpected element type: BIGINT. Expected: VARCHAR presto.default.transform(presto.default.array_constructor(row_constructor(orderkey, comment)), (expr) -> (expr)). 
```

**Comment by laithsakka** [comment]
do we want to change it or support both modes, I feel like moving to index might be a big change

**Comment by mbasmanova** [comment]
>  I feel like moving to index might be a bigger change

It might be indeed... Supporting both modes is error prone though. 

What would you suggest?

**Comment by laithsakka** [comment]
to unblock for now this would it make sense for presto to name the field of the struct nested in the array? or use  a row cast explicit to do the renaming int he query. @mbasmanova

**Comment by Yuhta** [comment]
If index is provided to the ctor of `FieldAccessTypedExpr`, we use index as it's less ambiguous; otherwise we know the struct type and name, we can infer the index like we did before during construction of `FieldAccessTypedExpr`

**Comment by Yuhta** [comment]
The only place it is a little harder is top level field, where we are not getting the struct type (`inputs()[0]->type()`)

**Comment by kevinwilfong** [comment]
We have a lot of special handling for Field References, but it looks like that's just for top level fields.

Could we not just extend the subscript operator to work on RowTypes? Since there's no way to refer to the top level row as a field, there's no risk of accessing a top level field through the subscript operator in a way that avoids this special handling.

**Comment by kevinwilfong** [comment]
Something like, we add a constructor to FieldAccessTypedExpr that takes the an index instead of a field name, and enforces that it's not a top level field (the input is not an InputAccessTypedExpr).  There are places where we assume all we need is the fieldName from FieldAccessTypedExpr today, so creating a new FieldSubscriptTypedExpr might be safer, although the code would be very similar.  There might be a path to eventually phasing out FieldAccessTypedExpr for subfields, and only using it for top level field access (if a FieldAccessTypedExpr accesses a subfield, we have the type of the struct, so we can always get the field index).  In the meantime we can also make a check in FieldAccessTypedExpr/FieldReference that verifies the incoming type (if it's not a top level field) has distinct names if the index is not provided.

Both FieldSubscriptTypedExpr (if we create it) and FieldAccessTypedExpr can compile down to FieldReference which already has support for index (but we only set it at runtime today).

**Comment by mbasmanova** [comment]
I believe this is done.
