### ISSUE TITLE
Respect column name in Parquet writer

### ISSUE THREAD

**Issue by Yohahaha** [facebookincubator/velox#5577]
### Description

Current implementation of parquet writer use exportToArrow with RowVector's rowType to construct ArrowSchema, and Type::name will be write to parquet schema as column name, It would bring wrong parquet schema.

Suppose we have tables and sqls like below
```
create table stu(id int, name varchar);
create table stu_distinct like stu;

insert into stu_distinct as select t1.id, t1.name from stu as t1, stu as t2 where t1.name == t2.name;
```
most optimizer will use alias or unique expr id to distinguish `name` field, and Velox may write parquet file with
```
message schema {
  optional int32 t1.id;
  optional binary t2.id (STRING);
}
```
then if we want run `select id, name from stu_distinct`, it will return all nulls, cause Velox will check field name between outputType and fileType
https://github.com/facebookincubator/velox/blob/14dd4fc2b1420e67a1c86bb50dbf459675a6baa2/velox/connectors/hive/HiveDataSource.cpp#L539-L541

### Solution
Pass RowType to parquet writer and let it be parsed as ArrowSchema.

**Comment by Yohahaha** [comment]
How does community feel about this? CC @Yuhta @majetideepak

**Comment by Yuhta** [comment]
Yes I think it's a bug and we should fix it in parquet writer

**Comment by Yohahaha** [comment]
already fixed by https://github.com/facebookincubator/velox/pull/6074
