### ISSUE TITLE
cast(double as varchar) doesn't match Presto

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#5594]
### Bug description

The implementation of cast(double as varchar) doesn't match Presto. 

In Presto, cast(1.0 as varchar) returns "1.0", but in Velox - "1". This causes result mismatch for Prestissimo queries.

```
 SELECT cast(1.0 * nationkey as varchar) FROM nation

Actual rows (up to 100 of 25 extra rows shown, 25 rows in total):
    [0]
    [1]
    [2]
  
Expected rows (up to 100 of 25 missing rows shown, 25 rows in total):
    [0.0]
    [1.0]
    [2.0]
```

CC: @kagamiori @vermapratyush @bikramSingh91 @laithsakka @kevin

### System information

n/a

**Comment by duanmeng** [comment]
@mbasmanova This should be because Velox parses "1.0" as a `DoubleType` and loses the *precision* (`.0`), while Presto parses it as a `Decimals`, which seems to not exist in Velox yet.

**Comment by mbasmanova** [comment]
CC: @majetideepak

**Comment by majetideepak** [comment]
@mbasmanova in the context of Velox, `1.0` is parsed as a double by default. You need to specify `parseDecimalAsDouble=false` to parse as a decimal.  See https://github.com/facebookincubator/velox/blob/main/velox/exec/tests/PlanNodeToStringTest.cpp#L655 
Unfortunately, the non-decimal tests expect double and the decimal tests expect a decimal.

On the Prestissimo side, I see the issue with
```
> SELECT cast(1.0 * nationkey as varchar) FROM nation
 _col0 
-------
 0     
 10    
 20    
 30    
 .....
 .....
(25 rows) 
```

Decimal cast to Varchar is currently broken. I will fix it after https://github.com/facebookincubator/velox/pull/5534 lands.

**Comment by mbasmanova** [comment]
@majetideepak Deepak, thank you for helping to look into this. Looking forward to a fix.

**Comment by bikramSingh91** [comment]
@majetideepak This is being encountered internally and needs a fix quickly, I have one ready, do you mind if I take this off your plate?

**Comment by majetideepak** [comment]
@bikramSingh91 please go ahead!
