### ISSUE TITLE
Decimal function signature result type computed by integer argument

### ISSUE THREAD

**Issue by jinchengchenghh** [facebookincubator/velox#5598]
### Description

Currently, Velox only supports to compute result precision and scale by decimal input argument, but for Spark function `round(decimal, scale)`, the result type depends on the second argument `scale`, how can we solve this?
```
  inline static std::pair<uint8_t, uint8_t> computeResultPrecisionScale(
      const uint8_t aPrecision,
      const uint8_t aScale,
      const ExtraParams& extraParams) {
    constexpr int32_t kDefaultScale = 0;
    int32_t scale = extraParams.params.round.decimal.has_value()
        ? extraParams.params.round.decimal.value()
        : 0;
    const auto& integralLeastNumDigits = aPrecision - aScale + 1;
    if (scale < 0) {
      const auto& newPrecision = std::max(integralLeastNumDigits, -aScale + 1);
      return {std::min(newPrecision, 38), 0};
    } else {
      return {
          std::min(
              static_cast<int32_t>(
                  integralLeastNumDigits +
                  std::min(static_cast<int32_t>(aScale), scale)),
              38),
          std::min(static_cast<int32_t>(aScale), scale)};
    }
  }
```

```
exec::FunctionSignatureBuilder()
          .integerVariable("a_precision")
          .integerVariable("a_scale")
          .integerVariable(
              "r_precision",
              "min(a_precision - a_scale + 1 + min(a_scale, 99), 38)") // The 99
                                                                       // is a
                                                                       // wrong
                                                                       // number,
                                                                       // which
                                                                       // should
                                                                       // be the
                                                                       // second
                                                                       // integer
                                                                       // argument,
                                                                       // how
                                                                       // can we
                                                                       // represent
                                                                       // this
                                                                       // signature?
          .integerVariable("r_scale", "min(a_scale, 99)") // same as above 99
          .returnType("DECIMAL(r_precision, r_scale)")
          .argumentType("DECIMAL(a_precision, a_scale)")
          .constantArgumentType("integer")
          .build()
```

Do you have some suggestions? @majetideepak 

Relevant PR: https://github.com/facebookincubator/velox/pull/5597

**Comment by jinchengchenghh** [comment]
Can we support `constantArgumentType("integer(b_scale)")` or `constantArgumentType("integer", "b_scale")`?

**Comment by jinchengchenghh** [comment]
Do you have any suggestions? Thanks! @mbasmanova

**Comment by mbasmanova** [comment]
I think it is not possible to define this as a function. It needs to be a special form (like cast).

**Comment by jinchengchenghh** [comment]
Yes, I think it can be a FunctionCallToSpecialForm(like row_constructor).
The following function `resolveTypeForSpecialForm` should add an argument `const std::shared_ptr<const core::CallExpr>& expr`, and revoke `eval` to get the input `scale`
```
TypePtr resolveTypeForSpecialForm(
    const std::string& functionName,
    const std::vector<TypePtr>& argTypes) {
```

```
TypePtr resolveType(
    const std::vector<std::shared_ptr<const core::ITypedExpr>>& inputs,
    const std::shared_ptr<const core::CallExpr>& expr,
    bool nullOnFailure) {

  std::vector<TypePtr> inputTypes;
  inputTypes.reserve(inputs.size());
  for (auto& input : inputs) {
    inputTypes.emplace_back(input->type());
  }

  if (auto resolvedType = exec::resolveTypeForSpecialForm(
          expr->getFunctionName(), inputTypes)) {
    return resolvedType;
  }
}
```

**Comment by mbasmanova** [comment]
@jinchengchenghh I'm curious where would you use resolveTypeForSpecialForm logic? In tests, when parsing SQL strings, or somewhere else?

**Comment by jinchengchenghh** [comment]
I only find the usage in https://github.com/facebookincubator/velox/blob/main/velox/functions/tests/FunctionRegistryTest.cpp#L528, I can have a try to mark `resolveType` as `VELOX_FAIL("CAST expressions do not support type resolution.");` like cast. Thanks for your advice.

**Comment by jinchengchenghh** [comment]
Here we will resolve type, https://github.com/facebookincubator/velox/blob/main/velox/parse/TypeResolver.cpp#L89
We will use this inputs to generate result type for Expr https://github.com/facebookincubator/velox/blob/main/velox/parse/Expressions.cpp#L112 when parsing SQL.

**Comment by majetideepak** [comment]
@jinchengchenghh, @mbasmanova I was reviewing #5441 and spent some time thinking about the issue here.
If the argument is a constant, then something like `constantArgumentType("integer", "b_scale")` proposed above should help here. Why would it not work?

**Comment by jinchengchenghh** [comment]
When we bind the signature, we should get the integer value, but we cannot get this value by `const TypePtr& actualType`, now we get from `core::TypedExprPtr input` by specialForm, https://github.com/facebookincubator/velox/pull/5597/files#diff-eac35f6f71f4d48a5603fa4ebe182c42d18202eea76f8b5a105ce6612163afe0R45

**Comment by majetideepak** [comment]
@jinchengchenghh Can you list here all the Spark decimal functions and expressions that require a special form in Velox? Thanks.

**Comment by jinchengchenghh** [comment]
Only `make_decimal` and  `decimal_round` require a special form. I'm not sure if there is other functions that require a special form.

**Comment by mbasmanova** [comment]
> Only `make_decimal` and `decimal_round` require a special form. 

Looks like these a "special" because they have a Type parameter. In a way, this is similar to CAST which can be thought of as having a Type parameter (toType). Maybe we could extend function API to allow for Type parameters. These would be passed to function's constructor only.

> I'm not sure if there is other functions that require a special form.

Would you go over Spark functions to see if you can spots anything else?

**Comment by jinchengchenghh** [comment]
Most of the Spark decimal Expressions are listed here, https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/decimalExpressions.scala and https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/mathExpressions.scala.

`RoundCeil` and `RoundFloor` is the similar case. https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/mathExpressions.scala#L322

**Comment by jinchengchenghh** [comment]
`make_decimal` argument is toType, but `decimal_round` needs the input argument `scale` to compute the real `toType` https://github.com/facebookincubator/velox/pull/5597/files#diff-eac35f6f71f4d48a5603fa4ebe182c42d18202eea76f8b5a105ce6612163afe0R24

**Comment by mbasmanova** [comment]
> decimal_round needs the input argument scale to compute the real toType

We can define decimal_round to take Type argument instead of scale and have the query planner convert scan to Type.

**Comment by rui-mo** [comment]
Hi @mbasmanova @majetideepak, I'm taking over the pulls requests from @jinchengchenghh when she is unavailable. I took a look at https://github.com/facebookincubator/velox/pull/5597 and https://github.com/facebookincubator/velox/pull/5441, and found the common issue needs to be addressed was how to get the result type from integer inputs. 
In current implementation, it looks tricky to me by extracting the integer value from cast expression and create the return type with it ([link](https://github.com/facebookincubator/velox/pull/5597/files#diff-eac35f6f71f4d48a5603fa4ebe182c42d18202eea76f8b5a105ce6612163afe0R43-R64)). Given the return types of both `decimal_round` and `make_decimal_by_unscaled_value` can be easily got in Gluten, I propose to add an extra argument for them. This argument could be a ConstantTypedExpr with null value, and in `resolveType(const std::vector<TypePtr>& argTypes)` of special form, the return type can be easily decided with it.
> We can define decimal_round to take Type argument instead of scale.

Seems Velox does not support taking type as argument, so I assume ConstantTypedExpr could be more proper. How do you think? Thanks.

**Comment by mbasmanova** [comment]
@rui-mo Rui, it seems to me that Spark has more special forms than Velox. I consider decimal_round and make_decimal_by_unscaled_value special forms and not functions because their return type cannot be decided by the input types. These look similar to CAST to me. I further think it is reasonable for Velox to allow applications to register custom special forms. 

An existing registerFunctionCallToSpecialForm API can be used to register special forms for decimal_round and make_decimal_by_unscaled_value. Similar to cals the corresponding FunctionCallToSpecialForm implementations will throw from resolveType since return type cannot be inferred from the input types.

```
TypePtr CastCallToSpecialForm::resolveType(
    const std::vector<TypePtr>& /* argTypes */) {
  VELOX_FAIL("CAST expressions do not support type resolution.");
}
```

I assume constructSpecialForm API can be implemented similar to RowConstructorCallToSpecialForm::constructSpecialForm by making an instance of VectorFunction and passing it to std::make_shared<Expr>.

One wrinkle here is that we won't be able to parse expressions using these special forms in tests easily. We'll have to manually create typed expression trees for evaluation instead of using SQL strings.

**Comment by rui-mo** [comment]
@mbasmanova Masha, thank you for the quick reply.
> Similar to cals the corresponding FunctionCallToSpecialForm implementations will throw from resolveType since return type cannot be inferred from the input types.

Does this mean it won't affect functionality if the return type cannot be inferred from the input types? And the only issue is on tests creation.
If that's the case, I will follow your suggestion to revise these two PRs.

**Comment by mbasmanova** [comment]
@rui-mo You are correct. Velox requires the application to resolve types and provide fully resolved plans and expression trees. Velox assist type resolution by providing access to function signatures, but special forms are "special" and need to be hard-coded at the application level. There is no generic type resolution for special forms. Therefore, like you mentioned above, it is fine if some special forms cannot resolve types based only on inputs (e.g. CAST). The only impact is conveniency in writing tests.
