### ISSUE TITLE
Different Spark version has different function implemention

### ISSUE THREAD

**Issue by jinchengchenghh** [facebookincubator/velox#5620]
### Description

Now gluten supports both Spark3.2 and Spark3.3, most of the function input, result type and implementation are same.

But I find the result type of function `round(decimal, scale)` is different.

Spark3.2 https://github.com/apache/spark/blob/branch-3.2/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/mathExpressions.scala#L1303

```
override lazy val dataType: DataType = child.dataType match {
    // if the new scale is bigger which means we are scaling up,
    // keep the original scale as `Decimal` does
    case DecimalType.Fixed(p, s) => DecimalType(p, if (_scale > s) s else _scale)
    case t => t
  }
```

Spark3.3. and later: https://github.com/apache/spark/blob/b0b12cf3028331c12097f48cc857f4aad0e00d35/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/mathExpressions.scala#L1482
```
override lazy val dataType: DataType = child.dataType match {
    case DecimalType.Fixed(p, s) =>
      // After rounding we may need one more digit in the integral part,
      // e.g. `ceil(9.9, 0)` -> `10`, `ceil(99, -1)` -> `100`.
      val integralLeastNumDigits = p - s + 1
      if (_scale < 0) {
        // negative scale means we need to adjust `-scale` number of digits before the decimal
        // point, which means we need at lease `-scale + 1` digits (after rounding).
        val newPrecision = math.max(integralLeastNumDigits, -_scale + 1)
        // We have to accept the risk of overflow as we can't exceed the max precision.
        DecimalType(math.min(newPrecision, DecimalType.MAX_PRECISION), 0)
      } else {
        val newScale = math.min(s, _scale)
        // We have to accept the risk of overflow as we can't exceed the max precision.
        DecimalType(math.min(integralLeastNumDigits + newScale, 38), newScale)
      }
    case t => t
  }
```

Which version would Velox support?

And can we implement several versions with different name such as `spark32_round` and `spark33_round`? 

Wish for your reply, thanks! @mbasmanova

**Comment by mbasmanova** [comment]
@jinchengchenghh Supporting multiple versions of Spark would be challenging. How would one even find out the full list of differences? Discovering and fixes these one-by-one doesn't seem ideal. We would need to come up with some strategy and code structure first. Feel free to start a document to discuss (1) which versions we want to support; (2) how many functions are in each version; (3) what are the differences between the versions; (4) how we are going to organize the code, documentation and testing; (5) who will be the main people helping review Spark functions.

**Comment by jinchengchenghh** [comment]
CC @FelixYBW

**Comment by jinchengchenghh** [comment]
We support the newest version Spark3.5.
