### ISSUE TITLE
Issues calling reclaimer / arbitrator APIs in single-thread execution

### ISSUE THREAD

**Issue by zhztheplayer** [facebookincubator/velox#5646]
### PR

https://github.com/facebookincubator/velox/pull/5790

Update: All the draft fixes are included in the PR.

### Bug description

There were several issues encountered when we were trying to integrate with the Arbitrator/Reclaimer API with [Gluten](https://github.com/oap-project/gluten) (Spark accelerator backed by Velox).

Issue 1. MemoryPool's capacity got shrunk without setting an arbitrator (Draft fix at https://github.com/oap-project/velox/pull/362/commits/15a0bade347d44fbc620d1e3ae0802648e0ffc39, our fork of Velox)
Issue 2. Allow custom arbitrator implementation (to forward memory reservation / unreservation requests to a outside memory manager, in our case, the Spark memory manager) (Draft fix at https://github.com/oap-project/velox/pull/362/commits/3b704f4ab426369d1c6160d51e6e4cc45f67ed99)

Bug 1. "Executor was not supplied."  (Draft fix at https://github.com/facebookincubator/velox/pull/5647)
Bug 2. Dead lock once throwing error from "MemoryManager::addRootPool(...)" (Draft fix at https://github.com/oap-project/velox/pull/362/commits/11318f2bbd6235d54414ba349ce4396978136287)
Bug 3. Assertion failed, expected "spillPartitionEntry.second->numFiles() > 0" (Draft fix at https://github.com/oap-project/velox/pull/362/commits/94c785ae15d398858b8f8977d71e94a91f5487ea)
Bug 4. Assertion failed, expected "!spillFinalized_" (Draft fix at https://github.com/oap-project/velox/pull/362/commits/8f0cc371962c76bd3a8defa59feaedcd83eae0ba) (the fix may create issue in recursive spill, I am investigating)

To describe our scenario to use Memory::reclaim

1. Single-thread execution (`Task::next`)
2. Will not use shared arbitrator (one thread should not reclaim memory from another)

### System information

Velox System Info v0.0.2
Commit: 9bcdc8333390cbed9b63473f70af1350016efd91
CMake Version: 3.16.3
System: Linux-5.4.0-152-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by zhouyuan** [comment]
CC: @xiaoxmeng

**Comment by xiaoxmeng** [comment]
@zhztheplayer can we schedule a meeting to discuss this? Thanks!

**Comment by zhztheplayer** [comment]
Fixed in https://github.com/facebookincubator/velox/commit/83f6d642720682a7164719bb268dce6f91b20cda.
