### ISSUE TITLE
Stream processing support

### ISSUE THREAD

**Issue by eedalong** [facebookincubator/velox#5664]
### Description

Hi guys, great job on Velox. Inside Meta, XStream is built based on Velox right? I wonder whether you guys have any plan for stream processing support in opensourced Velox?

**Comment by kgpai** [comment]
Hi @eedalong - This would be better suited to a discussion post, rather than an issue. Can you open a discussion about stream support and then close this ?

**Comment by eedalong** [comment]
> Hi @eedalong - This would be better suited to a discussion post, rather than an issue. Can you open a discussion about stream support and then close this ?

No problem Thx.
