### ISSUE TITLE
Can not find simdjson.h when use system simdjson

### ISSUE THREAD

**Issue by Yohahaha** [facebookincubator/velox#5666]
### Problem description

Since PR #5405 force use simdjson.h under ${CMAKE_BINARY_DIR}/_deps/simdjson-src/simdjson, it breaks build when simdjson was already installed.

simdjson in my build machine:
```
# find /usr simdjson | grep simdjson
/usr/local/lib64/libsimdjson.a
/usr/local/lib64/cmake/simdjson
/usr/local/lib64/cmake/simdjson/simdjsonTargets.cmake
/usr/local/lib64/cmake/simdjson/simdjson-config-version.cmake
/usr/local/lib64/cmake/simdjson/simdjson-config.cmake
/usr/local/lib64/cmake/simdjson/simdjsonTargets-release.cmake
/usr/local/lib64/pkgconfig/simdjson.pc
/usr/local/include/simdjson.h
```

Could we use more general way to find simdjson?

CC @assignUser @kgpai 

### System information

Velox System Info v0.0.2
Commit: Not in a git repo.
CMake Version: 3.20.2
System: Linux-5.10.134-14.al8.x86_64
Arch: x86_64
C++ Compiler: /usr/lib64/ccache/c++
C++ Compiler Version: 10.2.1
C Compiler: /usr/lib64/ccache/cc
C Compiler Version: 10.2.1
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by assignUser** [comment]
@Yohahaha I see, the changes `singleheader` include path does not seem to be as universal as assumed... I'd rather like to avoid adding complex logic to deal with this when it can probably be handled via build system commands/settings or simlinking the header... 

For what it's worth the simdjson doc use the bare `#include <simdjson.h>` https://github.com/simdjson/simdjson#quick-start

**Comment by Yohahaha** [comment]
> it can probably be handled via build system commands/settings or simlinking the header...

Use soft symlink can work, but could you give some suggestions about how to use build commands/settings to deal with this path? `SOURCE_DIR ${CMAKE_BINARY_DIR}/_deps/simdjson-src/simdjson`

I think if we have to use `SOURCE_DIR ${CMAKE_BINARY_DIR}/_deps/simdjson-src/simdjson` as simdjson header file search path, maybe add set(simdjson_SOURCE BUNDLED) would more make sense.

**Comment by assignUser** [comment]
I didn't say it explicitly but I think we should revert #5405 and use the bare include path as it is the ,"official" one and the singleheader/... one is more an artifact of the build env when not using cmake.

**Comment by assignUser** [comment]
@kgpai @pedroerp opinions?

**Comment by pedroerp** [comment]
If #5405 breaks the build when simdjson is installed locally, then +1 to revert it. We can find another way to ensure it uses the right one within our monorepo.

If you guys can submit a PR with the change, I can help merge and solve the internal conflict.

**Comment by kgpai** [comment]
cc: @kevinwilfong
