### ISSUE TITLE
Failure Building benchmarks with S3 connector enabled

### ISSUE THREAD

**Issue by paul-amonson** [facebookincubator/velox#5682]
### Problem description

Found the following error on the build command line:

$ make release EXTRA_CMAKE_FLAGS="-DVELOX_BUILD_BENCHAMARKS=ON -DVELOX_ENABLE_S3=ON"
…
FAILED: velox/connectors/hive/storage_adapters/s3fs/benchmark/velox_s3read_benchmark
: && /usr/bin/c++ -mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17 -mbmi2 -D USE_VELOX_COMMON_BASE -D HAS_UNCAUGHT_EXCEPTIONS -Wall -Wextra -Wno-unused        -Wno-unused-parameter        -Wno-sign-compare        -Wno-ignored-qualifiers        -Wno-implicit-fallthrough          -Wno-empty-body          -Wno-class-memaccess          -Wno-comment          -Wno-int-in-bool-context          -Wno-redundant-move          -Wno-array-bounds          -Wno-maybe-uninitialized          -Wno-unused-result
-Wno-format-overflow          -Wno-strict-aliasing          -Wno-type-limits          -Wno-stringop-overflow          -Wno-stringop-overread          -Wno-return-type -Werror -O3 -DNDEBUG -Wl,-export-dynamic velox/connectors/hive/storage_adapters/s3fs/benchmark/CMakeFiles/velox_s3read_benchmark.dir/S3ReadBenchmark.cpp.o velox/connectors/hive/storage_adapters/s3fs/benchmark/CMakeFiles/velox_s3read_benchmark.dir/S3ReadBenchmarkMain.cpp.o velox/connectors/hive/storage_adapters/s3fs/benchmark/CMakeFiles/velox_s3read_benchmark.dir/__/__/__/__/__/__/_deps/simdjson-src/simdjson/singleheader/simdjson.cpp.o -o velox/connectors/hive/storage_adapters/s3fs/benchmark/velox_s3read_benchmark  -lvelox_read_benchmark_lib  velox/connectors/hive/storage_adapters/s3fs/libvelox_s3fs.a  velox/common/base/libvelox_exception.a  velox/exec/tests/utils/libvelox_exec_test_lib.a  /usr/local/lib/libfmt.a  /usr/local/lib/libfolly.a  velox/vector/tests/utils/libvelox_vector_test_lib.a  velox/exec/tests/utils/libvelox_temp_path.a  velox/parse/libvelox_parse_parser.a  velox/duckdb/conversion/libvelox_duckdb_parser.a  velox/parse/libvelox_parse_expression.a  velox/parse/libvelox_parse_utils.a  velox/functions/libvelox_function_registry.a  velox/dwio/common/tests/utils/libvelox_dwio_common_test_utils.a  velox/type/fbhive/libvelox_type_fbhive.a  velox/connectors/hive/storage_adapters/s3fs/libvelox_s3fs.a  /usr/local/lib/libaws-cpp-sdk-s3.a  /usr/local/lib/libaws-cpp-sdk-identity-management.a  /usr/local/lib/libaws-cpp-sdk-cognito-identity.a  /usr/local/lib/libaws-cpp-sdk-sts.a  /usr/local/lib/libaws-cpp-sdk-core.a  /usr/lib/x86_64-linux-gnu/libcurl.so  /usr/local/lib/libaws-crt-cpp.a  /usr/local/lib/libaws-c-mqtt.a  /usr/local/lib/libaws-c-event-stream.a  /usr/local/lib/libaws-c-s3.a  /usr/local/lib/libaws-c-auth.a  /usr/local/lib/libaws-c-http.a  /usr/local/lib/libaws-c-io.a  /usr/local/lib/libs2n.a  /usr/lib/x86_64-linux-gnu/libcrypto.a  /usr/local/lib/libaws-c-compression.a  /usr/local/lib/libaws-c-cal.a  /usr/lib/x86_64-linux-gnu/libcrypto.so  /usr/local/lib/libaws-c-sdkutils.a  /usr/local/lib/libaws-checksums.a  /usr/local/lib/libaws-c-common.a  -lpthread  -lm  -lrt  velox/dwio/dwrf/reader/libvelox_dwio_dwrf_reader.a  velox/dwio/dwrf/writer/libvelox_dwio_dwrf_writer.a  velox/dwio/dwrf/common/libvelox_dwio_dwrf_common.a  velox/dwio/dwrf/utils/libvelox_dwio_dwrf_utils.a  velox/dwio/dwrf/proto/libvelox_dwio_dwrf_proto.a  _deps/protobuf-build/libprotobuf.a  /usr/lib/x86_64-linux-gnu/liblz4.so  /usr/lib/x86_64-linux-gnu/liblzo2.so  /usr/lib/x86_64-linux-gnu/libz.so  velox/dwio/catalog/fbhive/libvelox_dwio_catalog_fbhive.a  velox/dwio/parquet/libvelox_dwio_parquet_reader.a  velox/dwio/parquet/duckdb_reader/libvelox_dwio_duckdb_parquet_reader.a  velox/duckdb/conversion/libvelox_duckdb_conversion.a  velox/external/duckdb/tpch/libtpch_extension.a  velox/duckdb/memory/libvelox_duckdb_allocator.a  velox/dwio/parquet/reader/libvelox_dwio_native_parquet_reader.a  /usr/lib/x86_64-linux-gnu/libzstd.so  /usr/lib/x86_64-linux-gnu/libsnappy.so  velox/dwio/parquet/thrift/libvelox_dwio_parquet_thrift.a  velox/dwio/parquet/libvelox_dwio_parquet_writer.a  velox/dwio/parquet/writer/libvelox_dwio_arrow_parquet_writer.a  velox/dwio/common/libvelox_dwio_common.a  velox/common/caching/libvelox_caching.a  velox/dwio/common/compression/libvelox_dwio_common_compression.a  velox/dwio/common/encryption/libvelox_dwio_common_encryption.a  velox/dwio/common/exception/libvelox_dwio_common_exception.a  third_party/arrow_ep/install/lib/libparquet.a  third_party/arrow_ep/install/lib/libarrow.a  /usr/lib/x86_64-linux-gnu/libthrift.a  velox/connectors/hive/libvelox_hive_partition_function.a  velox/tpch/gen/libvelox_tpch_gen.a  velox/external/duckdb/libduckdb.a  velox/external/duckdb/tpch/dbgen/libdbgen.a  velox/functions/prestosql/registration/libvelox_functions_prestosql.a  velox/functions/prestosql/libvelox_functions_prestosql_impl.a  velox/functions/prestosql/json/libvelox_functions_json.a  velox/external/md5/libmd5.a  velox/functions/prestosql/types/libvelox_presto_types.a  velox/functions/lib/libvelox_is_null_functions.a  velox/functions/prestosql/aggregates/libvelox_aggregates.a  velox/common/hyperloglog/libvelox_common_hyperloglog.a  velox/functions/lib/aggregates/libvelox_functions_aggregates.a  velox/serializers/libvelox_presto_serializer.a  velox/exec/libvelox_exec.a  velox/codegen/libvelox_codegen.a  velox/exec/libvelox_exec.a  velox/codegen/libvelox_codegen.a  velox/common/file/libvelox_file.a  velox/vector/arrow/libvelox_arrow_bridge.a  velox/expression/libvelox_expression.a  velox/core/libvelox_core.a  velox/connectors/libvelox_connector.a  velox/core/libvelox_config.a  velox/expression/libvelox_expression_functions.a  velox/expression/type_calculation/libvelox_type_calculation.a  velox/functions/lib/libvelox_functions_util.a  velox/functions/lib/libvelox_functions_lib.a  velox/vector/libvelox_vector.a  velox/type/libvelox_type.a  velox/common/serialization/libvelox_serialization.a  velox/type/tz/libvelox_type_tz.a  velox/external/date/libvelox_external_date.a  velox/buffer/libvelox_buffer.a  velox/common/memory/libvelox_memory.a  velox/common/testutil/libvelox_test_util.a  velox/common/base/libvelox_common_base.a  velox/common/base/libvelox_exception.a  velox/common/process/libvelox_process.a  /usr/lib/x86_64-linux-gnu/libgflags.so.2.2.2  /usr/lib/x86_64-linux-gnu/libglog.so  lib/libgtest.a  velox/common/time/libvelox_time.a  velox/common/encode/libvelox_encode.a  /usr/local/lib/libfolly.a  /usr/local/lib/libfmt.a  /usr/lib/x86_64-linux-gnu/libboost_regex.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_context.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_filesystem.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_program_options.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_system.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.74.0  /usr/lib/x86_64-linux-gnu/libboost_atomic.so.1.74.0  /usr/lib/x86_64-linux-gnu/libdouble-conversion.so  /usr/lib/x86_64-linux-gnu/libgflags.so.2.2.2  -lpthread  /usr/lib/x86_64-linux-gnu/libglog.so  /usr/lib/x86_64-linux-gnu/libevent.so  /usr/lib/x86_64-linux-gnu/libz.so  /usr/lib/x86_64-linux-gnu/libssl.so  /usr/lib/x86_64-linux-gnu/libcrypto.so  /usr/lib/x86_64-linux-gnu/libbz2.so  /usr/lib/x86_64-linux-gnu/liblzma.so  /usr/lib/x86_64-linux-gnu/liblz4.so  /usr/lib/x86_64-linux-gnu/libzstd.so  /usr/lib/x86_64-linux-gnu/libsnappy.so  /usr/lib/x86_64-linux-gnu/libsodium.so  -ldl  /usr/lib/x86_64-linux-gnu/libunwind.so  /usr/lib/x86_64-linux-gnu/libre2.so  /usr/lib/x86_64-linux-gnu/libre2.so && :
/usr/bin/ld: cannot find -lvelox_read_benchmark_lib: No such file or directory
collect2: error: ld returned 1 exit status
[926/942] Linking CXX executable velox/functions/prestosql/aggregates/benchmarks/velox_aggregates_simple_aggregates_benchmarks
ninja: build stopped: subcommand failed.
make[1]: *** [Makefile:87: build] Error 1
make[1]: Leaving directory '/home/user/workspace'
make: *** [Makefile:94: release] Error 2

I am fixing it as I file this issue.

### System information

Not system dependent.

**Comment by assignUser** [comment]
Closed by #5683
