### ISSUE TITLE
ArrayDistinct does not correctly handle varchar/varbinary

### ISSUE THREAD

**Issue by shiyu-bytedance** [facebookincubator/velox#5697]
### Bug description

Currently, ArrayDistinct UDF is registered to [support varchar/varbinary as input types](https://github.com/facebookincubator/velox/blame/main/velox/functions/prestosql/ArrayDistinct.cpp#L181).

However, ArrayDistinct filters unique values by employing a F14FastSet, which cannot correctly hash "deep" values such as varchar/varbinary, it can only handle POD values.

### System information

n/a

**Comment by shiyu-bytedance** [comment]
cc @mbasmanova who originally implemented this function.

**Comment by mbasmanova** [comment]
@shiyu-bytedance F14FastSet should work fine with StringViews. Do you have a repro that illustrates the problem?
