### ISSUE TITLE
Fast path optimization for all-ascii input does not work for functions with int32 output

### ISSUE THREAD

**Issue by PHILO-HE** [facebookincubator/velox#5792]
### Bug description

As we know, developers can implement a `callAscii` method to do an optimization on all-ascii input for simple functions. It works well for functions with varchar input & varchar output. But if output type is not varchar (e.g, int32 type), I found `callAscii` will NOT be called. With a quick debug, I found the framework's execution will go into an if branch (i.e., `fastPathIteration = true`, see below link), where `callAscii` method will never be called.
https://github.com/facebookincubator/velox/blob/main/velox/expression/SimpleFunctionAdapter.h#L546

### System information

N/A

**Comment by mbasmanova** [comment]
CC: @laithsakka @kagamiori Laith, Wei, would you help look into this?

@PHILO-HE Any chance you could provide a quick repro to help debugging?

**Comment by PHILO-HE** [comment]
> CC: @laithsakka @kagamiori Laith, Wei, would you help look into this?
> 
> @PHILO-HE Any chance you could provide a quick repro to help debugging?

Yes, the proposed `AsciiFunction` may be good to debug: https://github.com/facebookincubator/velox/pull/5020. I just kept the `callAscii` in that PR. And the first test case in `StringTest.Ascii`  can reproduce this issue.
```
gdb --args ./_build/debug/velox/functions/sparksql/tests/velox_functions_spark_test --gtest_filter=StringTest.Ascii
```

**Comment by laithsakka** [comment]
@PHILO-HE  thank you for reporting the issue,
looks like we need to add
```
 if (applyContext.allAscii) {
          applyUdf(applyContext, [&](auto& out, auto row) INLINE_LAMBDA {
              typename return_type_traits::NativeType out{};
          bool notNull = doApplyAsciiNotNull<0>(row, out, readers...);
          });
        } else{...}
   ```
 At line 603 to match the behaviour at line 640,
would you like to give it a try? or shall i put up a fix

**Comment by PHILO-HE** [comment]
Hi @laithsakka, I will try to fix it according to your nice proposed change and will add some tests to cover such cases. Many thanks!
