### ISSUE TITLE
Avoid calculating hash in OrderBy Sort

### ISSUE THREAD

**Issue by Likes123** [facebookincubator/velox#5906]
### Description

Void hash in OrderBy Spilling, because there is just one partition in OrderBy Splling
Spiller::fillSpillRuns
```
  for (;;) {
    auto numRows = container_.listRows(
        &iterator, rows.size(), RowContainer::kUnlimited, rows.data());
    // Calculate hashes for this batch of spill candidates.
    // TODO: Void hash in OrderBy Spilling, because there is just one partition in OrderBy Splling
    auto rowSet = folly::Range<char**>(rows.data(), numRows);
    for (auto i = 0; i < container_.keyTypes().size(); ++i) {
      container_.hash(i, rowSet, i > 0, hashes.data());
    }
	...
  }
```

**Comment by mbasmanova** [comment]
@Likes123 I'm not sure I understand this proposal. Would you clarify a bit? 

CC: @xiaoxmeng

**Comment by Likes123** [comment]
In OrderBy Splling, all data is belong to one partition, so we do not need accumulate hash value of every row.

**Comment by xiaoxmeng** [comment]
@Likes123 yes, we could skip this step if there is single partition.

**Comment by xiaoxmeng** [comment]
https://github.com/facebookincubator/velox/pull/6271 from @tanjialiang adds this optimization

**Comment by tanjialiang** [comment]
optimization is added, closing this issue.
