### ISSUE TITLE
Probably a bug in Unnest::needsInput

### ISSUE THREAD

**Issue by xumingming** [facebookincubator/velox#5956]
### Bug description

I am reading the code of Unnest operator, I noticed that Unnest's needsInput always returns true:

```c++
  bool needsInput() const override {
    return true;
  }
```

and isBlocked always return kNotBlocked:

```c++
  BlockingReason isBlocked(ContinueFuture* /*future*/) override {
    return BlockingReason::kNotBlocked;
  }
```

which means the upstream operator can add input to Unnest at any time, but the implementation of addInput is to hold the input RowVectorPtr into Unnest's private filed: input_:

```c++
void Unnest::addInput(RowVectorPtr input) {
  input_ = std::move(input);
}
```

if `input_` has not been fully processed yet, there is a chance, the not fully processed input been overwrite by new input?

### System information

not relevant.

### Relevant logs

```bash
not relevant.
```

**Comment by mbasmanova** [comment]
I think this works fine. The contract is that Driver must call getOutput after calling addInput. Since getOutput always processes all the input, things work. Feel free to play with this operator and share a repro if you run into a problem.

**Comment by xumingming** [comment]
@mbasmanova Thanks for the confirmation :)
