### ISSUE TITLE
Distinct Aggregation does not support multi-channel aggregates(e.g. covar_pop)

### ISSUE THREAD

**Issue by shiyu-bytedance** [facebookincubator/velox#5972]
### Description

See the sample unit test and error message:

```
TEST_F(CovarianceAggregationTest, distinctWithMultipleColumns) {
  auto data = makeRowVector({
      makeFlatVector<double>({1, 2, 1, 2, 1, 1, 2, 2}),
      makeFlatVector<double>({1, 1, 1, 2, 1, 1, 1, 2}),
  });
  createDuckDbTable({data});

  auto plan = PlanBuilder()
                  .values({data})
                  .singleAggregation(
                      {},
                      {"covar_pop(distinct c0, c1)"})
                  .planNode();
  AssertQueryBuilder(plan, duckDbQueryRunner_)
      .assertResults(
          "SELECT covar_pop(distinct c0, c1) FROM tmp");
}
```
Output:
```
/Users/bytedance/repos/oss_timber_lin_velox/velox/cmake-build-debug/velox/functions/prestosql/aggregates/tests/velox_aggregates_test --gtest_filter=CovarianceAggregationTest.*:CovarianceAggregationTest/*.*:CovarianceAggregationTest.*/*:*/CovarianceAggregationTest.*/*:*/CovarianceAggregationTest/*.* --gtest_color=no
Testing started at 10:07 AM ...
unknown file: Failure
C++ exception with description "Exception: VeloxUserError
Error Source: USER
Error Code: INVALID_ARGUMENT
Reason: (2 vs. 1)
Retriable: False
Expression: aggregate->inputs.size() == 1
Function: create
File: /Users/bytedance/repos/oss_timber_lin_velox/velox/velox/exec/DistinctAggregations.cpp
Line: 149
Stack trace:
Stack trace has been disabled.Use --velox_exception_user_stacktrace=true to enable it.
" thrown in the test body.


Process finished with exit code 1
```

Fix idea:

Augment SetAccumulator's constructor to accept a new parameter "DistinctChannelCount" and create as many `folly::F14FastSet` as `DistinctChannelCount`

@mbasmanova @frankobe @timber-lin

**Comment by mbasmanova** [comment]
@shiyu-bytedance Thank you for reporting this. Images are hard to work with. Would you share plan text of the test and error message as well?

**Comment by shiyu-bytedance** [comment]
> @shiyu-bytedance Thank you for reporting this. Images are hard to work with. Would you share plan text of the test and error message as well?

@mbasmanova Fixed. Would you (because I do not appear to have) have permission to assign this issue to me or @timber-lin? Thank you!

**Comment by mbasmanova** [comment]
@shiyu-bytedance 

Aggregation with 2+ inputs can be considered as an aggregation with a single input if we combine inputs in a struct (ROW). We can then use SetAccumulator<ComplexType> to accumulate distinct structs. 

What do you think?

**Comment by shiyu-bytedance** [comment]
> @shiyu-bytedance
> 
> Aggregation with 2+ inputs can be considered as an aggregation with a single input if we combine inputs in a struct (ROW). We can then use SetAccumulator to accumulate distinct structs.
> 
> What do you think?

I think that sounds great. What about then we do not specialize for this case. Instead, we always lift input/inputs into a struct, even when there's only one. I think that would simplify the code logic, but not sure about the perf hit due to "lift into struct" overhead.

**Comment by mbasmanova** [comment]
@shiyu-bytedance I agree that the code would be simpler if we always wrapped inputs in a struct, but we may loose performance. I think it should not be too difficult to specialize though. See set_agg aggregate function. Feel free to check if perf hit is negligible and if so always wrap.

**Comment by shiyu-bytedance** [comment]
> @shiyu-bytedance I agree that the code would be simpler if we always wrapped inputs in a struct, but we may loose performance. I think it should not be too difficult to specialize though. See set_agg aggregate function. Feel free to check if perf hit is negligible and if so always wrap.

Ok I understand. I will implement this. Thank you!

**Comment by mbasmanova** [comment]
Thank you, @shiyu-bytedance. This will be a nice addition.

**Comment by shiyu-bytedance** [comment]
> Thank you, @shiyu-bytedance. This will be a nice addition.

@mbasmanova Please review PR https://github.com/facebookincubator/velox/pull/6167
