### ISSUE TITLE
PartitionedOutput operator with zero-column output produces incorrect result

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#5976]
### Bug description

PartitionedOutput cannot distinguish between output being identical to input and output having no columns. In both cases it produces the input causing issues downstream.

See https://github.com/prestodb/presto/pull/20381

CC: @aditi-pandit @karteekmurthys 

### System information

n/a

**Comment by aditi-pandit** [comment]
@mbasmanova : Are you planning to add this fix ?

**Comment by karteekmurthys** [comment]
Thanks for the fix @mbasmanova!

**Comment by aditi-pandit** [comment]
@mbasmanova : Just for my understanding : In this case, the PartitionedOutput still needs to send the number of rows. That is sent in the header then ?
