### ISSUE TITLE
Add unscaled_value Spark function

### ISSUE THREAD

**Issue by liujiayi771** [facebookincubator/velox#6012]
### Description

https://github.com/apache/spark/blob/cf64008fce77b38d1237874b04f5ac124b01b3a8/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/decimalExpressions.scala#L30-L49

**Comment by mbasmanova** [comment]
I wonder how this function is used? Would you explain and maybe share some examples?

**Comment by liujiayi771** [comment]
> I wonder how this function is used? Would you explain and maybe share some examples?

In spark, there is an optimizer called DecimalAggregates, which optimizes the decimal sum and avg in window and agg. When the precision meets certain conditions, it uses `unscaled_value` to convert the decimal in sum and avg to long for operation to improve performance. You can check the following code, the code may explain more clearly.

https://github.com/apache/spark/blob/13732922cca4d03de216d0ad2264ec9212fb63b7/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/optimizer/Optimizer.scala#L2105-L2137

**Comment by mbasmanova** [comment]
@liujiayi771 Thank you for explaining. I wonder if this optimization is needed when using Velox. It seems that sum and average functions can implement this optimization on their own without any help from the optimizer.

**Comment by liujiayi771** [comment]
> @liujiayi771 Thank you for explaining. I wonder if this optimization is needed when using Velox. It seems that sum and average functions can implement this optimization on their own without any help from the optimizer.

We cannot change Spark so that it does not use DecimalAggregates to modify the execution plan. From the perspective of Velox, what it receives is the avg and sum of long. On the Velox side, it will not receive decimal that can be converted to long. We can only implement the `unscaled_value` function to adapt to Spark's optimization.
