### ISSUE TITLE
Partial aggregation flushes in a low-cardinality case

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#6035]
### Description

When running TPC-DS query q67, we found partial aggregation flushes a lot in a low-cardinality case.

Some stats:
Partial aggregation:
number of input rows: 486,013,077
**number of output rows: 486,010,397**
Final aggregation:
number of output rows: 49,144,036

The reason is `100 * numOutput / numInputRows_ >= abandonPartialAggregationMinPct_` is satisfied in partial aggregation nearly from the beginning to end. Below are some printed logs.
```
numOutput: 4003, numInputRows_: 4004, ratio: 99
numOutput: 4003, numInputRows_: 4004, ratio: 99
numOutput: 7937, numInputRows_: 8008, ratio: 99
numOutput: 7937, numInputRows_: 8008, ratio: 99
numOutput: 11871, numInputRows_: 12012, ratio: 98
numOutput: 11871, numInputRows_: 12012, ratio: 98
numOutput: 11871, numInputRows_: 12012, ratio: 98
numOutput: 4019, numInputRows_: 4019, ratio: 100
numOutput: 4019, numInputRows_: 4019, ratio: 100
numOutput: 7958, numInputRows_: 8038, ratio: 99
numOutput: 7958, numInputRows_: 8038, ratio: 99
numOutput: 11897, numInputRows_: 12057, ratio: 98
numOutput: 11897, numInputRows_: 12057, ratio: 98
numOutput: 11897, numInputRows_: 12057, ratio: 98
......
```
But if we delay this check for some time (by adding a min memory limit for flush), the ratio becomes closer to the actual case, and flushing is reduced a lot.

```
numOutput: 4003, numInputRows_: 4004, ratio: 99
numOutput: 7937, numInputRows_: 8008, ratio: 99
numOutput: 11871, numInputRows_: 12012, ratio: 98
numOutput: 15805, numInputRows_: 16016, ratio: 98
numOutput: 19739, numInputRows_: 20020, ratio: 98
numOutput: 20494, numInputRows_: 24024, ratio: 85
numOutput: 20600, numInputRows_: 28028, ratio: 73
numOutput: 20611, numInputRows_: 32032, ratio: 64
numOutput: 20612, numInputRows_: 36036, ratio: 57
numOutput: 24605, numInputRows_: 40029, ratio: 61
......
```
This is the stats after change.

Partial aggregation:
number of input rows: 486,013,077
**number of output rows: 67,671,731**
Final aggregation:
number of output rows: 49,144,036

The performance of this query is improved, from **70s** to **52s** on 100GB dataset. The performance improvement is larger on 1TB dataset.

In total, we need to make aggregation flush only in a high-cardinality case if memory allows. Otherwise, the advantage of partial aggregation cannot be fully taken.

**Comment by mbasmanova** [comment]
@rui-mo Can the same be achieved by tuning abandonPartialAggregationMinRows_ config? The default is 10'000, but perhaps, 100'000 would work better?

**Comment by rui-mo** [comment]
@mbasmanova Thank you. I tried it locally and found it works. We just ignored this config during code rebase. Sorry for the inconvenience.
