### ISSUE TITLE
[Native] - problem in casting varchar type column into  varchar(3) against c++ worker

### ISSUE THREAD

**Issue by mknegi** [facebookincubator/velox#6060]
### Bug description

There is a problem in casting between varchar type columns (with different lengths) in Prestissimo. 

In the following SQL the input is a varchar[8] type column cast into  varchar(3) and C++ worker returns incorrect results. This works correctly in Presto.

`presto:tpch> select cast(varchar_value as varchar(3)) from (values ('9898.122')) t(varchar_value);`
  _col0
----------
 9898.122
Note:-> This is incorrect output. The correct result should be 989

### System information

Velox System Info v0.0.2
Commit: fb5afdc532f3248b49302a4bdf0dbe406903882b
CMake Version: 3.26.4
System: Darwin-22.4.0
Arch: x86_64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 14.0.3.14030022
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 14.0.3.14030022
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr;/usr/local;/usr;/;/usr/local/Cellar/cmake/3.26.4;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by mbasmanova** [comment]
HI @mknegi, I see you are filing lots of issues. Curious where are you from and what are trying to do. Velox is all C++, unlike Presto which is a mix of Java and C++. Hence, it is redundant to include [native] prefix to Velox issues. I wonder if you meant to submit these issues to Presto instead. Looking forward to hearing from you.

**Comment by aditi-pandit** [comment]
> HI @mknegi, I see you are filing lots of issues. Curious where are you from and what are trying to do. Velox is all C++, unlike Presto which is a mix of Java and C++. Hence, it is redundant to include [native] prefix to Velox issues. I wonder if you meant to submit these issues to Presto instead. Looking forward to hearing from you.

@mbasmanova : Manoj is from IBM. We are getting these issues from running tests in presto-product-tests Presto module against Prestissimo. We want to establish that as a baseline for Presto/Prestissimo product tests in the build.

**Comment by mbasmanova** [comment]
@aditi-pandit Got it. Thank you for the context. Would it make sense to file these issues in the GitHub repo? Ideally, issues in Velox repo would be described in Velox terms and include a repro that can run with Velox alone.

**Comment by aditi-pandit** [comment]
@mbasmanova : Yes, the way the issue is described is more appropriate for Prestissimo than Velox. 

We has debugged this a bit and felt the issue is in Velox CastExpr, so filed it here. 

But you are right that without a Velox repro there isn't context. Will ask Manoj to file the issues in Presto github instead.

**Comment by mbasmanova** [comment]
@aditi-pandit Thanks.

**Comment by aditi-pandit** [comment]
Tracking this issue in Presto project https://github.com/prestodb/presto/issues/20847
