### ISSUE TITLE
Flaky test MultiFragmentTest.exchangeStatsOnFailure

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#6061]
### Bug description

https://app.circleci.com/pipelines/github/facebookincubator/velox/31064/workflows/aaa7fed9-3c84-444c-9ce9-bef5a8cc9e42/jobs/196194

### System information

n/a

**Comment by pansatadru** [comment]
Fixed with https://github.com/facebookincubator/velox/pull/11094
