### ISSUE TITLE
[Native] - Problem accessing different fields of a structure type data in c++ worker

### ISSUE THREAD

**Issue by mknegi** [facebookincubator/velox#6062]
### Bug description

There seems to be a problem in accessing different fields of a structure type data in c++ worker as shown by the output of the following query:
Query: 
SELECT r[2] FROM (VALUES (ROW (ROW (1, 'a', true)))) AS v(r)

Returns following error:
VeloxUserError: childIndex == inputType.getChildIdx(childName) (1 vs. 0) Cannot map field index to name in dereference expression: 1. Input struct may have duplicate or empty field names: ROW<"":INTEGER,"":VARCHAR,"":BOOLEAN>.

The expected output was 'a'
We can fetch the first field of the resultant row type data here:
presto:tpch> SELECT r[1] FROM (VALUES ROW(ROW(1, 'a', true)) ) AS v(r);
 _col0
-------
   1
(1 row)

### System information

Velox System Info v0.0.2
Commit: fb5afdc532f3248b49302a4bdf0dbe406903882b
CMake Version: 3.26.4
System: Darwin-22.4.0
Arch: x86_64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 14.0.3.14030022
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 14.0.3.14030022
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr;/usr/local;/usr;/;/usr/local/Cellar/cmake/3.26.4;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by mbasmanova** [comment]
This issue is being tracked in https://github.com/facebookincubator/velox/issues/5536

**Comment by mbasmanova** [comment]
Let's close this issue and consolidate the discussion in https://github.com/facebookincubator/velox/issues/5536
