### ISSUE TITLE
CMake Error building on Apple M1

### ISSUE THREAD

**Issue by dulvinw** [facebookincubator/velox#6090]
### Problem description

I'm getting the following error trying to build velox using the following command.

`export INSTALL_PREFIX=/Users/duwi/velox/velox_dependency_install`
`CPU_TARGET="arm64" ./scripts/setup-macos.sh`
`CPU_TARGET="aarch64" make`

### System information

Velox System Info v0.0.2
Commit: 0cf31a0ddb62dfffa3c6aa1386cc333240961f4a
CMake Version: 3.27.2
System: Darwin-22.5.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 14.0.3.14030022
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 14.0.3.14030022
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.27.2;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

### CMake log

```bash
CMake Error at CMake/resolve_dependency_modules/re2.cmake:38 (if):
  if given arguments:

    "STREQUAL" "BUNDLED"

  Unknown arguments specified
Call Stack (most recent call first):
  CMake/ResolveDependency.cmake:43 (include)
  CMake/ResolveDependency.cmake:75 (build_dependency)
  CMakeLists.txt:382 (resolve_dependency)
```

**Comment by kgpai** [comment]
I am curious why you would set things up with arm64 but then use aarch64 for the build - The arm64 binaries are apple m1 and aarch64 is like cortex arm.
