### ISSUE TITLE
Cast(string as integer) behaves differently from Spark on a corner case

### ISSUE THREAD

**Issue by marin-ma** [facebookincubator/velox#6110]
### Bug description

In SparkSQL,

```
SELECT cast("1.8" as tinyint); -- 1
SELECT cast("-1.8" as tinyint); -- -1

# Below patterns are also valid
SELECT cast("." as tinyint); -- 0
SELECT cast("-." as tinyint); -- 0
```

In Velox, all of the above query throws. We should make them behave the same as SparkSQL.

In SparkSQL, the behavior is to truncate rather than to round. I will raise a PR to fix the issue with `cast_to_int_by_truncate=true` which aligns with the SparkSQL cases.

### System information

Velox System Info v0.0.2
Commit: 7cebb341ae58824e7eb29eeee4c4bcd58af45c0e
CMake Version: 3.16.3
System: Linux-5.4.0-155-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by jinchengchenghh** [comment]
Is this the version difference? I test in presto
```

presto:default> select cast('1.8' as tinyint);
Query 20230822_211644_00008_sqyi8 failed: Cannot cast '1.8' to TINYINT

presto:default> select cast("1.8" as tinyint);
Query 20230822_211707_00009_sqyi8 failed: line 1:13: Column '1.8' cannot be resolved
select cast("1.8" as tinyint)

```
