### ISSUE TITLE
Investigate "too long with no output" error in fuzzer test in CircleCI

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#6117]
### Description

This fuzzer test failed because there were no output for 2 hours: https://app.circleci.com/pipelines/github/facebookincubator/velox/31266/workflows/3cd98acb-e744-4b67-96f2-dbdb8b1e1f27/jobs/197923.

We need to understand why the evaluation stuck.

**Comment by pedroerp** [comment]
last time I saw a similar failure, it was a bug in a string function triggering an infinite loop.

**Comment by kagamiori** [comment]
> last time I saw a similar failure, it was a bug in a string function triggering an infinite loop.

Hi @pedroerp, is there a github issue or a fix PR for that bug? I wonder whether the failure we see was due to the same reason (and potentially has already been fixed).

**Comment by kagamiori** [comment]
According to @kgpai, we were not able to reproduce this timeout error locally. So we'll try to reduce logging first in case this was one reason causing the failure.

**Comment by pedroerp** [comment]
> > last time I saw a similar failure, it was a bug in a string function triggering an infinite loop.
> 
> Hi @pedroerp, is there a github issue or a fix PR for that bug? I wonder whether the failure we see was due to the same reason (and potentially has already been fixed).

That was a different bug that has been fixed. I think my point is that this should be a similar cause (an infinite loop being triggered somewhere). If we can reproduce it, running perf will point you right to the right part of the code.

**Comment by kagamiori** [comment]
Closing this issue until we can reproduce it again.
