### ISSUE TITLE
Fuzzer test failure on try(array_remove())

### ISSUE THREAD

**Issue by zacw7** [facebookincubator/velox#6122]
### Bug description

Fuzzer reported a mismatch on testing array_remove.

We think the issue could be as follows:
`array_remove(x, element)` iterate the array `x` elements, and keeps adding the elements which is not `element`. During the iteration, when a `null` is found, the [iteration is interrupted](https://github.com/facebookincubator/velox/pull/6027/files#diff-05730d551b2432f68b64db0e73bccd5846780904db3084de78461ed5b75c5791R734-R736) and the elements that have been already added to the buffer are supposed to be cleared. It seems in some cases, somehow the buffer remains polluted, making the results of next rows incorrect, resulting in the mismatch.

How to repro:
1. Checkout https://github.com/facebookincubator/velox/pull/6027
2. Go to https://app.circleci.com/pipelines/github/facebookincubator/velox/30902/workflows/7725ca92-9751-47a3-bfde-bcf50130a4bf/jobs/194995/artifacts , download the input files used by the fuzzer test.
3. Run the fuzzer test locally with the input. (minimum expression to repro the issue using the above input files: `"try"("array_remove"("c1", (__complex_constant(c0))."row_field1"))`)

### System information

see description

### Relevant logs

```bash
https://app.circleci.com/pipelines/github/facebookincubator/velox/30902/workflows/7725ca92-9751-47a3-bfde-bcf50130a4bf/jobs/194995
```

cc. @kagamiori @laithsakka @amitkdutta

**Comment by laithsakka** [comment]
from https://facebookincubator.github.io/velox/develop/scalar-functions.html
2. If a function throws an exception while writing a complex type, then the output of the row being written as well as the output of the next row are undefined. Hence, it’s recommended to avoid throwing exceptions after writing has started for a complex output within the function.

solution:
```
 void call(
      out_type<Array<Generic<T1>>>& out,
      const arg_type<Array<Generic<T1>>>& array,
      const arg_type<Generic<T1>>& element) {
    static constexpr CompareFlags kFlags = {
        false, false, /*euqalsOnly*/ true, true /*stopAtNull*/};
    std::vector<std::optional<exec::GenericView>> toCopyItems;

    for (const auto& item : array) {
      if (item.has_value()) {
        auto result = element.compare(item.value(), kFlags);
        VELOX_USER_CHECK(
            result.has_value(),
            "array_remove does not support arrays with elements that are null or contain null")
        toCopyItems.push_back(item.value());
      } else {
        toCopyItems.push_back(std::nullopt);
      }
    }

    for (const auto& item : toCopyItems) {
      if (item.has_value()) {
        auto& newItem = out.add_item();
        newItem.copy_from(item.value());

      } else {
        out.add_null();
      }
    }
  }
};
```
