### ISSUE TITLE
Let Values node release reference on Values::values_

### ISSUE THREAD

**Issue by shiyu-bytedance** [facebookincubator/velox#6130]
### Description

Currently, the Values plan node and operator holds a vector<VectorPtr> values_, which are the values to be yielded out in getOutput.

Being a source operator, unlike TableScan, ValuesNode and Values op classes maintains references to their shared_ptr's of values_ throughout the entirety of query execution, leading to buffer not being freed.

In theory, the ValuesNode class no longer needs reference to its values_ as soon as they have been transferred to Values op.

In turn, Values op no longer needs reference to its values_ as soon as each one has been getOutput'd.

cc @mbasmanova for input on validity of this idea.

**Comment by shiyu-bytedance** [comment]
@mbasmanova 
The inspiration spawn out of my experimenting with "single node" benchmarking and noticing some unaccounted perf differences. After some investigation, I tracked it down to it being the time taken to free input vectors.

The idea here is similar to this comment(https://github.com/facebookincubator/velox/pull/6167#discussion_r1301980261) from you; that let us not hold on to memory longer than need to.

Currently, both ValuesNode and Values operator do not "clear".

As for Values usage, I believe I've seen it used in production to pass small hash tables or constants, so perhaps proactive reset'ing won't yield much memory saving.

**Comment by mbasmanova** [comment]
@shiyu-bytedance Got it. Thank you for providing more context. 

Currently, plan nodes are immutable. This is a nice property worth preserving.

One option might be to add a flag to ValuesNode that will indicate that Values operator should make a copy of the vectors and release these copies in getOutput().

**Comment by shiyu-bytedance** [comment]
@mbasmanova 
> Currently, plan nodes are immutable. This is a nice property worth preserving.

The way I thought about it is to add PlanNode::reclaim() API, which Driver.cpp (for example, among other users) can call to release resources held by operators once pipelines have been constructed. Much like, in memory constrained environment, memory reclaimer can invoke ::reclaim() on operators to free up memory.

**Comment by mbasmanova** [comment]
@shiyu-bytedance Do you have any other use cases for this functionality? If not, I'd prefer to avoid introducing more complexity into the Driver and limit the changes to Values node and operator.

**Comment by aditi-pandit** [comment]
> @shiyu-bytedance Got it. Thank you for providing more context.
> 
> Currently, plan nodes are immutable. This is a nice property worth preserving.
> 
> One option might be to add a flag to ValuesNode that will indicate that Values operator should make a copy of the vectors and release these copies in getOutput().

@mbasmanova, @shiyu-bytedance  :
+1.

Its good to have the property that PlanNodes are immutable. 

In my mind making Values operator like a SourceOperator that receives a Split with the values vector (instead of getting them from the PlanNode), could make the input vectors be passed along easily. Could we consider something like that ? Or is it too much of a change ?

Else, its good to add a flag to ValuesNode.

I too feel that we should keep the Driver API simple and not complicate it with the PlanNode reclaim. PlanNode reclaim is not part of the control mechanism required for data flow at all. So it seems an unnatural addition.

**Comment by shiyu-bytedance** [comment]
no feasible as plan nodes are immutable.
