### ISSUE TITLE
How connect presto with velox?

### ISSUE THREAD

**Issue by RaymondChina** [facebookincubator/velox#619]
We want to try velox with presto, it seems the todo includes
1. define protocol between presto and velox, build a binary with velox, and list on a port x
2. presto connect port x and send plan tree, receive the result

is it right ? thanks.

**Comment by huxiaoxiang** [comment]
We have the same question. Will there be a simple tutorial or blog about integration?

**Comment by kgpai** [comment]
@RaymondChina @huxiaoxiang 

Meta has the Prestissimo project (presto_cpp) which integrates velox and presto. It is not yet open sourced, however you can get access to it by signing some NDA's. 

cc: @jijufb @pedroerp

**Comment by jijufb** [comment]
@RaymondChina, I can initiative NDA process if you would like. Share me your company name, Company address and email address to which NDA doc should be sent?

**Comment by RaymondChina** [comment]
> @RaymondChina, I can initiative NDA process if you would like. Share me your company name, Company address and email address to which NDA doc should be sent?

where should I send company name and email to ? on this comments board ?
  @jijufb

**Comment by jijufb** [comment]
Please send to my email address - jiju@fb.com

**Comment by tangjiangling** [comment]
@kgpai @jijufb One more question: Are there any plans to open source Prestissimo?

**Comment by jijufb** [comment]
yes, tentatively targeting for H1 2022

**Comment by tangjiangling** [comment]
Wow, Awesome!

**Comment by huxiaoxiang** [comment]
> can you share all GitHub logins for providing access ?
I'v already signed the NDA doc. 
My Github info:
userName: huxiaoxiang
email:         34263604@qq.com
Thanks jijufb.

**Comment by RaymondChina** [comment]
> 

done

**Comment by RaymondChina** [comment]
> Please send to my email address - [jiju@fb.com](mailto:jiju@fb.com)

done, pls check it, thanks.

**Comment by wilhelmjung** [comment]
> Please send to my email address - [jiju@fb.com](mailto:jiju@fb.com)
Hi, Jiju. I also need the access to Prestissimo source code. Pls check the email, thanks!

**Comment by jijufb** [comment]
Are you part of Ant Group company?

**Comment by huxiaoxiang** [comment]
> Are you part of Ant Group company?

Well, I'm a SDE of Ant Group...

**Comment by jijufb** [comment]
Access to code have given.

**Comment by RaymondChina** [comment]
> 

company : Alibaba cloud 
mail: 1106927850@qq.com

**Comment by chuanlei** [comment]
@jijufb 
I want to get access to the Prestissimo presto_cpp which integrates velox and presto by signing some NDA's. Please send NDA doc to this email address. 

Company Name: Ant Group
Company Address:	Xixi Road 556, Xihu district, Hangzhou City, Zhejiang Province, China
Sending Email Address:	chuanlei.ncl@antgroup.com

**Comment by jijufb** [comment]
Access to code have given.

**Comment by zhengxingmao** [comment]
company : Deepexi
mail: zhengxingmao@deepexi.com
Thanks!

**Comment by long1208** [comment]
company:XYF
mail:13121311543@163.com
thanks!

**Comment by utf7** [comment]
company:https://www.ximalaya.com/

**Comment by wubiaoi** [comment]
company: meituan
mail: sywubiao@gmail.com
Thanks！

**Comment by jijufb** [comment]
>

**Comment by jijufb** [comment]
Bumping this message - 
If you are trying to get access to Presto code, please share below details to jiju@fb.com
1. Your full name
2. Company name
3. Company physical address
4. Your email address. 

This will help me to initiative NDA process.

If there is already a valid NDA, I should be able to provide access instantaneously.

**Comment by tangjiangling** [comment]
Thanks a lot.

**Comment by ImTangYun** [comment]
company:bigo
mail:candycloud6666@gmail.com

thanks!

**Comment by dingqiaoyi** [comment]
company : Alibaba cloud
mail: dingqiaoyi@qq.com

thanks

**Comment by jijufb** [comment]
Share your GitHub user name.

Thanks,
Jiju

**Comment by jiangzhx** [comment]
@jijufb 
Company name :  analysysdata
Your email address:  jiangzhx@gmail.com

thanks

**Comment by a516072575** [comment]
@jijufb 

company : BEKE
mail: 516072575@qq.com

thanks

**Comment by zhengxingmao** [comment]
At present, it has entered the second quarter. Is there a time point when this code will be open source. @[jijufb](https://github.com/jijufb)

**Comment by pedroerp** [comment]
> At present, it has entered the second quarter. Is there a time point when this code will be open source. @[jijufb](https://github.com/jijufb)

@zhengxingmao this code is currently being merged into prestodb (the java repo). @mshang816 should be able to provide you a more concrete timeline, but my guess is that it should take a few more weeks.

**Comment by zhengxingmao** [comment]
> > At present, it has entered the second quarter. Is there a time point when this code will be open source. @[jijufb](https://github.com/jijufb)
> 
> @zhengxingmao this code is currently being merged into prestodb (the java repo). @mshang816 should be able to provide you a more concrete timeline, but my guess is that it should take a few more weeks.

Thank you for your reply. I have found it in the prestodb project.

**Comment by kaka11chen** [comment]
company: aloudata
mail: [kaka11.chen@gmail.com](mailto:kaka11.chen@gmail.com)

Thanks!
