### ISSUE TITLE
VectorFuzzer::fuzzInputRow never creates arrays, maps of structs with nulls

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#6195]
### Bug description

VectorFuzzer::fuzzInputRow ignores containerHasNulls flag specified in the options.

```
RowVectorPtr VectorFuzzer::fuzzInputRow(const RowTypePtr& rowType) {
  ScopedOptions restorer(this);
  opts_.containerHasNulls = false;
  return fuzzRow(rowType, opts_.vectorSize);
}
```

Possible fix:

```
RowVectorPtr VectorFuzzer::fuzzInputRow(const RowTypePtr& rowType) {
  const auto size = opts_.vectorSize;
  std::vector<VectorPtr> children;
  for (auto i = 0; i < rowType->size(); ++i) {
    children.push_back(fuzz(rowType->childAt(i), size));
  }

  return std::make_shared<RowVector>(
      pool_, rowType, nullptr, size, std::move(children));
}
```

However, this triggers failures in expression fuzzer (probably because fuzzer starts testing new code paths): https://app.circleci.com/pipelines/github/facebookincubator/velox/31687/workflows/dd27e97a-7126-48bc-9d09-7879442b2070/jobs/201563

CC: @bikramSingh91 @laithsakka @kgpai @kagamiori @pedroerp 

### System information

n/a

**Comment by laithsakka** [comment]
this is fixed
in 
https://l.facebook.com/l.php?u=https%3A%2F%2Fgithub.com%2Ffacebookincubator%2Fvelox%2Fpull%2F6544&h=AT0LPLp4NNM3b6Qx7dBVkpvOsfje3u39gr4UE_9gXC00CdnYGZxAXWySOT5m6XIVh14_uH3VL2rKoovjU46YBdoVvSwkvB9ILN83Zgdcc6EzTbvh8ZLaxMKuHWj86vG7wIiKYH_pRJtHcrw5ieP1Czfa
