### ISSUE TITLE
Cast VARBINARY to VARCHAR is not allowed

### ISSUE THREAD

**Issue by zhejiangxiaomai** [facebookincubator/velox#6198]
### Bug description

Here is a spark UT. This case cast partition key (varbinary type to varchar type). https://github.com/apache/spark/blob/branch-3.2/sql/core/src/test/scala/org/apache/spark/sql/SQLQuerySuite.scala#L3800-L3805

And I translate it to a Velox UT here. https://github.com/facebookincubator/velox/pull/6077/files#diff-c62590f29a2bf22e50e276f2665e0a7666968880de73a6b4db745cbc0cfde6feR3038-R3058

[Expected behavior] 
we can cast varbinary to varchar successfully.

[actual behavior:]

when use gluten to run the sql.  velox will throw exception.
https://github.com/facebookincubator/velox/pull/6077/files#diff-e12652047a6e1efdb98a7749e2702ec9bd53aa314123d8e22e2955917dee5f38L619

### System information

Velox System Info v0.0.2
Commit: 316ef011e88cb64c5422e14b4878993c461547dd
CMake Version: 3.16.3
System: Linux-5.4.0-156-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

\nThe results will be copied to your clipboard if xclip is installed.

**Comment by mbasmanova** [comment]
Note that Presto doesn't support cast(varbinary as varchar):

```
presto> select cast(cast('test' as varbinary) as varchar);
Query failed: line 1:8: Cannot cast varbinary to varchar
```

If Spark support such cast, we'll need to figure out how to extend cast implementation to support both Presto and Spark's behaviors.

CC: @bikramSingh91 @laithsakka @kagamiori

**Comment by zhejiangxiaomai** [comment]
Here is spark result.
scala> spark.sql("select cast(cast('test' as binary) as string)").show()
+------------------------------------+
|CAST(CAST(test AS BINARY) AS STRING)|
+------------------------------------+
|                                test|
+------------------------------------+

cc: @rui-mo

**Comment by mbasmanova** [comment]
@zhejiangxiaomai Can you check whether Spark verifies that varbinary input contains only valid UTF-8 characters?

**Comment by zhejiangxiaomai** [comment]
Yes, Here is inplementation of spark. 
function `castToStringCode` call `fromBytes` to create a UTF-8 string.

castToStringCode link:
https://github.com/apache/spark/blob/branch-3.2/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/expressions/Cast.scala#L1139-L1142

fromBytes link
https://github.com/apache/spark/blob/branch-3.2/common/unsafe/src/main/java/org/apache/spark/unsafe/types/UTF8String.java#L105-L116

**Comment by mbasmanova** [comment]
@zhejiangxiaomai Somehow, I do not see a check for 'varbinary' being valid UTF-8 string. Would you share a pointer?

**Comment by mbasmanova** [comment]
FYI, Presto provides from_utf8 function to cast varbinary to varchar:

https://facebookincubator.github.io/velox/functions/presto/string.html#from_utf8

**Comment by zhejiangxiaomai** [comment]
From the code I saw, I didn't found a check whether `fromString` is UTF-8 string. And I think maybe we can extend cast implementation for cast `varbinary to varchar`.

**Comment by rui-mo** [comment]
@zhejiangxiaomai As we discussed offline, this issue is not relevant to `.project({"a", "cast(ds_alias as string)"})`, and the title `Cast VARBINARY to VARCHAR is not allowed` is misleading. Can we improve the titile and description to be more precise?

**Comment by zhejiangxiaomai** [comment]
Thanks, when I add more log. I know the root cause of this problem. The key reason is Converter will treat Varbinary as Varchr . https://github.com/facebookincubator/velox/blob/main/velox/type/Conversions.h#L373-L379. 
Then in setConstantValue function.  
setConstantValue(spec, it->second->dataType(), constValue);  https://github.com/facebookincubator/velox/blob/main/velox/connectors/hive/HiveDataSource.cpp#L920

(gdb) p constValue
$6 = {kind_ = facebook::velox::TypeKind::VARCHAR, ptr_ = 0x7fffc000b8f0}
(gdb) p it->second->dataType()
$7 = std::shared_ptr<const facebook::velox::Type> (use count 8, weak count 0) = {get() = 0x55556faa10b0}
(gdb) p it->second->dataType()->kind()
$8 = facebook::velox::TypeKind::VARBINARY

Finally, createConstant will check whether `constValue.kind` equal to `it->second->dataType()->kind()`.
