### ISSUE TITLE
Expression fuzzer generates invalid switch expression

### ISSUE THREAD

**Issue by laithsakka** [facebookincubator/velox#6219]
### Bug description

we have a PR fuzzer  that fails with 
Reason: Else clause of a SWITCH statement must have the same type as 'then' clauses. Expected ROW<"":BOOLEAN>, but got ROW<row_field0:BOOLEAN>.

https://app.circleci.com/pipelines/github/facebookincubator/velox/31820/workflows/9f41b232-b465-4c68-9caf-27c530cb651a/jobs/202703

### System information

NA

**Comment by Yuhta** [comment]
Similar issue but for `coalesce`: #6230

**Comment by kagamiori** [comment]
I'm not able to reproduce the error given in the link above on my devserver or my laptop.
