### ISSUE TITLE
[Native] NestedloopJoin with join criteria produces incorrect number of rows.

### ISSUE THREAD

**Issue by karteekmurthys** [facebookincubator/velox#6223]
### Bug description

Produces 1 addtional row more than the expected. Issue fails often on cluster with multiple workers.
```
java.lang.AssertionError: For query: 
 SELECT * FROM (SELECT * FROM nation WHERE nation.nationkey%2=0)FULL JOIN (SELECT * FROM region WHERE regionkey%2=0) region ON region.regionkey = 2
not equal
Actual rows (up to 100 of 1 extra rows shown, 16 rows in total):
    [null, null, null, null, 2, ASIA, ges. thinly even pinto beans ca]
Expected rows (up to 100 of 0 missing rows shown, 15 rows in total):
```

### System information

NA

**Comment by aditi-pandit** [comment]
@karteekmurthys : You mentioned that you need atleast 4 workers in your cluster to reproduce this problem. Does presto-cli using a cluster with 4 workers never hit this problem ?

**Comment by karteekmurthys** [comment]
There have been occasions where it fails on single worker as well. With new query involving nation and region I am able to reproduce lot more often even with single worker. We can clearly see filter has wrongly generated a build mismatch:

```
Actual rows (up to 100 of 1 extra rows shown, 16 rows in total):
    [null, null, null, null, 2, ASIA, ges. thinly even pinto beans ca]
```

Here regionkey = 2 satisfies the join criteria and must not have a null against it. CMIW

**Comment by karteekmurthys** [comment]
```
 SELECT nation.nationkey, region.regionkey, region.name FROM (SELECT * FROM nation WHERE nation.nationkey%4=0) nation FULL JOIN (SELECT * FROM region WHERE regionkey%4=0) region ON region.regionkey = 4
not equal
Actual rows (up to 100 of 9 extra rows shown, 9 rows in total):
    [0, 4, MIDDLE EAST]
    [4, 4, MIDDLE EAST]
    [8, 4, MIDDLE EAST]
    [12, 4, MIDDLE EAST]
    [16, 4, MIDDLE EAST]
    [20, 4, MIDDLE EAST]
    [24, 4, MIDDLE EAST]
    [null, 0, AFRICA]
    [null, 4, MIDDLE EAST]
Expected rows (up to 100 of 1 missing rows shown, 1 rows in total):
    [1]
```

**Comment by aditi-pandit** [comment]
> Expected 8 rows but got 9.
> 
> ```
>  SELECT nation.nationkey, region.regionkey, region.name FROM (SELECT * FROM nation WHERE nation.nationkey%4=0) nation FULL JOIN (SELECT * FROM region WHERE regionkey%4=0) region ON region.regionkey = 4
> not equal
> Actual rows (up to 100 of 9 extra rows shown, 9 rows in total):
>     [0, 4, MIDDLE EAST]
>     [4, 4, MIDDLE EAST]
>     [8, 4, MIDDLE EAST]
>     [12, 4, MIDDLE EAST]
>     [16, 4, MIDDLE EAST]
>     [20, 4, MIDDLE EAST]
>     [24, 4, MIDDLE EAST]
>     [null, 0, AFRICA]
>     [null, 4, MIDDLE EAST]
> Expected rows (up to 100 of 1 missing rows shown, 1 rows in total):
>     [1]
> ```

@karteekmurthys : This shows the behavior which was the hunch yesterday that the single row matching all rows is repeated with NULLs also.

Have you been able to see this with a single worker ?

**Comment by karteekmurthys** [comment]
Yes, I have been able to repro on single worker. Here is my finding, for the following query:
```
SELECT nation.nationkey, region.regionkey, region.name FROM (SELECT * FROM nation WHERE nation.nationkey%4=0) nation FULL JOIN (SELECT * FROM region WHERE regionkey%4=0) region ON region.regionkey = 4
```
The build side has 2 rows and 1 row is valid but the buildMatched_ vector has marked both invalid:
```
(lldb) p matched.isValid(1)
(bool) $0 = false
(lldb) p matched.isValid(0)
(bool) $1 = false
```

This variable is in getMismatchedOutput():

I tried to log the addresses of buildMatched_ member and it seems like it changes for the failures case:
```
I20230824 00:18:07.550011 1089194 NestedLoopJoinProbe.cpp:465] NestedLoopJoinProbe::doMatch() buildMatched obj at 0x600003885d70
I20230824 00:18:07.550037 1089194 NestedLoopJoinProbe.cpp:467] NestedLoopJoinProbe::doMatch() buildMatched at 0 0
I20230824 00:18:07.550056 1089194 NestedLoopJoinProbe.cpp:467] NestedLoopJoinProbe::doMatch() buildMatched at 1 1
I20230824 00:18:07.550103 1089194 NestedLoopJoinProbe.cpp:483] NestedLoopJoinProbe::doMatch() Final output size after filter 7
I20230824 00:18:07.550125 1089194 NestedLoopJoinProbe.cpp:171] NestedLoopJoinProbe::getOutPut after calling doMatch 7
I20230824 00:18:07.550144 1089194 NestedLoopJoinProbe.cpp:178] NestedLoopJoinProbe::getOutPut before exit 7
I20230824 00:18:07.550235 1089194 NestedLoopJoinProbe.cpp:164] NestedLoopJoinProbe::getOutPut hasProbedAllBuildData 0
I20230824 00:18:07.550253 1089194 NestedLoopJoinProbe.cpp:178] NestedLoopJoinProbe::getOutPut before exit 0

I20230824 00:18:07.581224 1089196 NestedLoopJoinProbe.cpp:132] NestedLoopJoinProbe::getOutput() buildMatched obj at 0x6000038f0180
I20230824 00:18:07.581323 1089196 NestedLoopJoinProbe.cpp:140] NestedLoopJoinProbe::getOutPut not hasProbedAllBuildData after getMismatchedOutput 2 <--- 2 Mismatches.
```

When the query succeeds, the buildMatched_ selectivity vector is unchanged yielding the correct results:
```
I20230824 00:15:23.333418 1084363 NestedLoopJoinProbe.cpp:465] NestedLoopJoinProbe::doMatch() buildMatched obj at 0x600003b687e0
I20230824 00:15:23.333437 1084363 NestedLoopJoinProbe.cpp:467] NestedLoopJoinProbe::doMatch() buildMatched at 0 0
I20230824 00:15:23.333454 1084363 NestedLoopJoinProbe.cpp:467] NestedLoopJoinProbe::doMatch() buildMatched at 1 1
I20230824 00:15:23.333503 1084363 NestedLoopJoinProbe.cpp:483] NestedLoopJoinProbe::doMatch() Final output size after filter 7
I20230824 00:15:23.333524 1084363 NestedLoopJoinProbe.cpp:171] NestedLoopJoinProbe::getOutPut after calling doMatch 7
I20230824 00:15:23.333540 1084363 NestedLoopJoinProbe.cpp:178] NestedLoopJoinProbe::getOutPut before exit 7
I20230824 00:15:23.333622 1084363 NestedLoopJoinProbe.cpp:164] NestedLoopJoinProbe::getOutPut hasProbedAllBuildData 0
I20230824 00:15:23.333640 1084363 NestedLoopJoinProbe.cpp:178] NestedLoopJoinProbe::getOutPut before exit 0
I20230824 00:15:23.336091 1083318 NestedLoopJoinProbe.cpp:132] NestedLoopJoinProbe::getOutput() buildMatched obj at 0x600003b687e0
I20230824 00:15:23.336154 1083318 NestedLoopJoinProbe.cpp:140] NestedLoopJoinProbe::getOutPut not hasProbedAllBuildData after getMismatchedOutput 1 <--- Correct result
I20230824 00:15:23.336174 1083318 NestedLoopJoinProbe.cpp:178] NestedLoopJoinProbe::getOutPut before exit 1
```

**Comment by karteekmurthys** [comment]
The root cause is a race condition between parallel NestedLoogJoinProbe operators. The common area for exchange of information between these probe operators is in `beginBuildMismatch()` method.

Let's say, if there are 2 probe operators P1 and P2. P1 processes all the build data and marks itself finished [here](https://github.com/facebookincubator/velox/blob/main/velox/exec/NestedLoopJoinProbe.cpp#L282), as other peers (P2) are still processing.
When P2 arrives at `beginBuildMismatch`, its peer P1 is marked finished and now it is the `lastProbe_` alive and copies the `buildMatched_`  SelectivityVector from peer P1.

But, in our failure case, this breaks. After P1 marks itself finish, the driver seems to have terminated and probe P2 has no peers to copy `buildMatched_` from. In our example query we have 1 result matched but the probe P2::buildMatched_ has 0 out of 2 rows unmatched. When P2::getOutPut is called, this time fetches all rows as mismatched rows from its own buildMatched_ SelectivityVector.

Some logs I printed out to help understand the flow:
```
14:12.462167 1890252 Task.cpp:1476] Task::allPeersFinished() numPeers 3 state.numRequested0
14:12.462172 1890229 NestedLoopJoinProbe.cpp:180] NestedLoopJoinProbe::getOutPut before exit 0
14:12.462188 1890252 NestedLoopJoinProbe.cpp:290] NestedLoopJoinProbe::beginBuildMismatch() set kFinish this 0x129b0d850
14:12.462199 1890249 Task.cpp:1476] Task::allPeersFinished() numPeers 3 state.numRequested1
14:12.462221 1890229 Task.cpp:1464] Task::allPeersFinished() entering 
14:12.462232 1890252 NestedLoopJoinProbe.cpp:125] NestedLoopJoinProbe::getOutput isFinished
14:12.462247 1890249 NestedLoopJoinProbe.cpp:290] NestedLoopJoinProbe::beginBuildMismatch() set kFinish this 0x129b0ef30
14:12.462266 1890229 Task.cpp:1476] Task::allPeersFinished() numPeers 3 state.numRequested2
14:12.462306 1890249 NestedLoopJoinProbe.cpp:125] NestedLoopJoinProbe::getOutput isFinished
14:12.462316 1890229 NestedLoopJoinProbe.cpp:296] NestedLoopJoinProbe::beginBuildMismatch() set lastProbe_ this 0x129b10020
No Peers found ---> 14:12.462342 1890229 NestedLoopJoinProbe.cpp:300] NestedLoopJoinProbe::beginBuildMismatch() number of peers: 0
14:12.462364 1890229 NestedLoopJoinProbe.cpp:134] NestedLoopJoinProbe::getOutput() buildMatched:0x600000c80720 buildIndeX_:0 this:0x129b10020
14:12.462436 1890229 NestedLoopJoinProbe.cpp:142] NestedLoopJoinProbe::getOutPut not hasProbedAllBuildData after getMismatchedOutput 2
14:12.462456 1890229 NestedLoopJoinProbe.cpp:180] NestedLoopJoinProbe::getOutPut before exit 2
14:12.462527 1890229 NestedLoopJoinProbe.cpp:125] NestedLoopJoinProbe::getOutput isFinished
```  
cc: @mbasmanova @aditi-pandit @majetideepak

**Comment by mbasmanova** [comment]
CC: @xiaoxmeng @usurai

**Comment by usurai** [comment]
@karteekmurthys Thanks for catching and investigating on this!
Indeed, probe operators should wait for the last probe operator to take the mismatch data, instead of finishing.
Fix is #6326.

**Comment by karteekmurthys** [comment]
@mbasmanova  @usurai 
Looks like we have more issues in nestedloop implementation:

```
Actual rows (up to 100 of 1 extra rows shown, 1 rows in total):
    [251]
Expected rows (up to 100 of 1 missing rows shown, 1 rows in total):
    [310]

        at org.testng.Assert.fail(Assert.java:110)
        at com.facebook.presto.tests.QueryAssertions.assertEqualsIgnoreOrder(QueryAssertions.java:251)
        at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:231)
        at com.facebook.presto.tests.QueryAssertions.assertQuery(QueryAssertions.java:106)
        at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:152)
        at com.facebook.presto.tests.AbstractTestQueryFramework.assertQuery(AbstractTestQueryFramework.java:147)
        at com.facebook.presto.nativeworker.AbstractTestNativeJoinQueries.testJoinsWithConstantFilterAndNoCriteria(AbstractTestNativeJoinQueries.java:132)
```

**Comment by aditi-pandit** [comment]
> 

@karteekmurthys : Are you able to reproduce this problem with all of LEFT, RIGHT and FULL OUTER joins ? Or is it specific to some of these ?

**Comment by aditi-pandit** [comment]
@karteekmurthys : https://github.com/facebookincubator/velox/blob/main/velox/exec/NestedLoopJoinProbe.cpp#L302 should be updating probeMatched_ also right ?

**Comment by karteekmurthys** [comment]
In this query,  the actual matched rows are 251 and there must be 59 buildMismatched rows. Seems like after the recent change the buildMatched_ all are selected (Need to confirm this).
```
SELECT count(*) FROM (SELECT * FROM lineitem WHERE orderkey % 1024 = 0) lineitem RIGHT JOIN (SELECT * FROM orders WHERE orderkey % 1024 = 0) orders ON orders.orderkey = 1024
```
@usurai

**Comment by usurai** [comment]
> In this query, the actual matched rows are 251 and there must be 59 buildMismatched rows. Seems like after the recent change the buildMatched_ all are selected (Need to confirm this).
> 
> ```
> SELECT count(*) FROM (SELECT * FROM lineitem WHERE orderkey % 1024 = 0) lineitem RIGHT JOIN (SELECT * FROM orders WHERE orderkey % 1024 = 0) orders ON orders.orderkey = 1024
> ```
> 
> @usurai

Could you share your dataset for this? I could not reproduce this with my handmade data. Thanks!

**Comment by karteekmurthys** [comment]
Please run the e2e tests here: https://github.com/prestodb/presto/pull/20381/files#diff-5ef1982fc26230a4150cc7fe37fbaebc7735cea470b2a09599ebd839f37ef369R124.
You can copy the test method `testJoinsWithConstantFilterAndNoCriteria` and just run it like any other e2e test.


I am not able to reproduce it locally either.

**Comment by karteekmurthys** [comment]
Here is the job that failed: https://app.circleci.com/pipelines/github/prestodb/presto/6974/workflows/ccf507fc-9314-4833-8211-0ecab8353b90/jobs/22350

**Comment by usurai** [comment]
@karteekmurthys Thanks for pointing to the failed test. Could you share the instruction to run the E2E test with command line(it's missing in `presto-native-execution`'s readme) as I don't have access to Intellij IDEA.
Regarding the test failure, I think we first need to figure out what's the representation of the expression `ON orders.orderkey = 1024` is in the system, a join condition or a filter. Please see my comment in the PR, thanks!

**Comment by karteekmurthys** [comment]
https://app.circleci.com/pipelines/github/prestodb/presto/6974/workflows/ccf507fc-9314-4833-8211-0ecab8353b90/jobs/22350
If no IntelliJ, you can run e2e by starting a docker container with image `prestocpp/prestocpp-avx-centos:root-20230613` and follow steps here in this file [`.circleci/continue_config.yml`](https://github.com/prestodb/presto/blob/master/.circleci/continue_config.yml).

**Comment by usurai** [comment]
I think this issue can be closed since the cause is not related to the nested loop join.
