### ISSUE TITLE
SelectiveTimestampColumnReader ignores ValueHook

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#6297]
### Bug description

Pushing aggregation into TableScan produces null values for TIMESTAMP columns.

E.g. the following query returns nulls for all rows in 2nd column when b is a TIMESTAMP:

```
SELECT a, min(b) FROM t GROUP BY 1
```

Unit test repro:

```
TEST_F(TableScanTest, xxx) {
  auto rowType = ROW({"c0", "c1", "c2"}, {TINYINT(), INTEGER(), TIMESTAMP()});
  auto vectors = makeVectors(2, 1'000, rowType);
  auto filePath = TempFilePath::create();
  writeToFile(filePath->path, vectors);
  createDuckDbTable(vectors);

  auto op =
      PlanBuilder()
          .tableScan(rowType)
          .partialAggregation(
              {"c0"}, {"min(c1)", "min(c2)"})
          .finalAggregation()
          .planNode();

  auto task = assertQuery(
      op,
      {filePath},
      "SELECT c0, min(c1), min(c2) FROM tmp GROUP BY 1");
}
```

I found this issue by extending AggregationFuzzer to create plans with TableScan node.

CC: @laithsakka @Yuhta @oerling 

### System information

n/a

**Comment by Yuhta** [comment]
CC: @zacw7

**Comment by laithsakka** [comment]
@mbasmanova @kagamiori 
Wei found a bunch of bugs in different aggregation functions when she tried to update the testing with table scan. 
We are blocked by human capacity to work on this feature.

**Comment by Yuhta** [comment]
We have a check guard against it now
