### ISSUE TITLE
Remove StopAtRhsNull compare mode

### ISSUE THREAD

**Issue by laithsakka** [facebookincubator/velox#6349]
### Bug description

A recent change added StopAtRhsNull to compare flags, so that array_remove would work. 
i chatted with @mbasmanova  it turn out, the logic is not dependent on rhs/lhs. 

but rather, the order of checks, and the current presto compare should be sufficient (if not we need to figure out why)
for example:
select array_remove(ARRAY[ARRAY[null], ARRAY[1]], ARRAY[1]) should be an error 
select array_remove(ARRAY[ARRAY[null, 1], ARRAY[1]], ARRAY[1]) is not because size is different

action items:
1. revert the StopAtRhsNull. 
2. make sure array_remove calls .compare with StopAtNulls
3. check that array_remove works in velox like presto if not investigate. 

### System information

NA

**Comment by zacw7** [comment]
https://github.com/facebookincubator/velox/pull/6444?fbclid=IwAR3hGD47nOPorDy7FKMQySND7HedLd7aVMlXzK5-dsYkRzL68U-XK4DJneM
