### ISSUE TITLE
Do not fill lookup.hits in HashLookup::reset

### ISSUE THREAD

**Issue by shiyu-bytedance** [facebookincubator/velox#6363]
### Description

Recently, in our benchmarking, we found that filling hits with nullptr is a rather expensive "cost", while not fully understanding its purpose based on our understanding of hashtable.

Some background and analysis:

For every input batch added to hashtable, hashlookup.reset() is called. It serves two purposes:
- resize its members to be at least as large as the current input
- fill hits with nullptr.

The resizing of members is just an alloc, not particularly expensive. However, filling hits with nullptr turns out to be somewhat costly. Because size of hits is proportional to input size, hence, the larger the avg input batch size, the more time is wasted on null'ing hits for each input.

A profiling sample from local benchmarking shows just how much time is consumed by HashLook.reset, specifically, null'ing hits consumes.

<img width="1652" alt="Screenshot 2023-08-30 at 3 34 13 PM" src="https://github.com/facebookincubator/velox/assets/105019964/5e5dd68d-d685-4671-8716-99e79f7f3777">

This led us to question the necessity of null'ing hits in HashLookup.reset() because based on our understanding of HashTable and our reading of code, it is redundant by virtue of the fact that we fail to identify a case where not null'ing hits would break any flow.

We further are skeptical about the up-to-dateness of the comment for `hits`, dated from `Initial commit`, stating:
> "// Hit for each row of input. nullptr if no hit. Points to the corresponding group row."

We propose that we remove below from HashLookup.reset():

`std::fill(hits.begin(), hits.end(), nullptr);`

Our internal testing do not detect breakage, thus, we are submitting a PR(https://github.com/facebookincubator/velox/pull/6365) for further CI validation.

Estimated saving:

Depends on batchSize since the time it takes to set all of HashLookup.hits to nullptr is positively correlated to the size of HashLookup.hits. However, on larger batch size, 1mil, saving is roughly 5% of HashAggregation::AddInput. **The screenshot of profile used batchSize of 30mil.

**Comment by shiyu-bytedance** [comment]
cc @mbasmanova @oerling for consideration.

**Comment by mbasmanova** [comment]
CC: @xiaoxmeng

**Comment by mbasmanova** [comment]
@shiyu-bytedance This is a nice investigation. Thank you for detailed report.

It is a bit difficult to reason about the fields in HashLookup struct. I wonder if it would be possible to document each field and update comment for methods that take HashLookup& to clarify what is supposed to be filled in before method call and what is being set by the method.

I'm seeing this code in HashProbe.cpp which also resets hits to null. Wondering if similar performance issues exists here.

```
    auto numInput = input_->size();
    auto& hits = lookup_->hits;
    hits.resize(numInput);
    std::fill(hits.data(), hits.data() + numInput, nullptr);
    if (!lookup_->rows.empty()) {
      table_->joinProbe(*lookup_);
    }
```

Also, seeing this method which might rely on 'hits' being null.

```
  /// Returns the first hit for each key in 'lookup'. The keys are in
  /// 'lookup.hits' with a nullptr representing a miss. This is for use in hash
  /// join probe. Use listJoinResults to iterate over the results.
  virtual void joinProbe(HashLookup& lookup) = 0;
```

**Comment by shiyu-bytedance** [comment]
@mbasmanova 
I verified the below case.
```
  /// Returns the first hit for each key in 'lookup'. The keys are in
  /// 'lookup.hits' with a nullptr representing a miss. This is for use in hash
  /// join probe. Use listJoinResults to iterate over the results.
  virtual void joinProbe(HashLookup& lookup) = 0;
```
I don't think it's a problem. The comment (confirmed with code) is saying for each row in hits, joinProbe will fill in a "hit" ptr or a nullptr if it's a miss. Effectively, the null'ing of hits in HashLookup.reset() is wasted, because in this case, joinProbe will "refill" every hits value anyway.
