### ISSUE TITLE
Unnecessary 'computeValueIdForRows' in 'groupProbe' for 'normalized key' mode

### ISSUE THREAD

**Issue by zhli1142015** [facebookincubator/velox#6405]
### Bug description

`groupProbe `would call `checkSize `for normalized key mode table. And in this function, the normalized key are always recomputed. From my understanding, the `multiplier_ `is not changed, we can retrieve the normazlied key from rows and there is no need to compute them again.

Below is the related call stack from TPCDS query67:
![image](https://github.com/facebookincubator/velox/assets/10524738/8c620812-4a6f-4cae-9218-71158066c8a5)

Query67 before:
![image](https://github.com/facebookincubator/velox/assets/10524738/03956500-e5b4-4c20-9982-ed1affb35f5a)

Query67 after skip 'computeValueIdForRows' in 'groupProbe':
![image](https://github.com/facebookincubator/velox/assets/10524738/4ef6b47a-8f07-4a6f-8f35-7e78eda783fa)

### System information

Velox System Info v0.0.2
Commit: 77e1d751f4ee9822eaf01197929445491fd0d0cd
CMake Version: 3.16.3
System: Linux-5.10.102.1-microsoft-standard-WSL2
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by mbasmanova** [comment]
Copied from the PR:

`groupProbe `would call `checkSize `for normalized key mode table. And in this function, the normalized key are always recomputed. From my understanding, the `multiplier_ `is not changed, we can retrieve the normazlied key from rows and there is no need to compute them again.

Below is the related call stack from TPCDS query67 by gluten:
![image](https://github.com/facebookincubator/velox/assets/10524738/8c620812-4a6f-4cae-9218-71158066c8a5)

**TPCDS 10GB Query67 by gluten** 

(31) HashAggregateExecTransformer
Input [10]: [i_category#398, i_class#399, i_brand#400, i_product_name#401, d_year#402, d_qoy#403, d_moy#404, s_store_id#405, spark_grouping_id#397L, _temp_2#422]
Keys [9]: [i_category#398, i_class#399, i_brand#400, i_product_name#401, d_year#402, d_qoy#403, d_moy#404, s_store_id#405, spark_grouping_id#397L]
Functions [1]: [partial_sum(_temp_2#422)]
Aggregate Attributes [2]: [sum#425, isEmpty#426]
Results [11]: [i_category#398, i_class#399, i_brand#400, i_product_name#401, d_year#402, d_qoy#403, d_moy#404, s_store_id#405, spark_grouping_id#397L, sum#427, isEmpty#428]

-- Project[expressions: (n16_10:VARCHAR, "n14_11"), (n16_11:VARCHAR, "n14_12"), (n16_12:VARCHAR, "n14_13"), (n16_13:VARCHAR, "n14_14"), (n16_14:INTEGER, "n14_15"), (n16_15:INTEGER, "n14_16"), (n16_16:INTEGER, "n14_17"), (n16_17:VARCHAR, "n14_18"), (n16_18:BIGINT, "n14_19"), (n16_19:DECIMAL(28,2), "n15_9"["col_0"]), (n16_20:BOOLEAN, "n15_9"["col_1"])] -> n16_10:VARCHAR, n16_11:VARCHAR, n16_12:VARCHAR, n16_13:VARCHAR, n16_14:INTEGER, n16_15:INTEGER, n16_16:INTEGER, n16_17:VARCHAR, n16_18:BIGINT, n16_19:DECIMAL(28,2), n16_20:BOOLEAN
  **-- Aggregation[PARTIAL [n14_11, n14_12, n14_13, n14_14, n14_15, n14_16, n14_17, n14_18, n14_19] n15_9 := decimal_sum("n14_20")] -> n14_11:VARCHAR, n14_12:VARCHAR, n14_13:VARCHAR, n14_14:VARCHAR, n14_15:INTEGER, n14_16:INTEGER, n14_17:INTEGER, n14_18:VARCHAR, n14_19:BIGINT, n15_9:ROW<col_0:DECIMAL(28,2),col_1:BOOLEAN>**
    -- Project[expressions: (n14_11:VARCHAR, "n13_2"), (n14_12:VARCHAR, "n13_3"), (n14_13:VARCHAR, "n13_4"), (n14_14:VARCHAR, "n13_5"), (n14_15:INTEGER, "n13_6"), (n14_16:INTEGER, "n13_7"), (n14_17:INTEGER, "n13_8"), (n14_18:VARCHAR, "n13_9"), (n14_19:BIGINT, "n13_10"), (n14_20:DECIMAL(18,2), coalesce(check_overflow(decimal_multiply("n13_1",try_cast "n13_0" as DECIMAL(10,0)),true,0),0))] -> n14_11:VARCHAR, n14_12:VARCHAR, n14_13:VARCHAR, n14_14:VARCHAR, n14_15:INTEGER, n14_16:INTEGER, n14_17:INTEGER, n14_18:VARCHAR, n14_19:BIGINT, n14_20:DECIMAL(18,2)

Before:
![image](https://github.com/facebookincubator/velox/assets/10524738/87d35f9c-1cb0-4d83-8114-e4d5d3417e00)

After skip 'computeValueIdForRows' in 'groupProbe':
![image](https://github.com/facebookincubator/velox/assets/10524738/4ef6b47a-8f07-4a6f-8f35-7e78eda783fa)
