### ISSUE TITLE
Lead Function Semantics Diff: when offset is null, Presto return null, Velox return the default value supplied by user

### ISSUE THREAD

**Issue by xumingming** [facebookincubator/velox#6413]
### Bug description

Test case:
```java
// Presto TestLeadFunction.java
assertWindowQuery("lead(orderkey, null, -1) OVER (PARTITION BY orderstatus ORDER BY orderkey)",
        resultBuilder(TEST_SESSION, INTEGER, VARCHAR, INTEGER)
                .row(3, "F", null)
                .row(5, "F", null)
                .row(6, "F", null)
                .row(33, "F", null)
                .row(1, "O", null)
                .row(2, "O", null)
                .row(4, "O", null)
                .row(7, "O", null)
                .row(32, "O", null)
                .row(34, "O", null)
                .build());
```

The result of the window function above in Velox is `-1`.

### System information

Not Relevant.

**Comment by xumingming** [comment]
I am not sure what is the *standard* expected result for this scenario, In Oracle([1]) , it describes the offset/default value as the following:

> The optional default value is returned if the offset goes beyond the scope of the table. If you do not specify default, then its default value is null.

[1]. https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/LEAD.html#GUID-0A0481F1-E98F-4535-A739-FCCA8D1B5B77

So seems Velox's current implementation is more standard? How do you guys think?

**Comment by xumingming** [comment]
@aditi-pandit Do you any suggestion how to proceed with this issue?

**Comment by aditi-pandit** [comment]
@xumingming : Presto doc (https://prestodb.io/docs/current/functions/window.html) states 
` If the offset is null or larger than the window, the default_value is returned, or if it is not specified null is returned.`

So it sounds like Velox is the correct interpretation. Its also inline with the Oracle behavior.

So maybe this is a bug in Presto java implementation ?

@mbasmanova : wdyt ?

**Comment by mbasmanova** [comment]
Looks like Presto documentation doesn't match implementation. This seems to be the case for for lead and lag functions.

**Comment by xumingming** [comment]
As discussed in https://github.com/prestodb/presto/issues/20835, we will `Return Null` when the offset is null for `Lead/Lag`.
