### ISSUE TITLE
Add support reading orc data through the index of the column

### ISSUE THREAD

**Issue by wypb** [facebookincubator/velox#6466]
### Description

Currently, velox reads the data in orc/parquet/dwrf files through column names, This should be fine in most cases. However, in some scenarios, we need to support reading data by the index of the column.

E.g. When writing ORC files with [hive versions earlier than 2.0.0](https://issues.apache.org/jira/browse/HIVE-4243), the output column name is similar to _col0 instead of the actual column name. When we read the orc file, we get column names from orc file like _col0 and _col1 (`struct<_col0:string,_col1:string,_col2:string,_col3:string,_col4:string>`). But the schema defined by our table is `struct<server_ip:string,header:string,reqtimestamp:string,idfa:string,idfv:string>`. In this way, the data we read through velox is all null.

By default, Presto reads data through the column index. For orc and Parquet, `hive.orc.use-column-names` and `hive.parquet.use-column-names` control the reading of data through column names respectively.

Similarly, spark also supports reading orc data by column index.

Therefore, it is necessary to read data through column index in velox.

Internally, I have implemented this function, but I feel that the code is not very well written, and want to ask the community's opinion.

CC: @Yuhta @mbasmanova

**Comment by mbasmanova** [comment]
CC: @spershin Sergey has been looking into this.

**Comment by Yuhta** [comment]
This is scoped to be addressed with schema evolution support in Velox (#6065).  In the meantime, @spershin will have a solution to just replace the column names in file with names in table schema.

**Comment by spershin** [comment]
Going to roll this out in the next day or two.

**Comment by wypb** [comment]
PR with the proposed fix:
https://github.com/facebookincubator/velox/pull/6531

**Comment by wypb** [comment]
PR with the proposed fix:
https://github.com/facebookincubator/velox/pull/6531
