### ISSUE TITLE
Bug in the function of timestamp type

### ISSUE THREAD

**Issue by lingbin** [facebookincubator/velox#6489]
### Bug description

[Expected behavior] and [actual behavior].

There seems to be a bug in the function of `timestamp` type.

https://github.com/facebookincubator/velox/blob/main/velox/functions/prestosql/tests/DateTimeFunctionsTest.cpp#L699-L700
```cpp
  setQueryTimeZone("Pacific/Apia");

  EXPECT_EQ(13, hour(Timestamp(0, 0)));
  EXPECT_EQ(13, hour(Timestamp(-1, Timestamp::kMaxNanos)));
```

For the `hour` function, the results obtained for the following two timestamps **should not be equal**, right? I think the expected result of the two should be a difference of 1.

update:
After exploring, it seems that the `std::duration_cast` here should not behave as expected when dealing with negative numbers.
https://github.com/facebookincubator/velox/blob/main/velox/type/Timestamp.cpp#L104-L108
```cpp
void Timestamp::toTimezone(const date::time_zone& zone) {
  auto tp = toTimePoint();
  auto epoch = zone.to_local(tp).time_since_epoch();
  seconds_ = std::chrono::duration_cast<std::chrono::seconds>(epoch).count();
}
```
We expect **rounding down**, but `std::duration_cast` seems to **always round towards 0**.

### System information

no need.

**Comment by lingbin** [comment]
cc @pedroerp

**Comment by pedroerp** [comment]
Hi @lingbin, could you check what's the Presto and Spark behavior when you pass them these numbers?

**Comment by lingbin** [comment]
Yes, I checked it in the Presto.  

```
presto> select TIMESTAMP '1969-12-31 23:59:59.999 UTC' AT TIME ZONE 'Pacific/Apia';
                _col0
--------------------------------------
 1969-12-31 12:59:59.999 Pacific/Apia


presto> select hour(TIMESTAMP '1969-12-31 23:59:59.999 UTC' AT TIME ZONE 'Pacific/Apia');
 _col0
-------
    12
(1 row)
```

The correct result should be `12`, but the result in Velox unit test is `13`.

**Comment by lingbin** [comment]
I've also confirmed that for the reason (as described above), the rounding behavior of `std::chrono::duration_cast` is not what we expect.  

I can submit a PR to fix it.

**Comment by pedroerp** [comment]
@spershin @mbasmanova I remember hearing a similar correctness issue in our batch validations internally. Might be the same problem.

**Comment by pedroerp** [comment]
@lingbin great catch! I can help review if you are willing to cut a PR to address this issue. Thanks for looking into this.
