### ISSUE TITLE
AggregateFunctionFactory cannot find the correct function with merely the input and output types of the immediate aggregation step

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#6506]
### Description

Currently, aggregation functions are registered in a map that associates each function name with a list of function signatures and one AggregateFunctionFactory. The AggregateFunctionFactory is called to creates the aggregation function instance in the HashAggregation operator. AggregateFunctionFactory receives a list of arguments and is supposed to return an std::unique_ptr of the correct aggregation function class: the aggregation function name, the current aggregation step, the input and output types of the current aggregation step, and a QueryConfig. However, for some functions that have multiple function signatures and aggregation function classes, these arguments are not enough to determine the correct function.

For example, min() has two signatures. They are implemented through two separate aggregation function classes.
```
min(T) -> T -> T
min(T, bigint) -> row(bigint, array(T)) -> array(T)
```

When AggregateFunctionFactory is called for the intermediate aggregation step with `row(bigint, array(integer))` being both the input and output types, both function signatures match the input and output types, so AggregateFunctionFactory cannot find out for which aggregation function class it should create the function instance. This causes incorrect result of the intermediate step of min(integer, bigint).
https://github.com/facebookincubator/velox/blob/68a968000578059f32562b82c09492009afb4f8e/velox/functions/prestosql/aggregates/MinMaxAggregates.cpp#L898-L977

This particular bug can be resolved by two approaches:
1. Change the intermediate type of the first function signature to `min(T) -> row(T) -> T`. This allows the AggregateFunctionFactory of min() to differentiate the intermediate types for the two function signatures by checking the number of row children. This approach requires only changes inside MinMaxAggregates.cpp. But it doesn't solve the limitation of the aggregation function resolution framework. This also affect backward compatibility of the aggregation intermediate states.
2. Let Aggregate::create() receive the raw input type of the entire aggregation in addition existing arguments and use it to find the correct the aggregation function class. This requires AggregationNode to carry the raw input types and pass them to the HashAggregation operator. We can use the raw input type when resolving the function or when creating the function instance.
    - (a) When resolving the function: The current AggregationFunctionMap is an `std::unordered_map<std::string, AggregateFunctionEntry>`, with each AggregateFunctionEntry consisting of a list of signatures and one AggregateFunctionFactory. We can change it to be an `std::unordered_map<std::string, std::vector<AggregateFunctionEntry>>` and use the raw input type to locate the AggregateFunctionFactory only for the matched signature. In the case of min(), we make one AggregateFunctionEntry for each signature and let `getAggregateFunctionEntry()` to locate the right one and call its factory directly. This requires changes to the registration and resolution APIs of aggregation functions.
    - (b) When creating the function: We don't change AggregationFunctionMap but simply make AggregateFunctionFactory receive an additional argument rawInputType and let AggregateFunctionFactory to use it to differentiate the two signatures. This requires adding the additional argument to the definitions of AggregateFunctionFactory of all existing aggregation functions.

Overall, approach 2 is more preferred. 2(a) makes more sense than 2(b) because differentiation of function signatures should ideally happen during function resolution. On the other hand 2(b) requires fewer changes than 2(a).

(In Presto, the AggregationNode holds a FunctionHandle for each aggregation function call. A FunctionHandle uniquely identify a function implementation and Presto use this FunctionHandle to retrieve the right function instance.)

**Comment by Yuhta** [comment]
Some old discussion on this topic: #2869

**Comment by mbasmanova** [comment]
Presto plans include raw input types for all aggregations regardless of the aggregation step.

Each aggregate function call is described by an Aggregation struct:

```
struct Aggregation {
  CallExpression call = {};
  std::shared_ptr<std::shared_ptr<RowExpression>> filter = {};
  std::shared_ptr<OrderingScheme> orderBy = {};
  bool distinct = {};
  std::shared_ptr<VariableReferenceExpression> mask = {};
  std::shared_ptr<FunctionHandle> functionHandle = {};
  List<std::shared_ptr<RowExpression>> arguments = {};
};

struct CallExpression : public RowExpression {
  String displayName = {};
  std::shared_ptr<FunctionHandle> functionHandle = {};
  Type returnType = {};
  List<std::shared_ptr<RowExpression>> arguments = {};

  CallExpression() noexcept;
};

struct BuiltInFunctionHandle : public FunctionHandle {
  Signature signature = {};

  BuiltInFunctionHandle() noexcept;
};

struct Signature {
  QualifiedObjectName name = {};
  FunctionKind kind = {};
  List<TypeVariableConstraint> typeVariableConstraints = {};
  List<LongVariableConstraint> longVariableConstraints = {};
  TypeSignature returnType = {};
  List<TypeSignature> argumentTypes = {};
  bool variableArity = {};
};
```

CallExpression.arguments specifies the types of the actual arguments for this particular step.

CallExpression.functionHandle is an instance of BuiltInFunctionHandle. BuiltInFunctionHandle.signature.argumentTypes specifies the raw input types.

Here are some examples of raw input types for min functions. These are the same regardless of the aggregation step.

```
SELECT orderkey, min(quantity, 5) FROM lineitem GROUP BY 1

{
  "argumentTypes": [
    "double",
    "bigint"
  ],
  "kind": "AGGREGATE",
  "longVariableConstraints": [],
  "name": "presto.default.min",
  "returnType": "array(double)",
  "typeVariableConstraints": [],
  "variableArity": false
}


SELECT orderkey, min(quantity) FROM lineitem GROUP BY 1

{
  "argumentTypes": [
    "double",
    "bigint"
  ],
  "kind": "AGGREGATE",
  "longVariableConstraints": [],
  "name": "presto.default.min",
  "returnType": "array(double)",
  "typeVariableConstraints": [],
  "variableArity": false
}
```

**Comment by mbasmanova** [comment]
Aggregate::create API takes function name, aggregation step, input types and result type.

```
  static std::unique_ptr<Aggregate> create(
      const std::string& name,
      core::AggregationNode::Step step,
      const std::vector<TypePtr>& argTypes,
      const TypePtr& resultType,
      const core::QueryConfig& config);
```

Aggregate function instances are required to support receiving a mix of raw inputs and intermediate results (used in streaming). 

To avoid needing to change the existing aggregate functions, we can modify HashAggregation operator to always pass raw input types as argTypes to Aggregate::create and use only PARTIAL or SINGLE for 'step'. 

For partial agg: 

- argTypes: raw input types
- step: PARTIAL
- resultType: intermediate type

For final agg:

- argTypes: raw input types
- step: SINGLE
- resultType: final type

For single agg:

- argTypes: raw input types
- step: SINGLE
- resultType: final type

For intermediate agg:

- argTypes: raw input types
- step: PARTIAL
- resultType: intermediate type

**Comment by mbasmanova** [comment]
This is fixed now. Aggregate functions are identified by name + raw input types.
