### ISSUE TITLE
rowVector->resize() make the vector invalid. 

### ISSUE THREAD

**Issue by laithsakka** [facebookincubator/velox#6520]
### Bug description
repo fuzzer issue:

https://app.circleci.com/pipelines/github/facebookincubator/velox/32996/workflows/893f2a58-0fb4-4c62-8b75-dcb81081d802/jobs/212726/artifacts

### System information

NA

**Comment by kgpai** [comment]
Verified that this is fixed by #6543

**Comment by laithsakka** [comment]
Fixed
