### ISSUE TITLE
Implement abort() in Parquet Writer

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#6556]
### Description

abort() is currently not implemented.
I see a segfault if we abort a write query in Prestissimo.

**Comment by duanmeng** [comment]
@majetideepak Could you assign this to me and maybe share some background info about it? I could learn more about the I/O of Velox since I have another task related to Parquet Writer along with this one. Thanks.

**Comment by majetideepak** [comment]
@duanmeng You can see the DWRF writer abort() being fixed here recently: https://github.com/facebookincubator/velox/pull/6497/files
For the Parquet writer, it would be very similar. You can probably extend the test in the PR to test Parquet as well.

**Comment by duanmeng** [comment]
> @duanmeng You can see the DWRF writer abort() being fixed here recently: https://github.com/facebookincubator/velox/pull/6497/files For the Parquet writer, it would be very similar. You can probably extend the test in the PR to test Parquet as well.

@majetideepak Got it, thanks a lot.
