### ISSUE TITLE
simdjson link error when velox is used as a third-party library

### ISSUE THREAD

**Issue by xiaodouchen** [facebookincubator/velox#6564]
### Problem description

Our project uses velox as a third-party library and also uses simdjson. In our project, we use `SIMDJsonExtractor` to implement the json function, but an error occurs during test running. After analyzing the problems, it was found that there was an error in linking simdjson in velox.

The correct link method provided by simdjson official should be "simdjson::simdjson", as shown below.
```
# Create imported target simdjson::simdjson
add_library(simdjson::simdjson STATIC IMPORTED)

set_target_properties(simdjson::simdjson PROPERTIES
   INTERFACE_COMPILE_DEFINITIONS "SIMDJSON_THREADS_ENABLED=1"
   INTERFACE_COMPILE_FEATURES "cxx_std_11"
   INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
   INTERFACE_LINK_LIBRARIES "Threads::Threads"
)
```

But the link in velox is "simdjson", as shown below.
```
add_library(velox_functions_json JsonExtractor.cpp JsonPathTokenizer.cpp
                                  SIMDJsonExtractor.cpp)

target_link_libraries(velox_functions_json velox_exception Folly::folly
                       simdjson)
```

As a result, `-DSIMDJSON_THREADS_ENABLED=1` was not configured when generating libvelox_functions_json.a.

### System information

Velox System Info v0.0.2
Commit: e9354bb74c04a25d41b4d8b4442750e87277b8a9
CMake Version: 3.25.1
System: Darwin-21.4.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 13.1.6.13160021
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 13.1.6.13160021
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX12.3.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.25.1;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by mbasmanova** [comment]
CC: @assignUser @kgpai
