### ISSUE TITLE
Do not allow invalid values in toSourceRow argument of BaseVector::copy

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#6591]
### Bug description

PR #4255 modified BaseVector::copy to allow invalid values in 'toSourceRow'. The change was to silently ignore these. This is problematic as it can hide difficult to track down bugs. We need to remove this check.

(Note that the code was moved from .h to .cpp file in 5989.)

```
void BaseVector::copy(
    const BaseVector* source,
    const SelectivityVector& rows,
    const vector_size_t* toSourceRow) {
  // Check if there are rows that do not exist in 'source'. Remove these from
  // 'ranges'.
  // TODO Update the callers and remove this logic.

  std::vector<CopyRange> ranges;
  if (toSourceRow == nullptr) {
    ...
  } else {
    ranges.reserve(rows.end());
    rows.applyToSelected([&](vector_size_t row) {
      const auto sourceRow = toSourceRow[row];

      // TODO Remove this check or turn it into DCHECK.
      if (sourceRow >= source->size()) {
        return;
      }
      ranges.push_back({sourceRow, row, 1});
    });
  }

  if (ranges.empty()) {
    return;
  }

  copyRanges(source, ranges);
}
```

CC: @laithsakka @bikramSingh91 @Yuhta @oerling 

### System information

n/a

**Comment by Yuhta** [comment]
@bikramSingh91 I tried putting these checks back and hit some fuzzer issue in `Expr::addNulls` and `FieldReference::evalSpecialFormSimplified`.  For the former we need to exclude the existing and added nulls from copy; for the second one I have not find out the reason.
