### ISSUE TITLE
Improve normalized key join probe

### ISSUE THREAD

**Issue by zhli1142015** [facebookincubator/velox#6694]
### Bug description

By profiling below query (with 10 GB TPCDS dataset), I found that almost 1/3 time of `joinNormalizedKeyProbe` is spent in `BaseHashTable::loadTags`. Based on my investigation, there may be two issues: 1. Cache miss caused by random access to tags (`table.table_`); 2. Small group size (4) in `joinNormalizedKeyProbe` that the computation after prefetch command can't overlap the overhead of cache miss.

![image](https://github.com/facebookincubator/velox/assets/10524738/97ae77e6-3707-454f-8eec-827977d73d9c)

For the first one, we can add prefetch command for tags access also. For second one, we could increase the group size from 4 to 64. Here is the change: https://github.com/facebookincubator/velox/pull/6695 .
### HashTableBenchmark Comparsion
I tested with `HashTableBenchmark`, below is the comparsion, we can observe the average **30%+** improvement in normalized key probe.

**Before**
Hit10K: Rows=10000 Hit%=100 NumProbes=10000 hash/row=5.8973 probe clocks=6.2596
 numDistinct=10000 mode=array
Miss10K: Rows=10000 Hit%=5 NumProbes=200000 hash/row=3.42308 probe clocks=6.06464
 numDistinct=12036 mode=array
HitVid10K: Rows=10000 Hit%=100 NumProbes=10000 hash/row=27.6897 probe clocks=7.7238
 numDistinct=10000 mode=array
MissVid10K: Rows=10000 Hit%=5 NumProbes=200000 hash/row=43.8259 probe clocks=7.92049
 numDistinct=12036 mode=array
Hit4M: Rows=4000000 Hit%=100 NumProbes=4000000 hash/row=2.78159 probe clocks=85.8359 f14Probe=121.464 (**141.507%**)
 numDistinct=4000000 mode=normalized key
Miss4M: Rows=4000000 Hit%=5 NumProbes=80000000 hash/row=2.75117 probe clocks=63.0263 f14Probe=88.2935 (**140.09%**)
 numDistinct=4802527 mode=normalized key
Hit32M: Rows=32000000 Hit%=100 NumProbes=32000000 hash/row=2.68998 probe clocks=116.868 f14Probe=135.49 (**115.934%**)
 numDistinct=32000000 mode=normalized key
Miss32M: Rows=32000000 Hit%=5 NumProbes=640000000 hash/row=2.89787 probe clocks=84.0981 f14Probe=103.206 (**122.721%**)
 numDistinct=38398149 mode=normalized key
Hit128M: Rows=128000000 Hit%=100 NumProbes=128000000 hash/row=2.77652 probe clocks=127.767 f14Probe=151.933 (**118.914%**)
 numDistinct=128000000 mode=normalized key

**After**
Hit10K: Rows=10000 Hit%=100 NumProbes=10000 hash/row=3.9611 probe clocks=5.2316
 numDistinct=10000 mode=array
Miss10K: Rows=10000 Hit%=5 NumProbes=200000 hash/row=2.7228 probe clocks=5.83393
 numDistinct=12036 mode=array
HitVid10K: Rows=10000 Hit%=100 NumProbes=10000 hash/row=27.6048 probe clocks=5.3479
 numDistinct=10000 mode=array
MissVid10K: Rows=10000 Hit%=5 NumProbes=200000 hash/row=44.9637 probe clocks=18.5007
 numDistinct=12036 mode=array
Hit4M: Rows=4000000 Hit%=100 NumProbes=4000000 hash/row=2.75155 probe clocks=59.7501 f14Probe=119.414 (**199.856%**)
 numDistinct=4000000 mode=normalized key
Miss4M: Rows=4000000 Hit%=5 NumProbes=80000000 hash/row=2.73869 probe clocks=47.6343 f14Probe=88.3835 (**185.546%**)
 numDistinct=4802527 mode=normalized key
Hit32M: Rows=32000000 Hit%=100 NumProbes=32000000 hash/row=2.74728 probe clocks=78.0082 f14Probe=143.808 (**184.35%**)
 numDistinct=32000000 mode=normalized key
Miss32M: Rows=32000000 Hit%=5 NumProbes=640000000 hash/row=2.93819 probe clocks=58.7963 f14Probe=102.669 (**174.618%**)
 numDistinct=38398149 mode=normalized key
Hit128M: Rows=128000000 Hit%=100 NumProbes=128000000 hash/row=2.96304 probe clocks=90.2933 f14Probe=155.448 (**172.159%**)
 numDistinct=128000000 mode=normalized key
### Gluten Comparsion
![image](https://github.com/facebookincubator/velox/assets/10524738/7e070425-eec6-41b0-aa43-7db77f645f66)
I also tested above query with 1TB TPCDS data by Gluten, below is comparsion:

Before this change:
![image](https://github.com/facebookincubator/velox/assets/10524738/329b082c-ed03-465c-b8fc-6a7bc03cdf00)

After this change:
![image](https://github.com/facebookincubator/velox/assets/10524738/19b19f43-e478-477b-8d1d-8b1a8b469088)

### System information

Velox System Info v0.0.2
Commit: 33a660951a507f42898666a1426df7328af286ab
CMake Version: 3.16.3
System: Linux-5.10.102.1-microsoft-standard-WSL2
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by mbasmanova** [comment]
@zhli1142015 Thank you for investigating and offering an optimization. I'll take a look early next week.
