### ISSUE TITLE
Input type for array_sort should be restricted to "orderable" types

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#6712]
### Bug description

In Presto, input to array_sort is restricted to orderable types. For example, MAP type is not orderable. Velox currently allows MAP inputs.

```
Unexpected parameters (array(map(boolean,tinyint))) for function array_sort. Expected: array_sort(array(E)) E:orderable, array_sort(array(T), function(T,T,integer)) T
```

This issue was discovered by running AggregationFuzzer with Presto as source of truth.

CC: @laithsakka

### System information

n/a

**Comment by mbasmanova** [comment]
@duanmeng Anything left to do here?

**Comment by duanmeng** [comment]
@mbasmanova No, left nulls check in https://github.com/facebookincubator/velox/issues/6713, which is not related to this issue.
