### ISSUE TITLE
array_sort should fail if array contains NULL

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#6713]
### Bug description

In Presto, array_sort function doesn't allow input arrays that contain nulls.

```
com.facebook.presto.spi.PrestoException: Array contains elements not supported for comparison
	at com.facebook.presto.operator.scalar.ArraySortFunction$2.compare(ArraySortFunction.java:101)
	at com.facebook.presto.operator.scalar.ArraySortFunction$2.compare(ArraySortFunction.java:91)
...
Caused by: com.facebook.presto.common.NotSupportedException: ARRAY comparison not supported for arrays with null elements
	at com.facebook.presto.common.type.TypeUtils.checkElementNotNull(TypeUtils.java:180)
	at com.facebook.presto.common.type.ArrayType.compareTo(ArrayType.java:124)
	at com.facebook.presto.operator.scalar.ArraySortFunction$2.compare(ArraySortFunction.java:97)
```

This issue was discovered by running AggregationFuzzer with Presto as source of truth.

CC: @laithsakka @duanmeng 

### System information

n/a

**Comment by duanmeng** [comment]
@mbasmanova This should be the same issue as we discussed in https://github.com/facebookincubator/velox/issues/6314#issuecomment-1725021636. I will fix this issue after that.

**Comment by mbasmanova** [comment]
@duanmeng Thanks. This is similar issue. The only difference is array_sort is a scalar function, but the other discussion was about aggregate functions.

**Comment by duanmeng** [comment]
This happens in the case of complex types. For example,

**Scalar Type**
```SQL
presto> SELECT array_sort(col0) FROM ( VALUES (array [2, null, 1])) AS t(col0);
    _col0
--------------
 [1, 2, null]
```
**Complex Type** (*The partial success and failure issue should be fixed too*)
```SQL
presto> SELECT array_sort(col0) FROM ( VALUES (array [array [1, 2, 3, 4], array [2, null, 3]])) AS t(col0);
            _col0
------------------------------
 [[1, 2, 3, 4], [2, null, 3]]

presto> SELECT array_sort(col0) FROM ( VALUES (array [array [1, 2, 3, 4], array [1, null, 3]])) AS t(col0);

Query 20230925_113531_00074_6r5h7 failed: Array contains elements not supported for comparison
```

**Comment by mbasmanova** [comment]
@duanmeng Presto semantics are a bit challenging. array_sort applied to arrays of complex types with nested nulls may or may not fail depending on whether the sorting logic needs to compare the nulls to decide the order. In Velox, one option would be to (1) check all array elements before sorting and throw if any element contains null; (2) check for contains-nulls only during comparison (Presto's implementation). Option (2) promises to match Presto's semantics (however weird these are), but I'm not sure how to convince myself that the results won't depend on the specific sorting algorithm being used. We could start with option (2) and if we find that this produces inconsistent results, switch to option (1).

```
presto:di> select array_sort(array[array[1, null], array[2, null]]);
         _col0
------------------------
 [[1, null], [2, null]]
(1 row)

Query 20230926_061441_03625_sq8kq, FINISHED, 1 node
Splits: 5 total, 5 done (100.00%)
174ms [0 rows, 0B] [0 rows/s, 0B/s]

presto:di> select array_sort(array[array[1, null], array[1, 2]]);
Query 20230926_061447_03626_sq8kq failed: Array contains elements not supported for comparison
```

**Comment by mbasmanova** [comment]
Opened an issue in prestodb repo to clarify whether existing semantics are intentional: https://github.com/prestodb/presto/issues/20965

**Comment by mbasmanova** [comment]
@duanmeng Are you still interested to work on this? Anything blocking?

**Comment by duanmeng** [comment]
@mbasmanova Yes, I will keep working on it.
