### ISSUE TITLE
sum(bigint) needs to check for overflow

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#6714]
### Bug description

In Presto, SUM(BIGINT) checks for overflow. In Velox, it doesn't.

```
com.facebook.presto.spi.PrestoException: bigint addition overflow: 4098410247810426670 + 5602492956270666201
	at com.facebook.presto.type.BigintOperators.add(BigintOperators.java:75)
	at com.facebook.presto.operator.aggregation.LongSumAggregation.sum(LongSumAggregation.java:37)
	at com.facebook.presto.$gen.BigintBigintSumGroupedAccumulator_20230924_052933_4062.addInput(Unknown Source)
```

This issue was discovered by running AggregationFuzzer with Presto as source of truth.

CC: @laithsakka @duanmeng 

### System information

n/a

**Comment by duanmeng** [comment]
@mbasmanova It seems that there is already an overflow check for `sum(bigint)` in https://github.com/facebookincubator/velox/blob/main/velox/functions/prestosql/aggregates/SumAggregate.h#L152, and related test in https://github.com/facebookincubator/velox/blob/main/velox/functions/prestosql/aggregates/tests/SumTest.cpp#L596

**Comment by mbasmanova** [comment]
@duanmeng You are correct. I tried reproducing this again, but can't. I'm going to close this issue and reopen if I see it again. Thanks.
