### ISSUE TITLE
checksum(ROW) doesn't handle null values correctly

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#6715]
### Bug description

When applied to ROW type inputs, checksum Presto aggregate function doesn't process null values properly. It ends up accessing individual struct fields on rows where top-level struct is null causing either wrong results or failures. Buggy logic is in `PrestoHasher::hash<TypeKind::ROW>`.

One example of a failure. 

```
Reason: Could not convert Timestamp(-6799976246779207263, 11646767826930344353) to milliseconds, Exception: VeloxUserError
```

This issue was discovered by running AggregationFuzzer with Presto as source of truth.

CC: @laithsakka @duanmeng @kgpai 

### System information

n/a

**Comment by laithsakka** [comment]
https://app.circleci.com/pipelines/github/facebookincubator/velox/34623/workflows/7c4e8fee-7c6d-4fa8-9dc8-145e85be3229/jobs/226628/steps
this one has different message 
Reason: Could not convert Timestamp(169838869991752, 608000000) to nanoseconds, Exception: VeloxUserError
