### ISSUE TITLE
set_union applied to all null values should return an empty array, not null

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#6720]
### Bug description

When applies to all null inputs, set_union in Presto returns an empty array. Velox returns null. 

This could be a bug in Presto since most aggregate functions ignore null inputs.

```
presto> select set_union(x) from (select cast(null as array(bigint))) as t(x);
 _col0
-------
 []
```

This issue was discovered by running AggregationFuzzer with Presto as source of truth.

CC: @laithsakka 

### System information

n/a

**Comment by laithsakka** [comment]
what diff does
"running AggregationFuzzer with Presto as source of truth"

**Comment by mbasmanova** [comment]
> what diff does "running AggregationFuzzer with Presto as source of truth"

There are multiple changes across Presto and Velox repos that are requires to run this. One of these is https://github.com/facebookincubator/velox/pull/6701 At this point, I don't have all the PRs submitted.

**Comment by mbasmanova** [comment]
Confirmed that Presto semantics are on purpose:

```
...The reason is so that SET_UNION  can be a drop-in replacement for 
ARRAY_DISTINCT(FLATTEN(ARRAY_AGG(x)))
``

**Comment by mbasmanova** [comment]
To summarize:

```
with all null input:

set_agg => [null]
set_union => []
array_agg => null
```
