### ISSUE TITLE
undefined reference to `typeinfo for google::protobuf::io::ZeroCopyOutputStream' after #5914

### ISSUE THREAD

**Issue by baibaichen** [facebookincubator/velox#6744]
### Problem description

After https://github.com/facebookincubator/velox/pull/5914, I got the following link issue
```
/usr/bin/ld: velox/dwio/common/compression/libvelox_dwio_common_compression.a(Compression.cpp.o): in function `google::protobuf::io::ZeroCopyOutputStream::ZeroCopyOutputStream()':
/home/chang/SourceCode/velox/cmake-build-debug-system/_deps/protobuf-src/src/google/protobuf/io/zero_copy_stream.h:193: undefined reference to `vtable for google::protobuf::io::ZeroCopyOutputStream'
/usr/bin/ld: velox/dwio/common/compression/libvelox_dwio_common_compression.a(Compression.cpp.o): in function `google::protobuf::io::ZeroCopyOutputStream::~ZeroCopyOutputStream()':
/velox/cmake-build-debug-system/_deps/protobuf-src/src/google/protobuf/io/zero_copy_stream.h:194: undefined reference to `vtable for google::protobuf::io::ZeroCopyOutputStream'
/usr/bin/ld: velox/dwio/common/libvelox_dwio_common.a(OutputStream.cpp.o):(.[data.rel.ro](http://data.rel.ro/)._ZTIN8facebook5velox4dwio6common20BufferedOutputStreamE[_ZTIN8facebook5velox4dwio6common20BufferedOutputStreamE]+0x10): undefined reference to `typeinfo for google::protobuf::io::ZeroCopyOutputStream'
```
Here are my  cmake option

```
-DVELOX_DEPENDENCY_SOURCE=BUNDLED
-DVELOX_ENABLE_EXAMPLES=ON
-DVELOX_ENABLE_PARQUET=ON
-DVELOX_BUILD_TESTING=ON
-DVELOX_ENABLE_BENCHMARKS=ON
-DVELOX_ENABLE_BENCHMARKS_BASIC=ON
```

I checked probobuf cmake  file and make sure **disbale RTTI is OFF**

Not sure how to fix it.

### System information

```
 cc --version
cc (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

cmake is 3.26.4

**Comment by mbasmanova** [comment]
CC: @nmahadevuni  @yingsu00 @Yuhta

**Comment by nmahadevuni** [comment]
@baibaichen @mbasmanova I'm looking into this issue.

**Comment by baibaichen** [comment]
More information.
1. velox_dwio_parquet_reader_test failed
2. velox_dwio_parquet_tpch_test  success.

**Comment by nmahadevuni** [comment]
@baibaichen Is this on the latest commit? What are the build configs? I have been running these tests with multiple PRs and I see them passing. Can you share the error?

**Comment by baibaichen** [comment]
@nmahadevuni  IIUC, `scripts/setup-macos.sh` and `scripts/setup-ubuntu.sh` will install  `libsnappy-dev`. I use the following cmake option.

```
-DVELOX_DEPENDENCY_SOURCE=BUNDLED  # !!!
-DVELOX_ENABLE_EXAMPLES=ON
-DVELOX_ENABLE_PARQUET=ON
-DVELOX_BUILD_TESTING=ON
-DVELOX_ENABLE_BENCHMARKS=ON
-DVELOX_ENABLE_BENCHMARKS_BASIC=ON
```

If you dind't define `VELOX_DEPENDENCY_SOURCE`,  velox would link system libprotobuf, may be that's why you can't reproduce the issue.

**Comment by baibaichen** [comment]
> @baibaichen Is this on the latest commit? What are the build configs? I have been running these tests with multiple PRs and I see them passing. Can you share the error?

Related with PR https://github.com/facebookincubator/velox/pull/5914/.  After this PR, `velox_dwio_native_parquet_reader ` will depends on `${Protobuf_LIBRARIES}`

I find if `velox_dwio_parquet_reader_test` depends on velox_hive_connector, then linker will success.  The magic is **OBJECT**
![image](https://github.com/facebookincubator/velox/assets/3688732/c53cec92-23fd-4747-89ac-ce84fffe69d7).

See https://github.com/facebookincubator/velox/pull/2897.

**Comment by nmahadevuni** [comment]
@baibaichen I tried building in BUNDLED mode on Ubuntu. Even without my changes, there are macro redefinition errors between Arrow and Glog dependencies. Following is the error I get

`In file included from /velox/velox/dwio/parquet/reader/PageReader.cpp:17:
In file included from /velox/./velox/dwio/parquet/reader/PageReader.h:20:
In file included from /velox/./velox/dwio/common/BitConcatenation.h:17:
In file included from /velox/./velox/buffer/Buffer.h:23:
In file included from /velox/./velox/common/base/CheckedArithmetic.h:22:
In file included from /velox/./velox/common/base/Exceptions.h:24:
velox/_build/release/_deps/glog-build/glog/logging.h:1381:9: error: 'DCHECK_GE' macro redefined [-Werror,-Wmacro-redefined]
#define DCHECK_GE(val1, val2) \
        ^
/velox/_build/release/third_party/arrow_ep/install/include/arrow/util/logging.h:146:9: note: previous definition is here
#define DCHECK_GE ARROW_DCHECK_GE
        ^`

Didn't you see this errors?

**Comment by baibaichen** [comment]
Yes，I saw that, but it's just **warning** in my case. I don't know how to set `warning as error`.

**Comment by czentgr** [comment]
I can repro the issue on Ubuntu when building shared libraries (not using -DVELOX_DEPENDENCY_SOURCE=BUNDLED).
Trying out the suggestion from @nmahadevuni 

> Can you move this protobuf link library to velox_dwio_common and check of it fixes the issue?
I turned off shared libs and turned on -DVELOX_DEPENDENCY_SOURCE=BUNDLED and after the suggestion the build passed.

I think the problem exists only on Ubuntu. On Mac I've not had problems.

**Comment by baibaichen** [comment]
@czentgr 

> I turned off shared libs and turned on -DVELOX_DEPENDENCY_SOURCE=BUNDLED and after the suggestion the build passed.

Which option is used to disable shared libraries? I always thought the default was a static link.

Thanks
Chang

**Comment by czentgr** [comment]
@baibaichen The issue also occurred when building shared libraries. Yes, the default is static but I was fixing problems when building shared libraries and ran into the same error.

The suggestion by @nmahadevuni fixed the issue.

**Comment by baibaichen** [comment]
@czentgr Thanks, I see. I did test building on ubuntu.

So @nmahadevuni,  It looks like `Static link with -DVELOX_DEPENDENCY_SOURCE=BUNDLED` is ok on mac but failed on ubuntun

**Comment by majetideepak** [comment]
This is likely fixed now
