### ISSUE TITLE
Refactor velox/functions/common/ArrayIntersect.cpp to support array_except()

### ISSUE THREAD

**Issue by pedroerp** [facebookincubator/velox#68]
The main logic is common. Refactor ArrayIntersect.cpp to provide array_except() semantic, register it as a function with the available signatures in Presto, and add unit tests. 

This link has useful information: https://prestodb.io/blog/2020/12/04/typedset

**Comment by mbasmanova** [comment]
@aditi-pandit This is done, right? Should we close this issue?

**Comment by aditi-pandit** [comment]
Yes, the main function is done. But I didn't get to the microbenchmark suggested by Pedro. It might be better to separate the two. wdyt ?

**Comment by pedroerp** [comment]
Regarding the benchmark: it would be nice to evaluate if the current approach is faster for primitive types as well - I remember there was a discussion that maybe for primitive types it could be faster to just create a new vector. Not a blocker though. 

We could even create a separate issue to track that, in case some of the new folks learning about the project would like to claim it.
