### ISSUE TITLE
Add support for LIKE with non-constant pattern

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#6804]
### Bug description

Some production queries use LIKE with a non-constant pattern. We need to find a way to support this safely in Velox.

The default approach of compiling regular expression for each row is very dangerous as it can bring down the machine by using too must CPU.

An alternative is to allow only small number of different patterns per query and fail if we see more. Also, we should recognize patterns that do not require regex and exclude these from the hard limit.

CC: @laithsakka @amitkdutta 

### System information

n/a

**Comment by mbasmanova** [comment]
CC: @aditi-pandit

**Comment by laithsakka** [comment]
This PR might be related in a way 

https://l.workplace.com/l.php?u=https%3A%2F%2Fgithub.com%2Ffacebookincubator%2Fvelox%2Fpull%2F6516&h=AT3h-Q7O9CSNremy-7NTxjzLRWIewarcgQnAf1mpCOxZ2Zo4O6ILvYCbvjrOX3tBq3QCX0QvsfVg1sWMYyFZTc9BbrhaDiEpu0yOjp_ndLujK4uFLOMFoB4MQtioUT0IbwFRBmuthOjIFlRhUsMLL6ExRr3bf_0_52-UcXeps1VrCjsWtw

**Comment by aditi-pandit** [comment]
@mbasmanova : Do you have an e2e Presto SQL example query for this. Would help understand this better.

**Comment by mbasmanova** [comment]
> @mbasmanova : Do you have an e2e Presto SQL example query for this ? Would help understand this better.

`SELECT a LIKE b FROM t`

**Comment by laithsakka** [comment]
working on this

**Comment by mbasmanova** [comment]
Added in #6917

Thank you, @laithsakka .
