### ISSUE TITLE
LosslessTimestamp serialization does not work properly during spilling

### ISSUE THREAD

**Issue by laithsakka** [facebookincubator/velox#6837]
### Bug description

LosslessTimestamp is used to allow prestoSerializer to serialize timestamp without loss of time precision, since by default prestoSerializer uses a single milli stored int64_t to represent time when serializing it which can lead to loss of precison https://github.com/facebookincubator/velox/pull/2279. 

Unfortunately, LosslessTimestamp does not work right, because not all time stamps fit in int64_t as nanos, this should be fixed to write two bytes (Seconds and nanons) and read two bytes instead

Using millis in int64_t is ok for presto, since presto TimeStamp uses milli precision and has limits the guarantee that timestamp fits in int64_t as millis.

For now I will change the default config for spiller to turn of LosslessTimestamp. This task is fix LosslessTimestamp serialization, and to add a config that would enable for non presto workload.

We probably do not want to enable it for presto workload since it will add more memory that is not needed

### System information

NA

**Comment by mbasmanova** [comment]
CC: @rui-mo

**Comment by mbasmanova** [comment]
> For now I will change the default config for spiller to turn of LosslessTimestamp. This task is fix LosslessTimestamp serialization, and to add a config that would enable for non presto workload.

Instead of disabling buggy code path, let's delete it altogether.

@rui-mo Rui, can someone from Gluten team help make this work properly for Spark?

**Comment by laithsakka** [comment]
@mbasmanova fixing it might be easier than deleting that path a config is propagated, ones fixed the whole code will be put back. I am not really sure if removing the whole path is the best.

**Comment by laithsakka** [comment]
This is fixed

**Comment by laithsakka** [comment]
https://www.internalfb.com/diff/D49796384

**Comment by rui-mo** [comment]
@mbasmanova Sorry for the late reply. We just come back from holiday.
In Spark timestamp type is stored as microseconds, and do we need to add another config for serializing and deserializing timestamp as micro?
Link: [TimestampType](https://github.com/apache/spark/blob/master/sql/api/src/main/scala/org/apache/spark/sql/types/TimestampType.scala#L23-L32)

**Comment by mbasmanova** [comment]
@rui-mo Thank you, Rui.
