### ISSUE TITLE
Parquet compression logic is broken for ZSTD, ZLIB, LZ4

### ISSUE THREAD

**Issue by nmahadevuni** [facebookincubator/velox#6890]
### Bug description

After https://github.com/facebookincubator/velox/pull/6586 , the Parquet compression code is broken. In `dwio/parquet/tests/reader/E2EFilterTest.cpp`, compression tests are broken. The tests are run only for Snappy and Uncompressed and ZSTD, GZIP and LZ4 tests are skipped since ARROW_WITH_ZLIB, ARROW_WITH_LZ4 and ARROW_WITH_ZSTD are not defined in Velox.

 I tried to define these in the root CMakeLists.txt when VELOX_ENABLE_PARQUET is ON, it then fails with below linking errors.

`Undefined symbols for architecture arm64:
  "facebook::velox::parquet::arrow::util::internal::MakeGZipCodec(int, facebook::velox::parquet::arrow::util::GZipFormat, std::__1::optional<int>)", referenced from:
      facebook::velox::parquet::arrow::util::Codec::Create(facebook::velox::parquet::arrow::Compression::type, facebook::velox::parquet::arrow::util::CodecOptions const&) in libvelox_dwio_arrow_parquet_writer_util_lib.a(Compression.cpp.o)
  "facebook::velox::parquet::arrow::util::internal::MakeZSTDCodec(int)", referenced from:
      facebook::velox::parquet::arrow::util::Codec::Create(facebook::velox::parquet::arrow::Compression::type, facebook::velox::parquet::arrow::util::CodecOptions const&) in libvelox_dwio_arrow_parquet_writer_util_lib.a(Compression.cpp.o)
  "facebook::velox::parquet::arrow::util::internal::MakeLz4RawCodec(int)", referenced from:
      facebook::velox::parquet::arrow::util::Codec::Create(facebook::velox::parquet::arrow::Compression::type, facebook::velox::parquet::arrow::util::CodecOptions const&) in libvelox_dwio_arrow_parquet_writer_util_lib.a(Compression.cpp.o)
  "facebook::velox::parquet::arrow::util::internal::MakeLz4FrameCodec(int)", referenced from:
      facebook::velox::parquet::arrow::util::Codec::Create(facebook::velox::parquet::arrow::Compression::type, facebook::velox::parquet::arrow::util::CodecOptions const&) in libvelox_dwio_arrow_parquet_writer_util_lib.a(Compression.cpp.o)
  "facebook::velox::parquet::arrow::util::internal::MakeLz4HadoopRawCodec()", referenced from:
      facebook::velox::parquet::arrow::util::Codec::Create(facebook::velox::parquet::arrow::Compression::type, facebook::velox::parquet::arrow::util::CodecOptions const&) in libvelox_dwio_arrow_parquet_writer_util_lib.a(Compression.cpp.o)
ld: symbol(s) not found for architecture arm64`

### System information

Velox System Info v0.0.2
Commit: bf350ece78f9e3953120d80ceabbec64b7163e6c
CMake Version: 3.27.6
System: Darwin-22.6.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 14.0.3.14030022
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 14.0.3.14030022
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.27.6;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by nmahadevuni** [comment]
@pedroerp @majetideepak

**Comment by majetideepak** [comment]
@nmahadevuni, we are fixing them. GZip and ZSTD PRs are here https://github.com/facebookincubator/velox/pull/6805
and here https://github.com/facebookincubator/velox/pull/6835

**Comment by nmahadevuni** [comment]
> @nmahadevuni, we are fixing them. GZip and ZSTD PRs are here #6805 and here #6835

Anyone's working on LZ4?

**Comment by majetideepak** [comment]
There is no PR for LZ4.

**Comment by yingsu00** [comment]
Most of the code copied already exist in dwio::common::compression. I created https://github.com/facebookincubator/velox/issues/6901 for future work.

**Comment by nmahadevuni** [comment]
> Looks like all is supported again; @nmahadevuni could you double check if anything is now working as expected?

All supported codecs are working now. Thanks!
