### ISSUE TITLE
Add an easy way to create array-of-arrays dataset for testing

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#6896]
### Description

PR #6816 introduced an easy way to create arrays for testing using JSON. 

It would be nice to extend this solution to allow creating arrays-of-arrays:

```
makeArrayOfArraysFromJson<int32_t>({
   "[[1, 2], [2, 3, 4], [null, 7]]",
   "[[1, 3, 7, 9], []]",
   ...
});
```

This can be used to simplify tests in velox/functions/prestosql/tests/ArrayAllMatchTest.cpp, ArrayAnyMatchTest.cpp, ArrayNoneMatchTest.cpp.

CC: @aditi-pandit @duanmeng

**Comment by ashokku2022** [comment]
Thanks @mbasmanova, assigning it to @soumiiow from IBM.

**Comment by mbasmanova** [comment]
@soumiiow Are you working on this?

**Comment by ashokku2022** [comment]
@mbasmanova Thank you Masha for following up, appreciate it!
Soumya has opened PR inside IBM repo. to go through the internal code review process first and once it is approved, she will open PR against OSS. ETA is early next week.
Work is in progress and if you want to see an early version of PR, Soumya could open an OSS draft PR. Please let us know. Thanks!

**Comment by mbasmanova** [comment]
@ashokku2022 Thank you for sharing the update. Please, create a WIP PR to provide visibility.

**Comment by mbasmanova** [comment]
Folks, any update on this?

**Comment by ashokku2022** [comment]
@mbasmanova Thanks for checking, appreciate it!
PR work is in progress. Soumya has been getting feedback from Aditi and has been updating the PR. The latest one was an hour ago. I believe, soon it should be approved by Aditi and then Soumya would reach out to you for your invaluable feedback.
