### ISSUE TITLE
Refactor velox/functions/common/ArrayIntersect.cpp to support array_union()

### ISSUE THREAD

**Issue by pedroerp** [facebookincubator/velox#69]
The main logic is common (union needs to de-duplicate elements). Refactor ArrayIntersect.cpp to provide array_union() semantic, register it as a function with the available signatures in Presto, and add unit tests.

This link has useful information: https://prestodb.io/blog/2020/12/04/typedset

**Comment by ankur4369** [comment]
I would like to work on this if that is okay

**Comment by pedroerp** [comment]
Just double checking that this is not done yet. I remember @aditi-pandit worked on this codebase.

**Comment by aditi-pandit** [comment]
array_union is not implemented. array_except, array_intersect and array_join are.
