### ISSUE TITLE
Avoid memcpy in vread by pass pre allocated buffer

### ISSUE THREAD

**Issue by Yohahaha** [facebookincubator/velox#6953]
### Description

Current implementation of vread in BufferedInput will pass empty IOBuf to File#preadv then allocate bytes from managed memory pool for hold above IOBuf by memcpy (cursor.pull). Curious why not pass pre-created IOBuf to File#preadv?

https://github.com/facebookincubator/velox/blob/024f1ea4c545179f8e6af18e399c2399700cba96/velox/dwio/common/BufferedInput.cpp#L45-L60

**Comment by Yuhta** [comment]
Because the memory must be allocated from our pools.  Is there a way to make `IOBuf` to use our memory pool?
