### ISSUE TITLE
Added task holder in split preload may lead dropPool failure

### ISSUE THREAD

**Issue by Yohahaha** [facebookincubator/velox#6994]
### Bug description

In Gluten, we initialize/release MemoryManager instance when Spark Task begin/finished, MemoryManager's lifecycle was not static scope but per Spark Task.

When enable split preload feature in Gluten, it will throw `The dropped memory pool xxx not found` occasionally. After remove `taskHolder` below, it works.
https://github.com/facebookincubator/velox/pull/4849/files#diff-b04232f155cc15faca93b69cf34dd80e29b534a4e54dd774bf8bdbedbfc66d6bR262-R265

IO executor hold shared ref of Task which contains shared ref of MemoryPool from QueryCtx, MemoryManager will be released when Spark Task finished, but Task shared ref in IO thread could be the last and released after Spark Task finished, it will invoke dropPool to a invalid MemoryManager.

Some thoughts:
1. Remove `taskHolder` in split preload logic. It may break what PR #4849 want fixed, and can not prevent introduce new shared ref in following patches.
2. Change MemoryPool usage in QueryCtx from shared pointer to raw pointer, manage passed MemoryPool's lifecycle out of QueryCtx.

Gluten issue: https://github.com/oap-project/gluten/issues/3364
CC @zhli1142015 @zhztheplayer 

### System information

Velox System Info v0.0.2
Commit: Not in a git repo.
CMake Version: 3.20.2
System: Linux-5.10.134-14.al8.x86_64
Arch: x86_64
C++ Compiler: /usr/lib64/ccache/c++
C++ Compiler Version: 10.2.1
C Compiler: /usr/lib64/ccache/cc
C Compiler Version: 10.2.1
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

### Relevant logs

```bash
terminate called after throwing an instance of 'facebook::velox::VeloxRuntimeError'
  what():  Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: The dropped memory pool WholeStageIterator_root not found
Retriable: False
Function: dropPool
File: /var/git/Velox/velox/common/memory/Memory.cpp
Line: 181
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox6memory13MemoryManager8dropPoolEPNS1_10MemoryPoolE
# 4  _ZN8facebook5velox6memory14MemoryPoolImplD2Ev
# 5  _ZNSt23_Sp_counted_ptr_inplaceIN8facebook5velox4core8QueryCtxESaIS3_ELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv
# 6  _ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_releaseEv
# 7  _ZN8facebook5velox4exec4TaskD2Ev
# 8  _ZNSt15_Sp_counted_ptrIPN8facebook5velox4exec4TaskELN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv
# 9  _ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_releaseEv
# 10 _ZN5folly6detail8function13DispatchSmall4execIZZN8facebook5velox4exec9TableScan12checkPreloadEvENKUlSt10shared_ptrINS5_9connector14ConnectorSplitEEE_clESB_EUlvE_EEmNS1_2OpEPNS1_4DataESG_
# 11 _ZN5folly18ThreadPoolExecutor7runTaskERKSt10shared_ptrINS0_6ThreadEEONS0_4TaskE
# 12 _ZN5folly6detail8function14FunctionTraitsIFvvEE7callBigIZNS_20IOThreadPoolExecutor3addENS_8FunctionIS3_EENSt6chrono8durationIlSt5ratioILl1ELl1000EEEES8_EUlvE_EEvRNS1_4DataE
# 13 _ZN5folly23AtomicNotificationQueueINS_8FunctionIFvvEEEE5driveIRNS_9EventBase10FuncRunnerEEEbOT_
# 14 _ZThn40_N5folly32EventBaseAtomicNotificationQueueINS_8FunctionIFvvEEENS_9EventBase10FuncRunnerEE12handlerReadyEt
# 15 event_process_active_single_queue.isra.0
# 16 event_base_loop
# 17 _ZN5folly9EventBase8loopMainEib
# 18 _ZN5folly9EventBase8loopBodyEib
# 19 _ZN5folly9EventBase4loopEv
# 20 _ZN5folly9EventBase11loopForeverEv
# 21 _ZN5folly20IOThreadPoolExecutor9threadRunESt10shared_ptrINS_18ThreadPoolExecutor6ThreadEE
# 22 _ZN5folly6detail8function14FunctionTraitsIFvvEE9callSmallISt5_BindIFMNS_18ThreadPoolExecutorEFvSt10shared_ptrINS7_6ThreadEEEPS7_SA_EEEEvRNS1_4DataE
# 23 execute_native_thread_routine
# 24 start_thread
# 25 clone
```

**Comment by zhztheplayer** [comment]
@Yohahaha I think we'd find a way to assign a memory pool with longer lifecycle (e.g. a global static pool) to background threads. That would fix a series of possible issues like this one.
