### ISSUE TITLE
GROUP BY CUBE generates empty results when input is empty

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#7013]
### Bug description

GROUP BY CUBE should always generate at least one row.

```
assertQuery("SELECT orderkey FROM orders WHERE orderkey < 0 GROUP BY CUBE (orderkey)");

java.lang.AssertionError: For query: 
 SELECT orderkey FROM orders WHERE orderkey < 0 GROUP BY CUBE (orderkey)
not equal
Actual rows (up to 100 of 0 extra rows shown, 0 rows in total):
    
Expected rows (up to 100 of 1 missing rows shown, 1 rows in total):
    [null]
```

CC: @zacw7 @aditi-pandit 

### System information

n/a

**Comment by mbasmanova** [comment]
In Java, HashAggregationOperator has an extra flag (produceDefaultOutput) and a list of group IDs for empty grouping sets. This triggers logic to produce extra output when there is no input. HashAggregation operator in Velox doesn't have this logic and AggregationNode in Velox is missing fields to trigger this logic.

```
    private final List<Integer> globalAggregationGroupIds;
    private final boolean produceDefaultOutput;

if (!inputProcessed && produceDefaultOutput) {
    // global aggregations always generate an output row with the default aggregation output (e.g. 0 for COUNT, NULL for SUM)
    finished = true;
    return getGlobalAggregationOutput();
}
```

This flag is set based on whether there are "empty" grouping sets (which is the case for CUBE aggregations).

```
public boolean hasDefaultOutput()
{
    return hasEmptyGroupingSet() && (step.isOutputPartial() || step.equals(SINGLE));
}
```

**Comment by aditi-pandit** [comment]
@mbasmanova Interestingly we too had an issue for this, and I had reached the same conclusion as well which I was going to discuss with you.

https://github.com/prestodb/presto/issues/20911
Failing SQL
`SELECT SUM(CAST(quantity AS BIGINT)) FROM lineitem WHERE quantity < 0 GROUP BY GROUPING SETS ((), ())`

The HashAgg operator was handling it with special code https://github.com/prestodb/presto/blob/master/presto-main/src/main/java/com/facebook/presto/operator/HashAggregationOperator.java#L622 which we don't have in C++.

**Comment by mbasmanova** [comment]
Somewhat related: https://github.com/prestodb/presto/pull/7239

The implementation is AggregationNode::hasDefaultOutput seems unnecessarily verbose.

```
    public boolean hasDefaultOutput()
    {
        return hasEmptyGroupingSet() && (step.isOutputPartial() || step.equals(SINGLE));
    }
```

It can be simplified to

```
    public boolean hasDefaultOutput()
    {
        return hasEmptyGroupingSet() && !step.equals(FINAL));
    }
```

**Comment by aditi-pandit** [comment]
Fixed by
https://github.com/facebookincubator/velox/pull/7112
https://github.com/facebookincubator/velox/pull/7353
