### ISSUE TITLE
json_extract fails with "Invalid JSON path"

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#7043]
### Bug description

In Presto, the query succeeds:

```
presto:di> select cast(json_extract('[{"k":3399}]', '$.[*].k') as array(bigint));
 _col0
--------
 [3399]
(1 row)
```

in Velox, fails:

```
TEST_F(JsonFunctionsTest, jsonExtract) {
  auto jsonExtract = [&](std::optional<std::string> json,
                         const std::string& path) {
    return evaluateOnce<std::string>(
        "json_extract(c0, c1)",
        makeRowVector(
            {makeJsonVector(json), makeFlatVector<std::string>({path})}));
  };

   jsonExtract("[{\"k\":3399}]", "$.[*].k");

Reason: Invalid JSON path: $.[*].k
Retriable: False
Context: json_extract(c0, c1)
Top-Level Context: Same as context.
Function: SIMDJsonExtractor
File: /Users/mbasmanova/cpp/velox-1/./velox/functions/prestosql/json/SIMDJsonExtractor.h
Line: 76
```

CC: @aditi-pandit @zacw7 @kevinwilfong @kgpai 

### System information

n/a

**Comment by kevinwilfong** [comment]
If I add the following to testFullJsonExtract() in Presto it fails the same way
https://github.com/prestodb/presto/blob/0e52fc3247542b2753d3f750acc6aa1f8e1ca507/presto-main/src/test/java/com/facebook/presto/operator/scalar/TestJsonExtract.java#L258

assertEquals(doJsonExtract("[{\"k\":3399}]", "$.[*].k"), "[3399]");

com.facebook.presto.spi.PrestoException: Invalid JSON path: '$.[*].k'

are we using a different version internally?

**Comment by kevinwilfong** [comment]
The test in Presto uses JsonPathTokenizer, while the json_extract UDF in Presto uses JayWay's JsonPath object.

JayWay's JsonPath supports a much richer syntax than JsonPathTokenizer that goes way beyond $.[*]

https://github.com/json-path/JsonPath#path-examples
