### ISSUE TITLE
Support partial processing of a range of consecutive rows that need to be processed in Partitioned 

### ISSUE THREAD

**Issue by bikramSingh91** [facebookincubator/velox#7048]
### Description

Issue: We noticed that in cases where there is no partitioning and round robin partitioning, we end up generating a [single IndexRange with the full set of input rows](https://github.com/facebookincubator/velox/blob/main/velox/exec/PartitionedOutput.cpp#L265-L267) to be processed by the serializer. The current implementation only checks if it needs to flush the serialized data after processing an IndexRange. With this we can hit OOM if the full set of input rows take up a lot of memory.

There are 2 possible solutions here:
  1. We add IndexRanges of size 1 for each row like we do in the case of regular partitioning.
  2. We support partial processing of large IndexRanges

We go with option 2 for the following reason:
Ans. The whole point of having IndexRange(s) is because the serializer can [optimize copying for ranges of values](https://github.com/facebookincubator/velox/blob/main/velox/serializers/PrestoSerializer.cpp#L1243)/chunks of memory space. If we add a single row each then we lose all the work gone into optimizing that behavior.

Additionally, as an optimization, we can also identify consecutive row idx being added to Destination and include them in a single row.

Multiple alternatives to implement partial range support:

- Currently exploring: 
  - Handling partial ranges inside detail::Destination::advance()
  - Save state related to an IndexRange being partially processed
  - Handle this in a separate codepath
  - I have a few implementation ideas that I am trying out, will update more once I converge on one.
    - Saving state and manipulating the IndexRange inplace before sending it to the serializer
    - Managing a separate reusable vector of indexRanges, making it easier to split and ranges and manage them separately without touching the original vector of indexRanges
  - Cons: extra manipulation and state required, but might be worth the cost

- Other alternatives:
  - Split the range and add it right after the current
    - Very simple
    - Con: But you will need to add the new range right after the current. This will be expensive in a vector
  - Split the range and add at the end
    - This is faster than the previous approach
    - Con: will reorder the rows, not sure if that breaks any expectation
  - Change the VectorSerializer API to take a vector of range pointers
    - Will make the code much simpler 
    - Con: we need to construct a vector every time we invoke the serializer
    - Con: Also the API changes will be a lot refactoring
  - Change the VectorSerializer API to take a list of rows
    - Let eh serializer take care of identifying consecutive rows to copy in one go. (this is the reason we use ranges, since copying chunks of data is faster)
    - Con: we need to create a vector of row idx each time. We currently do something equivalent when partitioning (creating a vector of IndexRange of size 1 for each row)
    - Con: lots of refactoring for an API change

**Comment by bikramSingh91** [comment]
cc: @xiaoxmeng @mbasmanova

**Comment by mbasmanova** [comment]
CC: @liujiayi771
