### ISSUE TITLE
Avoid compiling regex for  %{c0}%

### ISSUE THREAD

**Issue by laithsakka** [facebookincubator/velox#7074]
### Description

when a query has an expression like the above where c0 is fixed string, we do need to compile a regexp for each row
instead we can apply input.contains("c0"); 

repo:
```
TEST_F(Re2FunctionsTest, likeRegexLimit) {
  VectorPtr pattern = makeFlatVector<StringView>(26);
  VectorPtr input = makeFlatVector<StringView>(26);

  auto flatInput = input->asFlatVector<StringView>();
  for (int i = 0; i < 26; i++) {
    flatInput->set(i, "");
  }

  auto flatPattern = pattern->asFlatVector<StringView>();

  for (int i = 0; i < 26; i++) {
    std::string localPattern = fmt::format("%{}%", 'c' + i);
    flatPattern->set(i, StringView(localPattern));
  }

  auto result = evaluate("like(c0 , c1)", makeRowVector({input, pattern}));
  assertEqualVectors(makeConstant(false, 26), result);

}
```

**Comment by laithsakka** [comment]
cc: @pramodsatya

**Comment by mbasmanova** [comment]
CC: @aditi-pandit

**Comment by mbasmanova** [comment]
@aditi-pandit @pramodsatya Aditi, Pramod, is this something you could help with?

**Comment by pramodsatya** [comment]
> @aditi-pandit @pramodsatya Aditi, Pramod, is this something you could help with?

Hi Masha, I am working on this and will send out a PR soon.

**Comment by mbasmanova** [comment]
@pramodsatya Pramod, thank you for helping with this. Looking forward to a PR. Let us know in case something comes up and you decide not to work on this.

**Comment by mbasmanova** [comment]
@pramodsatya @aditi-pandit Pramod, Aditi, any update on this?

**Comment by pramodsatya** [comment]
Hi Masha, I got one round of review comments from Aditi and I have addressed them. The PR is pending review.

**Comment by mbasmanova** [comment]
@pramodsatya Pramod, thank you for the update. Ping me when all comments from Aditi are addressed and she is happy with the PR.

**Comment by mbasmanova** [comment]
@pramodsatya Pramod, I'm seeing that pattern like this is categorized as kGeneric. I believe this is because it contains an underscore (xxx_yyy%). Is this expected?

https://www.facebook.com/permalink.php?story_fbid=619180643116973&id=100050751285937%

**Comment by pramodsatya** [comment]
> @pramodsatya Pramod, I'm seeing that pattern like this is categorized as kGeneric. I believe this is because it contains an underscore (xxx_yyy%). Is this expected?
> 
> https://www.facebook.com/permalink.php?story_fbid=619180643116973&id=100050751285937%

Hi @mbasmanova, yes it is expected to be classified as kGeneric because of the underscore.
