### ISSUE TITLE
Remove the fine-grained spilling support from spilling framework

### ISSUE THREAD

**Issue by xiaoxmeng** [facebookincubator/velox#7125]
### Description

Currently, we support multi-partitioned spilling support for operators like aggregation and hash build to try to reduce the spilling io by keeping more data in memory. And for each spilled partition, we also allow some part of state in-memory and some on-disk. When actually running spilling in practice, we don't need these two features as for now. There are two reasons: (1) multi-partitioned spilling support don't allow us to free memory to the other operator or query as we don't support memory compaction in a data structure like hash string allocator or row container which means we have to spill them all at once each time. Then multi-partitioned spilling support is not enabled in Meta internal use case. Given that, we might not need multi-partitioned spilling for aggregation operator as for now. This will simplify the operator level processing to handle the unspill path and also improve the performance such as we don't need to erase each individual row from the row container (Gluten project found that single row erase can cost significant amount of cpu cycles). Also note for hash build operator will still keep multi-partitioned spilling support as we need to unspill a subset of build table at a time which is different than aggregation use case; (2) OOM prevent is fragile to queries and we found a couple of times that when a aggregation operator switches to output stage with a large memory footprint even with part of its state spilled to disk. And eventually, the in-memory state which is not-spillable eventually cause OOM during the output processing. It is safer to just spill the last in-memory state to disk if spilling has been triggered during the input processing. This simplifies the control logic. For example, for aggregation operator, we either spill everything to disk during the input stage or switch to spill mode and spill all the remaining output state to disk during the output stage.
Having discussed with @mbasmanova and @oerling, we decided to remove the above complexities and add those support later when we see the needs in practice and with memory compaction support in velox

**Comment by yma11** [comment]
> we don't need to erase each individual row from the row container.

@xiaoxmeng Any progress on this erase optimization for row container?

**Comment by xiaoxmeng** [comment]
> > we don't need to erase each individual row from the row container.
> 
> @xiaoxmeng Any progress on this erase optimization for row container?

@yma11 this is planned for this week. Thanks!

**Comment by yma11** [comment]
@xiaoxmeng @mbasmanova I see one PR [7317](https://github.com/facebookincubator/velox/pull/7317) for simplify hashAgg spill and it helps. But in my case, the same one as mentioned in [7251](https://github.com/facebookincubator/velox/issues/7251) but with spill triggered, velox still has great gap vs vanilla spark(`98s vs 63s`). Here are some info for you reference:
```
 -- Aggregation[FINAL [n0_0, n0_1] n1_2 := sum("n0_2"), n1_3 := sum("n0_3"), n1_4 := sum("n0_4"), n1_5 := sum("n0_5"), n1_6 := sum("n0_6"), n1_7 := sum("n0_7"), n1_8 := sum("n0_8"), n1_9 := sum("n0_9"), n1_10 := sum("n0_10")] -> n0_0:VARCHAR, n0_1:VARCHAR, n1_2:BIGINT, n1_3:BIGINT, n1_4:DOUBLE, n1_5:BIGINT, n1_6:DOUBLE, n1_7:BIGINT, n1_8:DOUBLE, n1_9:BIGINT, n1_10:DOUBLE
       Output: 28319541 rows (6.01GB, 6914 batches), Cpu time: 1m 11s, Blocked wall time: 0ns, Peak memory: 3.53GB, Memory allocations: 89955, Threads: 1, Spilled: 28319541 rows (1.74GB, 2 files)
          distinctKey0                 sum: 1, count: 1, min: 1, max: 1
          distinctKey1                 sum: 32171, count: 1, min: 32171, max: 32171
          hashtable.capacity           sum: 33554432, count: 1, min: 33554432, max: 33554432
          hashtable.numDistinct        sum: 9003287, count: 1, min: 9003287, max: 9003287
          hashtable.numRehashes        sum: 15, count: 1, min: 15, max: 15
          hashtable.numTombstones      sum: 0, count: 1, min: 0, max: 0
          runningAddInputWallNanos     sum: 33.55s, count: 1, min: 33.55s, max: 33.55s
          runningFinishWallNanos       sum: 799ns, count: 1, min: 799ns, max: 799ns
          runningGetOutputWallNanos    sum: 37.01s, count: 1, min: 37.01s, max: 37.01s
          spillDiskWrites              sum: 3951, count: 1, min: 3951, max: 3951
          spillFileSize                sum: 1.74GB, count: 2, min: 567.62MB, max: 1.19GB
          spillFillTime                sum: 921.96ms, count: 1, min: 921.96ms, max: 921.96ms
          spillFlushTime               sum: 9.40s, count: 1, min: 9.40s, max: 9.40s
          spillRuns                    sum: 2, count: 1, min: 2, max: 2
          spillSerializationTime       sum: 1.21s, count: 1, min: 1.21s, max: 1.21s
          spillSortTime                sum: 2.84s, count: 1, min: 2.84s, max: 2.84s
          spillWriteTime               sum: 819.16ms, count: 1, min: 819.16ms, max: 819.16ms
```
hotspots:
<img width="557" alt="image" src="https://github.com/facebookincubator/velox/assets/11849056/fec31209-0658-4ac2-8ef2-f3639de433f2">

Any insights about improvement or how should I tune this? will change to other compress codec help?

Thanks,
Yan

**Comment by mbasmanova** [comment]
@yma11 Curious what happens if you disable compression (use NONE codec)?

> spillDiskWrites              sum: 3951, count: 1, min: 3951, max: 3951

Wondering why is this so high.

**Comment by yma11** [comment]
> @yma11 Curious what happens if you disable compression (use NONE codec)?
> 
> > spillDiskWrites              sum: 3951, count: 1, min: 3951, max: 3951
> 
> Wondering why is this so high.

If disable spill compression, the E2E time shortens to 91s, better than compression.
<img width="449" alt="image" src="https://github.com/facebookincubator/velox/assets/11849056/28cc9836-1db1-41db-9a50-0a9b2da54345">

planStats:
```
-- Aggregation[FINAL [n0_0, n0_1] n1_2 := sum("n0_2"), n1_3 := sum("n0_3"), n1_4 := sum("n0_4"), n1_5 := sum("n0_5"), n1_6 := sum("n0_6"), n1_7 := sum("n0_7"), n1_8 := sum("n0_8"), n1_9 := sum("n0_9"), n1_10 := sum("n0_10")] -> n0_0:VARCHAR, n0_1:VARCHAR, n1_2:BIGINT, n1_3:BIGINT, n1_4:DOUBLE, n1_5:BIGINT, n1_6:DOUBLE, n1_7:BIGINT, n1_8:DOUBLE, n1_9:BIGINT, n1_10:DOUBLE
       Output: 28319541 rows (6.01GB, 6914 batches), Cpu time: 1m 5s, Blocked wall time: 0ns, Peak memory: 3.53GB, Memory allocations: 89955, Threads: 1, Spilled: 28319541 rows (3.80GB, 2 files)
          distinctKey0                 sum: 29795, count: 1, min: 29795, max: 29795
          distinctKey1                 sum: 31333, count: 1, min: 31333, max: 31333
          hashtable.capacity           sum: 33554432, count: 1, min: 33554432, max: 33554432
          hashtable.numDistinct        sum: 9003287, count: 1, min: 9003287, max: 9003287
          hashtable.numRehashes        sum: 15, count: 1, min: 15, max: 15
          hashtable.numTombstones      sum: 0, count: 1, min: 0, max: 0
          runningAddInputWallNanos     sum: 30.75s, count: 1, min: 30.75s, max: 30.75s
          runningFinishWallNanos       sum: 800ns, count: 1, min: 800ns, max: 800ns
          runningGetOutputWallNanos    sum: 34.72s, count: 1, min: 34.72s, max: 34.72s
          spillDiskWrites              sum: 3982, count: 1, min: 3982, max: 3982
          spillFileSize                sum: 3.80GB, count: 2, min: 1.21GB, max: 2.59GB
          spillFillTime                sum: 940.16ms, count: 1, min: 940.16ms, max: 940.16ms
          spillFlushTime               sum: 1.30s, count: 1, min: 1.30s, max: 1.30s
          spillRuns                    sum: 2, count: 1, min: 2, max: 2
          spillSerializationTime       sum: 1.28s, count: 1, min: 1.28s, max: 1.28s
          spillSortTime                sum: 2.89s, count: 1, min: 2.89s, max: 2.89s
          spillWriteTime               sum: 2.56s, count: 1, min: 2.56s, max: 2.56s
```

**Comment by yma11** [comment]
> 
> > spillDiskWrites              sum: 3951, count: 1, min: 3951, max: 3951
> 
> Wondering why is this so high.

I think the writes is determined by total spill size/ spill buffer size(1M as default). I tuned this number to a larger one but perf get even worse. I am wondering why there are so many steps in spill write process(extract spill, append to partition, maybe encode during serialization as I see decode is heavy in getOutputWithSpill). Can this part be simplified?

**Comment by xiaoxmeng** [comment]
> during serializat

Data is stored in row container. We need to extract the data from row container and then serialize for output to storage. You can disable write buffer if spill to local memory or local ssd. The write buffer size is to improve the io efficiency on remote storage. What's the performance looks like after disable compression, and the gap compared with vanilla spark? Thanks!

**Comment by xiaoxmeng** [comment]
@yma11 https://github.com/facebookincubator/velox/pull/7406 is the row erase optimization. Thanks!

**Comment by yma11** [comment]
> What's the performance looks like after disable compression, and the gap compared with vanilla spark? Thanks!

with compression disabled, E2E is `91s` and vanilla Spark is `63s`.

**Comment by xiaoxmeng** [comment]
https://github.com/facebookincubator/velox/pull/7406 has fixed this
