### ISSUE TITLE
Flaky tests in SharedArbitrationTest

### ISSUE THREAD

**Issue by Yuhta** [facebookincubator/velox#7154]
### Bug description

SharedArbitrationTest.raceBetweenRaclaimAndJoinFinish: https://app.circleci.com/pipelines/github/facebookincubator/velox/35936/workflows/5ced96bb-0f50-472c-8279-f0f69786c8bb/jobs/237834/steps
SharedArbitrationTest.reclaimFromCompletedOrderBy: https://app.circleci.com/pipelines/github/facebookincubator/velox/35942/workflows/0bb9203d-6af7-473c-9223-80fc81e04f2a/jobs/237872
SharedArbitrationTest.writerFlushThreshold:
https://app.circleci.com/pipelines/github/facebookincubator/velox/36300/workflows/4d298ff8-5b81-4935-b0bb-6b0529d38614/jobs/240906
SharedArbitrationTest.reclaimFromCompletedAggregation: https://app.circleci.com/pipelines/github/facebookincubator/velox/36481/workflows/87d1f59f-6a2a-4683-9b9e-0d394c91f20a/jobs/242392
SharedArbitrationTest.arbitrationFromTableWriter: https://app.circleci.com/pipelines/github/facebookincubator/velox/36504/workflows/fc741247-8fc4-4891-a199-d8ad84269b12/jobs/242593

### System information

n/a

**Comment by xiaoxmeng** [comment]
All the flaky tests have been fixed.

**Comment by xiaoxmeng** [comment]
https://github.com/facebookincubator/velox/pull/7227
https://github.com/facebookincubator/velox/pull/7225
https://github.com/facebookincubator/velox/pull/7222
