### ISSUE TITLE
Performance regression possibly caused by memory allocation

### ISSUE THREAD

**Issue by marin-ma** [facebookincubator/velox#7159]
### Bug description

In Gluten, we recently rebased our Velox dependency to the main branch to stay in sync with the community. However, we've observed a performance regression in our TPCH power test. The overall execution time increased from 1210s to 1350s. While most of the queries have slowed down, Q1-Q4 and Q22 remained unaffected. We also found some anomalies in the CPU metrics. Before the update, our readings were approximately 73% user% and 14% kernel%. After the update, they shifted to 64% user% and 21% kernel%.

Using TPCH Q21 as an example, we noticed that both shuffle reads and table scans are lagging. Given that our test was conducted on a single node, a common factor is that both operations read data from disks, usually the page cache.

We analyzed the hotspot using "perf" for the slowest stage in TPCH Q21. It seems that a significant amount of time is being spent on huge page memory allocation.

![image](https://github.com/facebookincubator/velox/assets/52736607/814ffeaa-6921-4e91-9f2a-6085220c0a61)

We found there are some major changes related to the memory allocation on the main branch after June (since out last rebased commit), and it's hard to identify which PR affects the performance.

### System information

Velox System Info v0.0.2
Commit: 4add701b440f6d60dd34d0112b4ad393f47fcfa5
CMake Version: 3.16.3
System: Linux-5.4.0-156-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.1.0
C Compiler: /usr/bin/cc
C Compiler Version: 11.1.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by mbasmanova** [comment]
CC: @oerling @Yuhta 

Use of huge pages was introduced in #5516 and #5413

**Comment by marin-ma** [comment]
> CC: @oerling @Yuhta
> 
> Use of huge pages was introduced in #5516 and #5413

Thanks! I tried disable `FLAGS_velox_memory_use_hugepages` introduced in #5413, the performance didn't go back.
I found it hard to simply revert #5516 . Is there any simple way to disable huge page allocation?

**Comment by mbasmanova** [comment]
@marin-ma Curious, whether it would be possible to bisect to find the problematic commit.

**Comment by Yuhta** [comment]
Do you still see huge page allocation after `FLAGS_velox_memory_use_hugepages` is set?  What does the profile look like after you disable it (and compare to the old code)?  Can you generate a flamegraph from the perf data?

**Comment by marin-ma** [comment]
Apologize for the confusion. Just confirmed that disable `FLAGS_velox_memory_use_hugepages` can bring the performance back to normal. Thanks for your help & will close this one.

**Comment by oerling** [comment]
Huge pages are useful for something that is long lived and accessed at random. Mileage can depend on specific CPU model. Given this, huge pages could be applied more selectively, e.g. only  for long lived tables. Could be there are platforms where there is no gain from that. System time is understandably increased by their use, so need to stay on for a long time to make up for that. To be seen. First question: After the system time is spent, what is the savings in probing a hash join? Use HashTableBenchmark.cpp. If there is no gain, just turn ooff huge pages across the board. If there is gain, see what the break-even is vs the added system time.
