### ISSUE TITLE
HashAgg w/o spill doesn't outperform vanilla Spark

### ISSUE THREAD

**Issue by yma11** [facebookincubator/velox#7251]
### Description

In a customer workload profiling, we found hashAgg can't outperform vanilla Spark, even in the case that no spill happens.  In this query, the groupby keys are the primary keys of the table so aggregation doesn't produce reduction at all. Here is the detailed plan stats:
```
    -- Aggregation[FINAL [n0_0, n0_1] n1_2 := sum("n0_2"), n1_3 := sum("n0_3"), n1_4 := sum("n0_4"), n1_5 := sum("n0_5"), n1_6 := sum("n0_6"), n1_7 := sum("n0_7"), n1_8 := sum("n0_8"), n1_9 := sum("n0_9"), n1_10 := sum("n0_10")] -> n0_0:VARCHAR, n0_1:VARCHAR, n1_2:BIGINT, n1_3:BIGINT, n1_4:DOUBLE, n1_5:BIGINT, n1_6:DOUBLE, n1_7:BIGINT, n1_8:DOUBLE, n1_9:BIGINT, n1_10:DOUBLE
       Output: 28319541 rows (6.01GB, 6914 batches), Cpu time: 37.48s, Blocked wall time: 0ns, Peak memory: 5.05GB, Memory allocations: 207459, Threads: 1
          distinctKey0                 sum: 1, count: 1, min: 1, max: 1
          distinctKey1                 sum: 32250, count: 1, min: 32250, max: 32250
          hashtable.capacity           sum: 33554432, count: 1, min: 33554432, max: 33554432
          hashtable.numDistinct        sum: 28319541, count: 1, min: 28319541, max: 28319541
          hashtable.numRehashes        sum: 14, count: 1, min: 14, max: 14
          hashtable.numTombstones      sum: 0, count: 1, min: 0, max: 0
          runningAddInputWallNanos     sum: 34.32s, count: 1, min: 34.32s, max: 34.32s
          runningFinishWallNanos       sum: 1.62us, count: 1, min: 1.62us, max: 1.62us
          runningGetOutputWallNanos    sum: 3.15s, count: 1, min: 3.15s, max: 3.15s
```
ping @FelixYBW @mbasmanova.

**Comment by mbasmanova** [comment]
@yma11 Thank you for reporting this. Would you add the previous node as well? What are the types of the grouping keys n0_0, n0_1? Does Spark use hash aggregation or sort + streaming aggregation? Any chance you could attach a profile?

I see that grouping keys are strings. Can you share the distribution of lengths of these strings?

n0_0:VARCHAR, n0_1:VARCHAR

This aggregation computes 8 sums. Can we reproduce the issue with 1 sum or 2? E.g. if we reduce number of sums, do we still see Velox not being faster than Spark? Is it slower or about the same?

I wonder if we could create a benchmark that ilustrates the issue.

**Comment by mbasmanova** [comment]
Assuming input is 2 strings + 8 bigint / double. With 6.01GB total over 28319541 rows -> that's 227 bytes per row. 8 bigint / double are 8 * 8 = 64 bytes. This leaves 163 bytes for 2 strings. ~80 bytes per string. Is this how it is?

Does the issue reproduced with just one string group-by key? Or do we need 2?

All pairs of input group-by strings are unique, but how many unique values are in each group-by key? Are these keys unique by themselves as well?

**Comment by mbasmanova** [comment]
CC: @oerling @Yuhta @xiaoxmeng

**Comment by yma11** [comment]
@mbasmanova Thanks for quick reply. 
> Would you add the previous node as well?

This is final Aggregation so previous node is shuffle.
> What are the types of the grouping keys n0_0, n0_1? 

As you assumed, they are strings. For n0_0, it has `19,653,306` unique values in total `28,273,546` rows. For n0_1, it has `23,225,893` unique values in total `23,642,319` rows.
>Does Spark use hash aggregation or sort + streaming aggregation?

It uses HashAggregation.
> Can we reproduce the issue with 1 sum or 2?

Yes. This issue can be reproduced using 2 keys with less sum.  But with single key, Velox can outperform vanilla Spark even with several sums, about 1.5X.

I will do a profile but it will need some time. Hope above info can give you some clue.

**Comment by mbasmanova** [comment]
@yma11 Thank you for these additional details. This is helpful. To recap, we need 2 string keys with mostly unique values and  1 aggregation. BTW, can you also clarify what are the lengths of the strings? Are these roughly 80 bytes each?

**Comment by yma11** [comment]
> can you also clarify what are the lengths of the strings? Are these roughly 80 bytes each?
Seems it's not so long but 32 bytes, like `256d12eb37ee1fed458dce8cfd6b67f1`.

**Comment by mbasmanova** [comment]
@yma11 Thanks.

So, it is 2 string keys with mostly unique values and 1 aggregation. Strings are ~32 bytes each, e.g. '256d12eb37ee1fed458dce8cfd6b67f1'.

**Comment by yma11** [comment]
The aggregation number doesn't quite matter.  Multi string keys affect much.

**Comment by mbasmanova** [comment]
@yma11 @oerling Discussed with Orri. We suspect the hot spot is hashing of StringView using spooky hash. Orri will put together a more efficient hash. @yma11 Would you be able to give it a try once PR is out?

```
namespace folly {
template <>
struct hasher<::facebook::velox::StringView> {
  size_t operator()(const ::facebook::velox::StringView view) const {
    return hash::SpookyHashV2::Hash64(view.data(), view.size(), 0);
    // return facebook::velox::bits::hashBytes(1, view.data(), view.size());
  }
};
```

**Comment by mbasmanova** [comment]
@yma11 Any chance you could you try to apply #7261 to see if it helps?

**Comment by yma11** [comment]
> @yma11 Any chance you could you try to apply #7261 to see if it helps?

@mbasmanova I applied this patch and E2E of the query is shortened to `40s` from `56s`. So this change helps. But `40s` is still not good enough and maybe caused by other code changes. Now I am switching to latest code and make deeper investigation. So will keep this ticket open util we figure out a good result.

**Comment by mbasmanova** [comment]
@yma11 Thank you for the update.

> But 40s is still not good enough 

Just out of curiosity, what is the number we are looking for?

> Now I am switching to latest code and make deeper investigation. So will keep this ticket open util we figure out a good result.

Thanks. Please, let us know what you find.

**Comment by yma11** [comment]
@mbasmanova Using latest velox code, the E2E query time still can't beat vanilla Spark. Here are the hotspots identified:
1):
<img width="488" alt="image" src="https://github.com/facebookincubator/velox/assets/11849056/2844e63a-61c6-4ba0-b139-ea0b4675f8e9">
2):
<img width="465" alt="image" src="https://github.com/facebookincubator/velox/assets/11849056/d5b546f7-26d1-4ced-9fc1-0c878db61fc7">

I am still using the query with group by on 2 primary string keys. Is it possible to further optimize this?

Actually there is a regression after Gluten switched to upstream Velox. Before the switch, the perf of this query is similar between Velox and spark and it's expected to have perf gain using the Hasher optimization. But after this switch, Velox perf is worse than spark, about ~80% and then become similar with Hasher optimization applied.
Thanks,
Yan

**Comment by mbasmanova** [comment]
@yma11 Thank you for the updates. We'll take a closer look. We need to create a benchmark so we can profile and optimize more easily. If you have cycles, see if you can help create such a benchmark. An example can be found in velox/functions/prestosql/aggregates/benchmarks/ReduceAgg.cpp. Otherwise, I'll create one. Thanks.

**Comment by yma11** [comment]
I think it maybe easier to reproduce by using parquet file `velox/dwio/parquet/tests/examples/str_sort.parquet` and a sql `select query_sig, result_sig from tmp groupby query_sig, result_sig` but haven't found any available example I can refer.

**Comment by mbasmanova** [comment]
@yma11 Unfortunately, I'm not setup to run tests over Parquet files.

I tried to create a benchmark to reproduce this issue: #7344

I'm seeing different numbers though: 14s cpu time vs. 37s in your case. Also, 2x fewer memory allocations: 110K vs. 210K.

```
 -- Aggregation[SINGLE [k1, k2] a0 := sum(ROW["n"])] -> k1:VARCHAR, k2:VARCHAR, a0:BIGINT
   Output: 28000000 rows (4.06GB, 27344 batches), Cpu time: 13.78s, Blocked wall time: 0ns, Peak memory: 3.30GB, Memory allocations: 109413, Threads: 1
``

**Comment by mbasmanova** [comment]
@oerling @yma11 Discussed with Orri. He is going to add a fast path to HashStringAllocator to copy a single string.

**Comment by mbasmanova** [comment]
@yma11 Fast path for HashStringAllocator to copy a single string: #7355

**Comment by yma11** [comment]
@mbasmanova with [7355](https://github.com/facebookincubator/velox/pull/7355), E2E time of same query shortens to 37s from 42s, so it now has about `14%` perf gain in this case.
By the way, I see [7261](https://github.com/facebookincubator/velox/pull/7261) is reverted for test failure, will it be ported again?

**Comment by mbasmanova** [comment]
@yma11 Thank you for the update. Happy to hear that we are no longer slower than Spark and a tiny bit faster.

I also noticed that https://github.com/facebookincubator/velox/pull/7261 was reverted. We'll need to work on getting it back in. CC: @Yuhta @oerling

**Comment by mbasmanova** [comment]
@yma11 One more optimization from Orri: #7386

Any chance you could try that?

**Comment by yma11** [comment]
> @yma11 One more optimization from Orri: #7386
> 
> Any chance you could try that?

I got a build error at gluten cpp side for this PR.
````
error: cannot convert ‘const xsimd::avx’ to ‘const xsimd::sse2&’
  294 |   return detail::BitMask<T, A>::toBitMask(mask, arch);
```
Any clue on it?

**Comment by Yuhta** [comment]
@yma11 Do you have the full output from compiler?

**Comment by yma11** [comment]
@Yuhta like this:
```
/root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/common/base/SimdUtil.h: In instantiation of ‘auto facebook::velox::simd::toBitMask(xsimd::batch_bool<T, A>, const A&) [with T = unsigned char; A = xsimd::avx]’:
/root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/common/base/SimdUtil-inl.h:1362:26:   required from ‘bool facebook::velox::simd::memEqualUnsafe(const void*, const void*, int32_t) [with A = xsimd::avx; int32_t = int]’
/root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/exec/RowContainer.h:1086:61:   required from here
/root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/common/base/SimdUtil.h:294:42: error: cannot convert ‘const xsimd::avx’ to ‘const xsimd::sse2&’
  294 |   return detail::BitMask<T, A>::toBitMask(mask, arch);
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~
In file included from /root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/common/base/SimdUtil.h:435,
                 from /root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/buffer/Buffer.h:26,
                 from /root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/vector/BaseVector.h:29,
                 from /root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/vector/ComplexVector.h:26,
                 from /root/workspace/gluten-111/cpp/velox/memory/VeloxColumnarBatch.h:22,
                 from /root/workspace/gluten-111/cpp/velox/operators/plannodes/RowVectorStream.h:22,
                 from /root/workspace/gluten-111/cpp/velox/compute/VeloxBackend.cc:24:
/root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/common/base/SimdUtil-inl.h:73:54: note:   initializing argument 2 of ‘static int facebook::velox::simd::detail::BitMask<T, A, 1>::toBitMask(xsimd::batch_bool<T, A>, const xsimd::sse2&) [with T = unsigned char; A = xsimd::avx]’
   73 |   static int toBitMask(xsimd::batch_bool<T, A> mask, const xsimd::sse2&) {
      |                                                      ^~~~~~~~~~~~~~~~~~
/root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/common/base/SimdUtil-inl.h: In instantiation of ‘bool facebook::velox::simd::memEqualUnsafe(const void*, const void*, int32_t) [with A = xsimd::avx; int32_t = int]’:
/root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/exec/RowContainer.h:1086:61:   required from here
/root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/common/base/SimdUtil-inl.h:1362:10: error: ‘void bits’ has incomplete type
 1362 |     auto bits = toBitMask(
      |          ^~~~
/root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/common/base/SimdUtil-inl.h: In instantiation of ‘static int facebook::velox::simd::detail::BitMask<T, A, 1>::toBitMask(xsimd::batch_bool<T, A>, const xsimd::sse2&) [with T = unsigned char; A = xsimd::avx]’:
/root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/common/base/SimdUtil.h:294:42:   required from ‘auto facebook::velox::simd::toBitMask(xsimd::batch_bool<T, A>, const A&) [with T = unsigned char; A = xsimd::avx]’
/root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/common/base/SimdUtil-inl.h:1362:26:   required from ‘bool facebook::velox::simd::memEqualUnsafe(const void*, const void*, int32_t) [with A = xsimd::avx; int32_t = int]’
/root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/exec/RowContainer.h:1086:61:   required from here
/root/workspace/gluten-111/ep/build-velox/build/velox_ep/velox/common/base/SimdUtil-inl.h:74:30: error: cannot convert ‘xsimd::batch_bool<unsigned char, xsimd::avx>’ to ‘__m128i’ {aka ‘__vector(2) long long int’}
   74 |     return _mm_movemask_epi8(mask);

```

**Comment by yma11** [comment]
@Yuhta Does the log help? I'd like to try this PR to see whether it can bring more perf gain.

**Comment by Yuhta** [comment]
Are you missing `-mavx2` in your build?
