### ISSUE TITLE
Handle Varchar(n) in Velox

### ISSUE THREAD

**Issue by aditi-pandit** [facebookincubator/velox#7264]
### Discussed in https://github.com/facebookincubator/velox/discussions/6888

<div type='discussions-op-text'>

<sup>Originally posted by **aditi-pandit** October  3, 2023</sup>
Both Presto and Spark allow specifying an optional max length for varchar type 
https://prestodb.io/docs/current/language/types.html#string
https://spark.apache.org/docs/latest/sql-ref-datatypes.html

Velox Varchar type doesn't support max length semantics. 

Right now, Presto always uses Velox varchar irrespective if the varchar has a max length. This causes incorrect results for many SQL.

```
presto:tpch> select cast(varchar_value as varchar(3)) from (values ('9898.122')) t(varchar_value);
_col0
9898.122

Note:-> This is incorrect output. The correct result should be 989
```
I tried to error out such invalid CAST expressions at the Prestissimo layer, but that failed many SQL queries in the native tests. So I feel doing so is very restrictive. It would be better to support varchar(n) natively in Velox.

Starting this discussion to understand : 

- Why Velox doesn't support the max length semantics ? There is the required work of adding a new type, casting functions etc. But is there a more fundamental limitation of Velox to support max length semantics ?
- The complexity to support the max length in the future.

@mbasmanova @pedroerp @oerling 
</div>

**Comment by gggrace14** [comment]
One quick fix we can attempt to align with Presto behavior is to convert to substr() in Prestissimo plan in PrestoToVeloxExpression.cpp.

We could address it at the moment with converting to substr() and only for the branch of varchar to varchar, as the behavior only differs when the input type is varchar and the target type is varchar, as shown below.
```
SELECT
    CAST(c0 AS VARCHAR(3)),
    CAST(c1 AS VARCHAR(3)),
    CAST(c2 AS VARCHAR(3)),
    CAST(c3 AS VARCHAR(3)),
    CAST(c4 AS VARCHAR(3)),
    CAST(c5 AS VARCHAR(3)),
    CAST(c6 AS VARCHAR(3))
FROM (
    VALUES
        (
            'abcdefgh',
            12345,
            0.12345,
            1.2345E5,
            INFINITY(),
            FALSE,
            TIMESTAMP '2024-07-01 20:25:35'
        )
) t(c0, c1, c2, c3, c4, c5, c6)
```
_col0	_col1	_col2	_col3	_col4	_col5	_col6
abc	12345	0.12345	123450.0	Infinity	false	2024-07-01 20:25:35.000

**Comment by czentgr** [comment]
@gggrace14 Thank you! I actually noticed this as well recently when I was adding tests to use the PrestoQueryRunner and tried to cast various types.
Which then begs the question, technically, the CAST should truncate the string result. So is this not a problem in Presto in the first place? Of course, this is what allows this workaround.

**Comment by gggrace14** [comment]
> @gggrace14 Thank you! I actually noticed this as well recently when I was adding tests to use the PrestoQueryRunner and tried to cast various types. Which then begs the question, technically, the CAST should truncate the string result. So is this not a problem in Presto in the first place? Of course, this is what allows this workaround.

Hi @czentgr , sorry I just found you comment. On the other hand, not quite get the question...

For the varchar to varchar(n) path, Presto Java does the truncation. Before my temp remedy, Prestissimo did not truncate. And after my remedy, Prestissimo truncates now. In general, at the moment our goal is to make Presto and Prestissimo behave in the same way. For the rest of data types, Presto is not truncating today. And we want to keep this behavior for now.
