### ISSUE TITLE
UndefinedBehaviorSanitizer: signed-integer-overflow in sequence function

### ISSUE THREAD

**Issue by laithsakka** [facebookincubator/velox#7269]
### Description

SUMMARY: UndefinedBehaviorSanitizer: signed-integer-overflow fbcode/velox/functions/prestosql/Sequence.cpp:204:41 in 

### Error Reproduction

run velox/expression/tests/facebook:fb_velox_expression_fuzzer_test4 - FacebookPrestoExpressionFuzzerTest.test
with seed 1164744513
on 5b70628cba0f00a3fccb5061d3c5d6b71d1bf763

https://www.internalfb.com/intern/test/562950057133820?ref_report_id=0
https://www.internalfb.com/intern/testinfra/diagnostics/17451448564036076.562950057133820.1698317848/

**Comment by laithsakka** [comment]
https://fburl.com/code/wu8s0vmu

**Comment by kewang1024** [comment]
https://github.com/facebookincubator/velox/pull/7320
