### ISSUE TITLE
Flaky HashJoinTest related to spilling and memory stats 

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#7281]
### Bug description

HashJoinTest/MultiThreadedHashJoinTest.rightSemiJoinFilterWithExtraFilter/1 fails at the check of `memory::spillMemoryPool()->stats().currentBytes`.

To reproduce the error, run `buck2 test '@fbcode//mode/dev' fbcode//velox/exec/tests:velox_exec_test -- --exact 'velox/exec/tests:velox_exec_test - HashJoinTest/MultiThreadedHashJoinTest.rightSemiJoinFilterWithExtraFilter/1' --run-disabled --jobs 18 --stress-runs 100 --record-results` on a devserver.

### System information

N/A

### Relevant logs

```bash
[----------] 1 test from HashJoinTest/MultiThreadedHashJoinTest
[ RUN      ] HashJoinTest/MultiThreadedHashJoinTest.rightSemiJoinFilterWithExtraFilter/1
fbcode/velox/exec/tests/HashJoinTest.cpp:647: Failure
Expected equality of these values:
  memory::spillMemoryPool()->stats().currentBytes
    Which is: 10368
  0
Google Test trace:
fbcode/velox/exec/tests/HashJoinTest.cpp:624: With Max Spill Level: 2
fbcode/velox/exec/tests/HashJoinTest.cpp:454: probeParallelize: 0, buildParallelize: 1 numDrivers: 3
```

**Comment by xiaoxmeng** [comment]
https://github.com/facebookincubator/velox/pull/7422 should have fixed this issue
