### ISSUE TITLE
Allow partial write to RowContainer's row

### ISSUE THREAD

**Issue by usurai** [facebookincubator/velox#7380]
### Description

The typical usage of `RowContainer` has been like the following:
1. request a new `row` via `newRow()`
2. write every field via `store()` and some reading
3. return `row` via `eraseRow()` or reuse it via `initializeRow(reuse=true)`

However, if the user don't write all the fields of the row, it might cause the issue for the `row` containing variable width fields: `eraseRow()` and `initializeRow(reuse=true)` frees variable width fields, if those fields are uninitialized, `HashStringAllocator` will try to free some random memory.

## Motivation
> If the user don't write all the fields of the row

This use case comes from https://github.com/facebookincubator/velox/pull/7172, where I tried to optimize `TopN` . The optimization delays the copying of non-key fields into `RowContainer` until the passed rows of a batch of input are confirmed, that is, for each input row that is bigger than current N-biggest rows, store its key fields into a `row` in `RowContainer`, this `row` might be a new row if there hasn't been enough N-biggest rows, or a `row` that's being replaced by the input row(via `initializeRow(reuse=true)`). After all the input has been processed, store the rest non-key fields of the passed rows into `RowContainer`.

## Current Status
https://github.com/facebookincubator/velox/pull/7299 addressed part of the problem by always zero-out variable width fields when freeing them. But since new rows coming from `newRow()` are uninitialized, if the user `eraseRow()` or `initializeRow(reuse=true)` a new row without writing to its variable width fields, it still causes the problem.

## Proposal
- Unfavored one: Enable `checkFree_` in `RowContainer`: With this flag enabled, `RowContainer` always zero-out fields at `newRow`, `intializeRow` and `eraseRow`. But this will cause unneeded overhead to current code that has the typical usage(write all fields) of `RowContainer`.
- Extend `newRow`, `intializeRow` to allow partial-write. That is, add a parameter(default to false) to these function that informs the `row` is/will be partial-write, so that:
    - `initialzeRow(row, reuse, zeroOut)` zero-out variable width fields.
    - `newRow(initialize)` passes the flag through to `initialzeRow`.

cc @mbasmanova @xiaoxmeng

**Comment by mbasmanova** [comment]
@usurai Thank you for the detailed description of the problem and possible solutions.

I assume we would like to have a way to trigger this code when initializing new row.

```
  } else if (rowSizeOffset_ != 0 && checkFree_) {
    // zero out string views so that clear() will not hit uninited data. The
    // fastest way is to set the whole row to 0.
    ::memset(row, 0, fixedRowSize_);
  }
```

Having 2 boolean flags in initializeRow might be a bit hard on the reader (difficult to tell which is which). Would it work to have a separate method to zero-out variable-width fields in the row?

**Comment by usurai** [comment]
@mbasmanova Great suggestion. Then the partial-write user will only need to invoke the added method before writing. 
While adding the new method, I think we should also revert the behavior of `initializeRow(reuse = true)`, that is, don't zero out variable width fields. Will this cause some confusion? E.g. `initializeRow` returns `row` that is uninitialized(in terms of fields).

`initializeRow` serves the following functions:
- Reset metadata(null bits, row size, free flag).
- If reuse, free external memory and aggregates.
- If not reuse and checkFree(which is always false) and contains variable width fields, zero out all fields.

How about splitting `initializeRow` into two methods:
1. `resetMetadata`(or something like this): Reset null bits, row size, free flag.
2. `prepareForReuse`: `resetMetadata` + free external memory and aggregates.

Plus the newly added `zeroOutVariableWidthFields`.

**Comment by mbasmanova** [comment]
@usurai This could work. I wonder why can't we always zero-out the row in initializeRow. Would an extra memset make any noticeable difference?

    ::memset(row, 0, fixedRowSize_);

**Comment by usurai** [comment]
I guess the difference would not be noticeable, but for most case the memset could be omitted(since all the `RowContainer` users have been using unintialized rows and doing well).
I think this(splitting and adding new method) adds some complexity but also provides the user more control.

**Comment by mbasmanova** [comment]
I'm a bit considered about increased complexity. Would it be possible to keep initializeRow as is and document that it leaves variable-width rows uninitialized and the caller is responsible to either write these using store() or call the new initializeVariableWidthFields() to zero these out? Alternatively, I'd consider zeroing out variable width fields by default. This is simple and no visible perf impact.

**Comment by usurai** [comment]
Got it. I implemented the first option https://github.com/facebookincubator/velox/pull/7383. Please take a look, thanks!
