### ISSUE TITLE
Add dynamic filter for preloading data source

### ISSUE THREAD

**Issue by zhli1142015** [facebookincubator/velox#7381]
### Description

`pendingDynamicFilters_` is evaluated to skip partitions in `HiveDataSource::addSplit` --> `SplitReader::prepareSplit` --> `testFilters`. They are added in `dataSource_` but not preloading data sources.
This is the case we observed in TPCDS query59, which impacting the raw input bytes after enabling split preloading.

Comparing:
![image](https://github.com/facebookincubator/velox/assets/10524738/4d4426e4-b3cd-4fca-87cb-40ea3be0b046)
Add the filters:
![image](https://github.com/facebookincubator/velox/assets/10524738/3bdf017e-86a7-453f-86ad-454fae924422)

**Comment by mbasmanova** [comment]
@zhli1142015 Thank you for creating this issue.

> They are added in dataSource_ but not preloading data sources.

Got it. Do you have a suggestion on how to start pushing filters into 'preloading' data sources as well?

**Comment by zhli1142015** [comment]
Copy the comments from PR:

> @zhli1142015 For example, it is still not clear to me why we need a new setColumnFilter when we already have addDynamicFilter. These 2 APIs seem to provide exactly same information.

To answer this question:
`addDynamicFilter` internally calls `filter_ = filter_ ? filter_->mergeWith(&filter) : filter.clone();`, https://github.com/facebookincubator/velox/blob/main/velox/dwio/common/ScanSpec.cpp
This new function: `setColumnFilter` internally calls `filter_ = std::move(filter);`

**Comment by zhli1142015** [comment]
> @zhli1142015 Thank you for creating this issue.
> 
> > They are added in dataSource_ but not preloading data sources.
> 
> Got it. Do you have a suggestion on how to start pushing filters into 'preloading' data sources as well?


@Yuhta  suggested to share the scanSpec between `dataSource_` and 'preloading' data sources, I tried that some UT failed with crash, as scanSpec can't be used cross mulit threads.
I think we can get the filters from `dataSource_` and set them to 'preloading' data sources before calling `addSplit` on 'preloading' data sources.

**Comment by zhli1142015** [comment]
> @zhli1142015 Are you saying that addDynamicFilter needs to have different behavior depending on whether the DataSource is a regular one or pre-fetching one? Does DataSource know which one it is? If yes, then addDynamicFilter can take this information into account. Otherwise, can we make DataSource know it is a pre-fetching source? If not, maybe add a flag to addDynamicFilter to indicate that we are in pre-fetching mode. BTW, for pre-fetching, can we not pass the filters during construction?

--> BTW, for pre-fetching, can we not pass the filters during construction?
Data pre-fetching happens in `HiveDataSource::addSplit` function, I think filters are needed to prun the partitions.
```
        auto ptr = connector->createDataSource(type, table, columns, ctx.get());
        if (task->isCancelled()) {
          return nullptr;
        }
        ptr->addSplit(split);
```

Yes, this is a good idea. We can add a parameter (maybe called `shouldMerge`) in `addDynamicFilter `to indicate the different behavior, either merge the filter with original filters or replace it.

Then we still add one API in DataSource `getColumnFilter` to get the final filter which is merged with dynamic filters from `dataSource_`. And for 'preloading' data sources we call `addDynamicFilter(shouldMerge=false)` to set the filter.
Please let me know if this looks good to you.

**Comment by Yuhta** [comment]
@mbasmanova I think the current proposal is ok.  So
* Merging happens only once on non-preload data source
* Merged filters are kept in operator, which is ok lifecycle-wise, and we already have similar treatment for pending filters
* Add `getColumnFilter` to extract merged filters
* On preload data source, we replace the filters instead of merging, controlled by a parameter on `addDynamicFilter`.  I would suggest to name it `addDynamicFilter(bool replaceExisting)`

**Comment by Yuhta** [comment]
Chatted with @mbasmanova and we can try put the dynamic filters in `ConnectorTableHandle` to make the interface cleaner.  So we add setters and getters in `ConnectorTableHandle` for dynamic filters and preloaded `HiveDataSource` will get it from there instead of relying on `addDynamicFilter`.

**Comment by zhli1142015** [comment]
> Chatted with @mbasmanova and we can try put the dynamic filters in `ConnectorTableHandle` to make the interface cleaner. So we add setter and getter in `ConnectorTableHandle` for dynamic filters and preloaded `HiveDataSource` will get them from there instead of relying on `addDynamicFilter`.

I experimented with the suggested approach and encountered some random failures in the test suite "velox_dwio_parquet_tpch_test" (see details below). It appears that `ConnectorTableHandle` is accessed concurrently by multiple threads/drivers, leading to issues when setting dynamic filters.

To address this, I propose passing dynamic filters to preloading data sources through `ConnectorQueryCtx`. I have made the necessary updates in the PR to reflect this solution. I would appreciate your feedback on whether this approach aligns with your expectations, or if you have any alternative suggestions.
Thanks.
```

[ RUN      ] ParquetTpchTest.Q10
double free or corruption (fasttop)
*** Aborted at 1703393252 (Unix time, try 'date -d @1703393252') ***
*** Signal 6 (SIGABRT) (0x3e8002b365a) received by PID 2831962 (pthread TID 0x7f85f7fff700) (linux TID 2833035) (maybe from PID 2831962, UID 1000) (code: -6), stack trace: ***
    @ 00000000067d7b11 folly::symbolizer::(anonymous namespace)::innerSignalHandler(int, siginfo_t*, void*)
                       /var/git/gluten/ep/build-velox/build/velox_ep/folly/_build/../folly/experimental/symbolizer/SignalHandler.cpp:449
    @ 00000000067d7bf2 folly::symbolizer::(anonymous namespace)::signalHandler(int, siginfo_t*, void*)
                       /var/git/gluten/ep/build-velox/build/velox_ep/folly/_build/../folly/experimental/symbolizer/SignalHandler.cpp:470
    @ 0000000000000000 (unknown)
    @ 000000000004300b gsignal
    @ 0000000000022858 abort
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 0000000000000000 (unknown)
    @ 00000000024abdc6 std::_Hashtable<unsigned int, std::pair<unsigned int const, std::shared_ptr<facebook::velox::common::Filter> >, std::allocator<std::pair<unsigned int const, std::shared_ptr<facebook::velox::common::Filter> > >, std::__detail::_Select1st, std::equal_to<unsigned int>, std::hash<unsigned int>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true> >::clear()
    @ 00000000024ab744 facebook::velox::exec::TableScan::getOutput()
    @ 000000000243be9e facebook::velox::exec::Driver::runInternal(std::shared_ptr<facebook::velox::exec::Driver>&, std::shared_ptr<facebook::velox::exec::BlockingState>&, std::shared_ptr<facebook::velox::RowVector>&)
    @ 000000000243d1f1 facebook::velox::exec::Driver::run(std::shared_ptr<facebook::velox::exec::Driver>)
    @ 000000000243d402 void folly::detail::function::FunctionTraits<void ()>::callSmall<facebook::velox::exec::Driver::enqueue(std::shared_ptr<facebook::velox::exec::Driver>)::{lambda()#1}>(folly::detail::function::Data&)
    @ 00000000066e5748 folly::detail::function::FunctionTraits<void ()>::operator()()
                       /var/git/gluten/ep/build-velox/build/velox_ep/folly/_build/../folly/Function.h:375
                       -> /var/git/gluten/ep/build-velox/build/velox_ep/folly/_build/../folly/Singleton.cpp
    @ 00000000067c4eb5 folly::ThreadPoolExecutor::runTask(std::shared_ptr<folly::ThreadPoolExecutor::Thread> const&, folly::ThreadPoolExecutor::Task&&)
                       /var/git/gluten/ep/build-velox/build/velox_ep/folly/_build/../folly/lang/Exception.h:285
                       -> /var/git/gluten/ep/build-velox/build/velox_ep/folly/_build/../folly/executors/ThreadPoolExecutor.cpp
    @ 00000000067763ee folly::CPUThreadPoolExecutor::threadRun(std::shared_ptr<folly::ThreadPoolExecutor::Thread>)
                       /var/git/gluten/ep/build-velox/build/velox_ep/folly/_build/../folly/executors/CPUThreadPoolExecutor.cpp:326
    @ 00000000067cfe61 void std::__invoke_impl<void, void (folly::ThreadPoolExecutor::*&)(std::shared_ptr<folly::ThreadPoolExecutor::Thread>), folly::ThreadPoolExecutor*&, std::shared_ptr<folly::ThreadPoolExecutor::Thread>&>(std::__invoke_memfun_deref, void (folly::ThreadPoolExecutor::*&)(std::shared_ptr<folly::ThreadPoolExecutor::Thread>), folly::ThreadPoolExecutor*&, std::shared_ptr<folly::ThreadPoolExecutor::Thread>&)
                       /usr/include/c++/9/bits/invoke.h:73
                       -> /var/git/gluten/ep/build-velox/build/velox_ep/folly/_build/../folly/executors/ThreadPoolExecutor.cpp
    @ 00000000067cf104 std::__invoke_result<void (folly::ThreadPoolExecutor::*&)(std::shared_ptr<folly::ThreadPoolExecutor::Thread>), folly::ThreadPoolExecutor*&, std::shared_ptr<folly::ThreadPoolExecutor::Thread>&>::type std::__invoke<void (folly::ThreadPoolExecutor::*&)(std::shared_ptr<folly::ThreadPoolExecutor::Thread>), folly::ThreadPoolExecutor*&, std::shared_ptr<folly::ThreadPoolExecutor::Thread>&>(void (folly::ThreadPoolExecutor::*&)(std::shared_ptr<folly::ThreadPoolExecutor::Thread>), folly::ThreadPoolExecutor*&, std::shared_ptr<folly::ThreadPoolExecutor::Thread>&)
                       /usr/include/c++/9/bits/invoke.h:95
                       -> /var/git/gluten/ep/build-velox/build/velox_ep/folly/_build/../folly/executors/ThreadPoolExecutor.cpp
    @ 00000000067cdee1 void std::_Bind<void (folly::ThreadPoolExecutor::*(folly::ThreadPoolExecutor*, std::shared_ptr<folly::ThreadPoolExecutor::Thread>))(std::shared_ptr<folly::ThreadPoolExecutor::Thread>)>::__call<void, , 0ul, 1ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul>)
                       /usr/include/c++/9/functional:400
                       -> /var/git/gluten/ep/build-velox/build/velox_ep/folly/_build/../folly/executors/ThreadPoolExecutor.cpp
    @ 00000000067cca12 void std::_Bind<void (folly::ThreadPoolExecutor::*(folly::ThreadPoolExecutor*, std::shared_ptr<folly::ThreadPoolExecutor::Thread>))(std::shared_ptr<folly::ThreadPoolExecutor::Thread>)>::operator()<, void>()
                       /usr/include/c++/9/functional:484
                       -> /var/git/gluten/ep/build-velox/build/velox_ep/folly/_build/../folly/executors/ThreadPoolExecutor.cpp
    @ 00000000067cb407 void folly::detail::function::FunctionTraits<void ()>::callSmall<std::_Bind<void (folly::ThreadPoolExecutor::*(folly::ThreadPoolExecutor*, std::shared_ptr<folly::ThreadPoolExecutor::Thread>))(std::shared_ptr<folly::ThreadPoolExecutor::Thread>)> >(folly::detail::function::Data&)
                       /var/git/gluten/ep/build-velox/build/velox_ep/folly/_build/../folly/Function.h:346
                       -> /var/git/gluten/ep/build-velox/build/velox_ep/folly/_build/../folly/executors/ThreadPoolExecutor.cpp
    @ 0000000000000000 (unknown)
    @ 0000000000008608 start_thread
    @ 000000000011f352 clone


```
