### ISSUE TITLE
Parquet reader build failed on Ubuntu "parquet/level_conversion.h: No such file or directory"

### ISSUE THREAD

**Issue by yingsu00** [facebookincubator/velox#7399]
### Problem description

https://app.circleci.com/pipelines/github/facebookincubator/velox/37300/workflows/4017e73d-c53f-4601-9fa8-3cdd480aa7aa/jobs/250552

level_conversion.h was moved from Arrow_ep to dwio/parquet/writer/arrow/utils in recent refactors.

```
FAILED: velox/connectors/hive/storage_adapters/s3fs/tests/CMakeFiles/velox_s3insert_test.dir/S3InsertTest.cpp.o 
ccache /opt/rh/gcc-toolset-9/root/bin/g++  -DAWS_MQTT_WITH_WEBSOCKETS -DAWS_SDK_VERSION_MAJOR=1 -DAWS_SDK_VERSION_MINOR=10 -DAWS_SDK_VERSION_PATCH=57 -DAWS_USE_EPOLL -DBOOST_ALL_NO_LIB -DBOOST_CONTEXT_DYN_LINK -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DFMT_LOCALE -DFOLLY_HAVE_INT128_T=1 -DGFLAGS_IS_A_DLL=0 -DSIMDJSON_THREADS_ENABLED=1 -DVELOX_ENABLE_GCS -DVELOX_ENABLE_HDFS3 -DVELOX_ENABLE_PARQUET -DVELOX_ENABLE_S3 -I../../. -I../../velox/external/xxhash -I_deps/xsimd-src/include -I. -I_deps/simdjson-src/include -isystem ../../velox -isystem ../../velox/external -isystem ../../velox/external/duckdb -isystem ../../velox/external/duckdb/tpch/dbgen/include -isystem /usr/include/libdwarf -isystem _deps/gtest-src/googletest/include -isystem _deps/gtest-src/googletest -mavx2 -mfma -mavx -mf16c -mlzcnt -std=c++17 -mbmi2 -D USE_VELOX_COMMON_BASE -D HAS_UNCAUGHT_EXCEPTIONS -Wall -Wextra -Wno-unused        -Wno-unused-parameter        -Wno-sign-compare        -Wno-ignored-qualifiers        -Wno-implicit-fallthrough          -Wno-empty-body          -Wno-class-memaccess          -Wno-comment          -Wno-int-in-bool-context          -Wno-redundant-move          -Wno-array-bounds          -Wno-maybe-uninitialized          -Wno-unused-result          -Wno-format-overflow          -Wno-strict-aliasing          -Wno-type-limits          -Wno-stringop-overflow          -Wno-stringop-overread          -Wno-return-type -Werror -O3 -DNDEBUG -fPIE   -pthread -DS2N_KYBER512R3_AVX2_BMI2 -DS2N_STACKTRACE -DS2N_CPUID_AVAILABLE -DS2N_FEATURES_AVAILABLE -fPIC -DS2N_FALL_THROUGH_SUPPORTED -DS2N___RESTRICT__SUPPORTED -DS2N_MADVISE_SUPPORTED -DS2N_CLONE_SUPPORTED -DS2N_LIBCRYPTO_SUPPORTS_EVP_MD5_SHA1_HASH -DS2N_LIBCRYPTO_SUPPORTS_EVP_RC4 -DS2N_LIBCRYPTO_SUPPORTS_EVP_MD_CTX_SET_PKEY_CTX -std=gnu++17 -MD -MT velox/connectors/hive/storage_adapters/s3fs/tests/CMakeFiles/velox_s3insert_test.dir/S3InsertTest.cpp.o -MF velox/connectors/hive/storage_adapters/s3fs/tests/CMakeFiles/velox_s3insert_test.dir/S3InsertTest.cpp.o.d -o velox/connectors/hive/storage_adapters/s3fs/tests/CMakeFiles/velox_s3insert_test.dir/S3InsertTest.cpp.o -c ../../velox/connectors/hive/storage_adapters/s3fs/tests/S3InsertTest.cpp
In file included from ../.././velox/dwio/parquet/reader/ParquetReader.h:23,
                 from ../../velox/connectors/hive/storage_adapters/s3fs/tests/S3InsertTest.cpp:23:
../.././velox/dwio/parquet/reader/ParquetTypeWithId.h:19:10: fatal error: parquet/level_conversion.h: No such file or directory
   19 | #include <parquet/level_conversion.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

### System information

 Backing Filesystem: xfs
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Kernel Version: 5.15.0-1039-aws
 Operating System: Ubuntu 20.04.6 LTS
 OSType: linux
 Architecture: x86_64

Starting container ghcr.io/facebookincubator/velox-dev:circleci-avx
  image cache not found on this host, downloading ghcr.io/facebookincubator/velox-dev:circleci-avx
circleci-avx: Pulling from facebookincubator/velox-dev
3f4fd5c3c800: Pull complete 
558c4424ea16: Pull complete 
cb5b844399a5: Pull complete 
8c8d3d51c149: Pull complete 
ghcr.io/facebookincubator/velox-dev:circleci-avx:
  using image ghcr.io/facebookincubator/velox-dev@sha256:3d9cfd959d1e6a1e0215b49e7c1d9df92bdd5853bf1ca3377678223dc8bdd171
  pull stats: download 978.9MiB in 7.785s (125.7MiB/s), extract 978.8MiB in 19.458s (50.3MiB/s)
  time to create container: 440ms
Digest: sha256:3d9cfd959d1e6a1e0215b49e7c1d9df92bdd5853bf1ca3377678223dc8bdd171
Status: Downloaded newer image for ghcr.io/facebookincubator/velox-dev:circleci-avx
Time to upload agent and config: 439.17612ms
Time to start containers: 569.947743ms

### CMake log

```bash
See https://app.circleci.com/pipelines/github/facebookincubator/velox/37300/workflows/4017e73d-c53f-4601-9fa8-3cdd480aa7aa/jobs/250552
```

**Comment by assignUser** [comment]
I think those headers where renamed during conversion to use camel case: `parquet/LevelConversion.h` could you try that fix in your PR?

**Comment by yingsu00** [comment]
@assignUser Thanks for replying. As far as I see, the level_conversion.h is still there at cmake-build-debug/third_party/arrow_ep/install/include/parquet/level_conversion.h, and the build step did install it there: https://app.circleci.com/pipelines/github/facebookincubator/velox/37763/workflows/7bfba05e-115e-4042-a55c-6700167d2d1f/jobs/253478?invite=true#step-105-403974_15

The newly moved in LevelConversion.h resides in the writer path: velox/dwio/parquet/writer/arrow/LevelConversion.h, and its reference in the Parquet reader will be replaced with faster native decoder that doesn't rely on these LevelInfo, etc classes in the near future, so I wanted to avoid including that file. Do you have any idea why third_party/arrow_ep/install/include/parquet/level_conversion.h was not found?

**Comment by yingsu00** [comment]
I think the possible reason was that S3InsertTest.cpp includes "velox/dwio/parquet/reader/ParquetReader.h", but it didn't check if VELOX_ENABLE_PARQUET is enabled. VELOX_ENABLE_PARQUET=ON would set VELOX_ENABLE_ARROW=ON and only when it's on it'll install arrow_ep.

**Comment by assignUser** [comment]
Ah yes that makes sense! I see you tested the fix in your PR :+1: .

**Comment by yingsu00** [comment]
Created a separate PR: https://github.com/facebookincubator/velox/pull/7510

**Comment by yingsu00** [comment]
@assignUser Will you be able to review https://github.com/facebookincubator/velox/pull/7510? Thanks!
