### ISSUE TITLE
Use Boost multiprecision to compute Presto decimal average value

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#7434]
### Description

The current decimal [average](https://github.com/facebookincubator/velox/blob/a0f2f9468d433c1fd76ab119e2e27dceff7a8a0e/velox/type/DecimalUtil.h#L279) computation is approximate.
Decimal values however are expected to be exact.

Spark decimal and multiply functions use Boost multiprecision int256_t value to avoid computation overflow.
https://github.com/facebookincubator/velox/pull/4613

We should consider using that for Presto as well.

**Comment by Yuhta** [comment]
The accumulator keeps the exact values I think?  Where does the approximation happen?

**Comment by majetideepak** [comment]
I think the [average](https://github.com/facebookincubator/velox/blob/a0f2f9468d433c1fd76ab119e2e27dceff7a8a0e/velox/type/DecimalUtil.h#L279) computation based off this is approximate.
We should use the higher precision type to compute that.

**Comment by majetideepak** [comment]
I fixed the description.

**Comment by Yuhta** [comment]
The `LongDecimalWithOverflowState` in avg is still exact.  If it's not exact, it's a bug in the code not design.

**Comment by majetideepak** [comment]
The average result is not exact.  We approximate the computation as follows
```
   *                       ---                                         ---
   *                      |    overflow_multiplier          sum          |
   * average = overflow * |     -----------------  +  ---------------    |
   *                      |         count              count * overflow  |
   *                       ---                                         ---
```
Say `overflow = 3` and `sum = 0`, count = 3`. The expected average is `overflow_multiplier = 2^127`. However, the above computation will give something other than `2^127` due to the division first.

**Comment by Yuhta** [comment]
`DecimalUtil::computeAverage(avg, 0, 3, 3)` is giving correct result with above example (with overflow error under ASAN though).  The result is exceeding the maximum allowed LONG DECIMAL so we do not really need to make it work.  Do you have another example?  Either way we do not need to change the intermediate result, just need to tweak `computeAverage`.

**Comment by majetideepak** [comment]
Yes, only the computeAverage needs a tweak. `LongDecimalWithOverflowState` stores the exact value.
Here is a reproducer
```
TEST(DecimalTest, average) {
  int128_t sum = 0;
  int64_t overflow = 0;
  int64_t count = 9;
  for (int i = 0 ; i < 9; i++) {
    overflow +=
        DecimalUtil::addWithOverflow(sum, sum, DecimalUtil::kLongDecimalMax);
  }
  int128_t avg = 0;
  DecimalUtil::computeAverage(avg, sum, count, overflow);
  ASSERT_EQ(avg, DecimalUtil::kLongDecimalMax);
}
```
```
Expected equality of these values:
  avg
    Which is: 99999999999999999999999999999999999998
  DecimalUtil::kLongDecimalMax
    Which is: 99999999999999999999999999999999999999
```
