### ISSUE TITLE
Add spilling support for aggregations with sorting/ordering.

### ISSUE THREAD

**Issue by spershin** [facebookincubator/velox#7455]
### Description

Currently we don't support spilling if aggregation nodes has aggregations with 'sorting/ordering' like this:

SELECT count(c0 ORDER BY c2) FROM tmp GROUP BY c1;

Need to add the support if we see queries with this are breaching memory limits.

**Comment by mbasmanova** [comment]
Sorted aggregations need to accumulate all input rows, then sort these within each group, then compute aggregations over sorted rows. For spilling purposes, we can Accumulator::extractFunction that returns an array of structs that represents all the input rows for a group.

**Comment by mbasmanova** [comment]
We can serialize rows as strings (VARBINARY) to save conversion to/from columnar format.
