### ISSUE TITLE
Add a test for ParquetReaderBenchmark

### ISSUE THREAD

**Issue by yingsu00** [facebookincubator/velox#7485]
### Description

The benchmark was not ran in CircleCI and Parquet code updates may cause the benchmark to fail. We want to add a test to make sure the benchmark continues functioning for every parquet reader PR.

**Comment by qqibrow** [comment]
to clarify, is the request to add a unit test to ensure ParquetReaderBenchmark class is runnable?

**Comment by yingsu00** [comment]
@qqibrow Yes that's correct. Have you started working on it? If not, @nmahadevuni can take it over.

**Comment by qqibrow** [comment]
not yet. @nmahadevuni feel free to take it over.
