### ISSUE TITLE
 Scalar function presto.default.multiply not registered with arguments: (BIGINT, INTERVAL DAY TO SECOND). 

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#7490]
### Bug description

20231107_233931_00455_s9ma5

```
 Scalar function presto.default.multiply not registered with arguments: (BIGINT, INTERVAL DAY TO SECOND). 
```

CC: @amitkdutta @kagamiori 

### System information

n/a

**Comment by mbasmanova** [comment]
Similar error: 20231109_120250_09759_nwk36

```
VeloxUserError:  Scalar function presto.default.plus not registered with arguments: (TIMESTAMP, INTERVAL DAY TO SECOND). Found function registered with the following signatures:
```

**Comment by mbasmanova** [comment]
Looks like arithmetic functions with INTERVAL DAY TO SECOND inputs are missing.

CC: @aditi-pandit

**Comment by kagamiori** [comment]
> Similar error: 20231109_120250_09759_nwk36
> 
> ```
> VeloxUserError:  Scalar function presto.default.plus not registered with arguments: (TIMESTAMP, INTERVAL DAY TO SECOND). Found function registered with the following signatures:
> ```

Hi @mbasmanova, somehow I don't find the plus(Timestamp, Interval) method defined in the IntervalDayTimeOperators.java. (https://github.com/prestodb/presto/blob/dae8a28f0ee15acee56a2086df5a56c2bb0576ef/presto-main/src/main/java/com/facebook/presto/type/IntervalDayTimeOperators.java#L48)

Do you know where this function is defined in Presto-Java?

**Comment by kagamiori** [comment]
> > Similar error: 20231109_120250_09759_nwk36
> > ```
> > VeloxUserError:  Scalar function presto.default.plus not registered with arguments: (TIMESTAMP, INTERVAL DAY TO SECOND). Found function registered with the following signatures:
> > ```
> 
> Hi @mbasmanova, somehow I don't find the plus(Timestamp, Interval) method defined in the IntervalDayTimeOperators.java. (https://github.com/prestodb/presto/blob/dae8a28f0ee15acee56a2086df5a56c2bb0576ef/presto-main/src/main/java/com/facebook/presto/type/IntervalDayTimeOperators.java#L48)
> 
> Do you know where this function is defined in Presto-Java?

No worries. I found it in the DateTimeOperators.java.
https://github.com/prestodb/presto/blob/6c48ec5d0a6ceac7cd75446d33674bac2ae4199e/presto-main/src/main/java/com/facebook/presto/type/DateTimeOperators.java#L91C1-L96

**Comment by mbasmanova** [comment]
@kagamiori Wei, it is in presto-main/src/main/java/com/facebook/presto/type/DateTimeOperators.java

```
    @ScalarOperator(ADD)
    @SqlType(StandardTypes.TIMESTAMP)
    public static long timestampPlusIntervalDayToSecond(@SqlType(StandardTypes.TIMESTAMP) long left, @SqlType(StandardTypes.INTERVAL_DAY_TO_SECOND) long right)
    {
        return left + right;
    }
```
