### ISSUE TITLE
Better messaging for Function signature errors . 

### ISSUE THREAD

**Issue by kgpai** [facebookincubator/velox#7501]
### Description

Currently when we detect incompatible changes in when running the function signature check CI job, we get inscrutable error messages . Eg : https://github.com/facebookincubator/velox/pull/7115#issuecomment-1801365422 . We need to make these more user friendly.

**Comment by mbasmanova** [comment]
The error message for "Incompatible changes in function signatures have been detected." is very cryptic and people cannot understand it without help. 

Example: https://github.com/facebookincubator/velox/pull/7115#issuecomment-1801365422

"Iterable item removed:" and "Found differences:" is not something regular humans understand. 

It would be nice to change these messages to something like this:

```
Incompatible changes in function signatures have been detected.

    * dayofmonth(date) -> bigint is changed to dayofmonth(date) -> integer
    * dayofmonth(timestamp) -> bigint is removed

Changing or removing function signatures breaks backwards compatibility as some users may rely on function signatures that no longer exist.
```

**Comment by mbasmanova** [comment]
Seeing another cryptic error message on PR #7497

```
Iterable item removed: [<root['in'][0] t1:'(T,constant...', t2:not present>, <root['in'][1] t1:'(T,constant...', t2:not present>]
Found differences: {'iterable_item_removed': [<root['in'][0] t1:'(T,constant...', t2:not present>, <root['in'][1] t1:'(T,constant...', t2:not present>], 'iterable_item_added': [<root['in'][0] t1:not present, t2:'(T,array(T)...'>, <root['in'][1] t1:not present, t2:'(T,array(un...'>]}
 
            Incompatible changes in function signatures have been detected.
            This means your changes have modified function signatures and possibly broken backwards compatibility.  
```

Here, no signature was removed, but more signatures were added. It looks like the checking logic is not quite correct.

Also, for some reason this failure shows up as "ci/circleci: linux-pr-fuzzer-run" failure, suggesting that Fuzzer failed. But it looks like Fuzzer didn't even run. Do these failures block fuzzer runs? They probably shouldn't.

CC: @bikramSingh91 @laithsakka @kgpai

**Comment by kgpai** [comment]
@mbasmanova In the above case Masha it is complaining about the removal of 'constness' which is possibly backwards incompatible. I will add that also to the better messaging. As per @laithsakka 's suggestion, one other thing we will do is move the signature check to end of the fuzzer run so that fuzzer can still run if we detect incompatible changes.
