### ISSUE TITLE
Equality comparison for complex types doesn't match Presto semantics

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#7536]
### Bug description

The results of comparing complex types in Velox do not match Presto when complex type values contain nulls.

Here are some examples using an array(bigint) type:

Velox result matches Presto:

```
presto:di> select array[1, null, 3] = array[1, 2, 3];
 _col0
-------
 NULL 

presto:di> select array[1, null, 3] = array[1, 2];
 _col0
-------
 false

presto:di> select array[1, null, 3] = array[1, null, 3];
 _col0
-------
 NULL
```

Velox returns NULL while Presto returns false:

```
presto:di> select array[1, null, 3] = array[1, null, 2];
 _col0
-------
 false
```

Velox unit test to reproduce:

```
TEST_F(ExprTest, xxx) {
  auto data = makeRowVector({
      makeArrayVectorFromJson<int32_t>({
          "[1, null, 3]",
          "[1, null, 3]",
          "[1, null, 3]",
          "[1, null, 3]",
      }),
      makeArrayVectorFromJson<int32_t>({
          "[1, 2, 3]",
          "[1, 2]",
          "[1, null, 3]",
          "[1, null, 2]",
      }),
  });

  auto r = evaluate("c0 = c1", data);
  LOG(ERROR) << r->toString();
  LOG(ERROR) << r->toString(0, 10);
}

0: null
1: false
2: null
3: null
```

Presto Java implementation of equality for arrays: com/facebook/presto/operator/scalar/ArrayEqualOperator.java

CC: @bikramSingh91 @laithsakka @kgpai @kagamiori

**Comment by laithsakka** [comment]
Two null handling  modes need to be and the StopAtNull mode need to be removed
 // NullIndeterminite mode
 // This mode is needed by presto functions that check for equality of complex
 // types, a return value of std::nullopt indicates the Indeterminate
 // results. comparing null with anything else is considered indeterminate are
 // results. not that aggregation False and Indeterminate is False.
 // While aggregating True and Indeterminate is also Indeterminate.
 // Indeterminate is reflected as Null in the final results. Example: Row(null,
 // 1) = Row(1, 2) is false. but Row(null, 1) = Row(null, 1) = Row(1, 2) is
 // null.


 // NullNotSupported
 // This mode is needed for presto functions that perform comparison for the
 // purpose of ordering. If a null is encountered it encountered an exception
 // is thrown, that exception should not be suppressed by a try. Note that if a
 // false is predetermined before the null is encountered then the result is
 // false. Example: Row(null, 2) > Row(null, 1) throws an exception. while
 // Row(1, null) > Row(2, null) is false. same apply for arrays.

**Comment by mbasmanova** [comment]
@rui-mo @PHILO-HE Folks, can you tell what are Spark semantics for comparing complex types with nested nulls? Do these match Presto or are these different?

**Comment by mbasmanova** [comment]
CC: @duanmeng

**Comment by mbasmanova** [comment]
@duanmeng Thank you for sharing Spark results for array comparison. Is this the case that Spark never returns a NULL (if neither arrays are NULL)?

**Comment by mbasmanova** [comment]
@duanmeng It seems that current Velox behavior doesn't match Spark semantics either. I also see that Spark doesn't register equalto function for complex types.

```
void registerCompareFunctions(const std::string& prefix) {
  exec::registerStatefulVectorFunction(
      prefix + "equalto", comparisonSignatures(), makeEqualTo);
```

**Comment by duanmeng** [comment]
> @duanmeng Thank you for sharing Spark results for array comparison. Is this the case that Spark never returns a NULL (if neither arrays are NULL)?

@mbasmanova I believe so.

>It seems that current Velox behavior doesn't match Spark semantics either. I also see that Spark doesn't register equalto function for complex types.

I am not sure about this, I will investigate it.

**Comment by rui-mo** [comment]
@mbasmanova Below is the compare logic of Array type in Spark. Array with null is regareded as smaller if its null value occurs earlier than the other. I believe a separate compare function is needed to match with Spark semantics.

https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/types/PhysicalDataType.scala#L281-L315

**Comment by laithsakka** [comment]
NullNotSupported is not an independent mode, its part of NullIndeterminite

  // NullIndeterminite is needed by presto functions a return value of
  // std::nullopt indicates an indeterminite results. Comparing null with
  // anything else is considered indeterminate results. note that aggregating
  // False and Indeterminate is False. While aggregating True and Indeterminate
  // is Indeterminate.

  // Indeterminate is reflected as Null in the final results when equalsOnly is
  // true. Example: Row(null, 1) = Row(1, 2) is false. but Row(null, 1) =
  // Row(null, 1) = Row(1, 2) is null.

  // Indeterminate generate as a user error that is not suppressed by a try
  // when equalsOnly is false.
  // Example: Row(null, 1) = Row(1, 2) is false. But, Row(null, 1) = Row(null,
  // 1) = Row(1, 2) is null.

**Comment by laithsakka** [comment]
when nulls are encountered sometimes we throw a suppressed error and sometimes not supressed error
this means that functions need to control throwing the error and it cant simply happen inside the compare call..

this fail
select try (Array[null,null]> Array[1,null])
but this is null 
select try(array_sort(Array[Array[null,null],Array[1,null]]))

**Comment by mbasmanova** [comment]
In SQL, NULL indicates unknown value. When evaluating an expression with NULL, it may not be possible to arrive at a concrete answer, in which case the result is NULL (unknown).

For example, 'NULL AND true' is NULL because the answer can be true if unknown value is true or the answer can be false if unknown value is false.

```
SELECT true AND true; -- true
SELECT false AND true; -- false

SELECT NULL AND true; -- NULL 
```

On the other hand, 'NULL AND false' is false because whether unknown value is true or false, the answer is still false. 

```
SELECT true AND false; -- false
SELECT false AND false; -- false

SELECT NULL AND false; -- false
```

This principle applies to any expression. The answer is NULL if there are 2 possible values of unknown value that produce different results.

Hence, 

- comparing (=, <, <=, >=) NULL scalar to any other value produces NULL.
- AND-ing NULL with true is NULL. AND-ing NULL with false is false.
- OR-ing NULL with true is true. OR-ing NULL with false is NULL. 
- NULL IN (`<list of values>`) is NULL if list is not empty and false otherwise.
- non-NULL IN (`<list of values>`) is true if list contains the value, false if list doesn't contain the value and doesn't contain NULL, NULL if list doesn't contain the value but contains a NULL.

Some examples,

```
SELECT null = 5; -- NULL

SELECT null < 5; -- NULL

SELECT null <= 5; -- NULL

SELECT null > 5; -- NULL

SELECT null >= 5; -- NULL

SELECT NULL and true; -- NULL

SELECT NULL and false; -- false

SELECT NULL or true; -- true

SELECT NULL or false; -- NULL

SELECT NULL in (1, 2, 3) -- NULL

SELECT 1 in (1, NULL, 3); -- true

SELECT 2 in (1, NULL, 3); -- NULL
```

Sorting a list of scalar values with NULLs produces a sorted list of non-NULL values with NULLs placed either at the start of the end of the list (based on NULLS FIRST / LAST clause).

Let's consider comparison of arrays. Equality comparison returns false if array sizes don't match. If sizes match and there is an index at which elements of the arrays compare false, the result is false. If all elements compare true, the result is true. If no elements compare false, but some compare NULL, the result is NULL.

```
boolean equals(a: array(T), b: array(T)):

  if (a.size != b.size) {
    return false;
  }

  boolean hasNull = false;
  for i : range(0, a.size) {
    r = equals(a[i], b[i])

    if (r IS NULL) {
      hasNull = true;
    } else if (r IS FALSE) {
      return false
    }
  }

  return hasNull ? NULL : true
```

Examples:

```
SELECT array[1, 2, 3] = array[1, null, 3]; -- NULL

SELECT array[1, null, 4] = array[1, null, 3]; -- false
```  

Less than comparison for arrays goes like this:

```
boolean lessThan(a: array(T), b: array(T)):
  n = min(a.size, b.size)

  for i : range(0, n):
    r = lessThan(a[i], b[i])

    if (r IS NULL) {
      return NULL
    } 

    if (r >= 0) {
      return false
    }

  return a.size < b.size
```

Examples:

```
SELECT array[1, 2] < array[1, 3, null]; -- true

SELECT array[1, null] < array[1, 3, null]; -- NULL

SELECT array[1, null, null] < array[1, 3, null]; -- NULL
```  

But there is a catch. Presto doesn't return NULL from <, >, <=, >=, but throws.

```
presto:di> SELECT array[1, 2] < array[1, 2, null];
 _col0
-------
 true

presto:di> select array[1, 2, null] < array[1, 2, null];
Query 20231115_134916_30771_ymfsk failed: ARRAY comparison not supported for arrays with null elements

presto:di> SELECT array[1, null, null] < array[1, 3];
Query 20231115_135317_31020_ymfsk failed: ARRAY comparison not supported for arrays with null elements

```

**Comment by mbasmanova** [comment]
Based on the list @rui-mo shared above, https://github.com/apache/spark/blob/master/sql/catalyst/src/main/scala/org/apache/spark/sql/catalyst/types/PhysicalDataType.scala#L281-L315, Spark semantics for comparison are different. NULL is not treated as unknown, but rather as a special value that is less than any other non-NULL value and is equal to another NULL value.

```
SELECT NULL = NULL; -- true
SELECT NULL = non-NULL; -- false
SELECT NULL < non-NULL; -- true
```

**Comment by duanmeng** [comment]
@mbasmanova Spark has the same NULL (not nested null) comparison semantics as Presto. And Spark provides a null-safe equal operator (`<=>`)
https://spark.apache.org/docs/3.3.1/sql-ref-null-semantics.html

Left Operand | Right Operand | > | >= | = | < | <= | <=>
-- | -- | -- | -- | -- | -- | -- | --
NULL | Any value | NULL | NULL | NULL | NULL | NULL | False
Any value | NULL | NULL | NULL | NULL | NULL | NULL | False
NULL | NULL | NULL | NULL | NULL | NULL | NULL | True

**Comment by mbasmanova** [comment]
CC: @aditi-pandit

**Comment by mbasmanova** [comment]
I would summarize Presto semantics as the following:

- equality return true, false or NULL and never throws.
- less than comparison return true, false or throws.
- functions that sort or compare values using less than may throw (if less than throws).
- functions that use equality may also throw if they cannot process NULL result for equality.

**Comment by laithsakka** [comment]
**The fix proposal:**

 - Indeterminate result: means that a comparison could not decide on what the result should be and is returned as std::nullopt.

### We will have three Null handling modes.
**NullIAsValue:**
This mode will match the current NoStop null mode.

**NullIAsIndeterminate:**
 This mode will match the Presto semantics for comparisons as described earlier and summarized below:
- When equalsOnly=true:
  - Results can be false, true, or Indeterminate.
  - Aggregating Indeterminate and false is false.
  - Aggregating Indeterminate and true is Indeterminate.
  - Aggregating false and true is false.
  - Aggregation happens across elements of the array and fields of structs.
  - Comparing maps happens by sorting them by keys then comparing keys as arrays and comparing values as arrays.

- When equalsOnly=false:
  - The compare will return Indeterminate results at first seen null (similar to what StopAtNull does now).
  - The compare will throw if the map is compared (not allowed on maps).
   **Question:** I wonder if we can just throw inside the compare instead of returning indeterminate,
   the only issue is that >, < throws errors that are different from array_sort. (in terms of being caught by try).
     -  <, > throws errors that try does not capture. 
     - array_sort throws errors that can be captured by try. 
    If we are ok with unifying it could simplify the repetition of throw logic at each function.

**NestedNullAsIndeterminate:**
- This mode works only with equalsOnly=false.
- This mode is needed by some sorting components like group by and array_sort.
-  In this mode, top-level nulls are treated and compared with NullIAsValue mode while any nested nulls are compared with NullIAsIndeterminate. 
- If while comparing children an Indeterminate is returned, the mode will return an Indeterminate. But it won't do that for top-level nulls.
  - null< Array[null] OR null< 1 OR null< Array[1] in this mode have determined results.
  - Array[null] < Array[null] is Indeterminate.

**Comment by laithsakka** [comment]
In the initial draft, I implemented the mode "NullIAsIndeterminate" but with the throw inside the compare for when equalsOnly=false. 

However, it addressed all Presto semantics as discussed by the notes of @mbasmanova above.
It is still a draft, so I am changing the design a bit to push the throw outside.

 Also, in my change, I combined the nullHandlingMode with the nullsFirst flag, but I think I will revert that change since the topic is complex enough without that change.

**Comment by laithsakka** [comment]
updated the proposal by adding items about nulls found in map keys in NullAsIndeterminate mode. 
  - Comparing maps happens by sorting them by keys then comparing keys as arrays and comparing values as arrays.
     Note that its impossible for nulls to appear in keys, but they can appear nested in keys if the appear in the keys we t 
     throw runtime error. If they appear nested in the keys then the Indeterminate logic applied to arrays will be applied  
     here.
     ex: Map(Array[null)->1) = Map(Array[null)->1)  => indeterminite. 
     ex: Map(Array[1,null)->1) = Map(Array[2,null)->1)  => false. 
     ex: Map(Array[null,1)->1) = Map(Array[null,2)->1)  => false.

**Comment by laithsakka** [comment]
select Map(Array[Array[2, null]], Array[1]) =  Map(Array[Array[1, null]], Array[1])
(INVALID_FUNCTION_ARGUMENT) map key cannot be indeterminate: [2, null] TAAL[BLAME_dirs,www/flib/presto/]

Although comparing Array[2, null] = Array[1, null] is false.

select Map(Array[Row(2,null)], Array[1]) =  Map(Array[Row(3,null)], Array[1])
(INVALID_FUNCTION_ARGUMENT) map key cannot be indeterminate: [2, null] TAAL[BLAME_dirs,www/flib/presto/]


select Map(Array[Row(2,null)], Array[1]) =  Map(Array[Row(3,null)], Array[1])
(INVALID_FUNCTION_ARGUMENT) map key cannot be indeterminate: [2, null] TAAL[BLAME_dirs,www/flib/presto/]

Note: even if keys are of arrays of different sizes

select Map(Array[Array[1,2]], Array[1]) =  Map(Array[Array[1,2, null]], Array[1])
key1: Array[1,2]
compared key :Array[1,2, null]
result
(INVALID_FUNCTION_ARGUMENT) map key cannot be indeterminate: [1, 2, null] TAAL[BLAME_dirs,www/flib/presto/]

**Comment by laithsakka** [comment]
what about nested null in values of map?
1) if keys are not match values not checked
```select Map(Array[1,2], Array[1, null]) =  Map(Array[1,3], Array[1, null])```
false.

2) Comparing values follow NullAsIndeterminate mode

```select Map(Array[1], Array[Array[null, 1]]) =  Map(Array[1], Array[Array[ null, 2]])```
false

```select Map(Array[1], Array[Array[1,2]]) =  Map(Array[1], Array[Array[ 1,2, null]])```
false

**Comment by laithsakka** [comment]
so it looks like the open question is now checked all keys for nested nulls is on add behaviour with actually odd message, 
is it a presto bug, or a feature we need to add to Velox.

**Comment by laithsakka** [comment]
Nested Nulls not allowed in keys I remember filing this 
https://github.com/prestodb/presto/issues/20868
and Presto folks told me Velox should not allow nested nulls in keys

the error above is coming from the map construction function, not the eq function.
MapFromEntries will allow it due to bug in presto, but we shall ignore that

**Comment by laithsakka** [comment]
updated proposal for map handling of NullAsIndeterminate equalsOnly=true mode for null in keys. 
Note that nested nulls should are not supported in presto in keys and the same applies for top level nulls so nothing to  worry about there.

**Comment by laithsakka** [comment]
after addressing all changes make sure this is fixed:
```
Also getting errors from Presto for Window operator with maps as sorting keys. This is not allowed in Presto because maps are not orderable, but the query succeeds in Velox.
```

**Comment by laithsakka** [comment]
the compare is fixed, the remaining part is 


**NestedNullAsIndeterminate:**
- This mode works only with equalsOnly=false.
- This mode is needed by some sorting components like order by and array_sort.
-  In this mode, top-level nulls are treated and compared with NullIAsValue mode while any nested nulls are compared with NullIAsIndeterminate. 
- If while comparing children an Indeterminate is returned, the compare will return an Indeterminate. But it won't do that for top-level nulls.
  - null< Array[null] OR null< 1 OR null< Array[1] in this mode have determined results.
  - Array[null] < Array[null] is Indeterminate.
  
  
  I will close this issue and put this in its own issue.
