### ISSUE TITLE
Circle-Ci linux-build test failures

### ISSUE THREAD

**Issue by soumiiow** [facebookincubator/velox#7593]
### Bug description

Circle-Ci linux-build failing for PR https://github.com/facebookincubator/velox/pull/7285. However, upon rerunning the failed tests in my local main branch, still getting those failures 

### System information

Velox System Info v0.0.2
Commit: 1c5387d93a6b7112f4cc6adc241bff4b7191b880
CMake Version: 3.27.7
System: Darwin-22.6.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 14.0.3.14030022
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 14.0.3.14030022
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX13.3.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.27.7;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

### Relevant logs

```bash
When running the following tests in Circle-CI or locally in my main branch getting the following failed tests:
velox_functions_lib_test (Failed)        
velox_functions_test (Failed)
velox_exec_test (Failed)

velox_exec_test
[  FAILED  ] ThreadDebugInfoDeathTest.withinSeperateDriverThread
[  FAILED  ] ThreadDebugInfoDeathTest.withinQueryCompilation
[  FAILED  ] ThreadDebugInfoDeathTest.withinTheCallingThread
[  FAILED  ] PrintPlanWithStatsTest.partialAggregateWithTableScan
[  FAILED  ] TableScanTest.validFileNoData
[  FAILED  ] SpillTestSuite/SpillTest.spillState/1, where GetParam() = 1
[  FAILED  ] SpillTestSuite/SpillTest.spillState/3, where GetParam() = 4
[  FAILED  ] SpillTestSuite/SpillTest.spillState/5, where GetParam() = 6
[  FAILED  ] SpillTestSuite/SpillTest.spillStateWithSmallTargetFileSize/1, where GetParam() = 1
[  FAILED  ] SpillTestSuite/SpillTest.spillStateWithSmallTargetFileSize/3, where GetParam() = 4
[  FAILED  ] SpillTestSuite/SpillTest.spillStateWithSmallTargetFileSize/5, where GetParam() = 6

velox_functions_test
[  FAILED  ] ProbabilityTest.betaCDF
[  FAILED  ] ProbabilityTest.chiSquaredCDF
[  FAILED  ] ProbabilityTest.fCDF
[  FAILED  ] ProbabilityTest.binomialCDF

velox_functions_lib_test
[  FAILED  ] KllSketchTest.deserialize
[  FAILED  ] KllSketchTest.memoryUsage
```

**Comment by ashokku2022** [comment]
@aditi-pandit @kgpai Could you please look at it and let us know, thanks!

**Comment by kgpai** [comment]
Hi Soumiya, 

> Circle-Ci linux-build failing for PR https://github.com/facebookincubator/velox/pull/7285. However, upon rerunning the failed tests in my local main branch, still getting those failures 

I am trying to understand this,  are you saying CCI is failing for your PR and is also failing locally ? Do the failing tests work against a clean main without your changes or do you still see failures there ?

**Comment by soumiiow** [comment]
@kgpai Hi Krishna! To clarify, I'm noticing that since yesterday, CCI has been failing for my PR. This morning, after syncing my branches again, I saw that these failures in the description also occurred on my clean main without my local changes.

**Comment by kgpai** [comment]
Are you running on a mac ? Your local failures could be attributed to some tests not running on a mac (we still dont have unit tests up for them in CI). 
As per this https://app.circleci.com/pipelines/github/facebookincubator/velox/38497/workflows/472e4b7b-da4d-47eb-9db8-391921fc57db/jobs/259745 last sync to main had all tests succeeding atleast on linux

**Comment by aditi-pandit** [comment]
@soumiiow : DId you look into why the failures were happening ? Dig deeper into the error messages ?

Below tests were written by IBM engineers and shouldn't fail imo 

[  FAILED  ] ProbabilityTest.betaCDF
[  FAILED  ] ProbabilityTest.chiSquaredCDF
[  FAILED  ] ProbabilityTest.fCDF
[  FAILED  ] ProbabilityTest.binomialCDF

**Comment by soumiiow** [comment]
So seems like some of these errors I pointed out, I noticed running locally on my Mac, as @kgpai indicated. I rebased my code to the latest main and everything passes now. Thank you for the help!! Closing this issue.
