### ISSUE TITLE
VectorFuzzer::Options::containerHasNulls doesn't work as described

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#7637]
### Bug description

containerHasNulls is supposed to allow for generating array/maps/structs with no nested nulls. However, the implementation doesn't match the comment and instead controls whether the array/map/struct is null or not.

```
    /// If true, fuzzer will generate top-level nulls for containers
    /// (arrays/maps/rows), i.e, nulls for the containers themselves, not the
    /// elements.
    ///
    /// The amount of nulls are controlled by `nullRatio`.
    bool containerHasNulls{true};
```

CC: @pedroerp @laithsakka @kgpai @kagamiori 

### System information

n/a

**Comment by pedroerp** [comment]
I can take a look at this one.
