### ISSUE TITLE
Remove thread local from HdfsFile in HdfsReadFile

### ISSUE THREAD

**Issue by kgpai** [facebookincubator/velox#7638]
### Bug description

folly::ThreadLocal exists till end thread is destoryed and will hold max size of HdfsFile across queries that have been processed. For long running threads this can eventually lead to OOMS. We should possibly replace this with folly::synchronized or equivalent.

See: https://github.com/facebookincubator/velox/blob/main/velox/connectors/hive/storage_adapters/hdfs/HdfsReadFile.h#L92

### System information

N/A

### Relevant logs

```bash
N/A
```

**Comment by kgpai** [comment]
cc: @chenxu14 , @Yuhta

**Comment by Yuhta** [comment]
Verified `ThreadLocal` itself alone is not the cause of OOM
