### ISSUE TITLE
set_union fails on aggregation fuzzer

### ISSUE THREAD

**Issue by laithsakka** [facebookincubator/velox#7657]
### Description

https://app.circleci.com/pipelines/github/facebookincubator/velox/38803/workflows/da5eb248-a242-4cdd-803d-5391d281857e/jobs/262361

check nightly fuzzer jobs also. 
```
This could be because set_union implementation in Velox doesn't respect the order of input (while in Presto it does).

presto:di> select set_union(array[x] order by x) from unnest(array[1, 2, 3, 2, 4]) as t(x);
    _col0
--------------
 [1, 2, 3, 4]

presto:di> select set_union(array[x] order by x desc) from unnest(array[1, 2, 3, 2, 4]) as t(x);
    _col0
--------------
 [4, 3, 2, 1]
```

**Comment by laithsakka** [comment]
One way to fix this is by using  a a hashSet and  a vector that stores the values In order in the accumulator.
Another way is to use an orderedList instead of hashSet, first will use more memory second will be more runtime.

**Comment by mbasmanova** [comment]
velox/functions/prestosql/aggregates/MapAccumulator.h has logic that might be helpful here.

**Comment by mbasmanova** [comment]
set_agg has the same issue.

**Comment by kgpai** [comment]
Working on this now.

**Comment by kgpai** [comment]
We can do something similar to what is done in MapAccumulator to SetAccumulator . In MapAccumulator we keep a map between key and size of the map when the key is inserted and use that to determine order. Doing that in SetAccumulator and making appropriate changes in SetBaseAggregate should give us similar behavior in set_union and set_agg.
