### ISSUE TITLE
Add window function fuzzer

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#7754]
### Description

The window operator is currently being tested in aggregation fuzzer with Presto aggregation functions. However, the window-specific functions, such as first_value, last_value, lag, and lead, are not tested yet. Also, aggregation fuzzer doesn't test window operator with random frames.

**Comment by kagamiori** [comment]
Some methods in the AggregationFuzzer class can be reused by the window function fuzzer, including
findInputGenerator(), 
makeSplits(), 
deserialize(), 
getFuzzerOptions(), 
generateKeys(), 
generateSortingKeys(), 
pickSignature(), 
generateInputData(),  
execute(), 
computeReferenceResults(). 

We can extract these methods into a base class `AggregationFuzzerBase` and let AggregationFuzzer and WindowFuzzer both inherit AggregationFuzzerBase.

**Comment by aditi-pandit** [comment]
@kagamiori : We definitely want to add Window function fuzzer testing. Its something we are taking on next in our development.

I too was putting some thought in how to do this and there is lot of re-use between AggregationFuzzer possible for it. In addition to the functions above we need to do more work for generating fuzzer frames as well. 

Are you proposing to do the refactoring you have mentioned above or its at an idea stage ?

**Comment by kagamiori** [comment]
> @kagamiori : We definitely want to add Window function fuzzer testing. Its something we are taking on next in our development.
> 
> I too was putting some thought on how to do this. There is re-use with AggregationFuzzer possible for it. In addition to the functions above we need to do more work for generating fuzzer frames as well.
> 
> Are you proposing to do the refactoring mentioned above or its at an idea stage ?

Hi @aditi-pandit, I'm planning to start refactoring AggregationFuzzer today if you haven't started yet, and the next step is to build a WindowFuzzer on top of `AggregationFuzzerBase`. What's your plan? Maybe we can work together.

**Comment by aditi-pandit** [comment]
@kagamiori : That's great. We can work together. Thanks so much.

- As a first step, we can take what was being done in AggregationFuzzer for window in the past and extend it to pick up non-aggregate window functions.  We can start with the ranking functions as many of those don't require parameters.  But lets also do the refactoring you are suggesting with AggregationFuzzerBase to a point that we can invoke the WindowFuzzer separately via its own command line flags. 

- The next step would be to extend WindowFuzzer for value functions that could use column parameters. 
- Then we could add fuzzer generated frames. 

If you start with the first bullet, then I can work on the more window specific extensions in the second and third bullet.

**Comment by kagamiori** [comment]
> @kagamiori : That's great. We can work together. Thanks so much.
> 
> * As a first step, we can take what was being done in AggregationFuzzer for window, and extend it to pick up non-aggregate window functions.  We can start with the ranking functions as many of those don't require parameters.  But lets also do the refactoring you are suggesting with AggregationFuzzerBase to a point that we can invoke the WindowFuzzer separately via its own command line flags.
> * The next step would be to extend WindowFuzzer for value functions that could use column parameters.
> * Then we could add fuzzer generated frames.
> 
> If you start with the first bullet, then I can work on the more window specific extensions in the second and third bullet.
> 
> Feel free to suggest any specific items you want to do in this issue as well. We can collaborate here.

@aditi-pandit: Sounds great. I'll start with the refactoring then.

**Comment by kagamiori** [comment]
When comparing fuzzer result against Presto-Java, I noticed that the columns in the partition-by clause cannot be complex-typed columns with NULL elements because Presto-Java doesn't support sorting on such columns. However, since the random data is typically generated for all columns together (unless custom input generator is used), VectorFuzzer has no idea which columns are the partition-by key columns, so all columns are generated with the same VectorFuzzer::Options.

I mitigated this issue by setting VectorFuzzer::Options::containerHasNulls to false for all input columns. We could extend VectorFuzzer API to allow us indicating a subset of columns that shouldn't contain NULL elements in the future if needed.

cc @kgpai @mbasmanova

**Comment by mbasmanova** [comment]
> I noticed that the columns in the partition-by clause cannot be complex-typed columns with NULL elements because Presto-Java doesn't support sorting on such columns.

It is probably something slightly different. Presto Type has orderable property. Types with maps are non-orderable. Other types are. For orderable types, the rules for sorting are complicated and they do allow nulls, but not always. See https://github.com/facebookincubator/velox/issues/7536#issuecomment-1812592270

**Comment by kagamiori** [comment]
Closing this issue since the fuzzer has been added.
