### ISSUE TITLE
Max spill run limit to avoid large memory allocation failure under batch workload

### ISSUE THREAD

**Issue by xiaoxmeng** [facebookincubator/velox#7760]
### Description

We have seen memory allocation failure from the memory allocator under Prestissimo on Spark workload. The allocation size is very large ~1GB and the allocation is made from spilling memory pool. It is likely caused by extreme large number of rows so that the spill run vector needs to allocate a large amount of memory. Have chat with @mbasmanova, to limit the spilling memory usage, we would better to put a limit on max spill run (a disk spilling config), that is, the max number of rows in a sorted run on disk.

**Comment by xiaoxmeng** [comment]
cc @mbasmanova @bikramSingh91 @duanmeng

**Comment by duanmeng** [comment]
@xiaoxmeng Hi Xuan, I've written a test to get the relation between pool memory usage and row number. I think the suitable row number should be `50 * 1024 * 1024`, (400MB memory usage in theory). What do you think?
The test runs 7 rounds and pushes 10 * 1024 * 1024 pointers into the vector in each round. The memory usage in the pool increases by [128, 256, 512 ...] if the current memory is less than the theory memory.
cc @mbasmanova 

### Detail Results
| rows (million) | usage (MB) | peak (MB) | usage in theory (MB) |
| --- | --- | --- | --- |
| 10 | 128 | 192 | 80 |
| 20 | 256 | 384 | 160 |
| 30 | 256 | 384 | 240 |
| 40 | 512 | 768 | 320 |
| 50 | 512 | 768 | 400 |
| 60 | 512 | 768 | 480 |
| 70 | 1024 | 1536 | 560 |

### Test Codes
```c++
int main(int argc, char* argv[]) {
 gflags::ParseCommandLineFlags(&argc, &argv, true);
 auto rootPool = defaultMemoryManager().addRootPool("root");
 auto pool = rootPool->addLeafChild("subPool");
 auto stlAllocator = memory::StlAllocator<char*>(*pool);

 std::vector<char*, memory::StlAllocator<char*>> rows(0, stlAllocator);

 char* ptr = "deadbeaf";
 uint64_t MB = 1 << 20;
 for (int r = 0; r < 7; ++r) {
   for (auto i = 0; i < 10 * MB; ++i) {
     rows.push_back(ptr);
   }

   LOG(INFO) << "=== Round " << r + 1 << " ===";
   LOG(INFO) << (r + 1) * 10 << " million rows, theory memory usage " << sizeof(char*) * (r + 1) * 10 << "MB";
   LOG(INFO) << pool->treeMemoryUsage();
 }

 return 0;
}
```

### Logs

```YAML
/Users/macduan/work/native/velox-5/cmake-build-debug-mactoolchain/velox/exec/tests/spill_run_benchmark
WARNING: Logging before InitGoogleLogging() is written to STDERR
I20231205 19:58:07.735734 3015288 SpillRunBenchmarkTest.cpp:40] === Round 1 ===
I20231205 19:58:07.736274 3015288 SpillRunBenchmarkTest.cpp:41] 10 million rows, theory memory usage 80MB
I20231205 19:58:07.736281 3015288 SpillRunBenchmarkTest.cpp:42] root usage 128.00MB peak 192.00MB
    subPool usage 128.00MB peak 192.00MB

Top 1 leaf memory pool usages:
    subPool usage 128.00MB peak 192.00MB
I20231205 19:58:07.964769 3015288 SpillRunBenchmarkTest.cpp:40] === Round 2 ===
I20231205 19:58:07.964804 3015288 SpillRunBenchmarkTest.cpp:41] 20 million rows, theory memory usage 160MB
I20231205 19:58:07.964810 3015288 SpillRunBenchmarkTest.cpp:42] root usage 256.00MB peak 384.00MB
    subPool usage 256.00MB peak 384.00MB

Top 1 leaf memory pool usages:
    subPool usage 256.00MB peak 384.00MB
I20231205 19:58:08.112907 3015288 SpillRunBenchmarkTest.cpp:40] === Round 3 ===
I20231205 19:58:08.112941 3015288 SpillRunBenchmarkTest.cpp:41] 30 million rows, theory memory usage 240MB
I20231205 19:58:08.112947 3015288 SpillRunBenchmarkTest.cpp:42] root usage 256.00MB peak 384.00MB
    subPool usage 256.00MB peak 384.00MB

Top 1 leaf memory pool usages:
    subPool usage 256.00MB peak 384.00MB
I20231205 19:58:08.448788 3015288 SpillRunBenchmarkTest.cpp:40] === Round 4 ===
I20231205 19:58:08.448832 3015288 SpillRunBenchmarkTest.cpp:41] 40 million rows, theory memory usage 320MB
I20231205 19:58:08.448838 3015288 SpillRunBenchmarkTest.cpp:42] root usage 512.00MB peak 768.00MB
    subPool usage 512.00MB peak 768.00MB

Top 1 leaf memory pool usages:
    subPool usage 512.00MB peak 768.00MB
I20231205 19:58:08.592370 3015288 SpillRunBenchmarkTest.cpp:40] === Round 5 ===
I20231205 19:58:08.592399 3015288 SpillRunBenchmarkTest.cpp:41] 50 million rows, theory memory usage 400MB
I20231205 19:58:08.592406 3015288 SpillRunBenchmarkTest.cpp:42] root usage 512.00MB peak 768.00MB
    subPool usage 512.00MB peak 768.00MB

Top 1 leaf memory pool usages:
    subPool usage 512.00MB peak 768.00MB
I20231205 19:58:08.735596 3015288 SpillRunBenchmarkTest.cpp:40] === Round 6 ===
I20231205 19:58:08.735623 3015288 SpillRunBenchmarkTest.cpp:41] 60 million rows, theory memory usage 480MB
I20231205 19:58:08.735630 3015288 SpillRunBenchmarkTest.cpp:42] root usage 512.00MB peak 768.00MB
    subPool usage 512.00MB peak 768.00MB

Top 1 leaf memory pool usages:
    subPool usage 512.00MB peak 768.00MB
I20231205 19:58:09.264232 3015288 SpillRunBenchmarkTest.cpp:40] === Round 7 ===
I20231205 19:58:09.264259 3015288 SpillRunBenchmarkTest.cpp:41] 70 million rows, theory memory usage 560MB
I20231205 19:58:09.264264 3015288 SpillRunBenchmarkTest.cpp:42] root usage 1.00GB peak 1.50GB
    subPool usage 1.00GB peak 1.50GB

Top 1 leaf memory pool usages:
    subPool usage 1.00GB peak 1.50GB

Process finished with exit code 0

```

**Comment by mbasmanova** [comment]
@xiaoxmeng @duanmeng It would be nice to keep memory usage under 100MB as we also need to reserve some memory for the actual spilling. Maybe we could put a limit at 10M rows (or lower).

**Comment by mbasmanova** [comment]
Since we know how many rows there are, we can use std::vector::reserve to allocate what's needed (or AlignedBuffer::allocate) and avoid 2x overhead we may get with default vector's implementation.

**Comment by duanmeng** [comment]
> Since we know how many rows there are, we can use std::vector::reserve to allocate what's needed (or AlignedBuffer::allocate) and avoid 2x overhead we may get with default vector's implementation.

@mbasmanova We can not know how many rows we will list from `ContainerRow` nor how many rows for each partition, so we list `kHashBatchSize` each time and push the actual rows into the rows vector (`spillRuns_[partition].rows`)?

https://github.com/facebookincubator/velox/blob/975ca3ac942472d6312b54280d8543a7b870d6b0/velox/exec/Spiller.cpp#L566-L595

**Comment by duanmeng** [comment]
Close this issue as #7928 landed.
