### ISSUE TITLE
Add Presto as a source of truth for Aggregation Fuzzer

### ISSUE THREAD

**Issue by kgpai** [facebookincubator/velox#7770]
### Description

Recently support has been added for PrestoQueryRunner in Velox. We can now use this to add support for Presto as a source of truth for the aggregation fuzzer. One way to achieve this is via the steps described below: 

1. Create docker script/image that has a certain version of java , preinstalled with some version of presto and required dependencies/tools. 
2. Creating a docker script/image as it helps with reproducibility and saves time during execution - i..e we do not need to build / install this on the fly and have some control on which versions of Presto to test against.  
3. Make changes to Aggregation fuzzer to run on this docker image and invoke calling presto via fuzzer validating these changes. 
4. Run this periodically on Github Actions but before we make it monitorable we need to have regular runs where we do not see failures. 
5. Have periodic refreshes of the docker image when new versions of Presto are released.

**Comment by mbasmanova** [comment]
CC: @duanmeng @aditi-pandit @spershin
