### ISSUE TITLE
ParquetTpchTest.xxx often timeout after 10min

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#7855]
### Bug description

We are seeing frequent timeouts for ParquetTpchTest.xxx tests. These tests seem to take more than 10 min to run. It would be nice to optimize the tests to run faster.

CC: @majetideepak @Yuhta @pedroerp 

### System information

n/a

**Comment by majetideepak** [comment]
All the time is being spent in writing TPC-H data to a DuckDB table after this change https://github.com/facebookincubator/velox/pull/6719/files
We do this per test making it ~19x slower.

**Comment by mbasmanova** [comment]
CC: @duanmeng

**Comment by majetideepak** [comment]
The fix here https://github.com/facebookincubator/velox/pull/7860 allows the test to complete in around 1 minutes 18 seconds.
Improving the performance of `DuckDbQueryRunner::createTable` is likely non-trivial.
