### ISSUE TITLE
Add support for lambda functions to StreamingAggregation

### ISSUE THREAD

**Issue by duanmeng** [facebookincubator/velox#7876]
### Description

StreamingAggregation operator currently doesn't support lambda function. It would be nice to add this capability. 

cc @mbasmanova

**Comment by mbasmanova** [comment]
CC: @xiaoxmeng

**Comment by duanmeng** [comment]
@mbasmanova Hi Masha, it seems that we could support lambda functions to StreamingAggregation directly by removing the constraint and extracting lambda inputs in `AggregationInfo::toAggregateInfo` according to this article https://velox-lib.io/blog/reduce-agg that describes the implementation only lambda aggregate Presto function. Do I understand it correctly?

**Comment by mbasmanova** [comment]
@duanmeng I believe that's correct. Thank you for looking into this.
