### ISSUE TITLE
Does Velox support dynamic partition write with overwrite?

### ISSUE THREAD

**Issue by JkSelf** [facebookincubator/velox#7878]
### Bug description

I used the `overwrite` mode in gluten, inserting two records into the same partition (part1=1, part2=1). 

```
Seq((1, 1, 1)).toDF("i", "part1", "part2").write.partitionBy("part1", "part2").parquet(tmpPath)

Seq((2, 1, 1)).toDF("i", "part1", "part2") .write.partitionBy("part1", "part2").mode("overwrite").parquet(tmpPath)
```

However, the query result was:
```
1, 1, 1
2, 1, 1
```
The second record, '2', did not overwrite the first record, '1'. 

It seems the UpdateMode defined in [here](https://github.com/facebookincubator/velox/blob/975ca3ac942472d6312b54280d8543a7b870d6b0/velox/connectors/hive/HiveDataSink.cpp#L581) is not used, right?

### System information

Velox System Info v0.0.2
Commit: 982c8e3ef1d6de735e61a39ba3eecaa586cbef26
CMake Version: 3.16.3
System: Linux-5.4.0-156-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by JkSelf** [comment]
@mbasmanova @majetideepak @Yuhta Do you have any input? Thanks.

**Comment by mbasmanova** [comment]
@JkSelf It might be easier to answer this question if you could share a Velox-only repro.

**Comment by gggrace14** [comment]
Hi @JkSelf , Velox itself is transparent to the overwrite mode or append mode. It leaves the caller system to control whether to write in overwrite mode or append mode, by setting HiveInsertTableHandle->locationHandle_ which derives HiveWriterParameters. Velox just writes to HiveWriterParameters.writeDirectory_/writeFileName_,
https://github.com/facebookincubator/velox/blob/156abe35d89b8c28a2f62f77ea499bf4e9229b0f/velox/connectors/hive/HiveDataSink.cpp#L582-L583

If we take a closer look at class LocationHandle
https://github.com/facebookincubator/velox/blob/2dc97deebba2664c4620f1e462476c5692691e4d/velox/connectors/hive/HiveDataSink.h#L80-L82

The writePath_ and targetPath_ are set by the caller system and could be used by the caller system. For example, one way to use them is, once Velox is done writing to the writePath_, the caller system could move the file at writePath_ to targetPath_. Then if the targetPath_ is set to an existing directory, the effect is to write and append. And if the target path is set to a new directory, the effect is to write and overwrite.

**Comment by kewang1024** [comment]
Like @gggrace14 mentioned above, the overwrite behavior would be performed by the caller (presto or spark), essentially the problem now is why spark is not respecting the `overwrite` mode

**Comment by JkSelf** [comment]
@gggrace14 @kewang1024 
Thanks for your reply. In my case, I mistakenly set the `writePath `and `targetPath ` to be the same when making the call. This caused it not to be overwritten. Apart from correctly setting the writePath and targetPath, do we also need to make the following settings for the 'overwrite' mode?

1. When creating the `LocationHandle`, we should set `tableType `to `kExisting`.
2. Set the `insert_existing_partitions_behavior `parameter to `kOverwrite`.

Looking forward to your response. Thanks for your help.

**Comment by JkSelf** [comment]
@gggrace14 @kewang1024 
The issue in Gluten has been resolved, and I will proceed to close it. Thank you once again for your assistance.
