### ISSUE TITLE
Use RAII version of folly::init

### ISSUE THREAD

**Issue by assignUser** [facebookincubator/velox#7894]
### Description

`folly::init` was deprecated recently and now throws a warning. In many places the use was corrected in #7700 but it caused issues with the fuzzer tests (see PR).

**Comment by majetideepak** [comment]
`folly::Init{&argc, &argv, true};` is causing the Init object to be destroyed immediately and not at the end of main. That is why we are seeing issues with benchmark and fuzzer.
Looking at the RAII folly change here https://github.com/facebook/folly/commit/7bf1486094cccb266e789a378d8e5f91e3cb7780#diff-fe24748541a4b73975e31bb08821bb15c783ecdd74e2057d256c4cd1b893ba92
`folly::init(&argc, &argv);` is deprecated and the RAII version is `folly::Init init(&argc, &argv);`
The latter does call the RAII API.

**Comment by assignUser** [comment]
Ah so the problem was me xD I'll add a fix
