### ISSUE TITLE
Make Velox compatible with fmt >= 9

### ISSUE THREAD

**Issue by assignUser** [facebookincubator/velox#7896]
### Description

AFAIK the main issue is https://github.com/fmtlib/fmt/issues/3131

**Comment by majetideepak** [comment]
Another reason to upgrade is https://github.com/fmtlib/fmt/issues/1895#issuecomment-863585031
fixed here https://github.com/fmtlib/fmt/pull/2426

**Comment by assignUser** [comment]
Likely I misunderstood the documentation because my cpp is pretty rudimentary for now.

I'll let you propose a solution :) but feel free to ping me if I can help implement it!
