### ISSUE TITLE
HashTable::fullProbe may enter an infinite loop

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#7914]
### Bug description

The for (;;) loop in HashTable::fullProbe may never exit causing the query to hang and causing the whole cluster to get stuck.

This may be happening because bucketOffset_ is a 64-bit integer, but nextBucketOffset takes it as 32-bit:

```
bucketOffset_ = table.nextBucketOffset(bucketOffset_);

int64_t nextBucketOffset(int32_t offset) const {
```

This may reproduce if we try to build a hash table with `224*1024*1024-1` unique keys (7/8 of the 2GB hash table size).

We need to add more Fuzzer-like testing to catch bugs like this faster and change all for (;;) loops to add a guard (max number of iterations).

```
int32_t nextOffset_;
```

nextOffset_ should be 64-bit as well.

CC: @aditi-pandit @xiaoxmeng @oerling @amitkdutta 

### System information

n/a

**Comment by mbasmanova** [comment]
Might be related: https://github.com/facebookincubator/velox/issues/3874

**Comment by xiaoxmeng** [comment]
https://github.com/facebookincubator/velox/pull/7925 has fixed this issue.
