### ISSUE TITLE
find_first: SQL array indices start at 1. Got 0.

### ISSUE THREAD

**Issue by laithsakka** [facebookincubator/velox#7942]
### Description

```

Error Source: USER
Error Code: INVALID_ARGUMENT
Reason: SQL array indices start at 1. Got 0.
Retriable: False
Context: find_first(c1, crc32(c2), (__a0) -> array_has_duplicates(__a0))
Top-Level Context: array_except(c0, array_union(find_first(c1, crc32(c2), (__a0) -> array_has_duplicates(__a0)), find_first(c1, crc32(c2), (__a0) -> array_has_duplicates(__a0))))
Function: operator()
File: fbcode/velox/functions/prestosql/FindFirst.cpp
Line: 175
Stack trace:
Stack trace has been disabled. Use --velox_exception_user_stacktrace_enabled=true to enable it.
```

### Error Reproduction

Meta only :
https://www.internalfb.com/intern/test/562950057189272?ref_report_id=0

**Comment by mbasmanova** [comment]
This is a bug in find_first(array, index, lambda). When array is NULL and index is invalid, the result should be NULL, not an error.

**Comment by Benedict-delay** [comment]
> This is a bug in find_first(array, index, lambda). When array is NULL and index is zero, the result should be NULL, not an error. I.e. find_first(NULL, 0, lambda) should return NULL, not error.





https://typeerror-bear.github.io/uKWaGYCVq28QY1lGAidU3G5O5mbvSCiYkQaOvOREIz/
