### ISSUE TITLE
Aggregation fuzzer: velox/dwio/dwrf/writer/ColumnWriter.cpp Reason: not supported yet HUGEINT

### ISSUE THREAD

**Issue by laithsakka** [facebookincubator/velox#7954]
### Description

https://app.circleci.com/pipelines/github/facebookincubator/velox/40396/workflows/f31dedf7-fdcc-4bef-873d-28a90f0e5a66/jobs/275959

### Error Reproduction

https://app.circleci.com/pipelines/github/facebookincubator/velox/40396/workflows/f31dedf7-fdcc-4bef-873d-28a90f0e5a66/jobs/275959

**Comment by kevinwilfong** [comment]
This looks like the same issue as reported https://github.com/facebookincubator/velox/issues/7775 just detected through a different means.
