### ISSUE TITLE
spark fuzzer try(between("c1",20492,"c2")) wrong results

### ISSUE THREAD

**Issue by laithsakka** [facebookincubator/velox#8073]
### Description

https://app.circleci.com/pipelines/github/facebookincubator/velox/40999/workflows/44e2ee11-3a2f-4f63-a457-41f631f809f1/jobs/281182

**Comment by Yuhta** [comment]
Duplicate of https://github.com/facebookincubator/velox/issues/7856

It's the first expression with `R,JwQ3j"{fM;R*u2CT.?3@4"HUEghW3T_6uAz_=qa]m'j*d4YQWH$fI$z=GKTCWK4#F>G{` that is failing
