### ISSUE TITLE
The logic for sharedSubexprs within lambdas can be a memory hog

### ISSUE THREAD

**Issue by kevinwilfong** [facebookincubator/velox#8093]
### Bug description

The logic for evaluating shared subexpressions once in Expr.cpp uses a map keyed on the addresses of the distinct input fields, which contains a SelectivityVector with the rows already processed, and a Vector containing the results for the already processed rows.
https://github.com/facebookincubator/velox/blob/d3f0dc9ca68e1c7a39ae38a4864ca79375840a8a/velox/expression/Expr.cpp#L872,L873

Normally this map should be small given usually only having one entry given that in order for an expression to be reused all of its input expressions need to be identical as well.

With lambdas this is not necessarily the case.  Although the expressions may be identical, the addresses of the inputs may not be.  For example, reduce wraps the input in a dictionary before each invocation of the lambda, meaning the input to each lambda is a unique Vector with a unique address. This means we can't take advantage of shared subexpressions, but worse, it can cause the sharedSubexprResults_ maps in the expression to explode, with one entry per lambda invocation.
https://github.com/facebookincubator/velox/blob/d3f0dc9ca68e1c7a39ae38a4864ca79375840a8a/velox/functions/prestosql/Reduce.cpp#L139,L143

I saw just such a case where Reduce was being called on arrays with millions of values in some rows.

This was compounded by the selectivityVectorPool_ in the ExecCtx.  Elsewhere in the lambda we were constructing LocalSelectivityVectors on the order of the size of the elements in the arrays, which would get returned to the pool and reused as the SelectivityVectors in the values of sharedSubexprResults_ on subsequent calls.

So we ended up trying to create 1,000,000 SelectivityVectors, each large enough to hold 1,000,000 bits, which easily surpassed 10's of GBs of memory.

I mention the selectivityVectorPool_ only because it's an interesting complicating factor, and was critical to this particular example (and made it much harder to debug).  However, I think the root cause is the way sharedSubexprResults_ is used within lambdas.  It's easy to envision a case where the issue occurs even with the selectivityVectorPool_ disabled.

Given that lambdas may be called many more times than other expressions, I could see a lot of value in using sharedSubexprResults_, particularly for expressions involving captured values which may be the same for every invocation.  (Although the wrapCature logic is also likely to trigger the same issue).
https://github.com/facebookincubator/velox/blob/aaaa0791008267d8be0a5c141db6da261aba8892/velox/expression/LambdaExpr.cpp#L113,L116

Should we limit the size of sharedSubexprResults_ to 1 (it gets cleared at the end of every ExprSet eval invocation)?  If we're going to get value from it, it's probably going to have the same inputs on every invocation, and this prevents the sort of unbounded growth I witnessed.

### System information

.

**Comment by bikramSingh91** [comment]
I dug into the history of the change that adds a map to manage the inputs to shared subexpressions. Looks like it was added around the time when dictionary inputs were allowed to be used as inputs to the shared sub-expressions and we witnessed instances where different levels of unwrapped inputs ended up being fed into the shared sub-expressions. With all the fixes that went in, this should now be highly unlikely so we can probably limit the size to 1 (or replace it with a mechanism that resets the cached results if a different set of inputs are used).

Like you mentioned earlier, this state should have been reset on every invocation of ExprSet, which means that some state of an expression tree should be reset between subsequent batches. For a lambda like reduce, every index from the input arrays is like a new set of input for the lambda expression tree. Maybe we should reset its state between these invocations and take a look at other lambdas that are similar. This would ensure that any state (apart from shared subexpression or any others that might be added in the future) that should be reset between input batches would consistently be reset for cases like this. If this is generic enough then we can also build this reseting functionality into the lamda function's API.

What do you think?

**Comment by kevinwilfong** [comment]
@bikramSingh91 
Thanks for digging into the history!

This is what I was trying to get at in the second to last paragraph.  Although the input arguments may be the different on each invocation, the captures will likely be the same, so not having to recompute expressions on top of those could yield a lot of benefit depending on the cost of the expressions and the number of times the lambda is invoked.

**Comment by spershin** [comment]
If this dire situation happens only for batches with very large number of elements in vectors and some lambda expressions running through them, then we can have a threshold after which we don't apply the sharedSubexprs optimization or clean it on every iteration over the elements or keep a restricted 'depth' (not 1 or infinite, but N)?

**Comment by bikramSingh91** [comment]
> @bikramSingh91 Thanks for digging into the history!
> 
> This is what I was trying to get at in the second to last paragraph. Although the input arguments may be the different on each invocation, the captures will likely be the same, so not having to recompute expressions on top of those could yield a lot of benefit depending on the cost of the expressions and the number of times the lambda is invoked.

Thats a good point, the captures are same so there might be branches inside the lambda that only rely on these, so their result can be reused. I think restricting the size to 1 (or replacing it with a mechanism that resets the cached results if a different set of inputs are used) should work well. It might still be worth checking if there is state in Expr that should be reset between subsequent iterations and make sure we do reset it.

**Comment by kevinwilfong** [comment]
Thanks for the responses, it sounds like we agree on restricting the size. I'll make the limit configurable so we can tweak it as needed.

**Comment by mbasmanova** [comment]
> I saw just such a case where Reduce was being called on arrays with millions of values in some rows.

@kevinwilfong Curious if this is happening when an array have millions of elements. Is this the case? Any chance you could share a snippet of reduce expression for that scenario. Wondering if 'reduce' call here could have been re-written into something simpler.

**Comment by kevinwilfong** [comment]
@mbasmanova here's the reduce expression in the case I saw

```
        REDUCE(
          ARRAY_AGG(
            ARRAY[
              start, start + duration
            ] 
            ORDER BY 
              start ASC
          ), 
          ARRAY[0, 0], 
          (s, x) -> ARRAY[
            s[1] + (
              IF(
                x[1] < s[2], 
                IF(
                  x[2] - s[2] > 0, 
                  x[2] - s[2], 
                  0
                ), 
                x[2] - x[1]
              )
            ), 
            IF(
              s[2] > x[2], 
              s[2], 
              x[2]
            )
          ], 
          s -> s[1]
        )
```
