### ISSUE TITLE
Add November 2023 monthly update

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#8115]
### Description

It looks like we did not add the November 2023 monthly update.

**Comment by majetideepak** [comment]
@mbasmanova do you have anyone in mind to take this up? Thanks!

**Comment by mbasmanova** [comment]
@majetideepak Hi Deepak, thank you for noticing and asking. I keep meaning to find time to put this together unsuccessfully. Any chance you could help?

**Comment by majetideepak** [comment]
@mbasmanova I can take this up.

**Comment by mbasmanova** [comment]
@majetideepak Thank you, Deepak.

**Comment by majetideepak** [comment]
https://github.com/facebookincubator/velox/pull/8148
