### ISSUE TITLE
Tests failure for MD5 and sha1 spark functions

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#8121]
### Bug description

In https://github.com/facebookincubator/velox/pull/7377, I noticed CI failure due to StringTest.MD5 and StringTest.sha1. The reason was Presto functions were used accidentally.
In `FunctionBaseTest`, Presto functions are registered with `Varbinary` as return and input type.
```
registerFunction<Md5Function, Varbinary, Varbinary>({prefix + "md5"});
registerFunction<Sha1Function, Varbinary, Varbinary>({prefix + "sha1"});
```
And Spark registers them with `Varchar` as return type and `Varbinary` as input type.
```
registerFunction<Md5Function, Varchar, Varbinary>({prefix + "md5"});
registerFunction<Sha1HexStringFunction, Varchar, Varbinary>(
      {prefix + "sha1"})
```
When registering Spark functions after Presto functions, the registration of Presto ones are not overriden due to different signatures. But when using `evaluateOnce<std::string, std::string>(
        "md5(c0)", {arg}, {VARBINARY()})` to compute, the two functions are possible to be mixed.

### System information

Velox System Info v0.0.2
Commit: 0e5d7cc350f2cea102e48e0392f78541a28a6447
CMake Version: 3.16.3
System: Linux-5.4.0-164-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;

### Relevant logs

```bash
278: [ RUN      ] StringTest.MD5
278: ../../velox/functions/sparksql/tests/StringTest.cpp:283: Failure
278: Expected equality of these values:
278:   md5("")
278:     Which is: ("\xD4\x1D\x8C\xD9\x8F\0\xB2\x4\xE9\x80\t\x98\xEC\xF8" "B~")
278:   "d41d8cd98f00b204e9800998ecf8427e"
278:     Which is: 0x43680b0
278: ../../velox/functions/sparksql/tests/StringTest.cpp:284: Failure
278: Expected equality of these values:
278:   md5("Infinity")
278:     Which is: ("\xEB*\xC5\xB0" "A\x80\xD8\xD6\x1\x1A\x1j\xEB\x8Fu\xB3")
278:   "eb2ac5b04180d8d6011a016aeb8f75b3"
278:     Which is: 0x4368100
278: [  FAILED  ] StringTest.MD5 (0 ms)
278: [ RUN      ] StringTest.sha1
278: ../../velox/functions/sparksql/tests/StringTest.cpp:289: Failure
278: Expected equality of these values:
278:   sha1("")
278:     Which is: ("\xDA" "9\xA3\xEE^kK\r2U\xBF\xEF\x95`\x18\x90\xAF\xD8\a\t")
278:   "da39a3ee5e6b4b0d3255bfef95601890afd80709"
278:     Which is: 0x4368150
278: ../../velox/functions/sparksql/tests/StringTest.cpp:290: Failure
278: Expected equality of these values:
278:   sha1("Spark")
278:     Which is: ("\x85\xF5\x95_K'\xA9\xA4\xC2\xAA\xB6\xFF\xE5\xD7\x18\x9F\xC2\x98\xB9,")
278:   "85f5955f4b27a9a4c2aab6ffe5d7189fc298b92c"
278:     Which is: 0x43681b0
278: ../../velox/functions/sparksql/tests/StringTest.cpp:291: Failure
278: Expected equality of these values:
278:   sha1("0123456789abcdefghijklmnopqrstuvwxyz")
278:     Which is: ("\xA2g\x4\xC0O\xC5\xF1\r\xB5\xAA\xB5\x84h\x3U1\xCCT$\x85")
278:   "a26704c04fc5f10db5aab58468035531cc542485"
278:     Which is: 0x4368238
278: [  FAILED  ] StringTest.sha1 (1 ms)
```

**Comment by mbasmanova** [comment]
@rui-mo Nice catch. Would you make a separate PR to fix this issue rather then include the fix in Cast refactoring PR?

**Comment by rui-mo** [comment]
@mbasmanova Opened https://github.com/facebookincubator/velox/pull/8123 for this fix. Thanks.
