### ISSUE TITLE
Optimize LIKE when input strings contain multi-byte characters

### ISSUE THREAD

**Issue by xumingming** [facebookincubator/velox#8125]
### Description

Currently we have fast path for LIKE operation when the pattern is a prefix/suffix like simple pattern, it would be nice to also have these optimizations when pattern contains unicode.

**Comment by mbasmanova** [comment]
Curious, what needs to be done different to support unicode strings?

**Comment by xumingming** [comment]
I think the main issue is about pattern matching, '_' should match with one `character`, rather than one `byte`, so for pattern like kAtLeastN, kRelaxedXxx(which contains '_'), we can't just skip `n` bytes when matching with some `_`, we need to check the input string to skip one character(variable bytes).

**Comment by mbasmanova** [comment]
@xumingming Thank you for clarifying. Makes sense. Sounds like some optimized patterns should work as is for unicode, but some need changes. kFixed, kPrefix, kSuffix and kSubstring should work as is, right? kExactlyN, kAtLeastN and kRelaxedXxx need to modified to ensure that `_` matches one possibly multi-byte characters, not one byte.

Is this correct? If so, do we have a bug currently where kExactlyN and kAtLeastN produce incorrect results for Unicode inputs?

**Comment by mbasmanova** [comment]
CC: @aditi-pandit @pramodsatya

**Comment by xumingming** [comment]
> @xumingming Thank you for clarifying. Makes sense. Sounds like some optimized patterns should work as is for unicode, but some need changes. kFixed, kPrefix, kSuffix and kSubstring should work as is, right? kExactlyN, kAtLeastN and kRelaxedXxx need to modified to ensure that `_` matches one possibly multi-byte characters, not one byte.
> 
> Is this correct? If so, do we have a bug currently where kExactlyN and kAtLeastN produce incorrect results for Unicode inputs?

@mbasmanova  I think you are right. I limited the fast path to ascii patterns only here: https://github.com/facebookincubator/velox/pull/8050/files#diff-2e3d78e46914f43b2f10ba4f76e0dd54f8a26e4bab636e37bed22f1512928c67R1303

**Comment by mbasmanova** [comment]
@xumingming If there is a bug in existing code on main, let's create a separate issue and fix it. 

>  I limited the fast path to ascii patterns only here:

Would that be sufficient? My impression is that a pattern may be ASCII: _123%, but if applied to match a unicode string with first char being multi-byte, it will produce wrong result, no?

**Comment by xumingming** [comment]
> @xumingming If there is a bug in existing code on main, let's create a separate issue and fix it.
> 
> > I limited the fast path to ascii patterns only here:
> 
> Would that be sufficient? My impression is that a pattern may be ASCII: _123%, but if applied to match a unicode string with first char being multi-byte, it will produce wrong result, no?

Um...yes, it will produce wrong result, current fast path could not do `_` matching correctly.

**Comment by mbasmanova** [comment]
@xumingming Got it. Let's create a separate GitHub issue about the existing correctness issue and prioritize fixing it.

CC: @kagamiori @amitkdutta @gggrace14 @kgpai

**Comment by xumingming** [comment]
I will submit a fix soon. Issue here: https://github.com/facebookincubator/velox/issues/8141

**Comment by mbasmanova** [comment]
@xumingming Thank you.

**Comment by pramodsatya** [comment]
> I will submit a fix soon. Issue here: #8141

Thank you @xumingming.

**Comment by xumingming** [comment]
Fixed by #8150
