### ISSUE TITLE
SEGFAULT in velox_cache_test

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#8139]
### Bug description

There is a SEGFAULT from velox_cache_test on the main branch. According to the log, the failed unit test is SsdFileTest.writeAndRead. It starts to fail after https://github.com/facebookincubator/velox/pull/6381 was merged. 

Here are three examples:
https://app.circleci.com/pipelines/github/facebookincubator/velox/41326/workflows/fe173f56-a0c2-4744-b87a-714098f124ba/jobs/283970
https://app.circleci.com/pipelines/github/facebookincubator/velox/41327/workflows/3f334ad3-72c9-4718-81e5-62a506e99e77/jobs/283980
https://app.circleci.com/pipelines/github/facebookincubator/velox/41343/workflows/c9c7be93-c9bf-4fc4-8cde-464c869218ff/jobs/284119

### System information

CI

**Comment by kagamiori** [comment]
cc @gggrace14, I wonder whether it's related to #6381. Could you help take a look?

**Comment by gggrace14** [comment]
The failure is not reproducible on local Mac or with buck test. https://github.com/facebookincubator/velox/pull/6381 actually only makes funcs available and does not add them to any execution path, I think. (So I initially thought it's not related)

I suspect it might have to do with CMakeList.txt. Feel it'll take some time to figure out. Let me disable this unit test first to unblock the main branch, as I saw another unit test was disabled.

**Comment by gggrace14** [comment]
> The failure is not reproducible on local Mac or with buck test. #6381 actually only makes funcs available and does not add them to any execution path, I think. (So I initially thought it's not related)
> 
> I suspect it might have to do with CMakeList.txt. Feel it'll take some time to figure out. Let me disable this unit test first to unblock the main branch, as I saw another unit test was disabled.

Want to ask @kgpai Krishna, in this case, will it help if I reproduce in Docker?

**Comment by gggrace14** [comment]
Also attempted https://github.com/facebookincubator/velox/pull/8145

**Comment by gggrace14** [comment]
I think https://github.com/facebookincubator/velox/pull/8145 fixed the issue. The tests are now green on the main branch, https://github.com/facebookincubator/velox/commits/main/. So closing this issue.
