### ISSUE TITLE
Parquet reader is not correctly reading the map type

### ISSUE THREAD

**Issue by liujiayi771** [facebookincubator/velox#8143]
### Bug description

We have a Parquet table that contains a map type. When using Velox to read the data, we are encountering incorrect results. The map does not have any null values, but Velox is reading several \<null:null\> key-value pairs. Additionally, there is another \<key-value\> pair in the incorrectly read map that has incorrect data.

```protobuf
optional group frequency (MAP) {
    repeated group key_value {
      required binary key (UTF8);
      optional int32 value;
    }
  }
```

```
############ Column(key) ############
name: key
path: frequency.key_value.key
max_definition_level: 2
max_repetition_level: 1
physical_type: BYTE_ARRAY
logical_type: String
converted_type (legacy): UTF8
compression: SNAPPY (space_saved: 27%)
############ Column(value) ############
name: value
path: frequency.key_value.value
max_definition_level: 3
max_repetition_level: 1
physical_type: INT32
logical_type: None
converted_type (legacy): NONE
compression: SNAPPY (space_saved: 41%)
```

During my debugging, I discovered that the definition level of these null \<key-value\> pairs is being read incorrectly. The correct definition level should be 2, but it is being read as 1 (where the maximum definition level is 2). 

The results are correct when using the Parquet C++ SDK or pandas to read this Parquet file.

### System information

N/A

**Comment by liujiayi771** [comment]
cc @yingsu00

**Comment by liujiayi771** [comment]
I will give an example to provide a simple explanation.
Correct results:
| Key | Value |
|-----|-------|
| a   |   1   |
| b   |   2   |
| c   |   3   |
| d   |   4   |
| e   |   1   |

Velox results:
| Key | Value |
|-----|-------|
| a   |   1   |
| b   |   2   |
| c   |   3   |
| z   |   2   |
| null   |   null   |

**Comment by yingsu00** [comment]
@liujiayi771 Thanks for creating the issue. This might be a metadata parsing issue. Do you think you can add a test to ParquetReaderTest with the problematic file after removing sensitive information? You can make it disabled for now. e.g. `TEST(MixedResultTest, DISABLED_test)`

**Comment by liujiayi771** [comment]
@yingsu00 Thanks. I will try to see if I can construct a test data that can reproduce the bug.

**Comment by yingsu00** [comment]
https://github.com/liujiayi771/velox/pull/1

**Comment by liujiayi771** [comment]
This bad case has been fixed.
