### ISSUE TITLE
The ArgsOverrideFunc for regexp_replace in ExpressionFuzzer is not compatible with Spark

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#8157]
### Description

When generating an expression, ExpressionFuzzer has two ways to generate the arguments: (1) generates the arguments by calling the registered ArgsOverrideFunc of the function if exists, or (2) generates random arguments according to the selected function signature if no ArgsOverrideFunc is registered for this function. ArgsOverrideFunc are registered in ExpressionFuzzer constructor and are kept in an std::unordered_map with the function names being the keys. However, the ArgsOverrideFunc registered for Presto's regexp_replace() function is not compatible with Spark's regexp_replace(). Specifically, Spark's regexp_replace() expects 3 or 4 arguments while Presto's expects 2 or 3 arguments. Right now, ExpressionFuzzer::generateRegexpReplaceArgs() only generates 2 or 3 arguments based on Presto's regexp_replace signatures.

In general, functions with the same name in Presto and in Spark (or in other engines) can have different expectations for their arguments, e.g., the number and order of arguments. So one possible solution is to move the registration of ArgsOverrideFunc out of ExpressionFuzzer to ExpressionFuzzerTest.cpp and SparkExpressionFuzzerTest.cpp, to let the fuzzer test for each engine determine which ArgsOverrideFunc to register.

This is a problem discovered by @codyschierbeck in https://github.com/facebookincubator/velox/issues/7856.

**Comment by kagamiori** [comment]
Some code pointers:
1. Registration of the ArgsOverrideFunc for regexp_replace: https://github.com/facebookincubator/velox/blob/e87462633e1aa9514044dba10a468341ddaecc05/velox/expression/tests/ExpressionFuzzer.cpp#L735-L736
2. Generation of arguments based on the registered ArgsOverrideFunc: https://github.com/facebookincubator/velox/blob/e87462633e1aa9514044dba10a468341ddaecc05/velox/expression/tests/ExpressionFuzzer.cpp#L1099
3. Presto's expression fuzzer test: https://github.com/facebookincubator/velox/blob/e87462633e1aa9514044dba10a468341ddaecc05/velox/expression/tests/ExpressionFuzzerTest.cpp#L32
4. Spark's expression fuzzer test: https://github.com/facebookincubator/velox/blob/e87462633e1aa9514044dba10a468341ddaecc05/velox/expression/tests/SparkExpressionFuzzerTest.cpp#L35

**Comment by codyschierbeck** [comment]
@kagamiori Hi! I hope you had a nice break over the holidays :).

I have been working on a couple different bugs present in both the fuzzer and regexp_replace, but I am hitting a point of debugging where some guidance might be helpful. First, a couple updates.

- I have a fix for the main issue described in this post. It is in my fork branch: https://github.com/codyschierbeck/velox/tree/fixFuzzerArgsOverrideFunc. Specifically, commit db57caa543db4eb21804cd745979d866b9b5b678. 
    -  This fix allows any engine that runs FuzzerRunner::run() to specify a set of function names (similar to skipFunctions) that ExpressionFuzzer has valid mappings for (see https://github.com/codyschierbeck/velox/commit/db57caa543db4eb21804cd745979d866b9b5b678#diff-405930bd8be6c3f3fb7c62dff30202e0805138ee20da17e5e9b86cc2bf4030c3R741-R756). If ExpressionFuzzer finds a valid mapping for an overrideFunction, it will override it. 
    - There are a few design concerns that should be addressed. 
        - First, this implementation adds a required argument to FuzzerRunner::run(). Doesn't feel like a big deal, but I can see how in the future if more fuzzer options similar to skipFunctions and overrideFunctions get added it could become an issue.
         - Second, it's not clear which of the three original override functions (empty_approx_set, regexp_replace, and switch) apply for both the Presto engine and the Spark engine. I was able run a couple greps and see that empty_approx_set is only defined in Presto, but switch seems to be a special type CallTypedExpr which I assume would apply to any current and future execution engine? As of now, my SparkExpressionFuzzer.cpp does not include switch but this investigation leads me to believe it should?


As for my debugging question, I'm running into crashes with regexp_replace that are occur after dozens of calls to regex_replace. Debugging this and having to skip my breakpoints upwards of a hundred times got tedious. So I was hoping to leverage the --sql command in velox_expression_runner_test found here: https://github.com/facebookincubator/velox/blob/main/velox/docs/develop/testing/fuzzer.rst. 

But after trying and looking at the CMakeLists.txt file for that, it seems to only work for velox_presto_sql_functions. I was considering making a prototype of one for my debugging needs, but before I did that I was wondering if that was already something in place to do that?

**Comment by kagamiori** [comment]
Hi @codyschierbeck, thank you for the update!

> @kagamiori Hi! I hope you had a nice break over the holidays :).
> 
> I have been working on a couple different bugs present in both the fuzzer and regexp_replace, but I am hitting a point of debugging where some guidance might be helpful. First, a couple updates.
> 
> * I have a fix for the main issue described in this post. It is in my fork branch: https://github.com/codyschierbeck/velox/tree/fixFuzzerArgsOverrideFunc. Specifically, commit [db57caa](https://github.com/facebookincubator/velox/commit/db57caa543db4eb21804cd745979d866b9b5b678).
>   
>   * This fix allows any engine that runs FuzzerRunner::run() to specify a set of function names (similar to skipFunctions) that ExpressionFuzzer has valid mappings for (see [codyschierbeck@db57caa#diff-405930bd8be6c3f3fb7c62dff30202e0805138ee20da17e5e9b86cc2bf4030c3R741-R756](https://github.com/codyschierbeck/velox/commit/db57caa543db4eb21804cd745979d866b9b5b678#diff-405930bd8be6c3f3fb7c62dff30202e0805138ee20da17e5e9b86cc2bf4030c3R741-R756)). If ExpressionFuzzer finds a valid mapping for an overrideFunction, it will override it.
>   * There are a few design concerns that should be addressed.
>     
>     * First, this implementation adds a required argument to FuzzerRunner::run(). Doesn't feel like a big deal, but I can see how in the future if more fuzzer options similar to skipFunctions and overrideFunctions get added it could become an issue.

You can create a `struct ExpressionFuzzerOptions` with the skipFunctions and overrideFunctions as members. This would allow us to put possibly other options in this struct and only pass one options object to FuzzerRunner::run().

> * Second, it's not clear which of the three original override functions (empty_approx_set, regexp_replace, and switch) apply for both the Presto engine and the Spark engine. I was able run a couple greps and see that empty_approx_set is only defined in Presto, but switch seems to be a special type CallTypedExpr which I assume would apply to any current and future execution engine? As of now, my SparkExpressionFuzzer.cpp does not include switch but this investigation leads me to believe it should?

"switch" is for the CASE clause in SQL, so I think Spark does need it.

> 
> As for my debugging question, I'm running into crashes with regexp_replace that are occur after dozens of calls to regex_replace. Debugging this and having to skip my breakpoints upwards of a hundred times got tedious. So I was hoping to leverage the --sql command in velox_expression_runner_test found here: https://github.com/facebookincubator/velox/blob/main/velox/docs/develop/testing/fuzzer.rst.
> 
> But after trying and looking at the CMakeLists.txt file for that, it seems to only work for velox_presto_sql_functions. I was considering making a prototype of one for my debugging needs, but before I did that I was wondering if that was already something in place to do that?

You're right that velox_expression_runner_test only works for Presto because ExpressionRunnerTest.cpp only registers Presto functions. You're welcome add a spark_expression_runner_test if that helps you.

Regarding the debugging process, since you said that the crash only occur after dozens of calls, I'm curious if you're able to reproduce the crash stably or there is any flakiness? Also, does the crash give you a stack trace? If so, you can add some logging statements in the function to see what are the last values before the crash. Another trick that might be helpful is to use `--persist_and_run_once` to save the expression and input data in files and then editing the expression to minimize it to a smallest expression that still reproduce that error (this approach requires spark_expression_runner_test). This could sometimes make the investigation simpler. (See here for instructions about --persist_and_run_once: https://facebookincubator.github.io/velox/develop/testing/fuzzer.html#accurate-on-disk-reproduction.)
