### ISSUE TITLE
Memory leaks may occur when the split preloading feature is enabled

### ISSUE THREAD

**Issue by zhli1142015** [facebookincubator/velox#8198]
### Bug description

Memory leaks may occur when the split preloading feature is enabled, either the connector thread pool is busy or the task fails or is cancelled. We've observed instances of memory leaks reported by Gluten during sporadic executions with the split preloading feature activated.

**The first error:**
```
E20231121 20:17:04.607774  1827 Exceptions.h:69] Line: /home/velox/common/memory/Memory.cpp:80, Function:~MemoryManager, Expression: numPools() == 0 (1 vs. 0) There are 1 unexpected alive memory pools allocated by user on memory manager destruction:
Memory Manager[capacity UNLIMITED alignment 64B usedBytes 169.70MB number of pools 1
List of root pools:
  __default_root__
  WholeStageIterator_root
Memory Allocator[MALLOC capacity UNLIMITED allocated bytes 177991552 allocated pages 42223 mapped pages 41519]
ARBITRATOR[GLUTEN] CAPACITY 8388608.00TB STATS[numRequests 0 numSucceeded 0 numAborted 0 numFailures 0 numNonReclaimableAttempts 0 queueTime 0us arbitrationTime 0us reclaimTime 0us shrunkMemory 0B reclaimedMemory 0B maxCapacity 0B freeCapacity 0B]], Source: RUNTIME, ErrorCode: INVALID_STATE
terminate called after throwing an instance of 'facebook::velox::VeloxRuntimeError'
ror Source: RUNTIME
Error Code: INVALID_STATE
Reason: (1 vs. 0) There are 1 unexpected alive memory pools allocated by user on memory manager destruction:
Memory Manager[capacity UNLIMITED alignment 64B usedBytes 169.70MB number of pools 1
List of root pools:
  __default_root__
  WholeStageIterator_root
Memory Allocator[MALLOC capacity UNLIMITED allocated bytes 177991552 allocated pages 42223 mapped pages 41519]
ARBITRATOR[GLUTEN] CAPACITY 8388608.00TB STATS[numRequests 0 numSucceeded 0 numAborted 0 numFailures 0 numNonReclaimableAttempts 0 queueTime 0us arbitrationTime 0us reclaimTime 0us shrunkMemory 0B reclaimedMemory 0B maxCapacity 0B freeCapacity 0B]]
Retriable: False
Expression: numPools() == 0
Function: ~MemoryManager
File: /home/velox/common/memory/Memory.cpp
Line: 80
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox6memory13MemoryManagerD1Ev
# 4  _ZN6gluten18VeloxMemoryManagerD0Ev
```

Our investigation reveals that this issue can be reproduced when the connector thread pool is either busy or hangs. The root cause is associated with the behavior of the `AsyncSource` class. Specifically, when the `move()` function is invoked before the `prepare()` function, the `make_()` function is executed within `move()`. Subsequently, the caller retrieves the result from `move()` without waiting for the completion of the `prepare()` function. The relevant code snippet can be found [here](https://github.com/facebookincubator/velox/blob/main/velox/common/base/AsyncSource.h#L104-L123).

This is an issue since Gluten is to perform memory recycling and leak check after task ended (not destroying) and in the `TableScan` class, we capture `std::shared_ptr<Task>` and retain it in the lambdas of [`split->dataSource`](https://github.com/facebookincubator/velox/blob/main/velox/exec/TableScan.cpp#L258C14-L258C14) and [`splitPreloader_`](https://github.com/facebookincubator/velox/blob/main/velox/exec/TableScan.cpp#L294). If the above situation (`make_()` function is executed within `move()`) occurs, the Task may finish without waiting for all `splitPreloader_` to complete execution in the thread pool. This can result in the Task not being destructed as Task share_ptr is still referenced, and the associated memory pool not being reclaimed. The memory is only released when all `splitPreloader_` have been executed (most of which may be empty functions), and this timing is unpredictable.

**The second one:**
```
E20231227 01:14:25.067804  8279 Exceptions.h:69] Line: /var/git/Velox/velox/common/memory/MemoryPool.cpp:408, Function:~MemoryPoolImpl, Expression: (usedReservationBytes_ == 0) && (reservationBytes_ == 0) && (minReservationBytes_ == 0) Bad memory usage track state: Memory Pool[op.0.0.0.TableScan LEAF root[WholeStageIterator_root] parent[node.0] MALLOC track-usage thread-safe]<unlimited max capacity unlimited capacity used 2.76MB available 244.00KB reservation [used 2.76MB, reserved 3.00MB, min 0B] counters [allocs 4772, frees 4762, reserves 0, releases 1, collisions 0])>, Source: RUNTIME, ErrorCode: INVALID_STATE
terminate called after throwing an instance of 'facebook::velox::VeloxRuntimeError'
  what():  Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: Bad memory usage track state: Memory Pool[op.0.0.0.TableScan LEAF root[WholeStageIterator_root] parent[node.0] MALLOC track-usage thread-safe]<unlimited max capacity unlimited capacity used 2.76MB available 244.00KB reservation [used 2.76MB, reserved 3.00MB, min 0B] counters [allocs 4772, frees 4762, reserves 0, releases 1, collisions 0])>
Retriable: False
Expression: (usedReservationBytes_ == 0) && (reservationBytes_ == 0) && (minReservationBytes_ == 0)
Function: ~MemoryPoolImpl
File: /var/git/Velox/velox/common/memory/MemoryPool.cpp
Line: 408
Stack trace:
# 0  _ZN8facebook5velox7process10StackTraceC1Ei
# 1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
# 2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_
# 3  _ZN8facebook5velox6memory14MemoryPoolImplD2Ev
# 4  _ZN6gluten18VeloxMemoryManagerD1Ev
# 5  _ZN6gluten18VeloxMemoryManagerD0Ev
# 6  0x00007fb344bc8607
```
This occurs when a task fails or is canceled, and the [prepare](https://github.com/facebookincubator/velox/blob/b42ace1a506f9441a445d91fae16105c2bdad111/velox/common/base/AsyncSource.h#L47) function is either still running or has already finished, but the [move](https://github.com/facebookincubator/velox/blob/b42ace1a506f9441a445d91fae16105c2bdad111/velox/common/base/AsyncSource.h#L85) function hasn't been invoked in time. This situation results in the [preloading DataSource](https://github.com/facebookincubator/velox/blob/b42ace1a506f9441a445d91fae16105c2bdad111/velox/exec/TableScan.cpp#L271) being referenced by split->dataSource->item_ and the memory allocated within it doesn't get released.

**Proposed solution**

To resolve the issue, I propose implementing a close function in the AsyncSource class. This function would be explicitly called for all preloading splits when closing the TableScan operator. The close function would:

1. Wait for the completion of the 'make_' function if it is executing in the thread pool.
2. Reset the 'make_' function if it has not started yet.
3. Clean up the 'item_' if 'make_' has completed, but the result 'item_' has not been returned to the caller (necessary in cases of task cancellation).

Please let me know if this make senese to you, and feel free to provide any other suggestions you may have.
Thanks.

### System information

elox System Info v0.0.2
Commit: 4e6d648a62285d28f10e38c9afbcb6d15c43bd28
CMake Version: 3.16.3
System: Linux-5.15.133.1-microsoft-standard-WSL2
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by xiaoxmeng** [comment]
@zhli1142015 I also recently see memory pool leaks but I don't see any zombie task. You mentioned that the split reload will hold the task reference. If that is the case, we shall see zombie task log? Thanks! @tanjialiang @bikramSingh91 @duanmeng

**Comment by zhli1142015** [comment]
The above log is the final entry. The error led to the crash of Spark executors, and I did not come across any logs related to zombie tasks.

I have added a new unit test to replicate the observed scenario: https://github.com/facebookincubator/velox/pull/8181/commits/9adebfc60bb0eab092be14a701eae7c317a13ca3. When executed independently, you will observe Task::numCreatedTasks() != Task::numDeletedTasks() in the final output.

**Comment by xiaoxmeng** [comment]
> When

So Gluten doesn't use Prestissimo so there is no Prestissimo shutdown process involved? Thanks!

**Comment by FelixYBW** [comment]
> Gluten doesn't use Prestissimo so there is no Prestissimo shutdown proc

How Prestissimo avoid the issue?

**Comment by zhli1142015** [comment]
Looks presto disabled split preloading because of the memory leak. I think it should be same issue.
https://github.com/prestodb/presto/issues/20020

**Comment by xiaoxmeng** [comment]
@zhli1142015 do you have a prototype fix with unit test to reproduce this? I can help take a look then. Thanks!

**Comment by majetideepak** [comment]
@zhli1142015 Thanks for this investigation. But based on your comments below, the issue in Prestissimo seems to be different from Gluten. In Prestissimo, the Task is destroyed and then we see a false positive log of a Memory Leak during the leak check. As you explained, the executor holds a reference to the Task and it should not be destroyed.

``This can result in the Task not being destructed as Task share_ptr is still referenced, and the associated memory pool not being reclaimed. The memory is only released when all splitPreloader_ have been executed ``

**Comment by xiaoxmeng** [comment]
> splitPreloader_

@zhli1142015 Yeah, it looks like this is a different issue. In Gluten, you want to drop all the pending task references when table scan finishes or closes?

**Comment by zhli1142015** [comment]
I think Gluten does memory leak check after tasks ended. If task references are not destroyed, the memory pool used by the tasks are not destroyed also. I think this is the reason we saw the error `There are 1 unexpected alive memory pools allocated by user on memory manager destruction`. This is the error we observed now. What I proposed is to make sure all resources are released before objects destructed.
@majetideepak I think this is the same issue because I saw similiar error after we revert the change https://github.com/facebookincubator/velox/pull/4849 locally. If you confirm tasks are already destroyed, then it myabe different issue.
Thanks.

**Comment by FelixYBW** [comment]
In Gltuen a task is stateless. Once it finishes, we should clean up most of the resources like the operators in the pipeline, the memory pool, the spilled files, etc. The next task scheduled to the thread may come from different query.

**Comment by majetideepak** [comment]
@zhli1142015 In https://github.com/prestodb/presto/issues/20020, we are seeing `(usedReservationBytes_ == 0) && (reservationBytes_ == 0) && (minReservationBytes_ == 0)` even with the fix https://github.com/facebookincubator/velox/pull/4849. This error is seen during the memory leak check when the task `is being` destroyed. 
In Prestissimo, the task is kept until the results are consumed and then it gets added to the cleanup queue. A periodic task checks for its ref count and deletes the task. Since the executor holds a ref to the task, it should technically not be destroyed.

**Comment by zhli1142015** [comment]
@majetideepak , thank you for your explanation, I get your point.
Our issue is caused by a race condition, and as a result, we observe different errors under different conditions. Let me explain the problem we observed. It might not be the same issue, but it could potentially help address your problem.

We observed two errors when fixing this issue. 
The first one is `There are 1 unexpected alive memory pools allocated by user on memory manager destruction`. I explained this issue above; it arises because the Task reference is hold by executors.

Another error is `Bad memory usage track state`. This can occur only when a Task fails or is canceled in Gluten env. We observed the `prepare` function might be in progress within the thread pool, rr, the `prepare` fucntion may have completed, but the `move` fucntion has not been invoked. This results in the [`DataSource`](https://github.com/facebookincubator/velox/blob/main/velox/exec/TableScan.cpp#L271C20-L271C20) is referenced by `item_`, and the allocated memory inside the data source not being released.

This is why we propose adding a close method to address this issue instead of simply removing the Task reference from the Executor.

**Comment by majetideepak** [comment]
> Another error is `Bad memory usage track state`. This can occur only when a Task fails or is canceled in Gluten env.

The above error is seen when the Task instance is destroyed. See bt below. In Gluten, do you destroy the task even if it is being referenced by the executor? Should you not wait until the executor completes? If you removed the fix `https://github.com/facebookincubator/velox/pull/4849`, then it makes sense that the task is destroyed and you see this error since the executor is still holding resources.

```
facebook::velox::detail::veloxCheckFail<>()
facebook::velox::memory::MemoryPoolImpl::~MemoryPoolImpl()
facebook::velox::exec::Task::~Task()
```

**Comment by zhli1142015** [comment]
The error is seen when destroying `gluten18VeloxMemoryManager` not task. @FelixYBW may have more context for this class.
Thanks.
```
# 3  _ZN8facebook5velox6memory14MemoryPoolImplD2Ev
# 4  _ZN6gluten18VeloxMemoryManagerD1Ev
# 5  _ZN6gluten18VeloxMemoryManagerD0Ev
```

**Comment by FelixYBW** [comment]
Since the close() function for each operator is used to clean up the context, we may release all the resource in close() function, it's more clear way and better than the automatic release in destructor.

**Comment by majetideepak** [comment]
@zhli1142015 We started to test #8181 internally. I will keep you posted.

**Comment by FelixYBW** [comment]
> @zhli1142015 We started to test #8181 internally. I will keep you posted.

Any update?

**Comment by majetideepak** [comment]
@FelixYBW We closed https://github.com/prestodb/presto/issues/20020 since we were not able to reproduce on the newer Velox code base. The fix https://github.com/facebookincubator/velox/pull/8181 was not used.

**Comment by FelixYBW** [comment]
So this fix can solve the issue we noted from Gluten. Not shown in Presto test yet. 

@xiaoxmeng Any comments?
