### ISSUE TITLE
Running scripts /setup-centos8.sh fails due to missing Boost dependency

### ISSUE THREAD

**Issue by rz-vastdata** [facebookincubator/velox#8207]
### Problem description

Seems that https://boostorg.jfrog.io/artifactory/main/release/1.72.0/source/boost_1_72_0.tar.gz is not available: 
- https://github.com/boostorg/boost/issues/842 
- https://github.com/boostorg/boost/issues/843

Relevant part of `scripts /setup-centos8.sh`:
https://github.com/facebookincubator/velox/blob/523e561d3da99a78a33c4e22106ba7d1cf83c8a2/scripts/setup-centos8.sh#L69C16-L69C100

Would it please be possible to switch to https://sourceforge.net/projects/boost/files/boost/1.72.0/boost_1_72_0.tar.gz?

### System information

N/A

### CMake log

```bash
N/A
```

**Comment by dcoliversun** [comment]
Test with https://archives.boost.io/release/1.72.0/source/boost_1_72_0.tar.gz successfully.
```plain
+ wget_and_untar https://archives.boost.io/release/1.72.0/source/boost_1_72_0.tar.gz boost
+ local URL=https://archives.boost.io/release/1.72.0/source/boost_1_72_0.tar.gz
+ local DIR=boost
+ mkdir -p boost
+ wget -q --max-redirect 3 -O - https://archives.boost.io/release/1.72.0/source/boost_1_72_0.tar.gz
+ tar -xz -C boost --strip-components=1
```

**Comment by czentgr** [comment]
The source was updated to get the Boost source from github aligning with the bundled source.
