### ISSUE TITLE
AggregationTest.reclaimFromAggregation is flaky

### ISSUE THREAD

**Issue by xiaoxmeng** [facebookincubator/velox#8252]
### Bug description

[       OK ] AggregationTest.maxSpillBytes (1912 ms)
[ RUN      ] AggregationTest.reclaimFromAggregation
../../velox/exec/tests/AggregationTest.cpp:3327: Failure
Expected: (stats[0].operatorStats[1].spilledBytes) > (0), actual: 0 vs 0

99% tests passed, 1 tests failed out of 298

This might be due to the recent test refactor

### System information

The failed test log: https://app.circleci.com/pipelines/github/facebookincubator/velox/41795/workflows/72b1aedd-0a4a-4cfc-9ce5-62da343bf84d/jobs/288028

**Comment by xiaoxmeng** [comment]
cc @mbasmanova @duanmeng

**Comment by mbasmanova** [comment]
CC: @rui-mo
