### ISSUE TITLE
Failure (n > 0) in HashAggregation when ignoreNullKeys=true and all input rows have null keys

### ISSUE THREAD

**Issue by shiyu-bytedance** [facebookincubator/velox#8320]
### Bug description

Consider this table:
c0, c1
null, 1

And this query WITH ignoreNullKeys = true:
select c0, sum(c1) group by c0

Expected result:
0 result rows.

Actual result:
HashAggregation crash

Analysis and commentary:

Subtly, the ignoreNullKeys option effectively turns HashAggregation operator into a two-in-1 (Filter + Agg).
Namely, this query `select c0, sum(c1) group by c0` when ignoreNullKeys = true is semantically equivalent to:
`select c0, sum(c1) group by c0 where c0 is not null`. A.k.a a filter + agg.

When this edge case occurs, after `deselectRowsWithNulls`, there's no rows to aggregate. And thus, HashAggregation's AddInput should simply return. Instead, it continues to proceed, triggering runtime asserts.

Recommended fix:

Gracefully return as soon as we realize there are no rows to agg in current batch. *Gracefully* being keyword here because we may need to "unwind partial states", such as aggregation statistics before returning. Or at least move the return logic to very early on of HashAgg->AddInput.

cc @mbasmanova @oerling 

### System information

n/a

### Relevant logs

```bash
Testing started at 7:04 PM ...
unknown file: Failure
C++ exception with description "Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: (0 vs. 0)
Retriable: False
Expression: n > 0
Function: incrementProbes
File: /Users/shiyu/repos/velox/velox/./velox/exec/HashTable.h
Line: 793
Stack trace:
# 0  
E20240109 19:04:53.955655 5960668 Exceptions.h:69] Line: /Users/shiyu/repos/velox/velox/./velox/exec/HashTable.h:793, Function:incrementProbes, Expression: n > 0 (0 vs. 0), Source: RUNTIME, ErrorCode: INVALID_STATE
# 1
```

**Comment by mbasmanova** [comment]
@shiyu-bytedance Hi Shiyu, thank you for reporting this crash. Let's fix it, but I'd like to clarify that ignoreNullKeys option should not be set freely. The query planner must ensure it is safe to ignore nulls. This is the case for example, if aggregation is followed by join on the group-by key. However, this is not valid to set this option for the queries you provided in the example.

Would you like to open a PR to fix the crash?

**Comment by ViggoC** [comment]
> The query planner must ensure it is safe to ignore nulls. This is the case for example, if aggregation is followed by join on the group-by key.

Could you explain why it's not valid to set ignoreNullKeys for aggregation followed by join? What's the different between a ingoring null keys aggregation with all null input and a normal aggregation with empty input in this example.

**Comment by ViggoC** [comment]
@mbasmanova Sorry, I misunderstood earlier. Your meaning is that an aggregation followed by a join is valid to set ignore null keys, but it is not valid for a standalone aggregation.

**Comment by ViggoC** [comment]
@mbasmanova I reported this  issue to Shiyu. It seems that our usage does not align with your design intentions. We are trying to integrate Velox into Elasticsearch, and the native aggregation operator in ES filters out null keys(Inconsistent with SQL semantics). I accidentally discovered that Velox's hash aggregate operator has this configuration and used it.

**Comment by mbasmanova** [comment]
@ViggoC Thank you for clarifying the use case. 

> We are trying to integrate Velox into Elasticsearch, and the native aggregation operator in ES filters out null keys(Inconsistent with SQL semantics). 

I see. In this case it is valid to set ignoreNullKeys=true. We should fix the crash. Would you like to help with the fix?

**Comment by ViggoC** [comment]
@shiyu-bytedance and I will try to fix it. Shiyu is more familiar with this part of the code, so he will take the lead. I am willing to provide assistance if he needs it.

**Comment by shiyu-bytedance** [comment]
> @shiyu-bytedance Hi Shiyu, thank you for reporting this crash. Let's fix it, but I'd like to clarify that ignoreNullKeys option should not be set freely. The query planner must ensure it is safe to ignore nulls. This is the case for example, if aggregation is followed by join on the group-by key. However, this is not valid to set this option for the queries you provided in the example.
> 
> Would you like to open a PR to fix the crash?

@mbasmanova I understand that the query I provided is not valid for ignoreNullKeys because it's Agg (not followed by Join). However, I do think (and would like to confirm we are on the same page) that this is still a legitimate bug.

Even if Agg is followed by Join and ignoreNullKeys is set to true, it's still possible that, by chance, some splits may have all their rows filtered out (due to null keys) and trigger this bug.

**Comment by mbasmanova** [comment]
@shiyu-bytedance Yes, crash is never an expected outcome. This is a bug that we'd need to fix.

**Comment by shiyu-bytedance** [comment]
> @shiyu-bytedance Yes, crash is never an expected outcome. This is a bug that we'd need to fix.

@mbasmanova Actually, just to be specific, this does not *crash* like deref null ptr, this case triggers an VELOX_CHECK. VELOX_CHECK's are littered through out Velox to ensure that we do not run into unexpected situations, such as those that arise from "bad" planning/optimizer.

I think to be very precise about qualifying this bug, this can be described as a case where even when planner/optimzer behaves correct, we can still "crash" by triggering the VELOX_CHECK in question.

So this bug is really:
1) An overly conservative VELOX_CHECK that needs to be relaxed to allow this edge case.
2) All subsequent works required to handle the relaxed assumption (i.e. don't crash).

All this is to say, crash, by way of triggering VELOX_CHECK, can be an expected outcome if the trigger is an impossible/invalid situation from bad planner/optimizer. But that's not this case.

**Comment by shiyu-bytedance** [comment]
> @shiyu-bytedance Thank you for clarifying. Indeed, let's make sure to use the term 'crash' only for crashes and otherwise say 'fail'. I updated the PR title. Would be nice to update PR description as well.

aligned

**Comment by yuedai** [comment]
I am new to Velox codebase and I am looking at this issue. I am curious that if Velox allows nullable keys? I try to crack a fix and I find there is assumption in many test case that key should not be nullable. Please correct me if I am wrong. @mbasmanova @shiyu-bytedance

**Comment by mbasmanova** [comment]
Unit test repro:

```
TEST_F(AggregationTest, xxx) {
  auto data = makeRowVector({
      makeAllNullFlatVector<int32_t>(3),
      makeFlatVector<int32_t>({1, 2, 3}),
  });

  auto plan = PlanBuilder()
                  .values({data})
                  .aggregation(
                      {"c0"},
                      {"sum(c1)"},
                      {},
                      core::AggregationNode::Step::kPartial,
                      true /*ignoreNullKeys*/
                      )
                  .planNode();

  AssertQueryBuilder(plan).assertEmptyResults();
}
```
