### ISSUE TITLE
Make SIMD support optional in favor of portability

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#833]
The current Velox implementation uses SIMD instructions specific to Intel. We must make this use optional in favor of portability to other hardware such as the Mac M1 processors.

**Comment by mbasmanova** [comment]
CC: @kgpai @wenleix @pedroerp @laithsakka @kevinwilfong

**Comment by yingsu00** [comment]
SIMD code should be guarded by hardware and OS check. Is this not the case?

**Comment by pedroerp** [comment]
+1. We had some chats with folks from TU Dresden who are developing a library to abstract SIMD usage called TVL. Pretty promising; this is the context:

> http://cidrdb.org/cidr2020/papers/p28-ungethuem-cidr20.pdf

**Comment by mbasmanova** [comment]
Here is the repo for TLV: https://github.com/MorphStore/TVLLib#welcome-to-the-template-vector-library-tvl

**Comment by kgpai** [comment]
This can be closed, as simd is portable via xsimd.
