### ISSUE TITLE
Support multi-byte escape char in LIKE

### ISSUE THREAD

**Issue by xumingming** [facebookincubator/velox#8363]
### Description

Presto support multi-byte character as escape char:

```
presto:sf1> select 'h_llo' LIKE 'h你_llo' ESCAPE '你';
 _col0
-------
 true
(1 row)
```

While Velox assume escape char is single byte char: https://github.com/facebookincubator/velox/blob/373eda093ae37571e12a91e5dbab627844fa0c27/velox/functions/lib/Re2Functions.cpp#L125-L131

**Comment by xumingming** [comment]
CC @mbasmanova

**Comment by mbasmanova** [comment]
> While Velox assume escape char is single byte char:

Let's makes to throw a clear error message is escape char is multi-byte and not just produce wrong results silently.

**Comment by mbasmanova** [comment]
CC: @gggrace14 @kagamiori @amitkdutta

**Comment by mbasmanova** [comment]
@xumingming Makes sense to me. It would be nice to clarify in the docs that escape char must be an ASCII character.

https://facebookincubator.github.io/velox/functions/presto/regexp.html

**Comment by xumingming** [comment]
Closing this as https://github.com/facebookincubator/velox/pull/9062 clarified doc for LIKE.
