### ISSUE TITLE
Add support for Parquet writer

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#837]
The scope of this issue is to add support to write to Parquet format

**Comment by mbasmanova** [comment]
It turns out that DuckDB has Parquet writer (in addition to reader). We could use that.

An example of using Parquet writer is: `COPY (SELECT * FROM tbl) TO 'result-snappy.parquet' (FORMAT 'parquet')`

**Comment by majetideepak** [comment]
This is now supported via Apache Arrow.
