### ISSUE TITLE
HashProbe canReplaceWithDynamicFilter_ logic produce wrong results

### ISSUE THREAD

**Issue by Yohahaha** [facebookincubator/velox#8388]
### Bug description

Wrong output results' plan
```
-- 19 HashJoin[LEFT SEMI (FILTER) n13_9=n18_5] -> n13_6:INTEGER, n13_7:INTEGER, n13_8:INTEGER, n13_9:BIGINT, n13_10:DECIMAL(7, 2), n13_11:DECIMAL(7, 2)
   Output: 14 rows
   HashBuild: Input: 456662 rows, Output: 0 rows
      distinctKey0                 sum: 2013, count: 1, min: 2013, max: 2013
      hashtable.capacity           sum: 599678, count: 1, min: 599678, max: 599678
      hashtable.numDistinct        sum: 456662, count: 1, min: 456662, max: 456662
      hashtable.numRehashes        sum: 1, count: 1, min: 1, max: 1
      rangeKey0                    sum: 599678, count: 1, min: 599678, max: 599678
   HashProbe: Input: 14 rows, Output: 14 rows
      dynamicFiltersProduced           sum: 1, count: 1, min: 1, max: 1
      replacedWithDynamicFilterRows    sum: 14, count: 1, min: 14, max: 14
   -- 13 Project[expressions: (n13_6:INTEGER, "n0_0"), (n13_7:INTEGER, "n0_1"), (n13_8:INTEGER, "n0_2"), (n13_9:BIGINT, "n0_3"), (n13_10:DECIMAL(7, 2), "n0_4"), (n13_11:DECIMAL(7, 2), "n0_5")] -> n13_6:INTEGER, n13_7:INTEGER, n13_8:INTEGER, n13_9:BIGINT, n13_10:DECIMAL(7, 2), n13_11:DECIMAL(7, 2)
      Output: 14 rows
   -- 18 Project[expressions: (n18_5:BIGINT, "n17_5")] -> n18_5:BIGINT
      Output: 456662 rows
```

After force set `canReplaceWithDynamicFilter_=false`, output is correct.
Correct output results' plan
```
-- 19 HashJoin[LEFT SEMI (FILTER) n13_9=n18_5] -> n13_6:INTEGER, n13_7:INTEGER, n13_8:INTEGER, n13_9:BIGINT, n13_10:DECIMAL(7, 2), n13_11:DECIMAL(7, 2)
   Output: 11 rows
   HashBuild: Input: 456662 rows, Output: 0 rows
      distinctKey0                 sum: 2013, count: 1, min: 2013, max: 2013
      hashtable.capacity           sum: 599678, count: 1, min: 599678, max: 599678
      hashtable.numDistinct        sum: 456662, count: 1, min: 456662, max: 456662
      hashtable.numRehashes        sum: 1, count: 1, min: 1, max: 1
      rangeKey0                    sum: 599678, count: 1, min: 599678, max: 599678
   HashProbe: Input: 14 rows, Output: 11 rows
      dynamicFiltersProduced       sum: 1, count: 1, min: 1, max: 1
   -- 13 Project[expressions: (n13_6:INTEGER, "n0_0"), (n13_7:INTEGER, "n0_1"), (n13_8:INTEGER, "n0_2"), (n13_9:BIGINT, "n0_3"), (n13_10:DECIMAL(7, 2), "n0_4"), (n13_11:DECIMAL(7, 2), "n0_5")] -> n13_6:INTEGER, n13_7:INTEGER, n13_8:INTEGER, n13_9:BIGINT, n13_10:DECIMAL(7, 2), n13_11:DECIMAL(7, 2)
      Output: 14 rows
   -- 18 Project[expressions: (n18_5:BIGINT, "n17_5")] -> n18_5:BIGINT
      Output: 456662 rows
```

Join equal condition may filter rows when `canReplaceWithDynamicFilter_` is true.

cc @mbasmanova 

### System information

n/a

**Comment by mbasmanova** [comment]
@Yohahaha Would you like to propose a fix?

Is this similar to https://github.com/facebookincubator/velox/pull/8313 ?

**Comment by Yohahaha** [comment]
@mbasmanova 
It's my mistake, in our internal operator, the operator will stop apply dynamic filter if these filters has low selectivity. Seems join node need its probe child must filter out all unneeded rows according to pushed dynamic filters.

**Comment by mbasmanova** [comment]
@Yohahaha Thank you for the update. Happy to hear the issue is resolved. Curious, what is the "internal operator" here?

**Comment by Yohahaha** [comment]
> what is the "internal operator" here?

It's a source operator implemented and used in our internal usage.

**Comment by mbasmanova** [comment]
@Yohahaha Curious, what type of source it reads the data from.

**Comment by Yohahaha** [comment]
> @Yohahaha Curious, what type of source it reads the data from.

Like shuffle read, may I ask does prestissimo's shuffle read support dynamic filter?

**Comment by mbasmanova** [comment]
@Yohahaha Shuffle in Prestissimo doesn't support filter pushdown. We have been thinking of adding that for a long time, just never got time to work on it. It is cool to know that you are doing something like that. Any insights / advice you can share based on your experience?

**Comment by Yohahaha** [comment]
> @Yohahaha Shuffle in Prestissimo doesn't support filter pushdown. We have been thinking of adding that for a long time, just never got time to work on it. It is cool to know that you are doing something like that. Any insights / advice you can share based on your experience?

Pushdown dynamic filter to shuffle read can gain much benefits when pipeline contains multi join nodes, if filter's selectivity is good, intermediate rows can be decreased significantly, and we always suppose less probe rows is better.

However, the apply order of dynamic filter and its selectivity may affect the effectiveness. So, I encounter above issue when early stop filtering when selectivity is low.

**Comment by mbasmanova** [comment]
@Yohahaha Got it. Thank you for sharing. This matches our understanding as well.
