### ISSUE TITLE
Add word_stem Presto function

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#8487]
### Description

Presto docs: https://prestodb.io/docs/0.278/functions/string.html

```
word_stem(word) → varchar
Returns the stem of word in the English language.

word_stem(word, lang) → varchar
Returns the stem of word in the lang language.
```

Presto's implementation: https://github.com/prestodb/presto/pull/9912

A possible C++ library that can be used in Velox: https://github.com/Blake-Madden/OleanderStemmingLibrary

CC: @aditi-pandit @majetideepak

**Comment by aditi-pandit** [comment]
@yhwang

**Comment by yhwang** [comment]
Slowly set up my dev environment and check the possible C++ library. The C++ library doesn't support all the languages supported on the Java side. I am checking https://snowballstem.org/ which should be the equivalent of the Java implementation (or I should say Java is one of its implementations). It does provide a C version which means we need to build it from the source and use it in Velox. any suggestion/comment?

**Comment by aditi-pandit** [comment]
@mbasmanova ⬆️
