### ISSUE TITLE
MacOS build failing with fmt 8.0.1

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#8537]
### Problem description

In file included from /oss/velox/velox/common/memory/tests/MemoryManagerTest.cpp:17:
In file included from /oss/prestissimo_velox_deps/include/fmt/format.h:44:
/oss/prestissimo_velox_deps/include/fmt/core.h:1168:20: error: assigning to 'const void *' from incompatible type '__bit_iterator<vector<bool, allocator<bool>>, true>'
    custom.value = &val;
                   ^~~~
/oss/prestissimo_velox_deps/include/fmt/core.h:1571:10: note: in instantiation of function template specialization 'fmt::v8::detail::value<fmt::basic_format_context<fmt::appender, char>>::value<std::__bit_const_reference<std::vector<bool>>>' requested here
  return {arg};
         ^
/oss/prestissimo_velox_deps/include/fmt/core.h:1692:23: note: in instantiation of function template specialization 'fmt::v8::detail::make_arg<true, fmt::basic_format_context<fmt::appender, char>, fmt::v8::detail::type::custom_type, std::__bit_const_reference<std::vector<bool>>, 0>' requested here
        data_{detail::make_arg<
                      ^

### System information

Velox System Info v0.0.2
Commit: 6d2f0d40cd2b33bd7df95fd98d611c4099a557fc
CMake Version: 3.26.4
System: Darwin-22.6.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 15.0.0.15000040
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 15.0.0.15000040
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.26.4;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by mbasmanova** [comment]
I'm seeing this too. CC: @kgpai @assignUser

**Comment by majetideepak** [comment]
I spoke with @assignUser. The recommendation is to upgrade to fmt `10.1.1`.
This will require reinstalling dependencies that use fmt. This includes folly.
```
./scripts/setup-macos.sh install_fmt
./scripts/setup-macos.sh install_folly
```

**Comment by kgpai** [comment]
The other option is to build using fmt_SOURCE=BUNDLED folly_SOURCE=BUNDLED .

**Comment by assignUser** [comment]
>  to upgrade to fmt 10.1.1

or 8.1.0 in case you can't update for other libraries (but in that case Krishnas option is probably easier anyway)

**Comment by majetideepak** [comment]
This is now resolved.
