### ISSUE TITLE
Decimal divide() get wrong results when short decimal / long decimal

### ISSUE THREAD

**Issue by xiaodouchen** [facebookincubator/velox#8598]
### Bug description

For the case `CAST('0.01' AS DECIMAL(17,4)) / CAST('5' AS DECIMAL(21,19))`, in presto, the result is `CAST('0.002' AS DECIMAL(21,19))`. However, in velox, the result is  `CAST('0.000' AS DECIMAL(21,19))`.

### System information

Velox System Info v0.0.2
Commit: a94ed0e1da9754dba19cc588a043ec3e128dbcfa
CMake Version: 3.28.1
System: Darwin-23.1.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 15.0.0.15000040
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 15.0.0.15000040
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX14.0.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.28.1;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by mbasmanova** [comment]
CC: @kagamiori @kgpai @gggrace14
