### ISSUE TITLE
from_base64 Presto function isn't decoding the input when the input isn't padded.

### ISSUE THREAD

**Issue by Joe-Abraham** [facebookincubator/velox#8646]
### Bug description

Added these test case without padding at `velox/functions/prestosql/tests/BinaryFunctionsTest.cpp` in `TEST_F(BinaryFunctionsTest, fromBase64) `
```  // Check encoded strings without padding
  EXPECT_EQ("a", fromBase64("YQ"));
  EXPECT_EQ("ab", fromBase64("YWI"));
  EXPECT_EQ("abcd", fromBase64("YWJjZA"));
```

Got the below error when the above test case ran.

```
[ RUN      ] BinaryFunctionsTest.fromBase64
unknown file: Failure
C++ exception with description "Exception: VeloxUserError
Error Source: USER
Error Code: INVALID_ARGUMENT
Reason: Base64::decode() - invalid input string: string length is not multiple of 4.
Retriable: False
Context: from_base64(c0)
Top-Level Context: Same as context.
Function: call
File: /Users/joe/Developer/velox/./velox/functions/prestosql/BinaryFunctions.h
Line: 297
Stack trace:
Stack trace has been disabled. Use --velox_exception_user_stacktrace_enabled=true to enable it.
" thrown in the test body.
[  FAILED  ] BinaryFunctionsTest.fromBase64 (8 ms)
```

### System information

Velox System Info v0.0.2
Commit: 3004e3494b45f1789ff5a435c713132989cc4f90
CMake Version: 3.27.8
System: Darwin-23.3.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 15.0.0.15000100
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 15.0.0.15000100
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.27.8;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by Joe-Abraham** [comment]
@kgpai wrote a quick test in Presto Java and tested the code below, which is passing successfully. I couldn't find any existing UTs to run.

```
public class TestBase64
{
    @Test
    public void testDecodeBase64()
    {
        assertEquals(new String(Base64.getDecoder().decode("YQ"), UTF_8), "a");
        assertEquals(new String(Base64.getDecoder().decode("YWI"), UTF_8), "ab");
        assertEquals(new String(Base64.getDecoder().decode("YWJjZA"), UTF_8), "abcd");
        assertEquals(new String(Base64.getDecoder().decode("YQ=="), UTF_8), "a");
        assertEquals(new String(Base64.getDecoder().decode("YWI="), UTF_8), "ab");
    }
}
```

**Comment by mbasmanova** [comment]
@Joe-Abraham Would you like to send a PR to fix this?
