### ISSUE TITLE
ParquetReader passes wrong columnIds array to DuckDB::ParquetReader

### ISSUE THREAD

**Issue by yingsu00** [facebookincubator/velox#865]
The following query fails with index out of bound error:
```
select count(*) from lineitem where partkey <20000000;
```
Call stack
```
std::__1::unique_ptr<duckdb::ColumnReader, std::__1::default_delete<duckdb::ColumnReader> >::get() const memory:2318
duckdb::StructColumnReader::GetChildReader(unsigned long long) parquet-amalgamation.cpp:13520
duckdb::ParquetReader::ScanInternal(duckdb::ParquetReaderScanState&, duckdb::DataChunk&) parquet-amalgamation.cpp:16349
duckdb::ParquetReader::Scan(duckdb::ParquetReaderScanState&, duckdb::DataChunk&) parquet-amalgamation.cpp:16283
facebook::velox::parquet::ParquetRowReader::next(unsigned long long, std::__1::shared_ptr<facebook::velox::BaseVector>&) ParquetReader.cpp:150
facebook::velox::connector::hive::HiveDataSource::next(unsigned long long) HiveConnector.cpp:495
facebook::velox::exec::TableScan::getOutput() TableScan.cpp:95
facebook::velox::exec::Driver::runInternal(std::__1::shared_ptr<facebook::velox::exec::Driver>&, std::__1::shared_ptr<facebook::velox::exec::BlockingState>*) Driver.cpp:375
facebook::velox::exec::Driver::run(std::__1::shared_ptr<facebook::velox::exec::Driver>) Driver.cpp:459
facebook::velox::exec::Driver::enqueue(std::__1::shared_ptr<facebook::velox::exec::Driver>)::$_0::operator()() const Driver.cpp:195
void folly::detail::function::FunctionTraits<void ()>::callSmall<facebook::velox::exec::Driver::enqueue(std::__1::shared_ptr<facebook::velox::exec::Driver>)::$_0>(folly::detail::function::Data&) Function.h:371
folly::detail::function::FunctionTraits<void ()>::operator()() Function.h:400
folly::ThreadPoolExecutor::runTask(std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread> const&, folly::ThreadPoolExecutor::Task&&) Exception.h:279
folly::ThreadPoolExecutor::runTask(std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread> const&, folly::ThreadPoolExecutor::Task&&) Executor.h:235
folly::ThreadPoolExecutor::runTask(std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread> const&, folly::ThreadPoolExecutor::Task&&) ThreadPoolExecutor.cpp:116
folly::CPUThreadPoolExecutor::threadRun(std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>) CPUThreadPoolExecutor.cpp:302
decltype(*(std::__1::forward<folly::ThreadPoolExecutor*&>(fp0)).*fp(std::__1::forward<std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>&>(fp1))) std::__1::__invoke<void (folly::ThreadPoolExecutor::*&)(std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>), folly::ThreadPoolExecutor*&, std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>&, void>(void (folly::ThreadPoolExecutor::*&)(std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>), folly::ThreadPoolExecutor*&, std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>&) type_traits:3688
std::__1::__bind_return<void (folly::ThreadPoolExecutor::*)(std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>), std::__1::tuple<folly::ThreadPoolExecutor*, std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread> >, std::__1::tuple<>, __is_valid_bind_return<void (folly::ThreadPoolExecutor::*)(std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>), std::__1::tuple<folly::ThreadPoolExecutor*, std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread> >, std::__1::tuple<> >::value>::type std::__1::__apply_functor<void (folly::ThreadPoolExecutor::*)(std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>), std::__1::tuple<folly::ThreadPoolExecutor*, std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread> >, 0ul, 1ul, std::__1::tuple<> >(void (folly::ThreadPoolExecutor::*&)(std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>), std::__1::tuple<folly::ThreadPoolExecutor*, std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread> >&, std::__1::__tuple_indices<0ul, 1ul>, std::__1::tuple<>&&) functional:2852
std::__1::__bind_return<void (folly::ThreadPoolExecutor::*)(std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>), std::__1::tuple<folly::ThreadPoolExecutor*, std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread> >, std::__1::tuple<>, __is_valid_bind_return<void (folly::ThreadPoolExecutor::*)(std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>), std::__1::tuple<folly::ThreadPoolExecutor*, std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread> >, std::__1::tuple<> >::value>::type std::__1::__bind<void (folly::ThreadPoolExecutor::*)(std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>), folly::ThreadPoolExecutor*, std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>&>::operator()<>() functional:2885
void folly::detail::function::FunctionTraits<void ()>::callSmall<std::__1::__bind<void (folly::ThreadPoolExecutor::*)(std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>), folly::ThreadPoolExecutor*, std::__1::shared_ptr<folly::ThreadPoolExecutor::Thread>&> >(folly::detail::function::Data&) Function.h:371
folly::detail::function::FunctionTraits<void ()>::operator()() Function.h:400
folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()::operator()() NamedThreadFactory.h:40
decltype(std::__1::forward<folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()>(fp)()) std::__1::__invoke<folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()>(folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()&&) type_traits:3747
void std::__1::__thread_execute<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()>(std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()>&, std::__1::__tuple_indices<>) thread:280
void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, folly::NamedThreadFactory::newThread(folly::Function<void ()>&&)::'lambda'()> >(void*) thread:291
_pthread_start 0x00007fff205a28fc
thread_start 0x00007fff2059e443
```

This is because DuckDB creates readers for all table columns even they are not used in the query and I created issue https://github.com/duckdb/duckdb/issues/2898
while ParquetRowReader only include the columns with filters:

```
ParquetRowReader::ParquetRowReader(
    std::shared_ptr<::duckdb::ParquetReader> reader,
    const dwio::common::RowReaderOptions& options,
    memory::MemoryPool& pool)
    : reader_(std::move(reader)), pool_(pool) {
...
  std::vector<::duckdb::column_t> columnIds;
  columnIds.reserve(rowType_->size());
  duckdbRowType_.reserve(rowType_->size());
  for (auto& node : filter) {
    columnIds.push_back(node.column);
    duckdbRowType_.push_back(reader_->return_types[node.column]);
  }
```
In DuckDB `ParquetReader::ScanInternal()`, it gets the reader 
```
auto file_col_idx = state.column_ids[filter_col.first];
```
But filter_col.first = 1 (partkey has hive column index 1) and column_ids array only has 1 element. Reading index 1 caused wrong `file_col_idx`.

Actually it's bad practice to pass in the state and columnIds to DuckDB ParquetReader from Velox. The state should be DuckDB ParquetReader internal state and should not be passed from outside. It also needs to set the column_ids correctly within DuckDB. Note that DuckDB reads the file metadata already during initialization, and the schema has all columns information and can be used to construct column_ids array. 

Additionally the column_ids array doesn't seem necessary, if both column_id and filter_col.first are hiveColumnIndexes. Then the above line should be 
```
auto file_col_idx = filter_col.first;
```

Furthermore, DuckDB should not create so many readers, one for each table column. It should only create readers for the columns needed.
 
I think DuckDB needs big refactoring to manage its states correctly before we can work on any additional optimizations.

**Comment by yingsu00** [comment]
cc @mbasmanova @majetideepak @aditi-pandit @frankobe
Before this is fixed, almost all queries on Parquet would return wrong results or just fail.

**Comment by mbasmanova** [comment]
@yingsu00 Thank you file filing an issue in DuckDB project. I saw a reply from Hannes where he acknowledged the problem and stated that he'd be happy to review the fix. Would you like to work on that?

**Comment by yingsu00** [comment]
@mbasmanova DuckDB parquet reader has much more problems than this. We need to come up with a plan together. I'm preparing a document/issue, stay tuned.

**Comment by mbasmanova** [comment]
> I'm preparing a document/issue, stay tuned.

@yingsu00 Do you have a sense of when you might have something to share?

**Comment by mbasmanova** [comment]
CC: @Mytherin @hannesmuehleisen

**Comment by yingsu00** [comment]
> Do you have a sense of when you might have something to share?
@mbasmanova Should be by next Thursday.

**Comment by hannesmuehleisen** [comment]
I’d be curious to hear what those “much more” problems are

**Comment by yingsu00** [comment]
> I’d be curious to hear what those “much more” problems are

@hannesmuehleisen Maybe I should rephrase the word "problem" to "unsupported features" and "future improvements", for example, Velox need to control and account for the memory Parquet reader uses. As another example, only RLE_DICTIONARY, PLAIN_DICTIONARY and PLAIN encodings are supported and we need to expand the coverage. Another example is to support rowgroup elimination based on rowgroup stats. Currently the Parquet reader is nearly 2x slower than Velox DWRF reader, even though the latter had to use expensive Varint encoding while Parquet doesn't. I'll describe more items in a Github issue. 

Also, the engineering cost for us to help improve DuckDB Parquet reader is quite high currently: we had to copy the DuckDB code, amalgamate them into huge files that slow down and freeze the IDE quite often, and it's very hard for us to test a DuckDB PR with Velox without porting and formatting the code again.  But we want to help and I'll be very happy to discuss options with you folks.

**Comment by hannesmuehleisen** [comment]
@yingsu00 Some comments (CC @mytherin):

- As far as I know, we had added memory allocation control to the Parquet reader for you guys, is that not sufficient
- Parquet has several specified but hardly used encodings, which ones do you need in particular?
- Row group elimination based on stats is supported, maybe its an integration issue from Velox?
- Re engineering cost, what did you need to change besides the amalgamation, I agree editing that directly is not nice

Happy to discuss these topics in more detail, too

**Comment by yingsu00** [comment]
cc @dborkar

**Comment by yingsu00** [comment]
@hannesmuehleisen I'm sorry I may have missed the memory allocator for Velox was already implemented, but there are other features that might help, eg caching and read ahead, pushdown aggregation and more. We may also want to optimize for the hardware our services are running on. The encoding we need at least includes DELTA_BINARY_PACKED. But anyways the basic need is we need a way to work on the code easier. Maybe we can discuss offline?

**Comment by hannesmuehleisen** [comment]
Sure, drop me a line hannes@duckdblabs.com

**Comment by majetideepak** [comment]
@hannesmuehleisen thanks for all the feedback. We will work with Ying and others to create a document with the missing pieces. I guess we can discuss further from there.

**Comment by mbasmanova** [comment]
@yingsu00 Here is a nice blog post about Parquet reader in DuckDB: https://duckdb.org/2021/06/25/querying-parquet.html

**Comment by mbasmanova** [comment]
> Row group elimination based on stats is supported, maybe its an integration issue from Velox?

Indeed, I see that being the case. There might be a bug in that logic though. I'm reading Parquet files for the 'lineitem' table created by Presto and these appear to have incomplete stats, e.g. min is present, but max is not. This generated a failure when pushing down `quantity < 24` filter.

`INTERNAL Error: Invalid PhysicalType for GetTypeIdSize`

Here is a repro: https://github.com/facebookincubator/velox/pull/881

**Comment by yingsu00** [comment]
> Sure, drop me a line [hannes@duckdblabs.com](mailto:hannes@duckdblabs.com)

@hannesmuehleisen Thank you for your email. I actually already pinged you on linkedin. We'll send you something next week.

**Comment by yingsu00** [comment]
@mbasmanova @hannesmuehleisen Per our internal discussions, we will contact DuckDB offline. I will hold off publishing the document as a Github issue now.
