### ISSUE TITLE
ExchangeQueue exists invalid promise and Exchange exists invalid future.

### ISSUE THREAD

**Issue by zbytekuwy** [facebookincubator/velox#8680]
### Bug description

When exchange get the list of serializedPages which is not up to 'maxBytes', exchangeQueue will push a promise and return future to notify exchange. But in this case, exchange operator is not blocked. The result of this case, the exchangeQueue will congest lots of promise which may be invalid.

The bug is from https://github.com/facebookincubator/velox/pull/7404

### System information

Velox System Info v0.0.2
Commit: 568a07fd1649cda18112acd28413576761160bdd
CMake Version: 3.25.1
System: Darwin-22.1.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 14.0.0.14000029
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 14.0.0.14000029
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX13.1.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.25.1;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by zbytekuwy** [comment]
@mbasmanova cc please

**Comment by mbasmanova** [comment]
@zbytekuwy Welcome to the community. Thank you for reporting an issue. 

I'm not sure I fully understand the problem though. Any chance you could elaborate a bit? How did you find this issue? Do you have a fix in mind?

Are you referring to ExchangeQueue::dequeueLocked creating a promise-future pair, but that future being ignored by the caller sometimes?
