### ISSUE TITLE
flattenVector() returned wrong stringview or size

### ISSUE THREAD

**Issue by FelixYBW** [facebookincubator/velox#8697]
### Bug description

flattenVector() should return an flatten vector as the same type. But we met two issues in a customer case. Code we used like this:

```
BaseVector::flattenVector(aStringViewLazyVector);
auto stringViewVectorPtr = StringViewLazyVector->asFlatVector<facebook::velox::StringView>();
VELOX_CHECK_NOT_NULL(stringViewVectorPtr, "column is nullptr");   // check failed
```
Or the check passed but one element of the stringView has 1G size but actually it's only a few bytes.

Currently our solution is to copy to a new rowvector like below.

```
for (auto& child : rowVector_->children()) {
    child->loadedVector();
}

velox::RowVectorPtr copy = std::dynamic_pointer_cast<velox::RowVector>(
      velox::BaseVector::create(rowVector_->type(), rowVector_->size(), rowVector_->pool()));
copy->copy(rowVector_.get(), 0, 0, rowVector_->size());
```

@mbasmanova Is there anything wrong of the usage? If it's not expected I will try to debug it.

### System information

Velox System Info v0.0.2
Commit: a94e60c70ce70cb644c88e5b1615d83491e98226
CMake Version: 3.16.3
System: Linux-5.4.0-1063-aws
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt
  
\nThe results will be copied to your clipboard if xclip is installed.

**Comment by mbasmanova** [comment]
@FelixYBW Binwei, this is probably a bug in BaseVector::flattenVector

```    case VectorEncoding::Simple::LAZY: {
      auto loadedVector =
          vector->asUnchecked<LazyVector>()->loadedVectorShared();
      BaseVector::flattenVector(loadedVector);
      return;
```

This branch doesn't modify 'vector' input parameter, just loads the LV. Hence, after flatten, 'vector' is still an instance of LazyVector, but contains a loaded FlatVector<StringView> inside. That would explain why check for null after asFlatVector fails.

Here is a simple repro:

```
TEST_F(VectorTest, xxx) {
  VectorPtr lv = makeLazyFlatVector<int32_t>(10, folly::identity);

  LOG(ERROR) << lv->toString();
  LOG(ERROR) << lv->as<LazyVector>()->isLoaded();

  BaseVector::flattenVector(lv);

  LOG(ERROR) << lv->toString();

  FAIL();
}
```

A fix might be:

```
    case VectorEncoding::Simple::LAZY: {
      vector = vector->asUnchecked<LazyVector>()->loadedVectorShared();
      BaseVector::flattenVector(vector);
      return;
    }
```

> Or the check passed but one element of the stringView has 1G size but actually it's only a few bytes.

This might be a different issue and it needs more debugging.

CC: @bikramSingh91

**Comment by FelixYBW** [comment]
@mbasmanova Sorry, I checked the code, we do have the the loadedVectorShared() before check, the check success in most cases but failed in several queries. 
Here is the code:
```
BaseVector::flattenVector(aStringViewLazyVector);
if (aStringViewLazyVector->isLazy()) {
  aStringViewLazyVector = aStringViewLazyVector->as<facebook::velox::LazyVector>()->loadedVectorShared();
  VELOX_DCHECK_NOT_NULL(aStringViewLazyVector);
}
auto stringViewVectorPtr = StringViewLazyVector->asFlatVector<facebook::velox::StringView>();
VELOX_CHECK_NOT_NULL(stringViewVectorPtr, "column is nullptr");   // check failed
```

Let me debug it then

**Comment by marin-ma** [comment]
@mbasmanova We found some of the failed case is when applying `BaseVector::flattenVector` on the output from `Limit`. According to below code piece, when `remainingLimit_ < input_->size()`, the size of the `output` RowVector will be smaller than its children. The size mismatch causes errors when attempting to access or manipulate the null and value buffers of the child vectors, as their sizes are expected to align with the parent vector. 

https://github.com/facebookincubator/velox/blob/11eab1a7396e5d6267fdf75fdd70497ea9150821/velox/exec/Limit.cpp#L92-L100

I'm not sure if somewhere else also produces such output RowVector. Because in `BaseVector::flattenVector`, the size mismatch is also ignored, we have to call `child->resize(parent->size())` after `BaseVector::flattenVector` as a workaround.

**Comment by mbasmanova** [comment]
> The size mismatch causes errors when attempting to access or manipulate the null and value buffers of the child vectors, as their sizes are expected to align with the parent vector.

@marin-ma I don't believe this is a requirement. Would you share some more details about the code that generates errors?

**Comment by marin-ma** [comment]
@mbasmanova In Gluten's native shuffle writer implementation, there's a conversion from the value and null buffers to Arrow Buffer: 

```
    for (auto& child : rowVector.children()) { // rowVector.size() == 100
      if (child->encoding() == facebook::velox::VectorEncoding::Simple::FLAT) {
        VELOX_DYNAMIC_SCALAR_TYPE_DISPATCH_ALL(
            collectFlatVectorBuffer, child->typeKind(), child.get(), buffers, partitionBufferPool_.get());
      } else {
        // ... Handle complex types.
      }
    }
```
`collectFlatVectorBuffer` implementation:

```
template <facebook::velox::TypeKind kind>
arrow::Status collectFlatVectorBuffer(
    facebook::velox::BaseVector* vector,
    std::vector<std::shared_ptr<arrow::Buffer>>& buffers,
    arrow::MemoryPool* pool) {
  using T = typename facebook::velox::TypeTraits<kind>::NativeType;
  auto flatVector = dynamic_cast<const facebook::velox::FlatVector<T>*>(vector);
  buffers.emplace_back();
  ARROW_ASSIGN_OR_RAISE(buffers.back(), toArrowBuffer(flatVector->nulls(), pool));
  buffers.emplace_back();
  ARROW_ASSIGN_OR_RAISE(buffers.back(), toArrowBuffer(flatVector->values(), pool));
  return arrow::Status::OK();
}

```
After the conversion, the arrow buffers will be serialized and written into files. If the `rowVector` is an output from `Limit` operator, the arrow buffers may have larger size than the parent `rowVector`, resulting in more data being written to disks.

**Comment by mbasmanova** [comment]
@marin-ma It sounds like a bug in Velox-to-Arrow conversion. CC: @pedroerp @kgpai

**Comment by FelixYBW** [comment]
It's not a bug of Velox-to-Arrow conversion. It's about how to get the vector size after flattenVector. In current code, we should always use the size of batch level row vector and ignore the size of child for each column. If it's by design, we needn't do anything, but adding a note here.

**Comment by FelixYBW** [comment]
Looks it's by design. When we use flattenVector, make sure to always get the vector size from top level rowvector and ignore the child size. Child size may be bigger than rowvector size.

**Comment by marin-ma** [comment]
@mbasmanova @laithsakka We reproduced this issue again, and found the root cause is that `flattenVector` doesn't modify the loaded vector in `LazyVector`. Here's my fix https://github.com/facebookincubator/velox/pull/9282

**Comment by FelixYBW** [comment]
> Looks it's by design. When we use flattenVector, make sure to always get the vector size from top level rowvector and ignore the child size. Child size may be bigger than rowvector size.

We noted a case that after ensureflatten, the child vector is an reference to vector of another rowvector with different size. So confirmed it's by design. The solution is to slice the child vector after flatten. Refer to https://github.com/apache/incubator-gluten/pull/5523
