### ISSUE TITLE
velox_exec_test MultiFragmentTest.partitionedOutputWithLargeInput fails unexpectedly 

### ISSUE THREAD

**Issue by codyschierbeck** [facebookincubator/velox#8703]
### Bug description

partitionedOutputWithLargeInput attempts to split an input vector when it reaches a task level memory limit of 1MB. In #8637 CI/CD, Linux Adapters failed this test when the input vector was only split twice instead of three times

```
/root/project/velox/exec/tests/MultiFragmentTest.cpp:588: Failure
Expected: (taskStats.at("0").inputVectors) > (2), actual: 2 vs 2
```

This can be found at https://app.circleci.com/pipelines/github/facebookincubator/velox/44024/workflows/b97bb212-6cae-48b0-8ec8-677c9f4fa844/jobs/307002 on line 80685 of Run Unit Tests. 

The most recent change to this test was 6 days ago when the https://github.com/facebookincubator/velox/commit/790d6bda3902b3dd65173333eb94c00bac361e58 attempted to reduce the runtime of this test by reducing the input vector to 3MB instead of the original 10MB.

I have been unable to reproduce this error locally. I will continue to investigate.

The CI build that failed was built in the following way:

```
make cmake BUILD_DIR=release BUILD_TYPE=Release && \
make build BUILD_DIR=release
make[1]: Entering directory '/root/project'
mkdir -p _build/release && \
cmake -B \
        "_build/release" \
        -DTREAT_WARNINGS_AS_ERRORS=1 -DENABLE_ALL_WARNINGS=1 -DVELOX_BUILD_MINIMAL="OFF" -DVELOX_BUILD_TESTING="ON" -DCMAKE_BUILD_TYPE=Release \
        -GNinja -DMAX_LINK_JOBS=8 -DMAX_HIGH_MEM_JOBS=8 -DVELOX_FORCE_COLORED_OUTPUT=ON \
        -DVELOX_ENABLE_BENCHMARKS=ON -DVELOX_ENABLE_ARROW=ON -DVELOX_ENABLE_PARQUET=ON -DVELOX_ENABLE_HDFS=ON -DVELOX_ENABLE_S3=ON -DVELOX_ENABLE_GCS=ON -DVELOX_ENABLE_ABFS=ON -DVELOX_ENABLE_SUBSTRAIT=ON -DVELOX_ENABLE_REMOTE_FUNCTIONS=ON
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
```

The last commit from velox main branch in this pull was 52ccd86a5f1438d6ac32f5e4d70ced9517807049.

I am building for Release locally to see if this may be why I am unable to reproduce.

@bikramSingh91 @mbasmanova 

### System information

Velox System Info v0.0.2
Commit: 7468a0f117a85369111ede9fa2325daabf24fdc3
CMake Version: 3.22.1
System: Linux-6.1.0-1028-oem
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 11.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by mbasmanova** [comment]
@bikramSingh91 Bikram, would you help take a look?

**Comment by codyschierbeck** [comment]
Building for release and running this test did not reproduce this failure.
