### ISSUE TITLE
Build Issue arising from fmt library

### ISSUE THREAD

**Issue by svm1** [facebookincubator/velox#8704]
### Problem description

Issue observed when building latest `main`, looks to stem from the `fmt` library - could it be related to the recent fmt version upgrade?

### System information

Velox System Info v0.0.2
Commit: 02a4f6c3ddd37f5656488d81517bb9042ee857f2
CMake Version: 3.27.7
System: Darwin-23.1.0
Arch: arm64
C++ Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
C++ Compiler Version: 15.0.0.15000040
C Compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
C Compiler Version: 15.0.0.15000040
CMake Prefix Path: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.27.7;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local
  

### CMake log

```bash
In file included from /Users/svm/presto/presto-native-execution/velox/velox/common/memory/tests/MockSharedArbitratorTest.cpp:19:
In file included from /usr/local/include/fmt/format.h:44:
/usr/local/include/fmt/core.h:1168:20: error: assigning to 'const void *' from incompatible type '__bit_iterator<vector<bool, allocator<bool>>, true>'
    custom.value = &val;
```

**Comment by kgpai** [comment]
Hmm, @svm1 Looks like you are running on an M1 , The m1 build for that sha did succeed : https://app.circleci.com/pipelines/github/facebookincubator/velox/44031/workflows/4521fd66-c537-4aa9-99a5-b1b8880aa243/jobs/307056 . I am building locally on my machine to validate this. 

I presume you did a make clean and rebuilt ? Also presuming you made sure you have the latest dependencies, and if not run setup-macos.sh.

**Comment by kgpai** [comment]
@svm1 I was able to build fine. Can you try out some of the suggestions above ? Thanks.

**Comment by svm1** [comment]
@kgpai Thanks - I ran make clean and rebuilt, but forgot to update dependencies with setup-macos.sh, my bad. Build succeeded, apologies for the false alarm.
