### ISSUE TITLE
Benchmark "like" operator

### ISSUE THREAD

**Issue by aditi-pandit** [facebookincubator/velox#872]
Velox LIKE operator was added in https://github.com/facebookincubator/velox/issues/208.

This was a quick first cut implementation using regex.

Multiple open ended questions about the performance came up:
i) Comparison with DuckDB implementation : https://github.com/duckdb/duckdb/blob/master/src/function/scalar/string/like.cpp
This implementation is supposed to be 2-4x faster than regex.
ii) Optimizations for starts-with, ends-with and contains special cases (Patterns like: foo%, %bar and %foo%)

Add micro-benchmarks for the like operator since its heavily used in TPC-H queries.

**Comment by aditi-pandit** [comment]
@pramodsatya

**Comment by aditi-pandit** [comment]
@pramodsatya tried some benchmarking of optimizations for starts-with, ends-with and contains special cases (Patterns like: foo%, %bar and %foo%).

We tried these expressions on tpc-h like usage (columns, data generated, and predicates from the queries) and have some good early results. https://docs.google.com/spreadsheets/d/1K6sByosNr2j2cj6U3AwJNgb1AqJPG5EKQhluvhuCf88/edit#gid=0

There will be PRs to follow up.

**Comment by pramodsatya** [comment]
Working on PRs #1763, #2453 for resolving the issue.

**Comment by aditi-pandit** [comment]
There are several optimizations added in LIKE operator now. So closing this.
