### ISSUE TITLE
Implement Presto aggregate function max_data_size_for_stats

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#874]
This is used by the `analyze` statement

**Comment by mbasmanova** [comment]
Here is documentation of the ANALYZE for reference: https://prestodb.io/docs/current/sql/analyze.html

**Comment by majetideepak** [comment]
@frankobe is this of interest to your team?

**Comment by frankobe** [comment]
This should be a good onboarding task. @shiyu-bytedance can you take this

**Comment by shiyu-bytedance** [comment]
@majetideepak @mbasmanova https://github.com/facebookincubator/velox/pull/1797
PTAL! Thank you!

**Comment by majetideepak** [comment]
Reopening a stale Issue.
