### ISSUE TITLE
Misaligned implementation between AlignedStlAllocator.allocate/deallocate for large allocations

### ISSUE THREAD

**Issue by xumingming** [facebookincubator/velox#8804]
### Bug description

I am reading the code of `AlignedStlAllocator`, and find there is a mismatch in the implementation of `allocate` and `deallocate`. In allocate, if the size we want to allocate is bigger than kMaxAlloc **and the pool is aligned** , it will allocate directly from the pool 

```c++
    if (n * sizeof(T) > HashStringAllocator::kMaxAlloc && poolAligned_) {
      return reinterpret_cast<T*>(allocator_->allocateFromPool(n * sizeof(T)));
    }
```

Otherwise it will do some calculation about the alignment delta, then allocate.

```c++
    // Allocate extra Alignment bytes for alignment and 4 bytes to store the
    // delta between unaligned and aligned pointers.
    auto size =
        checkedPlus<size_t>(Alignment + 4, checkedMultiply(n, sizeof(T)));
    auto ptr = reinterpret_cast<T*>(allocator_->allocate(size)->begin());

    // Align 'ptr + 4'.
    void* alignedPtr = (char*)ptr + 4;
    size -= 4;
    std::align(Alignment, n * sizeof(T), alignedPtr, size);

    // Write alignment delta just before the aligned pointer.
    int32_t delta = (char*)alignedPtr - (char*)ptr - 4;
    *reinterpret_cast<int32_t*>((char*)alignedPtr - 4) = delta;

    return reinterpret_cast<T*>(alignedPtr);
```

When deallocate, the condition in if is different:

```c++
    if (n * sizeof(T) > HashStringAllocator::kMaxAlloc) {
      return allocator_->freeToPool(p, n * sizeof(T));
    }
```

It does not check for `poolAligned_`, which might cause a memory block that is allocated with some delta be freed directly without considering the delta?

### System information

N/A

### Relevant logs

```bash
N/A
```

**Comment by Yuhta** [comment]
Thanks for the finding.  Can you help fix it?  In case allocation of larger than `kMaxAlloc`, we should always allocate from pool (fix the `allocate` side), and adjust the beginning address to conform to the alignment.

**Comment by xumingming** [comment]
@Yuhta sure, glad to fix it.

**Comment by xumingming** [comment]
@Yuhta My understanding of current AlignedStlAllocator implementation is:

* If the Memory Pool's alignment already satisfy our alignment requirement(`allocator_->pool()->alignment() >= Alignment`), we don't need to do another level of alignment. 
* Otherwise we need to do the alignment at the `AlignedStlAllocator` level.

So I propose the following changes(pseudo code):

```c++
  T* FOLLY_NONNULL allocate(std::size_t n) {
    if (n * sizeof(T) > HashStringAllocator::kMaxAlloc) {
      if (poolAligned_) {
        return reinterpret_cast<T*>(allocator_->allocateFromPool(n * sizeof(T)));
      } else {
        auto actualSize = <Do the alignment and calculate the actualSize to allocate>
        auto delta = <calculate the delta and store it>
        // Allocate the memory block with a Header
        auto header = reinterpret_cast<Header*>(allocateFromPool(actualSize));
        // Return the usable memory to user.
        return reinterpret_cast<T*>(header->begin() + delta + 4);
      }
    }

   // Rest of the code to handle small allocations.....
}

  void deallocate(T* FOLLY_NONNULL p, std::size_t n) noexcept {
    if (n * sizeof(T) > HashStringAllocator::kMaxAlloc) {
      if (poolAligned_) {
        return allocator_->freeToPool(p, n * sizeof(T));
      } else {
        auto delta = <fetch the delta from memory>
        // Deallocate the memory using the Header.
        allocator_->free(HashStringAllocator::headerOf((char*)p - 4 - delta));
    }

   // Rest of the code to handle small allocations.....
  }
```

How do you think?

**Comment by Yuhta** [comment]
@xumingming This looks good.  Maybe extract the delta calculation and header construction to a private method so that it can be reused in both direct allocation from pool and from hash string allocator.
