### ISSUE TITLE
Missing stack trace symbols on test failures

### ISSUE THREAD

**Issue by ZacBlanco** [facebookincubator/velox#8810]
### Bug description

I compiled velox code with:
```
make debug EXTRA_CMAKE_FLAGS="-DVELOX_ENABLE_PARQUET=ON -DVELOX_BUILD_TESTING=ON -DVELOX_DEPENDENCY_SOURCE=BUNDLED"
```

I added a test to `ParquetReaderTest.cpp` with:

```
TEST_F(ParquetReaderTest, expectedFailure) {
  VELOX_FAIL("no stack trace produced")
} 
```

I expect the test binary to fail the test and print the stack trace with symbols. Howver, the resulting stacktrace is missing symbols:

```
[ RUN      ] ParquetReaderTest.expectedFailure
E20240220 17:41:02.579433 4578125 Exceptions.h:69] Line: /Users/zacblanco/projects/velox/velox/dwio/parquet/tests/reader/ParquetReaderTest.cpp:803, Function:TestBody, Expression:  no stack trace produced, Source: RUNTIME, ErrorCode: INVALID_STATE
unknown file: Failure
C++ exception with description "Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: no stack trace produced
Retriable: False
Function: TestBody
File: /Users/zacblanco/projects/velox/velox/dwio/parquet/tests/reader/ParquetReaderTest.cpp
Line: 803
Stack trace:
# 0  
# 1  
# 2  
# 3  
# 4  
# 5  
# 6  
# 7  
# 8  
# 9  
# 10 
# 11 
# 12 
# 13 
# 14 
# 15 
# 16 
# 17 
# 18 
# 19 
```

### System information

Velox System Info v0.0.2
Commit: d55c48b76e5a7fbc96c3da78ec38ec82f44b5608
CMake Version: 3.28.3
System: Darwin-23.3.0
Arch: arm64
C++ Compiler: /Library/Developer/CommandLineTools/usr/bin/c++
C++ Compiler Version: 15.0.0.15000100
C Compiler: /Library/Developer/CommandLineTools/usr/bin/cc
C Compiler Version: 15.0.0.15000100
CMake Prefix Path: /Library/Developer/CommandLineTools/SDKs/MacOSX14.2.sdk/usr;/opt/homebrew;/usr/local;/usr;/;/opt/homebrew/Cellar/cmake/3.28.3;/usr/local;/usr/X11R6;/usr/pkg;/opt;/sw;/opt/local

**Comment by majetideepak** [comment]
I can reproduce this.

**Comment by majetideepak** [comment]
https://github.com/facebookincubator/velox/blob/3020196b001130a9027b09d6b3b95385b90bc2cb/velox/common/process/StackTrace.cpp#L19-L25
I see that there is no symbolized support on MacOS. That is why the symbols are missing. I also do not remember seeing bt symbols on MacOS ever. So this is not a regression.
