### ISSUE TITLE
Decimal aggregation calculation may cause OOM

### ISSUE THREAD

**Issue by lingbin** [facebookincubator/velox#8858]
### Bug description

In the TPCH-1TB test, if the `DECIMAL` type is used, Q18 takes up a lot of memory, causing OOM. However, if the decimal type is replaced with the `DOUBLE` type, it can be executed successfully. Moreover, it was also found that when using the decimal type, for other queries, even if they can be successfully executed, the memory required is many times that of using the double type.

The error reported in TPCH-1TB Q18 is when calculating `sum(DECIMAL)`, which contains 1.5 billion different groups.

### System information

n/a

**Comment by aditi-pandit** [comment]
Thanks @lingbin. This is an awesome find !

@karteekmurthys, @majetideepak
