### ISSUE TITLE
CI: macOS Build Failing after 3m

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#8907]
### Bug description

MacOS CI keeps failing on PRs:

https://github.com/facebookincubator/velox/actions/runs/8088153792/job/22101621642?pr=8906

```
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.12

To list all files that would be deleted:
  brew link --overwrite python@3.12 --dry-run
```

CC: @kgpai @spershin @majetideepak @assignUser @pedroerp 

### System information

n/a

**Comment by kgpai** [comment]
cc: @assignUser 
It seems aws-sam-cli is pulling these other dependencies which are causing the installation to fail : 
``` aws-sam-cli 1.109.0_1 -> 1.110.0, harfbuzz 8.3.0 -> 8.3.0_1, libpq 16.2 -> 16.2_1, node@20 20.11.1 -> 20.11.1_1, php 8.3.3 -> 8.3.3_1, python@3.12 3.12.2 -> 3.12.2_1, selenium-server 4.17.0 -> 4.18.1 `` .
