### ISSUE TITLE
Add support for reading partition key columns for ParquetReader

### ISSUE THREAD

**Issue by yingsu00** [facebookincubator/velox#891]
The DuckDB reader doesn't create readers for partition key columns since they are not in the Parquet file. This logic needs to be handled in Velox ParquetRowReader.

**Comment by yingsu00** [comment]
cc @majetideepak @aditi-pandit 

@mbasmanova Would it make sense to create a label "parquet" to help us track all parquet related issues?

**Comment by mbasmanova** [comment]
> Would it make sense to create a label "parquet" to help us track all parquet related issues?

That's a good idea. Created.
