### ISSUE TITLE
System crashes while build the velox

### ISSUE THREAD

**Issue by Sujanhid** [facebookincubator/velox#8997]
### Problem description

when I try to execute "make" command in velox root directory it was build perfectly fine until it utilize full main memory and after utilizing 16GB memory(RAM) and 16 swap memory the system crashed. 

Out of 2022 file it was perfectly build 1510 file within the 16 GB RAM and 16 GB swap memory.

suggest me way to fix it or else i did any mistake ??

command i have used:
git clone --recursive https://github.com/facebookincubator/velox.git
cd velox
./scripts/setup-ubuntu.sh 
make

### System information

Velox System Info v0.0.2
Commit: abb0df44d20326dca58691fb726432e84ee2d88f
CMake Version: 3.22.1
System: Linux-6.5.0-21-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 11.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by mbasmanova** [comment]
CC: @assignUser @majetideepak @kgpai

**Comment by kgpai** [comment]
Hi @Sujanhid , Set NUM_THREADS to 8 or something smaller so that you have enough memory to compile Velox.
`NUM_THREADS=8 make `
