### ISSUE TITLE
Parquet query fails on double type filters

### ISSUE THREAD

**Issue by yingsu00** [facebookincubator/velox#902]
Using velox/dwio/parquet/tests/examples/sample.parquet, the following query fails:
```
select a from tmp where b < 3.0;
```
Error message:

++ exception with description "Exception: VeloxUserError
Error Source: USER
Error Code: UNSUPPORTED
Reason: Unsupported column type for integer filter: DOUBLE
Retriable: False
Function: makeValue

The Velox filter in column b's ScanSpec is `kBigintRange`, while the DuckDB type is DOUBLE

**Comment by yingsu00** [comment]
cc @majetideepak @mbasmanova @aditi-pandit

**Comment by majetideepak** [comment]
@yingsu00 The filter should be created as below. That worked for me.

```
auto filters =
      common::test::singleSubfieldFilter("b", common::test::lessThanDouble(3.0));
```

**Comment by mbasmanova** [comment]
@yingsu00 Was suggestion from Deepak helpful? Is this issue resolved now?
