### ISSUE TITLE
Fails to create vector function with hard-coded scale

### ISSUE THREAD

**Issue by marin-ma** [facebookincubator/velox#9029]
### Bug description

Creating a vector function with decimal argument type which requires fixed scale throws exception.

Below example demonstrates the passed/failed function signatures
```
// Function signature 1 (passed)
exec::FunctionSignatureBuilder()
   .integerVariable("precision")
   .integerVariable("scale")
   .returnType("integer")
   .argumentType("decimal(precision, scale)")
   .build()

// Function signature 2 (failed)
exec::FunctionSignatureBuilder()
   .integerVariable("precision")
   .returnType("integer")
   .argumentType("decimal(precision, 6)")
   .build()

```

If the function is registered with Function signature 2, it throws exception `Scalar function signature is not supported`. Here's an example output
```
C++ exception with description "Exception: VeloxUserError
Error Source: USER
Error Code: INVALID_ARGUMENT
Reason: Scalar function signature is not supported: make_timestamp(INTEGER, INTEGER, INTEGER, INTEGER, INTEGER, DECIMAL(16, 6)). Supported signatures: (integer,integer,integer,integer,integer,decimal(precision,6)) -> timestamp, (integer,integer,integer,integer,integer,decimal(precision,6),varchar) -> timestamp.
Retriable: False
Function: resolveScalarFunctionType
File: /home/sparkuser/github/oap-project/velox/velox/parse/TypeResolver.cpp
Line: 99
Stack trace:
Stack trace has been disabled. Use --velox_exception_user_stacktrace_enabled=true to enable it.
" thrown in the test body.
```

### System information

Velox System Info v0.0.2
Commit: 960e419bf0342d9f84fe96a32a34f72812334550
CMake Version: 3.22.1
System: Linux-5.19.0-32-generic
Arch: x86_64
C++ Compiler: /bin/c++
C++ Compiler Version: 11.4.0
C Compiler: /bin/cc
C Compiler Version: 11.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by mbasmanova** [comment]
CC: @majetideepak
