### ISSUE TITLE
Add support for DECIMAL types to Simple Function API

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#9097]
### Description

It would be nice to allow implementing functions that operate on decimals using Simple Function API.

CC: @majetideepak

**Comment by mbasmanova** [comment]
A prototype: #9096

**Comment by mbasmanova** [comment]
CC: @rui-mo

**Comment by rui-mo** [comment]
cc: @marin-ma

**Comment by mbasmanova** [comment]
Fixed in #9096
