### ISSUE TITLE
Please update velox/docs/functions/presto/coverage.rst

### ISSUE THREAD

**Issue by InitialZJ** [facebookincubator/velox#9125]
### Description

Many features marked as unimplemented have actually been implemented.

**Comment by mbasmanova** [comment]
CC: @kgpai 

@InitialZJ Would you like to help update this doc? There are instructions at velox/functions/prestosql/coverage/README.md

**Comment by InitialZJ** [comment]
OK. I will update this doc.

**Comment by mbasmanova** [comment]
@InitialZJ Thank you.
