### ISSUE TITLE
ReaderFactory is not registered for format parquet

### ISSUE THREAD

**Issue by Sujanhid** [facebookincubator/velox#9168]
### Problem description

While i'm trying to run 
velox_tpch_benchmark --data_path=/home//tpch-kit/dbgen/1gb/

i got "ReaderFactory is not registered for format parquet" this error but i'm using .tbl format in my data folder 

my data folder structure will be like this:

  ├── customer
  │   └── customer.tbl
  ├── lineitem
  │   └── lineitem.tbl
  ├── nation
  │   └── nation.tbl
  ├── orders
  │   └── orders.tbl
  ├── part
  │   └── part.tbl
  ├── partsupp
  │   └── partsupp.tbl
  ├── region
  │   └── region.tbl
  └── supplier
      └── supplier.tbl

Also i used .parquet format file also, for that case also same error 
how to clear this error

my full error:
    

 E0320 11:45:30.360415 452645 Exceptions.h:69] Line: /home/velox/velox/velox/dwio/common/ReaderFactory.cpp:54, Function:getReaderFactory, Expression: it != readerFactories().end() ReaderFactory is not registered for format parquet, Source: RUNTIME, ErrorCode: INVALID_STATE
terminate called after throwing an instance of 'facebook::velox::VeloxRuntimeError'
  what():  Exception: VeloxRuntimeError
Error Source: RUNTIME
Error Code: INVALID_STATE
Reason: ReaderFactory is not registered for format parquet
Retriable: False
Expression: it != readerFactories().end()
Function: getReaderFactory
File: /home/velox/velox/velox/dwio/common/ReaderFactory.cpp
Line: 54
Stack trace:
0  _ZN8facebook5velox7process10StackTraceC1Ei
1  _ZN8facebook5velox14VeloxExceptionC1EPKcmS3_St17basic_string_viewIcSt11char_traitsIcEES7_S7_S7_bNS1_4TypeES7_
2  _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_
3  _ZN8facebook5velox4dwio6common16getReaderFactoryENS2_10FileFormatE
4  _ZN8facebook5velox4exec4test16TpchQueryBuilder14readFileSchemaERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_RKSt6vectorIS9_SaIS9_EE
5  _ZN8facebook5velox4exec4test16TpchQueryBuilder10initializeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
6  _Z17tpchBenchmarkMainv
7  main
8  0x0000000000029d8f
9  __libc_start_main
10 _start

*** Aborted at 1710915330 (Unix time, try 'date -d @1710915330') ***
*** Signal 6 (SIGABRT) (0x6e825) received by PID 452645 (pthread TID 0x7f618449c500) (linux TID 452645) (maybe from PID 452645, UID 0) (code: -6), stack trace: ***
    @ 0000000005a85761 _ZN5folly10symbolizer12_GLOBAL__N_113signalHandlerEiP9siginfo_tPv
                       /home/velox/velox/folly/folly/experimental/symbolizer/SignalHandler.cpp:449
    @ 000000000004251f (unknown)
    @ 00000000000969fc pthread_kill
    @ 0000000000042475 raise
    @ 00000000000287f2 abort
    @ 00000000000a2b9d (unknown)
    @ 00000000000ae20b (unknown)
    @ 00000000000ae276 _ZSt9terminatev
    @ 00000000000ae4d7 __cxa_throw
    @ 0000000005a81b2a __cxa_throw
                       /home/velox/velox/folly/folly/experimental/exception_tracer/ExceptionTracerLib.cpp:159
    @ 0000000005983111 _ZN8facebook5velox6detail14veloxCheckFailINS0_17VeloxRuntimeErrorERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRKNS1_18VeloxCheckFailArgsET0_
    @ 00000000050603e4 _ZN8facebook5velox4dwio6common16getReaderFactoryENS2_10FileFormatE
    @ 0000000001d9de40 _ZN8facebook5velox4exec4test16TpchQueryBuilder14readFileSchemaERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESB_RKSt6vectorIS9_SaIS9_EE
    @ 0000000001d9ff0c _ZN8facebook5velox4exec4test16TpchQueryBuilder10initializeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
    @ 0000000001ce0735 _Z17tpchBenchmarkMainv
    @ 0000000001cca2bd main
    @ 0000000000029d8f (unknown)
    @ 0000000000029e3f __libc_start_main
    @ 0000000001cda774 _start
Aborted

### System information

Velox System Info v0.0.2
Commit: 5e077909f912dea6902b6ddf07ec24639134e757
CMake Version: 3.22.1
System: Linux-6.5.0-21-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 11.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by majetideepak** [comment]
@Sujanhid You likely did not enable the CMake option `VELOX_ENABLE_PARQUET`. Can you confirm?

**Comment by yingsu00** [comment]
Closing for now as it seems to be a config issue
