### ISSUE TITLE
CustomTypeTest.getCustomTypeNames often failed in CI test

### ISSUE THREAD

**Issue by liujiayi771** [facebookincubator/velox#9169]
### Bug description

```
Failed to allocateBytes 6.33MB: Exceeded memory allocator limit of 512.00MB, Source: RUNTIME, ErrorCode: MEM_ALLOC_ERROR
229: [       OK ] CustomTypeTest.customType (4 ms)
229: [ RUN      ] CustomTypeTest.getCustomTypeNames
229: /root/project/velox/expression/tests/CustomTypeTest.cpp:213: Failure
229: Expected equality of these values:
229:   (std::unordered_set<std::string>{ "JSON", "HYPERLOGLOG", "TIMESTAMP WITH TIME ZONE", })
229:     Which is: { "TIMESTAMP WITH TIME ZONE", "HYPERLOGLOG", "JSON" }
229:   names
229:     Which is: { "JSON", "MATERIALIZETESTUDT", "UDT2", "TIMESTAMP WITH TIME ZONE", "HYPERLOGLOG" }
229: [  FAILED  ] CustomTypeTest.getCustomTypeNames (0 ms)
```

### System information

N/A

**Comment by liujiayi771** [comment]
@mbasmanova I have found that `MATERIALIZETESTUDT` and `UDT2` are registered in other tests. Is the failure of this UT related to the order of UT execution?

**Comment by mbasmanova** [comment]
> I have found that MATERIALIZETESTUDT and UDT2 are registered in other tests.

I'm not seeing these in Velox codebase. Are you running this test from a copy with custom changes? 

> Is the failure of this UT related to the order of UT execution?

It could be. Looks like some cleanup is missing somewhere.

**Comment by liujiayi771** [comment]
`ArrayViewTest` and `ArrayWriterTest` register UDTs, which should be unregistered after use to avoid causing instability in the test results of `CustomTypeTest.getCustomTypeNames`.
