### ISSUE TITLE
Orc reader complains unknown encoding for String column

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#922]
Hi, I tried to use Table Scan to read data from some Spark generated ORC files. But met below issue:

`Reason: buildReader string unknown encoding`

Looks like thrown from here:

    case TypeKind::VARCHAR:
      switch (static_cast<int64_t>(stripe.getEncoding(ek).kind())) {
        case proto::ColumnEncoding_Kind_DIRECT:
          return std::make_unique<SelectiveStringDirectColumnReader>(
              requestedType, stripe, scanSpec, std::move(flatMapContext));
        case proto::ColumnEncoding_Kind_DICTIONARY:
          return std::make_unique<SelectiveStringDictionaryColumnReader>(
              requestedType, stripe, scanSpec, std::move(flatMapContext));
        default:
          DWIO_RAISE("buildReader string unknown encoding");
      }

The DoubleType columns worked well. I want to know how can I generate the workable ORC files for Velox to use?

I am using below command to generate ORC files.
`df.write.mode("append").format("orc").save(ORC_path)`

Thank you in advance for the answering.

**Comment by rui-mo** [comment]
Noticed when generating ORC files, setting "spark.sql.hive.convertMetastoreOrc" to false can avoid this issue.

**Comment by mbasmanova** [comment]
CC: @yingsu00 @majetideepak
