### ISSUE TITLE
velox parquet schema is incorrect

### ISSUE THREAD

**Issue by qqibrow** [facebookincubator/velox#9242]
### Bug description

for the file attached:
actual schema: ROW<test:ARRAY<VARCHAR>>
expected schema from presto: test:array(row(test varchar))

### System information

Velox System Info v0.0.2
Commit: 1e186e548833750cdee4b95d829711ddad78aba1
CMake Version: 3.16.3
System: Linux-5.4.0-1063-aws
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

### Relevant logs

```bash
https://www.dropbox.com/scl/fi/0y1i7hzvddg128bavq2l8/test2430573504112849669parquet?rlkey=r3czlx8c4cl86u6ig9a3jh8gu&dl=0
```

**Comment by yingsu00** [comment]
Fix https://github.com/facebookincubator/velox/pull/9533

**Comment by yingsu00** [comment]
Closing it for now
