### ISSUE TITLE
Optimize json_extract function When it comes to extracting the same JSON multiple times through different JSONpaths

### ISSUE THREAD

**Issue by kuwylsr** [facebookincubator/velox#9323]
### Description

In practical application scenarios, it is often necessary to extract different keys from a JSON data. For example: 
```
select json_extract(col, jsonPath_1),json_extract(col, jsonPath_2),..., Json_extract(col, jsonPath_n) from values (json) as t (col) 
```
However, for the current implementation, we need to parse the same JSON n times and extract it, but in reality, we only need to parse it once and extract it n times. Moreover, the cost of the parsing process is significant.

**Comment by kuwylsr** [comment]
@mbasmanova cc, please

**Comment by mbasmanova** [comment]
@kuwylsr Curious, which application do you use to evaluate the queries. In Presto, a standard trick is to cast JSON to a struct first, then access individual members of the struct. Something like this:

```
presto> with u as (select cast(x as row(a bigint, c bigint)) as r from (values (json_parse('{"a": 10, "b": 20, "c": 30}'))) as t(x))
        -> select r.a, r.c from u;
 a  | c
----+----
 10 | 30
(1 row)
```

An optimizer should be able to automatically perform this transformation.

**Comment by kuwylsr** [comment]
@mbasmanova Thank you very much for your reply！The project in the school laboratory involved Json related query processing, and encounter performance issues.

**Comment by mbasmanova** [comment]
@kuwylsr I believe this issue is resolved, hence, going to close. Feel free to reopen if needed.
