### ISSUE TITLE
Missing exception handling in Parquet reader

### ISSUE THREAD

**Issue by chliang71** [facebookincubator/velox#9340]
### Bug description

Parquet read code path could throw exceptions, for example, TProtocolException is thrown [here](https://github.com/facebookincubator/velox/blob/main/velox/dwio/parquet/thrift/ParquetThriftTypes.cpp#L2998). But Parquet reader caller stack didn't seem to catch this exception. We suspect this is the cause of Velox worker crashes in some cases for us. 

### System information

Velox System Info v0.0.2
Commit: 6c9345a04a91c3bb26954fa7288557ebb5c71fd6
CMake Version: 3.27.0
System: Linux-5.10.197+
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 12.3.0
C Compiler: /usr/bin/cc
C Compiler Version: 12.3.0
CMake Prefix Path: /usr/local;/usr;/;/usr/local;/usr/local;/usr/X11R6;/usr/pkg;/opt

### Relevant logs

```bash
E20240322 08:56:00.884908  5795 Exceptions.h:69] Line: /data/1/buildkite/generic-ci-cluster-dca-pabaz-puriz/shared/buildkite-agent/builds/odin-dca11-kfs-1/uber/generic-udj/presto-native-execution/velox/velox/exec/Driver.cpp:581, Function:runInternal, Expression:  Operator::getOutput failed for [operator: TableScan, plan node ID: 0]: TProtocolException: Invalid data, Source: RUNTIME, ErrorCode: INVALID_STATE
E20240322 08:56:00.885166  5795 PrestoMain.cpp:40] *** Aborted at 1711097760 (unix time) try "date -d @1711097760" if you are using GNU date ***
E20240322 08:56:00.885206  5784 Exceptions.h:69] Line: /data/1/buildkite/generic-ci-cluster-dca-pabaz-puriz/shared/buildkite-agent/builds/odin-dca11-kfs-1/uber/generic-udj/presto-native-execution/velox/velox/exec/Driver.cpp:581, Function:runInternal, Expression:  Operator::getOutput failed for [operator: TableScan, plan node ID: 0]: TProtocolException: Invalid data, Source: RUNTIME, ErrorCode: INVALID_STATE
E20240322 08:56:00.887168  5795 PrestoMain.cpp:40] PC: @                0x0 (unknown)
E20240322 08:56:00.887238  5795 PrestoMain.cpp:40] *** SIGSEGV (@0x10f58) received by PID 44 (TID 0x7df550ff9700) from PID 69464; stack trace: ***
E20240322 08:56:00.888386  5795 PrestoMain.cpp:40]     @     0x7fb99063c21e google::(anonymous namespace)::FailureSignalHandler()
E20240322 08:56:00.889366  5795 PrestoMain.cpp:40]     @     0x7fb9908fa730 (unknown)
E20240322 08:56:00.892128  5795 PrestoMain.cpp:40]     @          0x3cff604 facebook::velox::exec::Driver::processLazyTiming()
E20240322 08:56:00.892781  5795 PrestoMain.cpp:40]     @           0x613b81 _ZN8facebook5velox4exec6Driver11runInternalERSt10shared_ptrIS2_ERS3_INS1_13BlockingStateEERS3_INS0_9RowVectorEE.cold
E20240322 08:56:00.893975  5795 PrestoMain.cpp:40]     @          0x3d03ac1 facebook::velox::exec::Driver::run()
E20240322 08:56:00.894603  5795 PrestoMain.cpp:40]     @          0x3d03c7f _ZN5folly6detail8function14FunctionTraitsIFvvEE9callSmallIZN8facebook5velox4exec6Driver7enqueueESt10shared_ptrIS9_EEUlvE_EEvRNS1_4DataE
E20240322 08:56:00.897652  5795 PrestoMain.cpp:40]     @          0x4523b76 folly::ThreadPoolExecutor::runTask()
E20240322 08:56:00.899235  5795 PrestoMain.cpp:40]     @          0x44fb455 folly::CPUThreadPoolExecutor::threadRun()
E20240322 08:56:00.902755  5795 PrestoMain.cpp:40]     @          0x45247e8 folly::detail::function::FunctionTraits<>::callSmall<>()
E20240322 08:56:00.904554  5795 PrestoMain.cpp:40]     @     0x7fb990223903 (unknown)
E20240322 08:56:00.906143  5795 PrestoMain.cpp:40]     @     0x7fb9908effa3 start_thread
E20240322 08:56:00.907539  5795 PrestoMain.cpp:40]     @     0x7fb98fee106f clone
```

**Comment by chliang71** [comment]
@yingsu00 @xiaoxmeng @Yuhta any insights?

**Comment by Yuhta** [comment]
All exceptions are caught in `Driver::runInternal`.  The stack trace you posted is a crash, not an exception

**Comment by chliang71** [comment]
Thanks for taking a look @Yuhta ! Yes it crashed which is exactly what we are trying to address. For more context, the same query triggered crash for a release build, but didn't for a debug build.  My initial speculation was it was somehow related to exception handling. But I could be wrong indeed, I'm new this code path.

I do see `Driver::runInternal` calling `CALL_OPERATOR` which created this message `Operator::getOutput failed for ...`. But the way I currently see the code, `CALL_OPERATOR` is just calling `VELOX_FAIL` [here](https://github.com/facebookincubator/velox/blob/main/velox/exec/Driver.cpp#L371), which is essentially rethrowing exception as [here](https://github.com/facebookincubator/velox/blob/main/velox/common/base/Exceptions.h#L328)? If this is true, could you shed some light on where/how the re-thrown exception is handled?

Thanks in advance.

**Comment by Yuhta** [comment]
It's not rethrow, it's creating a VeloxException which includes the stacktrace with the original exception message.  This error along should not cause crash, maybe some code path on the error handling has some problem.

**Comment by chliang71** [comment]
Had an offline sync and clarified the code path. Closing this issue.
