### ISSUE TITLE
Presto function current_date should return same date for all rows in a query

### ISSUE THREAD

**Issue by acvictor** [facebookincubator/velox#9354]
### Bug description

Presto's current_date implementation can return different result for different rows but should return the same result for all rows in a query.

### System information

Velox System Info v0.0.2
Commit: d6bf3b6a4ad7f43cef480c2bc93fdd75cdc634b8
CMake Version: 3.27.6
System: Linux-5.15.0-101-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 9.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 9.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr/local;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by mbasmanova** [comment]
@acvictor What is the use case where you see this function being evaluated on the worker by Velox and not constant-folded on the coordinator?
