### ISSUE TITLE
Incorrect result of window operation when frame bound exceeds INT32 limit and the frame is empty

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#9375]
### Description

Frames like `rows between unbounded preceding and 30000000000 preceding` should be empty, but we're setting the frame bound to 0 because k exceeds the limit of INT32 (i.e., in the example frame, 
-30000000000 < INT32_MIN). This makes the frames always contain row 0 and hence cause incorrect results.

https://github.com/facebookincubator/velox/blob/776ab24cc656d872b67939b8945602dcdbe91f24/velox/exec/Window.cpp#L314

### Error Reproduction

```
TEST_F(AggregateWindowTest, aaa) {
  auto data = makeRowVector({
      makeFlatVector<int64_t>({1, 2, 3, 4}),
  });
  auto expected = makeRowVector({
      makeFlatVector<int64_t>({1, 2, 3, 4}),
      makeNullableFlatVector<int64_t>(
          {std::nullopt, std::nullopt, std::nullopt, std::nullopt}),
  });
  WindowTestBase::testWindowFunction(
      {data},
      "sum(c0)",
      "",
      "rows between unbounded preceding and 30000000000 preceding",
      expected);
}
```

**Comment by kagamiori** [comment]
cc @aditi-pandit

**Comment by aditi-pandit** [comment]
@kagamiori : Will take a look.

**Comment by kagamiori** [comment]
Hi @aditi-pandit, if you haven't started yet, I'm going to make a fix of this issue since it blocks #9345. Please let me know if you have any thoughts.

**Comment by aditi-pandit** [comment]
@kagamiori : Apologize for the delay on this. I fell really ill last weekend, and am recovering now. Have now started looking at the PRs.

**Comment by kagamiori** [comment]
> @kagamiori : Apologize for the delay on this. I fell really ill last weekend, and am recovering now. Have now started looking at the PRs.

Hi @aditi-pandit, no worries. Please take care.
