### ISSUE TITLE
Cannot cast VARCHAR '2024-04-03 23:45' to TIMESTAMP

### ISSUE THREAD

**Issue by mbasmanova** [facebookincubator/velox#9382]
### Bug description

```
VeloxUserError:  Cannot cast VARCHAR '2024-04-03 23:45' to TIMESTAMP. Unable to parse timestamp value: "2024-04-03 23:45", expected format is (YYYY-MM-DD HH:MM:SS[.MS]) cast((presto.default.date_format(cast((intervalstart) as TIMESTAMP), %Y-%m-%d %H:%i:VARCHAR)) as TIMESTAMP)
```

This works in Presto:

```
presto> select cast('2024-04-03 23:45' as timestamp);
          _col0
-------------------------
 2024-04-03 23:45:00.000
```

CC: @svm1 @amitkdutta @kagamiori @aditi-pandit 

### System information

n/a

**Comment by mbasmanova** [comment]
CC: @pedroerp

**Comment by pedroerp** [comment]
We don't seem to support the "[]" (optional) pattern. The current code just tries to interpret and match it literally against the input string.

**Comment by pedroerp** [comment]
Seems like the "seconds" part is mandatory in our timestamp conversion logic - while at least Presto allows it to be omitted. I'll submit a PR to change that. 

An open question is whether we want to change it only for the Presto cast logic, or for all string->timestamp conversions. It feels pretty harmless so I'm leaning for the latter, but open to feedback.

**Comment by mbasmanova** [comment]
> An open question is whether we want to change it only for the Presto cast logic, or for all string->timestamp conversions. 

@rui-mo @PHILO-HE What are the semantics of cast(varchar as timestamp) in Spark?

**Comment by PHILO-HE** [comment]
> > @rui-mo @PHILO-HE What are the semantics of cast(varchar as timestamp) in Spark?
> 
> More specifically, are both:
> 
> > cast('1970-01-01 00:00:00' as timestamp);
> > cast('1970-01-01 00:00' as timestamp);
> 
> valid in Spark?

@pedroerp, @mbasmanova, I just confirmed. Yes, they are both valid in Spark. Spark allows second part is lacking, even hour or minute part can also be lacking.

**Comment by rui-mo** [comment]
Thanks for checking @PHILO-HE. Some other patterns supported in Spark are not supported in Presto, so we added a TODO in the cast hook.
E.g.
```
select cast('2015-03-18T12:03:17' as timestamp)
select cast('0001' as timestamp)
```
https://github.com/apache/spark/blob/master/sql/catalyst/src/test/scala/org/apache/spark/sql/catalyst/expressions/CastSuiteBase.scala#L127-L213

**Comment by pedroerp** [comment]
Thank you guys. I'll go ahead and merge #9401 to close this Issue, but let's follow up on other Spark-specific patterns that should be allowed.
