### ISSUE TITLE
PR's failing with Signature check failure

### ISSUE THREAD

**Issue by kgpai** [facebookincubator/velox#9424]
### Problem description

PR'S seem to be failing with signature check failure even though they dont have any changes in signatures: e.g : https://github.com/facebookincubator/velox/actions/runs/8622663090/job/23635372180?pr=9421 

### System information

N/A

### CMake log

```bash
N/A
```

**Comment by assignUser** [comment]
I have extended #9420 to fix this

**Comment by mbasmanova** [comment]
@kgpai @assignUser Is this fixed now?

**Comment by assignUser** [comment]
Yes, not sure why the bot didn't close it. Though there is a new issue now (sorry) fixed by https://github.com/facebookincubator/velox/pull/9451
