### ISSUE TITLE
convertStringToInt does not handle overflow correctly

### ISSUE THREAD

**Issue by rui-mo** [facebookincubator/velox#9442]
### Bug description

When casting string as int, for the input `'17515055537'`, convertStringToInt gives a result `335186353` instead of throwing for overflow.

https://github.com/facebookincubator/velox/blob/cef85a195bcfdee67dea16c427634d1f380287a7/velox/type/Conversions.h#L217-L223
During above calculation, 1751505553 * 10 + 7 gives 335186353, which is above 0, so the overflow check does not take effect.

### System information

Velox System Info v0.0.2
Commit: 069fb47d972bb757fda8cbb84271bd31aba586f0
CMake Version: 3.16.3
System: Linux-5.4.0-173-generic
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.1.0
C Compiler: /usr/bin/cc
C Compiler Version: 11.1.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by kgpai** [comment]
I tried this locally : 
```
int64_t res = 1751505553;
res = res * 10 + 7;  // 17515055537
  ```

I think this happens when you have result as int32_t and the initial value has already overflowed.
 
int32_t res = 1751505553; // actually res is 335186353

**Comment by rui-mo** [comment]
> T result = 0;

@kgpai Yes, T is int32_t type when casting varchar as int. Would you like to take a look on my fix https://github.com/facebookincubator/velox/pull/9443? Thanks.

**Comment by rui-mo** [comment]
> I think this happens when you have result as int32_t and the initial value has already overflowed.

@kgpai Thanks for your comment. 1751505553 is still under the max value of int32_t (2147483647), but after multiplying with 10, the result overflows.
