### ISSUE TITLE
Why we don't have ScanFilterAndProject operator in Velox?

### ISSUE THREAD

**Issue by xumingming** [facebookincubator/velox#9445]
### Description

In Presto Java there is a ScanFilterAndProject operator which do both TableScan and Filter in one operator, which I assume have the advantage of avoid materializing data which would be immediately dropped by the Filter if TableScan and Filter are not fused together.

In Velox, currently TableScan and Filter seems not fused together, e.g. TPCH Q21, Stage3, the plan is:

![image](https://github.com/facebookincubator/velox/assets/379733/f1543205-f4c1-4788-a59f-a793ded06eb6)

The data output from TableScanOperator is 16.46GB, which is immediately dropped to 10.41GB by FilterProject.

Any thoughts?

**Comment by mbasmanova** [comment]
> In Presto Java there is a ScanFilterAndProject operator which do both TableScan and Filter in one operator, which I assume have the advantage of avoid materializing data which would be immediately dropped by the Filter if TableScan and Filter are not fused together.

Actually, no. In Presto, one needs to enable hive.pushdown_filter_enabled session property (or corresponding configuration property) to push down filter into table scan. When this happens, the plan will have TableScan or ScanProject, but no ScanFilterAndProject node. Same in Prestissimo.

It looks like you may not have this enabled.

**Comment by mbasmanova** [comment]
> Do you happen to know why there will be no ScanFilter when we enable hive.pushdown_filter_enabled?

That's because the filter gets pushed down into TableScan and is handled by the connector. The main engine no longer sees the filter, just TableScan.
