### ISSUE TITLE
linux-parquet-s3 CircleCI run is failing

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#956]
The issue is with curl not being able to be installed
```
+ ./scripts/setup-adapters.sh
CentOS Linux 8 - AppStream                      859  B/s |  38  B     00:00    
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```
The root cause is that CentOS 8 is now EOL. We should move to CentOS Stream 8 and bake curl-devel into the image.

**Comment by mbasmanova** [comment]
CC: @kgpai @mshang816 Krishna, Michael, is this something you could take a look at?

**Comment by majetideepak** [comment]
@mbasmanova, @funrollloops opened a PR here https://github.com/facebookincubator/velox/pull/960 to fix this.
