### ISSUE TITLE
Enhance WindowFuzzer to support k-range and k-rows frames with column boundary

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#9572]
### Description

There are two limitations with the random frame generation in WindowFuzzer.
1. WindowFuzzer doesn't generate k-range frames.
2. WindowFuzzer doesn't generate k-rows frames with column boundaries, e.g., `ROWS BETWEEN c1 PRECEDING AND c2 FOLLOWING`.  

These frames are supported in the Window operators, so extension of WindowFuzzer to cover them is needed too.

**Comment by kagamiori** [comment]
Hi @aditi-pandit, would you help add this support to window fuzzer?

**Comment by aditi-pandit** [comment]
@minhancao

**Comment by aditi-pandit** [comment]
@kagamiori @mbasmanova : There was one more design point for k-range frames support in the WindowFuzzer. 

Window functions require special columns with pre-computed k range offsets values as per https://facebookincubator.github.io/velox/develop/window.html#k-range-frames. The WindowNode uses the range column for this special column. There isn't any history of the original "k column" which was used to compute the range value to be found.

e.g. If the original query was sum(c5) over (range between c1 preceding and c2 following) then the WindowNode doesn't know the original c1 and c2 columns. It only knows the range column as the column generated from current order_by column - c1, order_by + c2. However, when generating the query for the WindowFuzzer we need to use the original columns for the query.

So we will need to enhance WindowNode in Velox to carry forward the original k range column (or offset value), They are available as originalStartValue and originalEndValue in the Java WindowNode.

wdyt ?

**Comment by kagamiori** [comment]
Hi @aditi-pandit,

> So we will need to enhance WindowNode in Velox to carry forward the original k range column (or offset value), They are available as originalStartValue and originalEndValue in the Java WindowNode.

This sounds reasonable to me. Let's get @mbasmanova's opinion too.

**Comment by mbasmanova** [comment]
@aditi-pandit @kagamiori It is usually not a good practice to include properties that are used only in tests in production data objects. For example, including originalStartValue and originalEndValue in WindowNode would add properties that are not used in production and only used in the fuzzer. In Java, plan nodes are used for both logical and physical planning, hence, they often contain a mix of properties that only using during logical planning or only physical planning. Velox plan nodes represent physical plan nodes, hence, do not include properties needed for logical planning.

It is rarely the case that one cannot generate SQL from the physical plan, but looks like this is one of these cases. Perhaps, there can be some special code in the fuzzer to handle this.

**Comment by kagamiori** [comment]
> @aditi-pandit @kagamiori It is usually not a good practice to include properties that are used only in tests in production data objects. For example, including originalStartValue and originalEndValue in WindowNode would add properties that are not used in production and only used in the fuzzer. In Java, plan nodes are used for both logical and physical planning, hence, they often contain a mix of properties that only using during logical planning or only physical planning. Velox plan nodes represent physical plan nodes, hence, do not include properties needed for logical planning.
> 
> It is rarely the case that one cannot generate SQL from the physical plan, but looks like this is one of these cases. Perhaps, there can be some special code in the fuzzer to handle this.

Hi @mbasmanova, thank you for sharing the suggestion! 
> Perhaps, there can be some special code in the fuzzer to handle this.

Then I think one alternative implementation can be randomly generating the range frame columns for the original SQL, then using `SimpleExpressionEvaluator` to generate the frame columns for the Velox WindowNode.

For example, for an SQL frame `order by s1 asc range between c1 preceding and c2 following`, the fuzzer randomly generates the c1 and c2 vectors. Then, the fuzzer evaluates expressions `s1 - c1` and `s1 + c2` and uses their results to create the Velox WindowNode. When generating the reference SQL to send to PrestoDB, the fuzzer uses the original c1 and c2 columns.

@aditi-pandit, what do you think?

**Comment by aditi-pandit** [comment]
@kagamiori : Apologize for missing your update. Agree with Masha that we would have some fields not used in the runtime but only for this tooling.

The PrestoQueryRunner needs to generate the windowFrame here :
https://github.com/facebookincubator/velox/blob/main/velox/exec/fuzzer/PrestoQueryRunner.cpp#L407

At this point Velox WindowNode would have the columns for (s1 - c1) and (s1 + c2) in frameStart and frameEnd value but we want to generate c1 preceding and c2 following. We have completely lost track of c1 and c2 at this point.

An option I feel is to maybe have a PrestoQueryRunnerContext class that can capture some metadata for each PlanNode that can be used during SQL query generation. The WindowFuzzer would build both the WindowNode and the RunnerContext class. 

This has been running in my mind... Though what do you think of this change ? Would this mean a lot of changes to Fuzzer framework. We could try to do something isolated to WindowNode if that is the only node with this behavior.

**Comment by kagamiori** [comment]
> @kagamiori : Apologize for missing your update. Agree with Masha that we would have some fields not used in the runtime but only for this tooling.
> 
> The PrestoQueryRunner needs to generate the windowFrame here : https://github.com/facebookincubator/velox/blob/main/velox/exec/fuzzer/PrestoQueryRunner.cpp#L407
> 
> At this point Velox WindowNode would have the columns for (s1 - c1) and (s1 + c2) in frameStart and frameEnd value but we want to generate c1 preceding and c2 following. We have completely lost track of c1 and c2 at this point.
> 
> An option I feel is to maybe have a PrestoQueryRunnerContext class that can capture some metadata for each PlanNode that can be used during SQL query generation. The WindowFuzzer would build both the WindowNode and the RunnerContext class.
> 
> This has been running in my mind... Though what do you think of this change ? Would this mean a lot of changes to Fuzzer framework. We could try to do something isolated to WindowNode if that is the only node with this behavior.

Hi @aditi-pandit, yes, we need to give the original c1 and c2 columns to PrestoQueryRunner, but we may not have to make many changes to PrestoQueryRunner. In WindowFuzzer, we call `AggregationFuzzerBase::computeReferenceResults()` to invoke PrestoQueryRunner to get Presto's result. This computeReferenceResults() has two steps: It first gets the SQL string for the given WindowNode. This step doesn't use the input vectors. It then calls `PrestoQueryRunner::execute()` to write the input vectors to a file and sends the SQL string to Presto to execute. This second step doesn't use WindowNode. In the WindowNode, the frame boundary column names are "c1" and "c2". So basically, we can use the same WindowNode for both Velox execution and Presto SQL generation. But when sending the input vectors to them, we can give Velox the actual vectors of (s1 - c1) and (s1 + c2) as "c1" and "c2", and give the original c1 and c2 vectors to PrestoQueryRunner::execute() as "c1" and "c2". I think this could solve our problem. Please let me know if you see anything missing in this approach.

**Comment by aditi-pandit** [comment]
@kagamiori : Ah..I see what you are trying to do. Basically using the same column name for different contents that will evaluate the same way. The only issue I see here is that post the Window calculation you might have to skip the c1 and c2 columns in the validation, as they now have different contents. The WindowNode outputs all input columns as passthrough, and so adding a ProjectNode that skips c1 and c2 to the Window plan should suffice.

**Comment by kagamiori** [comment]
> @kagamiori : Ah..I see what you are trying to do. Basically using the same column name for different contents that will evaluate the same way. The only issue I see here is that post the Window calculation you might have to skip the c1 and c2 columns in the validation, as they now have different contents. The WindowNode outputs all input columns as passthrough, and so adding a ProjectNode that skips c1 and c2 to the Window plan should suffice.

Hi @aditi-pandit, that's a good point!
> The WindowNode outputs all input columns as passthrough, and so adding a ProjectNode that skips c1 and c2 to the Window plan should suffice.
This sounds good to me.
