### ISSUE TITLE
Parquet reading failed to decompress LZO files

### ISSUE THREAD

**Issue by yingsu00** [facebookincubator/velox#9618]
### Bug description

Query should succeed but failed with "decompression failed, decompressedSize is not equal to remainingOutputSize" error. The parquet file that can reproduce the error is [lzo.zip](https://github.com/facebookincubator/velox/files/15057270/lzo.zip)

### System information

N/A

### Relevant logs

```bash
To be found
```

**Comment by nmahadevuni** [comment]
@8dukongjian Can you please share how this lzo.zip data was created?

**Comment by majetideepak** [comment]
I have a fix for this here https://github.com/facebookincubator/velox/pull/10123
I need to find a parquet reader that supports Lzo to verify the results.

**Comment by majetideepak** [comment]
Verified the results via Presto.
