### ISSUE TITLE
Add expm1 Spark function

### ISSUE THREAD

**Issue by Donvi** [facebookincubator/velox#9716]
### Bug description

1. We find the function [expm1](https://spark.apache.org/docs/latest/api/sql/index.html#expm1), but no registration and implementation
2. The function is registered and executed with the native way 
3. As the [std::expm1](https://en.cppreference.com/w/cpp/numeric/math/expm1) mentioned, it can provide more accuracy for the returned value. So current proposal way is to used the std lib way.

### System information

Velox System Info v0.0.2
Commit: 4bf0fa0c9ae93b2f944548f93f4d792e49d67dfa
CMake Version: 3.22.1
System: Linux-5.15.146.1-microsoft-standard-WSL2
Arch: x86_64
C++ Compiler: /usr/bin/c++
C++ Compiler Version: 11.4.0
C Compiler: /usr/bin/cc
C Compiler Version: 11.4.0
CMake Prefix Path: /usr/local;/usr;/;/usr;/usr/local;/usr/X11R6;/usr/pkg;/opt

**Comment by mbasmanova** [comment]
CC: @rui-mo @PHILO-HE

**Comment by rui-mo** [comment]
It seems this PR is related https://github.com/facebookincubator/velox/pull/9667.

**Comment by Donvi** [comment]
> It seems this PR is related fix.

Right. It's fixed by #9667
