### ISSUE TITLE
`avg` function doesnt work on `real` type

### ISSUE THREAD

**Issue by frankobe** [facebookincubator/velox#974]
`avg` on `Real` column like `select avg(sr_return_amt) from store_returns` in tpcds leads to following exception

```
VeloxRuntimeError: type->childAt(0)->kind() == TypeKind::DOUBLE (BIGINT vs. DOUBLE) Input type for final aggregation must be (sum:double, count:bigint) struct

```

**Comment by mbasmanova** [comment]
CC: @spershin

**Comment by spershin** [comment]
We are trying to take care of this (along with other issues) at the moment.

**Comment by frankobe** [comment]
@spershin I submit my fix for this issue in https://github.com/facebookincubator/velox/pull/1087. Please take your time to review it as it blocks TPC-DS now

**Comment by mbasmanova** [comment]
@spershin Sergey, would you summarize what's the current plan to address this and similar problems?

**Comment by aditi-pandit** [comment]
Hi Frank,

  I had left a comment on this PR that might have got lost. 

  Another approach to this solution could be to handle the order of the arguments in the function VeloxExprConverter::toVeloxExpr in presto_cpp. Is that solution not feasible ? That fix might be cleaner than adding these new signatures into Velox.
