### ISSUE TITLE
Fuzzer jobs are blocked due to lack resource to execute

### ISSUE THREAD

**Issue by Yohahaha** [facebookincubator/velox#9744]
### Description

CI is red due to fuzzer jobs are broken due to lack resources.

https://github.com/facebookincubator/velox/actions/runs/8995033151/job/24709371527
https://github.com/facebookincubator/velox/actions/runs/8996615537/job/24713399665

**Comment by mbasmanova** [comment]
CC: @kgpai @assignUser @majetideepak

**Comment by assignUser** [comment]
It looks like there is only 1 16-core runner it seems like the  OSS team set concurrency for that runner to 1? @mbasmanova @kgpai could either of you check? (https://docs.github.com/en/actions/using-github-hosted-runners/about-larger-runners/about-larger-runners#autoscaling-larger-runners)

**Comment by kgpai** [comment]
Thanks @assignUser , Let me reach out to our OSS Team

**Comment by kgpai** [comment]
Looks like its because the runner names changed recently : https://www.internalfb.com/intern/opensource/ci/github-actions/runners 

Just need to rename it to 16-core-ubuntu
