### ISSUE TITLE
Different results of approx_distinct between Velox and Presto-Java

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#9761]
### Description

Velox and Presto returns different results with the following query.

Velox:
```
TEST_F(ApproxDistinctTest, aaa) {
  auto input = makeRowVector({
      makeFlatVector<int32_t>(
          {219716167, 422847510, 489801358, 1958888195, 606515184, 851641245}),
      makeConstant<double>(0.18802535624105074, 6),
  });
  auto expected = makeRowVector({
      makeConstant<int64_t>(5, 1),
  });

  auto plan = PlanBuilder()
                  .values({input})
                  .singleAggregation({}, {"approx_distinct(c0, c1)"})
                  .planNode();
  AssertQueryBuilder builder(plan);
  builder.assertResults(expected);  // -- Velox actual result is 3.
}
```

Presto:
```
SELECT
    APPROX_DISTINCT(c0, c1)
FROM (
    VALUES
        (219716167, 0.18802535624105074),
        (422847510, 0.18802535624105074),
        (489801358, 0.18802535624105074),
        (1958888195, 0.18802535624105074),
        (606515184, 0.18802535624105074),
        (851641245, 0.18802535624105074)
) t(c0, c1);  -- Presto returns 5.
```

For this query, both Velox and Presto use dense HLL, so their results should match. During investigation, I found that Velox and Presto got different hash values on the same input, which leads to differences at subsequent calculations based on the hash values. 

### Error Reproduction

The mismatch can be reproduced via the unit test and query given above.

**Comment by mbasmanova** [comment]
>  I found that Velox and Presto got different hash values on the same input

Would you share the input value and Velox and Presto hashes for that value?

**Comment by kagamiori** [comment]
> > I found that Velox and Presto got different hash values on the same input
> 
> Would you share the input value and Velox and Presto hashes for that value?

Yes, for example, for the input value `219716167`,  Velox gets a hash value `1954281567766450499` (uint64_t), while Presto gets a hash value `-2225388838451473260` (long).

**Comment by kagamiori** [comment]
Velox result matches Presto on the following query with small input values.
```
SELECT
    APPROX_DISTINCT(c0, c1)
FROM (
    VALUES
        (1, 0.18802535624105074),
        (2, 0.18802535624105074),
        (3, 0.18802535624105074),
        (4, 0.18802535624105074),
        (5, 0.18802535624105074),
        (6, 0.18802535624105074)
) t(c0, c1); -- both return 5.
```

**Comment by kagamiori** [comment]
Discussed offline. Velox just uses a different hash function from Presto. This hash function sometimes performs better and sometimes performs worse than Presto. There is no clear evidence that one hash function is better than the other. So we won't fix Velox to align with Presto.
