### ISSUE TITLE
Sharp edge: supporting libfmt v6

### ISSUE THREAD

**Issue by wesm** [facebookincubator/velox#977]
Since https://github.com/facebookincubator/velox/commit/bc7b6fad728fdbfa3abde01664d106f30c320bbc#diff-d19cb76f09197634b6aff9106b2a0d660d49e6fab00fc7456fa528bc30c68dea, compiling with libfmt 6.x (for example what's in Ubuntu 20.04) doesn't work anymore (looks like this https://gist.github.com/wesm/db7738cfe3f7b4604652725616539a4d)

Since the version of the library is available in `FMT_VERSION`, e.g.

```
// The fmt library version in the form major * 10000 + minor * 100 + patch.
#define FMT_VERSION 60102
```

it might be kind to developers to provide a graceful fallback when they haven't installed a newer libfmt on their system

**Comment by mbasmanova** [comment]
CC: @kgpai
