### ISSUE TITLE
Merge Join generating invalid vector

### ISSUE THREAD

**Issue by pedroerp** [facebookincubator/velox#9771]
### Bug description

Depending on the output buffer alignment, the existing merge join code tries to create an invalid dictionary (more rows than indices), if left join and filters are enabled. 

To reproduce, simply set the output buffer size to 1000 here:

https://github.com/facebookincubator/velox/blob/main/velox/exec/tests/MergeJoinTest.cpp#L580

(replace the `plan` parameter to ` makeCursorParameters(plan, 1000)`)

### System information

any

### Relevant logs

```bash
just run the unit test
```

**Comment by mbasmanova** [comment]
This looks like a problem similar to https://github.com/facebookincubator/velox/pull/6680

CC: @kevinwilfong @xiaoxmeng

**Comment by pedroerp** [comment]
Fixed in https://github.com/facebookincubator/velox/pull/9862
