### ISSUE TITLE
Circle CI job for linux-build failing intermittently

### ISSUE THREAD

**Issue by karteekmurthys** [facebookincubator/velox#980]
Linux-build: 

https://app.circleci.com/pipelines/github/facebookincubator/velox/4664/workflows/a8301152-13ed-4376-bb45-31045efecf23/jobs/23086

**velox_exec_test was failing and velox_functional_test failed intermittently.**

```
118: [  FAILED  ] DriverTest.cancel
118: [  FAILED  ] LocalPartitionTest.maxBufferSizeGather
118: 
118:  2 FAILED TESTS
121/121 Test #118: velox_exec_test ......................................***Failed  201.39 sec
[==========] Running 241 tests from 29 test suites.

```
Commands used for running tests on docker container:

```
make release EXTRA_CMAKE_FLAGS=" -DVELOX_ENABLE_PARQUET=ON -DVELOX_ENABLE_S3=ON " AWSSDK_ROOT_DIR=~/adapter-deps/install
ctest -j 16 -VV --output-on-failure
```

**Comment by kagamiori** [comment]
Hi Karteek, Thank you for reporting this issue! `DriverTest.cancel` was a flaky test and it has been fixed in https://github.com/facebookincubator/velox/pull/982 last week. Could you try rebasing to the latest main and let us know if there is still any problem?

**Comment by majetideepak** [comment]
The main branch looks good.
