### ISSUE TITLE
Wrong result while Iceberg table read with Positional Delete

### ISSUE THREAD

**Issue by agrawalreetika** [facebookincubator/velox#9856]
### Bug description

When we have a data file & position delete file with multiple rowgroups then the result count is not coming right.
So if I try to **DELETE all the rows** from the original table, and try to select count from the resulted table it returns a non-zero count.

**Steps To Reproduce -**
Execution Engine - Presto
Data Format - PARQUET

```
presto> set session iceberg.parquet_writer_block_size='2MB';

presto> CREATE TABLE customer_v2 WITH (format = 'PARQUET') AS SELECT * FROM tpch.sf1.customer;
presto> select count(*), max(custkey), min(custkey) from  customer_v2;
 _col0  | _col1  | _col2 
--------+--------+-------
 150000 | 150000 |     1 
(1 row)

presto> DELETE FROM customer_v2 WHERE custkey >=1 AND custkey<=150000; 
```

Current Query Output -
```
presto> select count(*) from customer_v2;
 _col0 
-------
 57413 
(1 row)
```

Expected Query Output -
```
presto> select count(*) from customer_v2;
 _col0 
-------
0
(1 row)
```

### System information

NA

**Comment by Yuhta** [comment]
@yingsu00 Can you take a look?

The count should be subtracted here, make sure the bitmask is created correctly:
https://github.com/facebookincubator/velox/blob/e8244c2e0fd0fcdb80372b126859493c57382ef0/velox/dwio/common/SelectiveStructColumnReader.cpp#L64

**Comment by yingsu00** [comment]
Thanks @Yuhta for looking into this. I will work on the fix.
