### ISSUE TITLE
Velox parquet scan fail when select row index column before data column

### ISSUE THREAD

**Issue by gaoyangxiaozhu** [facebookincubator/velox#9867]
### Bug description

below query 
```
select _tmp_row_index_column,  a, b from table
```
would fail if `_tmp_row_index_column` be marked to `kRowIndex` column.

In summary, all scan would fail if `kRowIndex` type column is selected before data column.

**Comment by gaoyangxiaozhu** [comment]
@Yuhta FYI

**Comment by yingsu00** [comment]
It seems this issue has been fixed by https://github.com/facebookincubator/velox/pull/9866. Closing for now.
