### ISSUE TITLE
Move to Centos9 Stream as Centos8 Stream is going EOL 2024-05-31

### ISSUE THREAD

**Issue by majetideepak** [facebookincubator/velox#9879]
### Description

As mentioned below, Centos8 Stream is going EOL on 2024-05-31. 
We must move our build and CI support to Centos 9 Stream.
https://www.centos.org/centos-stream/

**Comment by majetideepak** [comment]
CC: @kgpai, @assignUser

**Comment by majetideepak** [comment]
CC:  @czentgr

**Comment by zhztheplayer** [comment]
Is it possible to move to community-maintained centos 8 distribution? E.g., AlmaLinux https://hub.docker.com/_/almalinux

**Comment by majetideepak** [comment]
@zhztheplayer The benefit of Centos9 stream is also that it comes with GCC12. Centos Stream is a popular distro that we must support.
