### ISSUE TITLE
velox_test_util is being used in non-test targets

### ISSUE THREAD

**Issue by assignUser** [facebookincubator/velox#9933]
### Description

I noticed that `velox_test_util` is being used in the following non-test targets:
- velox_common_base
- velox_exec
- velox_memory
- velox_time

I think we should either rename/refactor the target  for use outside of tests or remove it from non-test targets.

**Comment by pedroerp** [comment]
Sounds reasonable to me. Do we know what inside `velox_test_util` is used by these targets?

**Comment by assignUser** [comment]
It's mostly `TestValue.h`:
```
/// The test facility used to inject callback hook in production execution point
/// to get, change and verify various internal execution state for unit test.
/// The hook injected in production code path will be opt out in release build
/// and only be executed in debug build. Please follow the example in
/// TestValueTest.cpp for use.
```
So it seems to be intentional after all, if you think that's fine feel free to close the issue.

**Comment by mbasmanova** [comment]
CC: @xiaoxmeng 

Maybe we could extract TestValue into its own target.

**Comment by majetideepak** [comment]
`add_library(velox_test_util ScopedTestTime.cpp TestValue.cpp)`
There is only one other source file linked with this target. We could make each of the sources an OBJECT library since they are never used together anyway.

**Comment by assignUser** [comment]
I initially thought it was an accidental inclusion in non-test targets and a pure test thing but it seems it is intentional and makes sure no extraneous code is included in a release build. I assume there is no way to do the tests this enables without it so it seems fine? The target itself is already small and not within `/tests` so not an issue imo.

Sorry for the confusion :)
