### ISSUE TITLE
Unit tests S3FileSystemTest.viaRegistry and S3FileSystemTest.fileHandle are failing at merge time.

### ISSUE THREAD

**Issue by kagamiori** [facebookincubator/velox#9958]
### Bug description

These two unit tests are failing in CI at merge time.
https://github.com/facebookincubator/velox/actions/runs/9264077299/job/25483530209
https://github.com/facebookincubator/velox/actions/runs/9264287643/job/25484131434

### System information

CI

**Comment by mbasmanova** [comment]
CC: @majetideepak

**Comment by kagamiori** [comment]
cc @xiaoxmeng

**Comment by majetideepak** [comment]
@kagamiori There seems to be a fix here https://github.com/facebookincubator/velox/pull/9950

**Comment by majetideepak** [comment]
Resolved with https://github.com/facebookincubator/velox/pull/9959
